// discord_app/modules/parent_tools/native/FamilyCenterDataConfirmation.tsx
import "XSmallIcon";
import jsxProd from "jsxProd";

let c3;
let c4;
const require = arg1;
function RowGroup(children) {
  const rows = children.rows;
  let obj = { spacing: 8, children: null };
  const items = [callback(require("../../../design/components/Text/native/Text.tsx") /* Text */.Text, { accessibilityRole: "header", variant: "text-sm/semibold", color: "text-muted", children: children.title }), ];
  obj = { hasIcons: true, children: null };
  obj[1] = rows.map((header) => {
    let IconComponent;
    let description;
    let negative;
    header = header.header;
    ({ description, IconComponent, negative } = header);
    const obj = { label: header, subLabel: description, icon: null };
    let str = "default";
    if (true === negative) {
      str = "text-status-dnd";
    }
    obj[2] = closure_3(callback(5315).TableRow.Icon, { variant: str, IconComponent });
    return closure_3(callback(5315).TableRow, obj, header);
  });
  items[1] = callback(require("../../../design/components/TableRow/native/TableRowGroup.native.tsx") /* TableRowGroupTitle */.TableRowGroup, obj);
  obj[1] = items;
  return callback2(require("../../../design/components/Stack/native/Stack.native.tsx") /* Stack */.Stack, obj);
}
({ jsx: c3, jsxs: c4 } = jsxProd);
const result = require("Stack").fileFinishedImporting("modules/parent_tools/native/FamilyCenterDataConfirmation.tsx");

export default function FamilyCenterDataConfirmation() {
  const intl = require("../../../intl/index.native.tsx") /* getSystemLocale */.intl;
  const intl2 = require("../../../intl/index.native.tsx") /* getSystemLocale */.intl;
  const stringResult = intl.string(require("../FamilyCenter.messages.js").CI1Env);
  const intl3 = require("../../../intl/index.native.tsx") /* getSystemLocale */.intl;
  const stringResult1 = intl2.string(require("../FamilyCenter.messages.js")["ksze+o"]);
  let obj = require("../hooks/useAgeSpecificText.tsx") /* useAgeSpecificText */;
  const intl4 = require("../../../intl/index.native.tsx") /* getSystemLocale */.intl;
  const stringResult2 = intl3.string(require("../FamilyCenter.messages.js")["n73g+V"]);
  const intl5 = require("../../../intl/index.native.tsx") /* getSystemLocale */.intl;
  const ageSpecificText = obj.useAgeSpecificText(intl4.string(require("../FamilyCenter.messages.js")["5x3taM"]), intl5.string(require("../FamilyCenter.messages.js").WZwGFX));
  let obj1 = require("../hooks/useAgeSpecificText.tsx") /* useAgeSpecificText */;
  const intl6 = require("../../../intl/index.native.tsx") /* getSystemLocale */.intl;
  const stringResult3 = intl4.string(require("../FamilyCenter.messages.js")["5x3taM"]);
  const intl7 = require("../../../intl/index.native.tsx") /* getSystemLocale */.intl;
  const ageSpecificText1 = obj1.useAgeSpecificText(intl6.string(require("../FamilyCenter.messages.js").FcKkcr), intl7.string(require("../FamilyCenter.messages.js").PQtDFk));
  let obj2 = require("../hooks/useAgeSpecificText.tsx") /* useAgeSpecificText */;
  const intl8 = require("../../../intl/index.native.tsx") /* getSystemLocale */.intl;
  const stringResult4 = intl6.string(require("../FamilyCenter.messages.js").FcKkcr);
  const intl9 = require("../../../intl/index.native.tsx") /* getSystemLocale */.intl;
  const ageSpecificText2 = obj2.useAgeSpecificText(intl8.string(require("../FamilyCenter.messages.js")["dES/2r"]), intl9.string(require("../FamilyCenter.messages.js").ep6mdN));
  let obj3 = require("../hooks/useAgeSpecificText.tsx") /* useAgeSpecificText */;
  const intl10 = require("../../../intl/index.native.tsx") /* getSystemLocale */.intl;
  const stringResult5 = intl8.string(require("../FamilyCenter.messages.js")["dES/2r"]);
  const intl11 = require("../../../intl/index.native.tsx") /* getSystemLocale */.intl;
  const ageSpecificText3 = obj3.useAgeSpecificText(intl10.string(require("../FamilyCenter.messages.js").GWPcQg), intl11.string(require("../FamilyCenter.messages.js").yFnKIg));
  let obj4 = require("../hooks/useAgeSpecificText.tsx") /* useAgeSpecificText */;
  const intl12 = require("../../../intl/index.native.tsx") /* getSystemLocale */.intl;
  const stringResult6 = intl10.string(require("../FamilyCenter.messages.js").GWPcQg);
  const intl13 = require("../../../intl/index.native.tsx") /* getSystemLocale */.intl;
  const ageSpecificText4 = obj4.useAgeSpecificText(intl12.string(require("../FamilyCenter.messages.js")["30+sih"]), intl13.string(require("../FamilyCenter.messages.js")["0cuLn1"]));
  let obj5 = require("../hooks/useAgeSpecificText.tsx") /* useAgeSpecificText */;
  const intl14 = require("../../../intl/index.native.tsx") /* getSystemLocale */.intl;
  const stringResult7 = intl12.string(require("../FamilyCenter.messages.js")["30+sih"]);
  const intl15 = require("../../../intl/index.native.tsx") /* getSystemLocale */.intl;
  const ageSpecificText5 = obj5.useAgeSpecificText(intl14.string(require("../FamilyCenter.messages.js").tHTyRh), intl15.string(require("../FamilyCenter.messages.js").TeNlMb));
  let obj6 = require("../hooks/useAgeSpecificText.tsx") /* useAgeSpecificText */;
  const intl16 = require("../../../intl/index.native.tsx") /* getSystemLocale */.intl;
  const stringResult8 = intl14.string(require("../FamilyCenter.messages.js").tHTyRh);
  const intl17 = require("../../../intl/index.native.tsx") /* getSystemLocale */.intl;
  const ageSpecificText6 = obj6.useAgeSpecificText(intl16.string(require("../FamilyCenter.messages.js").PfveQ6), intl17.string(require("../FamilyCenter.messages.js")["f7ofm/"]));
  let obj7 = require("../hooks/useAgeSpecificText.tsx") /* useAgeSpecificText */;
  const intl18 = require("../../../intl/index.native.tsx") /* getSystemLocale */.intl;
  const stringResult9 = intl16.string(require("../FamilyCenter.messages.js").PfveQ6);
  const intl19 = require("../../../intl/index.native.tsx") /* getSystemLocale */.intl;
  const ageSpecificText7 = obj7.useAgeSpecificText(intl18.string(require("../FamilyCenter.messages.js").MKeCj3), intl19.string(require("../FamilyCenter.messages.js").HdcGGl));
  let obj8 = require("../hooks/useAgeSpecificText.tsx") /* useAgeSpecificText */;
  const intl20 = require("../../../intl/index.native.tsx") /* getSystemLocale */.intl;
  const stringResult10 = intl18.string(require("../FamilyCenter.messages.js").MKeCj3);
  const intl21 = require("../../../intl/index.native.tsx") /* getSystemLocale */.intl;
  const ageSpecificText8 = obj8.useAgeSpecificText(intl20.string(require("../FamilyCenter.messages.js").wZejZr), intl21.string(require("../FamilyCenter.messages.js").tdgcf1));
  let obj9 = require("../hooks/useAgeSpecificText.tsx") /* useAgeSpecificText */;
  const intl22 = require("../../../intl/index.native.tsx") /* getSystemLocale */.intl;
  const stringResult11 = intl20.string(require("../FamilyCenter.messages.js").wZejZr);
  const intl23 = require("../../../intl/index.native.tsx") /* getSystemLocale */.intl;
  const ageSpecificText9 = obj9.useAgeSpecificText(intl22.string(require("../FamilyCenter.messages.js").ASf7XN), intl23.string(require("../FamilyCenter.messages.js")["82y87X"]));
  let obj10 = require("../hooks/useAgeSpecificText.tsx") /* useAgeSpecificText */;
  const intl24 = require("../../../intl/index.native.tsx") /* getSystemLocale */.intl;
  const stringResult12 = intl22.string(require("../FamilyCenter.messages.js").ASf7XN);
  const intl25 = require("../../../intl/index.native.tsx") /* getSystemLocale */.intl;
  obj = { header: null, description: null, IconComponent: null };
  const ageSpecificText10 = obj10.useAgeSpecificText(intl24.string(require("../FamilyCenter.messages.js")["0QDVFN"]), intl25.string(require("../FamilyCenter.messages.js")["1xBHHV"]));
  const intl26 = require("../../../intl/index.native.tsx") /* getSystemLocale */.intl;
  obj[0] = intl26.string(require("../FamilyCenter.messages.js")["/zMYZX"]);
  obj[1] = ageSpecificText;
  obj[2] = require("../../../design/components/Icon/native/redesign/generated/UserPlusIcon.tsx") /* UserPlusIcon */.UserPlusIcon;
  const items = [obj, , , , , , ];
  obj = { header: null, description: null, IconComponent: null };
  const intl27 = require("../../../intl/index.native.tsx") /* getSystemLocale */.intl;
  obj[0] = intl27.string(require("../FamilyCenter.messages.js")["44NEx6"]);
  obj[1] = ageSpecificText1;
  obj[2] = require("../../../design/components/Icon/native/redesign/generated/ServerIcon.tsx") /* ServerIcon */.ServerIcon;
  items[1] = obj;
  obj1 = { header: null, description: null, IconComponent: null };
  const intl28 = require("../../../intl/index.native.tsx") /* getSystemLocale */.intl;
  obj1[0] = intl28.string(require("../FamilyCenter.messages.js")["Z3G+8h"]);
  const intl29 = require("../../../intl/index.native.tsx") /* getSystemLocale */.intl;
  obj1[1] = intl29.string(require("../FamilyCenter.messages.js").KBgArX);
  obj1[2] = require("../../../design/components/Icon/native/redesign/generated/ForumIcon.tsx") /* ForumIcon */.ForumIcon;
  items[2] = obj1;
  obj2 = { header: null, description: null, IconComponent: null };
  const intl30 = require("../../../intl/index.native.tsx") /* getSystemLocale */.intl;
  obj2[0] = intl30.string(require("../FamilyCenter.messages.js").GNs2ZH);
  const intl31 = require("../../../intl/index.native.tsx") /* getSystemLocale */.intl;
  obj2[1] = intl31.string(require("../FamilyCenter.messages.js").Ief2xc);
  obj2[2] = require("../../../design/components/Icon/native/redesign/generated/PhoneIcon.tsx") /* PhoneIcon */.PhoneIcon;
  items[3] = obj2;
  obj3 = { header: null, description: null, IconComponent: null };
  const intl32 = require("../../../intl/index.native.tsx") /* getSystemLocale */.intl;
  obj3[0] = intl32.string(require("../FamilyCenter.messages.js").PjM3r5);
  obj3[1] = ageSpecificText2;
  obj3[2] = require("../../../design/components/Icon/native/redesign/generated/CreditCardIcon.tsx") /* CreditCardIcon */.CreditCardIcon;
  items[4] = obj3;
  obj4 = { header: null, description: null, IconComponent: null };
  const intl33 = require("../../../intl/index.native.tsx") /* getSystemLocale */.intl;
  obj4[0] = intl33.string(require("../FamilyCenter.messages.js").Fv3n8L);
  obj4[1] = ageSpecificText3;
  obj4[2] = require("../../../design/components/Icon/native/redesign/generated/GiftIcon.tsx") /* GiftIcon */.GiftIcon;
  items[5] = obj4;
  obj5 = { header: ageSpecificText4, description: ageSpecificText5, IconComponent: require("../../../design/components/Icon/native/redesign/generated/FlagIcon.tsx") /* FlagIcon */.FlagIcon };
  items[6] = obj5;
  obj6 = { header: null, description: null, IconComponent: null };
  const intl34 = require("../../../intl/index.native.tsx") /* getSystemLocale */.intl;
  obj6[0] = intl34.string(require("../FamilyCenter.messages.js").kyT6pZ);
  obj6[1] = ageSpecificText6;
  obj6[2] = require("../../../design/components/Icon/native/redesign/generated/ClockIcon.tsx") /* ClockIcon */.ClockIcon;
  const items1 = [obj6, , ];
  obj7 = { header: null, description: null, IconComponent: null };
  const intl35 = require("../../../intl/index.native.tsx") /* getSystemLocale */.intl;
  obj7[0] = intl35.string(require("../FamilyCenter.messages.js")["52ld7c"]);
  obj7[1] = ageSpecificText7;
  obj7[2] = require("../../../design/components/Icon/native/redesign/generated/PiggyBankIcon.tsx") /* PiggyBankIcon */.PiggyBankIcon;
  items1[1] = obj7;
  obj8 = { header: null, description: null, IconComponent: null };
  const intl36 = require("../../../intl/index.native.tsx") /* getSystemLocale */.intl;
  obj8[0] = intl36.string(require("../FamilyCenter.messages.js").UCuHM8);
  obj8[1] = ageSpecificText8;
  obj8[2] = require("../../../design/components/Icon/native/redesign/generated/SettingsIcon.tsx") /* SettingsIcon */.SettingsIcon;
  items1[2] = obj8;
  obj9 = { spacing: 24, children: null };
  const items2 = [callback(RowGroup, { title: stringResult, rows: items }), callback(RowGroup, { title: stringResult1, rows: items1 }), ];
  obj10 = { title: stringResult2, rows: null };
  const stringResult13 = intl24.string(require("../FamilyCenter.messages.js")["0QDVFN"]);
  const items3 = [{ header: ageSpecificText9, description: ageSpecificText10, IconComponent: require("../../../design/components/Icon/native/redesign/generated/XSmallIcon.tsx") /* XSmallIcon */.XSmallIcon, negative: true }];
  obj10[1] = items3;
  items2[2] = callback(RowGroup, obj10);
  obj9[1] = items2;
  return callback2(require("../../../design/components/Stack/native/Stack.native.tsx") /* Stack */.Stack, obj9);
};