// discord_app/modules/parent_tools/native/FamilyCenterDataConfirmation.tsx
import "XSmallIcon";
import jsxProd from "jsxProd";
import { ClockIcon } from "../../../design/components/Icon/native/redesign/generated/ClockIcon.tsx";
import { CreditCardIcon } from "../../../design/components/Icon/native/redesign/generated/CreditCardIcon.tsx";
import { FlagIcon } from "../../../design/components/Icon/native/redesign/generated/FlagIcon.tsx";
import { ForumIcon } from "../../../design/components/Icon/native/redesign/generated/ForumIcon.tsx";
import { GiftIcon } from "../../../design/components/Icon/native/redesign/generated/GiftIcon.tsx";
import { PhoneIcon } from "../../../design/components/Icon/native/redesign/generated/PhoneIcon.tsx";
import { PiggyBankIcon } from "../../../design/components/Icon/native/redesign/generated/PiggyBankIcon.tsx";
import { ServerIcon } from "../../../design/components/Icon/native/redesign/generated/ServerIcon.tsx";
import { SettingsIcon } from "../../../design/components/Icon/native/redesign/generated/SettingsIcon.tsx";
import { UserPlusIcon } from "../../../design/components/Icon/native/redesign/generated/UserPlusIcon.tsx";
import { XSmallIcon } from "../../../design/components/Icon/native/redesign/generated/XSmallIcon.tsx";
import { Stack } from "../../../design/components/Stack/native/Stack.native.tsx";
import { TableRowGroupTitle } from "../../../design/components/TableRow/native/TableRowGroup.native.tsx";
import { Text } from "../../../design/components/Text/native/Text.tsx";
import { getSystemLocale } from "../../../intl/index.native.tsx";
import { messagesProxy } from "../FamilyCenter.messages.js";
import { useAgeSpecificText } from "../hooks/useAgeSpecificText.tsx";

let c3;
let c4;
const require = arg1;
function RowGroup(children) {
  const rows = children.rows;
  let obj = { spacing: 8, children: null };
  const items = [callback(Text.Text, { accessibilityRole: "header", variant: "text-sm/semibold", color: "text-muted", children: children.title }), ];
  obj = { hasIcons: true, children: null };
  obj[1] = rows.map((header) => {
    let IconComponent;
    let description;
    let negative;
    header = header.header;
    ({ description, IconComponent, negative } = header);
    const obj = { label: header, subLabel: description, icon: null };
    let str = "default";
    if (true === negative) {
      str = "text-status-dnd";
    }
    obj[2] = closure_3(callback(5413).TableRow.Icon, { variant: str, IconComponent });
    return closure_3(callback(5413).TableRow, obj, header);
  });
  items[1] = callback(TableRowGroupTitle.TableRowGroup, obj);
  obj[1] = items;
  return callback2(Stack.Stack, obj);
}
({ jsx: c3, jsxs: c4 } = jsxProd);
const result = require("Stack").fileFinishedImporting("modules/parent_tools/native/FamilyCenterDataConfirmation.tsx");

export default function FamilyCenterDataConfirmation() {
  const intl = getSystemLocale.intl;
  const intl2 = getSystemLocale.intl;
  const stringResult = intl.string(messagesProxy.CI1Env);
  const intl3 = getSystemLocale.intl;
  const stringResult1 = intl2.string(messagesProxy["ksze+o"]);
  let obj = useAgeSpecificText;
  const intl4 = getSystemLocale.intl;
  const stringResult2 = intl3.string(messagesProxy["n73g+V"]);
  const intl5 = getSystemLocale.intl;
  const ageSpecificText = obj.useAgeSpecificText(intl4.string(messagesProxy["5x3taM"]), intl5.string(messagesProxy.WZwGFX));
  let obj1 = useAgeSpecificText;
  const intl6 = getSystemLocale.intl;
  const stringResult3 = intl4.string(messagesProxy["5x3taM"]);
  const intl7 = getSystemLocale.intl;
  const ageSpecificText1 = obj1.useAgeSpecificText(intl6.string(messagesProxy.FcKkcr), intl7.string(messagesProxy.PQtDFk));
  let obj2 = useAgeSpecificText;
  const intl8 = getSystemLocale.intl;
  const stringResult4 = intl6.string(messagesProxy.FcKkcr);
  const intl9 = getSystemLocale.intl;
  const ageSpecificText2 = obj2.useAgeSpecificText(intl8.string(messagesProxy["dES/2r"]), intl9.string(messagesProxy.ep6mdN));
  let obj3 = useAgeSpecificText;
  const intl10 = getSystemLocale.intl;
  const stringResult5 = intl8.string(messagesProxy["dES/2r"]);
  const intl11 = getSystemLocale.intl;
  const ageSpecificText3 = obj3.useAgeSpecificText(intl10.string(messagesProxy.GWPcQg), intl11.string(messagesProxy.yFnKIg));
  let obj4 = useAgeSpecificText;
  const intl12 = getSystemLocale.intl;
  const stringResult6 = intl10.string(messagesProxy.GWPcQg);
  const intl13 = getSystemLocale.intl;
  const ageSpecificText4 = obj4.useAgeSpecificText(intl12.string(messagesProxy["30+sih"]), intl13.string(messagesProxy["0cuLn1"]));
  let obj5 = useAgeSpecificText;
  const intl14 = getSystemLocale.intl;
  const stringResult7 = intl12.string(messagesProxy["30+sih"]);
  const intl15 = getSystemLocale.intl;
  const ageSpecificText5 = obj5.useAgeSpecificText(intl14.string(messagesProxy.tHTyRh), intl15.string(messagesProxy.TeNlMb));
  let obj6 = useAgeSpecificText;
  const intl16 = getSystemLocale.intl;
  const stringResult8 = intl14.string(messagesProxy.tHTyRh);
  const intl17 = getSystemLocale.intl;
  const ageSpecificText6 = obj6.useAgeSpecificText(intl16.string(messagesProxy.PfveQ6), intl17.string(messagesProxy["f7ofm/"]));
  let obj7 = useAgeSpecificText;
  const intl18 = getSystemLocale.intl;
  const stringResult9 = intl16.string(messagesProxy.PfveQ6);
  const intl19 = getSystemLocale.intl;
  const ageSpecificText7 = obj7.useAgeSpecificText(intl18.string(messagesProxy.MKeCj3), intl19.string(messagesProxy.HdcGGl));
  let obj8 = useAgeSpecificText;
  const intl20 = getSystemLocale.intl;
  const stringResult10 = intl18.string(messagesProxy.MKeCj3);
  const intl21 = getSystemLocale.intl;
  const ageSpecificText8 = obj8.useAgeSpecificText(intl20.string(messagesProxy.wZejZr), intl21.string(messagesProxy.tdgcf1));
  let obj9 = useAgeSpecificText;
  const intl22 = getSystemLocale.intl;
  const stringResult11 = intl20.string(messagesProxy.wZejZr);
  const intl23 = getSystemLocale.intl;
  const ageSpecificText9 = obj9.useAgeSpecificText(intl22.string(messagesProxy.ASf7XN), intl23.string(messagesProxy["82y87X"]));
  let obj10 = useAgeSpecificText;
  const intl24 = getSystemLocale.intl;
  const stringResult12 = intl22.string(messagesProxy.ASf7XN);
  const intl25 = getSystemLocale.intl;
  obj = { header: null, description: null, IconComponent: null };
  const ageSpecificText10 = obj10.useAgeSpecificText(intl24.string(messagesProxy["0QDVFN"]), intl25.string(messagesProxy["1xBHHV"]));
  const intl26 = getSystemLocale.intl;
  obj[0] = intl26.string(messagesProxy["/zMYZX"]);
  obj[1] = ageSpecificText;
  obj[2] = UserPlusIcon.UserPlusIcon;
  const items = [obj, , , , , , ];
  obj = { header: null, description: null, IconComponent: null };
  const intl27 = getSystemLocale.intl;
  obj[0] = intl27.string(messagesProxy["44NEx6"]);
  obj[1] = ageSpecificText1;
  obj[2] = ServerIcon.ServerIcon;
  items[1] = obj;
  obj1 = { header: null, description: null, IconComponent: null };
  const intl28 = getSystemLocale.intl;
  obj1[0] = intl28.string(messagesProxy["Z3G+8h"]);
  const intl29 = getSystemLocale.intl;
  obj1[1] = intl29.string(messagesProxy.KBgArX);
  obj1[2] = ForumIcon.ForumIcon;
  items[2] = obj1;
  obj2 = { header: null, description: null, IconComponent: null };
  const intl30 = getSystemLocale.intl;
  obj2[0] = intl30.string(messagesProxy.GNs2ZH);
  const intl31 = getSystemLocale.intl;
  obj2[1] = intl31.string(messagesProxy.Ief2xc);
  obj2[2] = PhoneIcon.PhoneIcon;
  items[3] = obj2;
  obj3 = { header: null, description: null, IconComponent: null };
  const intl32 = getSystemLocale.intl;
  obj3[0] = intl32.string(messagesProxy.PjM3r5);
  obj3[1] = ageSpecificText2;
  obj3[2] = CreditCardIcon.CreditCardIcon;
  items[4] = obj3;
  obj4 = { header: null, description: null, IconComponent: null };
  const intl33 = getSystemLocale.intl;
  obj4[0] = intl33.string(messagesProxy.Fv3n8L);
  obj4[1] = ageSpecificText3;
  obj4[2] = GiftIcon.GiftIcon;
  items[5] = obj4;
  obj5 = { header: ageSpecificText4, description: ageSpecificText5, IconComponent: FlagIcon.FlagIcon };
  items[6] = obj5;
  obj6 = { header: null, description: null, IconComponent: null };
  const intl34 = getSystemLocale.intl;
  obj6[0] = intl34.string(messagesProxy.kyT6pZ);
  obj6[1] = ageSpecificText6;
  obj6[2] = ClockIcon.ClockIcon;
  const items1 = [obj6, , ];
  obj7 = { header: null, description: null, IconComponent: null };
  const intl35 = getSystemLocale.intl;
  obj7[0] = intl35.string(messagesProxy["52ld7c"]);
  obj7[1] = ageSpecificText7;
  obj7[2] = PiggyBankIcon.PiggyBankIcon;
  items1[1] = obj7;
  obj8 = { header: null, description: null, IconComponent: null };
  const intl36 = getSystemLocale.intl;
  obj8[0] = intl36.string(messagesProxy.UCuHM8);
  obj8[1] = ageSpecificText8;
  obj8[2] = SettingsIcon.SettingsIcon;
  items1[2] = obj8;
  obj9 = { spacing: 24, children: null };
  const items2 = [callback(RowGroup, { title: stringResult, rows: items }), callback(RowGroup, { title: stringResult1, rows: items1 }), ];
  obj10 = { title: stringResult2, rows: null };
  const stringResult13 = intl24.string(messagesProxy["0QDVFN"]);
  const items3 = [{ header: ageSpecificText9, description: ageSpecificText10, IconComponent: XSmallIcon.XSmallIcon, negative: true }];
  obj10[1] = items3;
  items2[2] = callback(RowGroup, obj10);
  obj9[1] = items2;
  return callback2(Stack.Stack, obj9);
};