// discord_app/modules/toast/native/toastIconSubstitutions.tsx
import CheckmarkLargeIcon from "../../../design/components/Icon/native/redesign/generated/CheckmarkLargeIcon.tsx";
import CircleCheckIcon from "../../../design/components/Icon/native/redesign/generated/CircleCheckIcon.tsx";
import XLargeIcon from "../../../design/components/Icon/native/redesign/generated/XLargeIcon.tsx";
import CircleXIcon from "../../../design/components/Icon/native/redesign/generated/CircleXIcon.tsx";
import CircleErrorIcon from "../../../design/components/Icon/native/redesign/generated/CircleErrorIcon.tsx";
import WarningIcon from "../../../design/components/Icon/native/redesign/generated/WarningIcon.tsx";
import _modDef5005 from "../../../../_runtime/metro/05005__.js";
import _modDef5006 from "../../../../_runtime/metro/05006__.js";
import _modDef5007 from "../../../../_runtime/metro/05007__.js";
import _modDef5008 from "../../../../_runtime/metro/05008__.js";
import _modDef5009 from "../../../../_runtime/metro/05009__.js";
import _modDef5010 from "../../../../_runtime/metro/05010__.js";
import _modDef5011 from "../../../../_runtime/metro/05011__.js";
import CircleInformationIcon from "../../../design/components/Icon/native/redesign/generated/CircleInformationIcon.tsx";
import _modDef5015 from "../../../../_runtime/metro/05015__.js";
import _modDef5016 from "../../../../_runtime/metro/05016__.js";
import EnvelopeIcon from "../../../design/components/Icon/native/redesign/generated/EnvelopeIcon.tsx";
import _modDef5019 from "../../../../_runtime/metro/05019__.js";
import MicrophoneSlashIcon from "../../../design/components/Icon/native/redesign/generated/MicrophoneSlashIcon.tsx";
import _modDef5022 from "../../../../_runtime/metro/05022__.js";
import VideoSlashIcon from "../../../design/components/Icon/native/redesign/generated/VideoSlashIcon.tsx";
import _modDef5025 from "../../../../_runtime/metro/05025__.js";
import BoostGemIcon from "../../../design/components/Icon/native/redesign/generated/BoostGemIcon.tsx";
import _modDef5028 from "../../../../_runtime/metro/05028__.js";
import ArrowsLeftRightIcon from "../../../design/components/Icon/native/redesign/generated/ArrowsLeftRightIcon.tsx";
import size from "../../../../_runtime/metro/00002__.js";

const items = [CheckmarkLargeIcon.CheckmarkLargeIcon, "success"];
const items1 = [items, , , , ,];
const items2 = [CircleCheckIcon.CircleCheckIcon, "success"];
items1[1] = items2;
const items3 = [XLargeIcon.XLargeIcon, "critical"];
items1[2] = items3;
const items4 = [CircleXIcon.CircleXIcon, "critical"];
items1[3] = items4;
const items5 = [CircleErrorIcon.CircleErrorIcon, "critical"];
items1[4] = items5;
const items6 = [WarningIcon.WarningIcon, "critical"];
items1[5] = items6;
const items7 = [_modDef5005, { variant: "success" }];
const items8 = [items7, , , , , , , , , , , ,];
const items9 = [_modDef5006, { variant: "success" }];
items8[1] = items9;
const items10 = [_modDef5007, { variant: "critical" }];
items8[2] = items10;
const items11 = [_modDef5008, { variant: "critical" }];
items8[3] = items11;
const items12 = [_modDef5009, { variant: "critical" }];
items8[4] = items12;
const items13 = [_modDef5010, { variant: "critical" }];
items8[5] = items13;
const items14 = [_modDef5011];
const map = new Map(items1);
items14[1] = { icon: CircleInformationIcon.CircleInformationIcon };
items8[6] = items14;
const items15 = [_modDef5015];
const obj = { icon: CircleInformationIcon.CircleInformationIcon };
items15[1] = { icon: CircleInformationIcon.CircleInformationIcon };
items8[7] = items15;
const items16 = [_modDef5016];
const obj2 = { icon: CircleInformationIcon.CircleInformationIcon };
items16[1] = { icon: EnvelopeIcon.EnvelopeIcon };
items8[8] = items16;
const items17 = [_modDef5019];
const obj3 = { icon: EnvelopeIcon.EnvelopeIcon };
items17[1] = { icon: MicrophoneSlashIcon.MicrophoneSlashIcon };
items8[9] = items17;
const items18 = [_modDef5022];
const obj4 = { icon: MicrophoneSlashIcon.MicrophoneSlashIcon };
items18[1] = { icon: VideoSlashIcon.VideoSlashIcon };
items8[10] = items18;
const items19 = [_modDef5025];
const obj5 = { icon: VideoSlashIcon.VideoSlashIcon };
items19[1] = { icon: BoostGemIcon.BoostGemIcon };
items8[11] = items19;
const items20 = [_modDef5028];
const obj6 = { icon: BoostGemIcon.BoostGemIcon };
items20[1] = { icon: ArrowsLeftRightIcon.ArrowsLeftRightIcon };
items8[12] = items20;
const obj7 = { icon: ArrowsLeftRightIcon.ArrowsLeftRightIcon };
const result = size.fileFinishedImporting("modules/toast/native/toastIconSubstitutions.tsx");

export const TOAST_STATUS_ICONS = map;
export const TOAST_PNG_SUBSTITUTIONS = new Map(items8);
