// discord_app/modules/toast/native/toastIconSubstitutions.tsx
import CheckmarkLargeIcon from "../../../design/components/Icon/native/redesign/generated/CheckmarkLargeIcon.tsx";
import CircleCheckIcon from "../../../design/components/Icon/native/redesign/generated/CircleCheckIcon.tsx";
import XLargeIcon from "../../../design/components/Icon/native/redesign/generated/XLargeIcon.tsx";
import CircleXIcon from "../../../design/components/Icon/native/redesign/generated/CircleXIcon.tsx";
import CircleErrorIcon from "../../../design/components/Icon/native/redesign/generated/CircleErrorIcon.tsx";
import WarningIcon from "../../../design/components/Icon/native/redesign/generated/WarningIcon.tsx";
import AssetRegistryDefault from "../../../../_runtime/04811_AssetRegistry.js";
import AssetRegistryDefault2 from "../../../../_runtime/04812_AssetRegistry.js";
import AssetRegistryDefault3 from "../../../../_runtime/04813_AssetRegistry.js";
import AssetRegistryDefault4 from "../../../../_runtime/04814_AssetRegistry.js";
import AssetRegistryDefault5 from "../../../../_runtime/04815_AssetRegistry.js";
import AssetRegistryDefault6 from "../../../../_runtime/04816_AssetRegistry.js";
import AssetRegistryDefault7 from "../../../../_runtime/04817_AssetRegistry.js";
import CircleInformationIcon from "../../../design/components/Icon/native/redesign/generated/CircleInformationIcon.tsx";
import AssetRegistryDefault8 from "../../../../_runtime/04821_AssetRegistry.js";
import AssetRegistryDefault9 from "../../../../_runtime/04822_AssetRegistry.js";
import EnvelopeIcon from "../../../design/components/Icon/native/redesign/generated/EnvelopeIcon.tsx";
import AssetRegistryDefault10 from "../../../../_runtime/04825_AssetRegistry.js";
import MicrophoneSlashIcon from "../../../design/components/Icon/native/redesign/generated/MicrophoneSlashIcon.tsx";
import AssetRegistryDefault11 from "../../../../_runtime/04828_AssetRegistry.js";
import VideoSlashIcon from "../../../design/components/Icon/native/redesign/generated/VideoSlashIcon.tsx";
import AssetRegistryDefault12 from "../../../../_runtime/04831_AssetRegistry.js";
import BoostGemIcon from "../../../design/components/Icon/native/redesign/generated/BoostGemIcon.tsx";
import AssetRegistryDefault13 from "../../../../_runtime/04834_AssetRegistry.js";
import ArrowsLeftRightIcon from "../../../design/components/Icon/native/redesign/generated/ArrowsLeftRightIcon.tsx";
import size from "../../../../_runtime/metro/00002__.js";

const items = [CheckmarkLargeIcon.CheckmarkLargeIcon, "success"];
const items1 = [items, , , , ,];
const items2 = [CircleCheckIcon.CircleCheckIcon, "success"];
items1[1] = items2;
const items3 = [XLargeIcon.XLargeIcon, "critical"];
items1[2] = items3;
const items4 = [CircleXIcon.CircleXIcon, "critical"];
items1[3] = items4;
const items5 = [CircleErrorIcon.CircleErrorIcon, "critical"];
items1[4] = items5;
const items6 = [WarningIcon.WarningIcon, "critical"];
items1[5] = items6;
const items7 = [,];
const map = new Map(items1);
items7[0] = AssetRegistryDefault;
items7[1] = { variant: "success" };
const items8 = [items7, , , , , , , , , , , ,];
const items9 = [AssetRegistryDefault2, { variant: "success" }];
items8[1] = items9;
const items10 = [AssetRegistryDefault3, { variant: "critical" }];
items8[2] = items10;
const items11 = [AssetRegistryDefault4, { variant: "critical" }];
items8[3] = items11;
const items12 = [AssetRegistryDefault5, { variant: "critical" }];
items8[4] = items12;
const items13 = [AssetRegistryDefault6, { variant: "critical" }];
items8[5] = items13;
const items14 = [AssetRegistryDefault7, { icon: CircleInformationIcon.CircleInformationIcon }];
items8[6] = items14;
const items15 = [,];
({ icon: CircleInformationIcon.CircleInformationIcon });
items15[0] = AssetRegistryDefault8;
items15[1] = { icon: CircleInformationIcon.CircleInformationIcon };
items8[7] = items15;
const items16 = [,];
({ icon: CircleInformationIcon.CircleInformationIcon });
items16[0] = AssetRegistryDefault9;
items16[1] = { icon: EnvelopeIcon.EnvelopeIcon };
items8[8] = items16;
const items17 = [,];
({ icon: EnvelopeIcon.EnvelopeIcon });
items17[0] = AssetRegistryDefault10;
items17[1] = { icon: MicrophoneSlashIcon.MicrophoneSlashIcon };
items8[9] = items17;
const items18 = [,];
({ icon: MicrophoneSlashIcon.MicrophoneSlashIcon });
items18[0] = AssetRegistryDefault11;
items18[1] = { icon: VideoSlashIcon.VideoSlashIcon };
items8[10] = items18;
const items19 = [,];
({ icon: VideoSlashIcon.VideoSlashIcon });
items19[0] = AssetRegistryDefault12;
items19[1] = { icon: BoostGemIcon.BoostGemIcon };
items8[11] = items19;
const items20 = [,];
({ icon: BoostGemIcon.BoostGemIcon });
items20[0] = AssetRegistryDefault13;
items20[1] = { icon: ArrowsLeftRightIcon.ArrowsLeftRightIcon };
items8[12] = items20;
({ icon: ArrowsLeftRightIcon.ArrowsLeftRightIcon });
const map1 = new Map(items8);
const result = size.fileFinishedImporting("modules/toast/native/toastIconSubstitutions.tsx");

export const TOAST_STATUS_ICONS = map;
export const TOAST_PNG_SUBSTITUTIONS = map1;
