import { _isNativeReflectConstruct } from "../00199__isNativeReflectConstruct.js";
import { Blob } from "../00203_Blob.js";
import { FormData } from "../00211_FormData.js";
import { t } from "../00215_t.js";
import { _isNativeReflectConstruct } from "../00217__isNativeReflectConstruct.js";
import { _isNativeReflectConstruct } from "../00222__isNativeReflectConstruct.js";
import { _isNativeReflectConstruct } from "../00223__isNativeReflectConstruct.js";
import { URL } from "../00226_URL.js";
import { _isNativeReflectConstruct } from "../00228__isNativeReflectConstruct.js";
// _runtime/metro/00198__.js
import polyfillObjectProperty from "polyfillObjectProperty";
import polyfillObjectProperty from "polyfillObjectProperty";
import polyfillObjectProperty from "polyfillObjectProperty";
import polyfillObjectProperty from "polyfillObjectProperty";
import polyfillObjectProperty from "polyfillObjectProperty";
import polyfillObjectProperty from "polyfillObjectProperty";
import polyfillObjectProperty from "polyfillObjectProperty";
import polyfillObjectProperty from "polyfillObjectProperty";
import polyfillObjectProperty from "polyfillObjectProperty";
import polyfillObjectProperty from "polyfillObjectProperty";
import polyfillObjectProperty from "polyfillObjectProperty";
import polyfillObjectProperty from "polyfillObjectProperty";
import polyfillObjectProperty from "polyfillObjectProperty";
import polyfillObjectProperty from "polyfillObjectProperty";

polyfillObjectProperty.polyfillGlobal("XMLHttpRequest", () => _isNativeReflectConstruct /* _isNativeReflectConstruct */.default);
polyfillObjectProperty.polyfillGlobal("FormData", () => FormData /* FormData */.default);
polyfillObjectProperty.polyfillGlobal("fetch", () => t /* t */.fetch);
polyfillObjectProperty.polyfillGlobal("Headers", () => t /* t */.Headers);
polyfillObjectProperty.polyfillGlobal("Request", () => t /* t */.Request);
polyfillObjectProperty.polyfillGlobal("Response", () => t /* t */.Response);
polyfillObjectProperty.polyfillGlobal("WebSocket", () => _isNativeReflectConstruct /* _isNativeReflectConstruct */.default);
polyfillObjectProperty.polyfillGlobal("Blob", () => Blob /* Blob */.default);
polyfillObjectProperty.polyfillGlobal("File", () => _isNativeReflectConstruct /* _isNativeReflectConstruct */.default);
polyfillObjectProperty.polyfillGlobal("FileReader", () => _isNativeReflectConstruct /* _isNativeReflectConstruct */.default);
polyfillObjectProperty.polyfillGlobal("URL", () => URL /* URL */.URL);
polyfillObjectProperty.polyfillGlobal("URLSearchParams", () => URL /* URL */.URLSearchParams);
polyfillObjectProperty.polyfillGlobal("AbortController", () => _isNativeReflectConstruct /* _isNativeReflectConstruct */.AbortController);
polyfillObjectProperty.polyfillGlobal("AbortSignal", () => _isNativeReflectConstruct /* _isNativeReflectConstruct */.AbortSignal);