// _runtime/metro/00198__.js
import polyfillObjectProperty from "polyfillObjectProperty";
import polyfillObjectProperty from "polyfillObjectProperty";
import polyfillObjectProperty from "polyfillObjectProperty";
import polyfillObjectProperty from "polyfillObjectProperty";
import polyfillObjectProperty from "polyfillObjectProperty";
import polyfillObjectProperty from "polyfillObjectProperty";
import polyfillObjectProperty from "polyfillObjectProperty";
import polyfillObjectProperty from "polyfillObjectProperty";
import polyfillObjectProperty from "polyfillObjectProperty";
import polyfillObjectProperty from "polyfillObjectProperty";
import polyfillObjectProperty from "polyfillObjectProperty";
import polyfillObjectProperty from "polyfillObjectProperty";
import polyfillObjectProperty from "polyfillObjectProperty";
import polyfillObjectProperty from "polyfillObjectProperty";

polyfillObjectProperty.polyfillGlobal("XMLHttpRequest", () => require("../00199__isNativeReflectConstruct.js") /* _isNativeReflectConstruct */.default);
polyfillObjectProperty.polyfillGlobal("FormData", () => require("../00211_FormData.js") /* FormData */.default);
polyfillObjectProperty.polyfillGlobal("fetch", () => require("../00215_t.js") /* t */.fetch);
polyfillObjectProperty.polyfillGlobal("Headers", () => require("../00215_t.js") /* t */.Headers);
polyfillObjectProperty.polyfillGlobal("Request", () => require("../00215_t.js") /* t */.Request);
polyfillObjectProperty.polyfillGlobal("Response", () => require("../00215_t.js") /* t */.Response);
polyfillObjectProperty.polyfillGlobal("WebSocket", () => require("../00217__isNativeReflectConstruct.js") /* _isNativeReflectConstruct */.default);
polyfillObjectProperty.polyfillGlobal("Blob", () => require("../00203_Blob.js") /* Blob */.default);
polyfillObjectProperty.polyfillGlobal("File", () => require("../00222__isNativeReflectConstruct.js") /* _isNativeReflectConstruct */.default);
polyfillObjectProperty.polyfillGlobal("FileReader", () => require("../00223__isNativeReflectConstruct.js") /* _isNativeReflectConstruct */.default);
polyfillObjectProperty.polyfillGlobal("URL", () => require("../00226_URL.js") /* URL */.URL);
polyfillObjectProperty.polyfillGlobal("URLSearchParams", () => require("../00226_URL.js") /* URL */.URLSearchParams);
polyfillObjectProperty.polyfillGlobal("AbortController", () => require("../00228__isNativeReflectConstruct.js") /* _isNativeReflectConstruct */.AbortController);
polyfillObjectProperty.polyfillGlobal("AbortSignal", () => require("../00228__isNativeReflectConstruct.js") /* _isNativeReflectConstruct */.AbortSignal);