// === Module 392: ? ===

// Module 392
import _mod26 from "module_26" /* 26 */;
import module_65 from "module_65" /* 65 */;

const __INTERNAL_VIEW_CONFIG = { uiViewClassName: "AndroidHorizontalScrollView", bubblingEventTypes: {}, directEventTypes: {}, validAttributes: { decelerationRate: true, disableIntervalMomentum: true, maintainVisibleContentPosition: true, endFillColor: _mod26.colorAttribute, fadingEdgeLength: true, nestedScrollEnabled: true, overScrollMode: true, pagingEnabled: true, persistentScrollbar: true, horizontal: true, scrollEnabled: true, scrollEventThrottle: true, scrollPerfTag: true, sendMomentumEvents: true, showsHorizontalScrollIndicator: true, snapToAlignment: true, snapToEnd: true, snapToInterval: true, snapToStart: true, snapToOffsets: true, contentOffset: true, borderBottomLeftRadius: true, borderBottomRightRadius: true, borderRadius: true, borderStyle: true, borderRightColor: _mod26.colorAttribute, borderColor: _mod26.colorAttribute, borderBottomColor: _mod26.colorAttribute, borderTopLeftRadius: true, borderTopColor: _mod26.colorAttribute, removeClippedSubviews: true, borderTopRightRadius: true, borderLeftColor: _mod26.colorAttribute, pointerEvents: true, scrollsChildToFocus: true } };
({ decelerationRate: true, disableIntervalMomentum: true, maintainVisibleContentPosition: true, endFillColor: _mod26.colorAttribute, fadingEdgeLength: true, nestedScrollEnabled: true, overScrollMode: true, pagingEnabled: true, persistentScrollbar: true, horizontal: true, scrollEnabled: true, scrollEventThrottle: true, scrollPerfTag: true, sendMomentumEvents: true, showsHorizontalScrollIndicator: true, snapToAlignment: true, snapToEnd: true, snapToInterval: true, snapToStart: true, snapToOffsets: true, contentOffset: true, borderBottomLeftRadius: true, borderBottomRightRadius: true, borderRadius: true, borderStyle: true, borderRightColor: _mod26.colorAttribute, borderColor: _mod26.colorAttribute, borderBottomColor: _mod26.colorAttribute, borderTopLeftRadius: true, borderTopColor: _mod26.colorAttribute, removeClippedSubviews: true, borderTopRightRadius: true, borderLeftColor: _mod26.colorAttribute, pointerEvents: true, scrollsChildToFocus: true });

export default module_65.get("AndroidHorizontalScrollView", () => obj);
export { __INTERNAL_VIEW_CONFIG };