// _runtime/metro/00675__.js
import _mod682 from "00682__.js";
import NativeModules from "../00866_NativeModules.js";
import feedbackAsyncIntegration from "../00889_feedbackAsyncIntegration.js";
import SDK_PACKAGE_NAME from "../00978_SDK_PACKAGE_NAME.js";
import init from "../01000_init.js";
import _mod1041 from "01041__.js";
import _mod1045 from "01045__.js";
import reactNativeTracingIntegration from "../01052_reactNativeTracingIntegration.js";
import _mod1059 from "01059__.js";
import _mod1062 from "01062__.js";
import _mod1065 from "01065__.js";
import _mod1070 from "01070__.js";
import warn from "../01072_warn.js";

for (const key10013 in require("debugSymbolicatorIntegration")) {
  arg5[key10013] = require("debugSymbolicatorIntegration")[key10013];
  continue;
}

export const addBreadcrumb = _mod682.addBreadcrumb;
export const addIntegration = _mod682.addIntegration;
export const captureException = _mod682.captureException;
export const captureEvent = _mod682.captureEvent;
export const captureFeedback = _mod682.captureFeedback;
export const captureMessage = _mod682.captureMessage;
export const Scope = _mod682.Scope;
export const setContext = _mod682.setContext;
export const setExtra = _mod682.setExtra;
export const setExtras = _mod682.setExtras;
export const setTag = _mod682.setTag;
export const setTags = _mod682.setTags;
export const setUser = _mod682.setUser;
export const startInactiveSpan = _mod682.startInactiveSpan;
export const startSpan = _mod682.startSpan;
export const startSpanManual = _mod682.startSpanManual;
export const getActiveSpan = _mod682.getActiveSpan;
export const getRootSpan = _mod682.getRootSpan;
export const withActiveSpan = _mod682.withActiveSpan;
export const suppressTracing = _mod682.suppressTracing;
export const spanToJSON = _mod682.spanToJSON;
export const spanIsSampled = _mod682.spanIsSampled;
export const setMeasurement = _mod682.setMeasurement;
export const getCurrentScope = _mod682.getCurrentScope;
export const getGlobalScope = _mod682.getGlobalScope;
export const getIsolationScope = _mod682.getIsolationScope;
export const getClient = _mod682.getClient;
export const setCurrentClient = _mod682.setCurrentClient;
export const addEventProcessor = _mod682.addEventProcessor;
export const lastEventId = _mod682.lastEventId;
export const ErrorBoundary = init.ErrorBoundary;
export const withErrorBoundary = init.withErrorBoundary;
export const createReduxEnhancer = init.createReduxEnhancer;
export const Profiler = init.Profiler;
export const useProfiler = init.useProfiler;
export const withProfiler = init.withProfiler;
export const logger = feedbackAsyncIntegration.logger;
export const consoleLoggingIntegration = feedbackAsyncIntegration.consoleLoggingIntegration;
export const featureFlagsIntegration = feedbackAsyncIntegration.featureFlagsIntegration;
export const metrics = feedbackAsyncIntegration.metrics;
export const SDK_NAME = SDK_PACKAGE_NAME.SDK_NAME;
export const SDK_VERSION = SDK_PACKAGE_NAME.SDK_VERSION;
export const ReactNativeClient = _mod1041.ReactNativeClient;
export const init = _mod1045.init;
export const wrap = _mod1045.wrap;
export const nativeCrash = _mod1045.nativeCrash;
export const flush = _mod1045.flush;
export const close = _mod1045.close;
export const withScope = _mod1045.withScope;
export const crashedLastRun = _mod1045.crashedLastRun;
export const TouchEventBoundary = _mod1059.TouchEventBoundary;
export const withTouchEventBoundary = _mod1059.withTouchEventBoundary;
export const reactNativeTracingIntegration = reactNativeTracingIntegration.reactNativeTracingIntegration;
export const getCurrentReactNativeTracingIntegration =
  reactNativeTracingIntegration.getCurrentReactNativeTracingIntegration;
export const getReactNativeTracingIntegration = reactNativeTracingIntegration.getReactNativeTracingIntegration;
export const reactNavigationIntegration = reactNativeTracingIntegration.reactNavigationIntegration;
export const reactNativeNavigationIntegration = reactNativeTracingIntegration.reactNativeNavigationIntegration;
export const sentryTraceGesture = reactNativeTracingIntegration.sentryTraceGesture;
export const TimeToInitialDisplay = reactNativeTracingIntegration.TimeToInitialDisplay;
export const TimeToFullDisplay = reactNativeTracingIntegration.TimeToFullDisplay;
export const startTimeToInitialDisplaySpan = reactNativeTracingIntegration.startTimeToInitialDisplaySpan;
export const startTimeToFullDisplaySpan = reactNativeTracingIntegration.startTimeToFullDisplaySpan;
export const startIdleNavigationSpan = reactNativeTracingIntegration.startIdleNavigationSpan;
export const startIdleSpan = reactNativeTracingIntegration.startIdleSpan;
export const getDefaultIdleNavigationSpanOptions = reactNativeTracingIntegration.getDefaultIdleNavigationSpanOptions;
export const createTimeToFullDisplay = reactNativeTracingIntegration.createTimeToFullDisplay;
export const createTimeToInitialDisplay = reactNativeTracingIntegration.createTimeToInitialDisplay;
export const Mask = warn.Mask;
export const Unmask = warn.Unmask;
export const FeedbackButton = _mod1065.FeedbackButton;
export const FeedbackWidget = _mod1070.FeedbackWidget;
export const showFeedbackWidget = _mod1062.showFeedbackWidget;
export const showFeedbackButton = _mod1062.showFeedbackButton;
export const hideFeedbackButton = _mod1062.hideFeedbackButton;
export const getDataFromUri = NativeModules.getDataFromUri;
