// _runtime/metro/00682__.js
import _mod683 from "00683__.js";
import spanToJSON from "../00684_spanToJSON.js";
import unwrapScopeFromWeakRef from "../00685_unwrapScopeFromWeakRef.js";
import _mod686 from "00686__.js";
import _mod687 from "00687__.js";
import consoleSandbox from "../00689_consoleSandbox.js";
import _mod690 from "00690__.js";
import SDK_VERSION from "../00691_SDK_VERSION.js";
import _mod692 from "00692__.js";
import _htmlElementAsString from "../00693__htmlElementAsString.js";
import generateSpanId from "../00694_generateSpanId.js";
import uuid4 from "../00695_uuid4.js";
import safeDateNow from "../00696_safeDateNow.js";
import _mod697 from "00697__.js";
import _mod698 from "00698__.js";
import _mod699 from "00699__.js";
import MAX_BAGGAGE_STRING_LENGTH from "../00700_MAX_BAGGAGE_STRING_LENGTH.js";
import _mod701 from "00701__.js";
import _mod702 from "00702__.js";
import dateTimestampInSeconds from "../00703_dateTimestampInSeconds.js";
import SEMANTIC_ATTRIBUTE_CACHE_HIT from "../00704_SEMANTIC_ATTRIBUTE_CACHE_HIT.js";
import SPAN_STATUS_ERROR from "../00705_SPAN_STATUS_ERROR.js";
import _mod706 from "00706__.js";
import Scope from "../00708_Scope.js";
import _getSpanForScope from "../00709__getSpanForScope.js";
import closeSession from "../00710_closeSession.js";
import _mod712 from "00712__.js";
import _mod713 from "00713__.js";
import instrumentError from "../00714_instrumentError.js";
import _mod715 from "00715__.js";
import instrumentUnhandledRejection from "../00716_instrumentUnhandledRejection.js";
import TRACING_DEFAULTS from "../00717_TRACING_DEFAULTS.js";
import _mod720 from "00720__.js";
import SentryNonRecordingSpan from "../00721_SentryNonRecordingSpan.js";
import _mod722 from "00722__.js";
import DEFAULT_ENVIRONMENT from "../00723_DEFAULT_ENVIRONMENT.js";
import _mod725 from "00725__.js";
import logSpanEnd from "../00726_logSpanEnd.js";
import timedEventsToMeasurements from "../00727_timedEventsToMeasurements.js";
import _enhanceEventWithSdkInfo from "../00728__enhanceEventWithSdkInfo.js";
import forEachEnvelopeItem from "../00729_forEachEnvelopeItem.js";
import normalize from "../00730_normalize.js";
import _mod731 from "00731__.js";
import _mod732 from "00732__.js";
import sampleSpan from "../00733_sampleSpan.js";
import captureCheckIn from "../00734_captureCheckIn.js";
import applyClientOptions from "../00735_applyClientOptions.js";
import mergeScopeData from "../00736_mergeScopeData.js";
import _notifyEventProcessors from "../00737__notifyEventProcessors.js";
import SyncPromise from "../00738_SyncPromise.js";
import _mod739 from "00739__.js";
import _mod740 from "00740__.js";
import _mod741 from "00741__.js";
import SENTRY_BUFFER_FULL_ERROR from "../00742_SENTRY_BUFFER_FULL_ERROR.js";
import DEFAULT_TRANSPORT_BUFFER_SIZE from "../00743_DEFAULT_TRANSPORT_BUFFER_SIZE.js";
import disabledUntil from "../00744_disabledUntil.js";
import _INTERNAL_captureSerializedLog from "../00745__INTERNAL_captureSerializedLog.js";
import _INTERNAL_captureSerializedMetric from "../00750__INTERNAL_captureSerializedMetric.js";
import setupIntegration from "../00752_setupIntegration.js";
import _mod754 from "00754__.js";
import _mod756 from "00756__.js";
import exceptionFromError from "../00758_exceptionFromError.js";
import _mod759 from "00759__.js";
import _mod760 from "00760__.js";
import MIN_DELAY from "../00761_MIN_DELAY.js";
import eventFromEnvelope from "../00762_eventFromEnvelope.js";
import _INTERNAL_clearAiProviderSkips from "../00763__INTERNAL_clearAiProviderSkips.js";
import _mod764 from "00764__.js";
import _mod765 from "00765__.js";
import parameterize from "../00766_parameterize.js";
import _mod767 from "00767__.js";
import applySdkMetadata from "../00768_applySdkMetadata.js";
import _mod769 from "00769__.js";
import _mod770 from "00770__.js";
import _mod771 from "00771__.js";
import winterCGHeadersToDict from "../00772_winterCGHeadersToDict.js";
import _mod773 from "00773__.js";
import _mod774 from "00774__.js";
import _mergeOptions from "../00775__mergeOptions.js";
import linkedErrorsIntegration from "../00776_linkedErrorsIntegration.js";
import aggregateExceptionsFromError from "../00777_aggregateExceptionsFromError.js";
import moduleMetadataIntegration from "../00778_moduleMetadataIntegration.js";
import _mod779 from "00779__.js";
import requestDataIntegration from "../00780_requestDataIntegration.js";
import captureConsoleIntegration from "../00783_captureConsoleIntegration.js";
import instrumentConsole from "../00784_instrumentConsole.js";
import severityLevelFromString from "../00785_severityLevelFromString.js";
import _shouldDropEvent from "../00786__shouldDropEvent.js";
import _extractErrorData from "../00787__extractErrorData.js";
import generateIteratee from "../00788_generateIteratee.js";
import resolve from "../00789_resolve.js";
import markAsInstrumented from "../00790_markAsInstrumented.js";
import flattenIssue from "../00791_flattenIssue.js";
import thirdPartyErrorFilterIntegration from "../00792_thirdPartyErrorFilterIntegration.js";
import _mod793 from "00793__.js";
import featureFlagsIntegration from "../00794_featureFlagsIntegration.js";
import _INTERNAL_FLAG_BUFFER_SIZE from "../00795__INTERNAL_FLAG_BUFFER_SIZE.js";
import growthbookIntegration from "../00796_growthbookIntegration.js";
import profiler from "../00797_profiler.js";
import _addTracingHeadersToFetchRequest from "00798__addTracingHeadersToFetchRequest.js";
import trpcMiddleware from "../00799_trpcMiddleware.js";
import _mod800 from "00800__.js";
import captureFeedback from "../00814_captureFeedback.js";
import fmt from "../00815_fmt.js";
import consoleLoggingIntegration from "../00816_consoleLoggingIntegration.js";
import count from "../00818_count.js";
import _mod819 from "00819__.js";
import _mod820 from "00820__.js";
import convertPromptToMessages from "../00822_convertPromptToMessages.js";
import extractRequestAttributes from "../00827_extractRequestAttributes.js";
import INSTRUMENTED_METHODS from "../00829_INSTRUMENTED_METHODS.js";
import instrumentAnthropicAiClient from "../00834_instrumentAnthropicAiClient.js";
import ANTHROPIC_AI_INSTRUMENTED_METHODS from "../00836_ANTHROPIC_AI_INSTRUMENTED_METHODS.js";
import _mod838 from "00838__.js";
import CHATS_CREATE_METHOD from "../00839_CHATS_CREATE_METHOD.js";
import _mod842 from "00842__.js";
import LANGCHAIN_INTEGRATION_NAME from "../00844_LANGCHAIN_INTEGRATION_NAME.js";
import instrumentLangGraph from "../00845_instrumentLangGraph.js";
import LANGGRAPH_INTEGRATION_NAME from "../00846_LANGGRAPH_INTEGRATION_NAME.js";
import _mod848 from "00848__.js";
import _mod849 from "00849__.js";
import _resolveResponse from "../00850__resolveResponse.js";
import _isFetchSupported from "../00851__isFetchSupported.js";
import dynamicRequire from "../00852_dynamicRequire.js";
import _mod853 from "00853__.js";
import _mod854 from "00854__.js";
import replaceExports from "../00855_replaceExports.js";
import filenameIsInApp from "../00856_filenameIsInApp.js";
import callFrameToStackFrame from "../00857_callFrameToStackFrame.js";
import LRUMap from "../00858_LRUMap.js";
import vercelWaitUntil from "../00859_vercelWaitUntil.js";
import flushWithTimeout from "../00860_flushWithTimeout.js";
import escapeStringForRegex from "../00861_escapeStringForRegex.js";

Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });

export const registerSpanErrorInstrumentation = _mod683.registerSpanErrorInstrumentation;
export const getCapturedScopesOnSpan = unwrapScopeFromWeakRef.getCapturedScopesOnSpan;
export const setCapturedScopesOnSpan = unwrapScopeFromWeakRef.setCapturedScopesOnSpan;
export const TRACING_DEFAULTS = TRACING_DEFAULTS.TRACING_DEFAULTS;
export const startIdleSpan = TRACING_DEFAULTS.startIdleSpan;
export const SentrySpan = _mod725.SentrySpan;
export const SentryNonRecordingSpan = SentryNonRecordingSpan.SentryNonRecordingSpan;
export const SPAN_STATUS_ERROR = SPAN_STATUS_ERROR.SPAN_STATUS_ERROR;
export const SPAN_STATUS_OK = SPAN_STATUS_ERROR.SPAN_STATUS_OK;
export const SPAN_STATUS_UNSET = SPAN_STATUS_ERROR.SPAN_STATUS_UNSET;
export const getSpanStatusFromHttpCode = SPAN_STATUS_ERROR.getSpanStatusFromHttpCode;
export const setHttpStatus = SPAN_STATUS_ERROR.setHttpStatus;
export const continueTrace = _mod731.continueTrace;
export const startInactiveSpan = _mod731.startInactiveSpan;
export const startNewTrace = _mod731.startNewTrace;
export const startSpan = _mod731.startSpan;
export const startSpanManual = _mod731.startSpanManual;
export const suppressTracing = _mod731.suppressTracing;
export const withActiveSpan = _mod731.withActiveSpan;
export const getDynamicSamplingContextFromClient = _mod722.getDynamicSamplingContextFromClient;
export const getDynamicSamplingContextFromScope = _mod722.getDynamicSamplingContextFromScope;
export const getDynamicSamplingContextFromSpan = _mod722.getDynamicSamplingContextFromSpan;
export const spanToBaggageHeader = _mod722.spanToBaggageHeader;
export const setMeasurement = timedEventsToMeasurements.setMeasurement;
export const timedEventsToMeasurements = timedEventsToMeasurements.timedEventsToMeasurements;
export const sampleSpan = sampleSpan.sampleSpan;
export const logSpanEnd = logSpanEnd.logSpanEnd;
export const logSpanStart = logSpanEnd.logSpanStart;
export const SEMANTIC_ATTRIBUTE_CACHE_HIT = SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_ATTRIBUTE_CACHE_HIT;
export const SEMANTIC_ATTRIBUTE_CACHE_ITEM_SIZE = SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_ATTRIBUTE_CACHE_ITEM_SIZE;
export const SEMANTIC_ATTRIBUTE_CACHE_KEY = SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_ATTRIBUTE_CACHE_KEY;
export const SEMANTIC_ATTRIBUTE_EXCLUSIVE_TIME = SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_ATTRIBUTE_EXCLUSIVE_TIME;
export const SEMANTIC_ATTRIBUTE_HTTP_REQUEST_METHOD =
  SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_ATTRIBUTE_HTTP_REQUEST_METHOD;
export const SEMANTIC_ATTRIBUTE_PROFILE_ID = SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_ATTRIBUTE_PROFILE_ID;
export const SEMANTIC_ATTRIBUTE_SENTRY_CUSTOM_SPAN_NAME =
  SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_ATTRIBUTE_SENTRY_CUSTOM_SPAN_NAME;
export const SEMANTIC_ATTRIBUTE_SENTRY_IDLE_SPAN_FINISH_REASON =
  SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_ATTRIBUTE_SENTRY_IDLE_SPAN_FINISH_REASON;
export const SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_UNIT =
  SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_UNIT;
export const SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_VALUE =
  SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_VALUE;
export const SEMANTIC_ATTRIBUTE_SENTRY_OP = SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_ATTRIBUTE_SENTRY_OP;
export const SEMANTIC_ATTRIBUTE_SENTRY_ORIGIN = SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_ATTRIBUTE_SENTRY_ORIGIN;
export const SEMANTIC_ATTRIBUTE_SENTRY_PREVIOUS_TRACE_SAMPLE_RATE =
  SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_ATTRIBUTE_SENTRY_PREVIOUS_TRACE_SAMPLE_RATE;
export const SEMANTIC_ATTRIBUTE_SENTRY_SAMPLE_RATE = SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_ATTRIBUTE_SENTRY_SAMPLE_RATE;
export const SEMANTIC_ATTRIBUTE_SENTRY_SOURCE = SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_ATTRIBUTE_SENTRY_SOURCE;
export const SEMANTIC_ATTRIBUTE_URL_FULL = SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_ATTRIBUTE_URL_FULL;
export const SEMANTIC_LINK_ATTRIBUTE_LINK_TYPE = SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_LINK_ATTRIBUTE_LINK_TYPE;
export const createEventEnvelope = _enhanceEventWithSdkInfo.createEventEnvelope;
export const createSessionEnvelope = _enhanceEventWithSdkInfo.createSessionEnvelope;
export const createSpanEnvelope = _enhanceEventWithSdkInfo.createSpanEnvelope;
export const addEventProcessor = captureCheckIn.addEventProcessor;
export const captureCheckIn = captureCheckIn.captureCheckIn;
export const captureEvent = captureCheckIn.captureEvent;
export const captureException = captureCheckIn.captureException;
export const captureMessage = captureCheckIn.captureMessage;
export const captureSession = captureCheckIn.captureSession;
export const close = captureCheckIn.close;
export const endSession = captureCheckIn.endSession;
export const flush = captureCheckIn.flush;
export const isEnabled = captureCheckIn.isEnabled;
export const isInitialized = captureCheckIn.isInitialized;
export const lastEventId = captureCheckIn.lastEventId;
export const setContext = captureCheckIn.setContext;
export const setExtra = captureCheckIn.setExtra;
export const setExtras = captureCheckIn.setExtras;
export const setTag = captureCheckIn.setTag;
export const setTags = captureCheckIn.setTags;
export const setUser = captureCheckIn.setUser;
export const startSession = captureCheckIn.startSession;
export const withMonitor = captureCheckIn.withMonitor;
export const getClient = _mod713.getClient;
export const getCurrentScope = _mod713.getCurrentScope;
export const getGlobalScope = _mod713.getGlobalScope;
export const getIsolationScope = _mod713.getIsolationScope;
export const getTraceContextFromScope = _mod713.getTraceContextFromScope;
export const withIsolationScope = _mod713.withIsolationScope;
export const withScope = _mod713.withScope;
export const getDefaultCurrentScope = _mod712.getDefaultCurrentScope;
export const getDefaultIsolationScope = _mod712.getDefaultIsolationScope;
export const setAsyncContextStrategy = _mod706.setAsyncContextStrategy;
export const getGlobalSingleton = _mod690.getGlobalSingleton;
export const getMainCarrier = _mod690.getMainCarrier;
export const closeSession = closeSession.closeSession;
export const makeSession = closeSession.makeSession;
export const updateSession = closeSession.updateSession;
export const Scope = Scope.Scope;
export const notifyEventProcessors = _notifyEventProcessors.notifyEventProcessors;
export const getEnvelopeEndpointWithUrlEncodedAuth = _mod740.getEnvelopeEndpointWithUrlEncodedAuth;
export const getReportDialogEndpoint = _mod740.getReportDialogEndpoint;
export const Client = _mod741.Client;
export const ServerRuntimeClient = _mod756.ServerRuntimeClient;
export const initAndBind = _mod760.initAndBind;
export const setCurrentClient = _mod760.setCurrentClient;
export const createTransport = DEFAULT_TRANSPORT_BUFFER_SIZE.createTransport;
export const makeOfflineTransport = MIN_DELAY.makeOfflineTransport;
export const MULTIPLEXED_TRANSPORT_EXTRA_KEY = eventFromEnvelope.MULTIPLEXED_TRANSPORT_EXTRA_KEY;
export const makeMultiplexedTransport = eventFromEnvelope.makeMultiplexedTransport;
export const addIntegration = setupIntegration.addIntegration;
export const defineIntegration = setupIntegration.defineIntegration;
export const getIntegrationsToSetup = setupIntegration.getIntegrationsToSetup;
export const installedIntegrations = setupIntegration.installedIntegrations;
export const _INTERNAL_clearAiProviderSkips = _INTERNAL_clearAiProviderSkips._INTERNAL_clearAiProviderSkips;
export const _INTERNAL_shouldSkipAiProviderWrapping =
  _INTERNAL_clearAiProviderSkips._INTERNAL_shouldSkipAiProviderWrapping;
export const _INTERNAL_skipAiProviderWrapping = _INTERNAL_clearAiProviderSkips._INTERNAL_skipAiProviderWrapping;
export const applyScopeDataToEvent = mergeScopeData.applyScopeDataToEvent;
export const getCombinedScopeData = mergeScopeData.getCombinedScopeData;
export const mergeScopeData = mergeScopeData.mergeScopeData;
export const prepareEvent = applyClientOptions.prepareEvent;
export const createCheckInEnvelope = _mod759.createCheckInEnvelope;
export const hasSpansEnabled = _mod720.hasSpansEnabled;
export const isSentryRequestUrl = _mod764.isSentryRequestUrl;
export const handleCallbackErrors = _mod732.handleCallbackErrors;
export const fmt = parameterize.fmt;
export const parameterize = parameterize.parameterize;
export const addAutoIpAddressToSession = _mod767.addAutoIpAddressToSession;
export const addAutoIpAddressToUser = _mod767.addAutoIpAddressToUser;
export const addChildSpanToSpan = spanToJSON.addChildSpanToSpan;
export const convertSpanLinksForEnvelope = spanToJSON.convertSpanLinksForEnvelope;
export const getActiveSpan = spanToJSON.getActiveSpan;
export const getRootSpan = spanToJSON.getRootSpan;
export const getSpanDescendants = spanToJSON.getSpanDescendants;
export const getStatusMessage = spanToJSON.getStatusMessage;
export const spanIsSampled = spanToJSON.spanIsSampled;
export const spanTimeInputToSeconds = spanToJSON.spanTimeInputToSeconds;
export const spanToJSON = spanToJSON.spanToJSON;
export const spanToTraceContext = spanToJSON.spanToTraceContext;
export const spanToTraceHeader = spanToJSON.spanToTraceHeader;
export const updateSpanName = spanToJSON.updateSpanName;
export const _INTERNAL_setSpanForScope = _getSpanForScope._setSpanForScope;
export const parseSampleRate = _mod701.parseSampleRate;
export const applySdkMetadata = applySdkMetadata.applySdkMetadata;
export const getTraceData = _mod769.getTraceData;
export const getTraceMetaTags = _mod770.getTraceMetaTags;
export const debounce = _mod771.debounce;
export const extractQueryParamsFromUrl = winterCGHeadersToDict.extractQueryParamsFromUrl;
export const headersToDict = winterCGHeadersToDict.headersToDict;
export const httpHeadersToSpanAttributes = winterCGHeadersToDict.httpHeadersToSpanAttributes;
export const httpRequestToRequestData = winterCGHeadersToDict.httpRequestToRequestData;
export const winterCGHeadersToDict = winterCGHeadersToDict.winterCGHeadersToDict;
export const winterCGRequestToRequestData = winterCGHeadersToDict.winterCGRequestToRequestData;
export const DEFAULT_ENVIRONMENT = DEFAULT_ENVIRONMENT.DEFAULT_ENVIRONMENT;
export const DEV_ENVIRONMENT = DEFAULT_ENVIRONMENT.DEV_ENVIRONMENT;
export const addBreadcrumb = _mod773.addBreadcrumb;
export const functionToStringIntegration = _mod774.functionToStringIntegration;
export const eventFiltersIntegration = _mergeOptions.eventFiltersIntegration;
export const inboundFiltersIntegration = _mergeOptions.inboundFiltersIntegration;
export const linkedErrorsIntegration = linkedErrorsIntegration.linkedErrorsIntegration;
export const moduleMetadataIntegration = moduleMetadataIntegration.moduleMetadataIntegration;
export const requestDataIntegration = requestDataIntegration.requestDataIntegration;
export const captureConsoleIntegration = captureConsoleIntegration.captureConsoleIntegration;
export const dedupeIntegration = _shouldDropEvent.dedupeIntegration;
export const extraErrorDataIntegration = _extractErrorData.extraErrorDataIntegration;
export const rewriteFramesIntegration = generateIteratee.rewriteFramesIntegration;
export const instrumentSupabaseClient = markAsInstrumented.instrumentSupabaseClient;
export const supabaseIntegration = markAsInstrumented.supabaseIntegration;
export const zodErrorsIntegration = flattenIssue.zodErrorsIntegration;
export const thirdPartyErrorFilterIntegration = thirdPartyErrorFilterIntegration.thirdPartyErrorFilterIntegration;
export const consoleIntegration = _mod793.consoleIntegration;
export const featureFlagsIntegration = featureFlagsIntegration.featureFlagsIntegration;
export const growthbookIntegration = growthbookIntegration.growthbookIntegration;
export const profiler = profiler.profiler;
export const instrumentFetchRequest = _addTracingHeadersToFetchRequest.instrumentFetchRequest;
export const trpcMiddleware = trpcMiddleware.trpcMiddleware;
export const wrapMcpServerWithSentry = _mod800.wrapMcpServerWithSentry;
export const captureFeedback = captureFeedback.captureFeedback;
export const _INTERNAL_captureLog = _INTERNAL_captureSerializedLog._INTERNAL_captureLog;
export const _INTERNAL_captureSerializedLog = _INTERNAL_captureSerializedLog._INTERNAL_captureSerializedLog;
export const _INTERNAL_flushLogsBuffer = _INTERNAL_captureSerializedLog._INTERNAL_flushLogsBuffer;
export const logger = fmt;
export const consoleLoggingIntegration = consoleLoggingIntegration.consoleLoggingIntegration;
export const _INTERNAL_captureMetric = _INTERNAL_captureSerializedMetric._INTERNAL_captureMetric;
export const _INTERNAL_captureSerializedMetric = _INTERNAL_captureSerializedMetric._INTERNAL_captureSerializedMetric;
export const _INTERNAL_flushMetricsBuffer = _INTERNAL_captureSerializedMetric._INTERNAL_flushMetricsBuffer;
export const metrics = count;
export const createConsolaReporter = _mod819.createConsolaReporter;
export const addVercelAiProcessors = _mod820.addVercelAiProcessors;
export const _INTERNAL_cleanupToolCallSpan = convertPromptToMessages._INTERNAL_cleanupToolCallSpan;
export const _INTERNAL_getSpanForToolCallId = convertPromptToMessages._INTERNAL_getSpanForToolCallId;
export const instrumentOpenAiClient = extractRequestAttributes.instrumentOpenAiClient;
export const OPENAI_INTEGRATION_NAME = INSTRUMENTED_METHODS.OPENAI_INTEGRATION_NAME;
export const instrumentAnthropicAiClient = instrumentAnthropicAiClient.instrumentAnthropicAiClient;
export const ANTHROPIC_AI_INTEGRATION_NAME = ANTHROPIC_AI_INSTRUMENTED_METHODS.ANTHROPIC_AI_INTEGRATION_NAME;
export const instrumentGoogleGenAIClient = _mod838.instrumentGoogleGenAIClient;
export const GOOGLE_GENAI_INTEGRATION_NAME = CHATS_CREATE_METHOD.GOOGLE_GENAI_INTEGRATION_NAME;
export const createLangChainCallbackHandler = _mod842.createLangChainCallbackHandler;
export const LANGCHAIN_INTEGRATION_NAME = LANGCHAIN_INTEGRATION_NAME.LANGCHAIN_INTEGRATION_NAME;
export const instrumentLangGraph = instrumentLangGraph.instrumentLangGraph;
export const instrumentStateGraphCompile = instrumentLangGraph.instrumentStateGraphCompile;
export const LANGGRAPH_INTEGRATION_NAME = LANGGRAPH_INTEGRATION_NAME.LANGGRAPH_INTEGRATION_NAME;
export const _INTERNAL_FLAG_BUFFER_SIZE = _INTERNAL_FLAG_BUFFER_SIZE._INTERNAL_FLAG_BUFFER_SIZE;
export const _INTERNAL_MAX_FLAGS_PER_SPAN = _INTERNAL_FLAG_BUFFER_SIZE._INTERNAL_MAX_FLAGS_PER_SPAN;
export const _INTERNAL_addFeatureFlagToActiveSpan = _INTERNAL_FLAG_BUFFER_SIZE._INTERNAL_addFeatureFlagToActiveSpan;
export const _INTERNAL_copyFlagsFromScopeToEvent = _INTERNAL_FLAG_BUFFER_SIZE._INTERNAL_copyFlagsFromScopeToEvent;
export const _INTERNAL_insertFlagToScope = _INTERNAL_FLAG_BUFFER_SIZE._INTERNAL_insertFlagToScope;
export const applyAggregateErrorsToEvent = aggregateExceptionsFromError.applyAggregateErrorsToEvent;
export const getBreadcrumbLogLevelFromHttpStatusCode = _mod848.getBreadcrumbLogLevelFromHttpStatusCode;
export const getComponentName = _htmlElementAsString.getComponentName;
export const getLocationHref = _htmlElementAsString.getLocationHref;
export const htmlTreeAsString = _htmlElementAsString.htmlTreeAsString;
export const dsnFromString = _mod702.dsnFromString;
export const dsnToString = _mod702.dsnToString;
export const makeDsn = _mod702.makeDsn;
export const SentryError = _mod849.SentryError;
export const GLOBAL_OBJ = _mod686.GLOBAL_OBJ;
export const addConsoleInstrumentationHandler = instrumentConsole.addConsoleInstrumentationHandler;
export const addFetchEndInstrumentationHandler = _resolveResponse.addFetchEndInstrumentationHandler;
export const addFetchInstrumentationHandler = _resolveResponse.addFetchInstrumentationHandler;
export const addGlobalErrorInstrumentationHandler = instrumentError.addGlobalErrorInstrumentationHandler;
export const addGlobalUnhandledRejectionInstrumentationHandler =
  instrumentUnhandledRejection.addGlobalUnhandledRejectionInstrumentationHandler;
export const addHandler = _mod715.addHandler;
export const maybeInstrument = _mod715.maybeInstrument;
export const resetInstrumentationHandlers = _mod715.resetInstrumentationHandlers;
export const triggerHandlers = _mod715.triggerHandlers;
export const isDOMError = _mod692.isDOMError;
export const isDOMException = _mod692.isDOMException;
export const isElement = _mod692.isElement;
export const isError = _mod692.isError;
export const isErrorEvent = _mod692.isErrorEvent;
export const isEvent = _mod692.isEvent;
export const isInstanceOf = _mod692.isInstanceOf;
export const isParameterizedString = _mod692.isParameterizedString;
export const isPlainObject = _mod692.isPlainObject;
export const isPrimitive = _mod692.isPrimitive;
export const isRegExp = _mod692.isRegExp;
export const isString = _mod692.isString;
export const isSyntheticEvent = _mod692.isSyntheticEvent;
export const isThenable = _mod692.isThenable;
export const isVueViewModel = _mod692.isVueViewModel;
export const isBrowser = dynamicRequire.isBrowser;
export const CONSOLE_LEVELS = consoleSandbox.CONSOLE_LEVELS;
export const consoleSandbox = consoleSandbox.consoleSandbox;
export const debug = consoleSandbox.debug;
export const originalConsoleMethods = consoleSandbox.originalConsoleMethods;
export const addContextToFrame = uuid4.addContextToFrame;
export const addExceptionMechanism = uuid4.addExceptionMechanism;
export const addExceptionTypeValue = uuid4.addExceptionTypeValue;
export const checkOrSetAlreadyCaught = uuid4.checkOrSetAlreadyCaught;
export const getEventDescription = uuid4.getEventDescription;
export const parseSemver = uuid4.parseSemver;
export const uuid4 = uuid4.uuid4;
export const isNodeEnv = _mod853.isNodeEnv;
export const loadModule = _mod853.loadModule;
export const normalize = normalize.normalize;
export const normalizeToSize = normalize.normalizeToSize;
export const normalizeUrlToBase = normalize.normalizeUrlToBase;
export const addNonEnumerableProperty = _mod687.addNonEnumerableProperty;
export const convertToPlainObject = _mod687.convertToPlainObject;
export const dropUndefinedKeys = _mod687.dropUndefinedKeys;
export const extractExceptionKeysForMessage = _mod687.extractExceptionKeysForMessage;
export const fill = _mod687.fill;
export const getOriginalFunction = _mod687.getOriginalFunction;
export const markFunctionWrapped = _mod687.markFunctionWrapped;
export const objectify = _mod687.objectify;
export const basename = resolve.basename;
export const dirname = resolve.dirname;
export const isAbsolute = resolve.isAbsolute;
export const join = resolve.join;
export const normalizePath = resolve.normalizePath;
export const relative = resolve.relative;
export const resolve = resolve.resolve;
export const SENTRY_BUFFER_FULL_ERROR = SENTRY_BUFFER_FULL_ERROR.SENTRY_BUFFER_FULL_ERROR;
export const makePromiseBuffer = SENTRY_BUFFER_FULL_ERROR.makePromiseBuffer;
export const severityLevelFromString = severityLevelFromString.severityLevelFromString;
export const replaceExports = replaceExports.replaceExports;
export const UNKNOWN_FUNCTION = _mod698.UNKNOWN_FUNCTION;
export const createStackParser = _mod698.createStackParser;
export const getFramesFromEvent = _mod698.getFramesFromEvent;
export const getFunctionName = _mod698.getFunctionName;
export const stackParserFromStackParserOptions = _mod698.stackParserFromStackParserOptions;
export const stripSentryFramesAndReverse = _mod698.stripSentryFramesAndReverse;
export const filenameIsInApp = filenameIsInApp.filenameIsInApp;
export const node = filenameIsInApp.node;
export const nodeStackLineParser = filenameIsInApp.nodeStackLineParser;
export const isMatchingPattern = _mod697.isMatchingPattern;
export const safeJoin = _mod697.safeJoin;
export const snipLine = _mod697.snipLine;
export const stringMatchesSomePattern = _mod697.stringMatchesSomePattern;
export const truncate = _mod697.truncate;
export const isNativeFunction = _isFetchSupported.isNativeFunction;
export const supportsDOMError = _isFetchSupported.supportsDOMError;
export const supportsDOMException = _isFetchSupported.supportsDOMException;
export const supportsErrorEvent = _isFetchSupported.supportsErrorEvent;
export const supportsFetch = _isFetchSupported.supportsFetch;
export const supportsHistory = _isFetchSupported.supportsHistory;
export const supportsNativeFetch = _isFetchSupported.supportsNativeFetch;
export const supportsReferrerPolicy = _isFetchSupported.supportsReferrerPolicy;
export const supportsReportingObserver = _isFetchSupported.supportsReportingObserver;
export const SyncPromise = SyncPromise.SyncPromise;
export const rejectedSyncPromise = SyncPromise.rejectedSyncPromise;
export const resolvedSyncPromise = SyncPromise.resolvedSyncPromise;
export const browserPerformanceTimeOrigin = dateTimestampInSeconds.browserPerformanceTimeOrigin;
export const dateTimestampInSeconds = dateTimestampInSeconds.dateTimestampInSeconds;
export const timestampInSeconds = dateTimestampInSeconds.timestampInSeconds;
export const TRACEPARENT_REGEXP = _mod699.TRACEPARENT_REGEXP;
export const extractTraceparentData = _mod699.extractTraceparentData;
export const generateSentryTraceHeader = _mod699.generateSentryTraceHeader;
export const generateTraceparentHeader = _mod699.generateTraceparentHeader;
export const propagationContextFromHeaders = _mod699.propagationContextFromHeaders;
export const shouldContinueTrace = _mod699.shouldContinueTrace;
export const getSDKSource = _mod854.getSDKSource;
export const isBrowserBundle = _mod854.isBrowserBundle;
export const addItemToEnvelope = forEachEnvelopeItem.addItemToEnvelope;
export const createAttachmentEnvelopeItem = forEachEnvelopeItem.createAttachmentEnvelopeItem;
export const createEnvelope = forEachEnvelopeItem.createEnvelope;
export const createEventEnvelopeHeaders = forEachEnvelopeItem.createEventEnvelopeHeaders;
export const createSpanEnvelopeItem = forEachEnvelopeItem.createSpanEnvelopeItem;
export const envelopeContainsItemType = forEachEnvelopeItem.envelopeContainsItemType;
export const envelopeItemTypeToDataCategory = forEachEnvelopeItem.envelopeItemTypeToDataCategory;
export const forEachEnvelopeItem = forEachEnvelopeItem.forEachEnvelopeItem;
export const getSdkMetadataForEnvelopeHeader = forEachEnvelopeItem.getSdkMetadataForEnvelopeHeader;
export const parseEnvelope = forEachEnvelopeItem.parseEnvelope;
export const serializeEnvelope = forEachEnvelopeItem.serializeEnvelope;
export const createClientReportEnvelope = _mod754.createClientReportEnvelope;
export const DEFAULT_RETRY_AFTER = disabledUntil.DEFAULT_RETRY_AFTER;
export const disabledUntil = disabledUntil.disabledUntil;
export const isRateLimited = disabledUntil.isRateLimited;
export const parseRetryAfterHeader = disabledUntil.parseRetryAfterHeader;
export const updateRateLimits = disabledUntil.updateRateLimits;
export const MAX_BAGGAGE_STRING_LENGTH = MAX_BAGGAGE_STRING_LENGTH.MAX_BAGGAGE_STRING_LENGTH;
export const SENTRY_BAGGAGE_KEY_PREFIX = MAX_BAGGAGE_STRING_LENGTH.SENTRY_BAGGAGE_KEY_PREFIX;
export const SENTRY_BAGGAGE_KEY_PREFIX_REGEX = MAX_BAGGAGE_STRING_LENGTH.SENTRY_BAGGAGE_KEY_PREFIX_REGEX;
export const baggageHeaderToDynamicSamplingContext = MAX_BAGGAGE_STRING_LENGTH.baggageHeaderToDynamicSamplingContext;
export const dynamicSamplingContextToSentryBaggageHeader =
  MAX_BAGGAGE_STRING_LENGTH.dynamicSamplingContextToSentryBaggageHeader;
export const objectToBaggageHeader = MAX_BAGGAGE_STRING_LENGTH.objectToBaggageHeader;
export const parseBaggageHeader = MAX_BAGGAGE_STRING_LENGTH.parseBaggageHeader;
export const getHttpSpanDetailsFromUrlObject = _mod765.getHttpSpanDetailsFromUrlObject;
export const getSanitizedUrlString = _mod765.getSanitizedUrlString;
export const getSanitizedUrlStringFromUrlObject = _mod765.getSanitizedUrlStringFromUrlObject;
export const isURLObjectRelative = _mod765.isURLObjectRelative;
export const parseStringToURLObject = _mod765.parseStringToURLObject;
export const parseUrl = _mod765.parseUrl;
export const stripDataUrlContent = _mod765.stripDataUrlContent;
export const stripUrlQueryAndFragment = _mod765.stripUrlQueryAndFragment;
export const _INTERNAL_enhanceErrorWithSentryInfo = exceptionFromError._enhanceErrorWithSentryInfo;
export const eventFromMessage = exceptionFromError.eventFromMessage;
export const eventFromUnknownInput = exceptionFromError.eventFromUnknownInput;
export const exceptionFromError = exceptionFromError.exceptionFromError;
export const parseStackFrames = exceptionFromError.parseStackFrames;
export const callFrameToStackFrame = callFrameToStackFrame.callFrameToStackFrame;
export const watchdogTimer = callFrameToStackFrame.watchdogTimer;
export const LRUMap = LRUMap.LRUMap;
export const generateSpanId = generateSpanId.generateSpanId;
export const generateTraceId = generateSpanId.generateTraceId;
export const vercelWaitUntil = vercelWaitUntil.vercelWaitUntil;
export const flushIfServerless = flushWithTimeout.flushIfServerless;
export const SDK_VERSION = SDK_VERSION.SDK_VERSION;
export const getDebugImagesForResources = _mod739.getDebugImagesForResources;
export const getFilenameToDebugIdMap = _mod739.getFilenameToDebugIdMap;
export const getFilenameToMetadataMap = _mod779.getFilenameToMetadataMap;
export const escapeStringForRegex = escapeStringForRegex.escapeStringForRegex;
export const _INTERNAL_safeDateNow = safeDateNow.safeDateNow;
export const _INTERNAL_safeMathRandom = safeDateNow.safeMathRandom;
export const _INTERNAL_withRandomSafeContext = safeDateNow.withRandomSafeContext;
