// === Module 693: ? ===

// Module 693
import _mod694 from "module_694" /* 694 */;
import spanToJSON from "spanToJSON" /* 695 */;
import unwrapScopeFromWeakRef from "unwrapScopeFromWeakRef" /* 696 */;
import _mod697 from "module_697" /* 697 */;
import _mod698 from "module_698" /* 698 */;
import consoleSandbox from "consoleSandbox" /* 700 */;
import _mod701 from "module_701" /* 701 */;
import SDK_VERSION from "SDK_VERSION" /* 702 */;
import _mod703 from "module_703" /* 703 */;
import _htmlElementAsString from "_htmlElementAsString" /* 704 */;
import generateSpanId from "generateSpanId" /* 705 */;
import uuid4 from "uuid4" /* 706 */;
import safeDateNow from "safeDateNow" /* 707 */;
import _mod708 from "module_708" /* 708 */;
import _mod709 from "module_709" /* 709 */;
import _mod710 from "module_710" /* 710 */;
import MAX_BAGGAGE_STRING_LENGTH from "MAX_BAGGAGE_STRING_LENGTH" /* 711 */;
import _mod712 from "module_712" /* 712 */;
import _mod713 from "module_713" /* 713 */;
import dateTimestampInSeconds from "dateTimestampInSeconds" /* 714 */;
import SEMANTIC_ATTRIBUTE_CACHE_HIT from "SEMANTIC_ATTRIBUTE_CACHE_HIT" /* 715 */;
import SPAN_STATUS_ERROR from "SPAN_STATUS_ERROR" /* 716 */;
import _mod717 from "module_717" /* 717 */;
import Scope from "Scope" /* 719 */;
import _getSpanForScope from "_getSpanForScope" /* 720 */;
import closeSession from "closeSession" /* 721 */;
import _mod723 from "module_723" /* 723 */;
import _mod724 from "module_724" /* 724 */;
import instrumentError from "instrumentError" /* 725 */;
import _mod726 from "module_726" /* 726 */;
import instrumentUnhandledRejection from "instrumentUnhandledRejection" /* 727 */;
import TRACING_DEFAULTS from "TRACING_DEFAULTS" /* 728 */;
import _mod731 from "module_731" /* 731 */;
import SentryNonRecordingSpan from "SentryNonRecordingSpan" /* 732 */;
import _mod733 from "module_733" /* 733 */;
import DEFAULT_ENVIRONMENT from "DEFAULT_ENVIRONMENT" /* 734 */;
import _mod736 from "module_736" /* 736 */;
import logSpanEnd from "logSpanEnd" /* 737 */;
import timedEventsToMeasurements from "timedEventsToMeasurements" /* 738 */;
import _enhanceEventWithSdkInfo from "_enhanceEventWithSdkInfo" /* 739 */;
import forEachEnvelopeItem from "forEachEnvelopeItem" /* 740 */;
import normalize from "normalize" /* 741 */;
import _mod742 from "module_742" /* 742 */;
import _mod743 from "module_743" /* 743 */;
import sampleSpan from "sampleSpan" /* 744 */;
import captureCheckIn from "captureCheckIn" /* 745 */;
import applyClientOptions from "applyClientOptions" /* 746 */;
import mergeScopeData from "mergeScopeData" /* 747 */;
import _notifyEventProcessors from "_notifyEventProcessors" /* 748 */;
import SyncPromise from "SyncPromise" /* 749 */;
import _mod750 from "module_750" /* 750 */;
import _mod751 from "module_751" /* 751 */;
import _mod752 from "module_752" /* 752 */;
import SENTRY_BUFFER_FULL_ERROR from "SENTRY_BUFFER_FULL_ERROR" /* 753 */;
import DEFAULT_TRANSPORT_BUFFER_SIZE from "DEFAULT_TRANSPORT_BUFFER_SIZE" /* 754 */;
import disabledUntil from "disabledUntil" /* 755 */;
import _INTERNAL_captureSerializedLog from "_INTERNAL_captureSerializedLog" /* 756 */;
import _INTERNAL_captureSerializedMetric from "_INTERNAL_captureSerializedMetric" /* 761 */;
import setupIntegration from "setupIntegration" /* 763 */;
import _mod765 from "module_765" /* 765 */;
import _mod767 from "module_767" /* 767 */;
import exceptionFromError from "exceptionFromError" /* 769 */;
import _mod770 from "module_770" /* 770 */;
import _mod771 from "module_771" /* 771 */;
import MIN_DELAY from "MIN_DELAY" /* 772 */;
import eventFromEnvelope from "eventFromEnvelope" /* 773 */;
import _INTERNAL_clearAiProviderSkips from "_INTERNAL_clearAiProviderSkips" /* 774 */;
import _mod775 from "module_775" /* 775 */;
import _mod776 from "module_776" /* 776 */;
import parameterize from "parameterize" /* 777 */;
import _mod778 from "module_778" /* 778 */;
import applySdkMetadata from "applySdkMetadata" /* 779 */;
import _mod780 from "module_780" /* 780 */;
import _mod781 from "module_781" /* 781 */;
import _mod782 from "module_782" /* 782 */;
import winterCGHeadersToDict from "winterCGHeadersToDict" /* 783 */;
import _mod784 from "module_784" /* 784 */;
import _mod785 from "module_785" /* 785 */;
import _mergeOptions from "_mergeOptions" /* 786 */;
import linkedErrorsIntegration from "linkedErrorsIntegration" /* 787 */;
import aggregateExceptionsFromError from "aggregateExceptionsFromError" /* 788 */;
import moduleMetadataIntegration from "moduleMetadataIntegration" /* 789 */;
import _mod790 from "module_790" /* 790 */;
import requestDataIntegration from "requestDataIntegration" /* 791 */;
import captureConsoleIntegration from "captureConsoleIntegration" /* 794 */;
import instrumentConsole from "instrumentConsole" /* 795 */;
import severityLevelFromString from "severityLevelFromString" /* 796 */;
import _shouldDropEvent from "_shouldDropEvent" /* 797 */;
import _extractErrorData from "_extractErrorData" /* 798 */;
import generateIteratee from "generateIteratee" /* 799 */;
import resolve from "resolve" /* 800 */;
import markAsInstrumented from "markAsInstrumented" /* 801 */;
import flattenIssue from "flattenIssue" /* 802 */;
import thirdPartyErrorFilterIntegration from "thirdPartyErrorFilterIntegration" /* 803 */;
import _mod804 from "module_804" /* 804 */;
import featureFlagsIntegration from "featureFlagsIntegration" /* 805 */;
import _INTERNAL_FLAG_BUFFER_SIZE from "_INTERNAL_FLAG_BUFFER_SIZE" /* 806 */;
import growthbookIntegration from "growthbookIntegration" /* 807 */;
import profiler from "profiler" /* 808 */;
import _addTracingHeadersToFetchRequest from "_addTracingHeadersToFetchRequest" /* 809 */;
import trpcMiddleware from "trpcMiddleware" /* 810 */;
import _mod811 from "module_811" /* 811 */;
import captureFeedback from "captureFeedback" /* 825 */;
import fmt from "fmt" /* 826 */;
import consoleLoggingIntegration from "consoleLoggingIntegration" /* 827 */;
import count from "count" /* 829 */;
import _mod830 from "module_830" /* 830 */;
import _mod831 from "module_831" /* 831 */;
import convertPromptToMessages from "convertPromptToMessages" /* 833 */;
import extractRequestAttributes from "extractRequestAttributes" /* 838 */;
import INSTRUMENTED_METHODS from "INSTRUMENTED_METHODS" /* 840 */;
import instrumentAnthropicAiClient from "instrumentAnthropicAiClient" /* 845 */;
import ANTHROPIC_AI_INSTRUMENTED_METHODS from "ANTHROPIC_AI_INSTRUMENTED_METHODS" /* 847 */;
import _mod849 from "module_849" /* 849 */;
import CHATS_CREATE_METHOD from "CHATS_CREATE_METHOD" /* 850 */;
import _mod853 from "module_853" /* 853 */;
import LANGCHAIN_INTEGRATION_NAME from "LANGCHAIN_INTEGRATION_NAME" /* 855 */;
import instrumentLangGraph from "instrumentLangGraph" /* 856 */;
import LANGGRAPH_INTEGRATION_NAME from "LANGGRAPH_INTEGRATION_NAME" /* 857 */;
import _mod859 from "module_859" /* 859 */;
import _mod860 from "module_860" /* 860 */;
import _resolveResponse from "_resolveResponse" /* 861 */;
import _isFetchSupported from "_isFetchSupported" /* 862 */;
import dynamicRequire from "dynamicRequire" /* 863 */;
import _mod864 from "module_864" /* 864 */;
import _mod865 from "module_865" /* 865 */;
import replaceExports from "replaceExports" /* 866 */;
import filenameIsInApp from "filenameIsInApp" /* 867 */;
import callFrameToStackFrame from "callFrameToStackFrame" /* 868 */;
import LRUMap from "LRUMap" /* 869 */;
import vercelWaitUntil from "vercelWaitUntil" /* 870 */;
import flushWithTimeout from "flushWithTimeout" /* 871 */;
import escapeStringForRegex from "escapeStringForRegex" /* 872 */;

Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });

export const registerSpanErrorInstrumentation = _mod694.registerSpanErrorInstrumentation;
export const getCapturedScopesOnSpan = unwrapScopeFromWeakRef.getCapturedScopesOnSpan;
export const setCapturedScopesOnSpan = unwrapScopeFromWeakRef.setCapturedScopesOnSpan;
export const TRACING_DEFAULTS = TRACING_DEFAULTS.TRACING_DEFAULTS;
export const startIdleSpan = TRACING_DEFAULTS.startIdleSpan;
export const SentrySpan = _mod736.SentrySpan;
export const SentryNonRecordingSpan = SentryNonRecordingSpan.SentryNonRecordingSpan;
export const SPAN_STATUS_ERROR = SPAN_STATUS_ERROR.SPAN_STATUS_ERROR;
export const SPAN_STATUS_OK = SPAN_STATUS_ERROR.SPAN_STATUS_OK;
export const SPAN_STATUS_UNSET = SPAN_STATUS_ERROR.SPAN_STATUS_UNSET;
export const getSpanStatusFromHttpCode = SPAN_STATUS_ERROR.getSpanStatusFromHttpCode;
export const setHttpStatus = SPAN_STATUS_ERROR.setHttpStatus;
export const continueTrace = _mod742.continueTrace;
export const startInactiveSpan = _mod742.startInactiveSpan;
export const startNewTrace = _mod742.startNewTrace;
export const startSpan = _mod742.startSpan;
export const startSpanManual = _mod742.startSpanManual;
export const suppressTracing = _mod742.suppressTracing;
export const withActiveSpan = _mod742.withActiveSpan;
export const getDynamicSamplingContextFromClient = _mod733.getDynamicSamplingContextFromClient;
export const getDynamicSamplingContextFromScope = _mod733.getDynamicSamplingContextFromScope;
export const getDynamicSamplingContextFromSpan = _mod733.getDynamicSamplingContextFromSpan;
export const spanToBaggageHeader = _mod733.spanToBaggageHeader;
export const setMeasurement = timedEventsToMeasurements.setMeasurement;
export const timedEventsToMeasurements = timedEventsToMeasurements.timedEventsToMeasurements;
export const sampleSpan = sampleSpan.sampleSpan;
export const logSpanEnd = logSpanEnd.logSpanEnd;
export const logSpanStart = logSpanEnd.logSpanStart;
export const SEMANTIC_ATTRIBUTE_CACHE_HIT = SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_ATTRIBUTE_CACHE_HIT;
export const SEMANTIC_ATTRIBUTE_CACHE_ITEM_SIZE = SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_ATTRIBUTE_CACHE_ITEM_SIZE;
export const SEMANTIC_ATTRIBUTE_CACHE_KEY = SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_ATTRIBUTE_CACHE_KEY;
export const SEMANTIC_ATTRIBUTE_EXCLUSIVE_TIME = SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_ATTRIBUTE_EXCLUSIVE_TIME;
export const SEMANTIC_ATTRIBUTE_HTTP_REQUEST_METHOD = SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_ATTRIBUTE_HTTP_REQUEST_METHOD;
export const SEMANTIC_ATTRIBUTE_PROFILE_ID = SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_ATTRIBUTE_PROFILE_ID;
export const SEMANTIC_ATTRIBUTE_SENTRY_CUSTOM_SPAN_NAME = SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_ATTRIBUTE_SENTRY_CUSTOM_SPAN_NAME;
export const SEMANTIC_ATTRIBUTE_SENTRY_IDLE_SPAN_FINISH_REASON = SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_ATTRIBUTE_SENTRY_IDLE_SPAN_FINISH_REASON;
export const SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_UNIT = SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_UNIT;
export const SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_VALUE = SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_VALUE;
export const SEMANTIC_ATTRIBUTE_SENTRY_OP = SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_ATTRIBUTE_SENTRY_OP;
export const SEMANTIC_ATTRIBUTE_SENTRY_ORIGIN = SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_ATTRIBUTE_SENTRY_ORIGIN;
export const SEMANTIC_ATTRIBUTE_SENTRY_PREVIOUS_TRACE_SAMPLE_RATE = SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_ATTRIBUTE_SENTRY_PREVIOUS_TRACE_SAMPLE_RATE;
export const SEMANTIC_ATTRIBUTE_SENTRY_SAMPLE_RATE = SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_ATTRIBUTE_SENTRY_SAMPLE_RATE;
export const SEMANTIC_ATTRIBUTE_SENTRY_SOURCE = SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_ATTRIBUTE_SENTRY_SOURCE;
export const SEMANTIC_ATTRIBUTE_URL_FULL = SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_ATTRIBUTE_URL_FULL;
export const SEMANTIC_LINK_ATTRIBUTE_LINK_TYPE = SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_LINK_ATTRIBUTE_LINK_TYPE;
export const createEventEnvelope = _enhanceEventWithSdkInfo.createEventEnvelope;
export const createSessionEnvelope = _enhanceEventWithSdkInfo.createSessionEnvelope;
export const createSpanEnvelope = _enhanceEventWithSdkInfo.createSpanEnvelope;
export const addEventProcessor = captureCheckIn.addEventProcessor;
export const captureCheckIn = captureCheckIn.captureCheckIn;
export const captureEvent = captureCheckIn.captureEvent;
export const captureException = captureCheckIn.captureException;
export const captureMessage = captureCheckIn.captureMessage;
export const captureSession = captureCheckIn.captureSession;
export const close = captureCheckIn.close;
export const endSession = captureCheckIn.endSession;
export const flush = captureCheckIn.flush;
export const isEnabled = captureCheckIn.isEnabled;
export const isInitialized = captureCheckIn.isInitialized;
export const lastEventId = captureCheckIn.lastEventId;
export const setContext = captureCheckIn.setContext;
export const setExtra = captureCheckIn.setExtra;
export const setExtras = captureCheckIn.setExtras;
export const setTag = captureCheckIn.setTag;
export const setTags = captureCheckIn.setTags;
export const setUser = captureCheckIn.setUser;
export const startSession = captureCheckIn.startSession;
export const withMonitor = captureCheckIn.withMonitor;
export const getClient = _mod724.getClient;
export const getCurrentScope = _mod724.getCurrentScope;
export const getGlobalScope = _mod724.getGlobalScope;
export const getIsolationScope = _mod724.getIsolationScope;
export const getTraceContextFromScope = _mod724.getTraceContextFromScope;
export const withIsolationScope = _mod724.withIsolationScope;
export const withScope = _mod724.withScope;
export const getDefaultCurrentScope = _mod723.getDefaultCurrentScope;
export const getDefaultIsolationScope = _mod723.getDefaultIsolationScope;
export const setAsyncContextStrategy = _mod717.setAsyncContextStrategy;
export const getGlobalSingleton = _mod701.getGlobalSingleton;
export const getMainCarrier = _mod701.getMainCarrier;
export const closeSession = closeSession.closeSession;
export const makeSession = closeSession.makeSession;
export const updateSession = closeSession.updateSession;
export const Scope = Scope.Scope;
export const notifyEventProcessors = _notifyEventProcessors.notifyEventProcessors;
export const getEnvelopeEndpointWithUrlEncodedAuth = _mod751.getEnvelopeEndpointWithUrlEncodedAuth;
export const getReportDialogEndpoint = _mod751.getReportDialogEndpoint;
export const Client = _mod752.Client;
export const ServerRuntimeClient = _mod767.ServerRuntimeClient;
export const initAndBind = _mod771.initAndBind;
export const setCurrentClient = _mod771.setCurrentClient;
export const createTransport = DEFAULT_TRANSPORT_BUFFER_SIZE.createTransport;
export const makeOfflineTransport = MIN_DELAY.makeOfflineTransport;
export const MULTIPLEXED_TRANSPORT_EXTRA_KEY = eventFromEnvelope.MULTIPLEXED_TRANSPORT_EXTRA_KEY;
export const makeMultiplexedTransport = eventFromEnvelope.makeMultiplexedTransport;
export const addIntegration = setupIntegration.addIntegration;
export const defineIntegration = setupIntegration.defineIntegration;
export const getIntegrationsToSetup = setupIntegration.getIntegrationsToSetup;
export const installedIntegrations = setupIntegration.installedIntegrations;
export const _INTERNAL_clearAiProviderSkips = _INTERNAL_clearAiProviderSkips._INTERNAL_clearAiProviderSkips;
export const _INTERNAL_shouldSkipAiProviderWrapping = _INTERNAL_clearAiProviderSkips._INTERNAL_shouldSkipAiProviderWrapping;
export const _INTERNAL_skipAiProviderWrapping = _INTERNAL_clearAiProviderSkips._INTERNAL_skipAiProviderWrapping;
export const applyScopeDataToEvent = mergeScopeData.applyScopeDataToEvent;
export const getCombinedScopeData = mergeScopeData.getCombinedScopeData;
export const mergeScopeData = mergeScopeData.mergeScopeData;
export const prepareEvent = applyClientOptions.prepareEvent;
export const createCheckInEnvelope = _mod770.createCheckInEnvelope;
export const hasSpansEnabled = _mod731.hasSpansEnabled;
export const isSentryRequestUrl = _mod775.isSentryRequestUrl;
export const handleCallbackErrors = _mod743.handleCallbackErrors;
export const fmt = parameterize.fmt;
export const parameterize = parameterize.parameterize;
export const addAutoIpAddressToSession = _mod778.addAutoIpAddressToSession;
export const addAutoIpAddressToUser = _mod778.addAutoIpAddressToUser;
export const addChildSpanToSpan = spanToJSON.addChildSpanToSpan;
export const convertSpanLinksForEnvelope = spanToJSON.convertSpanLinksForEnvelope;
export const getActiveSpan = spanToJSON.getActiveSpan;
export const getRootSpan = spanToJSON.getRootSpan;
export const getSpanDescendants = spanToJSON.getSpanDescendants;
export const getStatusMessage = spanToJSON.getStatusMessage;
export const spanIsSampled = spanToJSON.spanIsSampled;
export const spanTimeInputToSeconds = spanToJSON.spanTimeInputToSeconds;
export const spanToJSON = spanToJSON.spanToJSON;
export const spanToTraceContext = spanToJSON.spanToTraceContext;
export const spanToTraceHeader = spanToJSON.spanToTraceHeader;
export const updateSpanName = spanToJSON.updateSpanName;
export const _INTERNAL_setSpanForScope = _getSpanForScope._setSpanForScope;
export const parseSampleRate = _mod712.parseSampleRate;
export const applySdkMetadata = applySdkMetadata.applySdkMetadata;
export const getTraceData = _mod780.getTraceData;
export const getTraceMetaTags = _mod781.getTraceMetaTags;
export const debounce = _mod782.debounce;
export const extractQueryParamsFromUrl = winterCGHeadersToDict.extractQueryParamsFromUrl;
export const headersToDict = winterCGHeadersToDict.headersToDict;
export const httpHeadersToSpanAttributes = winterCGHeadersToDict.httpHeadersToSpanAttributes;
export const httpRequestToRequestData = winterCGHeadersToDict.httpRequestToRequestData;
export const winterCGHeadersToDict = winterCGHeadersToDict.winterCGHeadersToDict;
export const winterCGRequestToRequestData = winterCGHeadersToDict.winterCGRequestToRequestData;
export const DEFAULT_ENVIRONMENT = DEFAULT_ENVIRONMENT.DEFAULT_ENVIRONMENT;
export const DEV_ENVIRONMENT = DEFAULT_ENVIRONMENT.DEV_ENVIRONMENT;
export const addBreadcrumb = _mod784.addBreadcrumb;
export const functionToStringIntegration = _mod785.functionToStringIntegration;
export const eventFiltersIntegration = _mergeOptions.eventFiltersIntegration;
export const inboundFiltersIntegration = _mergeOptions.inboundFiltersIntegration;
export const linkedErrorsIntegration = linkedErrorsIntegration.linkedErrorsIntegration;
export const moduleMetadataIntegration = moduleMetadataIntegration.moduleMetadataIntegration;
export const requestDataIntegration = requestDataIntegration.requestDataIntegration;
export const captureConsoleIntegration = captureConsoleIntegration.captureConsoleIntegration;
export const dedupeIntegration = _shouldDropEvent.dedupeIntegration;
export const extraErrorDataIntegration = _extractErrorData.extraErrorDataIntegration;
export const rewriteFramesIntegration = generateIteratee.rewriteFramesIntegration;
export const instrumentSupabaseClient = markAsInstrumented.instrumentSupabaseClient;
export const supabaseIntegration = markAsInstrumented.supabaseIntegration;
export const zodErrorsIntegration = flattenIssue.zodErrorsIntegration;
export const thirdPartyErrorFilterIntegration = thirdPartyErrorFilterIntegration.thirdPartyErrorFilterIntegration;
export const consoleIntegration = _mod804.consoleIntegration;
export const featureFlagsIntegration = featureFlagsIntegration.featureFlagsIntegration;
export const growthbookIntegration = growthbookIntegration.growthbookIntegration;
export const profiler = profiler.profiler;
export const instrumentFetchRequest = _addTracingHeadersToFetchRequest.instrumentFetchRequest;
export const trpcMiddleware = trpcMiddleware.trpcMiddleware;
export const wrapMcpServerWithSentry = _mod811.wrapMcpServerWithSentry;
export const captureFeedback = captureFeedback.captureFeedback;
export const _INTERNAL_captureLog = _INTERNAL_captureSerializedLog._INTERNAL_captureLog;
export const _INTERNAL_captureSerializedLog = _INTERNAL_captureSerializedLog._INTERNAL_captureSerializedLog;
export const _INTERNAL_flushLogsBuffer = _INTERNAL_captureSerializedLog._INTERNAL_flushLogsBuffer;
export const logger = fmt;
export const consoleLoggingIntegration = consoleLoggingIntegration.consoleLoggingIntegration;
export const _INTERNAL_captureMetric = _INTERNAL_captureSerializedMetric._INTERNAL_captureMetric;
export const _INTERNAL_captureSerializedMetric = _INTERNAL_captureSerializedMetric._INTERNAL_captureSerializedMetric;
export const _INTERNAL_flushMetricsBuffer = _INTERNAL_captureSerializedMetric._INTERNAL_flushMetricsBuffer;
export const metrics = count;
export const createConsolaReporter = _mod830.createConsolaReporter;
export const addVercelAiProcessors = _mod831.addVercelAiProcessors;
export const _INTERNAL_cleanupToolCallSpan = convertPromptToMessages._INTERNAL_cleanupToolCallSpan;
export const _INTERNAL_getSpanForToolCallId = convertPromptToMessages._INTERNAL_getSpanForToolCallId;
export const instrumentOpenAiClient = extractRequestAttributes.instrumentOpenAiClient;
export const OPENAI_INTEGRATION_NAME = INSTRUMENTED_METHODS.OPENAI_INTEGRATION_NAME;
export const instrumentAnthropicAiClient = instrumentAnthropicAiClient.instrumentAnthropicAiClient;
export const ANTHROPIC_AI_INTEGRATION_NAME = ANTHROPIC_AI_INSTRUMENTED_METHODS.ANTHROPIC_AI_INTEGRATION_NAME;
export const instrumentGoogleGenAIClient = _mod849.instrumentGoogleGenAIClient;
export const GOOGLE_GENAI_INTEGRATION_NAME = CHATS_CREATE_METHOD.GOOGLE_GENAI_INTEGRATION_NAME;
export const createLangChainCallbackHandler = _mod853.createLangChainCallbackHandler;
export const LANGCHAIN_INTEGRATION_NAME = LANGCHAIN_INTEGRATION_NAME.LANGCHAIN_INTEGRATION_NAME;
export const instrumentLangGraph = instrumentLangGraph.instrumentLangGraph;
export const instrumentStateGraphCompile = instrumentLangGraph.instrumentStateGraphCompile;
export const LANGGRAPH_INTEGRATION_NAME = LANGGRAPH_INTEGRATION_NAME.LANGGRAPH_INTEGRATION_NAME;
export const _INTERNAL_FLAG_BUFFER_SIZE = _INTERNAL_FLAG_BUFFER_SIZE._INTERNAL_FLAG_BUFFER_SIZE;
export const _INTERNAL_MAX_FLAGS_PER_SPAN = _INTERNAL_FLAG_BUFFER_SIZE._INTERNAL_MAX_FLAGS_PER_SPAN;
export const _INTERNAL_addFeatureFlagToActiveSpan = _INTERNAL_FLAG_BUFFER_SIZE._INTERNAL_addFeatureFlagToActiveSpan;
export const _INTERNAL_copyFlagsFromScopeToEvent = _INTERNAL_FLAG_BUFFER_SIZE._INTERNAL_copyFlagsFromScopeToEvent;
export const _INTERNAL_insertFlagToScope = _INTERNAL_FLAG_BUFFER_SIZE._INTERNAL_insertFlagToScope;
export const applyAggregateErrorsToEvent = aggregateExceptionsFromError.applyAggregateErrorsToEvent;
export const getBreadcrumbLogLevelFromHttpStatusCode = _mod859.getBreadcrumbLogLevelFromHttpStatusCode;
export const getComponentName = _htmlElementAsString.getComponentName;
export const getLocationHref = _htmlElementAsString.getLocationHref;
export const htmlTreeAsString = _htmlElementAsString.htmlTreeAsString;
export const dsnFromString = _mod713.dsnFromString;
export const dsnToString = _mod713.dsnToString;
export const makeDsn = _mod713.makeDsn;
export const SentryError = _mod860.SentryError;
export const GLOBAL_OBJ = _mod697.GLOBAL_OBJ;
export const addConsoleInstrumentationHandler = instrumentConsole.addConsoleInstrumentationHandler;
export const addFetchEndInstrumentationHandler = _resolveResponse.addFetchEndInstrumentationHandler;
export const addFetchInstrumentationHandler = _resolveResponse.addFetchInstrumentationHandler;
export const addGlobalErrorInstrumentationHandler = instrumentError.addGlobalErrorInstrumentationHandler;
export const addGlobalUnhandledRejectionInstrumentationHandler = instrumentUnhandledRejection.addGlobalUnhandledRejectionInstrumentationHandler;
export const addHandler = _mod726.addHandler;
export const maybeInstrument = _mod726.maybeInstrument;
export const resetInstrumentationHandlers = _mod726.resetInstrumentationHandlers;
export const triggerHandlers = _mod726.triggerHandlers;
export const isDOMError = _mod703.isDOMError;
export const isDOMException = _mod703.isDOMException;
export const isElement = _mod703.isElement;
export const isError = _mod703.isError;
export const isErrorEvent = _mod703.isErrorEvent;
export const isEvent = _mod703.isEvent;
export const isInstanceOf = _mod703.isInstanceOf;
export const isParameterizedString = _mod703.isParameterizedString;
export const isPlainObject = _mod703.isPlainObject;
export const isPrimitive = _mod703.isPrimitive;
export const isRegExp = _mod703.isRegExp;
export const isString = _mod703.isString;
export const isSyntheticEvent = _mod703.isSyntheticEvent;
export const isThenable = _mod703.isThenable;
export const isVueViewModel = _mod703.isVueViewModel;
export const isBrowser = dynamicRequire.isBrowser;
export const CONSOLE_LEVELS = consoleSandbox.CONSOLE_LEVELS;
export const consoleSandbox = consoleSandbox.consoleSandbox;
export const debug = consoleSandbox.debug;
export const originalConsoleMethods = consoleSandbox.originalConsoleMethods;
export const addContextToFrame = uuid4.addContextToFrame;
export const addExceptionMechanism = uuid4.addExceptionMechanism;
export const addExceptionTypeValue = uuid4.addExceptionTypeValue;
export const checkOrSetAlreadyCaught = uuid4.checkOrSetAlreadyCaught;
export const getEventDescription = uuid4.getEventDescription;
export const parseSemver = uuid4.parseSemver;
export const uuid4 = uuid4.uuid4;
export const isNodeEnv = _mod864.isNodeEnv;
export const loadModule = _mod864.loadModule;
export const normalize = normalize.normalize;
export const normalizeToSize = normalize.normalizeToSize;
export const normalizeUrlToBase = normalize.normalizeUrlToBase;
export const addNonEnumerableProperty = _mod698.addNonEnumerableProperty;
export const convertToPlainObject = _mod698.convertToPlainObject;
export const dropUndefinedKeys = _mod698.dropUndefinedKeys;
export const extractExceptionKeysForMessage = _mod698.extractExceptionKeysForMessage;
export const fill = _mod698.fill;
export const getOriginalFunction = _mod698.getOriginalFunction;
export const markFunctionWrapped = _mod698.markFunctionWrapped;
export const objectify = _mod698.objectify;
export const basename = resolve.basename;
export const dirname = resolve.dirname;
export const isAbsolute = resolve.isAbsolute;
export const join = resolve.join;
export const normalizePath = resolve.normalizePath;
export const relative = resolve.relative;
export const resolve = resolve.resolve;
export const SENTRY_BUFFER_FULL_ERROR = SENTRY_BUFFER_FULL_ERROR.SENTRY_BUFFER_FULL_ERROR;
export const makePromiseBuffer = SENTRY_BUFFER_FULL_ERROR.makePromiseBuffer;
export const severityLevelFromString = severityLevelFromString.severityLevelFromString;
export const replaceExports = replaceExports.replaceExports;
export const UNKNOWN_FUNCTION = _mod709.UNKNOWN_FUNCTION;
export const createStackParser = _mod709.createStackParser;
export const getFramesFromEvent = _mod709.getFramesFromEvent;
export const getFunctionName = _mod709.getFunctionName;
export const stackParserFromStackParserOptions = _mod709.stackParserFromStackParserOptions;
export const stripSentryFramesAndReverse = _mod709.stripSentryFramesAndReverse;
export const filenameIsInApp = filenameIsInApp.filenameIsInApp;
export const node = filenameIsInApp.node;
export const nodeStackLineParser = filenameIsInApp.nodeStackLineParser;
export const isMatchingPattern = _mod708.isMatchingPattern;
export const safeJoin = _mod708.safeJoin;
export const snipLine = _mod708.snipLine;
export const stringMatchesSomePattern = _mod708.stringMatchesSomePattern;
export const truncate = _mod708.truncate;
export const isNativeFunction = _isFetchSupported.isNativeFunction;
export const supportsDOMError = _isFetchSupported.supportsDOMError;
export const supportsDOMException = _isFetchSupported.supportsDOMException;
export const supportsErrorEvent = _isFetchSupported.supportsErrorEvent;
export const supportsFetch = _isFetchSupported.supportsFetch;
export const supportsHistory = _isFetchSupported.supportsHistory;
export const supportsNativeFetch = _isFetchSupported.supportsNativeFetch;
export const supportsReferrerPolicy = _isFetchSupported.supportsReferrerPolicy;
export const supportsReportingObserver = _isFetchSupported.supportsReportingObserver;
export const SyncPromise = SyncPromise.SyncPromise;
export const rejectedSyncPromise = SyncPromise.rejectedSyncPromise;
export const resolvedSyncPromise = SyncPromise.resolvedSyncPromise;
export const browserPerformanceTimeOrigin = dateTimestampInSeconds.browserPerformanceTimeOrigin;
export const dateTimestampInSeconds = dateTimestampInSeconds.dateTimestampInSeconds;
export const timestampInSeconds = dateTimestampInSeconds.timestampInSeconds;
export const TRACEPARENT_REGEXP = _mod710.TRACEPARENT_REGEXP;
export const extractTraceparentData = _mod710.extractTraceparentData;
export const generateSentryTraceHeader = _mod710.generateSentryTraceHeader;
export const generateTraceparentHeader = _mod710.generateTraceparentHeader;
export const propagationContextFromHeaders = _mod710.propagationContextFromHeaders;
export const shouldContinueTrace = _mod710.shouldContinueTrace;
export const getSDKSource = _mod865.getSDKSource;
export const isBrowserBundle = _mod865.isBrowserBundle;
export const addItemToEnvelope = forEachEnvelopeItem.addItemToEnvelope;
export const createAttachmentEnvelopeItem = forEachEnvelopeItem.createAttachmentEnvelopeItem;
export const createEnvelope = forEachEnvelopeItem.createEnvelope;
export const createEventEnvelopeHeaders = forEachEnvelopeItem.createEventEnvelopeHeaders;
export const createSpanEnvelopeItem = forEachEnvelopeItem.createSpanEnvelopeItem;
export const envelopeContainsItemType = forEachEnvelopeItem.envelopeContainsItemType;
export const envelopeItemTypeToDataCategory = forEachEnvelopeItem.envelopeItemTypeToDataCategory;
export const forEachEnvelopeItem = forEachEnvelopeItem.forEachEnvelopeItem;
export const getSdkMetadataForEnvelopeHeader = forEachEnvelopeItem.getSdkMetadataForEnvelopeHeader;
export const parseEnvelope = forEachEnvelopeItem.parseEnvelope;
export const serializeEnvelope = forEachEnvelopeItem.serializeEnvelope;
export const createClientReportEnvelope = _mod765.createClientReportEnvelope;
export const DEFAULT_RETRY_AFTER = disabledUntil.DEFAULT_RETRY_AFTER;
export const disabledUntil = disabledUntil.disabledUntil;
export const isRateLimited = disabledUntil.isRateLimited;
export const parseRetryAfterHeader = disabledUntil.parseRetryAfterHeader;
export const updateRateLimits = disabledUntil.updateRateLimits;
export const MAX_BAGGAGE_STRING_LENGTH = MAX_BAGGAGE_STRING_LENGTH.MAX_BAGGAGE_STRING_LENGTH;
export const SENTRY_BAGGAGE_KEY_PREFIX = MAX_BAGGAGE_STRING_LENGTH.SENTRY_BAGGAGE_KEY_PREFIX;
export const SENTRY_BAGGAGE_KEY_PREFIX_REGEX = MAX_BAGGAGE_STRING_LENGTH.SENTRY_BAGGAGE_KEY_PREFIX_REGEX;
export const baggageHeaderToDynamicSamplingContext = MAX_BAGGAGE_STRING_LENGTH.baggageHeaderToDynamicSamplingContext;
export const dynamicSamplingContextToSentryBaggageHeader = MAX_BAGGAGE_STRING_LENGTH.dynamicSamplingContextToSentryBaggageHeader;
export const objectToBaggageHeader = MAX_BAGGAGE_STRING_LENGTH.objectToBaggageHeader;
export const parseBaggageHeader = MAX_BAGGAGE_STRING_LENGTH.parseBaggageHeader;
export const getHttpSpanDetailsFromUrlObject = _mod776.getHttpSpanDetailsFromUrlObject;
export const getSanitizedUrlString = _mod776.getSanitizedUrlString;
export const getSanitizedUrlStringFromUrlObject = _mod776.getSanitizedUrlStringFromUrlObject;
export const isURLObjectRelative = _mod776.isURLObjectRelative;
export const parseStringToURLObject = _mod776.parseStringToURLObject;
export const parseUrl = _mod776.parseUrl;
export const stripDataUrlContent = _mod776.stripDataUrlContent;
export const stripUrlQueryAndFragment = _mod776.stripUrlQueryAndFragment;
export const _INTERNAL_enhanceErrorWithSentryInfo = exceptionFromError._enhanceErrorWithSentryInfo;
export const eventFromMessage = exceptionFromError.eventFromMessage;
export const eventFromUnknownInput = exceptionFromError.eventFromUnknownInput;
export const exceptionFromError = exceptionFromError.exceptionFromError;
export const parseStackFrames = exceptionFromError.parseStackFrames;
export const callFrameToStackFrame = callFrameToStackFrame.callFrameToStackFrame;
export const watchdogTimer = callFrameToStackFrame.watchdogTimer;
export const LRUMap = LRUMap.LRUMap;
export const generateSpanId = generateSpanId.generateSpanId;
export const generateTraceId = generateSpanId.generateTraceId;
export const vercelWaitUntil = vercelWaitUntil.vercelWaitUntil;
export const flushIfServerless = flushWithTimeout.flushIfServerless;
export const SDK_VERSION = SDK_VERSION.SDK_VERSION;
export const getDebugImagesForResources = _mod750.getDebugImagesForResources;
export const getFilenameToDebugIdMap = _mod750.getFilenameToDebugIdMap;
export const getFilenameToMetadataMap = _mod790.getFilenameToMetadataMap;
export const escapeStringForRegex = escapeStringForRegex.escapeStringForRegex;
export const _INTERNAL_safeDateNow = safeDateNow.safeDateNow;
export const _INTERNAL_safeMathRandom = safeDateNow.safeMathRandom;
export const _INTERNAL_withRandomSafeContext = safeDateNow.withRandomSafeContext;