// _runtime/metro/00693__.js
import _mod694 from "00694__.js";
import TRACE_FLAG_NONE from "../00695_TRACE_FLAG_NONE.js";
import _mod696 from "00696__.js";
import _mod697 from "00697__.js";
import _mod698 from "00698__.js";
import CONSOLE_LEVELS from "../00700_CONSOLE_LEVELS.js";
import _mod701 from "00701__.js";
import SDK_VERSION from "../00702_SDK_VERSION.js";
import _mod703 from "00703__.js";
import _mod704 from "00704__.js";
import generateSpanId from "../00705_generateSpanId.js";
import uuid4 from "../00706_uuid4.js";
import safeDateNow from "../00707_safeDateNow.js";
import _mod708 from "00708__.js";
import UNKNOWN_FUNCTION from "../00709_UNKNOWN_FUNCTION.js";
import regExp from "../00710_regExp.js";
import MAX_BAGGAGE_STRING_LENGTH from "../00711_MAX_BAGGAGE_STRING_LENGTH.js";
import _mod712 from "00712__.js";
import _mod713 from "00713__.js";
import browserPerformanceTimeOrigin from "../00714_browserPerformanceTimeOrigin.js";
import SEMANTIC_ATTRIBUTE_CACHE_HIT from "../00715_SEMANTIC_ATTRIBUTE_CACHE_HIT.js";
import SPAN_STATUS_ERROR from "../00716_SPAN_STATUS_ERROR.js";
import _mod717 from "00717__.js";
import Scope from "../00719_Scope.js";
import _getSpanForScope from "../00720__getSpanForScope.js";
import closeSession from "../00721_closeSession.js";
import _mod723 from "00723__.js";
import _mod724 from "00724__.js";
import _mod725 from "00725__.js";
import _mod726 from "00726__.js";
import _mod727 from "00727__.js";
import TRACING_DEFAULTS from "../00728_TRACING_DEFAULTS.js";
import _mod731 from "00731__.js";
import SentryNonRecordingSpan from "../00732_SentryNonRecordingSpan.js";
import freezeDscOnSpan from "../00733_freezeDscOnSpan.js";
import DEFAULT_ENVIRONMENT from "../00734_DEFAULT_ENVIRONMENT.js";
import SentrySpan from "../00736_SentrySpan.js";
import logSpanEnd from "../00737_logSpanEnd.js";
import timedEventsToMeasurements from "../00738_timedEventsToMeasurements.js";
import _enhanceEventWithSdkInfo from "../00739__enhanceEventWithSdkInfo.js";
import _mod740 from "00740__.js";
import normalize from "../00741_normalize.js";
import continueTrace from "../00742_continueTrace.js";
import _mod743 from "00743__.js";
import sampleSpan from "../00744_sampleSpan.js";
import _mod745 from "00745__.js";
import applyClientOptions from "../00746_applyClientOptions.js";
import applyScopeDataToEvent from "../00747_applyScopeDataToEvent.js";
import notifyEventProcessors from "../00748_notifyEventProcessors.js";
import SyncPromise from "../00749_SyncPromise.js";
import _mod750 from "00750__.js";
import _mod751 from "00751__.js";
import Client from "../00752_Client.js";
import SENTRY_BUFFER_FULL_ERROR from "../00753_SENTRY_BUFFER_FULL_ERROR.js";
import DEFAULT_TRANSPORT_BUFFER_SIZE from "../00754_DEFAULT_TRANSPORT_BUFFER_SIZE.js";
import DEFAULT_RETRY_AFTER from "../00755_DEFAULT_RETRY_AFTER.js";
import _INTERNAL_captureLog from "../00756__INTERNAL_captureLog.js";
import _INTERNAL_captureMetric from "../00761__INTERNAL_captureMetric.js";
import _mod763 from "00763__.js";
import _mod765 from "00765__.js";
import ServerRuntimeClient from "../00767_ServerRuntimeClient.js";
import _enhanceErrorWithSentryInfo from "../00769__enhanceErrorWithSentryInfo.js";
import _mod770 from "00770__.js";
import _mod771 from "00771__.js";
import MIN_DELAY from "../00772_MIN_DELAY.js";
import MULTIPLEXED_TRANSPORT_EXTRA_KEY from "../00773_MULTIPLEXED_TRANSPORT_EXTRA_KEY.js";
import _INTERNAL_clearAiProviderSkips from "../00774__INTERNAL_clearAiProviderSkips.js";
import _mod775 from "00775__.js";
import _mod776 from "00776__.js";
import parameterize from "../00777_parameterize.js";
import _mod778 from "00778__.js";
import applySdkMetadata from "../00779_applySdkMetadata.js";
import _mod780 from "00780__.js";
import _mod781 from "00781__.js";
import _mod782 from "00782__.js";
import extractQueryParamsFromUrl from "../00783_extractQueryParamsFromUrl.js";
import _mod784 from "00784__.js";
import functionToStringIntegration from "../00785_functionToStringIntegration.js";
import eventFiltersIntegration from "../00786_eventFiltersIntegration.js";
import linkedErrorsIntegration from "../00787_linkedErrorsIntegration.js";
import applyAggregateErrorsToEvent from "../00788_applyAggregateErrorsToEvent.js";
import moduleMetadataIntegration from "../00789_moduleMetadataIntegration.js";
import _mod790 from "00790__.js";
import requestDataIntegration from "../00791_requestDataIntegration.js";
import captureConsoleIntegration from "../00794_captureConsoleIntegration.js";
import _mod795 from "00795__.js";
import severityLevelFromString from "../00796_severityLevelFromString.js";
import _shouldDropEvent from "../00797__shouldDropEvent.js";
import extraErrorDataIntegration from "../00798_extraErrorDataIntegration.js";
import generateIteratee from "../00799_generateIteratee.js";
import basename from "../00800_basename.js";
import DB_OPERATIONS_TO_INSTRUMENT from "../00801_DB_OPERATIONS_TO_INSTRUMENT.js";
import applyZodErrorsToEvent from "../00802_applyZodErrorsToEvent.js";
import thirdPartyErrorFilterIntegration from "../00803_thirdPartyErrorFilterIntegration.js";
import _mod804 from "00804__.js";
import featureFlagsIntegration from "../00805_featureFlagsIntegration.js";
import _INTERNAL_FLAG_BUFFER_SIZE from "../00806__INTERNAL_FLAG_BUFFER_SIZE.js";
import growthbookIntegration from "../00807_growthbookIntegration.js";
import profiler from "../00808_profiler.js";
import _addTracingHeadersToFetchRequest from "00809__addTracingHeadersToFetchRequest.js";
import trpcMiddleware from "../00810_trpcMiddleware.js";
import wrapMcpServerWithSentry from "../00811_wrapMcpServerWithSentry.js";
import captureFeedback from "../00825_captureFeedback.js";
import fmt from "../00826_fmt.js";
import consoleLoggingIntegration from "../00827_consoleLoggingIntegration.js";
import count from "../00829_count.js";
import _mod830 from "00830__.js";
import _mod831 from "00831__.js";
import _INTERNAL_cleanupToolCallSpan from "../00833__INTERNAL_cleanupToolCallSpan.js";
import instrumentOpenAiClient from "../00838_instrumentOpenAiClient.js";
import INSTRUMENTED_METHODS from "../00840_INSTRUMENTED_METHODS.js";
import instrumentAnthropicAiClient from "../00845_instrumentAnthropicAiClient.js";
import ANTHROPIC_AI_INSTRUMENTED_METHODS from "../00847_ANTHROPIC_AI_INSTRUMENTED_METHODS.js";
import extractModel from "../00849_extractModel.js";
import CHATS_CREATE_METHOD from "../00850_CHATS_CREATE_METHOD.js";
import _mod853 from "00853__.js";
import LANGCHAIN_INTEGRATION_NAME from "../00855_LANGCHAIN_INTEGRATION_NAME.js";
import instrumentLangGraph from "../00856_instrumentLangGraph.js";
import LANGGRAPH_INTEGRATION_NAME from "../00857_LANGGRAPH_INTEGRATION_NAME.js";
import _mod859 from "00859__.js";
import SentryError from "../00860_SentryError.js";
import _mod861 from "00861__.js";
import _mod862 from "00862__.js";
import _mod863 from "00863__.js";
import _mod864 from "00864__.js";
import _mod865 from "00865__.js";
import replaceExports from "../00866_replaceExports.js";
import filenameIsInApp from "../00867_filenameIsInApp.js";
import callFrameToStackFrame from "../00868_callFrameToStackFrame.js";
import LRUMap from "../00869_LRUMap.js";
import vercelWaitUntil from "../00870_vercelWaitUntil.js";
import flushIfServerless from "../00871_flushIfServerless.js";
import escapeStringForRegex from "../00872_escapeStringForRegex.js";

Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
const TRACING_DEFAULTS_export = TRACING_DEFAULTS.TRACING_DEFAULTS;
const SentrySpan_export = SentrySpan.SentrySpan;
const SentryNonRecordingSpan_export = SentryNonRecordingSpan.SentryNonRecordingSpan;
const SPAN_STATUS_ERROR_export = SPAN_STATUS_ERROR.SPAN_STATUS_ERROR;
const continueTrace_export = continueTrace.continueTrace;
const timedEventsToMeasurements_export = timedEventsToMeasurements.timedEventsToMeasurements;
const sampleSpan_export = sampleSpan.sampleSpan;
const logSpanEnd_export = logSpanEnd.logSpanEnd;
const SEMANTIC_ATTRIBUTE_CACHE_HIT_export = SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_ATTRIBUTE_CACHE_HIT;
const closeSession_export = closeSession.closeSession;
const Scope_export = Scope.Scope;
const notifyEventProcessors_export = notifyEventProcessors.notifyEventProcessors;
const Client_export = Client.Client;
const ServerRuntimeClient_export = ServerRuntimeClient.ServerRuntimeClient;
const MULTIPLEXED_TRANSPORT_EXTRA_KEY_export = MULTIPLEXED_TRANSPORT_EXTRA_KEY.MULTIPLEXED_TRANSPORT_EXTRA_KEY;
const _INTERNAL_clearAiProviderSkips_export = _INTERNAL_clearAiProviderSkips._INTERNAL_clearAiProviderSkips;
const applyScopeDataToEvent_export = applyScopeDataToEvent.applyScopeDataToEvent;
const fmt_export = parameterize.fmt;
const parameterize_export = parameterize.parameterize;
const applySdkMetadata_export = applySdkMetadata.applySdkMetadata;
const extractQueryParamsFromUrl_export = extractQueryParamsFromUrl.extractQueryParamsFromUrl;
const DEFAULT_ENVIRONMENT_export = DEFAULT_ENVIRONMENT.DEFAULT_ENVIRONMENT;
const functionToStringIntegration_export = functionToStringIntegration.functionToStringIntegration;
const eventFiltersIntegration_export = eventFiltersIntegration.eventFiltersIntegration;
const linkedErrorsIntegration_export = linkedErrorsIntegration.linkedErrorsIntegration;
const moduleMetadataIntegration_export = moduleMetadataIntegration.moduleMetadataIntegration;
const requestDataIntegration_export = requestDataIntegration.requestDataIntegration;
const captureConsoleIntegration_export = captureConsoleIntegration.captureConsoleIntegration;
const extraErrorDataIntegration_export = extraErrorDataIntegration.extraErrorDataIntegration;
const thirdPartyErrorFilterIntegration_export = thirdPartyErrorFilterIntegration.thirdPartyErrorFilterIntegration;
const featureFlagsIntegration_export = featureFlagsIntegration.featureFlagsIntegration;
const growthbookIntegration_export = growthbookIntegration.growthbookIntegration;
const profiler_export = profiler.profiler;
const trpcMiddleware_export = trpcMiddleware.trpcMiddleware;
const wrapMcpServerWithSentry_export = wrapMcpServerWithSentry.wrapMcpServerWithSentry;
const captureFeedback_export = captureFeedback.captureFeedback;
const _INTERNAL_captureLog_export = _INTERNAL_captureLog._INTERNAL_captureLog;
const consoleLoggingIntegration_export = consoleLoggingIntegration.consoleLoggingIntegration;
const _INTERNAL_captureMetric_export = _INTERNAL_captureMetric._INTERNAL_captureMetric;
const _INTERNAL_cleanupToolCallSpan_export = _INTERNAL_cleanupToolCallSpan._INTERNAL_cleanupToolCallSpan;
const instrumentOpenAiClient_export = instrumentOpenAiClient.instrumentOpenAiClient;
const instrumentAnthropicAiClient_export = instrumentAnthropicAiClient.instrumentAnthropicAiClient;
const LANGCHAIN_INTEGRATION_NAME_export = LANGCHAIN_INTEGRATION_NAME.LANGCHAIN_INTEGRATION_NAME;
const instrumentLangGraph_export = instrumentLangGraph.instrumentLangGraph;
const LANGGRAPH_INTEGRATION_NAME_export = LANGGRAPH_INTEGRATION_NAME.LANGGRAPH_INTEGRATION_NAME;
const _INTERNAL_FLAG_BUFFER_SIZE_export = _INTERNAL_FLAG_BUFFER_SIZE._INTERNAL_FLAG_BUFFER_SIZE;
const applyAggregateErrorsToEvent_export = applyAggregateErrorsToEvent.applyAggregateErrorsToEvent;
const SentryError_export = SentryError.SentryError;
const CONSOLE_LEVELS_export = CONSOLE_LEVELS.CONSOLE_LEVELS;
const uuid4_export = uuid4.uuid4;
const normalize_export = normalize.normalize;
const basename_export = basename.basename;
const SENTRY_BUFFER_FULL_ERROR_export = SENTRY_BUFFER_FULL_ERROR.SENTRY_BUFFER_FULL_ERROR;
const severityLevelFromString_export = severityLevelFromString.severityLevelFromString;
const replaceExports_export = replaceExports.replaceExports;
const UNKNOWN_FUNCTION_export = UNKNOWN_FUNCTION.UNKNOWN_FUNCTION;
const filenameIsInApp_export = filenameIsInApp.filenameIsInApp;
const SyncPromise_export = SyncPromise.SyncPromise;
const browserPerformanceTimeOrigin_export = browserPerformanceTimeOrigin.browserPerformanceTimeOrigin;
const DEFAULT_RETRY_AFTER_export = DEFAULT_RETRY_AFTER.DEFAULT_RETRY_AFTER;
const MAX_BAGGAGE_STRING_LENGTH_export = MAX_BAGGAGE_STRING_LENGTH.MAX_BAGGAGE_STRING_LENGTH;
const callFrameToStackFrame_export = callFrameToStackFrame.callFrameToStackFrame;
const LRUMap_export = LRUMap.LRUMap;
const generateSpanId_export = generateSpanId.generateSpanId;
const vercelWaitUntil_export = vercelWaitUntil.vercelWaitUntil;
const flushIfServerless_export = flushIfServerless.flushIfServerless;
const SDK_VERSION_export = SDK_VERSION.SDK_VERSION;
const escapeStringForRegex_export = escapeStringForRegex.escapeStringForRegex;

export const registerSpanErrorInstrumentation = _mod694.registerSpanErrorInstrumentation;
export const getCapturedScopesOnSpan = _mod696.getCapturedScopesOnSpan;
export const setCapturedScopesOnSpan = _mod696.setCapturedScopesOnSpan;
export { TRACING_DEFAULTS_export as TRACING_DEFAULTS };
export const startIdleSpan = TRACING_DEFAULTS.startIdleSpan;
export { SentrySpan_export as SentrySpan };
export { SentryNonRecordingSpan_export as SentryNonRecordingSpan };
export { SPAN_STATUS_ERROR_export as SPAN_STATUS_ERROR };
export const SPAN_STATUS_OK = SPAN_STATUS_ERROR.SPAN_STATUS_OK;
export const SPAN_STATUS_UNSET = SPAN_STATUS_ERROR.SPAN_STATUS_UNSET;
export const getSpanStatusFromHttpCode = SPAN_STATUS_ERROR.getSpanStatusFromHttpCode;
export const setHttpStatus = SPAN_STATUS_ERROR.setHttpStatus;
export { continueTrace_export as continueTrace };
export const startInactiveSpan = continueTrace.startInactiveSpan;
export const startNewTrace = continueTrace.startNewTrace;
export const startSpan = continueTrace.startSpan;
export const startSpanManual = continueTrace.startSpanManual;
export const suppressTracing = continueTrace.suppressTracing;
export const withActiveSpan = continueTrace.withActiveSpan;
export const getDynamicSamplingContextFromClient = freezeDscOnSpan.getDynamicSamplingContextFromClient;
export const getDynamicSamplingContextFromScope = freezeDscOnSpan.getDynamicSamplingContextFromScope;
export const getDynamicSamplingContextFromSpan = freezeDscOnSpan.getDynamicSamplingContextFromSpan;
export const spanToBaggageHeader = freezeDscOnSpan.spanToBaggageHeader;
export const setMeasurement = timedEventsToMeasurements.setMeasurement;
export { timedEventsToMeasurements_export as timedEventsToMeasurements };
export { sampleSpan_export as sampleSpan };
export { logSpanEnd_export as logSpanEnd };
export const logSpanStart = logSpanEnd.logSpanStart;
export { SEMANTIC_ATTRIBUTE_CACHE_HIT_export as SEMANTIC_ATTRIBUTE_CACHE_HIT };
export const SEMANTIC_ATTRIBUTE_CACHE_ITEM_SIZE = SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_ATTRIBUTE_CACHE_ITEM_SIZE;
export const SEMANTIC_ATTRIBUTE_CACHE_KEY = SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_ATTRIBUTE_CACHE_KEY;
export const SEMANTIC_ATTRIBUTE_EXCLUSIVE_TIME = SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_ATTRIBUTE_EXCLUSIVE_TIME;
export const SEMANTIC_ATTRIBUTE_HTTP_REQUEST_METHOD =
  SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_ATTRIBUTE_HTTP_REQUEST_METHOD;
export const SEMANTIC_ATTRIBUTE_PROFILE_ID = SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_ATTRIBUTE_PROFILE_ID;
export const SEMANTIC_ATTRIBUTE_SENTRY_CUSTOM_SPAN_NAME =
  SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_ATTRIBUTE_SENTRY_CUSTOM_SPAN_NAME;
export const SEMANTIC_ATTRIBUTE_SENTRY_IDLE_SPAN_FINISH_REASON =
  SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_ATTRIBUTE_SENTRY_IDLE_SPAN_FINISH_REASON;
export const SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_UNIT =
  SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_UNIT;
export const SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_VALUE =
  SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_VALUE;
export const SEMANTIC_ATTRIBUTE_SENTRY_OP = SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_ATTRIBUTE_SENTRY_OP;
export const SEMANTIC_ATTRIBUTE_SENTRY_ORIGIN = SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_ATTRIBUTE_SENTRY_ORIGIN;
export const SEMANTIC_ATTRIBUTE_SENTRY_PREVIOUS_TRACE_SAMPLE_RATE =
  SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_ATTRIBUTE_SENTRY_PREVIOUS_TRACE_SAMPLE_RATE;
export const SEMANTIC_ATTRIBUTE_SENTRY_SAMPLE_RATE = SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_ATTRIBUTE_SENTRY_SAMPLE_RATE;
export const SEMANTIC_ATTRIBUTE_SENTRY_SOURCE = SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_ATTRIBUTE_SENTRY_SOURCE;
export const SEMANTIC_ATTRIBUTE_URL_FULL = SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_ATTRIBUTE_URL_FULL;
export const SEMANTIC_LINK_ATTRIBUTE_LINK_TYPE = SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_LINK_ATTRIBUTE_LINK_TYPE;
export const createEventEnvelope = _enhanceEventWithSdkInfo.createEventEnvelope;
export const createSessionEnvelope = _enhanceEventWithSdkInfo.createSessionEnvelope;
export const createSpanEnvelope = _enhanceEventWithSdkInfo.createSpanEnvelope;
export const addEventProcessor = _mod745.addEventProcessor;
export const captureCheckIn = _mod745.captureCheckIn;
export const captureEvent = _mod745.captureEvent;
export const captureException = _mod745.captureException;
export const captureMessage = _mod745.captureMessage;
export const captureSession = _mod745.captureSession;
export const close = _mod745.close;
export const endSession = _mod745.endSession;
export const flush = _mod745.flush;
export const isEnabled = _mod745.isEnabled;
export const isInitialized = _mod745.isInitialized;
export const lastEventId = _mod745.lastEventId;
export const setContext = _mod745.setContext;
export const setExtra = _mod745.setExtra;
export const setExtras = _mod745.setExtras;
export const setTag = _mod745.setTag;
export const setTags = _mod745.setTags;
export const setUser = _mod745.setUser;
export const startSession = _mod745.startSession;
export const withMonitor = _mod745.withMonitor;
export const getClient = _mod724.getClient;
export const getCurrentScope = _mod724.getCurrentScope;
export const getGlobalScope = _mod724.getGlobalScope;
export const getIsolationScope = _mod724.getIsolationScope;
export const getTraceContextFromScope = _mod724.getTraceContextFromScope;
export const withIsolationScope = _mod724.withIsolationScope;
export const withScope = _mod724.withScope;
export const getDefaultCurrentScope = _mod723.getDefaultCurrentScope;
export const getDefaultIsolationScope = _mod723.getDefaultIsolationScope;
export const setAsyncContextStrategy = _mod717.setAsyncContextStrategy;
export const getGlobalSingleton = _mod701.getGlobalSingleton;
export const getMainCarrier = _mod701.getMainCarrier;
export { closeSession_export as closeSession };
export const makeSession = closeSession.makeSession;
export const updateSession = closeSession.updateSession;
export { Scope_export as Scope };
export { notifyEventProcessors_export as notifyEventProcessors };
export const getEnvelopeEndpointWithUrlEncodedAuth = _mod751.getEnvelopeEndpointWithUrlEncodedAuth;
export const getReportDialogEndpoint = _mod751.getReportDialogEndpoint;
export { Client_export as Client };
export { ServerRuntimeClient_export as ServerRuntimeClient };
export const initAndBind = _mod771.initAndBind;
export const setCurrentClient = _mod771.setCurrentClient;
export const createTransport = DEFAULT_TRANSPORT_BUFFER_SIZE.createTransport;
export const makeOfflineTransport = MIN_DELAY.makeOfflineTransport;
export { MULTIPLEXED_TRANSPORT_EXTRA_KEY_export as MULTIPLEXED_TRANSPORT_EXTRA_KEY };
export const makeMultiplexedTransport = MULTIPLEXED_TRANSPORT_EXTRA_KEY.makeMultiplexedTransport;
export const addIntegration = _mod763.addIntegration;
export const defineIntegration = _mod763.defineIntegration;
export const getIntegrationsToSetup = _mod763.getIntegrationsToSetup;
export const installedIntegrations = _mod763.installedIntegrations;
export { _INTERNAL_clearAiProviderSkips_export as _INTERNAL_clearAiProviderSkips };
export const _INTERNAL_shouldSkipAiProviderWrapping =
  _INTERNAL_clearAiProviderSkips._INTERNAL_shouldSkipAiProviderWrapping;
export const _INTERNAL_skipAiProviderWrapping = _INTERNAL_clearAiProviderSkips._INTERNAL_skipAiProviderWrapping;
export { applyScopeDataToEvent_export as applyScopeDataToEvent };
export const getCombinedScopeData = applyScopeDataToEvent.getCombinedScopeData;
export const mergeScopeData = applyScopeDataToEvent.mergeScopeData;
export const prepareEvent = applyClientOptions.prepareEvent;
export const createCheckInEnvelope = _mod770.createCheckInEnvelope;
export const hasSpansEnabled = _mod731.hasSpansEnabled;
export const isSentryRequestUrl = _mod775.isSentryRequestUrl;
export const handleCallbackErrors = _mod743.handleCallbackErrors;
export { fmt_export as fmt };
export { parameterize_export as parameterize };
export const addAutoIpAddressToSession = _mod778.addAutoIpAddressToSession;
export const addAutoIpAddressToUser = _mod778.addAutoIpAddressToUser;
export const addChildSpanToSpan = TRACE_FLAG_NONE.addChildSpanToSpan;
export const convertSpanLinksForEnvelope = TRACE_FLAG_NONE.convertSpanLinksForEnvelope;
export const getActiveSpan = TRACE_FLAG_NONE.getActiveSpan;
export const getRootSpan = TRACE_FLAG_NONE.getRootSpan;
export const getSpanDescendants = TRACE_FLAG_NONE.getSpanDescendants;
export const getStatusMessage = TRACE_FLAG_NONE.getStatusMessage;
export const spanIsSampled = TRACE_FLAG_NONE.spanIsSampled;
export const spanTimeInputToSeconds = TRACE_FLAG_NONE.spanTimeInputToSeconds;
export const spanToJSON = TRACE_FLAG_NONE.spanToJSON;
export const spanToTraceContext = TRACE_FLAG_NONE.spanToTraceContext;
export const spanToTraceHeader = TRACE_FLAG_NONE.spanToTraceHeader;
export const updateSpanName = TRACE_FLAG_NONE.updateSpanName;
export const _INTERNAL_setSpanForScope = _getSpanForScope._setSpanForScope;
export const parseSampleRate = _mod712.parseSampleRate;
export { applySdkMetadata_export as applySdkMetadata };
export const getTraceData = _mod780.getTraceData;
export const getTraceMetaTags = _mod781.getTraceMetaTags;
export const debounce = _mod782.debounce;
export { extractQueryParamsFromUrl_export as extractQueryParamsFromUrl };
export const headersToDict = extractQueryParamsFromUrl.headersToDict;
export const httpHeadersToSpanAttributes = extractQueryParamsFromUrl.httpHeadersToSpanAttributes;
export const httpRequestToRequestData = extractQueryParamsFromUrl.httpRequestToRequestData;
export const winterCGHeadersToDict = extractQueryParamsFromUrl.winterCGHeadersToDict;
export const winterCGRequestToRequestData = extractQueryParamsFromUrl.winterCGRequestToRequestData;
export { DEFAULT_ENVIRONMENT_export as DEFAULT_ENVIRONMENT };
export const DEV_ENVIRONMENT = DEFAULT_ENVIRONMENT.DEV_ENVIRONMENT;
export const addBreadcrumb = _mod784.addBreadcrumb;
export { functionToStringIntegration_export as functionToStringIntegration };
export { eventFiltersIntegration_export as eventFiltersIntegration };
export const inboundFiltersIntegration = eventFiltersIntegration.inboundFiltersIntegration;
export { linkedErrorsIntegration_export as linkedErrorsIntegration };
export { moduleMetadataIntegration_export as moduleMetadataIntegration };
export { requestDataIntegration_export as requestDataIntegration };
export { captureConsoleIntegration_export as captureConsoleIntegration };
export const dedupeIntegration = _shouldDropEvent.dedupeIntegration;
export { extraErrorDataIntegration_export as extraErrorDataIntegration };
export const rewriteFramesIntegration = generateIteratee.rewriteFramesIntegration;
export const instrumentSupabaseClient = DB_OPERATIONS_TO_INSTRUMENT.instrumentSupabaseClient;
export const supabaseIntegration = DB_OPERATIONS_TO_INSTRUMENT.supabaseIntegration;
export const zodErrorsIntegration = applyZodErrorsToEvent.zodErrorsIntegration;
export { thirdPartyErrorFilterIntegration_export as thirdPartyErrorFilterIntegration };
export const consoleIntegration = _mod804.consoleIntegration;
export { featureFlagsIntegration_export as featureFlagsIntegration };
export { growthbookIntegration_export as growthbookIntegration };
export { profiler_export as profiler };
export const instrumentFetchRequest = _addTracingHeadersToFetchRequest.instrumentFetchRequest;
export { trpcMiddleware_export as trpcMiddleware };
export { wrapMcpServerWithSentry_export as wrapMcpServerWithSentry };
export { captureFeedback_export as captureFeedback };
export { _INTERNAL_captureLog_export as _INTERNAL_captureLog };
export const _INTERNAL_captureSerializedLog = _INTERNAL_captureLog._INTERNAL_captureSerializedLog;
export const _INTERNAL_flushLogsBuffer = _INTERNAL_captureLog._INTERNAL_flushLogsBuffer;
export const logger = fmt;
export { consoleLoggingIntegration_export as consoleLoggingIntegration };
export { _INTERNAL_captureMetric_export as _INTERNAL_captureMetric };
export const _INTERNAL_captureSerializedMetric = _INTERNAL_captureMetric._INTERNAL_captureSerializedMetric;
export const _INTERNAL_flushMetricsBuffer = _INTERNAL_captureMetric._INTERNAL_flushMetricsBuffer;
export const metrics = count;
export const createConsolaReporter = _mod830.createConsolaReporter;
export const addVercelAiProcessors = _mod831.addVercelAiProcessors;
export { _INTERNAL_cleanupToolCallSpan_export as _INTERNAL_cleanupToolCallSpan };
export const _INTERNAL_getSpanForToolCallId = _INTERNAL_cleanupToolCallSpan._INTERNAL_getSpanForToolCallId;
export { instrumentOpenAiClient_export as instrumentOpenAiClient };
export const OPENAI_INTEGRATION_NAME = INSTRUMENTED_METHODS.OPENAI_INTEGRATION_NAME;
export { instrumentAnthropicAiClient_export as instrumentAnthropicAiClient };
export const ANTHROPIC_AI_INTEGRATION_NAME = ANTHROPIC_AI_INSTRUMENTED_METHODS.ANTHROPIC_AI_INTEGRATION_NAME;
export const instrumentGoogleGenAIClient = extractModel.instrumentGoogleGenAIClient;
export const GOOGLE_GENAI_INTEGRATION_NAME = CHATS_CREATE_METHOD.GOOGLE_GENAI_INTEGRATION_NAME;
export const createLangChainCallbackHandler = _mod853.createLangChainCallbackHandler;
export { LANGCHAIN_INTEGRATION_NAME_export as LANGCHAIN_INTEGRATION_NAME };
export { instrumentLangGraph_export as instrumentLangGraph };
export const instrumentStateGraphCompile = instrumentLangGraph.instrumentStateGraphCompile;
export { LANGGRAPH_INTEGRATION_NAME_export as LANGGRAPH_INTEGRATION_NAME };
export { _INTERNAL_FLAG_BUFFER_SIZE_export as _INTERNAL_FLAG_BUFFER_SIZE };
export const _INTERNAL_MAX_FLAGS_PER_SPAN = _INTERNAL_FLAG_BUFFER_SIZE._INTERNAL_MAX_FLAGS_PER_SPAN;
export const _INTERNAL_addFeatureFlagToActiveSpan = _INTERNAL_FLAG_BUFFER_SIZE._INTERNAL_addFeatureFlagToActiveSpan;
export const _INTERNAL_copyFlagsFromScopeToEvent = _INTERNAL_FLAG_BUFFER_SIZE._INTERNAL_copyFlagsFromScopeToEvent;
export const _INTERNAL_insertFlagToScope = _INTERNAL_FLAG_BUFFER_SIZE._INTERNAL_insertFlagToScope;
export { applyAggregateErrorsToEvent_export as applyAggregateErrorsToEvent };
export const getBreadcrumbLogLevelFromHttpStatusCode = _mod859.getBreadcrumbLogLevelFromHttpStatusCode;
export const getComponentName = _mod704.getComponentName;
export const getLocationHref = _mod704.getLocationHref;
export const htmlTreeAsString = _mod704.htmlTreeAsString;
export const dsnFromString = _mod713.dsnFromString;
export const dsnToString = _mod713.dsnToString;
export const makeDsn = _mod713.makeDsn;
export { SentryError_export as SentryError };
export const GLOBAL_OBJ = _mod697.GLOBAL_OBJ;
export const addConsoleInstrumentationHandler = _mod795.addConsoleInstrumentationHandler;
export const addFetchEndInstrumentationHandler = _mod861.addFetchEndInstrumentationHandler;
export const addFetchInstrumentationHandler = _mod861.addFetchInstrumentationHandler;
export const addGlobalErrorInstrumentationHandler = _mod725.addGlobalErrorInstrumentationHandler;
export const addGlobalUnhandledRejectionInstrumentationHandler =
  _mod727.addGlobalUnhandledRejectionInstrumentationHandler;
export const addHandler = _mod726.addHandler;
export const maybeInstrument = _mod726.maybeInstrument;
export const resetInstrumentationHandlers = _mod726.resetInstrumentationHandlers;
export const triggerHandlers = _mod726.triggerHandlers;
export const isDOMError = _mod703.isDOMError;
export const isDOMException = _mod703.isDOMException;
export const isElement = _mod703.isElement;
export const isError = _mod703.isError;
export const isErrorEvent = _mod703.isErrorEvent;
export const isEvent = _mod703.isEvent;
export const isInstanceOf = _mod703.isInstanceOf;
export const isParameterizedString = _mod703.isParameterizedString;
export const isPlainObject = _mod703.isPlainObject;
export const isPrimitive = _mod703.isPrimitive;
export const isRegExp = _mod703.isRegExp;
export const isString = _mod703.isString;
export const isSyntheticEvent = _mod703.isSyntheticEvent;
export const isThenable = _mod703.isThenable;
export const isVueViewModel = _mod703.isVueViewModel;
export const isBrowser = _mod863.isBrowser;
export { CONSOLE_LEVELS_export as CONSOLE_LEVELS };
export const consoleSandbox = CONSOLE_LEVELS.consoleSandbox;
export const debug = CONSOLE_LEVELS.debug;
export const originalConsoleMethods = CONSOLE_LEVELS.originalConsoleMethods;
export const addContextToFrame = uuid4.addContextToFrame;
export const addExceptionMechanism = uuid4.addExceptionMechanism;
export const addExceptionTypeValue = uuid4.addExceptionTypeValue;
export const checkOrSetAlreadyCaught = uuid4.checkOrSetAlreadyCaught;
export const getEventDescription = uuid4.getEventDescription;
export const parseSemver = uuid4.parseSemver;
export { uuid4_export as uuid4 };
export const isNodeEnv = _mod864.isNodeEnv;
export const loadModule = _mod864.loadModule;
export { normalize_export as normalize };
export const normalizeToSize = normalize.normalizeToSize;
export const normalizeUrlToBase = normalize.normalizeUrlToBase;
export const addNonEnumerableProperty = _mod698.addNonEnumerableProperty;
export const convertToPlainObject = _mod698.convertToPlainObject;
export const dropUndefinedKeys = _mod698.dropUndefinedKeys;
export const extractExceptionKeysForMessage = _mod698.extractExceptionKeysForMessage;
export const fill = _mod698.fill;
export const getOriginalFunction = _mod698.getOriginalFunction;
export const markFunctionWrapped = _mod698.markFunctionWrapped;
export const objectify = _mod698.objectify;
export { basename_export as basename };
export const dirname = basename.dirname;
export const isAbsolute = basename.isAbsolute;
export const join = basename.join;
export const normalizePath = basename.normalizePath;
export const relative = basename.relative;
export const resolve = basename.resolve;
export { SENTRY_BUFFER_FULL_ERROR_export as SENTRY_BUFFER_FULL_ERROR };
export const makePromiseBuffer = SENTRY_BUFFER_FULL_ERROR.makePromiseBuffer;
export { severityLevelFromString_export as severityLevelFromString };
export { replaceExports_export as replaceExports };
export { UNKNOWN_FUNCTION_export as UNKNOWN_FUNCTION };
export const createStackParser = UNKNOWN_FUNCTION.createStackParser;
export const getFramesFromEvent = UNKNOWN_FUNCTION.getFramesFromEvent;
export const getFunctionName = UNKNOWN_FUNCTION.getFunctionName;
export const stackParserFromStackParserOptions = UNKNOWN_FUNCTION.stackParserFromStackParserOptions;
export const stripSentryFramesAndReverse = UNKNOWN_FUNCTION.stripSentryFramesAndReverse;
export { filenameIsInApp_export as filenameIsInApp };
export const node = filenameIsInApp.node;
export const nodeStackLineParser = filenameIsInApp.nodeStackLineParser;
export const isMatchingPattern = _mod708.isMatchingPattern;
export const safeJoin = _mod708.safeJoin;
export const snipLine = _mod708.snipLine;
export const stringMatchesSomePattern = _mod708.stringMatchesSomePattern;
export const truncate = _mod708.truncate;
export const isNativeFunction = _mod862.isNativeFunction;
export const supportsDOMError = _mod862.supportsDOMError;
export const supportsDOMException = _mod862.supportsDOMException;
export const supportsErrorEvent = _mod862.supportsErrorEvent;
export const supportsFetch = _mod862.supportsFetch;
export const supportsHistory = _mod862.supportsHistory;
export const supportsNativeFetch = _mod862.supportsNativeFetch;
export const supportsReferrerPolicy = _mod862.supportsReferrerPolicy;
export const supportsReportingObserver = _mod862.supportsReportingObserver;
export { SyncPromise_export as SyncPromise };
export const rejectedSyncPromise = SyncPromise.rejectedSyncPromise;
export const resolvedSyncPromise = SyncPromise.resolvedSyncPromise;
export { browserPerformanceTimeOrigin_export as browserPerformanceTimeOrigin };
export const dateTimestampInSeconds = browserPerformanceTimeOrigin.dateTimestampInSeconds;
export const timestampInSeconds = browserPerformanceTimeOrigin.timestampInSeconds;
export const TRACEPARENT_REGEXP = regExp.TRACEPARENT_REGEXP;
export const extractTraceparentData = regExp.extractTraceparentData;
export const generateSentryTraceHeader = regExp.generateSentryTraceHeader;
export const generateTraceparentHeader = regExp.generateTraceparentHeader;
export const propagationContextFromHeaders = regExp.propagationContextFromHeaders;
export const shouldContinueTrace = regExp.shouldContinueTrace;
export const getSDKSource = _mod865.getSDKSource;
export const isBrowserBundle = _mod865.isBrowserBundle;
export const addItemToEnvelope = _mod740.addItemToEnvelope;
export const createAttachmentEnvelopeItem = _mod740.createAttachmentEnvelopeItem;
export const createEnvelope = _mod740.createEnvelope;
export const createEventEnvelopeHeaders = _mod740.createEventEnvelopeHeaders;
export const createSpanEnvelopeItem = _mod740.createSpanEnvelopeItem;
export const envelopeContainsItemType = _mod740.envelopeContainsItemType;
export const envelopeItemTypeToDataCategory = _mod740.envelopeItemTypeToDataCategory;
export const forEachEnvelopeItem = _mod740.forEachEnvelopeItem;
export const getSdkMetadataForEnvelopeHeader = _mod740.getSdkMetadataForEnvelopeHeader;
export const parseEnvelope = _mod740.parseEnvelope;
export const serializeEnvelope = _mod740.serializeEnvelope;
export const createClientReportEnvelope = _mod765.createClientReportEnvelope;
export { DEFAULT_RETRY_AFTER_export as DEFAULT_RETRY_AFTER };
export const disabledUntil = DEFAULT_RETRY_AFTER.disabledUntil;
export const isRateLimited = DEFAULT_RETRY_AFTER.isRateLimited;
export const parseRetryAfterHeader = DEFAULT_RETRY_AFTER.parseRetryAfterHeader;
export const updateRateLimits = DEFAULT_RETRY_AFTER.updateRateLimits;
export { MAX_BAGGAGE_STRING_LENGTH_export as MAX_BAGGAGE_STRING_LENGTH };
export const SENTRY_BAGGAGE_KEY_PREFIX = MAX_BAGGAGE_STRING_LENGTH.SENTRY_BAGGAGE_KEY_PREFIX;
export const SENTRY_BAGGAGE_KEY_PREFIX_REGEX = MAX_BAGGAGE_STRING_LENGTH.SENTRY_BAGGAGE_KEY_PREFIX_REGEX;
export const baggageHeaderToDynamicSamplingContext = MAX_BAGGAGE_STRING_LENGTH.baggageHeaderToDynamicSamplingContext;
export const dynamicSamplingContextToSentryBaggageHeader =
  MAX_BAGGAGE_STRING_LENGTH.dynamicSamplingContextToSentryBaggageHeader;
export const objectToBaggageHeader = MAX_BAGGAGE_STRING_LENGTH.objectToBaggageHeader;
export const parseBaggageHeader = MAX_BAGGAGE_STRING_LENGTH.parseBaggageHeader;
export const getHttpSpanDetailsFromUrlObject = _mod776.getHttpSpanDetailsFromUrlObject;
export const getSanitizedUrlString = _mod776.getSanitizedUrlString;
export const getSanitizedUrlStringFromUrlObject = _mod776.getSanitizedUrlStringFromUrlObject;
export const isURLObjectRelative = _mod776.isURLObjectRelative;
export const parseStringToURLObject = _mod776.parseStringToURLObject;
export const parseUrl = _mod776.parseUrl;
export const stripDataUrlContent = _mod776.stripDataUrlContent;
export const stripUrlQueryAndFragment = _mod776.stripUrlQueryAndFragment;
export const _INTERNAL_enhanceErrorWithSentryInfo = _enhanceErrorWithSentryInfo._enhanceErrorWithSentryInfo;
export const eventFromMessage = _enhanceErrorWithSentryInfo.eventFromMessage;
export const eventFromUnknownInput = _enhanceErrorWithSentryInfo.eventFromUnknownInput;
export const exceptionFromError = _enhanceErrorWithSentryInfo.exceptionFromError;
export const parseStackFrames = _enhanceErrorWithSentryInfo.parseStackFrames;
export { callFrameToStackFrame_export as callFrameToStackFrame };
export const watchdogTimer = callFrameToStackFrame.watchdogTimer;
export { LRUMap_export as LRUMap };
export { generateSpanId_export as generateSpanId };
export const generateTraceId = generateSpanId.generateTraceId;
export { vercelWaitUntil_export as vercelWaitUntil };
export { flushIfServerless_export as flushIfServerless };
export { SDK_VERSION_export as SDK_VERSION };
export const getDebugImagesForResources = _mod750.getDebugImagesForResources;
export const getFilenameToDebugIdMap = _mod750.getFilenameToDebugIdMap;
export const getFilenameToMetadataMap = _mod790.getFilenameToMetadataMap;
export { escapeStringForRegex_export as escapeStringForRegex };
export const _INTERNAL_safeDateNow = safeDateNow.safeDateNow;
export const _INTERNAL_safeMathRandom = safeDateNow.safeMathRandom;
export const _INTERNAL_withRandomSafeContext = safeDateNow.withRandomSafeContext;
