// === Module 10988: ? ===

// Module 10988
import errorCallback from "errorCallback" /* 10989 */;
import _mod10990 from "module_10990" /* 10990 */;
import _mod10991 from "module_10991" /* 10991 */;
import _mod10993 from "module_10993" /* 10993 */;
import _mod10994 from "module_10994" /* 10994 */;
import _mod10995 from "module_10995" /* 10995 */;
import stackParserFromStackParserOptions from "stackParserFromStackParserOptions" /* 10996 */;
import _mod10997 from "module_10997" /* 10997 */;
import spanTimeInputToSeconds from "spanTimeInputToSeconds" /* 10998 */;
import _mod10999 from "module_10999" /* 10999 */;
import _mod11000 from "module_11000" /* 11000 */;
import _mod11001 from "module_11001" /* 11001 */;
import _mod11002 from "module_11002" /* 11002 */;
import generatePropagationContext from "generatePropagationContext" /* 11003 */;
import _mod11004 from "module_11004" /* 11004 */;
import _mod11005 from "module_11005" /* 11005 */;
import BAGGAGE_HEADER_NAME from "BAGGAGE_HEADER_NAME" /* 11006 */;
import _mod11008 from "module_11008" /* 11008 */;
import _mod11009 from "module_11009" /* 11009 */;
import _mod11010 from "module_11010" /* 11010 */;
import _mod11011 from "module_11011" /* 11011 */;
import _mod11012 from "module_11012" /* 11012 */;
import ScopeClass from "ScopeClass" /* 11014 */;
import _mod11016 from "module_11016" /* 11016 */;
import _mod11017 from "module_11017" /* 11017 */;
import _mod11019 from "module_11019" /* 11019 */;
import _mod11020 from "module_11020" /* 11020 */;
import _mod11022 from "module_11022" /* 11022 */;
import _mod11023 from "module_11023" /* 11023 */;
import _mod11024 from "module_11024" /* 11024 */;
import _mod11025 from "module_11025" /* 11025 */;
import _mod11026 from "module_11026" /* 11026 */;
import _mod11027 from "module_11027" /* 11027 */;
import _mod11028 from "module_11028" /* 11028 */;
import _mod11029 from "module_11029" /* 11029 */;
import _mod11030 from "module_11030" /* 11030 */;
import _mod11031 from "module_11031" /* 11031 */;
import _mod11032 from "module_11032" /* 11032 */;
import _mod11033 from "module_11033" /* 11033 */;
import _mod11034 from "module_11034" /* 11034 */;
import _mod11035 from "module_11035" /* 11035 */;
import _mod11036 from "module_11036" /* 11036 */;
import _mod11037 from "module_11037" /* 11037 */;
import _mod11038 from "module_11038" /* 11038 */;
import memoBuilder from "memoBuilder" /* 11039 */;
import _mod11040 from "module_11040" /* 11040 */;
import _flush from "_flush" /* 11041 */;
import _mod11042 from "module_11042" /* 11042 */;
import applyScopeDataToEvent from "applyScopeDataToEvent" /* 11043 */;
import notifyEventProcessors from "notifyEventProcessors" /* 11044 */;
import _mod11045 from "module_11045" /* 11045 */;
import SessionFlusher from "SessionFlusher" /* 11046 */;
import _mod11047 from "module_11047" /* 11047 */;
import _mod11048 from "module_11048" /* 11048 */;
import _mod11049 from "module_11049" /* 11049 */;
import _mod11050 from "module_11050" /* 11050 */;
import _mod11051 from "module_11051" /* 11051 */;
import _mod11052 from "module_11052" /* 11052 */;
import eventFromMessage from "eventFromMessage" /* 11053 */;
import _mod11054 from "module_11054" /* 11054 */;
import _mod11055 from "module_11055" /* 11055 */;
import _mod11056 from "module_11056" /* 11056 */;
import _mod11057 from "module_11057" /* 11057 */;
import _mod11058 from "module_11058" /* 11058 */;
import _mod11059 from "module_11059" /* 11059 */;
import _mod11060 from "module_11060" /* 11060 */;
import _mod11061 from "module_11061" /* 11061 */;
import _mod11062 from "module_11062" /* 11062 */;
import _mod11063 from "module_11063" /* 11063 */;
import _mod11064 from "module_11064" /* 11064 */;
import _mod11065 from "module_11065" /* 11065 */;
import _mod11066 from "module_11066" /* 11066 */;
import _mod11067 from "module_11067" /* 11067 */;
import _getEventFilterUrl from "_getEventFilterUrl" /* 11068 */;
import _mod11069 from "module_11069" /* 11069 */;
import _mod11070 from "module_11070" /* 11070 */;
import _mod11071 from "module_11071" /* 11071 */;
import _mod11073 from "module_11073" /* 11073 */;
import extractRequestData from "extractRequestData" /* 11074 */;
import stripUrlQueryAndFragment from "stripUrlQueryAndFragment" /* 11075 */;
import _mod11078 from "module_11078" /* 11078 */;
import _mod11079 from "module_11079" /* 11079 */;
import _mod11080 from "module_11080" /* 11080 */;
import debugIntegration from "debugIntegration" /* 11081 */;
import _mod11082 from "module_11082" /* 11082 */;
import extraErrorDataIntegration from "extraErrorDataIntegration" /* 11083 */;
import _mod11084 from "module_11084" /* 11084 */;
import _mod11085 from "module_11085" /* 11085 */;
import sessionTimingIntegration from "sessionTimingIntegration" /* 11086 */;
import _mod11087 from "module_11087" /* 11087 */;
import _mod11088 from "module_11088" /* 11088 */;
import _mod11089 from "module_11089" /* 11089 */;
import _mod11091 from "module_11091" /* 11091 */;
import metricsDefault from "metricsDefault" /* 11092 */;
import BrowserMetricsAggregator from "BrowserMetricsAggregator" /* 11097 */;
import _mod11098 from "module_11098" /* 11098 */;
import _mod11099 from "module_11099" /* 11099 */;
import _mod11100 from "module_11100" /* 11100 */;
import _mod11101 from "module_11101" /* 11101 */;
import _mod11102 from "module_11102" /* 11102 */;
import _mod11103 from "module_11103" /* 11103 */;
import _mod11104 from "module_11104" /* 11104 */;
import supportsFetch from "supportsFetch" /* 11105 */;
import _mod11106 from "module_11106" /* 11106 */;
import _mod11107 from "module_11107" /* 11107 */;
import _mod11108 from "module_11108" /* 11108 */;
import _mod11109 from "module_11109" /* 11109 */;
import _mod11110 from "module_11110" /* 11110 */;
import _mod11111 from "module_11111" /* 11111 */;
import _mod11112 from "module_11112" /* 11112 */;
import _mod11113 from "module_11113" /* 11113 */;
import _mod11114 from "module_11114" /* 11114 */;
import supportsHistory from "supportsHistory" /* 11115 */;
import _asyncNullishCoalesce2 from "_asyncNullishCoalesce2" /* 11116 */;
import _nullishCoalesce from "_nullishCoalesce" /* 11117 */;
import _asyncOptionalChain2 from "_asyncOptionalChain2" /* 11118 */;
import _asyncOptionalChainDelete2 from "_asyncOptionalChainDelete2" /* 11119 */;
import _optionalChain from "_optionalChain" /* 11120 */;
import _optionalChainDelete from "_optionalChainDelete" /* 11121 */;

const require = globalThis.__r;


export const registerSpanErrorInstrumentation = errorCallback.registerSpanErrorInstrumentation;
export const getCapturedScopesOnSpan = _mod11022.getCapturedScopesOnSpan;
export const setCapturedScopesOnSpan = _mod11022.setCapturedScopesOnSpan;
export const addTracingExtensions = _mod11023.addTracingExtensions;
export const TRACING_DEFAULTS = _mod11024.TRACING_DEFAULTS;
export const startIdleSpan = _mod11024.startIdleSpan;
export const SentrySpan = _mod11034.SentrySpan;
export const SentryNonRecordingSpan = _mod11026.SentryNonRecordingSpan;
export const SPAN_STATUS_ERROR = _mod11010.SPAN_STATUS_ERROR;
export const SPAN_STATUS_OK = _mod11010.SPAN_STATUS_OK;
export const SPAN_STATUS_UNSET = _mod11010.SPAN_STATUS_UNSET;
export const getSpanStatusFromHttpCode = _mod11010.getSpanStatusFromHttpCode;
export const setHttpStatus = _mod11010.setHttpStatus;
export const continueTrace = _mod11027.continueTrace;
export const startInactiveSpan = _mod11027.startInactiveSpan;
export const startNewTrace = _mod11027.startNewTrace;
export const startSpan = _mod11027.startSpan;
export const startSpanManual = _mod11027.startSpanManual;
export const suppressTracing = _mod11027.suppressTracing;
export const withActiveSpan = _mod11027.withActiveSpan;
export const getDynamicSamplingContextFromClient = _mod11029.getDynamicSamplingContextFromClient;
export const getDynamicSamplingContextFromScope = _mod11029.getDynamicSamplingContextFromScope;
export const getDynamicSamplingContextFromSpan = _mod11029.getDynamicSamplingContextFromSpan;
export const spanToBaggageHeader = _mod11029.spanToBaggageHeader;
export const setMeasurement = _mod11035.setMeasurement;
export const timedEventsToMeasurements = _mod11035.timedEventsToMeasurements;
export const sampleSpan = _mod11032.sampleSpan;
export const logSpanEnd = _mod11031.logSpanEnd;
export const logSpanStart = _mod11031.logSpanStart;
export const SEMANTIC_ATTRIBUTE_CACHE_HIT = _mod11008.SEMANTIC_ATTRIBUTE_CACHE_HIT;
export const SEMANTIC_ATTRIBUTE_CACHE_ITEM_SIZE = _mod11008.SEMANTIC_ATTRIBUTE_CACHE_ITEM_SIZE;
export const SEMANTIC_ATTRIBUTE_CACHE_KEY = _mod11008.SEMANTIC_ATTRIBUTE_CACHE_KEY;
export const SEMANTIC_ATTRIBUTE_EXCLUSIVE_TIME = _mod11008.SEMANTIC_ATTRIBUTE_EXCLUSIVE_TIME;
export const SEMANTIC_ATTRIBUTE_HTTP_REQUEST_METHOD = _mod11008.SEMANTIC_ATTRIBUTE_HTTP_REQUEST_METHOD;
export const SEMANTIC_ATTRIBUTE_PROFILE_ID = _mod11008.SEMANTIC_ATTRIBUTE_PROFILE_ID;
export const SEMANTIC_ATTRIBUTE_SENTRY_CUSTOM_SPAN_NAME = _mod11008.SEMANTIC_ATTRIBUTE_SENTRY_CUSTOM_SPAN_NAME;
export const SEMANTIC_ATTRIBUTE_SENTRY_IDLE_SPAN_FINISH_REASON = _mod11008.SEMANTIC_ATTRIBUTE_SENTRY_IDLE_SPAN_FINISH_REASON;
export const SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_UNIT = _mod11008.SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_UNIT;
export const SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_VALUE = _mod11008.SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_VALUE;
export const SEMANTIC_ATTRIBUTE_SENTRY_OP = _mod11008.SEMANTIC_ATTRIBUTE_SENTRY_OP;
export const SEMANTIC_ATTRIBUTE_SENTRY_ORIGIN = _mod11008.SEMANTIC_ATTRIBUTE_SENTRY_ORIGIN;
export const SEMANTIC_ATTRIBUTE_SENTRY_SAMPLE_RATE = _mod11008.SEMANTIC_ATTRIBUTE_SENTRY_SAMPLE_RATE;
export const SEMANTIC_ATTRIBUTE_SENTRY_SOURCE = _mod11008.SEMANTIC_ATTRIBUTE_SENTRY_SOURCE;
export const SEMANTIC_ATTRIBUTE_URL_FULL = _mod11008.SEMANTIC_ATTRIBUTE_URL_FULL;
export const createEventEnvelope = _mod11036.createEventEnvelope;
export const createSessionEnvelope = _mod11036.createSessionEnvelope;
export const createSpanEnvelope = _mod11036.createSpanEnvelope;
export const addEventProcessor = _flush.addEventProcessor;
export const captureCheckIn = _flush.captureCheckIn;
export const captureEvent = _flush.captureEvent;
export const captureException = _flush.captureException;
export const captureMessage = _flush.captureMessage;
export const captureSession = _flush.captureSession;
export const close = _flush.close;
export const endSession = _flush.endSession;
export const flush = _flush.flush;
export const isEnabled = _flush.isEnabled;
export const isInitialized = _flush.isInitialized;
export const lastEventId = _flush.lastEventId;
export const setContext = _flush.setContext;
export const setExtra = _flush.setExtra;
export const setExtras = _flush.setExtras;
export const setTag = _flush.setTag;
export const setTags = _flush.setTags;
export const setUser = _flush.setUser;
export const startSession = _flush.startSession;
export const withMonitor = _flush.withMonitor;
export const getClient = _mod11020.getClient;
export const getCurrentScope = _mod11020.getCurrentScope;
export const getGlobalScope = _mod11020.getGlobalScope;
export const getIsolationScope = _mod11020.getIsolationScope;
export const getTraceContextFromScope = _mod11020.getTraceContextFromScope;
export const withIsolationScope = _mod11020.withIsolationScope;
export const withScope = _mod11020.withScope;
export const getDefaultCurrentScope = _mod11019.getDefaultCurrentScope;
export const getDefaultIsolationScope = _mod11019.getDefaultIsolationScope;
export const setAsyncContextStrategy = _mod11012.setAsyncContextStrategy;
export const getMainCarrier = _mod11011.getMainCarrier;
export const closeSession = _mod11016.closeSession;
export const makeSession = _mod11016.makeSession;
export const updateSession = _mod11016.updateSession;
export const SessionFlusher = SessionFlusher.SessionFlusher;
export const Scope = ScopeClass.Scope;
export const notifyEventProcessors = notifyEventProcessors.notifyEventProcessors;
export const getEnvelopeEndpointWithUrlEncodedAuth = _mod11047.getEnvelopeEndpointWithUrlEncodedAuth;
export const getReportDialogEndpoint = _mod11047.getReportDialogEndpoint;
export const BaseClient = _mod11048.BaseClient;
export const ServerRuntimeClient = _mod11052.ServerRuntimeClient;
export const initAndBind = _mod11055.initAndBind;
export const setCurrentClient = _mod11055.setCurrentClient;
export const createTransport = _mod11056.createTransport;
export const makeOfflineTransport = _mod11059.makeOfflineTransport;
export const makeMultiplexedTransport = _mod11060.makeMultiplexedTransport;
export const addIntegration = _mod11049.addIntegration;
export const defineIntegration = _mod11049.defineIntegration;
export const getIntegrationsToSetup = _mod11049.getIntegrationsToSetup;
export const applyScopeDataToEvent = applyScopeDataToEvent.applyScopeDataToEvent;
export const mergeScopeData = applyScopeDataToEvent.mergeScopeData;
export const prepareEvent = _mod11042.prepareEvent;
export const createCheckInEnvelope = _mod11054.createCheckInEnvelope;
export const hasTracingEnabled = _mod11025.hasTracingEnabled;
export const isSentryRequestUrl = _mod11061.isSentryRequestUrl;
export const handleCallbackErrors = _mod11028.handleCallbackErrors;
export const parameterize = _mod11062.parameterize;
export const addChildSpanToSpan = spanTimeInputToSeconds.addChildSpanToSpan;
export const getActiveSpan = spanTimeInputToSeconds.getActiveSpan;
export const getRootSpan = spanTimeInputToSeconds.getRootSpan;
export const getSpanDescendants = spanTimeInputToSeconds.getSpanDescendants;
export const getStatusMessage = spanTimeInputToSeconds.getStatusMessage;
export const spanIsSampled = spanTimeInputToSeconds.spanIsSampled;
export const spanTimeInputToSeconds = spanTimeInputToSeconds.spanTimeInputToSeconds;
export const spanToJSON = spanTimeInputToSeconds.spanToJSON;
export const spanToTraceContext = spanTimeInputToSeconds.spanToTraceContext;
export const spanToTraceHeader = spanTimeInputToSeconds.spanToTraceHeader;
export const updateSpanName = spanTimeInputToSeconds.updateSpanName;
export const parseSampleRate = _mod11033.parseSampleRate;
export const applySdkMetadata = _mod11063.applySdkMetadata;
export const getTraceData = _mod11064.getTraceData;
export const getTraceMetaTags = _mod11065.getTraceMetaTags;
export const DEFAULT_ENVIRONMENT = _mod11030.DEFAULT_ENVIRONMENT;
export const addBreadcrumb = _mod11066.addBreadcrumb;
export const functionToStringIntegration = _mod11067.functionToStringIntegration;
export const inboundFiltersIntegration = _getEventFilterUrl.inboundFiltersIntegration;
export const linkedErrorsIntegration = _mod11069.linkedErrorsIntegration;
export const moduleMetadataIntegration = _mod11071.moduleMetadataIntegration;
export const requestDataIntegration = _mod11073.requestDataIntegration;
export const captureConsoleIntegration = _mod11078.captureConsoleIntegration;
export const debugIntegration = debugIntegration.debugIntegration;
export const dedupeIntegration = _mod11082.dedupeIntegration;
export const extraErrorDataIntegration = extraErrorDataIntegration.extraErrorDataIntegration;
export const rewriteFramesIntegration = _mod11084.rewriteFramesIntegration;
export const sessionTimingIntegration = sessionTimingIntegration.sessionTimingIntegration;
export const zodErrorsIntegration = _mod11087.zodErrorsIntegration;
export const thirdPartyErrorFilterIntegration = _mod11088.thirdPartyErrorFilterIntegration;
export const metrics = _mod11089.metrics;
export const profiler = _mod11091.profiler;
export const metricsDefault = metricsDefault.metricsDefault;
export const BrowserMetricsAggregator = BrowserMetricsAggregator.BrowserMetricsAggregator;
export const getMetricSummaryJsonForSpan = _mod11009.getMetricSummaryJsonForSpan;
export const addTracingHeadersToFetchRequest = _mod11098.addTracingHeadersToFetchRequest;
export const instrumentFetchRequest = _mod11098.instrumentFetchRequest;
export const trpcMiddleware = _mod11099.trpcMiddleware;
export const captureFeedback = _mod11100.captureFeedback;
export const getCurrentHub = _mod11101.getCurrentHub;
export const getCurrentHubShim = _mod11101.getCurrentHubShim;
export const applyAggregateErrorsToEvent = _mod11070.applyAggregateErrorsToEvent;
export const flatten = _mod11102.flatten;
export const getBreadcrumbLogLevelFromHttpStatusCode = _mod11103.getBreadcrumbLogLevelFromHttpStatusCode;
export const getComponentName = _mod11001.getComponentName;
export const getDomElement = _mod11001.getDomElement;
export const getLocationHref = _mod11001.getLocationHref;
export const htmlTreeAsString = _mod11001.htmlTreeAsString;
export const dsnFromString = _mod11040.dsnFromString;
export const dsnToString = _mod11040.dsnToString;
export const makeDsn = _mod11040.makeDsn;
export const SentryError = _mod11050.SentryError;
export const GLOBAL_OBJ = _mod10994.GLOBAL_OBJ;
export const getGlobalSingleton = _mod10994.getGlobalSingleton;
export const addConsoleInstrumentationHandler = _mod11079.addConsoleInstrumentationHandler;
export const addFetchEndInstrumentationHandler = _mod11104.addFetchEndInstrumentationHandler;
export const addFetchInstrumentationHandler = _mod11104.addFetchInstrumentationHandler;
export const addGlobalErrorInstrumentationHandler = _mod10990.addGlobalErrorInstrumentationHandler;
export const addGlobalUnhandledRejectionInstrumentationHandler = _mod10997.addGlobalUnhandledRejectionInstrumentationHandler;
export const addHandler = _mod10991.addHandler;
export const maybeInstrument = _mod10991.maybeInstrument;
export const resetInstrumentationHandlers = _mod10991.resetInstrumentationHandlers;
export const triggerHandlers = _mod10991.triggerHandlers;
export const isDOMError = _mod11000.isDOMError;
export const isDOMException = _mod11000.isDOMException;
export const isElement = _mod11000.isElement;
export const isError = _mod11000.isError;
export const isErrorEvent = _mod11000.isErrorEvent;
export const isEvent = _mod11000.isEvent;
export const isInstanceOf = _mod11000.isInstanceOf;
export const isParameterizedString = _mod11000.isParameterizedString;
export const isPlainObject = _mod11000.isPlainObject;
export const isPrimitive = _mod11000.isPrimitive;
export const isRegExp = _mod11000.isRegExp;
export const isString = _mod11000.isString;
export const isSyntheticEvent = _mod11000.isSyntheticEvent;
export const isThenable = _mod11000.isThenable;
export const isVueViewModel = _mod11000.isVueViewModel;
export const isBrowser = _mod11106.isBrowser;
export const CONSOLE_LEVELS = _mod10993.CONSOLE_LEVELS;
export const consoleSandbox = _mod10993.consoleSandbox;
export const logger = _mod10993.logger;
export const originalConsoleMethods = _mod10993.originalConsoleMethods;
export const memoBuilder = memoBuilder.memoBuilder;
export const addContextToFrame = _mod11004.addContextToFrame;
export const addExceptionMechanism = _mod11004.addExceptionMechanism;
export const addExceptionTypeValue = _mod11004.addExceptionTypeValue;
export const arrayify = _mod11004.arrayify;
export const checkOrSetAlreadyCaught = _mod11004.checkOrSetAlreadyCaught;
export const getEventDescription = _mod11004.getEventDescription;
export const parseSemver = _mod11004.parseSemver;
export const uuid4 = _mod11004.uuid4;
export const dynamicRequire = _mod11107.dynamicRequire;
export const isNodeEnv = _mod11107.isNodeEnv;
export const loadModule = _mod11107.loadModule;
export const normalize = _mod11038.normalize;
export const normalizeToSize = _mod11038.normalizeToSize;
export const normalizeUrlToBase = _mod11038.normalizeUrlToBase;
export const addNonEnumerableProperty = _mod10999.addNonEnumerableProperty;
export const convertToPlainObject = _mod10999.convertToPlainObject;
export const dropUndefinedKeys = _mod10999.dropUndefinedKeys;
export const extractExceptionKeysForMessage = _mod10999.extractExceptionKeysForMessage;
export const fill = _mod10999.fill;
export const getOriginalFunction = _mod10999.getOriginalFunction;
export const markFunctionWrapped = _mod10999.markFunctionWrapped;
export const objectify = _mod10999.objectify;
export const urlEncode = _mod10999.urlEncode;
export const basename = _mod11085.basename;
export const dirname = _mod11085.dirname;
export const isAbsolute = _mod11085.isAbsolute;
export const join = _mod11085.join;
export const normalizePath = _mod11085.normalizePath;
export const relative = _mod11085.relative;
export const resolve = _mod11085.resolve;
export const makePromiseBuffer = _mod11057.makePromiseBuffer;
export const DEFAULT_USER_INCLUDES = extractRequestData.DEFAULT_USER_INCLUDES;
export const addNormalizedRequestDataToEvent = extractRequestData.addNormalizedRequestDataToEvent;
export const addRequestDataToEvent = extractRequestData.addRequestDataToEvent;
export const extractPathForTransaction = extractRequestData.extractPathForTransaction;
export const extractQueryParamsFromUrl = extractRequestData.extractQueryParamsFromUrl;
export const extractRequestData = extractRequestData.extractRequestData;
export const headersToDict = extractRequestData.headersToDict;
export const httpRequestToRequestData = extractRequestData.httpRequestToRequestData;
export const winterCGHeadersToDict = extractRequestData.winterCGHeadersToDict;
export const winterCGRequestToRequestData = extractRequestData.winterCGRequestToRequestData;
export const severityLevelFromString = _mod11080.severityLevelFromString;
export const validSeverityLevels = _mod11080.validSeverityLevels;
export const UNKNOWN_FUNCTION = stackParserFromStackParserOptions.UNKNOWN_FUNCTION;
export const createStackParser = stackParserFromStackParserOptions.createStackParser;
export const getFramesFromEvent = stackParserFromStackParserOptions.getFramesFromEvent;
export const getFunctionName = stackParserFromStackParserOptions.getFunctionName;
export const stackParserFromStackParserOptions = stackParserFromStackParserOptions.stackParserFromStackParserOptions;
export const stripSentryFramesAndReverse = stackParserFromStackParserOptions.stripSentryFramesAndReverse;
export const filenameIsInApp = _mod11109.filenameIsInApp;
export const node = _mod11109.node;
export const nodeStackLineParser = _mod11109.nodeStackLineParser;
export const isMatchingPattern = _mod11002.isMatchingPattern;
export const safeJoin = _mod11002.safeJoin;
export const snipLine = _mod11002.snipLine;
export const stringMatchesSomePattern = _mod11002.stringMatchesSomePattern;
export const truncate = _mod11002.truncate;
export const isNativeFunction = supportsFetch.isNativeFunction;
export const supportsDOMError = supportsFetch.supportsDOMError;
export const supportsDOMException = supportsFetch.supportsDOMException;
export const supportsErrorEvent = supportsFetch.supportsErrorEvent;
export const supportsFetch = supportsFetch.supportsFetch;
export const supportsNativeFetch = supportsFetch.supportsNativeFetch;
export const supportsReferrerPolicy = supportsFetch.supportsReferrerPolicy;
export const supportsReportingObserver = supportsFetch.supportsReportingObserver;
export const SyncPromise = _mod11017.SyncPromise;
export const rejectedSyncPromise = _mod11017.rejectedSyncPromise;
export const resolvedSyncPromise = _mod11017.resolvedSyncPromise;
export const _browserPerformanceTimeOriginMode = require("module_11007")._browserPerformanceTimeOriginMode;
export const browserPerformanceTimeOrigin = require("module_11007").browserPerformanceTimeOrigin;
export const dateTimestampInSeconds = require("module_11007").dateTimestampInSeconds;
export const timestampInSeconds = require("module_11007").timestampInSeconds;
export const TRACEPARENT_REGEXP = _mod11005.TRACEPARENT_REGEXP;
export const extractTraceparentData = _mod11005.extractTraceparentData;
export const generateSentryTraceHeader = _mod11005.generateSentryTraceHeader;
export const propagationContextFromHeaders = _mod11005.propagationContextFromHeaders;
export const getSDKSource = _mod11108.getSDKSource;
export const isBrowserBundle = _mod11108.isBrowserBundle;
export const addItemToEnvelope = _mod11037.addItemToEnvelope;
export const createAttachmentEnvelopeItem = _mod11037.createAttachmentEnvelopeItem;
export const createEnvelope = _mod11037.createEnvelope;
export const createEventEnvelopeHeaders = _mod11037.createEventEnvelopeHeaders;
export const createSpanEnvelopeItem = _mod11037.createSpanEnvelopeItem;
export const envelopeContainsItemType = _mod11037.envelopeContainsItemType;
export const envelopeItemTypeToDataCategory = _mod11037.envelopeItemTypeToDataCategory;
export const forEachEnvelopeItem = _mod11037.forEachEnvelopeItem;
export const getSdkMetadataForEnvelopeHeader = _mod11037.getSdkMetadataForEnvelopeHeader;
export const parseEnvelope = _mod11037.parseEnvelope;
export const serializeEnvelope = _mod11037.serializeEnvelope;
export const createClientReportEnvelope = _mod11051.createClientReportEnvelope;
export const DEFAULT_RETRY_AFTER = _mod11058.DEFAULT_RETRY_AFTER;
export const disabledUntil = _mod11058.disabledUntil;
export const isRateLimited = _mod11058.isRateLimited;
export const parseRetryAfterHeader = _mod11058.parseRetryAfterHeader;
export const updateRateLimits = _mod11058.updateRateLimits;
export const BAGGAGE_HEADER_NAME = BAGGAGE_HEADER_NAME.BAGGAGE_HEADER_NAME;
export const MAX_BAGGAGE_STRING_LENGTH = BAGGAGE_HEADER_NAME.MAX_BAGGAGE_STRING_LENGTH;
export const SENTRY_BAGGAGE_KEY_PREFIX = BAGGAGE_HEADER_NAME.SENTRY_BAGGAGE_KEY_PREFIX;
export const SENTRY_BAGGAGE_KEY_PREFIX_REGEX = BAGGAGE_HEADER_NAME.SENTRY_BAGGAGE_KEY_PREFIX_REGEX;
export const baggageHeaderToDynamicSamplingContext = BAGGAGE_HEADER_NAME.baggageHeaderToDynamicSamplingContext;
export const dynamicSamplingContextToSentryBaggageHeader = BAGGAGE_HEADER_NAME.dynamicSamplingContextToSentryBaggageHeader;
export const parseBaggageHeader = BAGGAGE_HEADER_NAME.parseBaggageHeader;
export const getNumberOfUrlSegments = stripUrlQueryAndFragment.getNumberOfUrlSegments;
export const getSanitizedUrlString = stripUrlQueryAndFragment.getSanitizedUrlString;
export const parseUrl = stripUrlQueryAndFragment.parseUrl;
export const stripUrlQueryAndFragment = stripUrlQueryAndFragment.stripUrlQueryAndFragment;
export const makeFifoCache = _mod11110.makeFifoCache;
export const eventFromMessage = eventFromMessage.eventFromMessage;
export const eventFromUnknownInput = eventFromMessage.eventFromUnknownInput;
export const exceptionFromError = eventFromMessage.exceptionFromError;
export const parseStackFrames = eventFromMessage.parseStackFrames;
export const callFrameToStackFrame = _mod11111.callFrameToStackFrame;
export const watchdogTimer = _mod11111.watchdogTimer;
export const LRUMap = _mod11112.LRUMap;
export const generatePropagationContext = generatePropagationContext.generatePropagationContext;
export const generateSpanId = generatePropagationContext.generateSpanId;
export const generateTraceId = generatePropagationContext.generateTraceId;
export const vercelWaitUntil = _mod11113.vercelWaitUntil;
export const SDK_VERSION = _mod10995.SDK_VERSION;
export const getDebugImagesForResources = _mod11045.getDebugImagesForResources;
export const getFilenameToDebugIdMap = _mod11045.getFilenameToDebugIdMap;
export const escapeStringForRegex = _mod11114.escapeStringForRegex;
export const supportsHistory = supportsHistory.supportsHistory;
export const _asyncNullishCoalesce = _asyncNullishCoalesce2._asyncNullishCoalesce;
export const _asyncOptionalChain = _asyncOptionalChain2._asyncOptionalChain;
export const _asyncOptionalChainDelete = _asyncOptionalChainDelete2._asyncOptionalChainDelete;
export const _nullishCoalesce = _nullishCoalesce._nullishCoalesce;
export const _optionalChain = _optionalChain._optionalChain;
export const _optionalChainDelete = _optionalChainDelete._optionalChainDelete;