// _runtime/metro/11162__.js
import errorCallback from "../11163_errorCallback.js";
import _mod11164 from "11164__.js";
import _mod11165 from "11165__.js";
import _mod11167 from "11167__.js";
import _mod11168 from "11168__.js";
import _mod11169 from "11169__.js";
import stackParserFromStackParserOptions from "../11170_stackParserFromStackParserOptions.js";
import _mod11171 from "11171__.js";
import spanTimeInputToSeconds from "../11172_spanTimeInputToSeconds.js";
import _mod11173 from "11173__.js";
import _mod11174 from "11174__.js";
import _mod11175 from "11175__.js";
import _mod11176 from "11176__.js";
import generatePropagationContext from "../11177_generatePropagationContext.js";
import _mod11178 from "11178__.js";
import _mod11179 from "11179__.js";
import BAGGAGE_HEADER_NAME from "../11180_BAGGAGE_HEADER_NAME.js";
import _mod11182 from "11182__.js";
import _mod11183 from "11183__.js";
import _mod11184 from "11184__.js";
import _mod11185 from "11185__.js";
import _mod11186 from "11186__.js";
import ScopeClass from "../11188_ScopeClass.js";
import _mod11190 from "11190__.js";
import _mod11191 from "11191__.js";
import _mod11193 from "11193__.js";
import _mod11194 from "11194__.js";
import _mod11196 from "11196__.js";
import _mod11197 from "11197__.js";
import _mod11198 from "11198__.js";
import _mod11199 from "11199__.js";
import _mod11200 from "11200__.js";
import _mod11201 from "11201__.js";
import _mod11202 from "11202__.js";
import _mod11203 from "11203__.js";
import _mod11204 from "11204__.js";
import _mod11205 from "11205__.js";
import _mod11206 from "11206__.js";
import _mod11207 from "11207__.js";
import _mod11208 from "11208__.js";
import _mod11209 from "11209__.js";
import _mod11210 from "11210__.js";
import _mod11211 from "11211__.js";
import _mod11212 from "11212__.js";
import memoBuilder from "../11213_memoBuilder.js";
import _mod11214 from "11214__.js";
import _flush from "../11215__flush.js";
import _mod11216 from "11216__.js";
import applyScopeDataToEvent from "../11217_applyScopeDataToEvent.js";
import notifyEventProcessors from "../11218_notifyEventProcessors.js";
import _mod11219 from "11219__.js";
import SessionFlusher from "../11220_SessionFlusher.js";
import _mod11221 from "11221__.js";
import _mod11222 from "11222__.js";
import _mod11223 from "11223__.js";
import _mod11224 from "11224__.js";
import _mod11225 from "11225__.js";
import _mod11226 from "11226__.js";
import eventFromMessage from "../11227_eventFromMessage.js";
import _mod11228 from "11228__.js";
import _mod11229 from "11229__.js";
import _mod11230 from "11230__.js";
import _mod11231 from "11231__.js";
import _mod11232 from "11232__.js";
import _mod11233 from "11233__.js";
import _mod11234 from "11234__.js";
import _mod11235 from "11235__.js";
import _mod11236 from "11236__.js";
import _mod11237 from "11237__.js";
import _mod11238 from "11238__.js";
import _mod11239 from "11239__.js";
import _mod11240 from "11240__.js";
import _mod11241 from "11241__.js";
import _getEventFilterUrl from "../11242__getEventFilterUrl.js";
import _mod11243 from "11243__.js";
import _mod11244 from "11244__.js";
import _mod11245 from "11245__.js";
import _mod11247 from "11247__.js";
import extractRequestData from "../11248_extractRequestData.js";
import stripUrlQueryAndFragment from "../11249_stripUrlQueryAndFragment.js";
import _mod11252 from "11252__.js";
import _mod11253 from "11253__.js";
import _mod11254 from "11254__.js";
import debugIntegration from "../11255_debugIntegration.js";
import _mod11256 from "11256__.js";
import extraErrorDataIntegration from "../11257_extraErrorDataIntegration.js";
import _mod11258 from "11258__.js";
import _mod11259 from "11259__.js";
import sessionTimingIntegration from "../11260_sessionTimingIntegration.js";
import _mod11261 from "11261__.js";
import _mod11262 from "11262__.js";
import _mod11263 from "11263__.js";
import _mod11265 from "11265__.js";
import metricsDefault from "../11266_metricsDefault.js";
import BrowserMetricsAggregator from "../11271_BrowserMetricsAggregator.js";
import _mod11272 from "11272__.js";
import _mod11273 from "11273__.js";
import _mod11274 from "11274__.js";
import _mod11275 from "11275__.js";
import _mod11276 from "11276__.js";
import _mod11277 from "11277__.js";
import _mod11278 from "11278__.js";
import supportsFetch from "../11279_supportsFetch.js";
import _mod11280 from "11280__.js";
import _mod11281 from "11281__.js";
import _mod11282 from "11282__.js";
import _mod11283 from "11283__.js";
import _mod11284 from "11284__.js";
import _mod11285 from "11285__.js";
import _mod11286 from "11286__.js";
import _mod11287 from "11287__.js";
import _mod11288 from "11288__.js";
import supportsHistory from "../11289_supportsHistory.js";
import _asyncNullishCoalesce2 from "../11290__asyncNullishCoalesce2.js";
import _nullishCoalesce from "../11291__nullishCoalesce.js";
import _asyncOptionalChain2 from "../11292__asyncOptionalChain2.js";
import _asyncOptionalChainDelete2 from "../11293__asyncOptionalChainDelete2.js";
import _optionalChain from "../11294__optionalChain.js";
import _optionalChainDelete from "../11295__optionalChainDelete.js";

const require = globalThis.__r;

export const registerSpanErrorInstrumentation = errorCallback.registerSpanErrorInstrumentation;
export const getCapturedScopesOnSpan = _mod11196.getCapturedScopesOnSpan;
export const setCapturedScopesOnSpan = _mod11196.setCapturedScopesOnSpan;
export const addTracingExtensions = _mod11197.addTracingExtensions;
export const TRACING_DEFAULTS = _mod11198.TRACING_DEFAULTS;
export const startIdleSpan = _mod11198.startIdleSpan;
export const SentrySpan = _mod11208.SentrySpan;
export const SentryNonRecordingSpan = _mod11200.SentryNonRecordingSpan;
export const SPAN_STATUS_ERROR = _mod11184.SPAN_STATUS_ERROR;
export const SPAN_STATUS_OK = _mod11184.SPAN_STATUS_OK;
export const SPAN_STATUS_UNSET = _mod11184.SPAN_STATUS_UNSET;
export const getSpanStatusFromHttpCode = _mod11184.getSpanStatusFromHttpCode;
export const setHttpStatus = _mod11184.setHttpStatus;
export const continueTrace = _mod11201.continueTrace;
export const startInactiveSpan = _mod11201.startInactiveSpan;
export const startNewTrace = _mod11201.startNewTrace;
export const startSpan = _mod11201.startSpan;
export const startSpanManual = _mod11201.startSpanManual;
export const suppressTracing = _mod11201.suppressTracing;
export const withActiveSpan = _mod11201.withActiveSpan;
export const getDynamicSamplingContextFromClient = _mod11203.getDynamicSamplingContextFromClient;
export const getDynamicSamplingContextFromScope = _mod11203.getDynamicSamplingContextFromScope;
export const getDynamicSamplingContextFromSpan = _mod11203.getDynamicSamplingContextFromSpan;
export const spanToBaggageHeader = _mod11203.spanToBaggageHeader;
export const setMeasurement = _mod11209.setMeasurement;
export const timedEventsToMeasurements = _mod11209.timedEventsToMeasurements;
export const sampleSpan = _mod11206.sampleSpan;
export const logSpanEnd = _mod11205.logSpanEnd;
export const logSpanStart = _mod11205.logSpanStart;
export const SEMANTIC_ATTRIBUTE_CACHE_HIT = _mod11182.SEMANTIC_ATTRIBUTE_CACHE_HIT;
export const SEMANTIC_ATTRIBUTE_CACHE_ITEM_SIZE = _mod11182.SEMANTIC_ATTRIBUTE_CACHE_ITEM_SIZE;
export const SEMANTIC_ATTRIBUTE_CACHE_KEY = _mod11182.SEMANTIC_ATTRIBUTE_CACHE_KEY;
export const SEMANTIC_ATTRIBUTE_EXCLUSIVE_TIME = _mod11182.SEMANTIC_ATTRIBUTE_EXCLUSIVE_TIME;
export const SEMANTIC_ATTRIBUTE_HTTP_REQUEST_METHOD = _mod11182.SEMANTIC_ATTRIBUTE_HTTP_REQUEST_METHOD;
export const SEMANTIC_ATTRIBUTE_PROFILE_ID = _mod11182.SEMANTIC_ATTRIBUTE_PROFILE_ID;
export const SEMANTIC_ATTRIBUTE_SENTRY_CUSTOM_SPAN_NAME = _mod11182.SEMANTIC_ATTRIBUTE_SENTRY_CUSTOM_SPAN_NAME;
export const SEMANTIC_ATTRIBUTE_SENTRY_IDLE_SPAN_FINISH_REASON =
  _mod11182.SEMANTIC_ATTRIBUTE_SENTRY_IDLE_SPAN_FINISH_REASON;
export const SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_UNIT = _mod11182.SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_UNIT;
export const SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_VALUE = _mod11182.SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_VALUE;
export const SEMANTIC_ATTRIBUTE_SENTRY_OP = _mod11182.SEMANTIC_ATTRIBUTE_SENTRY_OP;
export const SEMANTIC_ATTRIBUTE_SENTRY_ORIGIN = _mod11182.SEMANTIC_ATTRIBUTE_SENTRY_ORIGIN;
export const SEMANTIC_ATTRIBUTE_SENTRY_SAMPLE_RATE = _mod11182.SEMANTIC_ATTRIBUTE_SENTRY_SAMPLE_RATE;
export const SEMANTIC_ATTRIBUTE_SENTRY_SOURCE = _mod11182.SEMANTIC_ATTRIBUTE_SENTRY_SOURCE;
export const SEMANTIC_ATTRIBUTE_URL_FULL = _mod11182.SEMANTIC_ATTRIBUTE_URL_FULL;
export const createEventEnvelope = _mod11210.createEventEnvelope;
export const createSessionEnvelope = _mod11210.createSessionEnvelope;
export const createSpanEnvelope = _mod11210.createSpanEnvelope;
export const addEventProcessor = _flush.addEventProcessor;
export const captureCheckIn = _flush.captureCheckIn;
export const captureEvent = _flush.captureEvent;
export const captureException = _flush.captureException;
export const captureMessage = _flush.captureMessage;
export const captureSession = _flush.captureSession;
export const close = _flush.close;
export const endSession = _flush.endSession;
export const flush = _flush.flush;
export const isEnabled = _flush.isEnabled;
export const isInitialized = _flush.isInitialized;
export const lastEventId = _flush.lastEventId;
export const setContext = _flush.setContext;
export const setExtra = _flush.setExtra;
export const setExtras = _flush.setExtras;
export const setTag = _flush.setTag;
export const setTags = _flush.setTags;
export const setUser = _flush.setUser;
export const startSession = _flush.startSession;
export const withMonitor = _flush.withMonitor;
export const getClient = _mod11194.getClient;
export const getCurrentScope = _mod11194.getCurrentScope;
export const getGlobalScope = _mod11194.getGlobalScope;
export const getIsolationScope = _mod11194.getIsolationScope;
export const getTraceContextFromScope = _mod11194.getTraceContextFromScope;
export const withIsolationScope = _mod11194.withIsolationScope;
export const withScope = _mod11194.withScope;
export const getDefaultCurrentScope = _mod11193.getDefaultCurrentScope;
export const getDefaultIsolationScope = _mod11193.getDefaultIsolationScope;
export const setAsyncContextStrategy = _mod11186.setAsyncContextStrategy;
export const getMainCarrier = _mod11185.getMainCarrier;
export const closeSession = _mod11190.closeSession;
export const makeSession = _mod11190.makeSession;
export const updateSession = _mod11190.updateSession;
export const SessionFlusher = SessionFlusher.SessionFlusher;
export const Scope = ScopeClass.Scope;
export const notifyEventProcessors = notifyEventProcessors.notifyEventProcessors;
export const getEnvelopeEndpointWithUrlEncodedAuth = _mod11221.getEnvelopeEndpointWithUrlEncodedAuth;
export const getReportDialogEndpoint = _mod11221.getReportDialogEndpoint;
export const BaseClient = _mod11222.BaseClient;
export const ServerRuntimeClient = _mod11226.ServerRuntimeClient;
export const initAndBind = _mod11229.initAndBind;
export const setCurrentClient = _mod11229.setCurrentClient;
export const createTransport = _mod11230.createTransport;
export const makeOfflineTransport = _mod11233.makeOfflineTransport;
export const makeMultiplexedTransport = _mod11234.makeMultiplexedTransport;
export const addIntegration = _mod11223.addIntegration;
export const defineIntegration = _mod11223.defineIntegration;
export const getIntegrationsToSetup = _mod11223.getIntegrationsToSetup;
export const applyScopeDataToEvent = applyScopeDataToEvent.applyScopeDataToEvent;
export const mergeScopeData = applyScopeDataToEvent.mergeScopeData;
export const prepareEvent = _mod11216.prepareEvent;
export const createCheckInEnvelope = _mod11228.createCheckInEnvelope;
export const hasTracingEnabled = _mod11199.hasTracingEnabled;
export const isSentryRequestUrl = _mod11235.isSentryRequestUrl;
export const handleCallbackErrors = _mod11202.handleCallbackErrors;
export const parameterize = _mod11236.parameterize;
export const addChildSpanToSpan = spanTimeInputToSeconds.addChildSpanToSpan;
export const getActiveSpan = spanTimeInputToSeconds.getActiveSpan;
export const getRootSpan = spanTimeInputToSeconds.getRootSpan;
export const getSpanDescendants = spanTimeInputToSeconds.getSpanDescendants;
export const getStatusMessage = spanTimeInputToSeconds.getStatusMessage;
export const spanIsSampled = spanTimeInputToSeconds.spanIsSampled;
export const spanTimeInputToSeconds = spanTimeInputToSeconds.spanTimeInputToSeconds;
export const spanToJSON = spanTimeInputToSeconds.spanToJSON;
export const spanToTraceContext = spanTimeInputToSeconds.spanToTraceContext;
export const spanToTraceHeader = spanTimeInputToSeconds.spanToTraceHeader;
export const updateSpanName = spanTimeInputToSeconds.updateSpanName;
export const parseSampleRate = _mod11207.parseSampleRate;
export const applySdkMetadata = _mod11237.applySdkMetadata;
export const getTraceData = _mod11238.getTraceData;
export const getTraceMetaTags = _mod11239.getTraceMetaTags;
export const DEFAULT_ENVIRONMENT = _mod11204.DEFAULT_ENVIRONMENT;
export const addBreadcrumb = _mod11240.addBreadcrumb;
export const functionToStringIntegration = _mod11241.functionToStringIntegration;
export const inboundFiltersIntegration = _getEventFilterUrl.inboundFiltersIntegration;
export const linkedErrorsIntegration = _mod11243.linkedErrorsIntegration;
export const moduleMetadataIntegration = _mod11245.moduleMetadataIntegration;
export const requestDataIntegration = _mod11247.requestDataIntegration;
export const captureConsoleIntegration = _mod11252.captureConsoleIntegration;
export const debugIntegration = debugIntegration.debugIntegration;
export const dedupeIntegration = _mod11256.dedupeIntegration;
export const extraErrorDataIntegration = extraErrorDataIntegration.extraErrorDataIntegration;
export const rewriteFramesIntegration = _mod11258.rewriteFramesIntegration;
export const sessionTimingIntegration = sessionTimingIntegration.sessionTimingIntegration;
export const zodErrorsIntegration = _mod11261.zodErrorsIntegration;
export const thirdPartyErrorFilterIntegration = _mod11262.thirdPartyErrorFilterIntegration;
export const metrics = _mod11263.metrics;
export const profiler = _mod11265.profiler;
export const metricsDefault = metricsDefault.metricsDefault;
export const BrowserMetricsAggregator = BrowserMetricsAggregator.BrowserMetricsAggregator;
export const getMetricSummaryJsonForSpan = _mod11183.getMetricSummaryJsonForSpan;
export const addTracingHeadersToFetchRequest = _mod11272.addTracingHeadersToFetchRequest;
export const instrumentFetchRequest = _mod11272.instrumentFetchRequest;
export const trpcMiddleware = _mod11273.trpcMiddleware;
export const captureFeedback = _mod11274.captureFeedback;
export const getCurrentHub = _mod11275.getCurrentHub;
export const getCurrentHubShim = _mod11275.getCurrentHubShim;
export const applyAggregateErrorsToEvent = _mod11244.applyAggregateErrorsToEvent;
export const flatten = _mod11276.flatten;
export const getBreadcrumbLogLevelFromHttpStatusCode = _mod11277.getBreadcrumbLogLevelFromHttpStatusCode;
export const getComponentName = _mod11175.getComponentName;
export const getDomElement = _mod11175.getDomElement;
export const getLocationHref = _mod11175.getLocationHref;
export const htmlTreeAsString = _mod11175.htmlTreeAsString;
export const dsnFromString = _mod11214.dsnFromString;
export const dsnToString = _mod11214.dsnToString;
export const makeDsn = _mod11214.makeDsn;
export const SentryError = _mod11224.SentryError;
export const GLOBAL_OBJ = _mod11168.GLOBAL_OBJ;
export const getGlobalSingleton = _mod11168.getGlobalSingleton;
export const addConsoleInstrumentationHandler = _mod11253.addConsoleInstrumentationHandler;
export const addFetchEndInstrumentationHandler = _mod11278.addFetchEndInstrumentationHandler;
export const addFetchInstrumentationHandler = _mod11278.addFetchInstrumentationHandler;
export const addGlobalErrorInstrumentationHandler = _mod11164.addGlobalErrorInstrumentationHandler;
export const addGlobalUnhandledRejectionInstrumentationHandler =
  _mod11171.addGlobalUnhandledRejectionInstrumentationHandler;
export const addHandler = _mod11165.addHandler;
export const maybeInstrument = _mod11165.maybeInstrument;
export const resetInstrumentationHandlers = _mod11165.resetInstrumentationHandlers;
export const triggerHandlers = _mod11165.triggerHandlers;
export const isDOMError = _mod11174.isDOMError;
export const isDOMException = _mod11174.isDOMException;
export const isElement = _mod11174.isElement;
export const isError = _mod11174.isError;
export const isErrorEvent = _mod11174.isErrorEvent;
export const isEvent = _mod11174.isEvent;
export const isInstanceOf = _mod11174.isInstanceOf;
export const isParameterizedString = _mod11174.isParameterizedString;
export const isPlainObject = _mod11174.isPlainObject;
export const isPrimitive = _mod11174.isPrimitive;
export const isRegExp = _mod11174.isRegExp;
export const isString = _mod11174.isString;
export const isSyntheticEvent = _mod11174.isSyntheticEvent;
export const isThenable = _mod11174.isThenable;
export const isVueViewModel = _mod11174.isVueViewModel;
export const isBrowser = _mod11280.isBrowser;
export const CONSOLE_LEVELS = _mod11167.CONSOLE_LEVELS;
export const consoleSandbox = _mod11167.consoleSandbox;
export const logger = _mod11167.logger;
export const originalConsoleMethods = _mod11167.originalConsoleMethods;
export const memoBuilder = memoBuilder.memoBuilder;
export const addContextToFrame = _mod11178.addContextToFrame;
export const addExceptionMechanism = _mod11178.addExceptionMechanism;
export const addExceptionTypeValue = _mod11178.addExceptionTypeValue;
export const arrayify = _mod11178.arrayify;
export const checkOrSetAlreadyCaught = _mod11178.checkOrSetAlreadyCaught;
export const getEventDescription = _mod11178.getEventDescription;
export const parseSemver = _mod11178.parseSemver;
export const uuid4 = _mod11178.uuid4;
export const dynamicRequire = _mod11281.dynamicRequire;
export const isNodeEnv = _mod11281.isNodeEnv;
export const loadModule = _mod11281.loadModule;
export const normalize = _mod11212.normalize;
export const normalizeToSize = _mod11212.normalizeToSize;
export const normalizeUrlToBase = _mod11212.normalizeUrlToBase;
export const addNonEnumerableProperty = _mod11173.addNonEnumerableProperty;
export const convertToPlainObject = _mod11173.convertToPlainObject;
export const dropUndefinedKeys = _mod11173.dropUndefinedKeys;
export const extractExceptionKeysForMessage = _mod11173.extractExceptionKeysForMessage;
export const fill = _mod11173.fill;
export const getOriginalFunction = _mod11173.getOriginalFunction;
export const markFunctionWrapped = _mod11173.markFunctionWrapped;
export const objectify = _mod11173.objectify;
export const urlEncode = _mod11173.urlEncode;
export const basename = _mod11259.basename;
export const dirname = _mod11259.dirname;
export const isAbsolute = _mod11259.isAbsolute;
export const join = _mod11259.join;
export const normalizePath = _mod11259.normalizePath;
export const relative = _mod11259.relative;
export const resolve = _mod11259.resolve;
export const makePromiseBuffer = _mod11231.makePromiseBuffer;
export const DEFAULT_USER_INCLUDES = extractRequestData.DEFAULT_USER_INCLUDES;
export const addNormalizedRequestDataToEvent = extractRequestData.addNormalizedRequestDataToEvent;
export const addRequestDataToEvent = extractRequestData.addRequestDataToEvent;
export const extractPathForTransaction = extractRequestData.extractPathForTransaction;
export const extractQueryParamsFromUrl = extractRequestData.extractQueryParamsFromUrl;
export const extractRequestData = extractRequestData.extractRequestData;
export const headersToDict = extractRequestData.headersToDict;
export const httpRequestToRequestData = extractRequestData.httpRequestToRequestData;
export const winterCGHeadersToDict = extractRequestData.winterCGHeadersToDict;
export const winterCGRequestToRequestData = extractRequestData.winterCGRequestToRequestData;
export const severityLevelFromString = _mod11254.severityLevelFromString;
export const validSeverityLevels = _mod11254.validSeverityLevels;
export const UNKNOWN_FUNCTION = stackParserFromStackParserOptions.UNKNOWN_FUNCTION;
export const createStackParser = stackParserFromStackParserOptions.createStackParser;
export const getFramesFromEvent = stackParserFromStackParserOptions.getFramesFromEvent;
export const getFunctionName = stackParserFromStackParserOptions.getFunctionName;
export const stackParserFromStackParserOptions = stackParserFromStackParserOptions.stackParserFromStackParserOptions;
export const stripSentryFramesAndReverse = stackParserFromStackParserOptions.stripSentryFramesAndReverse;
export const filenameIsInApp = _mod11283.filenameIsInApp;
export const node = _mod11283.node;
export const nodeStackLineParser = _mod11283.nodeStackLineParser;
export const isMatchingPattern = _mod11176.isMatchingPattern;
export const safeJoin = _mod11176.safeJoin;
export const snipLine = _mod11176.snipLine;
export const stringMatchesSomePattern = _mod11176.stringMatchesSomePattern;
export const truncate = _mod11176.truncate;
export const isNativeFunction = supportsFetch.isNativeFunction;
export const supportsDOMError = supportsFetch.supportsDOMError;
export const supportsDOMException = supportsFetch.supportsDOMException;
export const supportsErrorEvent = supportsFetch.supportsErrorEvent;
export const supportsFetch = supportsFetch.supportsFetch;
export const supportsNativeFetch = supportsFetch.supportsNativeFetch;
export const supportsReferrerPolicy = supportsFetch.supportsReferrerPolicy;
export const supportsReportingObserver = supportsFetch.supportsReportingObserver;
export const SyncPromise = _mod11191.SyncPromise;
export const rejectedSyncPromise = _mod11191.rejectedSyncPromise;
export const resolvedSyncPromise = _mod11191.resolvedSyncPromise;
export const _browserPerformanceTimeOriginMode = require("11181__.js")._browserPerformanceTimeOriginMode;
export const browserPerformanceTimeOrigin = require("11181__.js").browserPerformanceTimeOrigin;
export const dateTimestampInSeconds = require("11181__.js").dateTimestampInSeconds;
export const timestampInSeconds = require("11181__.js").timestampInSeconds;
export const TRACEPARENT_REGEXP = _mod11179.TRACEPARENT_REGEXP;
export const extractTraceparentData = _mod11179.extractTraceparentData;
export const generateSentryTraceHeader = _mod11179.generateSentryTraceHeader;
export const propagationContextFromHeaders = _mod11179.propagationContextFromHeaders;
export const getSDKSource = _mod11282.getSDKSource;
export const isBrowserBundle = _mod11282.isBrowserBundle;
export const addItemToEnvelope = _mod11211.addItemToEnvelope;
export const createAttachmentEnvelopeItem = _mod11211.createAttachmentEnvelopeItem;
export const createEnvelope = _mod11211.createEnvelope;
export const createEventEnvelopeHeaders = _mod11211.createEventEnvelopeHeaders;
export const createSpanEnvelopeItem = _mod11211.createSpanEnvelopeItem;
export const envelopeContainsItemType = _mod11211.envelopeContainsItemType;
export const envelopeItemTypeToDataCategory = _mod11211.envelopeItemTypeToDataCategory;
export const forEachEnvelopeItem = _mod11211.forEachEnvelopeItem;
export const getSdkMetadataForEnvelopeHeader = _mod11211.getSdkMetadataForEnvelopeHeader;
export const parseEnvelope = _mod11211.parseEnvelope;
export const serializeEnvelope = _mod11211.serializeEnvelope;
export const createClientReportEnvelope = _mod11225.createClientReportEnvelope;
export const DEFAULT_RETRY_AFTER = _mod11232.DEFAULT_RETRY_AFTER;
export const disabledUntil = _mod11232.disabledUntil;
export const isRateLimited = _mod11232.isRateLimited;
export const parseRetryAfterHeader = _mod11232.parseRetryAfterHeader;
export const updateRateLimits = _mod11232.updateRateLimits;
export const BAGGAGE_HEADER_NAME = BAGGAGE_HEADER_NAME.BAGGAGE_HEADER_NAME;
export const MAX_BAGGAGE_STRING_LENGTH = BAGGAGE_HEADER_NAME.MAX_BAGGAGE_STRING_LENGTH;
export const SENTRY_BAGGAGE_KEY_PREFIX = BAGGAGE_HEADER_NAME.SENTRY_BAGGAGE_KEY_PREFIX;
export const SENTRY_BAGGAGE_KEY_PREFIX_REGEX = BAGGAGE_HEADER_NAME.SENTRY_BAGGAGE_KEY_PREFIX_REGEX;
export const baggageHeaderToDynamicSamplingContext = BAGGAGE_HEADER_NAME.baggageHeaderToDynamicSamplingContext;
export const dynamicSamplingContextToSentryBaggageHeader =
  BAGGAGE_HEADER_NAME.dynamicSamplingContextToSentryBaggageHeader;
export const parseBaggageHeader = BAGGAGE_HEADER_NAME.parseBaggageHeader;
export const getNumberOfUrlSegments = stripUrlQueryAndFragment.getNumberOfUrlSegments;
export const getSanitizedUrlString = stripUrlQueryAndFragment.getSanitizedUrlString;
export const parseUrl = stripUrlQueryAndFragment.parseUrl;
export const stripUrlQueryAndFragment = stripUrlQueryAndFragment.stripUrlQueryAndFragment;
export const makeFifoCache = _mod11284.makeFifoCache;
export const eventFromMessage = eventFromMessage.eventFromMessage;
export const eventFromUnknownInput = eventFromMessage.eventFromUnknownInput;
export const exceptionFromError = eventFromMessage.exceptionFromError;
export const parseStackFrames = eventFromMessage.parseStackFrames;
export const callFrameToStackFrame = _mod11285.callFrameToStackFrame;
export const watchdogTimer = _mod11285.watchdogTimer;
export const LRUMap = _mod11286.LRUMap;
export const generatePropagationContext = generatePropagationContext.generatePropagationContext;
export const generateSpanId = generatePropagationContext.generateSpanId;
export const generateTraceId = generatePropagationContext.generateTraceId;
export const vercelWaitUntil = _mod11287.vercelWaitUntil;
export const SDK_VERSION = _mod11169.SDK_VERSION;
export const getDebugImagesForResources = _mod11219.getDebugImagesForResources;
export const getFilenameToDebugIdMap = _mod11219.getFilenameToDebugIdMap;
export const escapeStringForRegex = _mod11288.escapeStringForRegex;
export const supportsHistory = supportsHistory.supportsHistory;
export const _asyncNullishCoalesce = _asyncNullishCoalesce2._asyncNullishCoalesce;
export const _asyncOptionalChain = _asyncOptionalChain2._asyncOptionalChain;
export const _asyncOptionalChainDelete = _asyncOptionalChainDelete2._asyncOptionalChainDelete;
export const _nullishCoalesce = _nullishCoalesce._nullishCoalesce;
export const _optionalChain = _optionalChain._optionalChain;
export const _optionalChainDelete = _optionalChainDelete._optionalChainDelete;
