// === Module 11203: ? ===

// Module 11203
import errorCallback from "errorCallback" /* 11204 */;
import _mod11205 from "module_11205" /* 11205 */;
import _mod11206 from "module_11206" /* 11206 */;
import _mod11208 from "module_11208" /* 11208 */;
import _mod11209 from "module_11209" /* 11209 */;
import _mod11210 from "module_11210" /* 11210 */;
import stackParserFromStackParserOptions from "stackParserFromStackParserOptions" /* 11211 */;
import _mod11212 from "module_11212" /* 11212 */;
import spanTimeInputToSeconds from "spanTimeInputToSeconds" /* 11213 */;
import _mod11214 from "module_11214" /* 11214 */;
import _mod11215 from "module_11215" /* 11215 */;
import _mod11216 from "module_11216" /* 11216 */;
import _mod11217 from "module_11217" /* 11217 */;
import generatePropagationContext from "generatePropagationContext" /* 11218 */;
import _mod11219 from "module_11219" /* 11219 */;
import _mod11220 from "module_11220" /* 11220 */;
import BAGGAGE_HEADER_NAME from "BAGGAGE_HEADER_NAME" /* 11221 */;
import _mod11223 from "module_11223" /* 11223 */;
import _mod11224 from "module_11224" /* 11224 */;
import _mod11225 from "module_11225" /* 11225 */;
import _mod11226 from "module_11226" /* 11226 */;
import _mod11227 from "module_11227" /* 11227 */;
import ScopeClass from "ScopeClass" /* 11229 */;
import _mod11231 from "module_11231" /* 11231 */;
import _mod11232 from "module_11232" /* 11232 */;
import _mod11234 from "module_11234" /* 11234 */;
import _mod11235 from "module_11235" /* 11235 */;
import _mod11237 from "module_11237" /* 11237 */;
import _mod11238 from "module_11238" /* 11238 */;
import _mod11239 from "module_11239" /* 11239 */;
import _mod11240 from "module_11240" /* 11240 */;
import _mod11241 from "module_11241" /* 11241 */;
import _mod11242 from "module_11242" /* 11242 */;
import _mod11243 from "module_11243" /* 11243 */;
import _mod11244 from "module_11244" /* 11244 */;
import _mod11245 from "module_11245" /* 11245 */;
import _mod11246 from "module_11246" /* 11246 */;
import _mod11247 from "module_11247" /* 11247 */;
import _mod11248 from "module_11248" /* 11248 */;
import _mod11249 from "module_11249" /* 11249 */;
import _mod11250 from "module_11250" /* 11250 */;
import _mod11251 from "module_11251" /* 11251 */;
import _mod11252 from "module_11252" /* 11252 */;
import _mod11253 from "module_11253" /* 11253 */;
import memoBuilder from "memoBuilder" /* 11254 */;
import _mod11255 from "module_11255" /* 11255 */;
import _flush from "_flush" /* 11256 */;
import _mod11257 from "module_11257" /* 11257 */;
import applyScopeDataToEvent from "applyScopeDataToEvent" /* 11258 */;
import notifyEventProcessors from "notifyEventProcessors" /* 11259 */;
import _mod11260 from "module_11260" /* 11260 */;
import SessionFlusher from "SessionFlusher" /* 11261 */;
import _mod11262 from "module_11262" /* 11262 */;
import _mod11263 from "module_11263" /* 11263 */;
import _mod11264 from "module_11264" /* 11264 */;
import _mod11265 from "module_11265" /* 11265 */;
import _mod11266 from "module_11266" /* 11266 */;
import _mod11267 from "module_11267" /* 11267 */;
import eventFromMessage from "eventFromMessage" /* 11268 */;
import _mod11269 from "module_11269" /* 11269 */;
import _mod11270 from "module_11270" /* 11270 */;
import _mod11271 from "module_11271" /* 11271 */;
import _mod11272 from "module_11272" /* 11272 */;
import _mod11273 from "module_11273" /* 11273 */;
import _mod11274 from "module_11274" /* 11274 */;
import _mod11275 from "module_11275" /* 11275 */;
import _mod11276 from "module_11276" /* 11276 */;
import _mod11277 from "module_11277" /* 11277 */;
import _mod11278 from "module_11278" /* 11278 */;
import _mod11279 from "module_11279" /* 11279 */;
import _mod11280 from "module_11280" /* 11280 */;
import _mod11281 from "module_11281" /* 11281 */;
import _mod11282 from "module_11282" /* 11282 */;
import _getEventFilterUrl from "_getEventFilterUrl" /* 11283 */;
import _mod11284 from "module_11284" /* 11284 */;
import _mod11285 from "module_11285" /* 11285 */;
import _mod11286 from "module_11286" /* 11286 */;
import _mod11288 from "module_11288" /* 11288 */;
import extractRequestData from "extractRequestData" /* 11289 */;
import stripUrlQueryAndFragment from "stripUrlQueryAndFragment" /* 11290 */;
import _mod11293 from "module_11293" /* 11293 */;
import _mod11294 from "module_11294" /* 11294 */;
import _mod11295 from "module_11295" /* 11295 */;
import debugIntegration from "debugIntegration" /* 11296 */;
import _mod11297 from "module_11297" /* 11297 */;
import extraErrorDataIntegration from "extraErrorDataIntegration" /* 11298 */;
import _mod11299 from "module_11299" /* 11299 */;
import _mod11300 from "module_11300" /* 11300 */;
import sessionTimingIntegration from "sessionTimingIntegration" /* 11301 */;
import _mod11302 from "module_11302" /* 11302 */;
import _mod11303 from "module_11303" /* 11303 */;
import _mod11304 from "module_11304" /* 11304 */;
import _mod11306 from "module_11306" /* 11306 */;
import metricsDefault from "metricsDefault" /* 11307 */;
import BrowserMetricsAggregator from "BrowserMetricsAggregator" /* 11312 */;
import _mod11313 from "module_11313" /* 11313 */;
import _mod11314 from "module_11314" /* 11314 */;
import _mod11315 from "module_11315" /* 11315 */;
import _mod11316 from "module_11316" /* 11316 */;
import _mod11317 from "module_11317" /* 11317 */;
import _mod11318 from "module_11318" /* 11318 */;
import _mod11319 from "module_11319" /* 11319 */;
import supportsFetch from "supportsFetch" /* 11320 */;
import _mod11321 from "module_11321" /* 11321 */;
import _mod11322 from "module_11322" /* 11322 */;
import _mod11323 from "module_11323" /* 11323 */;
import _mod11324 from "module_11324" /* 11324 */;
import _mod11325 from "module_11325" /* 11325 */;
import _mod11326 from "module_11326" /* 11326 */;
import _mod11327 from "module_11327" /* 11327 */;
import _mod11328 from "module_11328" /* 11328 */;
import _mod11329 from "module_11329" /* 11329 */;
import supportsHistory from "supportsHistory" /* 11330 */;
import _asyncNullishCoalesce2 from "_asyncNullishCoalesce2" /* 11331 */;
import _nullishCoalesce from "_nullishCoalesce" /* 11332 */;
import _asyncOptionalChain2 from "_asyncOptionalChain2" /* 11333 */;
import _asyncOptionalChainDelete2 from "_asyncOptionalChainDelete2" /* 11334 */;
import _optionalChain from "_optionalChain" /* 11335 */;
import _optionalChainDelete from "_optionalChainDelete" /* 11336 */;

const require = globalThis.__r;


export const registerSpanErrorInstrumentation = errorCallback.registerSpanErrorInstrumentation;
export const getCapturedScopesOnSpan = _mod11237.getCapturedScopesOnSpan;
export const setCapturedScopesOnSpan = _mod11237.setCapturedScopesOnSpan;
export const addTracingExtensions = _mod11238.addTracingExtensions;
export const TRACING_DEFAULTS = _mod11239.TRACING_DEFAULTS;
export const startIdleSpan = _mod11239.startIdleSpan;
export const SentrySpan = _mod11249.SentrySpan;
export const SentryNonRecordingSpan = _mod11241.SentryNonRecordingSpan;
export const SPAN_STATUS_ERROR = _mod11225.SPAN_STATUS_ERROR;
export const SPAN_STATUS_OK = _mod11225.SPAN_STATUS_OK;
export const SPAN_STATUS_UNSET = _mod11225.SPAN_STATUS_UNSET;
export const getSpanStatusFromHttpCode = _mod11225.getSpanStatusFromHttpCode;
export const setHttpStatus = _mod11225.setHttpStatus;
export const continueTrace = _mod11242.continueTrace;
export const startInactiveSpan = _mod11242.startInactiveSpan;
export const startNewTrace = _mod11242.startNewTrace;
export const startSpan = _mod11242.startSpan;
export const startSpanManual = _mod11242.startSpanManual;
export const suppressTracing = _mod11242.suppressTracing;
export const withActiveSpan = _mod11242.withActiveSpan;
export const getDynamicSamplingContextFromClient = _mod11244.getDynamicSamplingContextFromClient;
export const getDynamicSamplingContextFromScope = _mod11244.getDynamicSamplingContextFromScope;
export const getDynamicSamplingContextFromSpan = _mod11244.getDynamicSamplingContextFromSpan;
export const spanToBaggageHeader = _mod11244.spanToBaggageHeader;
export const setMeasurement = _mod11250.setMeasurement;
export const timedEventsToMeasurements = _mod11250.timedEventsToMeasurements;
export const sampleSpan = _mod11247.sampleSpan;
export const logSpanEnd = _mod11246.logSpanEnd;
export const logSpanStart = _mod11246.logSpanStart;
export const SEMANTIC_ATTRIBUTE_CACHE_HIT = _mod11223.SEMANTIC_ATTRIBUTE_CACHE_HIT;
export const SEMANTIC_ATTRIBUTE_CACHE_ITEM_SIZE = _mod11223.SEMANTIC_ATTRIBUTE_CACHE_ITEM_SIZE;
export const SEMANTIC_ATTRIBUTE_CACHE_KEY = _mod11223.SEMANTIC_ATTRIBUTE_CACHE_KEY;
export const SEMANTIC_ATTRIBUTE_EXCLUSIVE_TIME = _mod11223.SEMANTIC_ATTRIBUTE_EXCLUSIVE_TIME;
export const SEMANTIC_ATTRIBUTE_HTTP_REQUEST_METHOD = _mod11223.SEMANTIC_ATTRIBUTE_HTTP_REQUEST_METHOD;
export const SEMANTIC_ATTRIBUTE_PROFILE_ID = _mod11223.SEMANTIC_ATTRIBUTE_PROFILE_ID;
export const SEMANTIC_ATTRIBUTE_SENTRY_CUSTOM_SPAN_NAME = _mod11223.SEMANTIC_ATTRIBUTE_SENTRY_CUSTOM_SPAN_NAME;
export const SEMANTIC_ATTRIBUTE_SENTRY_IDLE_SPAN_FINISH_REASON = _mod11223.SEMANTIC_ATTRIBUTE_SENTRY_IDLE_SPAN_FINISH_REASON;
export const SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_UNIT = _mod11223.SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_UNIT;
export const SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_VALUE = _mod11223.SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_VALUE;
export const SEMANTIC_ATTRIBUTE_SENTRY_OP = _mod11223.SEMANTIC_ATTRIBUTE_SENTRY_OP;
export const SEMANTIC_ATTRIBUTE_SENTRY_ORIGIN = _mod11223.SEMANTIC_ATTRIBUTE_SENTRY_ORIGIN;
export const SEMANTIC_ATTRIBUTE_SENTRY_SAMPLE_RATE = _mod11223.SEMANTIC_ATTRIBUTE_SENTRY_SAMPLE_RATE;
export const SEMANTIC_ATTRIBUTE_SENTRY_SOURCE = _mod11223.SEMANTIC_ATTRIBUTE_SENTRY_SOURCE;
export const SEMANTIC_ATTRIBUTE_URL_FULL = _mod11223.SEMANTIC_ATTRIBUTE_URL_FULL;
export const createEventEnvelope = _mod11251.createEventEnvelope;
export const createSessionEnvelope = _mod11251.createSessionEnvelope;
export const createSpanEnvelope = _mod11251.createSpanEnvelope;
export const addEventProcessor = _flush.addEventProcessor;
export const captureCheckIn = _flush.captureCheckIn;
export const captureEvent = _flush.captureEvent;
export const captureException = _flush.captureException;
export const captureMessage = _flush.captureMessage;
export const captureSession = _flush.captureSession;
export const close = _flush.close;
export const endSession = _flush.endSession;
export const flush = _flush.flush;
export const isEnabled = _flush.isEnabled;
export const isInitialized = _flush.isInitialized;
export const lastEventId = _flush.lastEventId;
export const setContext = _flush.setContext;
export const setExtra = _flush.setExtra;
export const setExtras = _flush.setExtras;
export const setTag = _flush.setTag;
export const setTags = _flush.setTags;
export const setUser = _flush.setUser;
export const startSession = _flush.startSession;
export const withMonitor = _flush.withMonitor;
export const getClient = _mod11235.getClient;
export const getCurrentScope = _mod11235.getCurrentScope;
export const getGlobalScope = _mod11235.getGlobalScope;
export const getIsolationScope = _mod11235.getIsolationScope;
export const getTraceContextFromScope = _mod11235.getTraceContextFromScope;
export const withIsolationScope = _mod11235.withIsolationScope;
export const withScope = _mod11235.withScope;
export const getDefaultCurrentScope = _mod11234.getDefaultCurrentScope;
export const getDefaultIsolationScope = _mod11234.getDefaultIsolationScope;
export const setAsyncContextStrategy = _mod11227.setAsyncContextStrategy;
export const getMainCarrier = _mod11226.getMainCarrier;
export const closeSession = _mod11231.closeSession;
export const makeSession = _mod11231.makeSession;
export const updateSession = _mod11231.updateSession;
export const SessionFlusher = SessionFlusher.SessionFlusher;
export const Scope = ScopeClass.Scope;
export const notifyEventProcessors = notifyEventProcessors.notifyEventProcessors;
export const getEnvelopeEndpointWithUrlEncodedAuth = _mod11262.getEnvelopeEndpointWithUrlEncodedAuth;
export const getReportDialogEndpoint = _mod11262.getReportDialogEndpoint;
export const BaseClient = _mod11263.BaseClient;
export const ServerRuntimeClient = _mod11267.ServerRuntimeClient;
export const initAndBind = _mod11270.initAndBind;
export const setCurrentClient = _mod11270.setCurrentClient;
export const createTransport = _mod11271.createTransport;
export const makeOfflineTransport = _mod11274.makeOfflineTransport;
export const makeMultiplexedTransport = _mod11275.makeMultiplexedTransport;
export const addIntegration = _mod11264.addIntegration;
export const defineIntegration = _mod11264.defineIntegration;
export const getIntegrationsToSetup = _mod11264.getIntegrationsToSetup;
export const applyScopeDataToEvent = applyScopeDataToEvent.applyScopeDataToEvent;
export const mergeScopeData = applyScopeDataToEvent.mergeScopeData;
export const prepareEvent = _mod11257.prepareEvent;
export const createCheckInEnvelope = _mod11269.createCheckInEnvelope;
export const hasTracingEnabled = _mod11240.hasTracingEnabled;
export const isSentryRequestUrl = _mod11276.isSentryRequestUrl;
export const handleCallbackErrors = _mod11243.handleCallbackErrors;
export const parameterize = _mod11277.parameterize;
export const addChildSpanToSpan = spanTimeInputToSeconds.addChildSpanToSpan;
export const getActiveSpan = spanTimeInputToSeconds.getActiveSpan;
export const getRootSpan = spanTimeInputToSeconds.getRootSpan;
export const getSpanDescendants = spanTimeInputToSeconds.getSpanDescendants;
export const getStatusMessage = spanTimeInputToSeconds.getStatusMessage;
export const spanIsSampled = spanTimeInputToSeconds.spanIsSampled;
export const spanTimeInputToSeconds = spanTimeInputToSeconds.spanTimeInputToSeconds;
export const spanToJSON = spanTimeInputToSeconds.spanToJSON;
export const spanToTraceContext = spanTimeInputToSeconds.spanToTraceContext;
export const spanToTraceHeader = spanTimeInputToSeconds.spanToTraceHeader;
export const updateSpanName = spanTimeInputToSeconds.updateSpanName;
export const parseSampleRate = _mod11248.parseSampleRate;
export const applySdkMetadata = _mod11278.applySdkMetadata;
export const getTraceData = _mod11279.getTraceData;
export const getTraceMetaTags = _mod11280.getTraceMetaTags;
export const DEFAULT_ENVIRONMENT = _mod11245.DEFAULT_ENVIRONMENT;
export const addBreadcrumb = _mod11281.addBreadcrumb;
export const functionToStringIntegration = _mod11282.functionToStringIntegration;
export const inboundFiltersIntegration = _getEventFilterUrl.inboundFiltersIntegration;
export const linkedErrorsIntegration = _mod11284.linkedErrorsIntegration;
export const moduleMetadataIntegration = _mod11286.moduleMetadataIntegration;
export const requestDataIntegration = _mod11288.requestDataIntegration;
export const captureConsoleIntegration = _mod11293.captureConsoleIntegration;
export const debugIntegration = debugIntegration.debugIntegration;
export const dedupeIntegration = _mod11297.dedupeIntegration;
export const extraErrorDataIntegration = extraErrorDataIntegration.extraErrorDataIntegration;
export const rewriteFramesIntegration = _mod11299.rewriteFramesIntegration;
export const sessionTimingIntegration = sessionTimingIntegration.sessionTimingIntegration;
export const zodErrorsIntegration = _mod11302.zodErrorsIntegration;
export const thirdPartyErrorFilterIntegration = _mod11303.thirdPartyErrorFilterIntegration;
export const metrics = _mod11304.metrics;
export const profiler = _mod11306.profiler;
export const metricsDefault = metricsDefault.metricsDefault;
export const BrowserMetricsAggregator = BrowserMetricsAggregator.BrowserMetricsAggregator;
export const getMetricSummaryJsonForSpan = _mod11224.getMetricSummaryJsonForSpan;
export const addTracingHeadersToFetchRequest = _mod11313.addTracingHeadersToFetchRequest;
export const instrumentFetchRequest = _mod11313.instrumentFetchRequest;
export const trpcMiddleware = _mod11314.trpcMiddleware;
export const captureFeedback = _mod11315.captureFeedback;
export const getCurrentHub = _mod11316.getCurrentHub;
export const getCurrentHubShim = _mod11316.getCurrentHubShim;
export const applyAggregateErrorsToEvent = _mod11285.applyAggregateErrorsToEvent;
export const flatten = _mod11317.flatten;
export const getBreadcrumbLogLevelFromHttpStatusCode = _mod11318.getBreadcrumbLogLevelFromHttpStatusCode;
export const getComponentName = _mod11216.getComponentName;
export const getDomElement = _mod11216.getDomElement;
export const getLocationHref = _mod11216.getLocationHref;
export const htmlTreeAsString = _mod11216.htmlTreeAsString;
export const dsnFromString = _mod11255.dsnFromString;
export const dsnToString = _mod11255.dsnToString;
export const makeDsn = _mod11255.makeDsn;
export const SentryError = _mod11265.SentryError;
export const GLOBAL_OBJ = _mod11209.GLOBAL_OBJ;
export const getGlobalSingleton = _mod11209.getGlobalSingleton;
export const addConsoleInstrumentationHandler = _mod11294.addConsoleInstrumentationHandler;
export const addFetchEndInstrumentationHandler = _mod11319.addFetchEndInstrumentationHandler;
export const addFetchInstrumentationHandler = _mod11319.addFetchInstrumentationHandler;
export const addGlobalErrorInstrumentationHandler = _mod11205.addGlobalErrorInstrumentationHandler;
export const addGlobalUnhandledRejectionInstrumentationHandler = _mod11212.addGlobalUnhandledRejectionInstrumentationHandler;
export const addHandler = _mod11206.addHandler;
export const maybeInstrument = _mod11206.maybeInstrument;
export const resetInstrumentationHandlers = _mod11206.resetInstrumentationHandlers;
export const triggerHandlers = _mod11206.triggerHandlers;
export const isDOMError = _mod11215.isDOMError;
export const isDOMException = _mod11215.isDOMException;
export const isElement = _mod11215.isElement;
export const isError = _mod11215.isError;
export const isErrorEvent = _mod11215.isErrorEvent;
export const isEvent = _mod11215.isEvent;
export const isInstanceOf = _mod11215.isInstanceOf;
export const isParameterizedString = _mod11215.isParameterizedString;
export const isPlainObject = _mod11215.isPlainObject;
export const isPrimitive = _mod11215.isPrimitive;
export const isRegExp = _mod11215.isRegExp;
export const isString = _mod11215.isString;
export const isSyntheticEvent = _mod11215.isSyntheticEvent;
export const isThenable = _mod11215.isThenable;
export const isVueViewModel = _mod11215.isVueViewModel;
export const isBrowser = _mod11321.isBrowser;
export const CONSOLE_LEVELS = _mod11208.CONSOLE_LEVELS;
export const consoleSandbox = _mod11208.consoleSandbox;
export const logger = _mod11208.logger;
export const originalConsoleMethods = _mod11208.originalConsoleMethods;
export const memoBuilder = memoBuilder.memoBuilder;
export const addContextToFrame = _mod11219.addContextToFrame;
export const addExceptionMechanism = _mod11219.addExceptionMechanism;
export const addExceptionTypeValue = _mod11219.addExceptionTypeValue;
export const arrayify = _mod11219.arrayify;
export const checkOrSetAlreadyCaught = _mod11219.checkOrSetAlreadyCaught;
export const getEventDescription = _mod11219.getEventDescription;
export const parseSemver = _mod11219.parseSemver;
export const uuid4 = _mod11219.uuid4;
export const dynamicRequire = _mod11322.dynamicRequire;
export const isNodeEnv = _mod11322.isNodeEnv;
export const loadModule = _mod11322.loadModule;
export const normalize = _mod11253.normalize;
export const normalizeToSize = _mod11253.normalizeToSize;
export const normalizeUrlToBase = _mod11253.normalizeUrlToBase;
export const addNonEnumerableProperty = _mod11214.addNonEnumerableProperty;
export const convertToPlainObject = _mod11214.convertToPlainObject;
export const dropUndefinedKeys = _mod11214.dropUndefinedKeys;
export const extractExceptionKeysForMessage = _mod11214.extractExceptionKeysForMessage;
export const fill = _mod11214.fill;
export const getOriginalFunction = _mod11214.getOriginalFunction;
export const markFunctionWrapped = _mod11214.markFunctionWrapped;
export const objectify = _mod11214.objectify;
export const urlEncode = _mod11214.urlEncode;
export const basename = _mod11300.basename;
export const dirname = _mod11300.dirname;
export const isAbsolute = _mod11300.isAbsolute;
export const join = _mod11300.join;
export const normalizePath = _mod11300.normalizePath;
export const relative = _mod11300.relative;
export const resolve = _mod11300.resolve;
export const makePromiseBuffer = _mod11272.makePromiseBuffer;
export const DEFAULT_USER_INCLUDES = extractRequestData.DEFAULT_USER_INCLUDES;
export const addNormalizedRequestDataToEvent = extractRequestData.addNormalizedRequestDataToEvent;
export const addRequestDataToEvent = extractRequestData.addRequestDataToEvent;
export const extractPathForTransaction = extractRequestData.extractPathForTransaction;
export const extractQueryParamsFromUrl = extractRequestData.extractQueryParamsFromUrl;
export const extractRequestData = extractRequestData.extractRequestData;
export const headersToDict = extractRequestData.headersToDict;
export const httpRequestToRequestData = extractRequestData.httpRequestToRequestData;
export const winterCGHeadersToDict = extractRequestData.winterCGHeadersToDict;
export const winterCGRequestToRequestData = extractRequestData.winterCGRequestToRequestData;
export const severityLevelFromString = _mod11295.severityLevelFromString;
export const validSeverityLevels = _mod11295.validSeverityLevels;
export const UNKNOWN_FUNCTION = stackParserFromStackParserOptions.UNKNOWN_FUNCTION;
export const createStackParser = stackParserFromStackParserOptions.createStackParser;
export const getFramesFromEvent = stackParserFromStackParserOptions.getFramesFromEvent;
export const getFunctionName = stackParserFromStackParserOptions.getFunctionName;
export const stackParserFromStackParserOptions = stackParserFromStackParserOptions.stackParserFromStackParserOptions;
export const stripSentryFramesAndReverse = stackParserFromStackParserOptions.stripSentryFramesAndReverse;
export const filenameIsInApp = _mod11324.filenameIsInApp;
export const node = _mod11324.node;
export const nodeStackLineParser = _mod11324.nodeStackLineParser;
export const isMatchingPattern = _mod11217.isMatchingPattern;
export const safeJoin = _mod11217.safeJoin;
export const snipLine = _mod11217.snipLine;
export const stringMatchesSomePattern = _mod11217.stringMatchesSomePattern;
export const truncate = _mod11217.truncate;
export const isNativeFunction = supportsFetch.isNativeFunction;
export const supportsDOMError = supportsFetch.supportsDOMError;
export const supportsDOMException = supportsFetch.supportsDOMException;
export const supportsErrorEvent = supportsFetch.supportsErrorEvent;
export const supportsFetch = supportsFetch.supportsFetch;
export const supportsNativeFetch = supportsFetch.supportsNativeFetch;
export const supportsReferrerPolicy = supportsFetch.supportsReferrerPolicy;
export const supportsReportingObserver = supportsFetch.supportsReportingObserver;
export const SyncPromise = _mod11232.SyncPromise;
export const rejectedSyncPromise = _mod11232.rejectedSyncPromise;
export const resolvedSyncPromise = _mod11232.resolvedSyncPromise;
export const _browserPerformanceTimeOriginMode = require("module_11222")._browserPerformanceTimeOriginMode;
export const browserPerformanceTimeOrigin = require("module_11222").browserPerformanceTimeOrigin;
export const dateTimestampInSeconds = require("module_11222").dateTimestampInSeconds;
export const timestampInSeconds = require("module_11222").timestampInSeconds;
export const TRACEPARENT_REGEXP = _mod11220.TRACEPARENT_REGEXP;
export const extractTraceparentData = _mod11220.extractTraceparentData;
export const generateSentryTraceHeader = _mod11220.generateSentryTraceHeader;
export const propagationContextFromHeaders = _mod11220.propagationContextFromHeaders;
export const getSDKSource = _mod11323.getSDKSource;
export const isBrowserBundle = _mod11323.isBrowserBundle;
export const addItemToEnvelope = _mod11252.addItemToEnvelope;
export const createAttachmentEnvelopeItem = _mod11252.createAttachmentEnvelopeItem;
export const createEnvelope = _mod11252.createEnvelope;
export const createEventEnvelopeHeaders = _mod11252.createEventEnvelopeHeaders;
export const createSpanEnvelopeItem = _mod11252.createSpanEnvelopeItem;
export const envelopeContainsItemType = _mod11252.envelopeContainsItemType;
export const envelopeItemTypeToDataCategory = _mod11252.envelopeItemTypeToDataCategory;
export const forEachEnvelopeItem = _mod11252.forEachEnvelopeItem;
export const getSdkMetadataForEnvelopeHeader = _mod11252.getSdkMetadataForEnvelopeHeader;
export const parseEnvelope = _mod11252.parseEnvelope;
export const serializeEnvelope = _mod11252.serializeEnvelope;
export const createClientReportEnvelope = _mod11266.createClientReportEnvelope;
export const DEFAULT_RETRY_AFTER = _mod11273.DEFAULT_RETRY_AFTER;
export const disabledUntil = _mod11273.disabledUntil;
export const isRateLimited = _mod11273.isRateLimited;
export const parseRetryAfterHeader = _mod11273.parseRetryAfterHeader;
export const updateRateLimits = _mod11273.updateRateLimits;
export const BAGGAGE_HEADER_NAME = BAGGAGE_HEADER_NAME.BAGGAGE_HEADER_NAME;
export const MAX_BAGGAGE_STRING_LENGTH = BAGGAGE_HEADER_NAME.MAX_BAGGAGE_STRING_LENGTH;
export const SENTRY_BAGGAGE_KEY_PREFIX = BAGGAGE_HEADER_NAME.SENTRY_BAGGAGE_KEY_PREFIX;
export const SENTRY_BAGGAGE_KEY_PREFIX_REGEX = BAGGAGE_HEADER_NAME.SENTRY_BAGGAGE_KEY_PREFIX_REGEX;
export const baggageHeaderToDynamicSamplingContext = BAGGAGE_HEADER_NAME.baggageHeaderToDynamicSamplingContext;
export const dynamicSamplingContextToSentryBaggageHeader = BAGGAGE_HEADER_NAME.dynamicSamplingContextToSentryBaggageHeader;
export const parseBaggageHeader = BAGGAGE_HEADER_NAME.parseBaggageHeader;
export const getNumberOfUrlSegments = stripUrlQueryAndFragment.getNumberOfUrlSegments;
export const getSanitizedUrlString = stripUrlQueryAndFragment.getSanitizedUrlString;
export const parseUrl = stripUrlQueryAndFragment.parseUrl;
export const stripUrlQueryAndFragment = stripUrlQueryAndFragment.stripUrlQueryAndFragment;
export const makeFifoCache = _mod11325.makeFifoCache;
export const eventFromMessage = eventFromMessage.eventFromMessage;
export const eventFromUnknownInput = eventFromMessage.eventFromUnknownInput;
export const exceptionFromError = eventFromMessage.exceptionFromError;
export const parseStackFrames = eventFromMessage.parseStackFrames;
export const callFrameToStackFrame = _mod11326.callFrameToStackFrame;
export const watchdogTimer = _mod11326.watchdogTimer;
export const LRUMap = _mod11327.LRUMap;
export const generatePropagationContext = generatePropagationContext.generatePropagationContext;
export const generateSpanId = generatePropagationContext.generateSpanId;
export const generateTraceId = generatePropagationContext.generateTraceId;
export const vercelWaitUntil = _mod11328.vercelWaitUntil;
export const SDK_VERSION = _mod11210.SDK_VERSION;
export const getDebugImagesForResources = _mod11260.getDebugImagesForResources;
export const getFilenameToDebugIdMap = _mod11260.getFilenameToDebugIdMap;
export const escapeStringForRegex = _mod11329.escapeStringForRegex;
export const supportsHistory = supportsHistory.supportsHistory;
export const _asyncNullishCoalesce = _asyncNullishCoalesce2._asyncNullishCoalesce;
export const _asyncOptionalChain = _asyncOptionalChain2._asyncOptionalChain;
export const _asyncOptionalChainDelete = _asyncOptionalChainDelete2._asyncOptionalChainDelete;
export const _nullishCoalesce = _nullishCoalesce._nullishCoalesce;
export const _optionalChain = _optionalChain._optionalChain;
export const _optionalChainDelete = _optionalChainDelete._optionalChainDelete;