// _runtime/metro/12290__.js
import errorCallback from "../12291_errorCallback.js";
import _mod12292 from "12292__.js";
import _mod12293 from "12293__.js";
import _mod12295 from "12295__.js";
import _mod12296 from "12296__.js";
import _mod12297 from "12297__.js";
import stackParserFromStackParserOptions from "../12298_stackParserFromStackParserOptions.js";
import _mod12299 from "12299__.js";
import spanTimeInputToSeconds from "../12300_spanTimeInputToSeconds.js";
import _mod12301 from "12301__.js";
import _mod12302 from "12302__.js";
import _mod12303 from "12303__.js";
import _mod12304 from "12304__.js";
import generatePropagationContext from "../12305_generatePropagationContext.js";
import _mod12306 from "12306__.js";
import _mod12307 from "12307__.js";
import BAGGAGE_HEADER_NAME from "../12308_BAGGAGE_HEADER_NAME.js";
import _mod12310 from "12310__.js";
import _mod12311 from "12311__.js";
import _mod12312 from "12312__.js";
import _mod12313 from "12313__.js";
import _mod12314 from "12314__.js";
import ScopeClass from "../12316_ScopeClass.js";
import _mod12318 from "12318__.js";
import _mod12319 from "12319__.js";
import _mod12321 from "12321__.js";
import _mod12322 from "12322__.js";
import _mod12324 from "12324__.js";
import _mod12325 from "12325__.js";
import _mod12326 from "12326__.js";
import _mod12327 from "12327__.js";
import _mod12328 from "12328__.js";
import _mod12329 from "12329__.js";
import _mod12330 from "12330__.js";
import _mod12331 from "12331__.js";
import _mod12332 from "12332__.js";
import _mod12333 from "12333__.js";
import _mod12334 from "12334__.js";
import _mod12335 from "12335__.js";
import _mod12336 from "12336__.js";
import _mod12337 from "12337__.js";
import _mod12338 from "12338__.js";
import _mod12339 from "12339__.js";
import _mod12340 from "12340__.js";
import memoBuilder from "../12341_memoBuilder.js";
import _mod12342 from "12342__.js";
import _flush from "../12343__flush.js";
import _mod12344 from "12344__.js";
import applyScopeDataToEvent from "../12345_applyScopeDataToEvent.js";
import notifyEventProcessors from "../12346_notifyEventProcessors.js";
import _mod12347 from "12347__.js";
import SessionFlusher from "../12348_SessionFlusher.js";
import _mod12349 from "12349__.js";
import _mod12350 from "12350__.js";
import _mod12351 from "12351__.js";
import _mod12352 from "12352__.js";
import _mod12353 from "12353__.js";
import _mod12354 from "12354__.js";
import eventFromMessage from "../12355_eventFromMessage.js";
import _mod12356 from "12356__.js";
import _mod12357 from "12357__.js";
import _mod12358 from "12358__.js";
import _mod12359 from "12359__.js";
import _mod12360 from "12360__.js";
import _mod12361 from "12361__.js";
import _mod12362 from "12362__.js";
import _mod12363 from "12363__.js";
import _mod12364 from "12364__.js";
import _mod12365 from "12365__.js";
import _mod12366 from "12366__.js";
import _mod12367 from "12367__.js";
import _mod12368 from "12368__.js";
import _mod12369 from "12369__.js";
import _getEventFilterUrl from "../12370__getEventFilterUrl.js";
import _mod12371 from "12371__.js";
import _mod12372 from "12372__.js";
import _mod12373 from "12373__.js";
import _mod12375 from "12375__.js";
import extractRequestData from "../12376_extractRequestData.js";
import stripUrlQueryAndFragment from "../12377_stripUrlQueryAndFragment.js";
import _mod12380 from "12380__.js";
import _mod12381 from "12381__.js";
import _mod12382 from "12382__.js";
import debugIntegration from "../12383_debugIntegration.js";
import _mod12384 from "12384__.js";
import extraErrorDataIntegration from "../12385_extraErrorDataIntegration.js";
import _mod12386 from "12386__.js";
import _mod12387 from "12387__.js";
import sessionTimingIntegration from "../12388_sessionTimingIntegration.js";
import _mod12389 from "12389__.js";
import _mod12390 from "12390__.js";
import _mod12391 from "12391__.js";
import _mod12393 from "12393__.js";
import metricsDefault from "../12394_metricsDefault.js";
import BrowserMetricsAggregator from "../12399_BrowserMetricsAggregator.js";
import _mod12400 from "12400__.js";
import _mod12401 from "12401__.js";
import _mod12402 from "12402__.js";
import _mod12403 from "12403__.js";
import _mod12404 from "12404__.js";
import _mod12405 from "12405__.js";
import _mod12406 from "12406__.js";
import supportsFetch from "../12407_supportsFetch.js";
import _mod12408 from "12408__.js";
import _mod12409 from "12409__.js";
import _mod12410 from "12410__.js";
import _mod12411 from "12411__.js";
import _mod12412 from "12412__.js";
import _mod12413 from "12413__.js";
import _mod12414 from "12414__.js";
import _mod12415 from "12415__.js";
import _mod12416 from "12416__.js";
import supportsHistory from "../12417_supportsHistory.js";
import _asyncNullishCoalesce2 from "../12418__asyncNullishCoalesce2.js";
import _nullishCoalesce from "../12419__nullishCoalesce.js";
import _asyncOptionalChain2 from "../12420__asyncOptionalChain2.js";
import _asyncOptionalChainDelete2 from "../12421__asyncOptionalChainDelete2.js";
import _optionalChain from "../12422__optionalChain.js";
import _optionalChainDelete from "../12423__optionalChainDelete.js";

const require = globalThis.__r;

export const registerSpanErrorInstrumentation = errorCallback.registerSpanErrorInstrumentation;
export const getCapturedScopesOnSpan = _mod12324.getCapturedScopesOnSpan;
export const setCapturedScopesOnSpan = _mod12324.setCapturedScopesOnSpan;
export const addTracingExtensions = _mod12325.addTracingExtensions;
export const TRACING_DEFAULTS = _mod12326.TRACING_DEFAULTS;
export const startIdleSpan = _mod12326.startIdleSpan;
export const SentrySpan = _mod12336.SentrySpan;
export const SentryNonRecordingSpan = _mod12328.SentryNonRecordingSpan;
export const SPAN_STATUS_ERROR = _mod12312.SPAN_STATUS_ERROR;
export const SPAN_STATUS_OK = _mod12312.SPAN_STATUS_OK;
export const SPAN_STATUS_UNSET = _mod12312.SPAN_STATUS_UNSET;
export const getSpanStatusFromHttpCode = _mod12312.getSpanStatusFromHttpCode;
export const setHttpStatus = _mod12312.setHttpStatus;
export const continueTrace = _mod12329.continueTrace;
export const startInactiveSpan = _mod12329.startInactiveSpan;
export const startNewTrace = _mod12329.startNewTrace;
export const startSpan = _mod12329.startSpan;
export const startSpanManual = _mod12329.startSpanManual;
export const suppressTracing = _mod12329.suppressTracing;
export const withActiveSpan = _mod12329.withActiveSpan;
export const getDynamicSamplingContextFromClient = _mod12331.getDynamicSamplingContextFromClient;
export const getDynamicSamplingContextFromScope = _mod12331.getDynamicSamplingContextFromScope;
export const getDynamicSamplingContextFromSpan = _mod12331.getDynamicSamplingContextFromSpan;
export const spanToBaggageHeader = _mod12331.spanToBaggageHeader;
export const setMeasurement = _mod12337.setMeasurement;
export const timedEventsToMeasurements = _mod12337.timedEventsToMeasurements;
export const sampleSpan = _mod12334.sampleSpan;
export const logSpanEnd = _mod12333.logSpanEnd;
export const logSpanStart = _mod12333.logSpanStart;
export const SEMANTIC_ATTRIBUTE_CACHE_HIT = _mod12310.SEMANTIC_ATTRIBUTE_CACHE_HIT;
export const SEMANTIC_ATTRIBUTE_CACHE_ITEM_SIZE = _mod12310.SEMANTIC_ATTRIBUTE_CACHE_ITEM_SIZE;
export const SEMANTIC_ATTRIBUTE_CACHE_KEY = _mod12310.SEMANTIC_ATTRIBUTE_CACHE_KEY;
export const SEMANTIC_ATTRIBUTE_EXCLUSIVE_TIME = _mod12310.SEMANTIC_ATTRIBUTE_EXCLUSIVE_TIME;
export const SEMANTIC_ATTRIBUTE_HTTP_REQUEST_METHOD = _mod12310.SEMANTIC_ATTRIBUTE_HTTP_REQUEST_METHOD;
export const SEMANTIC_ATTRIBUTE_PROFILE_ID = _mod12310.SEMANTIC_ATTRIBUTE_PROFILE_ID;
export const SEMANTIC_ATTRIBUTE_SENTRY_CUSTOM_SPAN_NAME = _mod12310.SEMANTIC_ATTRIBUTE_SENTRY_CUSTOM_SPAN_NAME;
export const SEMANTIC_ATTRIBUTE_SENTRY_IDLE_SPAN_FINISH_REASON =
  _mod12310.SEMANTIC_ATTRIBUTE_SENTRY_IDLE_SPAN_FINISH_REASON;
export const SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_UNIT = _mod12310.SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_UNIT;
export const SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_VALUE = _mod12310.SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_VALUE;
export const SEMANTIC_ATTRIBUTE_SENTRY_OP = _mod12310.SEMANTIC_ATTRIBUTE_SENTRY_OP;
export const SEMANTIC_ATTRIBUTE_SENTRY_ORIGIN = _mod12310.SEMANTIC_ATTRIBUTE_SENTRY_ORIGIN;
export const SEMANTIC_ATTRIBUTE_SENTRY_SAMPLE_RATE = _mod12310.SEMANTIC_ATTRIBUTE_SENTRY_SAMPLE_RATE;
export const SEMANTIC_ATTRIBUTE_SENTRY_SOURCE = _mod12310.SEMANTIC_ATTRIBUTE_SENTRY_SOURCE;
export const SEMANTIC_ATTRIBUTE_URL_FULL = _mod12310.SEMANTIC_ATTRIBUTE_URL_FULL;
export const createEventEnvelope = _mod12338.createEventEnvelope;
export const createSessionEnvelope = _mod12338.createSessionEnvelope;
export const createSpanEnvelope = _mod12338.createSpanEnvelope;
export const addEventProcessor = _flush.addEventProcessor;
export const captureCheckIn = _flush.captureCheckIn;
export const captureEvent = _flush.captureEvent;
export const captureException = _flush.captureException;
export const captureMessage = _flush.captureMessage;
export const captureSession = _flush.captureSession;
export const close = _flush.close;
export const endSession = _flush.endSession;
export const flush = _flush.flush;
export const isEnabled = _flush.isEnabled;
export const isInitialized = _flush.isInitialized;
export const lastEventId = _flush.lastEventId;
export const setContext = _flush.setContext;
export const setExtra = _flush.setExtra;
export const setExtras = _flush.setExtras;
export const setTag = _flush.setTag;
export const setTags = _flush.setTags;
export const setUser = _flush.setUser;
export const startSession = _flush.startSession;
export const withMonitor = _flush.withMonitor;
export const getClient = _mod12322.getClient;
export const getCurrentScope = _mod12322.getCurrentScope;
export const getGlobalScope = _mod12322.getGlobalScope;
export const getIsolationScope = _mod12322.getIsolationScope;
export const getTraceContextFromScope = _mod12322.getTraceContextFromScope;
export const withIsolationScope = _mod12322.withIsolationScope;
export const withScope = _mod12322.withScope;
export const getDefaultCurrentScope = _mod12321.getDefaultCurrentScope;
export const getDefaultIsolationScope = _mod12321.getDefaultIsolationScope;
export const setAsyncContextStrategy = _mod12314.setAsyncContextStrategy;
export const getMainCarrier = _mod12313.getMainCarrier;
export const closeSession = _mod12318.closeSession;
export const makeSession = _mod12318.makeSession;
export const updateSession = _mod12318.updateSession;
export const SessionFlusher = SessionFlusher.SessionFlusher;
export const Scope = ScopeClass.Scope;
export const notifyEventProcessors = notifyEventProcessors.notifyEventProcessors;
export const getEnvelopeEndpointWithUrlEncodedAuth = _mod12349.getEnvelopeEndpointWithUrlEncodedAuth;
export const getReportDialogEndpoint = _mod12349.getReportDialogEndpoint;
export const BaseClient = _mod12350.BaseClient;
export const ServerRuntimeClient = _mod12354.ServerRuntimeClient;
export const initAndBind = _mod12357.initAndBind;
export const setCurrentClient = _mod12357.setCurrentClient;
export const createTransport = _mod12358.createTransport;
export const makeOfflineTransport = _mod12361.makeOfflineTransport;
export const makeMultiplexedTransport = _mod12362.makeMultiplexedTransport;
export const addIntegration = _mod12351.addIntegration;
export const defineIntegration = _mod12351.defineIntegration;
export const getIntegrationsToSetup = _mod12351.getIntegrationsToSetup;
export const applyScopeDataToEvent = applyScopeDataToEvent.applyScopeDataToEvent;
export const mergeScopeData = applyScopeDataToEvent.mergeScopeData;
export const prepareEvent = _mod12344.prepareEvent;
export const createCheckInEnvelope = _mod12356.createCheckInEnvelope;
export const hasTracingEnabled = _mod12327.hasTracingEnabled;
export const isSentryRequestUrl = _mod12363.isSentryRequestUrl;
export const handleCallbackErrors = _mod12330.handleCallbackErrors;
export const parameterize = _mod12364.parameterize;
export const addChildSpanToSpan = spanTimeInputToSeconds.addChildSpanToSpan;
export const getActiveSpan = spanTimeInputToSeconds.getActiveSpan;
export const getRootSpan = spanTimeInputToSeconds.getRootSpan;
export const getSpanDescendants = spanTimeInputToSeconds.getSpanDescendants;
export const getStatusMessage = spanTimeInputToSeconds.getStatusMessage;
export const spanIsSampled = spanTimeInputToSeconds.spanIsSampled;
export const spanTimeInputToSeconds = spanTimeInputToSeconds.spanTimeInputToSeconds;
export const spanToJSON = spanTimeInputToSeconds.spanToJSON;
export const spanToTraceContext = spanTimeInputToSeconds.spanToTraceContext;
export const spanToTraceHeader = spanTimeInputToSeconds.spanToTraceHeader;
export const updateSpanName = spanTimeInputToSeconds.updateSpanName;
export const parseSampleRate = _mod12335.parseSampleRate;
export const applySdkMetadata = _mod12365.applySdkMetadata;
export const getTraceData = _mod12366.getTraceData;
export const getTraceMetaTags = _mod12367.getTraceMetaTags;
export const DEFAULT_ENVIRONMENT = _mod12332.DEFAULT_ENVIRONMENT;
export const addBreadcrumb = _mod12368.addBreadcrumb;
export const functionToStringIntegration = _mod12369.functionToStringIntegration;
export const inboundFiltersIntegration = _getEventFilterUrl.inboundFiltersIntegration;
export const linkedErrorsIntegration = _mod12371.linkedErrorsIntegration;
export const moduleMetadataIntegration = _mod12373.moduleMetadataIntegration;
export const requestDataIntegration = _mod12375.requestDataIntegration;
export const captureConsoleIntegration = _mod12380.captureConsoleIntegration;
export const debugIntegration = debugIntegration.debugIntegration;
export const dedupeIntegration = _mod12384.dedupeIntegration;
export const extraErrorDataIntegration = extraErrorDataIntegration.extraErrorDataIntegration;
export const rewriteFramesIntegration = _mod12386.rewriteFramesIntegration;
export const sessionTimingIntegration = sessionTimingIntegration.sessionTimingIntegration;
export const zodErrorsIntegration = _mod12389.zodErrorsIntegration;
export const thirdPartyErrorFilterIntegration = _mod12390.thirdPartyErrorFilterIntegration;
export const metrics = _mod12391.metrics;
export const profiler = _mod12393.profiler;
export const metricsDefault = metricsDefault.metricsDefault;
export const BrowserMetricsAggregator = BrowserMetricsAggregator.BrowserMetricsAggregator;
export const getMetricSummaryJsonForSpan = _mod12311.getMetricSummaryJsonForSpan;
export const addTracingHeadersToFetchRequest = _mod12400.addTracingHeadersToFetchRequest;
export const instrumentFetchRequest = _mod12400.instrumentFetchRequest;
export const trpcMiddleware = _mod12401.trpcMiddleware;
export const captureFeedback = _mod12402.captureFeedback;
export const getCurrentHub = _mod12403.getCurrentHub;
export const getCurrentHubShim = _mod12403.getCurrentHubShim;
export const applyAggregateErrorsToEvent = _mod12372.applyAggregateErrorsToEvent;
export const flatten = _mod12404.flatten;
export const getBreadcrumbLogLevelFromHttpStatusCode = _mod12405.getBreadcrumbLogLevelFromHttpStatusCode;
export const getComponentName = _mod12303.getComponentName;
export const getDomElement = _mod12303.getDomElement;
export const getLocationHref = _mod12303.getLocationHref;
export const htmlTreeAsString = _mod12303.htmlTreeAsString;
export const dsnFromString = _mod12342.dsnFromString;
export const dsnToString = _mod12342.dsnToString;
export const makeDsn = _mod12342.makeDsn;
export const SentryError = _mod12352.SentryError;
export const GLOBAL_OBJ = _mod12296.GLOBAL_OBJ;
export const getGlobalSingleton = _mod12296.getGlobalSingleton;
export const addConsoleInstrumentationHandler = _mod12381.addConsoleInstrumentationHandler;
export const addFetchEndInstrumentationHandler = _mod12406.addFetchEndInstrumentationHandler;
export const addFetchInstrumentationHandler = _mod12406.addFetchInstrumentationHandler;
export const addGlobalErrorInstrumentationHandler = _mod12292.addGlobalErrorInstrumentationHandler;
export const addGlobalUnhandledRejectionInstrumentationHandler =
  _mod12299.addGlobalUnhandledRejectionInstrumentationHandler;
export const addHandler = _mod12293.addHandler;
export const maybeInstrument = _mod12293.maybeInstrument;
export const resetInstrumentationHandlers = _mod12293.resetInstrumentationHandlers;
export const triggerHandlers = _mod12293.triggerHandlers;
export const isDOMError = _mod12302.isDOMError;
export const isDOMException = _mod12302.isDOMException;
export const isElement = _mod12302.isElement;
export const isError = _mod12302.isError;
export const isErrorEvent = _mod12302.isErrorEvent;
export const isEvent = _mod12302.isEvent;
export const isInstanceOf = _mod12302.isInstanceOf;
export const isParameterizedString = _mod12302.isParameterizedString;
export const isPlainObject = _mod12302.isPlainObject;
export const isPrimitive = _mod12302.isPrimitive;
export const isRegExp = _mod12302.isRegExp;
export const isString = _mod12302.isString;
export const isSyntheticEvent = _mod12302.isSyntheticEvent;
export const isThenable = _mod12302.isThenable;
export const isVueViewModel = _mod12302.isVueViewModel;
export const isBrowser = _mod12408.isBrowser;
export const CONSOLE_LEVELS = _mod12295.CONSOLE_LEVELS;
export const consoleSandbox = _mod12295.consoleSandbox;
export const logger = _mod12295.logger;
export const originalConsoleMethods = _mod12295.originalConsoleMethods;
export const memoBuilder = memoBuilder.memoBuilder;
export const addContextToFrame = _mod12306.addContextToFrame;
export const addExceptionMechanism = _mod12306.addExceptionMechanism;
export const addExceptionTypeValue = _mod12306.addExceptionTypeValue;
export const arrayify = _mod12306.arrayify;
export const checkOrSetAlreadyCaught = _mod12306.checkOrSetAlreadyCaught;
export const getEventDescription = _mod12306.getEventDescription;
export const parseSemver = _mod12306.parseSemver;
export const uuid4 = _mod12306.uuid4;
export const dynamicRequire = _mod12409.dynamicRequire;
export const isNodeEnv = _mod12409.isNodeEnv;
export const loadModule = _mod12409.loadModule;
export const normalize = _mod12340.normalize;
export const normalizeToSize = _mod12340.normalizeToSize;
export const normalizeUrlToBase = _mod12340.normalizeUrlToBase;
export const addNonEnumerableProperty = _mod12301.addNonEnumerableProperty;
export const convertToPlainObject = _mod12301.convertToPlainObject;
export const dropUndefinedKeys = _mod12301.dropUndefinedKeys;
export const extractExceptionKeysForMessage = _mod12301.extractExceptionKeysForMessage;
export const fill = _mod12301.fill;
export const getOriginalFunction = _mod12301.getOriginalFunction;
export const markFunctionWrapped = _mod12301.markFunctionWrapped;
export const objectify = _mod12301.objectify;
export const urlEncode = _mod12301.urlEncode;
export const basename = _mod12387.basename;
export const dirname = _mod12387.dirname;
export const isAbsolute = _mod12387.isAbsolute;
export const join = _mod12387.join;
export const normalizePath = _mod12387.normalizePath;
export const relative = _mod12387.relative;
export const resolve = _mod12387.resolve;
export const makePromiseBuffer = _mod12359.makePromiseBuffer;
export const DEFAULT_USER_INCLUDES = extractRequestData.DEFAULT_USER_INCLUDES;
export const addNormalizedRequestDataToEvent = extractRequestData.addNormalizedRequestDataToEvent;
export const addRequestDataToEvent = extractRequestData.addRequestDataToEvent;
export const extractPathForTransaction = extractRequestData.extractPathForTransaction;
export const extractQueryParamsFromUrl = extractRequestData.extractQueryParamsFromUrl;
export const extractRequestData = extractRequestData.extractRequestData;
export const headersToDict = extractRequestData.headersToDict;
export const httpRequestToRequestData = extractRequestData.httpRequestToRequestData;
export const winterCGHeadersToDict = extractRequestData.winterCGHeadersToDict;
export const winterCGRequestToRequestData = extractRequestData.winterCGRequestToRequestData;
export const severityLevelFromString = _mod12382.severityLevelFromString;
export const validSeverityLevels = _mod12382.validSeverityLevels;
export const UNKNOWN_FUNCTION = stackParserFromStackParserOptions.UNKNOWN_FUNCTION;
export const createStackParser = stackParserFromStackParserOptions.createStackParser;
export const getFramesFromEvent = stackParserFromStackParserOptions.getFramesFromEvent;
export const getFunctionName = stackParserFromStackParserOptions.getFunctionName;
export const stackParserFromStackParserOptions = stackParserFromStackParserOptions.stackParserFromStackParserOptions;
export const stripSentryFramesAndReverse = stackParserFromStackParserOptions.stripSentryFramesAndReverse;
export const filenameIsInApp = _mod12411.filenameIsInApp;
export const node = _mod12411.node;
export const nodeStackLineParser = _mod12411.nodeStackLineParser;
export const isMatchingPattern = _mod12304.isMatchingPattern;
export const safeJoin = _mod12304.safeJoin;
export const snipLine = _mod12304.snipLine;
export const stringMatchesSomePattern = _mod12304.stringMatchesSomePattern;
export const truncate = _mod12304.truncate;
export const isNativeFunction = supportsFetch.isNativeFunction;
export const supportsDOMError = supportsFetch.supportsDOMError;
export const supportsDOMException = supportsFetch.supportsDOMException;
export const supportsErrorEvent = supportsFetch.supportsErrorEvent;
export const supportsFetch = supportsFetch.supportsFetch;
export const supportsNativeFetch = supportsFetch.supportsNativeFetch;
export const supportsReferrerPolicy = supportsFetch.supportsReferrerPolicy;
export const supportsReportingObserver = supportsFetch.supportsReportingObserver;
export const SyncPromise = _mod12319.SyncPromise;
export const rejectedSyncPromise = _mod12319.rejectedSyncPromise;
export const resolvedSyncPromise = _mod12319.resolvedSyncPromise;
export const _browserPerformanceTimeOriginMode = require("12309__.js")._browserPerformanceTimeOriginMode;
export const browserPerformanceTimeOrigin = require("12309__.js").browserPerformanceTimeOrigin;
export const dateTimestampInSeconds = require("12309__.js").dateTimestampInSeconds;
export const timestampInSeconds = require("12309__.js").timestampInSeconds;
export const TRACEPARENT_REGEXP = _mod12307.TRACEPARENT_REGEXP;
export const extractTraceparentData = _mod12307.extractTraceparentData;
export const generateSentryTraceHeader = _mod12307.generateSentryTraceHeader;
export const propagationContextFromHeaders = _mod12307.propagationContextFromHeaders;
export const getSDKSource = _mod12410.getSDKSource;
export const isBrowserBundle = _mod12410.isBrowserBundle;
export const addItemToEnvelope = _mod12339.addItemToEnvelope;
export const createAttachmentEnvelopeItem = _mod12339.createAttachmentEnvelopeItem;
export const createEnvelope = _mod12339.createEnvelope;
export const createEventEnvelopeHeaders = _mod12339.createEventEnvelopeHeaders;
export const createSpanEnvelopeItem = _mod12339.createSpanEnvelopeItem;
export const envelopeContainsItemType = _mod12339.envelopeContainsItemType;
export const envelopeItemTypeToDataCategory = _mod12339.envelopeItemTypeToDataCategory;
export const forEachEnvelopeItem = _mod12339.forEachEnvelopeItem;
export const getSdkMetadataForEnvelopeHeader = _mod12339.getSdkMetadataForEnvelopeHeader;
export const parseEnvelope = _mod12339.parseEnvelope;
export const serializeEnvelope = _mod12339.serializeEnvelope;
export const createClientReportEnvelope = _mod12353.createClientReportEnvelope;
export const DEFAULT_RETRY_AFTER = _mod12360.DEFAULT_RETRY_AFTER;
export const disabledUntil = _mod12360.disabledUntil;
export const isRateLimited = _mod12360.isRateLimited;
export const parseRetryAfterHeader = _mod12360.parseRetryAfterHeader;
export const updateRateLimits = _mod12360.updateRateLimits;
export const BAGGAGE_HEADER_NAME = BAGGAGE_HEADER_NAME.BAGGAGE_HEADER_NAME;
export const MAX_BAGGAGE_STRING_LENGTH = BAGGAGE_HEADER_NAME.MAX_BAGGAGE_STRING_LENGTH;
export const SENTRY_BAGGAGE_KEY_PREFIX = BAGGAGE_HEADER_NAME.SENTRY_BAGGAGE_KEY_PREFIX;
export const SENTRY_BAGGAGE_KEY_PREFIX_REGEX = BAGGAGE_HEADER_NAME.SENTRY_BAGGAGE_KEY_PREFIX_REGEX;
export const baggageHeaderToDynamicSamplingContext = BAGGAGE_HEADER_NAME.baggageHeaderToDynamicSamplingContext;
export const dynamicSamplingContextToSentryBaggageHeader =
  BAGGAGE_HEADER_NAME.dynamicSamplingContextToSentryBaggageHeader;
export const parseBaggageHeader = BAGGAGE_HEADER_NAME.parseBaggageHeader;
export const getNumberOfUrlSegments = stripUrlQueryAndFragment.getNumberOfUrlSegments;
export const getSanitizedUrlString = stripUrlQueryAndFragment.getSanitizedUrlString;
export const parseUrl = stripUrlQueryAndFragment.parseUrl;
export const stripUrlQueryAndFragment = stripUrlQueryAndFragment.stripUrlQueryAndFragment;
export const makeFifoCache = _mod12412.makeFifoCache;
export const eventFromMessage = eventFromMessage.eventFromMessage;
export const eventFromUnknownInput = eventFromMessage.eventFromUnknownInput;
export const exceptionFromError = eventFromMessage.exceptionFromError;
export const parseStackFrames = eventFromMessage.parseStackFrames;
export const callFrameToStackFrame = _mod12413.callFrameToStackFrame;
export const watchdogTimer = _mod12413.watchdogTimer;
export const LRUMap = _mod12414.LRUMap;
export const generatePropagationContext = generatePropagationContext.generatePropagationContext;
export const generateSpanId = generatePropagationContext.generateSpanId;
export const generateTraceId = generatePropagationContext.generateTraceId;
export const vercelWaitUntil = _mod12415.vercelWaitUntil;
export const SDK_VERSION = _mod12297.SDK_VERSION;
export const getDebugImagesForResources = _mod12347.getDebugImagesForResources;
export const getFilenameToDebugIdMap = _mod12347.getFilenameToDebugIdMap;
export const escapeStringForRegex = _mod12416.escapeStringForRegex;
export const supportsHistory = supportsHistory.supportsHistory;
export const _asyncNullishCoalesce = _asyncNullishCoalesce2._asyncNullishCoalesce;
export const _asyncOptionalChain = _asyncOptionalChain2._asyncOptionalChain;
export const _asyncOptionalChainDelete = _asyncOptionalChainDelete2._asyncOptionalChainDelete;
export const _nullishCoalesce = _nullishCoalesce._nullishCoalesce;
export const _optionalChain = _optionalChain._optionalChain;
export const _optionalChainDelete = _optionalChainDelete._optionalChainDelete;
