// _runtime/metro/12308__.js
import errorCallback from "../12309_errorCallback.js";
import _mod12310 from "12310__.js";
import _mod12311 from "12311__.js";
import _mod12313 from "12313__.js";
import _mod12314 from "12314__.js";
import _mod12315 from "12315__.js";
import stackParserFromStackParserOptions from "../12316_stackParserFromStackParserOptions.js";
import _mod12317 from "12317__.js";
import spanTimeInputToSeconds from "../12318_spanTimeInputToSeconds.js";
import _mod12319 from "12319__.js";
import _mod12320 from "12320__.js";
import _mod12321 from "12321__.js";
import _mod12322 from "12322__.js";
import generatePropagationContext from "../12323_generatePropagationContext.js";
import _mod12324 from "12324__.js";
import _mod12325 from "12325__.js";
import BAGGAGE_HEADER_NAME from "../12326_BAGGAGE_HEADER_NAME.js";
import _mod12328 from "12328__.js";
import _mod12329 from "12329__.js";
import _mod12330 from "12330__.js";
import _mod12331 from "12331__.js";
import _mod12332 from "12332__.js";
import ScopeClass from "../12334_ScopeClass.js";
import _mod12336 from "12336__.js";
import _mod12337 from "12337__.js";
import _mod12339 from "12339__.js";
import _mod12340 from "12340__.js";
import _mod12342 from "12342__.js";
import _mod12343 from "12343__.js";
import _mod12344 from "12344__.js";
import _mod12345 from "12345__.js";
import _mod12346 from "12346__.js";
import _mod12347 from "12347__.js";
import _mod12348 from "12348__.js";
import _mod12349 from "12349__.js";
import _mod12350 from "12350__.js";
import _mod12351 from "12351__.js";
import _mod12352 from "12352__.js";
import _mod12353 from "12353__.js";
import _mod12354 from "12354__.js";
import _mod12355 from "12355__.js";
import _mod12356 from "12356__.js";
import _mod12357 from "12357__.js";
import _mod12358 from "12358__.js";
import memoBuilder from "../12359_memoBuilder.js";
import _mod12360 from "12360__.js";
import _flush from "../12361__flush.js";
import _mod12362 from "12362__.js";
import applyScopeDataToEvent from "../12363_applyScopeDataToEvent.js";
import notifyEventProcessors from "../12364_notifyEventProcessors.js";
import _mod12365 from "12365__.js";
import SessionFlusher from "../12366_SessionFlusher.js";
import _mod12367 from "12367__.js";
import _mod12368 from "12368__.js";
import _mod12369 from "12369__.js";
import _mod12370 from "12370__.js";
import _mod12371 from "12371__.js";
import _mod12372 from "12372__.js";
import eventFromMessage from "../12373_eventFromMessage.js";
import _mod12374 from "12374__.js";
import _mod12375 from "12375__.js";
import _mod12376 from "12376__.js";
import _mod12377 from "12377__.js";
import _mod12378 from "12378__.js";
import _mod12379 from "12379__.js";
import _mod12380 from "12380__.js";
import _mod12381 from "12381__.js";
import _mod12382 from "12382__.js";
import _mod12383 from "12383__.js";
import _mod12384 from "12384__.js";
import _mod12385 from "12385__.js";
import _mod12386 from "12386__.js";
import _mod12387 from "12387__.js";
import _getEventFilterUrl from "../12388__getEventFilterUrl.js";
import _mod12389 from "12389__.js";
import _mod12390 from "12390__.js";
import _mod12391 from "12391__.js";
import _mod12393 from "12393__.js";
import extractRequestData from "../12394_extractRequestData.js";
import stripUrlQueryAndFragment from "../12395_stripUrlQueryAndFragment.js";
import _mod12398 from "12398__.js";
import _mod12399 from "12399__.js";
import _mod12400 from "12400__.js";
import debugIntegration from "../12401_debugIntegration.js";
import _mod12402 from "12402__.js";
import extraErrorDataIntegration from "../12403_extraErrorDataIntegration.js";
import _mod12404 from "12404__.js";
import _mod12405 from "12405__.js";
import sessionTimingIntegration from "../12406_sessionTimingIntegration.js";
import _mod12407 from "12407__.js";
import _mod12408 from "12408__.js";
import _mod12409 from "12409__.js";
import _mod12411 from "12411__.js";
import metricsDefault from "../12412_metricsDefault.js";
import BrowserMetricsAggregator from "../12417_BrowserMetricsAggregator.js";
import _mod12418 from "12418__.js";
import _mod12419 from "12419__.js";
import _mod12420 from "12420__.js";
import _mod12421 from "12421__.js";
import _mod12422 from "12422__.js";
import _mod12423 from "12423__.js";
import _mod12424 from "12424__.js";
import supportsFetch from "../12425_supportsFetch.js";
import _mod12426 from "12426__.js";
import _mod12427 from "12427__.js";
import _mod12428 from "12428__.js";
import _mod12429 from "12429__.js";
import _mod12430 from "12430__.js";
import _mod12431 from "12431__.js";
import _mod12432 from "12432__.js";
import _mod12433 from "12433__.js";
import _mod12434 from "12434__.js";
import supportsHistory from "../12435_supportsHistory.js";
import _asyncNullishCoalesce2 from "../12436__asyncNullishCoalesce2.js";
import _nullishCoalesce from "../12437__nullishCoalesce.js";
import _asyncOptionalChain2 from "../12438__asyncOptionalChain2.js";
import _asyncOptionalChainDelete2 from "../12439__asyncOptionalChainDelete2.js";
import _optionalChain from "../12440__optionalChain.js";
import _optionalChainDelete from "../12441__optionalChainDelete.js";

const require = globalThis.__r;

export const registerSpanErrorInstrumentation = errorCallback.registerSpanErrorInstrumentation;
export const getCapturedScopesOnSpan = _mod12342.getCapturedScopesOnSpan;
export const setCapturedScopesOnSpan = _mod12342.setCapturedScopesOnSpan;
export const addTracingExtensions = _mod12343.addTracingExtensions;
export const TRACING_DEFAULTS = _mod12344.TRACING_DEFAULTS;
export const startIdleSpan = _mod12344.startIdleSpan;
export const SentrySpan = _mod12354.SentrySpan;
export const SentryNonRecordingSpan = _mod12346.SentryNonRecordingSpan;
export const SPAN_STATUS_ERROR = _mod12330.SPAN_STATUS_ERROR;
export const SPAN_STATUS_OK = _mod12330.SPAN_STATUS_OK;
export const SPAN_STATUS_UNSET = _mod12330.SPAN_STATUS_UNSET;
export const getSpanStatusFromHttpCode = _mod12330.getSpanStatusFromHttpCode;
export const setHttpStatus = _mod12330.setHttpStatus;
export const continueTrace = _mod12347.continueTrace;
export const startInactiveSpan = _mod12347.startInactiveSpan;
export const startNewTrace = _mod12347.startNewTrace;
export const startSpan = _mod12347.startSpan;
export const startSpanManual = _mod12347.startSpanManual;
export const suppressTracing = _mod12347.suppressTracing;
export const withActiveSpan = _mod12347.withActiveSpan;
export const getDynamicSamplingContextFromClient = _mod12349.getDynamicSamplingContextFromClient;
export const getDynamicSamplingContextFromScope = _mod12349.getDynamicSamplingContextFromScope;
export const getDynamicSamplingContextFromSpan = _mod12349.getDynamicSamplingContextFromSpan;
export const spanToBaggageHeader = _mod12349.spanToBaggageHeader;
export const setMeasurement = _mod12355.setMeasurement;
export const timedEventsToMeasurements = _mod12355.timedEventsToMeasurements;
export const sampleSpan = _mod12352.sampleSpan;
export const logSpanEnd = _mod12351.logSpanEnd;
export const logSpanStart = _mod12351.logSpanStart;
export const SEMANTIC_ATTRIBUTE_CACHE_HIT = _mod12328.SEMANTIC_ATTRIBUTE_CACHE_HIT;
export const SEMANTIC_ATTRIBUTE_CACHE_ITEM_SIZE = _mod12328.SEMANTIC_ATTRIBUTE_CACHE_ITEM_SIZE;
export const SEMANTIC_ATTRIBUTE_CACHE_KEY = _mod12328.SEMANTIC_ATTRIBUTE_CACHE_KEY;
export const SEMANTIC_ATTRIBUTE_EXCLUSIVE_TIME = _mod12328.SEMANTIC_ATTRIBUTE_EXCLUSIVE_TIME;
export const SEMANTIC_ATTRIBUTE_HTTP_REQUEST_METHOD = _mod12328.SEMANTIC_ATTRIBUTE_HTTP_REQUEST_METHOD;
export const SEMANTIC_ATTRIBUTE_PROFILE_ID = _mod12328.SEMANTIC_ATTRIBUTE_PROFILE_ID;
export const SEMANTIC_ATTRIBUTE_SENTRY_CUSTOM_SPAN_NAME = _mod12328.SEMANTIC_ATTRIBUTE_SENTRY_CUSTOM_SPAN_NAME;
export const SEMANTIC_ATTRIBUTE_SENTRY_IDLE_SPAN_FINISH_REASON =
  _mod12328.SEMANTIC_ATTRIBUTE_SENTRY_IDLE_SPAN_FINISH_REASON;
export const SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_UNIT = _mod12328.SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_UNIT;
export const SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_VALUE = _mod12328.SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_VALUE;
export const SEMANTIC_ATTRIBUTE_SENTRY_OP = _mod12328.SEMANTIC_ATTRIBUTE_SENTRY_OP;
export const SEMANTIC_ATTRIBUTE_SENTRY_ORIGIN = _mod12328.SEMANTIC_ATTRIBUTE_SENTRY_ORIGIN;
export const SEMANTIC_ATTRIBUTE_SENTRY_SAMPLE_RATE = _mod12328.SEMANTIC_ATTRIBUTE_SENTRY_SAMPLE_RATE;
export const SEMANTIC_ATTRIBUTE_SENTRY_SOURCE = _mod12328.SEMANTIC_ATTRIBUTE_SENTRY_SOURCE;
export const SEMANTIC_ATTRIBUTE_URL_FULL = _mod12328.SEMANTIC_ATTRIBUTE_URL_FULL;
export const createEventEnvelope = _mod12356.createEventEnvelope;
export const createSessionEnvelope = _mod12356.createSessionEnvelope;
export const createSpanEnvelope = _mod12356.createSpanEnvelope;
export const addEventProcessor = _flush.addEventProcessor;
export const captureCheckIn = _flush.captureCheckIn;
export const captureEvent = _flush.captureEvent;
export const captureException = _flush.captureException;
export const captureMessage = _flush.captureMessage;
export const captureSession = _flush.captureSession;
export const close = _flush.close;
export const endSession = _flush.endSession;
export const flush = _flush.flush;
export const isEnabled = _flush.isEnabled;
export const isInitialized = _flush.isInitialized;
export const lastEventId = _flush.lastEventId;
export const setContext = _flush.setContext;
export const setExtra = _flush.setExtra;
export const setExtras = _flush.setExtras;
export const setTag = _flush.setTag;
export const setTags = _flush.setTags;
export const setUser = _flush.setUser;
export const startSession = _flush.startSession;
export const withMonitor = _flush.withMonitor;
export const getClient = _mod12340.getClient;
export const getCurrentScope = _mod12340.getCurrentScope;
export const getGlobalScope = _mod12340.getGlobalScope;
export const getIsolationScope = _mod12340.getIsolationScope;
export const getTraceContextFromScope = _mod12340.getTraceContextFromScope;
export const withIsolationScope = _mod12340.withIsolationScope;
export const withScope = _mod12340.withScope;
export const getDefaultCurrentScope = _mod12339.getDefaultCurrentScope;
export const getDefaultIsolationScope = _mod12339.getDefaultIsolationScope;
export const setAsyncContextStrategy = _mod12332.setAsyncContextStrategy;
export const getMainCarrier = _mod12331.getMainCarrier;
export const closeSession = _mod12336.closeSession;
export const makeSession = _mod12336.makeSession;
export const updateSession = _mod12336.updateSession;
export const SessionFlusher = SessionFlusher.SessionFlusher;
export const Scope = ScopeClass.Scope;
export const notifyEventProcessors = notifyEventProcessors.notifyEventProcessors;
export const getEnvelopeEndpointWithUrlEncodedAuth = _mod12367.getEnvelopeEndpointWithUrlEncodedAuth;
export const getReportDialogEndpoint = _mod12367.getReportDialogEndpoint;
export const BaseClient = _mod12368.BaseClient;
export const ServerRuntimeClient = _mod12372.ServerRuntimeClient;
export const initAndBind = _mod12375.initAndBind;
export const setCurrentClient = _mod12375.setCurrentClient;
export const createTransport = _mod12376.createTransport;
export const makeOfflineTransport = _mod12379.makeOfflineTransport;
export const makeMultiplexedTransport = _mod12380.makeMultiplexedTransport;
export const addIntegration = _mod12369.addIntegration;
export const defineIntegration = _mod12369.defineIntegration;
export const getIntegrationsToSetup = _mod12369.getIntegrationsToSetup;
export const applyScopeDataToEvent = applyScopeDataToEvent.applyScopeDataToEvent;
export const mergeScopeData = applyScopeDataToEvent.mergeScopeData;
export const prepareEvent = _mod12362.prepareEvent;
export const createCheckInEnvelope = _mod12374.createCheckInEnvelope;
export const hasTracingEnabled = _mod12345.hasTracingEnabled;
export const isSentryRequestUrl = _mod12381.isSentryRequestUrl;
export const handleCallbackErrors = _mod12348.handleCallbackErrors;
export const parameterize = _mod12382.parameterize;
export const addChildSpanToSpan = spanTimeInputToSeconds.addChildSpanToSpan;
export const getActiveSpan = spanTimeInputToSeconds.getActiveSpan;
export const getRootSpan = spanTimeInputToSeconds.getRootSpan;
export const getSpanDescendants = spanTimeInputToSeconds.getSpanDescendants;
export const getStatusMessage = spanTimeInputToSeconds.getStatusMessage;
export const spanIsSampled = spanTimeInputToSeconds.spanIsSampled;
export const spanTimeInputToSeconds = spanTimeInputToSeconds.spanTimeInputToSeconds;
export const spanToJSON = spanTimeInputToSeconds.spanToJSON;
export const spanToTraceContext = spanTimeInputToSeconds.spanToTraceContext;
export const spanToTraceHeader = spanTimeInputToSeconds.spanToTraceHeader;
export const updateSpanName = spanTimeInputToSeconds.updateSpanName;
export const parseSampleRate = _mod12353.parseSampleRate;
export const applySdkMetadata = _mod12383.applySdkMetadata;
export const getTraceData = _mod12384.getTraceData;
export const getTraceMetaTags = _mod12385.getTraceMetaTags;
export const DEFAULT_ENVIRONMENT = _mod12350.DEFAULT_ENVIRONMENT;
export const addBreadcrumb = _mod12386.addBreadcrumb;
export const functionToStringIntegration = _mod12387.functionToStringIntegration;
export const inboundFiltersIntegration = _getEventFilterUrl.inboundFiltersIntegration;
export const linkedErrorsIntegration = _mod12389.linkedErrorsIntegration;
export const moduleMetadataIntegration = _mod12391.moduleMetadataIntegration;
export const requestDataIntegration = _mod12393.requestDataIntegration;
export const captureConsoleIntegration = _mod12398.captureConsoleIntegration;
export const debugIntegration = debugIntegration.debugIntegration;
export const dedupeIntegration = _mod12402.dedupeIntegration;
export const extraErrorDataIntegration = extraErrorDataIntegration.extraErrorDataIntegration;
export const rewriteFramesIntegration = _mod12404.rewriteFramesIntegration;
export const sessionTimingIntegration = sessionTimingIntegration.sessionTimingIntegration;
export const zodErrorsIntegration = _mod12407.zodErrorsIntegration;
export const thirdPartyErrorFilterIntegration = _mod12408.thirdPartyErrorFilterIntegration;
export const metrics = _mod12409.metrics;
export const profiler = _mod12411.profiler;
export const metricsDefault = metricsDefault.metricsDefault;
export const BrowserMetricsAggregator = BrowserMetricsAggregator.BrowserMetricsAggregator;
export const getMetricSummaryJsonForSpan = _mod12329.getMetricSummaryJsonForSpan;
export const addTracingHeadersToFetchRequest = _mod12418.addTracingHeadersToFetchRequest;
export const instrumentFetchRequest = _mod12418.instrumentFetchRequest;
export const trpcMiddleware = _mod12419.trpcMiddleware;
export const captureFeedback = _mod12420.captureFeedback;
export const getCurrentHub = _mod12421.getCurrentHub;
export const getCurrentHubShim = _mod12421.getCurrentHubShim;
export const applyAggregateErrorsToEvent = _mod12390.applyAggregateErrorsToEvent;
export const flatten = _mod12422.flatten;
export const getBreadcrumbLogLevelFromHttpStatusCode = _mod12423.getBreadcrumbLogLevelFromHttpStatusCode;
export const getComponentName = _mod12321.getComponentName;
export const getDomElement = _mod12321.getDomElement;
export const getLocationHref = _mod12321.getLocationHref;
export const htmlTreeAsString = _mod12321.htmlTreeAsString;
export const dsnFromString = _mod12360.dsnFromString;
export const dsnToString = _mod12360.dsnToString;
export const makeDsn = _mod12360.makeDsn;
export const SentryError = _mod12370.SentryError;
export const GLOBAL_OBJ = _mod12314.GLOBAL_OBJ;
export const getGlobalSingleton = _mod12314.getGlobalSingleton;
export const addConsoleInstrumentationHandler = _mod12399.addConsoleInstrumentationHandler;
export const addFetchEndInstrumentationHandler = _mod12424.addFetchEndInstrumentationHandler;
export const addFetchInstrumentationHandler = _mod12424.addFetchInstrumentationHandler;
export const addGlobalErrorInstrumentationHandler = _mod12310.addGlobalErrorInstrumentationHandler;
export const addGlobalUnhandledRejectionInstrumentationHandler =
  _mod12317.addGlobalUnhandledRejectionInstrumentationHandler;
export const addHandler = _mod12311.addHandler;
export const maybeInstrument = _mod12311.maybeInstrument;
export const resetInstrumentationHandlers = _mod12311.resetInstrumentationHandlers;
export const triggerHandlers = _mod12311.triggerHandlers;
export const isDOMError = _mod12320.isDOMError;
export const isDOMException = _mod12320.isDOMException;
export const isElement = _mod12320.isElement;
export const isError = _mod12320.isError;
export const isErrorEvent = _mod12320.isErrorEvent;
export const isEvent = _mod12320.isEvent;
export const isInstanceOf = _mod12320.isInstanceOf;
export const isParameterizedString = _mod12320.isParameterizedString;
export const isPlainObject = _mod12320.isPlainObject;
export const isPrimitive = _mod12320.isPrimitive;
export const isRegExp = _mod12320.isRegExp;
export const isString = _mod12320.isString;
export const isSyntheticEvent = _mod12320.isSyntheticEvent;
export const isThenable = _mod12320.isThenable;
export const isVueViewModel = _mod12320.isVueViewModel;
export const isBrowser = _mod12426.isBrowser;
export const CONSOLE_LEVELS = _mod12313.CONSOLE_LEVELS;
export const consoleSandbox = _mod12313.consoleSandbox;
export const logger = _mod12313.logger;
export const originalConsoleMethods = _mod12313.originalConsoleMethods;
export const memoBuilder = memoBuilder.memoBuilder;
export const addContextToFrame = _mod12324.addContextToFrame;
export const addExceptionMechanism = _mod12324.addExceptionMechanism;
export const addExceptionTypeValue = _mod12324.addExceptionTypeValue;
export const arrayify = _mod12324.arrayify;
export const checkOrSetAlreadyCaught = _mod12324.checkOrSetAlreadyCaught;
export const getEventDescription = _mod12324.getEventDescription;
export const parseSemver = _mod12324.parseSemver;
export const uuid4 = _mod12324.uuid4;
export const dynamicRequire = _mod12427.dynamicRequire;
export const isNodeEnv = _mod12427.isNodeEnv;
export const loadModule = _mod12427.loadModule;
export const normalize = _mod12358.normalize;
export const normalizeToSize = _mod12358.normalizeToSize;
export const normalizeUrlToBase = _mod12358.normalizeUrlToBase;
export const addNonEnumerableProperty = _mod12319.addNonEnumerableProperty;
export const convertToPlainObject = _mod12319.convertToPlainObject;
export const dropUndefinedKeys = _mod12319.dropUndefinedKeys;
export const extractExceptionKeysForMessage = _mod12319.extractExceptionKeysForMessage;
export const fill = _mod12319.fill;
export const getOriginalFunction = _mod12319.getOriginalFunction;
export const markFunctionWrapped = _mod12319.markFunctionWrapped;
export const objectify = _mod12319.objectify;
export const urlEncode = _mod12319.urlEncode;
export const basename = _mod12405.basename;
export const dirname = _mod12405.dirname;
export const isAbsolute = _mod12405.isAbsolute;
export const join = _mod12405.join;
export const normalizePath = _mod12405.normalizePath;
export const relative = _mod12405.relative;
export const resolve = _mod12405.resolve;
export const makePromiseBuffer = _mod12377.makePromiseBuffer;
export const DEFAULT_USER_INCLUDES = extractRequestData.DEFAULT_USER_INCLUDES;
export const addNormalizedRequestDataToEvent = extractRequestData.addNormalizedRequestDataToEvent;
export const addRequestDataToEvent = extractRequestData.addRequestDataToEvent;
export const extractPathForTransaction = extractRequestData.extractPathForTransaction;
export const extractQueryParamsFromUrl = extractRequestData.extractQueryParamsFromUrl;
export const extractRequestData = extractRequestData.extractRequestData;
export const headersToDict = extractRequestData.headersToDict;
export const httpRequestToRequestData = extractRequestData.httpRequestToRequestData;
export const winterCGHeadersToDict = extractRequestData.winterCGHeadersToDict;
export const winterCGRequestToRequestData = extractRequestData.winterCGRequestToRequestData;
export const severityLevelFromString = _mod12400.severityLevelFromString;
export const validSeverityLevels = _mod12400.validSeverityLevels;
export const UNKNOWN_FUNCTION = stackParserFromStackParserOptions.UNKNOWN_FUNCTION;
export const createStackParser = stackParserFromStackParserOptions.createStackParser;
export const getFramesFromEvent = stackParserFromStackParserOptions.getFramesFromEvent;
export const getFunctionName = stackParserFromStackParserOptions.getFunctionName;
export const stackParserFromStackParserOptions = stackParserFromStackParserOptions.stackParserFromStackParserOptions;
export const stripSentryFramesAndReverse = stackParserFromStackParserOptions.stripSentryFramesAndReverse;
export const filenameIsInApp = _mod12429.filenameIsInApp;
export const node = _mod12429.node;
export const nodeStackLineParser = _mod12429.nodeStackLineParser;
export const isMatchingPattern = _mod12322.isMatchingPattern;
export const safeJoin = _mod12322.safeJoin;
export const snipLine = _mod12322.snipLine;
export const stringMatchesSomePattern = _mod12322.stringMatchesSomePattern;
export const truncate = _mod12322.truncate;
export const isNativeFunction = supportsFetch.isNativeFunction;
export const supportsDOMError = supportsFetch.supportsDOMError;
export const supportsDOMException = supportsFetch.supportsDOMException;
export const supportsErrorEvent = supportsFetch.supportsErrorEvent;
export const supportsFetch = supportsFetch.supportsFetch;
export const supportsNativeFetch = supportsFetch.supportsNativeFetch;
export const supportsReferrerPolicy = supportsFetch.supportsReferrerPolicy;
export const supportsReportingObserver = supportsFetch.supportsReportingObserver;
export const SyncPromise = _mod12337.SyncPromise;
export const rejectedSyncPromise = _mod12337.rejectedSyncPromise;
export const resolvedSyncPromise = _mod12337.resolvedSyncPromise;
export const _browserPerformanceTimeOriginMode = require("12327__.js")._browserPerformanceTimeOriginMode;
export const browserPerformanceTimeOrigin = require("12327__.js").browserPerformanceTimeOrigin;
export const dateTimestampInSeconds = require("12327__.js").dateTimestampInSeconds;
export const timestampInSeconds = require("12327__.js").timestampInSeconds;
export const TRACEPARENT_REGEXP = _mod12325.TRACEPARENT_REGEXP;
export const extractTraceparentData = _mod12325.extractTraceparentData;
export const generateSentryTraceHeader = _mod12325.generateSentryTraceHeader;
export const propagationContextFromHeaders = _mod12325.propagationContextFromHeaders;
export const getSDKSource = _mod12428.getSDKSource;
export const isBrowserBundle = _mod12428.isBrowserBundle;
export const addItemToEnvelope = _mod12357.addItemToEnvelope;
export const createAttachmentEnvelopeItem = _mod12357.createAttachmentEnvelopeItem;
export const createEnvelope = _mod12357.createEnvelope;
export const createEventEnvelopeHeaders = _mod12357.createEventEnvelopeHeaders;
export const createSpanEnvelopeItem = _mod12357.createSpanEnvelopeItem;
export const envelopeContainsItemType = _mod12357.envelopeContainsItemType;
export const envelopeItemTypeToDataCategory = _mod12357.envelopeItemTypeToDataCategory;
export const forEachEnvelopeItem = _mod12357.forEachEnvelopeItem;
export const getSdkMetadataForEnvelopeHeader = _mod12357.getSdkMetadataForEnvelopeHeader;
export const parseEnvelope = _mod12357.parseEnvelope;
export const serializeEnvelope = _mod12357.serializeEnvelope;
export const createClientReportEnvelope = _mod12371.createClientReportEnvelope;
export const DEFAULT_RETRY_AFTER = _mod12378.DEFAULT_RETRY_AFTER;
export const disabledUntil = _mod12378.disabledUntil;
export const isRateLimited = _mod12378.isRateLimited;
export const parseRetryAfterHeader = _mod12378.parseRetryAfterHeader;
export const updateRateLimits = _mod12378.updateRateLimits;
export const BAGGAGE_HEADER_NAME = BAGGAGE_HEADER_NAME.BAGGAGE_HEADER_NAME;
export const MAX_BAGGAGE_STRING_LENGTH = BAGGAGE_HEADER_NAME.MAX_BAGGAGE_STRING_LENGTH;
export const SENTRY_BAGGAGE_KEY_PREFIX = BAGGAGE_HEADER_NAME.SENTRY_BAGGAGE_KEY_PREFIX;
export const SENTRY_BAGGAGE_KEY_PREFIX_REGEX = BAGGAGE_HEADER_NAME.SENTRY_BAGGAGE_KEY_PREFIX_REGEX;
export const baggageHeaderToDynamicSamplingContext = BAGGAGE_HEADER_NAME.baggageHeaderToDynamicSamplingContext;
export const dynamicSamplingContextToSentryBaggageHeader =
  BAGGAGE_HEADER_NAME.dynamicSamplingContextToSentryBaggageHeader;
export const parseBaggageHeader = BAGGAGE_HEADER_NAME.parseBaggageHeader;
export const getNumberOfUrlSegments = stripUrlQueryAndFragment.getNumberOfUrlSegments;
export const getSanitizedUrlString = stripUrlQueryAndFragment.getSanitizedUrlString;
export const parseUrl = stripUrlQueryAndFragment.parseUrl;
export const stripUrlQueryAndFragment = stripUrlQueryAndFragment.stripUrlQueryAndFragment;
export const makeFifoCache = _mod12430.makeFifoCache;
export const eventFromMessage = eventFromMessage.eventFromMessage;
export const eventFromUnknownInput = eventFromMessage.eventFromUnknownInput;
export const exceptionFromError = eventFromMessage.exceptionFromError;
export const parseStackFrames = eventFromMessage.parseStackFrames;
export const callFrameToStackFrame = _mod12431.callFrameToStackFrame;
export const watchdogTimer = _mod12431.watchdogTimer;
export const LRUMap = _mod12432.LRUMap;
export const generatePropagationContext = generatePropagationContext.generatePropagationContext;
export const generateSpanId = generatePropagationContext.generateSpanId;
export const generateTraceId = generatePropagationContext.generateTraceId;
export const vercelWaitUntil = _mod12433.vercelWaitUntil;
export const SDK_VERSION = _mod12315.SDK_VERSION;
export const getDebugImagesForResources = _mod12365.getDebugImagesForResources;
export const getFilenameToDebugIdMap = _mod12365.getFilenameToDebugIdMap;
export const escapeStringForRegex = _mod12434.escapeStringForRegex;
export const supportsHistory = supportsHistory.supportsHistory;
export const _asyncNullishCoalesce = _asyncNullishCoalesce2._asyncNullishCoalesce;
export const _asyncOptionalChain = _asyncOptionalChain2._asyncOptionalChain;
export const _asyncOptionalChainDelete = _asyncOptionalChainDelete2._asyncOptionalChainDelete;
export const _nullishCoalesce = _nullishCoalesce._nullishCoalesce;
export const _optionalChain = _optionalChain._optionalChain;
export const _optionalChainDelete = _optionalChainDelete._optionalChainDelete;
