// _runtime/metro/12560__.js
import errorCallback from "../12561_errorCallback.js";
import _mod12562 from "12562__.js";
import _mod12563 from "12563__.js";
import _mod12565 from "12565__.js";
import _mod12566 from "12566__.js";
import _mod12567 from "12567__.js";
import stackParserFromStackParserOptions from "../12568_stackParserFromStackParserOptions.js";
import _mod12569 from "12569__.js";
import spanTimeInputToSeconds from "../12570_spanTimeInputToSeconds.js";
import _mod12571 from "12571__.js";
import _mod12572 from "12572__.js";
import _mod12573 from "12573__.js";
import _mod12574 from "12574__.js";
import generatePropagationContext from "../12575_generatePropagationContext.js";
import _mod12576 from "12576__.js";
import _mod12577 from "12577__.js";
import BAGGAGE_HEADER_NAME from "../12578_BAGGAGE_HEADER_NAME.js";
import _mod12580 from "12580__.js";
import _mod12581 from "12581__.js";
import _mod12582 from "12582__.js";
import _mod12583 from "12583__.js";
import _mod12584 from "12584__.js";
import ScopeClass from "../12586_ScopeClass.js";
import _mod12588 from "12588__.js";
import _mod12589 from "12589__.js";
import _mod12591 from "12591__.js";
import _mod12592 from "12592__.js";
import _mod12594 from "12594__.js";
import _mod12595 from "12595__.js";
import _mod12596 from "12596__.js";
import _mod12597 from "12597__.js";
import _mod12598 from "12598__.js";
import _mod12599 from "12599__.js";
import _mod12600 from "12600__.js";
import _mod12601 from "12601__.js";
import _mod12602 from "12602__.js";
import _mod12603 from "12603__.js";
import _mod12604 from "12604__.js";
import _mod12605 from "12605__.js";
import _mod12606 from "12606__.js";
import _mod12607 from "12607__.js";
import _mod12608 from "12608__.js";
import _mod12609 from "12609__.js";
import _mod12610 from "12610__.js";
import memoBuilder from "../12611_memoBuilder.js";
import _mod12612 from "12612__.js";
import _flush from "../12613__flush.js";
import _mod12614 from "12614__.js";
import applyScopeDataToEvent from "../12615_applyScopeDataToEvent.js";
import notifyEventProcessors from "../12616_notifyEventProcessors.js";
import _mod12617 from "12617__.js";
import SessionFlusher from "../12618_SessionFlusher.js";
import _mod12619 from "12619__.js";
import _mod12620 from "12620__.js";
import _mod12621 from "12621__.js";
import _mod12622 from "12622__.js";
import _mod12623 from "12623__.js";
import _mod12624 from "12624__.js";
import eventFromMessage from "../12625_eventFromMessage.js";
import _mod12626 from "12626__.js";
import _mod12627 from "12627__.js";
import _mod12628 from "12628__.js";
import _mod12629 from "12629__.js";
import _mod12630 from "12630__.js";
import _mod12631 from "12631__.js";
import _mod12632 from "12632__.js";
import _mod12633 from "12633__.js";
import _mod12634 from "12634__.js";
import _mod12635 from "12635__.js";
import _mod12636 from "12636__.js";
import _mod12637 from "12637__.js";
import _mod12638 from "12638__.js";
import _mod12639 from "12639__.js";
import _getEventFilterUrl from "../12640__getEventFilterUrl.js";
import _mod12641 from "12641__.js";
import _mod12642 from "12642__.js";
import _mod12643 from "12643__.js";
import _mod12645 from "12645__.js";
import extractRequestData from "../12646_extractRequestData.js";
import stripUrlQueryAndFragment from "../12647_stripUrlQueryAndFragment.js";
import _mod12650 from "12650__.js";
import _mod12651 from "12651__.js";
import _mod12652 from "12652__.js";
import debugIntegration from "../12653_debugIntegration.js";
import _mod12654 from "12654__.js";
import extraErrorDataIntegration from "../12655_extraErrorDataIntegration.js";
import _mod12656 from "12656__.js";
import _mod12657 from "12657__.js";
import sessionTimingIntegration from "../12658_sessionTimingIntegration.js";
import _mod12659 from "12659__.js";
import _mod12660 from "12660__.js";
import _mod12661 from "12661__.js";
import _mod12663 from "12663__.js";
import metricsDefault from "../12664_metricsDefault.js";
import BrowserMetricsAggregator from "../12669_BrowserMetricsAggregator.js";
import _mod12670 from "12670__.js";
import _mod12671 from "12671__.js";
import _mod12672 from "12672__.js";
import _mod12673 from "12673__.js";
import _mod12674 from "12674__.js";
import _mod12675 from "12675__.js";
import _mod12676 from "12676__.js";
import supportsFetch from "../12677_supportsFetch.js";
import _mod12678 from "12678__.js";
import _mod12679 from "12679__.js";
import _mod12680 from "12680__.js";
import _mod12681 from "12681__.js";
import _mod12682 from "12682__.js";
import _mod12683 from "12683__.js";
import _mod12684 from "12684__.js";
import _mod12685 from "12685__.js";
import _mod12686 from "12686__.js";
import supportsHistory from "../12687_supportsHistory.js";
import _asyncNullishCoalesce2 from "../12688__asyncNullishCoalesce2.js";
import _nullishCoalesce from "../12689__nullishCoalesce.js";
import _asyncOptionalChain2 from "../12690__asyncOptionalChain2.js";
import _asyncOptionalChainDelete2 from "../12691__asyncOptionalChainDelete2.js";
import _optionalChain from "../12692__optionalChain.js";
import _optionalChainDelete from "../12693__optionalChainDelete.js";

const require = globalThis.__r;

export const registerSpanErrorInstrumentation = errorCallback.registerSpanErrorInstrumentation;
export const getCapturedScopesOnSpan = _mod12594.getCapturedScopesOnSpan;
export const setCapturedScopesOnSpan = _mod12594.setCapturedScopesOnSpan;
export const addTracingExtensions = _mod12595.addTracingExtensions;
export const TRACING_DEFAULTS = _mod12596.TRACING_DEFAULTS;
export const startIdleSpan = _mod12596.startIdleSpan;
export const SentrySpan = _mod12606.SentrySpan;
export const SentryNonRecordingSpan = _mod12598.SentryNonRecordingSpan;
export const SPAN_STATUS_ERROR = _mod12582.SPAN_STATUS_ERROR;
export const SPAN_STATUS_OK = _mod12582.SPAN_STATUS_OK;
export const SPAN_STATUS_UNSET = _mod12582.SPAN_STATUS_UNSET;
export const getSpanStatusFromHttpCode = _mod12582.getSpanStatusFromHttpCode;
export const setHttpStatus = _mod12582.setHttpStatus;
export const continueTrace = _mod12599.continueTrace;
export const startInactiveSpan = _mod12599.startInactiveSpan;
export const startNewTrace = _mod12599.startNewTrace;
export const startSpan = _mod12599.startSpan;
export const startSpanManual = _mod12599.startSpanManual;
export const suppressTracing = _mod12599.suppressTracing;
export const withActiveSpan = _mod12599.withActiveSpan;
export const getDynamicSamplingContextFromClient = _mod12601.getDynamicSamplingContextFromClient;
export const getDynamicSamplingContextFromScope = _mod12601.getDynamicSamplingContextFromScope;
export const getDynamicSamplingContextFromSpan = _mod12601.getDynamicSamplingContextFromSpan;
export const spanToBaggageHeader = _mod12601.spanToBaggageHeader;
export const setMeasurement = _mod12607.setMeasurement;
export const timedEventsToMeasurements = _mod12607.timedEventsToMeasurements;
export const sampleSpan = _mod12604.sampleSpan;
export const logSpanEnd = _mod12603.logSpanEnd;
export const logSpanStart = _mod12603.logSpanStart;
export const SEMANTIC_ATTRIBUTE_CACHE_HIT = _mod12580.SEMANTIC_ATTRIBUTE_CACHE_HIT;
export const SEMANTIC_ATTRIBUTE_CACHE_ITEM_SIZE = _mod12580.SEMANTIC_ATTRIBUTE_CACHE_ITEM_SIZE;
export const SEMANTIC_ATTRIBUTE_CACHE_KEY = _mod12580.SEMANTIC_ATTRIBUTE_CACHE_KEY;
export const SEMANTIC_ATTRIBUTE_EXCLUSIVE_TIME = _mod12580.SEMANTIC_ATTRIBUTE_EXCLUSIVE_TIME;
export const SEMANTIC_ATTRIBUTE_HTTP_REQUEST_METHOD = _mod12580.SEMANTIC_ATTRIBUTE_HTTP_REQUEST_METHOD;
export const SEMANTIC_ATTRIBUTE_PROFILE_ID = _mod12580.SEMANTIC_ATTRIBUTE_PROFILE_ID;
export const SEMANTIC_ATTRIBUTE_SENTRY_CUSTOM_SPAN_NAME = _mod12580.SEMANTIC_ATTRIBUTE_SENTRY_CUSTOM_SPAN_NAME;
export const SEMANTIC_ATTRIBUTE_SENTRY_IDLE_SPAN_FINISH_REASON =
  _mod12580.SEMANTIC_ATTRIBUTE_SENTRY_IDLE_SPAN_FINISH_REASON;
export const SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_UNIT = _mod12580.SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_UNIT;
export const SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_VALUE = _mod12580.SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_VALUE;
export const SEMANTIC_ATTRIBUTE_SENTRY_OP = _mod12580.SEMANTIC_ATTRIBUTE_SENTRY_OP;
export const SEMANTIC_ATTRIBUTE_SENTRY_ORIGIN = _mod12580.SEMANTIC_ATTRIBUTE_SENTRY_ORIGIN;
export const SEMANTIC_ATTRIBUTE_SENTRY_SAMPLE_RATE = _mod12580.SEMANTIC_ATTRIBUTE_SENTRY_SAMPLE_RATE;
export const SEMANTIC_ATTRIBUTE_SENTRY_SOURCE = _mod12580.SEMANTIC_ATTRIBUTE_SENTRY_SOURCE;
export const SEMANTIC_ATTRIBUTE_URL_FULL = _mod12580.SEMANTIC_ATTRIBUTE_URL_FULL;
export const createEventEnvelope = _mod12608.createEventEnvelope;
export const createSessionEnvelope = _mod12608.createSessionEnvelope;
export const createSpanEnvelope = _mod12608.createSpanEnvelope;
export const addEventProcessor = _flush.addEventProcessor;
export const captureCheckIn = _flush.captureCheckIn;
export const captureEvent = _flush.captureEvent;
export const captureException = _flush.captureException;
export const captureMessage = _flush.captureMessage;
export const captureSession = _flush.captureSession;
export const close = _flush.close;
export const endSession = _flush.endSession;
export const flush = _flush.flush;
export const isEnabled = _flush.isEnabled;
export const isInitialized = _flush.isInitialized;
export const lastEventId = _flush.lastEventId;
export const setContext = _flush.setContext;
export const setExtra = _flush.setExtra;
export const setExtras = _flush.setExtras;
export const setTag = _flush.setTag;
export const setTags = _flush.setTags;
export const setUser = _flush.setUser;
export const startSession = _flush.startSession;
export const withMonitor = _flush.withMonitor;
export const getClient = _mod12592.getClient;
export const getCurrentScope = _mod12592.getCurrentScope;
export const getGlobalScope = _mod12592.getGlobalScope;
export const getIsolationScope = _mod12592.getIsolationScope;
export const getTraceContextFromScope = _mod12592.getTraceContextFromScope;
export const withIsolationScope = _mod12592.withIsolationScope;
export const withScope = _mod12592.withScope;
export const getDefaultCurrentScope = _mod12591.getDefaultCurrentScope;
export const getDefaultIsolationScope = _mod12591.getDefaultIsolationScope;
export const setAsyncContextStrategy = _mod12584.setAsyncContextStrategy;
export const getMainCarrier = _mod12583.getMainCarrier;
export const closeSession = _mod12588.closeSession;
export const makeSession = _mod12588.makeSession;
export const updateSession = _mod12588.updateSession;
export const SessionFlusher = SessionFlusher.SessionFlusher;
export const Scope = ScopeClass.Scope;
export const notifyEventProcessors = notifyEventProcessors.notifyEventProcessors;
export const getEnvelopeEndpointWithUrlEncodedAuth = _mod12619.getEnvelopeEndpointWithUrlEncodedAuth;
export const getReportDialogEndpoint = _mod12619.getReportDialogEndpoint;
export const BaseClient = _mod12620.BaseClient;
export const ServerRuntimeClient = _mod12624.ServerRuntimeClient;
export const initAndBind = _mod12627.initAndBind;
export const setCurrentClient = _mod12627.setCurrentClient;
export const createTransport = _mod12628.createTransport;
export const makeOfflineTransport = _mod12631.makeOfflineTransport;
export const makeMultiplexedTransport = _mod12632.makeMultiplexedTransport;
export const addIntegration = _mod12621.addIntegration;
export const defineIntegration = _mod12621.defineIntegration;
export const getIntegrationsToSetup = _mod12621.getIntegrationsToSetup;
export const applyScopeDataToEvent = applyScopeDataToEvent.applyScopeDataToEvent;
export const mergeScopeData = applyScopeDataToEvent.mergeScopeData;
export const prepareEvent = _mod12614.prepareEvent;
export const createCheckInEnvelope = _mod12626.createCheckInEnvelope;
export const hasTracingEnabled = _mod12597.hasTracingEnabled;
export const isSentryRequestUrl = _mod12633.isSentryRequestUrl;
export const handleCallbackErrors = _mod12600.handleCallbackErrors;
export const parameterize = _mod12634.parameterize;
export const addChildSpanToSpan = spanTimeInputToSeconds.addChildSpanToSpan;
export const getActiveSpan = spanTimeInputToSeconds.getActiveSpan;
export const getRootSpan = spanTimeInputToSeconds.getRootSpan;
export const getSpanDescendants = spanTimeInputToSeconds.getSpanDescendants;
export const getStatusMessage = spanTimeInputToSeconds.getStatusMessage;
export const spanIsSampled = spanTimeInputToSeconds.spanIsSampled;
export const spanTimeInputToSeconds = spanTimeInputToSeconds.spanTimeInputToSeconds;
export const spanToJSON = spanTimeInputToSeconds.spanToJSON;
export const spanToTraceContext = spanTimeInputToSeconds.spanToTraceContext;
export const spanToTraceHeader = spanTimeInputToSeconds.spanToTraceHeader;
export const updateSpanName = spanTimeInputToSeconds.updateSpanName;
export const parseSampleRate = _mod12605.parseSampleRate;
export const applySdkMetadata = _mod12635.applySdkMetadata;
export const getTraceData = _mod12636.getTraceData;
export const getTraceMetaTags = _mod12637.getTraceMetaTags;
export const DEFAULT_ENVIRONMENT = _mod12602.DEFAULT_ENVIRONMENT;
export const addBreadcrumb = _mod12638.addBreadcrumb;
export const functionToStringIntegration = _mod12639.functionToStringIntegration;
export const inboundFiltersIntegration = _getEventFilterUrl.inboundFiltersIntegration;
export const linkedErrorsIntegration = _mod12641.linkedErrorsIntegration;
export const moduleMetadataIntegration = _mod12643.moduleMetadataIntegration;
export const requestDataIntegration = _mod12645.requestDataIntegration;
export const captureConsoleIntegration = _mod12650.captureConsoleIntegration;
export const debugIntegration = debugIntegration.debugIntegration;
export const dedupeIntegration = _mod12654.dedupeIntegration;
export const extraErrorDataIntegration = extraErrorDataIntegration.extraErrorDataIntegration;
export const rewriteFramesIntegration = _mod12656.rewriteFramesIntegration;
export const sessionTimingIntegration = sessionTimingIntegration.sessionTimingIntegration;
export const zodErrorsIntegration = _mod12659.zodErrorsIntegration;
export const thirdPartyErrorFilterIntegration = _mod12660.thirdPartyErrorFilterIntegration;
export const metrics = _mod12661.metrics;
export const profiler = _mod12663.profiler;
export const metricsDefault = metricsDefault.metricsDefault;
export const BrowserMetricsAggregator = BrowserMetricsAggregator.BrowserMetricsAggregator;
export const getMetricSummaryJsonForSpan = _mod12581.getMetricSummaryJsonForSpan;
export const addTracingHeadersToFetchRequest = _mod12670.addTracingHeadersToFetchRequest;
export const instrumentFetchRequest = _mod12670.instrumentFetchRequest;
export const trpcMiddleware = _mod12671.trpcMiddleware;
export const captureFeedback = _mod12672.captureFeedback;
export const getCurrentHub = _mod12673.getCurrentHub;
export const getCurrentHubShim = _mod12673.getCurrentHubShim;
export const applyAggregateErrorsToEvent = _mod12642.applyAggregateErrorsToEvent;
export const flatten = _mod12674.flatten;
export const getBreadcrumbLogLevelFromHttpStatusCode = _mod12675.getBreadcrumbLogLevelFromHttpStatusCode;
export const getComponentName = _mod12573.getComponentName;
export const getDomElement = _mod12573.getDomElement;
export const getLocationHref = _mod12573.getLocationHref;
export const htmlTreeAsString = _mod12573.htmlTreeAsString;
export const dsnFromString = _mod12612.dsnFromString;
export const dsnToString = _mod12612.dsnToString;
export const makeDsn = _mod12612.makeDsn;
export const SentryError = _mod12622.SentryError;
export const GLOBAL_OBJ = _mod12566.GLOBAL_OBJ;
export const getGlobalSingleton = _mod12566.getGlobalSingleton;
export const addConsoleInstrumentationHandler = _mod12651.addConsoleInstrumentationHandler;
export const addFetchEndInstrumentationHandler = _mod12676.addFetchEndInstrumentationHandler;
export const addFetchInstrumentationHandler = _mod12676.addFetchInstrumentationHandler;
export const addGlobalErrorInstrumentationHandler = _mod12562.addGlobalErrorInstrumentationHandler;
export const addGlobalUnhandledRejectionInstrumentationHandler =
  _mod12569.addGlobalUnhandledRejectionInstrumentationHandler;
export const addHandler = _mod12563.addHandler;
export const maybeInstrument = _mod12563.maybeInstrument;
export const resetInstrumentationHandlers = _mod12563.resetInstrumentationHandlers;
export const triggerHandlers = _mod12563.triggerHandlers;
export const isDOMError = _mod12572.isDOMError;
export const isDOMException = _mod12572.isDOMException;
export const isElement = _mod12572.isElement;
export const isError = _mod12572.isError;
export const isErrorEvent = _mod12572.isErrorEvent;
export const isEvent = _mod12572.isEvent;
export const isInstanceOf = _mod12572.isInstanceOf;
export const isParameterizedString = _mod12572.isParameterizedString;
export const isPlainObject = _mod12572.isPlainObject;
export const isPrimitive = _mod12572.isPrimitive;
export const isRegExp = _mod12572.isRegExp;
export const isString = _mod12572.isString;
export const isSyntheticEvent = _mod12572.isSyntheticEvent;
export const isThenable = _mod12572.isThenable;
export const isVueViewModel = _mod12572.isVueViewModel;
export const isBrowser = _mod12678.isBrowser;
export const CONSOLE_LEVELS = _mod12565.CONSOLE_LEVELS;
export const consoleSandbox = _mod12565.consoleSandbox;
export const logger = _mod12565.logger;
export const originalConsoleMethods = _mod12565.originalConsoleMethods;
export const memoBuilder = memoBuilder.memoBuilder;
export const addContextToFrame = _mod12576.addContextToFrame;
export const addExceptionMechanism = _mod12576.addExceptionMechanism;
export const addExceptionTypeValue = _mod12576.addExceptionTypeValue;
export const arrayify = _mod12576.arrayify;
export const checkOrSetAlreadyCaught = _mod12576.checkOrSetAlreadyCaught;
export const getEventDescription = _mod12576.getEventDescription;
export const parseSemver = _mod12576.parseSemver;
export const uuid4 = _mod12576.uuid4;
export const dynamicRequire = _mod12679.dynamicRequire;
export const isNodeEnv = _mod12679.isNodeEnv;
export const loadModule = _mod12679.loadModule;
export const normalize = _mod12610.normalize;
export const normalizeToSize = _mod12610.normalizeToSize;
export const normalizeUrlToBase = _mod12610.normalizeUrlToBase;
export const addNonEnumerableProperty = _mod12571.addNonEnumerableProperty;
export const convertToPlainObject = _mod12571.convertToPlainObject;
export const dropUndefinedKeys = _mod12571.dropUndefinedKeys;
export const extractExceptionKeysForMessage = _mod12571.extractExceptionKeysForMessage;
export const fill = _mod12571.fill;
export const getOriginalFunction = _mod12571.getOriginalFunction;
export const markFunctionWrapped = _mod12571.markFunctionWrapped;
export const objectify = _mod12571.objectify;
export const urlEncode = _mod12571.urlEncode;
export const basename = _mod12657.basename;
export const dirname = _mod12657.dirname;
export const isAbsolute = _mod12657.isAbsolute;
export const join = _mod12657.join;
export const normalizePath = _mod12657.normalizePath;
export const relative = _mod12657.relative;
export const resolve = _mod12657.resolve;
export const makePromiseBuffer = _mod12629.makePromiseBuffer;
export const DEFAULT_USER_INCLUDES = extractRequestData.DEFAULT_USER_INCLUDES;
export const addNormalizedRequestDataToEvent = extractRequestData.addNormalizedRequestDataToEvent;
export const addRequestDataToEvent = extractRequestData.addRequestDataToEvent;
export const extractPathForTransaction = extractRequestData.extractPathForTransaction;
export const extractQueryParamsFromUrl = extractRequestData.extractQueryParamsFromUrl;
export const extractRequestData = extractRequestData.extractRequestData;
export const headersToDict = extractRequestData.headersToDict;
export const httpRequestToRequestData = extractRequestData.httpRequestToRequestData;
export const winterCGHeadersToDict = extractRequestData.winterCGHeadersToDict;
export const winterCGRequestToRequestData = extractRequestData.winterCGRequestToRequestData;
export const severityLevelFromString = _mod12652.severityLevelFromString;
export const validSeverityLevels = _mod12652.validSeverityLevels;
export const UNKNOWN_FUNCTION = stackParserFromStackParserOptions.UNKNOWN_FUNCTION;
export const createStackParser = stackParserFromStackParserOptions.createStackParser;
export const getFramesFromEvent = stackParserFromStackParserOptions.getFramesFromEvent;
export const getFunctionName = stackParserFromStackParserOptions.getFunctionName;
export const stackParserFromStackParserOptions = stackParserFromStackParserOptions.stackParserFromStackParserOptions;
export const stripSentryFramesAndReverse = stackParserFromStackParserOptions.stripSentryFramesAndReverse;
export const filenameIsInApp = _mod12681.filenameIsInApp;
export const node = _mod12681.node;
export const nodeStackLineParser = _mod12681.nodeStackLineParser;
export const isMatchingPattern = _mod12574.isMatchingPattern;
export const safeJoin = _mod12574.safeJoin;
export const snipLine = _mod12574.snipLine;
export const stringMatchesSomePattern = _mod12574.stringMatchesSomePattern;
export const truncate = _mod12574.truncate;
export const isNativeFunction = supportsFetch.isNativeFunction;
export const supportsDOMError = supportsFetch.supportsDOMError;
export const supportsDOMException = supportsFetch.supportsDOMException;
export const supportsErrorEvent = supportsFetch.supportsErrorEvent;
export const supportsFetch = supportsFetch.supportsFetch;
export const supportsNativeFetch = supportsFetch.supportsNativeFetch;
export const supportsReferrerPolicy = supportsFetch.supportsReferrerPolicy;
export const supportsReportingObserver = supportsFetch.supportsReportingObserver;
export const SyncPromise = _mod12589.SyncPromise;
export const rejectedSyncPromise = _mod12589.rejectedSyncPromise;
export const resolvedSyncPromise = _mod12589.resolvedSyncPromise;
export const _browserPerformanceTimeOriginMode = require("12579__.js")._browserPerformanceTimeOriginMode;
export const browserPerformanceTimeOrigin = require("12579__.js").browserPerformanceTimeOrigin;
export const dateTimestampInSeconds = require("12579__.js").dateTimestampInSeconds;
export const timestampInSeconds = require("12579__.js").timestampInSeconds;
export const TRACEPARENT_REGEXP = _mod12577.TRACEPARENT_REGEXP;
export const extractTraceparentData = _mod12577.extractTraceparentData;
export const generateSentryTraceHeader = _mod12577.generateSentryTraceHeader;
export const propagationContextFromHeaders = _mod12577.propagationContextFromHeaders;
export const getSDKSource = _mod12680.getSDKSource;
export const isBrowserBundle = _mod12680.isBrowserBundle;
export const addItemToEnvelope = _mod12609.addItemToEnvelope;
export const createAttachmentEnvelopeItem = _mod12609.createAttachmentEnvelopeItem;
export const createEnvelope = _mod12609.createEnvelope;
export const createEventEnvelopeHeaders = _mod12609.createEventEnvelopeHeaders;
export const createSpanEnvelopeItem = _mod12609.createSpanEnvelopeItem;
export const envelopeContainsItemType = _mod12609.envelopeContainsItemType;
export const envelopeItemTypeToDataCategory = _mod12609.envelopeItemTypeToDataCategory;
export const forEachEnvelopeItem = _mod12609.forEachEnvelopeItem;
export const getSdkMetadataForEnvelopeHeader = _mod12609.getSdkMetadataForEnvelopeHeader;
export const parseEnvelope = _mod12609.parseEnvelope;
export const serializeEnvelope = _mod12609.serializeEnvelope;
export const createClientReportEnvelope = _mod12623.createClientReportEnvelope;
export const DEFAULT_RETRY_AFTER = _mod12630.DEFAULT_RETRY_AFTER;
export const disabledUntil = _mod12630.disabledUntil;
export const isRateLimited = _mod12630.isRateLimited;
export const parseRetryAfterHeader = _mod12630.parseRetryAfterHeader;
export const updateRateLimits = _mod12630.updateRateLimits;
export const BAGGAGE_HEADER_NAME = BAGGAGE_HEADER_NAME.BAGGAGE_HEADER_NAME;
export const MAX_BAGGAGE_STRING_LENGTH = BAGGAGE_HEADER_NAME.MAX_BAGGAGE_STRING_LENGTH;
export const SENTRY_BAGGAGE_KEY_PREFIX = BAGGAGE_HEADER_NAME.SENTRY_BAGGAGE_KEY_PREFIX;
export const SENTRY_BAGGAGE_KEY_PREFIX_REGEX = BAGGAGE_HEADER_NAME.SENTRY_BAGGAGE_KEY_PREFIX_REGEX;
export const baggageHeaderToDynamicSamplingContext = BAGGAGE_HEADER_NAME.baggageHeaderToDynamicSamplingContext;
export const dynamicSamplingContextToSentryBaggageHeader =
  BAGGAGE_HEADER_NAME.dynamicSamplingContextToSentryBaggageHeader;
export const parseBaggageHeader = BAGGAGE_HEADER_NAME.parseBaggageHeader;
export const getNumberOfUrlSegments = stripUrlQueryAndFragment.getNumberOfUrlSegments;
export const getSanitizedUrlString = stripUrlQueryAndFragment.getSanitizedUrlString;
export const parseUrl = stripUrlQueryAndFragment.parseUrl;
export const stripUrlQueryAndFragment = stripUrlQueryAndFragment.stripUrlQueryAndFragment;
export const makeFifoCache = _mod12682.makeFifoCache;
export const eventFromMessage = eventFromMessage.eventFromMessage;
export const eventFromUnknownInput = eventFromMessage.eventFromUnknownInput;
export const exceptionFromError = eventFromMessage.exceptionFromError;
export const parseStackFrames = eventFromMessage.parseStackFrames;
export const callFrameToStackFrame = _mod12683.callFrameToStackFrame;
export const watchdogTimer = _mod12683.watchdogTimer;
export const LRUMap = _mod12684.LRUMap;
export const generatePropagationContext = generatePropagationContext.generatePropagationContext;
export const generateSpanId = generatePropagationContext.generateSpanId;
export const generateTraceId = generatePropagationContext.generateTraceId;
export const vercelWaitUntil = _mod12685.vercelWaitUntil;
export const SDK_VERSION = _mod12567.SDK_VERSION;
export const getDebugImagesForResources = _mod12617.getDebugImagesForResources;
export const getFilenameToDebugIdMap = _mod12617.getFilenameToDebugIdMap;
export const escapeStringForRegex = _mod12686.escapeStringForRegex;
export const supportsHistory = supportsHistory.supportsHistory;
export const _asyncNullishCoalesce = _asyncNullishCoalesce2._asyncNullishCoalesce;
export const _asyncOptionalChain = _asyncOptionalChain2._asyncOptionalChain;
export const _asyncOptionalChainDelete = _asyncOptionalChainDelete2._asyncOptionalChainDelete;
export const _nullishCoalesce = _nullishCoalesce._nullishCoalesce;
export const _optionalChain = _optionalChain._optionalChain;
export const _optionalChainDelete = _optionalChainDelete._optionalChainDelete;
