// _runtime/metro/12560__.js
import _mod12561 from "12561__.js";
import _mod12562 from "12562__.js";
import _mod12563 from "12563__.js";
import _mod12565 from "12565__.js";
import _mod12566 from "12566__.js";
import _mod12567 from "12567__.js";
import _mod12568 from "12568__.js";
import _mod12569 from "12569__.js";
import _mod12570 from "12570__.js";
import _mod12571 from "12571__.js";
import _mod12572 from "12572__.js";
import htmlTreeAsString from "../12573_htmlTreeAsString.js";
import _mod12574 from "12574__.js";
import generatePropagationContext from "../12575_generatePropagationContext.js";
import _mod12576 from "12576__.js";
import _mod12577 from "12577__.js";
import BAGGAGE_HEADER_NAME from "../12578_BAGGAGE_HEADER_NAME.js";
import _mod12580 from "12580__.js";
import _slicedToArray from "12581__slicedToArray.js";
import _mod12582 from "12582__.js";
import _mod12583 from "12583__.js";
import _mod12584 from "12584__.js";
import _mod12586 from "12586__.js";
import _mod12588 from "12588__.js";
import _mod12589 from "12589__.js";
import _mod12591 from "12591__.js";
import _mod12592 from "12592__.js";
import _mod12594 from "12594__.js";
import _mod12595 from "12595__.js";
import _mod12596 from "12596__.js";
import _mod12597 from "12597__.js";
import _mod12598 from "12598__.js";
import _mod12599 from "12599__.js";
import _mod12600 from "12600__.js";
import _mod12601 from "12601__.js";
import _mod12602 from "12602__.js";
import _mod12603 from "12603__.js";
import _mod12604 from "12604__.js";
import _mod12605 from "12605__.js";
import _mod12606 from "12606__.js";
import _mod12607 from "12607__.js";
import _mod12608 from "12608__.js";
import _mod12609 from "12609__.js";
import _mod12610 from "12610__.js";
import memoBuilder from "../12611_memoBuilder.js";
import _mod12612 from "12612__.js";
import _mod12613 from "12613__.js";
import _mod12614 from "12614__.js";
import _mod12615 from "12615__.js";
import _mod12616 from "12616__.js";
import _mod12617 from "12617__.js";
import SessionFlusher from "../12618_SessionFlusher.js";
import _mod12619 from "12619__.js";
import BaseClient from "../12620_BaseClient.js";
import _mod12621 from "12621__.js";
import _mod12622 from "12622__.js";
import _mod12623 from "12623__.js";
import _mod12624 from "12624__.js";
import eventFromMessage from "../12625_eventFromMessage.js";
import _mod12626 from "12626__.js";
import _mod12627 from "12627__.js";
import _mod12628 from "12628__.js";
import _mod12629 from "12629__.js";
import _slicedToArray2 from "12630__slicedToArray.js";
import _mod12631 from "12631__.js";
import eventFromEnvelope from "../12632_eventFromEnvelope.js";
import _mod12633 from "12633__.js";
import _mod12634 from "12634__.js";
import _mod12635 from "12635__.js";
import _mod12636 from "12636__.js";
import _mod12637 from "12637__.js";
import _mod12638 from "12638__.js";
import _mod12639 from "12639__.js";
import inboundFiltersIntegration from "../12640_inboundFiltersIntegration.js";
import _mod12641 from "12641__.js";
import _mod12642 from "12642__.js";
import _mod12643 from "12643__.js";
import _mod12645 from "12645__.js";
import DEFAULT_USER_INCLUDES from "../12646_DEFAULT_USER_INCLUDES.js";
import stripUrlQueryAndFragment from "../12647_stripUrlQueryAndFragment.js";
import _mod12650 from "12650__.js";
import _mod12651 from "12651__.js";
import _mod12652 from "12652__.js";
import debugIntegration from "../12653_debugIntegration.js";
import _mod12654 from "12654__.js";
import _mod12655 from "12655__.js";
import _mod12656 from "12656__.js";
import _mod12657 from "12657__.js";
import sessionTimingIntegration from "../12658_sessionTimingIntegration.js";
import _mod12659 from "12659__.js";
import _mod12660 from "12660__.js";
import metrics from "../12661_metrics.js";
import _mod12663 from "12663__.js";
import metricsDefault from "../12664_metricsDefault.js";
import BrowserMetricsAggregator from "../12669_BrowserMetricsAggregator.js";
import instrumentFetchRequest from "../12670_instrumentFetchRequest.js";
import _mod12671 from "12671__.js";
import _mod12672 from "12672__.js";
import _mod12673 from "12673__.js";
import _mod12674 from "12674__.js";
import _mod12675 from "12675__.js";
import _mod12676 from "12676__.js";
import _mod12677 from "12677__.js";
import dynamicRequire from "../12678_dynamicRequire.js";
import _mod12679 from "12679__.js";
import _mod12680 from "12680__.js";
import _mod12681 from "12681__.js";
import _mod12682 from "12682__.js";
import _mod12683 from "12683__.js";
import _mod12684 from "12684__.js";
import _mod12685 from "12685__.js";
import _mod12686 from "12686__.js";
import supportsHistory from "../12687_supportsHistory.js";
import _asyncToGenerator from "12688__asyncToGenerator.js";
import _nullishCoalesce from "../12689__nullishCoalesce.js";
import _asyncToGenerator2 from "12690__asyncToGenerator.js";
import _asyncToGenerator3 from "12691__asyncToGenerator.js";
import _optionalChain from "../12692__optionalChain.js";
import _optionalChainDelete from "../12693__optionalChainDelete.js";

const require = globalThis.__r;

const SessionFlusher_export = SessionFlusher.SessionFlusher;
const BaseClient_export = BaseClient.BaseClient;
const inboundFiltersIntegration_export = inboundFiltersIntegration.inboundFiltersIntegration;
const debugIntegration_export = debugIntegration.debugIntegration;
const sessionTimingIntegration_export = sessionTimingIntegration.sessionTimingIntegration;
const metrics_export = metrics.metrics;
const metricsDefault_export = metricsDefault.metricsDefault;
const BrowserMetricsAggregator_export = BrowserMetricsAggregator.BrowserMetricsAggregator;
const instrumentFetchRequest_export = instrumentFetchRequest.instrumentFetchRequest;
const htmlTreeAsString_export = htmlTreeAsString.htmlTreeAsString;
const memoBuilder_export = memoBuilder.memoBuilder;
const dynamicRequire_export = _mod12679.dynamicRequire;
const DEFAULT_USER_INCLUDES_export = DEFAULT_USER_INCLUDES.DEFAULT_USER_INCLUDES;
const BAGGAGE_HEADER_NAME_export = BAGGAGE_HEADER_NAME.BAGGAGE_HEADER_NAME;
const stripUrlQueryAndFragment_export = stripUrlQueryAndFragment.stripUrlQueryAndFragment;
const eventFromMessage_export = eventFromMessage.eventFromMessage;
const generatePropagationContext_export = generatePropagationContext.generatePropagationContext;
const supportsHistory_export = supportsHistory.supportsHistory;
const _nullishCoalesce_export = _nullishCoalesce._nullishCoalesce;
const _optionalChain_export = _optionalChain._optionalChain;
const _optionalChainDelete_export = _optionalChainDelete._optionalChainDelete;

export const registerSpanErrorInstrumentation = _mod12561.registerSpanErrorInstrumentation;
export const getCapturedScopesOnSpan = _mod12594.getCapturedScopesOnSpan;
export const setCapturedScopesOnSpan = _mod12594.setCapturedScopesOnSpan;
export const addTracingExtensions = _mod12595.addTracingExtensions;
export const TRACING_DEFAULTS = _mod12596.TRACING_DEFAULTS;
export const startIdleSpan = _mod12596.startIdleSpan;
export const SentrySpan = _mod12606.SentrySpan;
export const SentryNonRecordingSpan = _mod12598.SentryNonRecordingSpan;
export const SPAN_STATUS_ERROR = _mod12582.SPAN_STATUS_ERROR;
export const SPAN_STATUS_OK = _mod12582.SPAN_STATUS_OK;
export const SPAN_STATUS_UNSET = _mod12582.SPAN_STATUS_UNSET;
export const getSpanStatusFromHttpCode = _mod12582.getSpanStatusFromHttpCode;
export const setHttpStatus = _mod12582.setHttpStatus;
export const continueTrace = _mod12599.continueTrace;
export const startInactiveSpan = _mod12599.startInactiveSpan;
export const startNewTrace = _mod12599.startNewTrace;
export const startSpan = _mod12599.startSpan;
export const startSpanManual = _mod12599.startSpanManual;
export const suppressTracing = _mod12599.suppressTracing;
export const withActiveSpan = _mod12599.withActiveSpan;
export const getDynamicSamplingContextFromClient = _mod12601.getDynamicSamplingContextFromClient;
export const getDynamicSamplingContextFromScope = _mod12601.getDynamicSamplingContextFromScope;
export const getDynamicSamplingContextFromSpan = _mod12601.getDynamicSamplingContextFromSpan;
export const spanToBaggageHeader = _mod12601.spanToBaggageHeader;
export const setMeasurement = _mod12607.setMeasurement;
export const timedEventsToMeasurements = _mod12607.timedEventsToMeasurements;
export const sampleSpan = _mod12604.sampleSpan;
export const logSpanEnd = _mod12603.logSpanEnd;
export const logSpanStart = _mod12603.logSpanStart;
export const SEMANTIC_ATTRIBUTE_CACHE_HIT = _mod12580.SEMANTIC_ATTRIBUTE_CACHE_HIT;
export const SEMANTIC_ATTRIBUTE_CACHE_ITEM_SIZE = _mod12580.SEMANTIC_ATTRIBUTE_CACHE_ITEM_SIZE;
export const SEMANTIC_ATTRIBUTE_CACHE_KEY = _mod12580.SEMANTIC_ATTRIBUTE_CACHE_KEY;
export const SEMANTIC_ATTRIBUTE_EXCLUSIVE_TIME = _mod12580.SEMANTIC_ATTRIBUTE_EXCLUSIVE_TIME;
export const SEMANTIC_ATTRIBUTE_HTTP_REQUEST_METHOD = _mod12580.SEMANTIC_ATTRIBUTE_HTTP_REQUEST_METHOD;
export const SEMANTIC_ATTRIBUTE_PROFILE_ID = _mod12580.SEMANTIC_ATTRIBUTE_PROFILE_ID;
export const SEMANTIC_ATTRIBUTE_SENTRY_CUSTOM_SPAN_NAME = _mod12580.SEMANTIC_ATTRIBUTE_SENTRY_CUSTOM_SPAN_NAME;
export const SEMANTIC_ATTRIBUTE_SENTRY_IDLE_SPAN_FINISH_REASON =
  _mod12580.SEMANTIC_ATTRIBUTE_SENTRY_IDLE_SPAN_FINISH_REASON;
export const SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_UNIT = _mod12580.SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_UNIT;
export const SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_VALUE = _mod12580.SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_VALUE;
export const SEMANTIC_ATTRIBUTE_SENTRY_OP = _mod12580.SEMANTIC_ATTRIBUTE_SENTRY_OP;
export const SEMANTIC_ATTRIBUTE_SENTRY_ORIGIN = _mod12580.SEMANTIC_ATTRIBUTE_SENTRY_ORIGIN;
export const SEMANTIC_ATTRIBUTE_SENTRY_SAMPLE_RATE = _mod12580.SEMANTIC_ATTRIBUTE_SENTRY_SAMPLE_RATE;
export const SEMANTIC_ATTRIBUTE_SENTRY_SOURCE = _mod12580.SEMANTIC_ATTRIBUTE_SENTRY_SOURCE;
export const SEMANTIC_ATTRIBUTE_URL_FULL = _mod12580.SEMANTIC_ATTRIBUTE_URL_FULL;
export const createEventEnvelope = _mod12608.createEventEnvelope;
export const createSessionEnvelope = _mod12608.createSessionEnvelope;
export const createSpanEnvelope = _mod12608.createSpanEnvelope;
export const addEventProcessor = _mod12613.addEventProcessor;
export const captureCheckIn = _mod12613.captureCheckIn;
export const captureEvent = _mod12613.captureEvent;
export const captureException = _mod12613.captureException;
export const captureMessage = _mod12613.captureMessage;
export const captureSession = _mod12613.captureSession;
export const close = _mod12613.close;
export const endSession = _mod12613.endSession;
export const flush = _mod12613.flush;
export const isEnabled = _mod12613.isEnabled;
export const isInitialized = _mod12613.isInitialized;
export const lastEventId = _mod12613.lastEventId;
export const setContext = _mod12613.setContext;
export const setExtra = _mod12613.setExtra;
export const setExtras = _mod12613.setExtras;
export const setTag = _mod12613.setTag;
export const setTags = _mod12613.setTags;
export const setUser = _mod12613.setUser;
export const startSession = _mod12613.startSession;
export const withMonitor = _mod12613.withMonitor;
export const getClient = _mod12592.getClient;
export const getCurrentScope = _mod12592.getCurrentScope;
export const getGlobalScope = _mod12592.getGlobalScope;
export const getIsolationScope = _mod12592.getIsolationScope;
export const getTraceContextFromScope = _mod12592.getTraceContextFromScope;
export const withIsolationScope = _mod12592.withIsolationScope;
export const withScope = _mod12592.withScope;
export const getDefaultCurrentScope = _mod12591.getDefaultCurrentScope;
export const getDefaultIsolationScope = _mod12591.getDefaultIsolationScope;
export const setAsyncContextStrategy = _mod12584.setAsyncContextStrategy;
export const getMainCarrier = _mod12583.getMainCarrier;
export const closeSession = _mod12588.closeSession;
export const makeSession = _mod12588.makeSession;
export const updateSession = _mod12588.updateSession;
export { SessionFlusher_export as SessionFlusher };
export const Scope = _mod12586.Scope;
export const notifyEventProcessors = _mod12616.notifyEventProcessors;
export const getEnvelopeEndpointWithUrlEncodedAuth = _mod12619.getEnvelopeEndpointWithUrlEncodedAuth;
export const getReportDialogEndpoint = _mod12619.getReportDialogEndpoint;
export { BaseClient_export as BaseClient };
export const ServerRuntimeClient = _mod12624.ServerRuntimeClient;
export const initAndBind = _mod12627.initAndBind;
export const setCurrentClient = _mod12627.setCurrentClient;
export const createTransport = _mod12628.createTransport;
export const makeOfflineTransport = _mod12631.makeOfflineTransport;
export const makeMultiplexedTransport = eventFromEnvelope.makeMultiplexedTransport;
export const addIntegration = _mod12621.addIntegration;
export const defineIntegration = _mod12621.defineIntegration;
export const getIntegrationsToSetup = _mod12621.getIntegrationsToSetup;
export const applyScopeDataToEvent = _mod12615.applyScopeDataToEvent;
export const mergeScopeData = _mod12615.mergeScopeData;
export const prepareEvent = _mod12614.prepareEvent;
export const createCheckInEnvelope = _mod12626.createCheckInEnvelope;
export const hasTracingEnabled = _mod12597.hasTracingEnabled;
export const isSentryRequestUrl = _mod12633.isSentryRequestUrl;
export const handleCallbackErrors = _mod12600.handleCallbackErrors;
export const parameterize = _mod12634.parameterize;
export const addChildSpanToSpan = _mod12570.addChildSpanToSpan;
export const getActiveSpan = _mod12570.getActiveSpan;
export const getRootSpan = _mod12570.getRootSpan;
export const getSpanDescendants = _mod12570.getSpanDescendants;
export const getStatusMessage = _mod12570.getStatusMessage;
export const spanIsSampled = _mod12570.spanIsSampled;
export const spanTimeInputToSeconds = _mod12570.spanTimeInputToSeconds;
export const spanToJSON = _mod12570.spanToJSON;
export const spanToTraceContext = _mod12570.spanToTraceContext;
export const spanToTraceHeader = _mod12570.spanToTraceHeader;
export const updateSpanName = _mod12570.updateSpanName;
export const parseSampleRate = _mod12605.parseSampleRate;
export const applySdkMetadata = _mod12635.applySdkMetadata;
export const getTraceData = _mod12636.getTraceData;
export const getTraceMetaTags = _mod12637.getTraceMetaTags;
export const DEFAULT_ENVIRONMENT = _mod12602.DEFAULT_ENVIRONMENT;
export const addBreadcrumb = _mod12638.addBreadcrumb;
export const functionToStringIntegration = _mod12639.functionToStringIntegration;
export { inboundFiltersIntegration_export as inboundFiltersIntegration };
export const linkedErrorsIntegration = _mod12641.linkedErrorsIntegration;
export const moduleMetadataIntegration = _mod12643.moduleMetadataIntegration;
export const requestDataIntegration = _mod12645.requestDataIntegration;
export const captureConsoleIntegration = _mod12650.captureConsoleIntegration;
export { debugIntegration_export as debugIntegration };
export const dedupeIntegration = _mod12654.dedupeIntegration;
export const extraErrorDataIntegration = _mod12655.extraErrorDataIntegration;
export const rewriteFramesIntegration = _mod12656.rewriteFramesIntegration;
export { sessionTimingIntegration_export as sessionTimingIntegration };
export const zodErrorsIntegration = _mod12659.zodErrorsIntegration;
export const thirdPartyErrorFilterIntegration = _mod12660.thirdPartyErrorFilterIntegration;
export { metrics_export as metrics };
export const profiler = _mod12663.profiler;
export { metricsDefault_export as metricsDefault };
export { BrowserMetricsAggregator_export as BrowserMetricsAggregator };
export const getMetricSummaryJsonForSpan = _slicedToArray.getMetricSummaryJsonForSpan;
export const addTracingHeadersToFetchRequest = instrumentFetchRequest.addTracingHeadersToFetchRequest;
export { instrumentFetchRequest_export as instrumentFetchRequest };
export const trpcMiddleware = _mod12671.trpcMiddleware;
export const captureFeedback = _mod12672.captureFeedback;
export const getCurrentHub = _mod12673.getCurrentHub;
export const getCurrentHubShim = _mod12673.getCurrentHubShim;
export const applyAggregateErrorsToEvent = _mod12642.applyAggregateErrorsToEvent;
export const flatten = _mod12674.flatten;
export const getBreadcrumbLogLevelFromHttpStatusCode = _mod12675.getBreadcrumbLogLevelFromHttpStatusCode;
export const getComponentName = htmlTreeAsString.getComponentName;
export const getDomElement = htmlTreeAsString.getDomElement;
export const getLocationHref = htmlTreeAsString.getLocationHref;
export { htmlTreeAsString_export as htmlTreeAsString };
export const dsnFromString = _mod12612.dsnFromString;
export const dsnToString = _mod12612.dsnToString;
export const makeDsn = _mod12612.makeDsn;
export const SentryError = _mod12622.SentryError;
export const GLOBAL_OBJ = _mod12566.GLOBAL_OBJ;
export const getGlobalSingleton = _mod12566.getGlobalSingleton;
export const addConsoleInstrumentationHandler = _mod12651.addConsoleInstrumentationHandler;
export const addFetchEndInstrumentationHandler = _mod12676.addFetchEndInstrumentationHandler;
export const addFetchInstrumentationHandler = _mod12676.addFetchInstrumentationHandler;
export const addGlobalErrorInstrumentationHandler = _mod12562.addGlobalErrorInstrumentationHandler;
export const addGlobalUnhandledRejectionInstrumentationHandler =
  _mod12569.addGlobalUnhandledRejectionInstrumentationHandler;
export const addHandler = _mod12563.addHandler;
export const maybeInstrument = _mod12563.maybeInstrument;
export const resetInstrumentationHandlers = _mod12563.resetInstrumentationHandlers;
export const triggerHandlers = _mod12563.triggerHandlers;
export const isDOMError = _mod12572.isDOMError;
export const isDOMException = _mod12572.isDOMException;
export const isElement = _mod12572.isElement;
export const isError = _mod12572.isError;
export const isErrorEvent = _mod12572.isErrorEvent;
export const isEvent = _mod12572.isEvent;
export const isInstanceOf = _mod12572.isInstanceOf;
export const isParameterizedString = _mod12572.isParameterizedString;
export const isPlainObject = _mod12572.isPlainObject;
export const isPrimitive = _mod12572.isPrimitive;
export const isRegExp = _mod12572.isRegExp;
export const isString = _mod12572.isString;
export const isSyntheticEvent = _mod12572.isSyntheticEvent;
export const isThenable = _mod12572.isThenable;
export const isVueViewModel = _mod12572.isVueViewModel;
export const isBrowser = dynamicRequire.isBrowser;
export const CONSOLE_LEVELS = _mod12565.CONSOLE_LEVELS;
export const consoleSandbox = _mod12565.consoleSandbox;
export const logger = _mod12565.logger;
export const originalConsoleMethods = _mod12565.originalConsoleMethods;
export { memoBuilder_export as memoBuilder };
export const addContextToFrame = _mod12576.addContextToFrame;
export const addExceptionMechanism = _mod12576.addExceptionMechanism;
export const addExceptionTypeValue = _mod12576.addExceptionTypeValue;
export const arrayify = _mod12576.arrayify;
export const checkOrSetAlreadyCaught = _mod12576.checkOrSetAlreadyCaught;
export const getEventDescription = _mod12576.getEventDescription;
export const parseSemver = _mod12576.parseSemver;
export const uuid4 = _mod12576.uuid4;
export { dynamicRequire_export as dynamicRequire };
export const isNodeEnv = _mod12679.isNodeEnv;
export const loadModule = _mod12679.loadModule;
export const normalize = _mod12610.normalize;
export const normalizeToSize = _mod12610.normalizeToSize;
export const normalizeUrlToBase = _mod12610.normalizeUrlToBase;
export const addNonEnumerableProperty = _mod12571.addNonEnumerableProperty;
export const convertToPlainObject = _mod12571.convertToPlainObject;
export const dropUndefinedKeys = _mod12571.dropUndefinedKeys;
export const extractExceptionKeysForMessage = _mod12571.extractExceptionKeysForMessage;
export const fill = _mod12571.fill;
export const getOriginalFunction = _mod12571.getOriginalFunction;
export const markFunctionWrapped = _mod12571.markFunctionWrapped;
export const objectify = _mod12571.objectify;
export const urlEncode = _mod12571.urlEncode;
export const basename = _mod12657.basename;
export const dirname = _mod12657.dirname;
export const isAbsolute = _mod12657.isAbsolute;
export const join = _mod12657.join;
export const normalizePath = _mod12657.normalizePath;
export const relative = _mod12657.relative;
export const resolve = _mod12657.resolve;
export const makePromiseBuffer = _mod12629.makePromiseBuffer;
export { DEFAULT_USER_INCLUDES_export as DEFAULT_USER_INCLUDES };
export const addNormalizedRequestDataToEvent = DEFAULT_USER_INCLUDES.addNormalizedRequestDataToEvent;
export const addRequestDataToEvent = DEFAULT_USER_INCLUDES.addRequestDataToEvent;
export const extractPathForTransaction = DEFAULT_USER_INCLUDES.extractPathForTransaction;
export const extractQueryParamsFromUrl = DEFAULT_USER_INCLUDES.extractQueryParamsFromUrl;
export const extractRequestData = DEFAULT_USER_INCLUDES.extractRequestData;
export const headersToDict = DEFAULT_USER_INCLUDES.headersToDict;
export const httpRequestToRequestData = DEFAULT_USER_INCLUDES.httpRequestToRequestData;
export const winterCGHeadersToDict = DEFAULT_USER_INCLUDES.winterCGHeadersToDict;
export const winterCGRequestToRequestData = DEFAULT_USER_INCLUDES.winterCGRequestToRequestData;
export const severityLevelFromString = _mod12652.severityLevelFromString;
export const validSeverityLevels = _mod12652.validSeverityLevels;
export const UNKNOWN_FUNCTION = _mod12568.UNKNOWN_FUNCTION;
export const createStackParser = _mod12568.createStackParser;
export const getFramesFromEvent = _mod12568.getFramesFromEvent;
export const getFunctionName = _mod12568.getFunctionName;
export const stackParserFromStackParserOptions = _mod12568.stackParserFromStackParserOptions;
export const stripSentryFramesAndReverse = _mod12568.stripSentryFramesAndReverse;
export const filenameIsInApp = _mod12681.filenameIsInApp;
export const node = _mod12681.node;
export const nodeStackLineParser = _mod12681.nodeStackLineParser;
export const isMatchingPattern = _mod12574.isMatchingPattern;
export const safeJoin = _mod12574.safeJoin;
export const snipLine = _mod12574.snipLine;
export const stringMatchesSomePattern = _mod12574.stringMatchesSomePattern;
export const truncate = _mod12574.truncate;
export const isNativeFunction = _mod12677.isNativeFunction;
export const supportsDOMError = _mod12677.supportsDOMError;
export const supportsDOMException = _mod12677.supportsDOMException;
export const supportsErrorEvent = _mod12677.supportsErrorEvent;
export const supportsFetch = _mod12677.supportsFetch;
export const supportsNativeFetch = _mod12677.supportsNativeFetch;
export const supportsReferrerPolicy = _mod12677.supportsReferrerPolicy;
export const supportsReportingObserver = _mod12677.supportsReportingObserver;
export const SyncPromise = _mod12589.SyncPromise;
export const rejectedSyncPromise = _mod12589.rejectedSyncPromise;
export const resolvedSyncPromise = _mod12589.resolvedSyncPromise;
export const _browserPerformanceTimeOriginMode =
  require("_browserPerformanceTimeOriginMode")._browserPerformanceTimeOriginMode;
export { browserPerformanceTimeOrigin } from "_browserPerformanceTimeOriginMode";
export { dateTimestampInSeconds } from "_browserPerformanceTimeOriginMode";
export { timestampInSeconds } from "_browserPerformanceTimeOriginMode";
export const TRACEPARENT_REGEXP = _mod12577.TRACEPARENT_REGEXP;
export const extractTraceparentData = _mod12577.extractTraceparentData;
export const generateSentryTraceHeader = _mod12577.generateSentryTraceHeader;
export const propagationContextFromHeaders = _mod12577.propagationContextFromHeaders;
export const getSDKSource = _mod12680.getSDKSource;
export const isBrowserBundle = _mod12680.isBrowserBundle;
export const addItemToEnvelope = _mod12609.addItemToEnvelope;
export const createAttachmentEnvelopeItem = _mod12609.createAttachmentEnvelopeItem;
export const createEnvelope = _mod12609.createEnvelope;
export const createEventEnvelopeHeaders = _mod12609.createEventEnvelopeHeaders;
export const createSpanEnvelopeItem = _mod12609.createSpanEnvelopeItem;
export const envelopeContainsItemType = _mod12609.envelopeContainsItemType;
export const envelopeItemTypeToDataCategory = _mod12609.envelopeItemTypeToDataCategory;
export const forEachEnvelopeItem = _mod12609.forEachEnvelopeItem;
export const getSdkMetadataForEnvelopeHeader = _mod12609.getSdkMetadataForEnvelopeHeader;
export const parseEnvelope = _mod12609.parseEnvelope;
export const serializeEnvelope = _mod12609.serializeEnvelope;
export const createClientReportEnvelope = _mod12623.createClientReportEnvelope;
export const DEFAULT_RETRY_AFTER = _slicedToArray2.DEFAULT_RETRY_AFTER;
export const disabledUntil = _slicedToArray2.disabledUntil;
export const isRateLimited = _slicedToArray2.isRateLimited;
export const parseRetryAfterHeader = _slicedToArray2.parseRetryAfterHeader;
export const updateRateLimits = _slicedToArray2.updateRateLimits;
export { BAGGAGE_HEADER_NAME_export as BAGGAGE_HEADER_NAME };
export const MAX_BAGGAGE_STRING_LENGTH = BAGGAGE_HEADER_NAME.MAX_BAGGAGE_STRING_LENGTH;
export const SENTRY_BAGGAGE_KEY_PREFIX = BAGGAGE_HEADER_NAME.SENTRY_BAGGAGE_KEY_PREFIX;
export const SENTRY_BAGGAGE_KEY_PREFIX_REGEX = BAGGAGE_HEADER_NAME.SENTRY_BAGGAGE_KEY_PREFIX_REGEX;
export const baggageHeaderToDynamicSamplingContext = BAGGAGE_HEADER_NAME.baggageHeaderToDynamicSamplingContext;
export const dynamicSamplingContextToSentryBaggageHeader =
  BAGGAGE_HEADER_NAME.dynamicSamplingContextToSentryBaggageHeader;
export const parseBaggageHeader = BAGGAGE_HEADER_NAME.parseBaggageHeader;
export const getNumberOfUrlSegments = stripUrlQueryAndFragment.getNumberOfUrlSegments;
export const getSanitizedUrlString = stripUrlQueryAndFragment.getSanitizedUrlString;
export const parseUrl = stripUrlQueryAndFragment.parseUrl;
export { stripUrlQueryAndFragment_export as stripUrlQueryAndFragment };
export const makeFifoCache = _mod12682.makeFifoCache;
export { eventFromMessage_export as eventFromMessage };
export const eventFromUnknownInput = eventFromMessage.eventFromUnknownInput;
export const exceptionFromError = eventFromMessage.exceptionFromError;
export const parseStackFrames = eventFromMessage.parseStackFrames;
export const callFrameToStackFrame = _mod12683.callFrameToStackFrame;
export const watchdogTimer = _mod12683.watchdogTimer;
export const LRUMap = _mod12684.LRUMap;
export { generatePropagationContext_export as generatePropagationContext };
export const generateSpanId = generatePropagationContext.generateSpanId;
export const generateTraceId = generatePropagationContext.generateTraceId;
export const vercelWaitUntil = _mod12685.vercelWaitUntil;
export const SDK_VERSION = _mod12567.SDK_VERSION;
export const getDebugImagesForResources = _mod12617.getDebugImagesForResources;
export const getFilenameToDebugIdMap = _mod12617.getFilenameToDebugIdMap;
export const escapeStringForRegex = _mod12686.escapeStringForRegex;
export { supportsHistory_export as supportsHistory };
export const _asyncNullishCoalesce = _asyncToGenerator._asyncNullishCoalesce;
export const _asyncOptionalChain = _asyncToGenerator2._asyncOptionalChain;
export const _asyncOptionalChainDelete = _asyncToGenerator3._asyncOptionalChainDelete;
export { _nullishCoalesce_export as _nullishCoalesce };
export { _optionalChain_export as _optionalChain };
export { _optionalChainDelete_export as _optionalChainDelete };
