// _runtime/metro/12575__.js
import _mod12576 from "12576__.js";
import _mod12577 from "12577__.js";
import _mod12578 from "12578__.js";
import _mod12580 from "12580__.js";
import _mod12581 from "12581__.js";
import _mod12582 from "12582__.js";
import _mod12583 from "12583__.js";
import _mod12584 from "12584__.js";
import _mod12585 from "12585__.js";
import _mod12586 from "12586__.js";
import _mod12587 from "12587__.js";
import htmlTreeAsString from "../12588_htmlTreeAsString.js";
import _mod12589 from "12589__.js";
import generatePropagationContext from "../12590_generatePropagationContext.js";
import _mod12591 from "12591__.js";
import _mod12592 from "12592__.js";
import BAGGAGE_HEADER_NAME from "../12593_BAGGAGE_HEADER_NAME.js";
import _mod12595 from "12595__.js";
import _slicedToArray from "12596__slicedToArray.js";
import _mod12597 from "12597__.js";
import _mod12598 from "12598__.js";
import _mod12599 from "12599__.js";
import _mod12601 from "12601__.js";
import _mod12603 from "12603__.js";
import _mod12604 from "12604__.js";
import _mod12606 from "12606__.js";
import _mod12607 from "12607__.js";
import _mod12609 from "12609__.js";
import _mod12610 from "12610__.js";
import _mod12611 from "12611__.js";
import _mod12612 from "12612__.js";
import _mod12613 from "12613__.js";
import _mod12614 from "12614__.js";
import _mod12615 from "12615__.js";
import _mod12616 from "12616__.js";
import _mod12617 from "12617__.js";
import _mod12618 from "12618__.js";
import _mod12619 from "12619__.js";
import _mod12620 from "12620__.js";
import _mod12621 from "12621__.js";
import _mod12622 from "12622__.js";
import _mod12623 from "12623__.js";
import _mod12624 from "12624__.js";
import _mod12625 from "12625__.js";
import memoBuilder from "../12626_memoBuilder.js";
import _mod12627 from "12627__.js";
import _mod12628 from "12628__.js";
import _mod12629 from "12629__.js";
import _mod12630 from "12630__.js";
import _mod12631 from "12631__.js";
import _mod12632 from "12632__.js";
import SessionFlusher from "../12633_SessionFlusher.js";
import _mod12634 from "12634__.js";
import BaseClient from "../12635_BaseClient.js";
import _mod12636 from "12636__.js";
import _mod12637 from "12637__.js";
import _mod12638 from "12638__.js";
import _mod12639 from "12639__.js";
import eventFromMessage from "../12640_eventFromMessage.js";
import _mod12641 from "12641__.js";
import _mod12642 from "12642__.js";
import _mod12643 from "12643__.js";
import _mod12644 from "12644__.js";
import _slicedToArray2 from "12645__slicedToArray.js";
import _mod12646 from "12646__.js";
import eventFromEnvelope from "../12647_eventFromEnvelope.js";
import _mod12648 from "12648__.js";
import _mod12649 from "12649__.js";
import _mod12650 from "12650__.js";
import _mod12651 from "12651__.js";
import _mod12652 from "12652__.js";
import _mod12653 from "12653__.js";
import _mod12654 from "12654__.js";
import inboundFiltersIntegration from "../12655_inboundFiltersIntegration.js";
import _mod12656 from "12656__.js";
import _mod12657 from "12657__.js";
import _mod12658 from "12658__.js";
import _mod12660 from "12660__.js";
import DEFAULT_USER_INCLUDES from "../12661_DEFAULT_USER_INCLUDES.js";
import stripUrlQueryAndFragment from "../12662_stripUrlQueryAndFragment.js";
import _mod12665 from "12665__.js";
import _mod12666 from "12666__.js";
import _mod12667 from "12667__.js";
import debugIntegration from "../12668_debugIntegration.js";
import _mod12669 from "12669__.js";
import _mod12670 from "12670__.js";
import _mod12671 from "12671__.js";
import _mod12672 from "12672__.js";
import sessionTimingIntegration from "../12673_sessionTimingIntegration.js";
import _mod12674 from "12674__.js";
import _mod12675 from "12675__.js";
import metrics from "../12676_metrics.js";
import _mod12678 from "12678__.js";
import metricsDefault from "../12679_metricsDefault.js";
import BrowserMetricsAggregator from "../12684_BrowserMetricsAggregator.js";
import instrumentFetchRequest from "../12685_instrumentFetchRequest.js";
import _mod12686 from "12686__.js";
import _mod12687 from "12687__.js";
import _mod12688 from "12688__.js";
import _mod12689 from "12689__.js";
import _mod12690 from "12690__.js";
import _mod12691 from "12691__.js";
import _mod12692 from "12692__.js";
import dynamicRequire from "../12693_dynamicRequire.js";
import _mod12694 from "12694__.js";
import _mod12695 from "12695__.js";
import _mod12696 from "12696__.js";
import _mod12697 from "12697__.js";
import _mod12698 from "12698__.js";
import _mod12699 from "12699__.js";
import _mod12700 from "12700__.js";
import _mod12701 from "12701__.js";
import supportsHistory from "../12702_supportsHistory.js";
import _asyncToGenerator from "12703__asyncToGenerator.js";
import _nullishCoalesce from "../12704__nullishCoalesce.js";
import _asyncToGenerator2 from "12705__asyncToGenerator.js";
import _asyncToGenerator3 from "12706__asyncToGenerator.js";
import _optionalChain from "../12707__optionalChain.js";
import _optionalChainDelete from "../12708__optionalChainDelete.js";

const require = globalThis.__r;

const SessionFlusher_export = SessionFlusher.SessionFlusher;
const BaseClient_export = BaseClient.BaseClient;
const inboundFiltersIntegration_export = inboundFiltersIntegration.inboundFiltersIntegration;
const debugIntegration_export = debugIntegration.debugIntegration;
const sessionTimingIntegration_export = sessionTimingIntegration.sessionTimingIntegration;
const metrics_export = metrics.metrics;
const metricsDefault_export = metricsDefault.metricsDefault;
const BrowserMetricsAggregator_export = BrowserMetricsAggregator.BrowserMetricsAggregator;
const instrumentFetchRequest_export = instrumentFetchRequest.instrumentFetchRequest;
const htmlTreeAsString_export = htmlTreeAsString.htmlTreeAsString;
const memoBuilder_export = memoBuilder.memoBuilder;
const dynamicRequire_export = _mod12694.dynamicRequire;
const DEFAULT_USER_INCLUDES_export = DEFAULT_USER_INCLUDES.DEFAULT_USER_INCLUDES;
const BAGGAGE_HEADER_NAME_export = BAGGAGE_HEADER_NAME.BAGGAGE_HEADER_NAME;
const stripUrlQueryAndFragment_export = stripUrlQueryAndFragment.stripUrlQueryAndFragment;
const eventFromMessage_export = eventFromMessage.eventFromMessage;
const generatePropagationContext_export = generatePropagationContext.generatePropagationContext;
const supportsHistory_export = supportsHistory.supportsHistory;
const _nullishCoalesce_export = _nullishCoalesce._nullishCoalesce;
const _optionalChain_export = _optionalChain._optionalChain;
const _optionalChainDelete_export = _optionalChainDelete._optionalChainDelete;

export const registerSpanErrorInstrumentation = _mod12576.registerSpanErrorInstrumentation;
export const getCapturedScopesOnSpan = _mod12609.getCapturedScopesOnSpan;
export const setCapturedScopesOnSpan = _mod12609.setCapturedScopesOnSpan;
export const addTracingExtensions = _mod12610.addTracingExtensions;
export const TRACING_DEFAULTS = _mod12611.TRACING_DEFAULTS;
export const startIdleSpan = _mod12611.startIdleSpan;
export const SentrySpan = _mod12621.SentrySpan;
export const SentryNonRecordingSpan = _mod12613.SentryNonRecordingSpan;
export const SPAN_STATUS_ERROR = _mod12597.SPAN_STATUS_ERROR;
export const SPAN_STATUS_OK = _mod12597.SPAN_STATUS_OK;
export const SPAN_STATUS_UNSET = _mod12597.SPAN_STATUS_UNSET;
export const getSpanStatusFromHttpCode = _mod12597.getSpanStatusFromHttpCode;
export const setHttpStatus = _mod12597.setHttpStatus;
export const continueTrace = _mod12614.continueTrace;
export const startInactiveSpan = _mod12614.startInactiveSpan;
export const startNewTrace = _mod12614.startNewTrace;
export const startSpan = _mod12614.startSpan;
export const startSpanManual = _mod12614.startSpanManual;
export const suppressTracing = _mod12614.suppressTracing;
export const withActiveSpan = _mod12614.withActiveSpan;
export const getDynamicSamplingContextFromClient = _mod12616.getDynamicSamplingContextFromClient;
export const getDynamicSamplingContextFromScope = _mod12616.getDynamicSamplingContextFromScope;
export const getDynamicSamplingContextFromSpan = _mod12616.getDynamicSamplingContextFromSpan;
export const spanToBaggageHeader = _mod12616.spanToBaggageHeader;
export const setMeasurement = _mod12622.setMeasurement;
export const timedEventsToMeasurements = _mod12622.timedEventsToMeasurements;
export const sampleSpan = _mod12619.sampleSpan;
export const logSpanEnd = _mod12618.logSpanEnd;
export const logSpanStart = _mod12618.logSpanStart;
export const SEMANTIC_ATTRIBUTE_CACHE_HIT = _mod12595.SEMANTIC_ATTRIBUTE_CACHE_HIT;
export const SEMANTIC_ATTRIBUTE_CACHE_ITEM_SIZE = _mod12595.SEMANTIC_ATTRIBUTE_CACHE_ITEM_SIZE;
export const SEMANTIC_ATTRIBUTE_CACHE_KEY = _mod12595.SEMANTIC_ATTRIBUTE_CACHE_KEY;
export const SEMANTIC_ATTRIBUTE_EXCLUSIVE_TIME = _mod12595.SEMANTIC_ATTRIBUTE_EXCLUSIVE_TIME;
export const SEMANTIC_ATTRIBUTE_HTTP_REQUEST_METHOD = _mod12595.SEMANTIC_ATTRIBUTE_HTTP_REQUEST_METHOD;
export const SEMANTIC_ATTRIBUTE_PROFILE_ID = _mod12595.SEMANTIC_ATTRIBUTE_PROFILE_ID;
export const SEMANTIC_ATTRIBUTE_SENTRY_CUSTOM_SPAN_NAME = _mod12595.SEMANTIC_ATTRIBUTE_SENTRY_CUSTOM_SPAN_NAME;
export const SEMANTIC_ATTRIBUTE_SENTRY_IDLE_SPAN_FINISH_REASON =
  _mod12595.SEMANTIC_ATTRIBUTE_SENTRY_IDLE_SPAN_FINISH_REASON;
export const SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_UNIT = _mod12595.SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_UNIT;
export const SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_VALUE = _mod12595.SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_VALUE;
export const SEMANTIC_ATTRIBUTE_SENTRY_OP = _mod12595.SEMANTIC_ATTRIBUTE_SENTRY_OP;
export const SEMANTIC_ATTRIBUTE_SENTRY_ORIGIN = _mod12595.SEMANTIC_ATTRIBUTE_SENTRY_ORIGIN;
export const SEMANTIC_ATTRIBUTE_SENTRY_SAMPLE_RATE = _mod12595.SEMANTIC_ATTRIBUTE_SENTRY_SAMPLE_RATE;
export const SEMANTIC_ATTRIBUTE_SENTRY_SOURCE = _mod12595.SEMANTIC_ATTRIBUTE_SENTRY_SOURCE;
export const SEMANTIC_ATTRIBUTE_URL_FULL = _mod12595.SEMANTIC_ATTRIBUTE_URL_FULL;
export const createEventEnvelope = _mod12623.createEventEnvelope;
export const createSessionEnvelope = _mod12623.createSessionEnvelope;
export const createSpanEnvelope = _mod12623.createSpanEnvelope;
export const addEventProcessor = _mod12628.addEventProcessor;
export const captureCheckIn = _mod12628.captureCheckIn;
export const captureEvent = _mod12628.captureEvent;
export const captureException = _mod12628.captureException;
export const captureMessage = _mod12628.captureMessage;
export const captureSession = _mod12628.captureSession;
export const close = _mod12628.close;
export const endSession = _mod12628.endSession;
export const flush = _mod12628.flush;
export const isEnabled = _mod12628.isEnabled;
export const isInitialized = _mod12628.isInitialized;
export const lastEventId = _mod12628.lastEventId;
export const setContext = _mod12628.setContext;
export const setExtra = _mod12628.setExtra;
export const setExtras = _mod12628.setExtras;
export const setTag = _mod12628.setTag;
export const setTags = _mod12628.setTags;
export const setUser = _mod12628.setUser;
export const startSession = _mod12628.startSession;
export const withMonitor = _mod12628.withMonitor;
export const getClient = _mod12607.getClient;
export const getCurrentScope = _mod12607.getCurrentScope;
export const getGlobalScope = _mod12607.getGlobalScope;
export const getIsolationScope = _mod12607.getIsolationScope;
export const getTraceContextFromScope = _mod12607.getTraceContextFromScope;
export const withIsolationScope = _mod12607.withIsolationScope;
export const withScope = _mod12607.withScope;
export const getDefaultCurrentScope = _mod12606.getDefaultCurrentScope;
export const getDefaultIsolationScope = _mod12606.getDefaultIsolationScope;
export const setAsyncContextStrategy = _mod12599.setAsyncContextStrategy;
export const getMainCarrier = _mod12598.getMainCarrier;
export const closeSession = _mod12603.closeSession;
export const makeSession = _mod12603.makeSession;
export const updateSession = _mod12603.updateSession;
export { SessionFlusher_export as SessionFlusher };
export const Scope = _mod12601.Scope;
export const notifyEventProcessors = _mod12631.notifyEventProcessors;
export const getEnvelopeEndpointWithUrlEncodedAuth = _mod12634.getEnvelopeEndpointWithUrlEncodedAuth;
export const getReportDialogEndpoint = _mod12634.getReportDialogEndpoint;
export { BaseClient_export as BaseClient };
export const ServerRuntimeClient = _mod12639.ServerRuntimeClient;
export const initAndBind = _mod12642.initAndBind;
export const setCurrentClient = _mod12642.setCurrentClient;
export const createTransport = _mod12643.createTransport;
export const makeOfflineTransport = _mod12646.makeOfflineTransport;
export const makeMultiplexedTransport = eventFromEnvelope.makeMultiplexedTransport;
export const addIntegration = _mod12636.addIntegration;
export const defineIntegration = _mod12636.defineIntegration;
export const getIntegrationsToSetup = _mod12636.getIntegrationsToSetup;
export const applyScopeDataToEvent = _mod12630.applyScopeDataToEvent;
export const mergeScopeData = _mod12630.mergeScopeData;
export const prepareEvent = _mod12629.prepareEvent;
export const createCheckInEnvelope = _mod12641.createCheckInEnvelope;
export const hasTracingEnabled = _mod12612.hasTracingEnabled;
export const isSentryRequestUrl = _mod12648.isSentryRequestUrl;
export const handleCallbackErrors = _mod12615.handleCallbackErrors;
export const parameterize = _mod12649.parameterize;
export const addChildSpanToSpan = _mod12585.addChildSpanToSpan;
export const getActiveSpan = _mod12585.getActiveSpan;
export const getRootSpan = _mod12585.getRootSpan;
export const getSpanDescendants = _mod12585.getSpanDescendants;
export const getStatusMessage = _mod12585.getStatusMessage;
export const spanIsSampled = _mod12585.spanIsSampled;
export const spanTimeInputToSeconds = _mod12585.spanTimeInputToSeconds;
export const spanToJSON = _mod12585.spanToJSON;
export const spanToTraceContext = _mod12585.spanToTraceContext;
export const spanToTraceHeader = _mod12585.spanToTraceHeader;
export const updateSpanName = _mod12585.updateSpanName;
export const parseSampleRate = _mod12620.parseSampleRate;
export const applySdkMetadata = _mod12650.applySdkMetadata;
export const getTraceData = _mod12651.getTraceData;
export const getTraceMetaTags = _mod12652.getTraceMetaTags;
export const DEFAULT_ENVIRONMENT = _mod12617.DEFAULT_ENVIRONMENT;
export const addBreadcrumb = _mod12653.addBreadcrumb;
export const functionToStringIntegration = _mod12654.functionToStringIntegration;
export { inboundFiltersIntegration_export as inboundFiltersIntegration };
export const linkedErrorsIntegration = _mod12656.linkedErrorsIntegration;
export const moduleMetadataIntegration = _mod12658.moduleMetadataIntegration;
export const requestDataIntegration = _mod12660.requestDataIntegration;
export const captureConsoleIntegration = _mod12665.captureConsoleIntegration;
export { debugIntegration_export as debugIntegration };
export const dedupeIntegration = _mod12669.dedupeIntegration;
export const extraErrorDataIntegration = _mod12670.extraErrorDataIntegration;
export const rewriteFramesIntegration = _mod12671.rewriteFramesIntegration;
export { sessionTimingIntegration_export as sessionTimingIntegration };
export const zodErrorsIntegration = _mod12674.zodErrorsIntegration;
export const thirdPartyErrorFilterIntegration = _mod12675.thirdPartyErrorFilterIntegration;
export { metrics_export as metrics };
export const profiler = _mod12678.profiler;
export { metricsDefault_export as metricsDefault };
export { BrowserMetricsAggregator_export as BrowserMetricsAggregator };
export const getMetricSummaryJsonForSpan = _slicedToArray.getMetricSummaryJsonForSpan;
export const addTracingHeadersToFetchRequest = instrumentFetchRequest.addTracingHeadersToFetchRequest;
export { instrumentFetchRequest_export as instrumentFetchRequest };
export const trpcMiddleware = _mod12686.trpcMiddleware;
export const captureFeedback = _mod12687.captureFeedback;
export const getCurrentHub = _mod12688.getCurrentHub;
export const getCurrentHubShim = _mod12688.getCurrentHubShim;
export const applyAggregateErrorsToEvent = _mod12657.applyAggregateErrorsToEvent;
export const flatten = _mod12689.flatten;
export const getBreadcrumbLogLevelFromHttpStatusCode = _mod12690.getBreadcrumbLogLevelFromHttpStatusCode;
export const getComponentName = htmlTreeAsString.getComponentName;
export const getDomElement = htmlTreeAsString.getDomElement;
export const getLocationHref = htmlTreeAsString.getLocationHref;
export { htmlTreeAsString_export as htmlTreeAsString };
export const dsnFromString = _mod12627.dsnFromString;
export const dsnToString = _mod12627.dsnToString;
export const makeDsn = _mod12627.makeDsn;
export const SentryError = _mod12637.SentryError;
export const GLOBAL_OBJ = _mod12581.GLOBAL_OBJ;
export const getGlobalSingleton = _mod12581.getGlobalSingleton;
export const addConsoleInstrumentationHandler = _mod12666.addConsoleInstrumentationHandler;
export const addFetchEndInstrumentationHandler = _mod12691.addFetchEndInstrumentationHandler;
export const addFetchInstrumentationHandler = _mod12691.addFetchInstrumentationHandler;
export const addGlobalErrorInstrumentationHandler = _mod12577.addGlobalErrorInstrumentationHandler;
export const addGlobalUnhandledRejectionInstrumentationHandler =
  _mod12584.addGlobalUnhandledRejectionInstrumentationHandler;
export const addHandler = _mod12578.addHandler;
export const maybeInstrument = _mod12578.maybeInstrument;
export const resetInstrumentationHandlers = _mod12578.resetInstrumentationHandlers;
export const triggerHandlers = _mod12578.triggerHandlers;
export const isDOMError = _mod12587.isDOMError;
export const isDOMException = _mod12587.isDOMException;
export const isElement = _mod12587.isElement;
export const isError = _mod12587.isError;
export const isErrorEvent = _mod12587.isErrorEvent;
export const isEvent = _mod12587.isEvent;
export const isInstanceOf = _mod12587.isInstanceOf;
export const isParameterizedString = _mod12587.isParameterizedString;
export const isPlainObject = _mod12587.isPlainObject;
export const isPrimitive = _mod12587.isPrimitive;
export const isRegExp = _mod12587.isRegExp;
export const isString = _mod12587.isString;
export const isSyntheticEvent = _mod12587.isSyntheticEvent;
export const isThenable = _mod12587.isThenable;
export const isVueViewModel = _mod12587.isVueViewModel;
export const isBrowser = dynamicRequire.isBrowser;
export const CONSOLE_LEVELS = _mod12580.CONSOLE_LEVELS;
export const consoleSandbox = _mod12580.consoleSandbox;
export const logger = _mod12580.logger;
export const originalConsoleMethods = _mod12580.originalConsoleMethods;
export { memoBuilder_export as memoBuilder };
export const addContextToFrame = _mod12591.addContextToFrame;
export const addExceptionMechanism = _mod12591.addExceptionMechanism;
export const addExceptionTypeValue = _mod12591.addExceptionTypeValue;
export const arrayify = _mod12591.arrayify;
export const checkOrSetAlreadyCaught = _mod12591.checkOrSetAlreadyCaught;
export const getEventDescription = _mod12591.getEventDescription;
export const parseSemver = _mod12591.parseSemver;
export const uuid4 = _mod12591.uuid4;
export { dynamicRequire_export as dynamicRequire };
export const isNodeEnv = _mod12694.isNodeEnv;
export const loadModule = _mod12694.loadModule;
export const normalize = _mod12625.normalize;
export const normalizeToSize = _mod12625.normalizeToSize;
export const normalizeUrlToBase = _mod12625.normalizeUrlToBase;
export const addNonEnumerableProperty = _mod12586.addNonEnumerableProperty;
export const convertToPlainObject = _mod12586.convertToPlainObject;
export const dropUndefinedKeys = _mod12586.dropUndefinedKeys;
export const extractExceptionKeysForMessage = _mod12586.extractExceptionKeysForMessage;
export const fill = _mod12586.fill;
export const getOriginalFunction = _mod12586.getOriginalFunction;
export const markFunctionWrapped = _mod12586.markFunctionWrapped;
export const objectify = _mod12586.objectify;
export const urlEncode = _mod12586.urlEncode;
export const basename = _mod12672.basename;
export const dirname = _mod12672.dirname;
export const isAbsolute = _mod12672.isAbsolute;
export const join = _mod12672.join;
export const normalizePath = _mod12672.normalizePath;
export const relative = _mod12672.relative;
export const resolve = _mod12672.resolve;
export const makePromiseBuffer = _mod12644.makePromiseBuffer;
export { DEFAULT_USER_INCLUDES_export as DEFAULT_USER_INCLUDES };
export const addNormalizedRequestDataToEvent = DEFAULT_USER_INCLUDES.addNormalizedRequestDataToEvent;
export const addRequestDataToEvent = DEFAULT_USER_INCLUDES.addRequestDataToEvent;
export const extractPathForTransaction = DEFAULT_USER_INCLUDES.extractPathForTransaction;
export const extractQueryParamsFromUrl = DEFAULT_USER_INCLUDES.extractQueryParamsFromUrl;
export const extractRequestData = DEFAULT_USER_INCLUDES.extractRequestData;
export const headersToDict = DEFAULT_USER_INCLUDES.headersToDict;
export const httpRequestToRequestData = DEFAULT_USER_INCLUDES.httpRequestToRequestData;
export const winterCGHeadersToDict = DEFAULT_USER_INCLUDES.winterCGHeadersToDict;
export const winterCGRequestToRequestData = DEFAULT_USER_INCLUDES.winterCGRequestToRequestData;
export const severityLevelFromString = _mod12667.severityLevelFromString;
export const validSeverityLevels = _mod12667.validSeverityLevels;
export const UNKNOWN_FUNCTION = _mod12583.UNKNOWN_FUNCTION;
export const createStackParser = _mod12583.createStackParser;
export const getFramesFromEvent = _mod12583.getFramesFromEvent;
export const getFunctionName = _mod12583.getFunctionName;
export const stackParserFromStackParserOptions = _mod12583.stackParserFromStackParserOptions;
export const stripSentryFramesAndReverse = _mod12583.stripSentryFramesAndReverse;
export const filenameIsInApp = _mod12696.filenameIsInApp;
export const node = _mod12696.node;
export const nodeStackLineParser = _mod12696.nodeStackLineParser;
export const isMatchingPattern = _mod12589.isMatchingPattern;
export const safeJoin = _mod12589.safeJoin;
export const snipLine = _mod12589.snipLine;
export const stringMatchesSomePattern = _mod12589.stringMatchesSomePattern;
export const truncate = _mod12589.truncate;
export const isNativeFunction = _mod12692.isNativeFunction;
export const supportsDOMError = _mod12692.supportsDOMError;
export const supportsDOMException = _mod12692.supportsDOMException;
export const supportsErrorEvent = _mod12692.supportsErrorEvent;
export const supportsFetch = _mod12692.supportsFetch;
export const supportsNativeFetch = _mod12692.supportsNativeFetch;
export const supportsReferrerPolicy = _mod12692.supportsReferrerPolicy;
export const supportsReportingObserver = _mod12692.supportsReportingObserver;
export const SyncPromise = _mod12604.SyncPromise;
export const rejectedSyncPromise = _mod12604.rejectedSyncPromise;
export const resolvedSyncPromise = _mod12604.resolvedSyncPromise;
export const _browserPerformanceTimeOriginMode =
  require("_browserPerformanceTimeOriginMode")._browserPerformanceTimeOriginMode;
export { browserPerformanceTimeOrigin } from "_browserPerformanceTimeOriginMode";
export { dateTimestampInSeconds } from "_browserPerformanceTimeOriginMode";
export { timestampInSeconds } from "_browserPerformanceTimeOriginMode";
export const TRACEPARENT_REGEXP = _mod12592.TRACEPARENT_REGEXP;
export const extractTraceparentData = _mod12592.extractTraceparentData;
export const generateSentryTraceHeader = _mod12592.generateSentryTraceHeader;
export const propagationContextFromHeaders = _mod12592.propagationContextFromHeaders;
export const getSDKSource = _mod12695.getSDKSource;
export const isBrowserBundle = _mod12695.isBrowserBundle;
export const addItemToEnvelope = _mod12624.addItemToEnvelope;
export const createAttachmentEnvelopeItem = _mod12624.createAttachmentEnvelopeItem;
export const createEnvelope = _mod12624.createEnvelope;
export const createEventEnvelopeHeaders = _mod12624.createEventEnvelopeHeaders;
export const createSpanEnvelopeItem = _mod12624.createSpanEnvelopeItem;
export const envelopeContainsItemType = _mod12624.envelopeContainsItemType;
export const envelopeItemTypeToDataCategory = _mod12624.envelopeItemTypeToDataCategory;
export const forEachEnvelopeItem = _mod12624.forEachEnvelopeItem;
export const getSdkMetadataForEnvelopeHeader = _mod12624.getSdkMetadataForEnvelopeHeader;
export const parseEnvelope = _mod12624.parseEnvelope;
export const serializeEnvelope = _mod12624.serializeEnvelope;
export const createClientReportEnvelope = _mod12638.createClientReportEnvelope;
export const DEFAULT_RETRY_AFTER = _slicedToArray2.DEFAULT_RETRY_AFTER;
export const disabledUntil = _slicedToArray2.disabledUntil;
export const isRateLimited = _slicedToArray2.isRateLimited;
export const parseRetryAfterHeader = _slicedToArray2.parseRetryAfterHeader;
export const updateRateLimits = _slicedToArray2.updateRateLimits;
export { BAGGAGE_HEADER_NAME_export as BAGGAGE_HEADER_NAME };
export const MAX_BAGGAGE_STRING_LENGTH = BAGGAGE_HEADER_NAME.MAX_BAGGAGE_STRING_LENGTH;
export const SENTRY_BAGGAGE_KEY_PREFIX = BAGGAGE_HEADER_NAME.SENTRY_BAGGAGE_KEY_PREFIX;
export const SENTRY_BAGGAGE_KEY_PREFIX_REGEX = BAGGAGE_HEADER_NAME.SENTRY_BAGGAGE_KEY_PREFIX_REGEX;
export const baggageHeaderToDynamicSamplingContext = BAGGAGE_HEADER_NAME.baggageHeaderToDynamicSamplingContext;
export const dynamicSamplingContextToSentryBaggageHeader =
  BAGGAGE_HEADER_NAME.dynamicSamplingContextToSentryBaggageHeader;
export const parseBaggageHeader = BAGGAGE_HEADER_NAME.parseBaggageHeader;
export const getNumberOfUrlSegments = stripUrlQueryAndFragment.getNumberOfUrlSegments;
export const getSanitizedUrlString = stripUrlQueryAndFragment.getSanitizedUrlString;
export const parseUrl = stripUrlQueryAndFragment.parseUrl;
export { stripUrlQueryAndFragment_export as stripUrlQueryAndFragment };
export const makeFifoCache = _mod12697.makeFifoCache;
export { eventFromMessage_export as eventFromMessage };
export const eventFromUnknownInput = eventFromMessage.eventFromUnknownInput;
export const exceptionFromError = eventFromMessage.exceptionFromError;
export const parseStackFrames = eventFromMessage.parseStackFrames;
export const callFrameToStackFrame = _mod12698.callFrameToStackFrame;
export const watchdogTimer = _mod12698.watchdogTimer;
export const LRUMap = _mod12699.LRUMap;
export { generatePropagationContext_export as generatePropagationContext };
export const generateSpanId = generatePropagationContext.generateSpanId;
export const generateTraceId = generatePropagationContext.generateTraceId;
export const vercelWaitUntil = _mod12700.vercelWaitUntil;
export const SDK_VERSION = _mod12582.SDK_VERSION;
export const getDebugImagesForResources = _mod12632.getDebugImagesForResources;
export const getFilenameToDebugIdMap = _mod12632.getFilenameToDebugIdMap;
export const escapeStringForRegex = _mod12701.escapeStringForRegex;
export { supportsHistory_export as supportsHistory };
export const _asyncNullishCoalesce = _asyncToGenerator._asyncNullishCoalesce;
export const _asyncOptionalChain = _asyncToGenerator2._asyncOptionalChain;
export const _asyncOptionalChainDelete = _asyncToGenerator3._asyncOptionalChainDelete;
export { _nullishCoalesce_export as _nullishCoalesce };
export { _optionalChain_export as _optionalChain };
export { _optionalChainDelete_export as _optionalChainDelete };
