// === Module 12575: ? ===

// Module 12575
import errorCallback from "errorCallback" /* 12576 */;
import _mod12577 from "module_12577" /* 12577 */;
import _mod12578 from "module_12578" /* 12578 */;
import _mod12580 from "module_12580" /* 12580 */;
import _mod12581 from "module_12581" /* 12581 */;
import _mod12582 from "module_12582" /* 12582 */;
import stackParserFromStackParserOptions from "stackParserFromStackParserOptions" /* 12583 */;
import _mod12584 from "module_12584" /* 12584 */;
import spanTimeInputToSeconds from "spanTimeInputToSeconds" /* 12585 */;
import _mod12586 from "module_12586" /* 12586 */;
import _mod12587 from "module_12587" /* 12587 */;
import _mod12588 from "module_12588" /* 12588 */;
import _mod12589 from "module_12589" /* 12589 */;
import generatePropagationContext from "generatePropagationContext" /* 12590 */;
import _mod12591 from "module_12591" /* 12591 */;
import _mod12592 from "module_12592" /* 12592 */;
import BAGGAGE_HEADER_NAME from "BAGGAGE_HEADER_NAME" /* 12593 */;
import _mod12595 from "module_12595" /* 12595 */;
import _mod12596 from "module_12596" /* 12596 */;
import _mod12597 from "module_12597" /* 12597 */;
import _mod12598 from "module_12598" /* 12598 */;
import _mod12599 from "module_12599" /* 12599 */;
import ScopeClass from "ScopeClass" /* 12601 */;
import _mod12603 from "module_12603" /* 12603 */;
import _mod12604 from "module_12604" /* 12604 */;
import _mod12606 from "module_12606" /* 12606 */;
import _mod12607 from "module_12607" /* 12607 */;
import _mod12609 from "module_12609" /* 12609 */;
import _mod12610 from "module_12610" /* 12610 */;
import _mod12611 from "module_12611" /* 12611 */;
import _mod12612 from "module_12612" /* 12612 */;
import _mod12613 from "module_12613" /* 12613 */;
import _mod12614 from "module_12614" /* 12614 */;
import _mod12615 from "module_12615" /* 12615 */;
import _mod12616 from "module_12616" /* 12616 */;
import _mod12617 from "module_12617" /* 12617 */;
import _mod12618 from "module_12618" /* 12618 */;
import _mod12619 from "module_12619" /* 12619 */;
import _mod12620 from "module_12620" /* 12620 */;
import _mod12621 from "module_12621" /* 12621 */;
import _mod12622 from "module_12622" /* 12622 */;
import _mod12623 from "module_12623" /* 12623 */;
import _mod12624 from "module_12624" /* 12624 */;
import _mod12625 from "module_12625" /* 12625 */;
import memoBuilder from "memoBuilder" /* 12626 */;
import _mod12627 from "module_12627" /* 12627 */;
import _flush from "_flush" /* 12628 */;
import _mod12629 from "module_12629" /* 12629 */;
import applyScopeDataToEvent from "applyScopeDataToEvent" /* 12630 */;
import notifyEventProcessors from "notifyEventProcessors" /* 12631 */;
import _mod12632 from "module_12632" /* 12632 */;
import SessionFlusher from "SessionFlusher" /* 12633 */;
import _mod12634 from "module_12634" /* 12634 */;
import _mod12635 from "module_12635" /* 12635 */;
import _mod12636 from "module_12636" /* 12636 */;
import _mod12637 from "module_12637" /* 12637 */;
import _mod12638 from "module_12638" /* 12638 */;
import _mod12639 from "module_12639" /* 12639 */;
import eventFromMessage from "eventFromMessage" /* 12640 */;
import _mod12641 from "module_12641" /* 12641 */;
import _mod12642 from "module_12642" /* 12642 */;
import _mod12643 from "module_12643" /* 12643 */;
import _mod12644 from "module_12644" /* 12644 */;
import _mod12645 from "module_12645" /* 12645 */;
import _mod12646 from "module_12646" /* 12646 */;
import _mod12647 from "module_12647" /* 12647 */;
import _mod12648 from "module_12648" /* 12648 */;
import _mod12649 from "module_12649" /* 12649 */;
import _mod12650 from "module_12650" /* 12650 */;
import _mod12651 from "module_12651" /* 12651 */;
import _mod12652 from "module_12652" /* 12652 */;
import _mod12653 from "module_12653" /* 12653 */;
import _mod12654 from "module_12654" /* 12654 */;
import _getEventFilterUrl from "_getEventFilterUrl" /* 12655 */;
import _mod12656 from "module_12656" /* 12656 */;
import _mod12657 from "module_12657" /* 12657 */;
import _mod12658 from "module_12658" /* 12658 */;
import _mod12660 from "module_12660" /* 12660 */;
import extractRequestData from "extractRequestData" /* 12661 */;
import stripUrlQueryAndFragment from "stripUrlQueryAndFragment" /* 12662 */;
import _mod12665 from "module_12665" /* 12665 */;
import _mod12666 from "module_12666" /* 12666 */;
import _mod12667 from "module_12667" /* 12667 */;
import debugIntegration from "debugIntegration" /* 12668 */;
import _mod12669 from "module_12669" /* 12669 */;
import extraErrorDataIntegration from "extraErrorDataIntegration" /* 12670 */;
import _mod12671 from "module_12671" /* 12671 */;
import _mod12672 from "module_12672" /* 12672 */;
import sessionTimingIntegration from "sessionTimingIntegration" /* 12673 */;
import _mod12674 from "module_12674" /* 12674 */;
import _mod12675 from "module_12675" /* 12675 */;
import _mod12676 from "module_12676" /* 12676 */;
import _mod12678 from "module_12678" /* 12678 */;
import metricsDefault from "metricsDefault" /* 12679 */;
import BrowserMetricsAggregator from "BrowserMetricsAggregator" /* 12684 */;
import _mod12685 from "module_12685" /* 12685 */;
import _mod12686 from "module_12686" /* 12686 */;
import _mod12687 from "module_12687" /* 12687 */;
import _mod12688 from "module_12688" /* 12688 */;
import _mod12689 from "module_12689" /* 12689 */;
import _mod12690 from "module_12690" /* 12690 */;
import _mod12691 from "module_12691" /* 12691 */;
import supportsFetch from "supportsFetch" /* 12692 */;
import _mod12693 from "module_12693" /* 12693 */;
import _mod12694 from "module_12694" /* 12694 */;
import _mod12695 from "module_12695" /* 12695 */;
import _mod12696 from "module_12696" /* 12696 */;
import _mod12697 from "module_12697" /* 12697 */;
import _mod12698 from "module_12698" /* 12698 */;
import _mod12699 from "module_12699" /* 12699 */;
import _mod12700 from "module_12700" /* 12700 */;
import _mod12701 from "module_12701" /* 12701 */;
import supportsHistory from "supportsHistory" /* 12702 */;
import _asyncNullishCoalesce2 from "_asyncNullishCoalesce2" /* 12703 */;
import _nullishCoalesce from "_nullishCoalesce" /* 12704 */;
import _asyncOptionalChain2 from "_asyncOptionalChain2" /* 12705 */;
import _asyncOptionalChainDelete2 from "_asyncOptionalChainDelete2" /* 12706 */;
import _optionalChain from "_optionalChain" /* 12707 */;
import _optionalChainDelete from "_optionalChainDelete" /* 12708 */;

const require = globalThis.__r;


export const registerSpanErrorInstrumentation = errorCallback.registerSpanErrorInstrumentation;
export const getCapturedScopesOnSpan = _mod12609.getCapturedScopesOnSpan;
export const setCapturedScopesOnSpan = _mod12609.setCapturedScopesOnSpan;
export const addTracingExtensions = _mod12610.addTracingExtensions;
export const TRACING_DEFAULTS = _mod12611.TRACING_DEFAULTS;
export const startIdleSpan = _mod12611.startIdleSpan;
export const SentrySpan = _mod12621.SentrySpan;
export const SentryNonRecordingSpan = _mod12613.SentryNonRecordingSpan;
export const SPAN_STATUS_ERROR = _mod12597.SPAN_STATUS_ERROR;
export const SPAN_STATUS_OK = _mod12597.SPAN_STATUS_OK;
export const SPAN_STATUS_UNSET = _mod12597.SPAN_STATUS_UNSET;
export const getSpanStatusFromHttpCode = _mod12597.getSpanStatusFromHttpCode;
export const setHttpStatus = _mod12597.setHttpStatus;
export const continueTrace = _mod12614.continueTrace;
export const startInactiveSpan = _mod12614.startInactiveSpan;
export const startNewTrace = _mod12614.startNewTrace;
export const startSpan = _mod12614.startSpan;
export const startSpanManual = _mod12614.startSpanManual;
export const suppressTracing = _mod12614.suppressTracing;
export const withActiveSpan = _mod12614.withActiveSpan;
export const getDynamicSamplingContextFromClient = _mod12616.getDynamicSamplingContextFromClient;
export const getDynamicSamplingContextFromScope = _mod12616.getDynamicSamplingContextFromScope;
export const getDynamicSamplingContextFromSpan = _mod12616.getDynamicSamplingContextFromSpan;
export const spanToBaggageHeader = _mod12616.spanToBaggageHeader;
export const setMeasurement = _mod12622.setMeasurement;
export const timedEventsToMeasurements = _mod12622.timedEventsToMeasurements;
export const sampleSpan = _mod12619.sampleSpan;
export const logSpanEnd = _mod12618.logSpanEnd;
export const logSpanStart = _mod12618.logSpanStart;
export const SEMANTIC_ATTRIBUTE_CACHE_HIT = _mod12595.SEMANTIC_ATTRIBUTE_CACHE_HIT;
export const SEMANTIC_ATTRIBUTE_CACHE_ITEM_SIZE = _mod12595.SEMANTIC_ATTRIBUTE_CACHE_ITEM_SIZE;
export const SEMANTIC_ATTRIBUTE_CACHE_KEY = _mod12595.SEMANTIC_ATTRIBUTE_CACHE_KEY;
export const SEMANTIC_ATTRIBUTE_EXCLUSIVE_TIME = _mod12595.SEMANTIC_ATTRIBUTE_EXCLUSIVE_TIME;
export const SEMANTIC_ATTRIBUTE_HTTP_REQUEST_METHOD = _mod12595.SEMANTIC_ATTRIBUTE_HTTP_REQUEST_METHOD;
export const SEMANTIC_ATTRIBUTE_PROFILE_ID = _mod12595.SEMANTIC_ATTRIBUTE_PROFILE_ID;
export const SEMANTIC_ATTRIBUTE_SENTRY_CUSTOM_SPAN_NAME = _mod12595.SEMANTIC_ATTRIBUTE_SENTRY_CUSTOM_SPAN_NAME;
export const SEMANTIC_ATTRIBUTE_SENTRY_IDLE_SPAN_FINISH_REASON = _mod12595.SEMANTIC_ATTRIBUTE_SENTRY_IDLE_SPAN_FINISH_REASON;
export const SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_UNIT = _mod12595.SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_UNIT;
export const SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_VALUE = _mod12595.SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_VALUE;
export const SEMANTIC_ATTRIBUTE_SENTRY_OP = _mod12595.SEMANTIC_ATTRIBUTE_SENTRY_OP;
export const SEMANTIC_ATTRIBUTE_SENTRY_ORIGIN = _mod12595.SEMANTIC_ATTRIBUTE_SENTRY_ORIGIN;
export const SEMANTIC_ATTRIBUTE_SENTRY_SAMPLE_RATE = _mod12595.SEMANTIC_ATTRIBUTE_SENTRY_SAMPLE_RATE;
export const SEMANTIC_ATTRIBUTE_SENTRY_SOURCE = _mod12595.SEMANTIC_ATTRIBUTE_SENTRY_SOURCE;
export const SEMANTIC_ATTRIBUTE_URL_FULL = _mod12595.SEMANTIC_ATTRIBUTE_URL_FULL;
export const createEventEnvelope = _mod12623.createEventEnvelope;
export const createSessionEnvelope = _mod12623.createSessionEnvelope;
export const createSpanEnvelope = _mod12623.createSpanEnvelope;
export const addEventProcessor = _flush.addEventProcessor;
export const captureCheckIn = _flush.captureCheckIn;
export const captureEvent = _flush.captureEvent;
export const captureException = _flush.captureException;
export const captureMessage = _flush.captureMessage;
export const captureSession = _flush.captureSession;
export const close = _flush.close;
export const endSession = _flush.endSession;
export const flush = _flush.flush;
export const isEnabled = _flush.isEnabled;
export const isInitialized = _flush.isInitialized;
export const lastEventId = _flush.lastEventId;
export const setContext = _flush.setContext;
export const setExtra = _flush.setExtra;
export const setExtras = _flush.setExtras;
export const setTag = _flush.setTag;
export const setTags = _flush.setTags;
export const setUser = _flush.setUser;
export const startSession = _flush.startSession;
export const withMonitor = _flush.withMonitor;
export const getClient = _mod12607.getClient;
export const getCurrentScope = _mod12607.getCurrentScope;
export const getGlobalScope = _mod12607.getGlobalScope;
export const getIsolationScope = _mod12607.getIsolationScope;
export const getTraceContextFromScope = _mod12607.getTraceContextFromScope;
export const withIsolationScope = _mod12607.withIsolationScope;
export const withScope = _mod12607.withScope;
export const getDefaultCurrentScope = _mod12606.getDefaultCurrentScope;
export const getDefaultIsolationScope = _mod12606.getDefaultIsolationScope;
export const setAsyncContextStrategy = _mod12599.setAsyncContextStrategy;
export const getMainCarrier = _mod12598.getMainCarrier;
export const closeSession = _mod12603.closeSession;
export const makeSession = _mod12603.makeSession;
export const updateSession = _mod12603.updateSession;
export const SessionFlusher = SessionFlusher.SessionFlusher;
export const Scope = ScopeClass.Scope;
export const notifyEventProcessors = notifyEventProcessors.notifyEventProcessors;
export const getEnvelopeEndpointWithUrlEncodedAuth = _mod12634.getEnvelopeEndpointWithUrlEncodedAuth;
export const getReportDialogEndpoint = _mod12634.getReportDialogEndpoint;
export const BaseClient = _mod12635.BaseClient;
export const ServerRuntimeClient = _mod12639.ServerRuntimeClient;
export const initAndBind = _mod12642.initAndBind;
export const setCurrentClient = _mod12642.setCurrentClient;
export const createTransport = _mod12643.createTransport;
export const makeOfflineTransport = _mod12646.makeOfflineTransport;
export const makeMultiplexedTransport = _mod12647.makeMultiplexedTransport;
export const addIntegration = _mod12636.addIntegration;
export const defineIntegration = _mod12636.defineIntegration;
export const getIntegrationsToSetup = _mod12636.getIntegrationsToSetup;
export const applyScopeDataToEvent = applyScopeDataToEvent.applyScopeDataToEvent;
export const mergeScopeData = applyScopeDataToEvent.mergeScopeData;
export const prepareEvent = _mod12629.prepareEvent;
export const createCheckInEnvelope = _mod12641.createCheckInEnvelope;
export const hasTracingEnabled = _mod12612.hasTracingEnabled;
export const isSentryRequestUrl = _mod12648.isSentryRequestUrl;
export const handleCallbackErrors = _mod12615.handleCallbackErrors;
export const parameterize = _mod12649.parameterize;
export const addChildSpanToSpan = spanTimeInputToSeconds.addChildSpanToSpan;
export const getActiveSpan = spanTimeInputToSeconds.getActiveSpan;
export const getRootSpan = spanTimeInputToSeconds.getRootSpan;
export const getSpanDescendants = spanTimeInputToSeconds.getSpanDescendants;
export const getStatusMessage = spanTimeInputToSeconds.getStatusMessage;
export const spanIsSampled = spanTimeInputToSeconds.spanIsSampled;
export const spanTimeInputToSeconds = spanTimeInputToSeconds.spanTimeInputToSeconds;
export const spanToJSON = spanTimeInputToSeconds.spanToJSON;
export const spanToTraceContext = spanTimeInputToSeconds.spanToTraceContext;
export const spanToTraceHeader = spanTimeInputToSeconds.spanToTraceHeader;
export const updateSpanName = spanTimeInputToSeconds.updateSpanName;
export const parseSampleRate = _mod12620.parseSampleRate;
export const applySdkMetadata = _mod12650.applySdkMetadata;
export const getTraceData = _mod12651.getTraceData;
export const getTraceMetaTags = _mod12652.getTraceMetaTags;
export const DEFAULT_ENVIRONMENT = _mod12617.DEFAULT_ENVIRONMENT;
export const addBreadcrumb = _mod12653.addBreadcrumb;
export const functionToStringIntegration = _mod12654.functionToStringIntegration;
export const inboundFiltersIntegration = _getEventFilterUrl.inboundFiltersIntegration;
export const linkedErrorsIntegration = _mod12656.linkedErrorsIntegration;
export const moduleMetadataIntegration = _mod12658.moduleMetadataIntegration;
export const requestDataIntegration = _mod12660.requestDataIntegration;
export const captureConsoleIntegration = _mod12665.captureConsoleIntegration;
export const debugIntegration = debugIntegration.debugIntegration;
export const dedupeIntegration = _mod12669.dedupeIntegration;
export const extraErrorDataIntegration = extraErrorDataIntegration.extraErrorDataIntegration;
export const rewriteFramesIntegration = _mod12671.rewriteFramesIntegration;
export const sessionTimingIntegration = sessionTimingIntegration.sessionTimingIntegration;
export const zodErrorsIntegration = _mod12674.zodErrorsIntegration;
export const thirdPartyErrorFilterIntegration = _mod12675.thirdPartyErrorFilterIntegration;
export const metrics = _mod12676.metrics;
export const profiler = _mod12678.profiler;
export const metricsDefault = metricsDefault.metricsDefault;
export const BrowserMetricsAggregator = BrowserMetricsAggregator.BrowserMetricsAggregator;
export const getMetricSummaryJsonForSpan = _mod12596.getMetricSummaryJsonForSpan;
export const addTracingHeadersToFetchRequest = _mod12685.addTracingHeadersToFetchRequest;
export const instrumentFetchRequest = _mod12685.instrumentFetchRequest;
export const trpcMiddleware = _mod12686.trpcMiddleware;
export const captureFeedback = _mod12687.captureFeedback;
export const getCurrentHub = _mod12688.getCurrentHub;
export const getCurrentHubShim = _mod12688.getCurrentHubShim;
export const applyAggregateErrorsToEvent = _mod12657.applyAggregateErrorsToEvent;
export const flatten = _mod12689.flatten;
export const getBreadcrumbLogLevelFromHttpStatusCode = _mod12690.getBreadcrumbLogLevelFromHttpStatusCode;
export const getComponentName = _mod12588.getComponentName;
export const getDomElement = _mod12588.getDomElement;
export const getLocationHref = _mod12588.getLocationHref;
export const htmlTreeAsString = _mod12588.htmlTreeAsString;
export const dsnFromString = _mod12627.dsnFromString;
export const dsnToString = _mod12627.dsnToString;
export const makeDsn = _mod12627.makeDsn;
export const SentryError = _mod12637.SentryError;
export const GLOBAL_OBJ = _mod12581.GLOBAL_OBJ;
export const getGlobalSingleton = _mod12581.getGlobalSingleton;
export const addConsoleInstrumentationHandler = _mod12666.addConsoleInstrumentationHandler;
export const addFetchEndInstrumentationHandler = _mod12691.addFetchEndInstrumentationHandler;
export const addFetchInstrumentationHandler = _mod12691.addFetchInstrumentationHandler;
export const addGlobalErrorInstrumentationHandler = _mod12577.addGlobalErrorInstrumentationHandler;
export const addGlobalUnhandledRejectionInstrumentationHandler = _mod12584.addGlobalUnhandledRejectionInstrumentationHandler;
export const addHandler = _mod12578.addHandler;
export const maybeInstrument = _mod12578.maybeInstrument;
export const resetInstrumentationHandlers = _mod12578.resetInstrumentationHandlers;
export const triggerHandlers = _mod12578.triggerHandlers;
export const isDOMError = _mod12587.isDOMError;
export const isDOMException = _mod12587.isDOMException;
export const isElement = _mod12587.isElement;
export const isError = _mod12587.isError;
export const isErrorEvent = _mod12587.isErrorEvent;
export const isEvent = _mod12587.isEvent;
export const isInstanceOf = _mod12587.isInstanceOf;
export const isParameterizedString = _mod12587.isParameterizedString;
export const isPlainObject = _mod12587.isPlainObject;
export const isPrimitive = _mod12587.isPrimitive;
export const isRegExp = _mod12587.isRegExp;
export const isString = _mod12587.isString;
export const isSyntheticEvent = _mod12587.isSyntheticEvent;
export const isThenable = _mod12587.isThenable;
export const isVueViewModel = _mod12587.isVueViewModel;
export const isBrowser = _mod12693.isBrowser;
export const CONSOLE_LEVELS = _mod12580.CONSOLE_LEVELS;
export const consoleSandbox = _mod12580.consoleSandbox;
export const logger = _mod12580.logger;
export const originalConsoleMethods = _mod12580.originalConsoleMethods;
export const memoBuilder = memoBuilder.memoBuilder;
export const addContextToFrame = _mod12591.addContextToFrame;
export const addExceptionMechanism = _mod12591.addExceptionMechanism;
export const addExceptionTypeValue = _mod12591.addExceptionTypeValue;
export const arrayify = _mod12591.arrayify;
export const checkOrSetAlreadyCaught = _mod12591.checkOrSetAlreadyCaught;
export const getEventDescription = _mod12591.getEventDescription;
export const parseSemver = _mod12591.parseSemver;
export const uuid4 = _mod12591.uuid4;
export const dynamicRequire = _mod12694.dynamicRequire;
export const isNodeEnv = _mod12694.isNodeEnv;
export const loadModule = _mod12694.loadModule;
export const normalize = _mod12625.normalize;
export const normalizeToSize = _mod12625.normalizeToSize;
export const normalizeUrlToBase = _mod12625.normalizeUrlToBase;
export const addNonEnumerableProperty = _mod12586.addNonEnumerableProperty;
export const convertToPlainObject = _mod12586.convertToPlainObject;
export const dropUndefinedKeys = _mod12586.dropUndefinedKeys;
export const extractExceptionKeysForMessage = _mod12586.extractExceptionKeysForMessage;
export const fill = _mod12586.fill;
export const getOriginalFunction = _mod12586.getOriginalFunction;
export const markFunctionWrapped = _mod12586.markFunctionWrapped;
export const objectify = _mod12586.objectify;
export const urlEncode = _mod12586.urlEncode;
export const basename = _mod12672.basename;
export const dirname = _mod12672.dirname;
export const isAbsolute = _mod12672.isAbsolute;
export const join = _mod12672.join;
export const normalizePath = _mod12672.normalizePath;
export const relative = _mod12672.relative;
export const resolve = _mod12672.resolve;
export const makePromiseBuffer = _mod12644.makePromiseBuffer;
export const DEFAULT_USER_INCLUDES = extractRequestData.DEFAULT_USER_INCLUDES;
export const addNormalizedRequestDataToEvent = extractRequestData.addNormalizedRequestDataToEvent;
export const addRequestDataToEvent = extractRequestData.addRequestDataToEvent;
export const extractPathForTransaction = extractRequestData.extractPathForTransaction;
export const extractQueryParamsFromUrl = extractRequestData.extractQueryParamsFromUrl;
export const extractRequestData = extractRequestData.extractRequestData;
export const headersToDict = extractRequestData.headersToDict;
export const httpRequestToRequestData = extractRequestData.httpRequestToRequestData;
export const winterCGHeadersToDict = extractRequestData.winterCGHeadersToDict;
export const winterCGRequestToRequestData = extractRequestData.winterCGRequestToRequestData;
export const severityLevelFromString = _mod12667.severityLevelFromString;
export const validSeverityLevels = _mod12667.validSeverityLevels;
export const UNKNOWN_FUNCTION = stackParserFromStackParserOptions.UNKNOWN_FUNCTION;
export const createStackParser = stackParserFromStackParserOptions.createStackParser;
export const getFramesFromEvent = stackParserFromStackParserOptions.getFramesFromEvent;
export const getFunctionName = stackParserFromStackParserOptions.getFunctionName;
export const stackParserFromStackParserOptions = stackParserFromStackParserOptions.stackParserFromStackParserOptions;
export const stripSentryFramesAndReverse = stackParserFromStackParserOptions.stripSentryFramesAndReverse;
export const filenameIsInApp = _mod12696.filenameIsInApp;
export const node = _mod12696.node;
export const nodeStackLineParser = _mod12696.nodeStackLineParser;
export const isMatchingPattern = _mod12589.isMatchingPattern;
export const safeJoin = _mod12589.safeJoin;
export const snipLine = _mod12589.snipLine;
export const stringMatchesSomePattern = _mod12589.stringMatchesSomePattern;
export const truncate = _mod12589.truncate;
export const isNativeFunction = supportsFetch.isNativeFunction;
export const supportsDOMError = supportsFetch.supportsDOMError;
export const supportsDOMException = supportsFetch.supportsDOMException;
export const supportsErrorEvent = supportsFetch.supportsErrorEvent;
export const supportsFetch = supportsFetch.supportsFetch;
export const supportsNativeFetch = supportsFetch.supportsNativeFetch;
export const supportsReferrerPolicy = supportsFetch.supportsReferrerPolicy;
export const supportsReportingObserver = supportsFetch.supportsReportingObserver;
export const SyncPromise = _mod12604.SyncPromise;
export const rejectedSyncPromise = _mod12604.rejectedSyncPromise;
export const resolvedSyncPromise = _mod12604.resolvedSyncPromise;
export const _browserPerformanceTimeOriginMode = require("module_12594")._browserPerformanceTimeOriginMode;
export const browserPerformanceTimeOrigin = require("module_12594").browserPerformanceTimeOrigin;
export const dateTimestampInSeconds = require("module_12594").dateTimestampInSeconds;
export const timestampInSeconds = require("module_12594").timestampInSeconds;
export const TRACEPARENT_REGEXP = _mod12592.TRACEPARENT_REGEXP;
export const extractTraceparentData = _mod12592.extractTraceparentData;
export const generateSentryTraceHeader = _mod12592.generateSentryTraceHeader;
export const propagationContextFromHeaders = _mod12592.propagationContextFromHeaders;
export const getSDKSource = _mod12695.getSDKSource;
export const isBrowserBundle = _mod12695.isBrowserBundle;
export const addItemToEnvelope = _mod12624.addItemToEnvelope;
export const createAttachmentEnvelopeItem = _mod12624.createAttachmentEnvelopeItem;
export const createEnvelope = _mod12624.createEnvelope;
export const createEventEnvelopeHeaders = _mod12624.createEventEnvelopeHeaders;
export const createSpanEnvelopeItem = _mod12624.createSpanEnvelopeItem;
export const envelopeContainsItemType = _mod12624.envelopeContainsItemType;
export const envelopeItemTypeToDataCategory = _mod12624.envelopeItemTypeToDataCategory;
export const forEachEnvelopeItem = _mod12624.forEachEnvelopeItem;
export const getSdkMetadataForEnvelopeHeader = _mod12624.getSdkMetadataForEnvelopeHeader;
export const parseEnvelope = _mod12624.parseEnvelope;
export const serializeEnvelope = _mod12624.serializeEnvelope;
export const createClientReportEnvelope = _mod12638.createClientReportEnvelope;
export const DEFAULT_RETRY_AFTER = _mod12645.DEFAULT_RETRY_AFTER;
export const disabledUntil = _mod12645.disabledUntil;
export const isRateLimited = _mod12645.isRateLimited;
export const parseRetryAfterHeader = _mod12645.parseRetryAfterHeader;
export const updateRateLimits = _mod12645.updateRateLimits;
export const BAGGAGE_HEADER_NAME = BAGGAGE_HEADER_NAME.BAGGAGE_HEADER_NAME;
export const MAX_BAGGAGE_STRING_LENGTH = BAGGAGE_HEADER_NAME.MAX_BAGGAGE_STRING_LENGTH;
export const SENTRY_BAGGAGE_KEY_PREFIX = BAGGAGE_HEADER_NAME.SENTRY_BAGGAGE_KEY_PREFIX;
export const SENTRY_BAGGAGE_KEY_PREFIX_REGEX = BAGGAGE_HEADER_NAME.SENTRY_BAGGAGE_KEY_PREFIX_REGEX;
export const baggageHeaderToDynamicSamplingContext = BAGGAGE_HEADER_NAME.baggageHeaderToDynamicSamplingContext;
export const dynamicSamplingContextToSentryBaggageHeader = BAGGAGE_HEADER_NAME.dynamicSamplingContextToSentryBaggageHeader;
export const parseBaggageHeader = BAGGAGE_HEADER_NAME.parseBaggageHeader;
export const getNumberOfUrlSegments = stripUrlQueryAndFragment.getNumberOfUrlSegments;
export const getSanitizedUrlString = stripUrlQueryAndFragment.getSanitizedUrlString;
export const parseUrl = stripUrlQueryAndFragment.parseUrl;
export const stripUrlQueryAndFragment = stripUrlQueryAndFragment.stripUrlQueryAndFragment;
export const makeFifoCache = _mod12697.makeFifoCache;
export const eventFromMessage = eventFromMessage.eventFromMessage;
export const eventFromUnknownInput = eventFromMessage.eventFromUnknownInput;
export const exceptionFromError = eventFromMessage.exceptionFromError;
export const parseStackFrames = eventFromMessage.parseStackFrames;
export const callFrameToStackFrame = _mod12698.callFrameToStackFrame;
export const watchdogTimer = _mod12698.watchdogTimer;
export const LRUMap = _mod12699.LRUMap;
export const generatePropagationContext = generatePropagationContext.generatePropagationContext;
export const generateSpanId = generatePropagationContext.generateSpanId;
export const generateTraceId = generatePropagationContext.generateTraceId;
export const vercelWaitUntil = _mod12700.vercelWaitUntil;
export const SDK_VERSION = _mod12582.SDK_VERSION;
export const getDebugImagesForResources = _mod12632.getDebugImagesForResources;
export const getFilenameToDebugIdMap = _mod12632.getFilenameToDebugIdMap;
export const escapeStringForRegex = _mod12701.escapeStringForRegex;
export const supportsHistory = supportsHistory.supportsHistory;
export const _asyncNullishCoalesce = _asyncNullishCoalesce2._asyncNullishCoalesce;
export const _asyncOptionalChain = _asyncOptionalChain2._asyncOptionalChain;
export const _asyncOptionalChainDelete = _asyncOptionalChainDelete2._asyncOptionalChainDelete;
export const _nullishCoalesce = _nullishCoalesce._nullishCoalesce;
export const _optionalChain = _optionalChain._optionalChain;
export const _optionalChainDelete = _optionalChainDelete._optionalChainDelete;