// _runtime/metro/12792__.js
import errorCallback from "../12793_errorCallback.js";
import _mod12794 from "12794__.js";
import _mod12795 from "12795__.js";
import _mod12797 from "12797__.js";
import _mod12798 from "12798__.js";
import _mod12799 from "12799__.js";
import stackParserFromStackParserOptions from "../12800_stackParserFromStackParserOptions.js";
import _mod12801 from "12801__.js";
import spanTimeInputToSeconds from "../12802_spanTimeInputToSeconds.js";
import _mod12803 from "12803__.js";
import _mod12804 from "12804__.js";
import _mod12805 from "12805__.js";
import _mod12806 from "12806__.js";
import generatePropagationContext from "../12807_generatePropagationContext.js";
import _mod12808 from "12808__.js";
import _mod12809 from "12809__.js";
import BAGGAGE_HEADER_NAME from "../12810_BAGGAGE_HEADER_NAME.js";
import _mod12812 from "12812__.js";
import _mod12813 from "12813__.js";
import _mod12814 from "12814__.js";
import _mod12815 from "12815__.js";
import _mod12816 from "12816__.js";
import ScopeClass from "../12818_ScopeClass.js";
import _mod12820 from "12820__.js";
import _mod12821 from "12821__.js";
import _mod12823 from "12823__.js";
import _mod12824 from "12824__.js";
import _mod12826 from "12826__.js";
import _mod12827 from "12827__.js";
import _mod12828 from "12828__.js";
import _mod12829 from "12829__.js";
import _mod12830 from "12830__.js";
import _mod12831 from "12831__.js";
import _mod12832 from "12832__.js";
import _mod12833 from "12833__.js";
import _mod12834 from "12834__.js";
import _mod12835 from "12835__.js";
import _mod12836 from "12836__.js";
import _mod12837 from "12837__.js";
import _mod12838 from "12838__.js";
import _mod12839 from "12839__.js";
import _mod12840 from "12840__.js";
import _mod12841 from "12841__.js";
import _mod12842 from "12842__.js";
import memoBuilder from "../12843_memoBuilder.js";
import _mod12844 from "12844__.js";
import _flush from "../12845__flush.js";
import _mod12846 from "12846__.js";
import applyScopeDataToEvent from "../12847_applyScopeDataToEvent.js";
import notifyEventProcessors from "../12848_notifyEventProcessors.js";
import _mod12849 from "12849__.js";
import SessionFlusher from "../12850_SessionFlusher.js";
import _mod12851 from "12851__.js";
import _mod12852 from "12852__.js";
import _mod12853 from "12853__.js";
import _mod12854 from "12854__.js";
import _mod12855 from "12855__.js";
import _mod12856 from "12856__.js";
import eventFromMessage from "../12857_eventFromMessage.js";
import _mod12858 from "12858__.js";
import _mod12859 from "12859__.js";
import _mod12860 from "12860__.js";
import _mod12861 from "12861__.js";
import _mod12862 from "12862__.js";
import _mod12863 from "12863__.js";
import _mod12864 from "12864__.js";
import _mod12865 from "12865__.js";
import _mod12866 from "12866__.js";
import _mod12867 from "12867__.js";
import _mod12868 from "12868__.js";
import _mod12869 from "12869__.js";
import _mod12870 from "12870__.js";
import _mod12871 from "12871__.js";
import _getEventFilterUrl from "../12872__getEventFilterUrl.js";
import _mod12873 from "12873__.js";
import _mod12874 from "12874__.js";
import _mod12875 from "12875__.js";
import _mod12877 from "12877__.js";
import extractRequestData from "../12878_extractRequestData.js";
import stripUrlQueryAndFragment from "../12879_stripUrlQueryAndFragment.js";
import _mod12882 from "12882__.js";
import _mod12883 from "12883__.js";
import _mod12884 from "12884__.js";
import debugIntegration from "../12885_debugIntegration.js";
import _mod12886 from "12886__.js";
import extraErrorDataIntegration from "../12887_extraErrorDataIntegration.js";
import _mod12888 from "12888__.js";
import _mod12889 from "12889__.js";
import sessionTimingIntegration from "../12890_sessionTimingIntegration.js";
import _mod12891 from "12891__.js";
import _mod12892 from "12892__.js";
import _mod12893 from "12893__.js";
import _mod12895 from "12895__.js";
import metricsDefault from "../12896_metricsDefault.js";
import BrowserMetricsAggregator from "../12901_BrowserMetricsAggregator.js";
import _mod12902 from "12902__.js";
import _mod12903 from "12903__.js";
import _mod12904 from "12904__.js";
import _mod12905 from "12905__.js";
import _mod12906 from "12906__.js";
import _mod12907 from "12907__.js";
import _mod12908 from "12908__.js";
import supportsFetch from "../12909_supportsFetch.js";
import _mod12910 from "12910__.js";
import _mod12911 from "12911__.js";
import _mod12912 from "12912__.js";
import _mod12913 from "12913__.js";
import _mod12914 from "12914__.js";
import _mod12915 from "12915__.js";
import _mod12916 from "12916__.js";
import _mod12917 from "12917__.js";
import _mod12918 from "12918__.js";
import supportsHistory from "../12919_supportsHistory.js";
import _asyncNullishCoalesce2 from "../12920__asyncNullishCoalesce2.js";
import _nullishCoalesce from "../12921__nullishCoalesce.js";
import _asyncOptionalChain2 from "../12922__asyncOptionalChain2.js";
import _asyncOptionalChainDelete2 from "../12923__asyncOptionalChainDelete2.js";
import _optionalChain from "../12924__optionalChain.js";
import _optionalChainDelete from "../12925__optionalChainDelete.js";

export const registerSpanErrorInstrumentation = errorCallback.registerSpanErrorInstrumentation;
export const getCapturedScopesOnSpan = _mod12826.getCapturedScopesOnSpan;
export const setCapturedScopesOnSpan = _mod12826.setCapturedScopesOnSpan;
export const addTracingExtensions = _mod12827.addTracingExtensions;
export const TRACING_DEFAULTS = _mod12828.TRACING_DEFAULTS;
export const startIdleSpan = _mod12828.startIdleSpan;
export const SentrySpan = _mod12838.SentrySpan;
export const SentryNonRecordingSpan = _mod12830.SentryNonRecordingSpan;
export const SPAN_STATUS_ERROR = _mod12814.SPAN_STATUS_ERROR;
export const SPAN_STATUS_OK = _mod12814.SPAN_STATUS_OK;
export const SPAN_STATUS_UNSET = _mod12814.SPAN_STATUS_UNSET;
export const getSpanStatusFromHttpCode = _mod12814.getSpanStatusFromHttpCode;
export const setHttpStatus = _mod12814.setHttpStatus;
export const continueTrace = _mod12831.continueTrace;
export const startInactiveSpan = _mod12831.startInactiveSpan;
export const startNewTrace = _mod12831.startNewTrace;
export const startSpan = _mod12831.startSpan;
export const startSpanManual = _mod12831.startSpanManual;
export const suppressTracing = _mod12831.suppressTracing;
export const withActiveSpan = _mod12831.withActiveSpan;
export const getDynamicSamplingContextFromClient = _mod12833.getDynamicSamplingContextFromClient;
export const getDynamicSamplingContextFromScope = _mod12833.getDynamicSamplingContextFromScope;
export const getDynamicSamplingContextFromSpan = _mod12833.getDynamicSamplingContextFromSpan;
export const spanToBaggageHeader = _mod12833.spanToBaggageHeader;
export const setMeasurement = _mod12839.setMeasurement;
export const timedEventsToMeasurements = _mod12839.timedEventsToMeasurements;
export const sampleSpan = _mod12836.sampleSpan;
export const logSpanEnd = _mod12835.logSpanEnd;
export const logSpanStart = _mod12835.logSpanStart;
export const SEMANTIC_ATTRIBUTE_CACHE_HIT = _mod12812.SEMANTIC_ATTRIBUTE_CACHE_HIT;
export const SEMANTIC_ATTRIBUTE_CACHE_ITEM_SIZE = _mod12812.SEMANTIC_ATTRIBUTE_CACHE_ITEM_SIZE;
export const SEMANTIC_ATTRIBUTE_CACHE_KEY = _mod12812.SEMANTIC_ATTRIBUTE_CACHE_KEY;
export const SEMANTIC_ATTRIBUTE_EXCLUSIVE_TIME = _mod12812.SEMANTIC_ATTRIBUTE_EXCLUSIVE_TIME;
export const SEMANTIC_ATTRIBUTE_HTTP_REQUEST_METHOD = _mod12812.SEMANTIC_ATTRIBUTE_HTTP_REQUEST_METHOD;
export const SEMANTIC_ATTRIBUTE_PROFILE_ID = _mod12812.SEMANTIC_ATTRIBUTE_PROFILE_ID;
export const SEMANTIC_ATTRIBUTE_SENTRY_CUSTOM_SPAN_NAME = _mod12812.SEMANTIC_ATTRIBUTE_SENTRY_CUSTOM_SPAN_NAME;
export const SEMANTIC_ATTRIBUTE_SENTRY_IDLE_SPAN_FINISH_REASON =
  _mod12812.SEMANTIC_ATTRIBUTE_SENTRY_IDLE_SPAN_FINISH_REASON;
export const SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_UNIT = _mod12812.SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_UNIT;
export const SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_VALUE = _mod12812.SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_VALUE;
export const SEMANTIC_ATTRIBUTE_SENTRY_OP = _mod12812.SEMANTIC_ATTRIBUTE_SENTRY_OP;
export const SEMANTIC_ATTRIBUTE_SENTRY_ORIGIN = _mod12812.SEMANTIC_ATTRIBUTE_SENTRY_ORIGIN;
export const SEMANTIC_ATTRIBUTE_SENTRY_SAMPLE_RATE = _mod12812.SEMANTIC_ATTRIBUTE_SENTRY_SAMPLE_RATE;
export const SEMANTIC_ATTRIBUTE_SENTRY_SOURCE = _mod12812.SEMANTIC_ATTRIBUTE_SENTRY_SOURCE;
export const SEMANTIC_ATTRIBUTE_URL_FULL = _mod12812.SEMANTIC_ATTRIBUTE_URL_FULL;
export const createEventEnvelope = _mod12840.createEventEnvelope;
export const createSessionEnvelope = _mod12840.createSessionEnvelope;
export const createSpanEnvelope = _mod12840.createSpanEnvelope;
export const addEventProcessor = _flush.addEventProcessor;
export const captureCheckIn = _flush.captureCheckIn;
export const captureEvent = _flush.captureEvent;
export const captureException = _flush.captureException;
export const captureMessage = _flush.captureMessage;
export const captureSession = _flush.captureSession;
export const close = _flush.close;
export const endSession = _flush.endSession;
export const flush = _flush.flush;
export const isEnabled = _flush.isEnabled;
export const isInitialized = _flush.isInitialized;
export const lastEventId = _flush.lastEventId;
export const setContext = _flush.setContext;
export const setExtra = _flush.setExtra;
export const setExtras = _flush.setExtras;
export const setTag = _flush.setTag;
export const setTags = _flush.setTags;
export const setUser = _flush.setUser;
export const startSession = _flush.startSession;
export const withMonitor = _flush.withMonitor;
export const getClient = _mod12824.getClient;
export const getCurrentScope = _mod12824.getCurrentScope;
export const getGlobalScope = _mod12824.getGlobalScope;
export const getIsolationScope = _mod12824.getIsolationScope;
export const getTraceContextFromScope = _mod12824.getTraceContextFromScope;
export const withIsolationScope = _mod12824.withIsolationScope;
export const withScope = _mod12824.withScope;
export const getDefaultCurrentScope = _mod12823.getDefaultCurrentScope;
export const getDefaultIsolationScope = _mod12823.getDefaultIsolationScope;
export const setAsyncContextStrategy = _mod12816.setAsyncContextStrategy;
export const getMainCarrier = _mod12815.getMainCarrier;
export const closeSession = _mod12820.closeSession;
export const makeSession = _mod12820.makeSession;
export const updateSession = _mod12820.updateSession;
export const SessionFlusher = SessionFlusher.SessionFlusher;
export const Scope = ScopeClass.Scope;
export const notifyEventProcessors = notifyEventProcessors.notifyEventProcessors;
export const getEnvelopeEndpointWithUrlEncodedAuth = _mod12851.getEnvelopeEndpointWithUrlEncodedAuth;
export const getReportDialogEndpoint = _mod12851.getReportDialogEndpoint;
export const BaseClient = _mod12852.BaseClient;
export const ServerRuntimeClient = _mod12856.ServerRuntimeClient;
export const initAndBind = _mod12859.initAndBind;
export const setCurrentClient = _mod12859.setCurrentClient;
export const createTransport = _mod12860.createTransport;
export const makeOfflineTransport = _mod12863.makeOfflineTransport;
export const makeMultiplexedTransport = _mod12864.makeMultiplexedTransport;
export const addIntegration = _mod12853.addIntegration;
export const defineIntegration = _mod12853.defineIntegration;
export const getIntegrationsToSetup = _mod12853.getIntegrationsToSetup;
export const applyScopeDataToEvent = applyScopeDataToEvent.applyScopeDataToEvent;
export const mergeScopeData = applyScopeDataToEvent.mergeScopeData;
export const prepareEvent = _mod12846.prepareEvent;
export const createCheckInEnvelope = _mod12858.createCheckInEnvelope;
export const hasTracingEnabled = _mod12829.hasTracingEnabled;
export const isSentryRequestUrl = _mod12865.isSentryRequestUrl;
export const handleCallbackErrors = _mod12832.handleCallbackErrors;
export const parameterize = _mod12866.parameterize;
export const addChildSpanToSpan = spanTimeInputToSeconds.addChildSpanToSpan;
export const getActiveSpan = spanTimeInputToSeconds.getActiveSpan;
export const getRootSpan = spanTimeInputToSeconds.getRootSpan;
export const getSpanDescendants = spanTimeInputToSeconds.getSpanDescendants;
export const getStatusMessage = spanTimeInputToSeconds.getStatusMessage;
export const spanIsSampled = spanTimeInputToSeconds.spanIsSampled;
export const spanTimeInputToSeconds = spanTimeInputToSeconds.spanTimeInputToSeconds;
export const spanToJSON = spanTimeInputToSeconds.spanToJSON;
export const spanToTraceContext = spanTimeInputToSeconds.spanToTraceContext;
export const spanToTraceHeader = spanTimeInputToSeconds.spanToTraceHeader;
export const updateSpanName = spanTimeInputToSeconds.updateSpanName;
export const parseSampleRate = _mod12837.parseSampleRate;
export const applySdkMetadata = _mod12867.applySdkMetadata;
export const getTraceData = _mod12868.getTraceData;
export const getTraceMetaTags = _mod12869.getTraceMetaTags;
export const DEFAULT_ENVIRONMENT = _mod12834.DEFAULT_ENVIRONMENT;
export const addBreadcrumb = _mod12870.addBreadcrumb;
export const functionToStringIntegration = _mod12871.functionToStringIntegration;
export const inboundFiltersIntegration = _getEventFilterUrl.inboundFiltersIntegration;
export const linkedErrorsIntegration = _mod12873.linkedErrorsIntegration;
export const moduleMetadataIntegration = _mod12875.moduleMetadataIntegration;
export const requestDataIntegration = _mod12877.requestDataIntegration;
export const captureConsoleIntegration = _mod12882.captureConsoleIntegration;
export const debugIntegration = debugIntegration.debugIntegration;
export const dedupeIntegration = _mod12886.dedupeIntegration;
export const extraErrorDataIntegration = extraErrorDataIntegration.extraErrorDataIntegration;
export const rewriteFramesIntegration = _mod12888.rewriteFramesIntegration;
export const sessionTimingIntegration = sessionTimingIntegration.sessionTimingIntegration;
export const zodErrorsIntegration = _mod12891.zodErrorsIntegration;
export const thirdPartyErrorFilterIntegration = _mod12892.thirdPartyErrorFilterIntegration;
export const metrics = _mod12893.metrics;
export const profiler = _mod12895.profiler;
export const metricsDefault = metricsDefault.metricsDefault;
export const BrowserMetricsAggregator = BrowserMetricsAggregator.BrowserMetricsAggregator;
export const getMetricSummaryJsonForSpan = _mod12813.getMetricSummaryJsonForSpan;
export const addTracingHeadersToFetchRequest = _mod12902.addTracingHeadersToFetchRequest;
export const instrumentFetchRequest = _mod12902.instrumentFetchRequest;
export const trpcMiddleware = _mod12903.trpcMiddleware;
export const captureFeedback = _mod12904.captureFeedback;
export const getCurrentHub = _mod12905.getCurrentHub;
export const getCurrentHubShim = _mod12905.getCurrentHubShim;
export const applyAggregateErrorsToEvent = _mod12874.applyAggregateErrorsToEvent;
export const flatten = _mod12906.flatten;
export const getBreadcrumbLogLevelFromHttpStatusCode = _mod12907.getBreadcrumbLogLevelFromHttpStatusCode;
export const getComponentName = _mod12805.getComponentName;
export const getDomElement = _mod12805.getDomElement;
export const getLocationHref = _mod12805.getLocationHref;
export const htmlTreeAsString = _mod12805.htmlTreeAsString;
export const dsnFromString = _mod12844.dsnFromString;
export const dsnToString = _mod12844.dsnToString;
export const makeDsn = _mod12844.makeDsn;
export const SentryError = _mod12854.SentryError;
export const GLOBAL_OBJ = _mod12798.GLOBAL_OBJ;
export const getGlobalSingleton = _mod12798.getGlobalSingleton;
export const addConsoleInstrumentationHandler = _mod12883.addConsoleInstrumentationHandler;
export const addFetchEndInstrumentationHandler = _mod12908.addFetchEndInstrumentationHandler;
export const addFetchInstrumentationHandler = _mod12908.addFetchInstrumentationHandler;
export const addGlobalErrorInstrumentationHandler = _mod12794.addGlobalErrorInstrumentationHandler;
export const addGlobalUnhandledRejectionInstrumentationHandler =
  _mod12801.addGlobalUnhandledRejectionInstrumentationHandler;
export const addHandler = _mod12795.addHandler;
export const maybeInstrument = _mod12795.maybeInstrument;
export const resetInstrumentationHandlers = _mod12795.resetInstrumentationHandlers;
export const triggerHandlers = _mod12795.triggerHandlers;
export const isDOMError = _mod12804.isDOMError;
export const isDOMException = _mod12804.isDOMException;
export const isElement = _mod12804.isElement;
export const isError = _mod12804.isError;
export const isErrorEvent = _mod12804.isErrorEvent;
export const isEvent = _mod12804.isEvent;
export const isInstanceOf = _mod12804.isInstanceOf;
export const isParameterizedString = _mod12804.isParameterizedString;
export const isPlainObject = _mod12804.isPlainObject;
export const isPrimitive = _mod12804.isPrimitive;
export const isRegExp = _mod12804.isRegExp;
export const isString = _mod12804.isString;
export const isSyntheticEvent = _mod12804.isSyntheticEvent;
export const isThenable = _mod12804.isThenable;
export const isVueViewModel = _mod12804.isVueViewModel;
export const isBrowser = _mod12910.isBrowser;
export const CONSOLE_LEVELS = _mod12797.CONSOLE_LEVELS;
export const consoleSandbox = _mod12797.consoleSandbox;
export const logger = _mod12797.logger;
export const originalConsoleMethods = _mod12797.originalConsoleMethods;
export const memoBuilder = memoBuilder.memoBuilder;
export const addContextToFrame = _mod12808.addContextToFrame;
export const addExceptionMechanism = _mod12808.addExceptionMechanism;
export const addExceptionTypeValue = _mod12808.addExceptionTypeValue;
export const arrayify = _mod12808.arrayify;
export const checkOrSetAlreadyCaught = _mod12808.checkOrSetAlreadyCaught;
export const getEventDescription = _mod12808.getEventDescription;
export const parseSemver = _mod12808.parseSemver;
export const uuid4 = _mod12808.uuid4;
export const dynamicRequire = _mod12911.dynamicRequire;
export const isNodeEnv = _mod12911.isNodeEnv;
export const loadModule = _mod12911.loadModule;
export const normalize = _mod12842.normalize;
export const normalizeToSize = _mod12842.normalizeToSize;
export const normalizeUrlToBase = _mod12842.normalizeUrlToBase;
export const addNonEnumerableProperty = _mod12803.addNonEnumerableProperty;
export const convertToPlainObject = _mod12803.convertToPlainObject;
export const dropUndefinedKeys = _mod12803.dropUndefinedKeys;
export const extractExceptionKeysForMessage = _mod12803.extractExceptionKeysForMessage;
export const fill = _mod12803.fill;
export const getOriginalFunction = _mod12803.getOriginalFunction;
export const markFunctionWrapped = _mod12803.markFunctionWrapped;
export const objectify = _mod12803.objectify;
export const urlEncode = _mod12803.urlEncode;
export const basename = _mod12889.basename;
export const dirname = _mod12889.dirname;
export const isAbsolute = _mod12889.isAbsolute;
export const join = _mod12889.join;
export const normalizePath = _mod12889.normalizePath;
export const relative = _mod12889.relative;
export const resolve = _mod12889.resolve;
export const makePromiseBuffer = _mod12861.makePromiseBuffer;
export const DEFAULT_USER_INCLUDES = extractRequestData.DEFAULT_USER_INCLUDES;
export const addNormalizedRequestDataToEvent = extractRequestData.addNormalizedRequestDataToEvent;
export const addRequestDataToEvent = extractRequestData.addRequestDataToEvent;
export const extractPathForTransaction = extractRequestData.extractPathForTransaction;
export const extractQueryParamsFromUrl = extractRequestData.extractQueryParamsFromUrl;
export const extractRequestData = extractRequestData.extractRequestData;
export const headersToDict = extractRequestData.headersToDict;
export const httpRequestToRequestData = extractRequestData.httpRequestToRequestData;
export const winterCGHeadersToDict = extractRequestData.winterCGHeadersToDict;
export const winterCGRequestToRequestData = extractRequestData.winterCGRequestToRequestData;
export const severityLevelFromString = _mod12884.severityLevelFromString;
export const validSeverityLevels = _mod12884.validSeverityLevels;
export const UNKNOWN_FUNCTION = stackParserFromStackParserOptions.UNKNOWN_FUNCTION;
export const createStackParser = stackParserFromStackParserOptions.createStackParser;
export const getFramesFromEvent = stackParserFromStackParserOptions.getFramesFromEvent;
export const getFunctionName = stackParserFromStackParserOptions.getFunctionName;
export const stackParserFromStackParserOptions = stackParserFromStackParserOptions.stackParserFromStackParserOptions;
export const stripSentryFramesAndReverse = stackParserFromStackParserOptions.stripSentryFramesAndReverse;
export const filenameIsInApp = _mod12913.filenameIsInApp;
export const node = _mod12913.node;
export const nodeStackLineParser = _mod12913.nodeStackLineParser;
export const isMatchingPattern = _mod12806.isMatchingPattern;
export const safeJoin = _mod12806.safeJoin;
export const snipLine = _mod12806.snipLine;
export const stringMatchesSomePattern = _mod12806.stringMatchesSomePattern;
export const truncate = _mod12806.truncate;
export const isNativeFunction = supportsFetch.isNativeFunction;
export const supportsDOMError = supportsFetch.supportsDOMError;
export const supportsDOMException = supportsFetch.supportsDOMException;
export const supportsErrorEvent = supportsFetch.supportsErrorEvent;
export const supportsFetch = supportsFetch.supportsFetch;
export const supportsNativeFetch = supportsFetch.supportsNativeFetch;
export const supportsReferrerPolicy = supportsFetch.supportsReferrerPolicy;
export const supportsReportingObserver = supportsFetch.supportsReportingObserver;
export const SyncPromise = _mod12821.SyncPromise;
export const rejectedSyncPromise = _mod12821.rejectedSyncPromise;
export const resolvedSyncPromise = _mod12821.resolvedSyncPromise;
export const _browserPerformanceTimeOriginMode = require("12811__.js")._browserPerformanceTimeOriginMode;
export const browserPerformanceTimeOrigin = require("12811__.js").browserPerformanceTimeOrigin;
export const dateTimestampInSeconds = require("12811__.js").dateTimestampInSeconds;
export const timestampInSeconds = require("12811__.js").timestampInSeconds;
export const TRACEPARENT_REGEXP = _mod12809.TRACEPARENT_REGEXP;
export const extractTraceparentData = _mod12809.extractTraceparentData;
export const generateSentryTraceHeader = _mod12809.generateSentryTraceHeader;
export const propagationContextFromHeaders = _mod12809.propagationContextFromHeaders;
export const getSDKSource = _mod12912.getSDKSource;
export const isBrowserBundle = _mod12912.isBrowserBundle;
export const addItemToEnvelope = _mod12841.addItemToEnvelope;
export const createAttachmentEnvelopeItem = _mod12841.createAttachmentEnvelopeItem;
export const createEnvelope = _mod12841.createEnvelope;
export const createEventEnvelopeHeaders = _mod12841.createEventEnvelopeHeaders;
export const createSpanEnvelopeItem = _mod12841.createSpanEnvelopeItem;
export const envelopeContainsItemType = _mod12841.envelopeContainsItemType;
export const envelopeItemTypeToDataCategory = _mod12841.envelopeItemTypeToDataCategory;
export const forEachEnvelopeItem = _mod12841.forEachEnvelopeItem;
export const getSdkMetadataForEnvelopeHeader = _mod12841.getSdkMetadataForEnvelopeHeader;
export const parseEnvelope = _mod12841.parseEnvelope;
export const serializeEnvelope = _mod12841.serializeEnvelope;
export const createClientReportEnvelope = _mod12855.createClientReportEnvelope;
export const DEFAULT_RETRY_AFTER = _mod12862.DEFAULT_RETRY_AFTER;
export const disabledUntil = _mod12862.disabledUntil;
export const isRateLimited = _mod12862.isRateLimited;
export const parseRetryAfterHeader = _mod12862.parseRetryAfterHeader;
export const updateRateLimits = _mod12862.updateRateLimits;
export const BAGGAGE_HEADER_NAME = BAGGAGE_HEADER_NAME.BAGGAGE_HEADER_NAME;
export const MAX_BAGGAGE_STRING_LENGTH = BAGGAGE_HEADER_NAME.MAX_BAGGAGE_STRING_LENGTH;
export const SENTRY_BAGGAGE_KEY_PREFIX = BAGGAGE_HEADER_NAME.SENTRY_BAGGAGE_KEY_PREFIX;
export const SENTRY_BAGGAGE_KEY_PREFIX_REGEX = BAGGAGE_HEADER_NAME.SENTRY_BAGGAGE_KEY_PREFIX_REGEX;
export const baggageHeaderToDynamicSamplingContext = BAGGAGE_HEADER_NAME.baggageHeaderToDynamicSamplingContext;
export const dynamicSamplingContextToSentryBaggageHeader =
  BAGGAGE_HEADER_NAME.dynamicSamplingContextToSentryBaggageHeader;
export const parseBaggageHeader = BAGGAGE_HEADER_NAME.parseBaggageHeader;
export const getNumberOfUrlSegments = stripUrlQueryAndFragment.getNumberOfUrlSegments;
export const getSanitizedUrlString = stripUrlQueryAndFragment.getSanitizedUrlString;
export const parseUrl = stripUrlQueryAndFragment.parseUrl;
export const stripUrlQueryAndFragment = stripUrlQueryAndFragment.stripUrlQueryAndFragment;
export const makeFifoCache = _mod12914.makeFifoCache;
export const eventFromMessage = eventFromMessage.eventFromMessage;
export const eventFromUnknownInput = eventFromMessage.eventFromUnknownInput;
export const exceptionFromError = eventFromMessage.exceptionFromError;
export const parseStackFrames = eventFromMessage.parseStackFrames;
export const callFrameToStackFrame = _mod12915.callFrameToStackFrame;
export const watchdogTimer = _mod12915.watchdogTimer;
export const LRUMap = _mod12916.LRUMap;
export const generatePropagationContext = generatePropagationContext.generatePropagationContext;
export const generateSpanId = generatePropagationContext.generateSpanId;
export const generateTraceId = generatePropagationContext.generateTraceId;
export const vercelWaitUntil = _mod12917.vercelWaitUntil;
export const SDK_VERSION = _mod12799.SDK_VERSION;
export const getDebugImagesForResources = _mod12849.getDebugImagesForResources;
export const getFilenameToDebugIdMap = _mod12849.getFilenameToDebugIdMap;
export const escapeStringForRegex = _mod12918.escapeStringForRegex;
export const supportsHistory = supportsHistory.supportsHistory;
export const _asyncNullishCoalesce = _asyncNullishCoalesce2._asyncNullishCoalesce;
export const _asyncOptionalChain = _asyncOptionalChain2._asyncOptionalChain;
export const _asyncOptionalChainDelete = _asyncOptionalChainDelete2._asyncOptionalChainDelete;
export const _nullishCoalesce = _nullishCoalesce._nullishCoalesce;
export const _optionalChain = _optionalChain._optionalChain;
export const _optionalChainDelete = _optionalChainDelete._optionalChainDelete;
