// _runtime/metro/12862__.js
import errorCallback from "../12863_errorCallback.js";
import _mod12864 from "12864__.js";
import _mod12865 from "12865__.js";
import _mod12867 from "12867__.js";
import _mod12868 from "12868__.js";
import _mod12869 from "12869__.js";
import stackParserFromStackParserOptions from "../12870_stackParserFromStackParserOptions.js";
import _mod12871 from "12871__.js";
import spanTimeInputToSeconds from "../12872_spanTimeInputToSeconds.js";
import _mod12873 from "12873__.js";
import _mod12874 from "12874__.js";
import _mod12875 from "12875__.js";
import _mod12876 from "12876__.js";
import generatePropagationContext from "../12877_generatePropagationContext.js";
import _mod12878 from "12878__.js";
import _mod12879 from "12879__.js";
import BAGGAGE_HEADER_NAME from "../12880_BAGGAGE_HEADER_NAME.js";
import _mod12882 from "12882__.js";
import _mod12883 from "12883__.js";
import _mod12884 from "12884__.js";
import _mod12885 from "12885__.js";
import _mod12886 from "12886__.js";
import ScopeClass from "../12888_ScopeClass.js";
import _mod12890 from "12890__.js";
import _mod12891 from "12891__.js";
import _mod12893 from "12893__.js";
import _mod12894 from "12894__.js";
import _mod12896 from "12896__.js";
import _mod12897 from "12897__.js";
import _mod12898 from "12898__.js";
import _mod12899 from "12899__.js";
import _mod12900 from "12900__.js";
import _mod12901 from "12901__.js";
import _mod12902 from "12902__.js";
import _mod12903 from "12903__.js";
import _mod12904 from "12904__.js";
import _mod12905 from "12905__.js";
import _mod12906 from "12906__.js";
import _mod12907 from "12907__.js";
import _mod12908 from "12908__.js";
import _mod12909 from "12909__.js";
import _mod12910 from "12910__.js";
import _mod12911 from "12911__.js";
import _mod12912 from "12912__.js";
import memoBuilder from "../12913_memoBuilder.js";
import _mod12914 from "12914__.js";
import _flush from "../12915__flush.js";
import _mod12916 from "12916__.js";
import applyScopeDataToEvent from "../12917_applyScopeDataToEvent.js";
import notifyEventProcessors from "../12918_notifyEventProcessors.js";
import _mod12919 from "12919__.js";
import SessionFlusher from "../12920_SessionFlusher.js";
import _mod12921 from "12921__.js";
import _mod12922 from "12922__.js";
import _mod12923 from "12923__.js";
import _mod12924 from "12924__.js";
import _mod12925 from "12925__.js";
import _mod12926 from "12926__.js";
import eventFromMessage from "../12927_eventFromMessage.js";
import _mod12928 from "12928__.js";
import _mod12929 from "12929__.js";
import _mod12930 from "12930__.js";
import _mod12931 from "12931__.js";
import _mod12932 from "12932__.js";
import _mod12933 from "12933__.js";
import _mod12934 from "12934__.js";
import _mod12935 from "12935__.js";
import _mod12936 from "12936__.js";
import _mod12937 from "12937__.js";
import _mod12938 from "12938__.js";
import _mod12939 from "12939__.js";
import _mod12940 from "12940__.js";
import _mod12941 from "12941__.js";
import _getEventFilterUrl from "../12942__getEventFilterUrl.js";
import _mod12943 from "12943__.js";
import _mod12944 from "12944__.js";
import _mod12945 from "12945__.js";
import _mod12947 from "12947__.js";
import extractRequestData from "../12948_extractRequestData.js";
import stripUrlQueryAndFragment from "../12949_stripUrlQueryAndFragment.js";
import _mod12952 from "12952__.js";
import _mod12953 from "12953__.js";
import _mod12954 from "12954__.js";
import debugIntegration from "../12955_debugIntegration.js";
import _mod12956 from "12956__.js";
import extraErrorDataIntegration from "../12957_extraErrorDataIntegration.js";
import _mod12958 from "12958__.js";
import _mod12959 from "12959__.js";
import sessionTimingIntegration from "../12960_sessionTimingIntegration.js";
import _mod12961 from "12961__.js";
import _mod12962 from "12962__.js";
import _mod12963 from "12963__.js";
import _mod12965 from "12965__.js";
import metricsDefault from "../12966_metricsDefault.js";
import BrowserMetricsAggregator from "../12971_BrowserMetricsAggregator.js";
import _mod12972 from "12972__.js";
import _mod12973 from "12973__.js";
import _mod12974 from "12974__.js";
import _mod12975 from "12975__.js";
import _mod12976 from "12976__.js";
import _mod12977 from "12977__.js";
import _mod12978 from "12978__.js";
import supportsFetch from "../12979_supportsFetch.js";
import _mod12980 from "12980__.js";
import _mod12981 from "12981__.js";
import _mod12982 from "12982__.js";
import _mod12983 from "12983__.js";
import _mod12984 from "12984__.js";
import _mod12985 from "12985__.js";
import _mod12986 from "12986__.js";
import _mod12987 from "12987__.js";
import _mod12988 from "12988__.js";
import supportsHistory from "../12989_supportsHistory.js";
import _asyncNullishCoalesce2 from "../12990__asyncNullishCoalesce2.js";
import _nullishCoalesce from "../12991__nullishCoalesce.js";
import _asyncOptionalChain2 from "../12992__asyncOptionalChain2.js";
import _asyncOptionalChainDelete2 from "../12993__asyncOptionalChainDelete2.js";
import _optionalChain from "../12994__optionalChain.js";
import _optionalChainDelete from "../12995__optionalChainDelete.js";

export const registerSpanErrorInstrumentation = errorCallback.registerSpanErrorInstrumentation;
export const getCapturedScopesOnSpan = _mod12896.getCapturedScopesOnSpan;
export const setCapturedScopesOnSpan = _mod12896.setCapturedScopesOnSpan;
export const addTracingExtensions = _mod12897.addTracingExtensions;
export const TRACING_DEFAULTS = _mod12898.TRACING_DEFAULTS;
export const startIdleSpan = _mod12898.startIdleSpan;
export const SentrySpan = _mod12908.SentrySpan;
export const SentryNonRecordingSpan = _mod12900.SentryNonRecordingSpan;
export const SPAN_STATUS_ERROR = _mod12884.SPAN_STATUS_ERROR;
export const SPAN_STATUS_OK = _mod12884.SPAN_STATUS_OK;
export const SPAN_STATUS_UNSET = _mod12884.SPAN_STATUS_UNSET;
export const getSpanStatusFromHttpCode = _mod12884.getSpanStatusFromHttpCode;
export const setHttpStatus = _mod12884.setHttpStatus;
export const continueTrace = _mod12901.continueTrace;
export const startInactiveSpan = _mod12901.startInactiveSpan;
export const startNewTrace = _mod12901.startNewTrace;
export const startSpan = _mod12901.startSpan;
export const startSpanManual = _mod12901.startSpanManual;
export const suppressTracing = _mod12901.suppressTracing;
export const withActiveSpan = _mod12901.withActiveSpan;
export const getDynamicSamplingContextFromClient = _mod12903.getDynamicSamplingContextFromClient;
export const getDynamicSamplingContextFromScope = _mod12903.getDynamicSamplingContextFromScope;
export const getDynamicSamplingContextFromSpan = _mod12903.getDynamicSamplingContextFromSpan;
export const spanToBaggageHeader = _mod12903.spanToBaggageHeader;
export const setMeasurement = _mod12909.setMeasurement;
export const timedEventsToMeasurements = _mod12909.timedEventsToMeasurements;
export const sampleSpan = _mod12906.sampleSpan;
export const logSpanEnd = _mod12905.logSpanEnd;
export const logSpanStart = _mod12905.logSpanStart;
export const SEMANTIC_ATTRIBUTE_CACHE_HIT = _mod12882.SEMANTIC_ATTRIBUTE_CACHE_HIT;
export const SEMANTIC_ATTRIBUTE_CACHE_ITEM_SIZE = _mod12882.SEMANTIC_ATTRIBUTE_CACHE_ITEM_SIZE;
export const SEMANTIC_ATTRIBUTE_CACHE_KEY = _mod12882.SEMANTIC_ATTRIBUTE_CACHE_KEY;
export const SEMANTIC_ATTRIBUTE_EXCLUSIVE_TIME = _mod12882.SEMANTIC_ATTRIBUTE_EXCLUSIVE_TIME;
export const SEMANTIC_ATTRIBUTE_HTTP_REQUEST_METHOD = _mod12882.SEMANTIC_ATTRIBUTE_HTTP_REQUEST_METHOD;
export const SEMANTIC_ATTRIBUTE_PROFILE_ID = _mod12882.SEMANTIC_ATTRIBUTE_PROFILE_ID;
export const SEMANTIC_ATTRIBUTE_SENTRY_CUSTOM_SPAN_NAME = _mod12882.SEMANTIC_ATTRIBUTE_SENTRY_CUSTOM_SPAN_NAME;
export const SEMANTIC_ATTRIBUTE_SENTRY_IDLE_SPAN_FINISH_REASON =
  _mod12882.SEMANTIC_ATTRIBUTE_SENTRY_IDLE_SPAN_FINISH_REASON;
export const SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_UNIT = _mod12882.SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_UNIT;
export const SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_VALUE = _mod12882.SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_VALUE;
export const SEMANTIC_ATTRIBUTE_SENTRY_OP = _mod12882.SEMANTIC_ATTRIBUTE_SENTRY_OP;
export const SEMANTIC_ATTRIBUTE_SENTRY_ORIGIN = _mod12882.SEMANTIC_ATTRIBUTE_SENTRY_ORIGIN;
export const SEMANTIC_ATTRIBUTE_SENTRY_SAMPLE_RATE = _mod12882.SEMANTIC_ATTRIBUTE_SENTRY_SAMPLE_RATE;
export const SEMANTIC_ATTRIBUTE_SENTRY_SOURCE = _mod12882.SEMANTIC_ATTRIBUTE_SENTRY_SOURCE;
export const SEMANTIC_ATTRIBUTE_URL_FULL = _mod12882.SEMANTIC_ATTRIBUTE_URL_FULL;
export const createEventEnvelope = _mod12910.createEventEnvelope;
export const createSessionEnvelope = _mod12910.createSessionEnvelope;
export const createSpanEnvelope = _mod12910.createSpanEnvelope;
export const addEventProcessor = _flush.addEventProcessor;
export const captureCheckIn = _flush.captureCheckIn;
export const captureEvent = _flush.captureEvent;
export const captureException = _flush.captureException;
export const captureMessage = _flush.captureMessage;
export const captureSession = _flush.captureSession;
export const close = _flush.close;
export const endSession = _flush.endSession;
export const flush = _flush.flush;
export const isEnabled = _flush.isEnabled;
export const isInitialized = _flush.isInitialized;
export const lastEventId = _flush.lastEventId;
export const setContext = _flush.setContext;
export const setExtra = _flush.setExtra;
export const setExtras = _flush.setExtras;
export const setTag = _flush.setTag;
export const setTags = _flush.setTags;
export const setUser = _flush.setUser;
export const startSession = _flush.startSession;
export const withMonitor = _flush.withMonitor;
export const getClient = _mod12894.getClient;
export const getCurrentScope = _mod12894.getCurrentScope;
export const getGlobalScope = _mod12894.getGlobalScope;
export const getIsolationScope = _mod12894.getIsolationScope;
export const getTraceContextFromScope = _mod12894.getTraceContextFromScope;
export const withIsolationScope = _mod12894.withIsolationScope;
export const withScope = _mod12894.withScope;
export const getDefaultCurrentScope = _mod12893.getDefaultCurrentScope;
export const getDefaultIsolationScope = _mod12893.getDefaultIsolationScope;
export const setAsyncContextStrategy = _mod12886.setAsyncContextStrategy;
export const getMainCarrier = _mod12885.getMainCarrier;
export const closeSession = _mod12890.closeSession;
export const makeSession = _mod12890.makeSession;
export const updateSession = _mod12890.updateSession;
export const SessionFlusher = SessionFlusher.SessionFlusher;
export const Scope = ScopeClass.Scope;
export const notifyEventProcessors = notifyEventProcessors.notifyEventProcessors;
export const getEnvelopeEndpointWithUrlEncodedAuth = _mod12921.getEnvelopeEndpointWithUrlEncodedAuth;
export const getReportDialogEndpoint = _mod12921.getReportDialogEndpoint;
export const BaseClient = _mod12922.BaseClient;
export const ServerRuntimeClient = _mod12926.ServerRuntimeClient;
export const initAndBind = _mod12929.initAndBind;
export const setCurrentClient = _mod12929.setCurrentClient;
export const createTransport = _mod12930.createTransport;
export const makeOfflineTransport = _mod12933.makeOfflineTransport;
export const makeMultiplexedTransport = _mod12934.makeMultiplexedTransport;
export const addIntegration = _mod12923.addIntegration;
export const defineIntegration = _mod12923.defineIntegration;
export const getIntegrationsToSetup = _mod12923.getIntegrationsToSetup;
export const applyScopeDataToEvent = applyScopeDataToEvent.applyScopeDataToEvent;
export const mergeScopeData = applyScopeDataToEvent.mergeScopeData;
export const prepareEvent = _mod12916.prepareEvent;
export const createCheckInEnvelope = _mod12928.createCheckInEnvelope;
export const hasTracingEnabled = _mod12899.hasTracingEnabled;
export const isSentryRequestUrl = _mod12935.isSentryRequestUrl;
export const handleCallbackErrors = _mod12902.handleCallbackErrors;
export const parameterize = _mod12936.parameterize;
export const addChildSpanToSpan = spanTimeInputToSeconds.addChildSpanToSpan;
export const getActiveSpan = spanTimeInputToSeconds.getActiveSpan;
export const getRootSpan = spanTimeInputToSeconds.getRootSpan;
export const getSpanDescendants = spanTimeInputToSeconds.getSpanDescendants;
export const getStatusMessage = spanTimeInputToSeconds.getStatusMessage;
export const spanIsSampled = spanTimeInputToSeconds.spanIsSampled;
export const spanTimeInputToSeconds = spanTimeInputToSeconds.spanTimeInputToSeconds;
export const spanToJSON = spanTimeInputToSeconds.spanToJSON;
export const spanToTraceContext = spanTimeInputToSeconds.spanToTraceContext;
export const spanToTraceHeader = spanTimeInputToSeconds.spanToTraceHeader;
export const updateSpanName = spanTimeInputToSeconds.updateSpanName;
export const parseSampleRate = _mod12907.parseSampleRate;
export const applySdkMetadata = _mod12937.applySdkMetadata;
export const getTraceData = _mod12938.getTraceData;
export const getTraceMetaTags = _mod12939.getTraceMetaTags;
export const DEFAULT_ENVIRONMENT = _mod12904.DEFAULT_ENVIRONMENT;
export const addBreadcrumb = _mod12940.addBreadcrumb;
export const functionToStringIntegration = _mod12941.functionToStringIntegration;
export const inboundFiltersIntegration = _getEventFilterUrl.inboundFiltersIntegration;
export const linkedErrorsIntegration = _mod12943.linkedErrorsIntegration;
export const moduleMetadataIntegration = _mod12945.moduleMetadataIntegration;
export const requestDataIntegration = _mod12947.requestDataIntegration;
export const captureConsoleIntegration = _mod12952.captureConsoleIntegration;
export const debugIntegration = debugIntegration.debugIntegration;
export const dedupeIntegration = _mod12956.dedupeIntegration;
export const extraErrorDataIntegration = extraErrorDataIntegration.extraErrorDataIntegration;
export const rewriteFramesIntegration = _mod12958.rewriteFramesIntegration;
export const sessionTimingIntegration = sessionTimingIntegration.sessionTimingIntegration;
export const zodErrorsIntegration = _mod12961.zodErrorsIntegration;
export const thirdPartyErrorFilterIntegration = _mod12962.thirdPartyErrorFilterIntegration;
export const metrics = _mod12963.metrics;
export const profiler = _mod12965.profiler;
export const metricsDefault = metricsDefault.metricsDefault;
export const BrowserMetricsAggregator = BrowserMetricsAggregator.BrowserMetricsAggregator;
export const getMetricSummaryJsonForSpan = _mod12883.getMetricSummaryJsonForSpan;
export const addTracingHeadersToFetchRequest = _mod12972.addTracingHeadersToFetchRequest;
export const instrumentFetchRequest = _mod12972.instrumentFetchRequest;
export const trpcMiddleware = _mod12973.trpcMiddleware;
export const captureFeedback = _mod12974.captureFeedback;
export const getCurrentHub = _mod12975.getCurrentHub;
export const getCurrentHubShim = _mod12975.getCurrentHubShim;
export const applyAggregateErrorsToEvent = _mod12944.applyAggregateErrorsToEvent;
export const flatten = _mod12976.flatten;
export const getBreadcrumbLogLevelFromHttpStatusCode = _mod12977.getBreadcrumbLogLevelFromHttpStatusCode;
export const getComponentName = _mod12875.getComponentName;
export const getDomElement = _mod12875.getDomElement;
export const getLocationHref = _mod12875.getLocationHref;
export const htmlTreeAsString = _mod12875.htmlTreeAsString;
export const dsnFromString = _mod12914.dsnFromString;
export const dsnToString = _mod12914.dsnToString;
export const makeDsn = _mod12914.makeDsn;
export const SentryError = _mod12924.SentryError;
export const GLOBAL_OBJ = _mod12868.GLOBAL_OBJ;
export const getGlobalSingleton = _mod12868.getGlobalSingleton;
export const addConsoleInstrumentationHandler = _mod12953.addConsoleInstrumentationHandler;
export const addFetchEndInstrumentationHandler = _mod12978.addFetchEndInstrumentationHandler;
export const addFetchInstrumentationHandler = _mod12978.addFetchInstrumentationHandler;
export const addGlobalErrorInstrumentationHandler = _mod12864.addGlobalErrorInstrumentationHandler;
export const addGlobalUnhandledRejectionInstrumentationHandler =
  _mod12871.addGlobalUnhandledRejectionInstrumentationHandler;
export const addHandler = _mod12865.addHandler;
export const maybeInstrument = _mod12865.maybeInstrument;
export const resetInstrumentationHandlers = _mod12865.resetInstrumentationHandlers;
export const triggerHandlers = _mod12865.triggerHandlers;
export const isDOMError = _mod12874.isDOMError;
export const isDOMException = _mod12874.isDOMException;
export const isElement = _mod12874.isElement;
export const isError = _mod12874.isError;
export const isErrorEvent = _mod12874.isErrorEvent;
export const isEvent = _mod12874.isEvent;
export const isInstanceOf = _mod12874.isInstanceOf;
export const isParameterizedString = _mod12874.isParameterizedString;
export const isPlainObject = _mod12874.isPlainObject;
export const isPrimitive = _mod12874.isPrimitive;
export const isRegExp = _mod12874.isRegExp;
export const isString = _mod12874.isString;
export const isSyntheticEvent = _mod12874.isSyntheticEvent;
export const isThenable = _mod12874.isThenable;
export const isVueViewModel = _mod12874.isVueViewModel;
export const isBrowser = _mod12980.isBrowser;
export const CONSOLE_LEVELS = _mod12867.CONSOLE_LEVELS;
export const consoleSandbox = _mod12867.consoleSandbox;
export const logger = _mod12867.logger;
export const originalConsoleMethods = _mod12867.originalConsoleMethods;
export const memoBuilder = memoBuilder.memoBuilder;
export const addContextToFrame = _mod12878.addContextToFrame;
export const addExceptionMechanism = _mod12878.addExceptionMechanism;
export const addExceptionTypeValue = _mod12878.addExceptionTypeValue;
export const arrayify = _mod12878.arrayify;
export const checkOrSetAlreadyCaught = _mod12878.checkOrSetAlreadyCaught;
export const getEventDescription = _mod12878.getEventDescription;
export const parseSemver = _mod12878.parseSemver;
export const uuid4 = _mod12878.uuid4;
export const dynamicRequire = _mod12981.dynamicRequire;
export const isNodeEnv = _mod12981.isNodeEnv;
export const loadModule = _mod12981.loadModule;
export const normalize = _mod12912.normalize;
export const normalizeToSize = _mod12912.normalizeToSize;
export const normalizeUrlToBase = _mod12912.normalizeUrlToBase;
export const addNonEnumerableProperty = _mod12873.addNonEnumerableProperty;
export const convertToPlainObject = _mod12873.convertToPlainObject;
export const dropUndefinedKeys = _mod12873.dropUndefinedKeys;
export const extractExceptionKeysForMessage = _mod12873.extractExceptionKeysForMessage;
export const fill = _mod12873.fill;
export const getOriginalFunction = _mod12873.getOriginalFunction;
export const markFunctionWrapped = _mod12873.markFunctionWrapped;
export const objectify = _mod12873.objectify;
export const urlEncode = _mod12873.urlEncode;
export const basename = _mod12959.basename;
export const dirname = _mod12959.dirname;
export const isAbsolute = _mod12959.isAbsolute;
export const join = _mod12959.join;
export const normalizePath = _mod12959.normalizePath;
export const relative = _mod12959.relative;
export const resolve = _mod12959.resolve;
export const makePromiseBuffer = _mod12931.makePromiseBuffer;
export const DEFAULT_USER_INCLUDES = extractRequestData.DEFAULT_USER_INCLUDES;
export const addNormalizedRequestDataToEvent = extractRequestData.addNormalizedRequestDataToEvent;
export const addRequestDataToEvent = extractRequestData.addRequestDataToEvent;
export const extractPathForTransaction = extractRequestData.extractPathForTransaction;
export const extractQueryParamsFromUrl = extractRequestData.extractQueryParamsFromUrl;
export const extractRequestData = extractRequestData.extractRequestData;
export const headersToDict = extractRequestData.headersToDict;
export const httpRequestToRequestData = extractRequestData.httpRequestToRequestData;
export const winterCGHeadersToDict = extractRequestData.winterCGHeadersToDict;
export const winterCGRequestToRequestData = extractRequestData.winterCGRequestToRequestData;
export const severityLevelFromString = _mod12954.severityLevelFromString;
export const validSeverityLevels = _mod12954.validSeverityLevels;
export const UNKNOWN_FUNCTION = stackParserFromStackParserOptions.UNKNOWN_FUNCTION;
export const createStackParser = stackParserFromStackParserOptions.createStackParser;
export const getFramesFromEvent = stackParserFromStackParserOptions.getFramesFromEvent;
export const getFunctionName = stackParserFromStackParserOptions.getFunctionName;
export const stackParserFromStackParserOptions = stackParserFromStackParserOptions.stackParserFromStackParserOptions;
export const stripSentryFramesAndReverse = stackParserFromStackParserOptions.stripSentryFramesAndReverse;
export const filenameIsInApp = _mod12983.filenameIsInApp;
export const node = _mod12983.node;
export const nodeStackLineParser = _mod12983.nodeStackLineParser;
export const isMatchingPattern = _mod12876.isMatchingPattern;
export const safeJoin = _mod12876.safeJoin;
export const snipLine = _mod12876.snipLine;
export const stringMatchesSomePattern = _mod12876.stringMatchesSomePattern;
export const truncate = _mod12876.truncate;
export const isNativeFunction = supportsFetch.isNativeFunction;
export const supportsDOMError = supportsFetch.supportsDOMError;
export const supportsDOMException = supportsFetch.supportsDOMException;
export const supportsErrorEvent = supportsFetch.supportsErrorEvent;
export const supportsFetch = supportsFetch.supportsFetch;
export const supportsNativeFetch = supportsFetch.supportsNativeFetch;
export const supportsReferrerPolicy = supportsFetch.supportsReferrerPolicy;
export const supportsReportingObserver = supportsFetch.supportsReportingObserver;
export const SyncPromise = _mod12891.SyncPromise;
export const rejectedSyncPromise = _mod12891.rejectedSyncPromise;
export const resolvedSyncPromise = _mod12891.resolvedSyncPromise;
export const _browserPerformanceTimeOriginMode = require("12881__.js")._browserPerformanceTimeOriginMode;
export const browserPerformanceTimeOrigin = require("12881__.js").browserPerformanceTimeOrigin;
export const dateTimestampInSeconds = require("12881__.js").dateTimestampInSeconds;
export const timestampInSeconds = require("12881__.js").timestampInSeconds;
export const TRACEPARENT_REGEXP = _mod12879.TRACEPARENT_REGEXP;
export const extractTraceparentData = _mod12879.extractTraceparentData;
export const generateSentryTraceHeader = _mod12879.generateSentryTraceHeader;
export const propagationContextFromHeaders = _mod12879.propagationContextFromHeaders;
export const getSDKSource = _mod12982.getSDKSource;
export const isBrowserBundle = _mod12982.isBrowserBundle;
export const addItemToEnvelope = _mod12911.addItemToEnvelope;
export const createAttachmentEnvelopeItem = _mod12911.createAttachmentEnvelopeItem;
export const createEnvelope = _mod12911.createEnvelope;
export const createEventEnvelopeHeaders = _mod12911.createEventEnvelopeHeaders;
export const createSpanEnvelopeItem = _mod12911.createSpanEnvelopeItem;
export const envelopeContainsItemType = _mod12911.envelopeContainsItemType;
export const envelopeItemTypeToDataCategory = _mod12911.envelopeItemTypeToDataCategory;
export const forEachEnvelopeItem = _mod12911.forEachEnvelopeItem;
export const getSdkMetadataForEnvelopeHeader = _mod12911.getSdkMetadataForEnvelopeHeader;
export const parseEnvelope = _mod12911.parseEnvelope;
export const serializeEnvelope = _mod12911.serializeEnvelope;
export const createClientReportEnvelope = _mod12925.createClientReportEnvelope;
export const DEFAULT_RETRY_AFTER = _mod12932.DEFAULT_RETRY_AFTER;
export const disabledUntil = _mod12932.disabledUntil;
export const isRateLimited = _mod12932.isRateLimited;
export const parseRetryAfterHeader = _mod12932.parseRetryAfterHeader;
export const updateRateLimits = _mod12932.updateRateLimits;
export const BAGGAGE_HEADER_NAME = BAGGAGE_HEADER_NAME.BAGGAGE_HEADER_NAME;
export const MAX_BAGGAGE_STRING_LENGTH = BAGGAGE_HEADER_NAME.MAX_BAGGAGE_STRING_LENGTH;
export const SENTRY_BAGGAGE_KEY_PREFIX = BAGGAGE_HEADER_NAME.SENTRY_BAGGAGE_KEY_PREFIX;
export const SENTRY_BAGGAGE_KEY_PREFIX_REGEX = BAGGAGE_HEADER_NAME.SENTRY_BAGGAGE_KEY_PREFIX_REGEX;
export const baggageHeaderToDynamicSamplingContext = BAGGAGE_HEADER_NAME.baggageHeaderToDynamicSamplingContext;
export const dynamicSamplingContextToSentryBaggageHeader =
  BAGGAGE_HEADER_NAME.dynamicSamplingContextToSentryBaggageHeader;
export const parseBaggageHeader = BAGGAGE_HEADER_NAME.parseBaggageHeader;
export const getNumberOfUrlSegments = stripUrlQueryAndFragment.getNumberOfUrlSegments;
export const getSanitizedUrlString = stripUrlQueryAndFragment.getSanitizedUrlString;
export const parseUrl = stripUrlQueryAndFragment.parseUrl;
export const stripUrlQueryAndFragment = stripUrlQueryAndFragment.stripUrlQueryAndFragment;
export const makeFifoCache = _mod12984.makeFifoCache;
export const eventFromMessage = eventFromMessage.eventFromMessage;
export const eventFromUnknownInput = eventFromMessage.eventFromUnknownInput;
export const exceptionFromError = eventFromMessage.exceptionFromError;
export const parseStackFrames = eventFromMessage.parseStackFrames;
export const callFrameToStackFrame = _mod12985.callFrameToStackFrame;
export const watchdogTimer = _mod12985.watchdogTimer;
export const LRUMap = _mod12986.LRUMap;
export const generatePropagationContext = generatePropagationContext.generatePropagationContext;
export const generateSpanId = generatePropagationContext.generateSpanId;
export const generateTraceId = generatePropagationContext.generateTraceId;
export const vercelWaitUntil = _mod12987.vercelWaitUntil;
export const SDK_VERSION = _mod12869.SDK_VERSION;
export const getDebugImagesForResources = _mod12919.getDebugImagesForResources;
export const getFilenameToDebugIdMap = _mod12919.getFilenameToDebugIdMap;
export const escapeStringForRegex = _mod12988.escapeStringForRegex;
export const supportsHistory = supportsHistory.supportsHistory;
export const _asyncNullishCoalesce = _asyncNullishCoalesce2._asyncNullishCoalesce;
export const _asyncOptionalChain = _asyncOptionalChain2._asyncOptionalChain;
export const _asyncOptionalChainDelete = _asyncOptionalChainDelete2._asyncOptionalChainDelete;
export const _nullishCoalesce = _nullishCoalesce._nullishCoalesce;
export const _optionalChain = _optionalChain._optionalChain;
export const _optionalChainDelete = _optionalChainDelete._optionalChainDelete;
