// _runtime/metro/12922__.js
import errorCallback from "../12923_errorCallback.js";
import _mod12924 from "12924__.js";
import _mod12925 from "12925__.js";
import _mod12927 from "12927__.js";
import _mod12928 from "12928__.js";
import _mod12929 from "12929__.js";
import stackParserFromStackParserOptions from "../12930_stackParserFromStackParserOptions.js";
import _mod12931 from "12931__.js";
import spanTimeInputToSeconds from "../12932_spanTimeInputToSeconds.js";
import _mod12933 from "12933__.js";
import _mod12934 from "12934__.js";
import _mod12935 from "12935__.js";
import _mod12936 from "12936__.js";
import generatePropagationContext from "../12937_generatePropagationContext.js";
import _mod12938 from "12938__.js";
import _mod12939 from "12939__.js";
import BAGGAGE_HEADER_NAME from "../12940_BAGGAGE_HEADER_NAME.js";
import _mod12942 from "12942__.js";
import _mod12943 from "12943__.js";
import _mod12944 from "12944__.js";
import _mod12945 from "12945__.js";
import _mod12946 from "12946__.js";
import ScopeClass from "../12948_ScopeClass.js";
import _mod12950 from "12950__.js";
import _mod12951 from "12951__.js";
import _mod12953 from "12953__.js";
import _mod12954 from "12954__.js";
import _mod12956 from "12956__.js";
import _mod12957 from "12957__.js";
import _mod12958 from "12958__.js";
import _mod12959 from "12959__.js";
import _mod12960 from "12960__.js";
import _mod12961 from "12961__.js";
import _mod12962 from "12962__.js";
import _mod12963 from "12963__.js";
import _mod12964 from "12964__.js";
import _mod12965 from "12965__.js";
import _mod12966 from "12966__.js";
import _mod12967 from "12967__.js";
import _mod12968 from "12968__.js";
import _mod12969 from "12969__.js";
import _mod12970 from "12970__.js";
import _mod12971 from "12971__.js";
import _mod12972 from "12972__.js";
import memoBuilder from "../12973_memoBuilder.js";
import _mod12974 from "12974__.js";
import _flush from "../12975__flush.js";
import _mod12976 from "12976__.js";
import applyScopeDataToEvent from "../12977_applyScopeDataToEvent.js";
import notifyEventProcessors from "../12978_notifyEventProcessors.js";
import _mod12979 from "12979__.js";
import SessionFlusher from "../12980_SessionFlusher.js";
import _mod12981 from "12981__.js";
import _mod12982 from "12982__.js";
import _mod12983 from "12983__.js";
import _mod12984 from "12984__.js";
import _mod12985 from "12985__.js";
import _mod12986 from "12986__.js";
import eventFromMessage from "../12987_eventFromMessage.js";
import _mod12988 from "12988__.js";
import _mod12989 from "12989__.js";
import _mod12990 from "12990__.js";
import _mod12991 from "12991__.js";
import _mod12992 from "12992__.js";
import _mod12993 from "12993__.js";
import _mod12994 from "12994__.js";
import _mod12995 from "12995__.js";
import _mod12996 from "12996__.js";
import _mod12997 from "12997__.js";
import _mod12998 from "12998__.js";
import _mod12999 from "12999__.js";
import _mod13000 from "13000__.js";
import _mod13001 from "13001__.js";
import _getEventFilterUrl from "../13002__getEventFilterUrl.js";
import _mod13003 from "13003__.js";
import _mod13004 from "13004__.js";
import _mod13005 from "13005__.js";
import _mod13007 from "13007__.js";
import extractRequestData from "../13008_extractRequestData.js";
import stripUrlQueryAndFragment from "../13009_stripUrlQueryAndFragment.js";
import _mod13012 from "13012__.js";
import _mod13013 from "13013__.js";
import _mod13014 from "13014__.js";
import debugIntegration from "../13015_debugIntegration.js";
import _mod13016 from "13016__.js";
import extraErrorDataIntegration from "../13017_extraErrorDataIntegration.js";
import _mod13018 from "13018__.js";
import _mod13019 from "13019__.js";
import sessionTimingIntegration from "../13020_sessionTimingIntegration.js";
import _mod13021 from "13021__.js";
import _mod13022 from "13022__.js";
import _mod13023 from "13023__.js";
import _mod13025 from "13025__.js";
import metricsDefault from "../13026_metricsDefault.js";
import BrowserMetricsAggregator from "../13031_BrowserMetricsAggregator.js";
import _mod13032 from "13032__.js";
import _mod13033 from "13033__.js";
import _mod13034 from "13034__.js";
import _mod13035 from "13035__.js";
import _mod13036 from "13036__.js";
import _mod13037 from "13037__.js";
import _mod13038 from "13038__.js";
import supportsFetch from "../13039_supportsFetch.js";
import _mod13040 from "13040__.js";
import _mod13041 from "13041__.js";
import _mod13042 from "13042__.js";
import _mod13043 from "13043__.js";
import _mod13044 from "13044__.js";
import _mod13045 from "13045__.js";
import _mod13046 from "13046__.js";
import _mod13047 from "13047__.js";
import _mod13048 from "13048__.js";
import supportsHistory from "../13049_supportsHistory.js";
import _asyncNullishCoalesce2 from "../13050__asyncNullishCoalesce2.js";
import _nullishCoalesce from "../13051__nullishCoalesce.js";
import _asyncOptionalChain2 from "../13052__asyncOptionalChain2.js";
import _asyncOptionalChainDelete2 from "../13053__asyncOptionalChainDelete2.js";
import _optionalChain from "../13054__optionalChain.js";
import _optionalChainDelete from "../13055__optionalChainDelete.js";

const require = globalThis.__r;

export const registerSpanErrorInstrumentation = errorCallback.registerSpanErrorInstrumentation;
export const getCapturedScopesOnSpan = _mod12956.getCapturedScopesOnSpan;
export const setCapturedScopesOnSpan = _mod12956.setCapturedScopesOnSpan;
export const addTracingExtensions = _mod12957.addTracingExtensions;
export const TRACING_DEFAULTS = _mod12958.TRACING_DEFAULTS;
export const startIdleSpan = _mod12958.startIdleSpan;
export const SentrySpan = _mod12968.SentrySpan;
export const SentryNonRecordingSpan = _mod12960.SentryNonRecordingSpan;
export const SPAN_STATUS_ERROR = _mod12944.SPAN_STATUS_ERROR;
export const SPAN_STATUS_OK = _mod12944.SPAN_STATUS_OK;
export const SPAN_STATUS_UNSET = _mod12944.SPAN_STATUS_UNSET;
export const getSpanStatusFromHttpCode = _mod12944.getSpanStatusFromHttpCode;
export const setHttpStatus = _mod12944.setHttpStatus;
export const continueTrace = _mod12961.continueTrace;
export const startInactiveSpan = _mod12961.startInactiveSpan;
export const startNewTrace = _mod12961.startNewTrace;
export const startSpan = _mod12961.startSpan;
export const startSpanManual = _mod12961.startSpanManual;
export const suppressTracing = _mod12961.suppressTracing;
export const withActiveSpan = _mod12961.withActiveSpan;
export const getDynamicSamplingContextFromClient = _mod12963.getDynamicSamplingContextFromClient;
export const getDynamicSamplingContextFromScope = _mod12963.getDynamicSamplingContextFromScope;
export const getDynamicSamplingContextFromSpan = _mod12963.getDynamicSamplingContextFromSpan;
export const spanToBaggageHeader = _mod12963.spanToBaggageHeader;
export const setMeasurement = _mod12969.setMeasurement;
export const timedEventsToMeasurements = _mod12969.timedEventsToMeasurements;
export const sampleSpan = _mod12966.sampleSpan;
export const logSpanEnd = _mod12965.logSpanEnd;
export const logSpanStart = _mod12965.logSpanStart;
export const SEMANTIC_ATTRIBUTE_CACHE_HIT = _mod12942.SEMANTIC_ATTRIBUTE_CACHE_HIT;
export const SEMANTIC_ATTRIBUTE_CACHE_ITEM_SIZE = _mod12942.SEMANTIC_ATTRIBUTE_CACHE_ITEM_SIZE;
export const SEMANTIC_ATTRIBUTE_CACHE_KEY = _mod12942.SEMANTIC_ATTRIBUTE_CACHE_KEY;
export const SEMANTIC_ATTRIBUTE_EXCLUSIVE_TIME = _mod12942.SEMANTIC_ATTRIBUTE_EXCLUSIVE_TIME;
export const SEMANTIC_ATTRIBUTE_HTTP_REQUEST_METHOD = _mod12942.SEMANTIC_ATTRIBUTE_HTTP_REQUEST_METHOD;
export const SEMANTIC_ATTRIBUTE_PROFILE_ID = _mod12942.SEMANTIC_ATTRIBUTE_PROFILE_ID;
export const SEMANTIC_ATTRIBUTE_SENTRY_CUSTOM_SPAN_NAME = _mod12942.SEMANTIC_ATTRIBUTE_SENTRY_CUSTOM_SPAN_NAME;
export const SEMANTIC_ATTRIBUTE_SENTRY_IDLE_SPAN_FINISH_REASON =
  _mod12942.SEMANTIC_ATTRIBUTE_SENTRY_IDLE_SPAN_FINISH_REASON;
export const SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_UNIT = _mod12942.SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_UNIT;
export const SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_VALUE = _mod12942.SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_VALUE;
export const SEMANTIC_ATTRIBUTE_SENTRY_OP = _mod12942.SEMANTIC_ATTRIBUTE_SENTRY_OP;
export const SEMANTIC_ATTRIBUTE_SENTRY_ORIGIN = _mod12942.SEMANTIC_ATTRIBUTE_SENTRY_ORIGIN;
export const SEMANTIC_ATTRIBUTE_SENTRY_SAMPLE_RATE = _mod12942.SEMANTIC_ATTRIBUTE_SENTRY_SAMPLE_RATE;
export const SEMANTIC_ATTRIBUTE_SENTRY_SOURCE = _mod12942.SEMANTIC_ATTRIBUTE_SENTRY_SOURCE;
export const SEMANTIC_ATTRIBUTE_URL_FULL = _mod12942.SEMANTIC_ATTRIBUTE_URL_FULL;
export const createEventEnvelope = _mod12970.createEventEnvelope;
export const createSessionEnvelope = _mod12970.createSessionEnvelope;
export const createSpanEnvelope = _mod12970.createSpanEnvelope;
export const addEventProcessor = _flush.addEventProcessor;
export const captureCheckIn = _flush.captureCheckIn;
export const captureEvent = _flush.captureEvent;
export const captureException = _flush.captureException;
export const captureMessage = _flush.captureMessage;
export const captureSession = _flush.captureSession;
export const close = _flush.close;
export const endSession = _flush.endSession;
export const flush = _flush.flush;
export const isEnabled = _flush.isEnabled;
export const isInitialized = _flush.isInitialized;
export const lastEventId = _flush.lastEventId;
export const setContext = _flush.setContext;
export const setExtra = _flush.setExtra;
export const setExtras = _flush.setExtras;
export const setTag = _flush.setTag;
export const setTags = _flush.setTags;
export const setUser = _flush.setUser;
export const startSession = _flush.startSession;
export const withMonitor = _flush.withMonitor;
export const getClient = _mod12954.getClient;
export const getCurrentScope = _mod12954.getCurrentScope;
export const getGlobalScope = _mod12954.getGlobalScope;
export const getIsolationScope = _mod12954.getIsolationScope;
export const getTraceContextFromScope = _mod12954.getTraceContextFromScope;
export const withIsolationScope = _mod12954.withIsolationScope;
export const withScope = _mod12954.withScope;
export const getDefaultCurrentScope = _mod12953.getDefaultCurrentScope;
export const getDefaultIsolationScope = _mod12953.getDefaultIsolationScope;
export const setAsyncContextStrategy = _mod12946.setAsyncContextStrategy;
export const getMainCarrier = _mod12945.getMainCarrier;
export const closeSession = _mod12950.closeSession;
export const makeSession = _mod12950.makeSession;
export const updateSession = _mod12950.updateSession;
export const SessionFlusher = SessionFlusher.SessionFlusher;
export const Scope = ScopeClass.Scope;
export const notifyEventProcessors = notifyEventProcessors.notifyEventProcessors;
export const getEnvelopeEndpointWithUrlEncodedAuth = _mod12981.getEnvelopeEndpointWithUrlEncodedAuth;
export const getReportDialogEndpoint = _mod12981.getReportDialogEndpoint;
export const BaseClient = _mod12982.BaseClient;
export const ServerRuntimeClient = _mod12986.ServerRuntimeClient;
export const initAndBind = _mod12989.initAndBind;
export const setCurrentClient = _mod12989.setCurrentClient;
export const createTransport = _mod12990.createTransport;
export const makeOfflineTransport = _mod12993.makeOfflineTransport;
export const makeMultiplexedTransport = _mod12994.makeMultiplexedTransport;
export const addIntegration = _mod12983.addIntegration;
export const defineIntegration = _mod12983.defineIntegration;
export const getIntegrationsToSetup = _mod12983.getIntegrationsToSetup;
export const applyScopeDataToEvent = applyScopeDataToEvent.applyScopeDataToEvent;
export const mergeScopeData = applyScopeDataToEvent.mergeScopeData;
export const prepareEvent = _mod12976.prepareEvent;
export const createCheckInEnvelope = _mod12988.createCheckInEnvelope;
export const hasTracingEnabled = _mod12959.hasTracingEnabled;
export const isSentryRequestUrl = _mod12995.isSentryRequestUrl;
export const handleCallbackErrors = _mod12962.handleCallbackErrors;
export const parameterize = _mod12996.parameterize;
export const addChildSpanToSpan = spanTimeInputToSeconds.addChildSpanToSpan;
export const getActiveSpan = spanTimeInputToSeconds.getActiveSpan;
export const getRootSpan = spanTimeInputToSeconds.getRootSpan;
export const getSpanDescendants = spanTimeInputToSeconds.getSpanDescendants;
export const getStatusMessage = spanTimeInputToSeconds.getStatusMessage;
export const spanIsSampled = spanTimeInputToSeconds.spanIsSampled;
export const spanTimeInputToSeconds = spanTimeInputToSeconds.spanTimeInputToSeconds;
export const spanToJSON = spanTimeInputToSeconds.spanToJSON;
export const spanToTraceContext = spanTimeInputToSeconds.spanToTraceContext;
export const spanToTraceHeader = spanTimeInputToSeconds.spanToTraceHeader;
export const updateSpanName = spanTimeInputToSeconds.updateSpanName;
export const parseSampleRate = _mod12967.parseSampleRate;
export const applySdkMetadata = _mod12997.applySdkMetadata;
export const getTraceData = _mod12998.getTraceData;
export const getTraceMetaTags = _mod12999.getTraceMetaTags;
export const DEFAULT_ENVIRONMENT = _mod12964.DEFAULT_ENVIRONMENT;
export const addBreadcrumb = _mod13000.addBreadcrumb;
export const functionToStringIntegration = _mod13001.functionToStringIntegration;
export const inboundFiltersIntegration = _getEventFilterUrl.inboundFiltersIntegration;
export const linkedErrorsIntegration = _mod13003.linkedErrorsIntegration;
export const moduleMetadataIntegration = _mod13005.moduleMetadataIntegration;
export const requestDataIntegration = _mod13007.requestDataIntegration;
export const captureConsoleIntegration = _mod13012.captureConsoleIntegration;
export const debugIntegration = debugIntegration.debugIntegration;
export const dedupeIntegration = _mod13016.dedupeIntegration;
export const extraErrorDataIntegration = extraErrorDataIntegration.extraErrorDataIntegration;
export const rewriteFramesIntegration = _mod13018.rewriteFramesIntegration;
export const sessionTimingIntegration = sessionTimingIntegration.sessionTimingIntegration;
export const zodErrorsIntegration = _mod13021.zodErrorsIntegration;
export const thirdPartyErrorFilterIntegration = _mod13022.thirdPartyErrorFilterIntegration;
export const metrics = _mod13023.metrics;
export const profiler = _mod13025.profiler;
export const metricsDefault = metricsDefault.metricsDefault;
export const BrowserMetricsAggregator = BrowserMetricsAggregator.BrowserMetricsAggregator;
export const getMetricSummaryJsonForSpan = _mod12943.getMetricSummaryJsonForSpan;
export const addTracingHeadersToFetchRequest = _mod13032.addTracingHeadersToFetchRequest;
export const instrumentFetchRequest = _mod13032.instrumentFetchRequest;
export const trpcMiddleware = _mod13033.trpcMiddleware;
export const captureFeedback = _mod13034.captureFeedback;
export const getCurrentHub = _mod13035.getCurrentHub;
export const getCurrentHubShim = _mod13035.getCurrentHubShim;
export const applyAggregateErrorsToEvent = _mod13004.applyAggregateErrorsToEvent;
export const flatten = _mod13036.flatten;
export const getBreadcrumbLogLevelFromHttpStatusCode = _mod13037.getBreadcrumbLogLevelFromHttpStatusCode;
export const getComponentName = _mod12935.getComponentName;
export const getDomElement = _mod12935.getDomElement;
export const getLocationHref = _mod12935.getLocationHref;
export const htmlTreeAsString = _mod12935.htmlTreeAsString;
export const dsnFromString = _mod12974.dsnFromString;
export const dsnToString = _mod12974.dsnToString;
export const makeDsn = _mod12974.makeDsn;
export const SentryError = _mod12984.SentryError;
export const GLOBAL_OBJ = _mod12928.GLOBAL_OBJ;
export const getGlobalSingleton = _mod12928.getGlobalSingleton;
export const addConsoleInstrumentationHandler = _mod13013.addConsoleInstrumentationHandler;
export const addFetchEndInstrumentationHandler = _mod13038.addFetchEndInstrumentationHandler;
export const addFetchInstrumentationHandler = _mod13038.addFetchInstrumentationHandler;
export const addGlobalErrorInstrumentationHandler = _mod12924.addGlobalErrorInstrumentationHandler;
export const addGlobalUnhandledRejectionInstrumentationHandler =
  _mod12931.addGlobalUnhandledRejectionInstrumentationHandler;
export const addHandler = _mod12925.addHandler;
export const maybeInstrument = _mod12925.maybeInstrument;
export const resetInstrumentationHandlers = _mod12925.resetInstrumentationHandlers;
export const triggerHandlers = _mod12925.triggerHandlers;
export const isDOMError = _mod12934.isDOMError;
export const isDOMException = _mod12934.isDOMException;
export const isElement = _mod12934.isElement;
export const isError = _mod12934.isError;
export const isErrorEvent = _mod12934.isErrorEvent;
export const isEvent = _mod12934.isEvent;
export const isInstanceOf = _mod12934.isInstanceOf;
export const isParameterizedString = _mod12934.isParameterizedString;
export const isPlainObject = _mod12934.isPlainObject;
export const isPrimitive = _mod12934.isPrimitive;
export const isRegExp = _mod12934.isRegExp;
export const isString = _mod12934.isString;
export const isSyntheticEvent = _mod12934.isSyntheticEvent;
export const isThenable = _mod12934.isThenable;
export const isVueViewModel = _mod12934.isVueViewModel;
export const isBrowser = _mod13040.isBrowser;
export const CONSOLE_LEVELS = _mod12927.CONSOLE_LEVELS;
export const consoleSandbox = _mod12927.consoleSandbox;
export const logger = _mod12927.logger;
export const originalConsoleMethods = _mod12927.originalConsoleMethods;
export const memoBuilder = memoBuilder.memoBuilder;
export const addContextToFrame = _mod12938.addContextToFrame;
export const addExceptionMechanism = _mod12938.addExceptionMechanism;
export const addExceptionTypeValue = _mod12938.addExceptionTypeValue;
export const arrayify = _mod12938.arrayify;
export const checkOrSetAlreadyCaught = _mod12938.checkOrSetAlreadyCaught;
export const getEventDescription = _mod12938.getEventDescription;
export const parseSemver = _mod12938.parseSemver;
export const uuid4 = _mod12938.uuid4;
export const dynamicRequire = _mod13041.dynamicRequire;
export const isNodeEnv = _mod13041.isNodeEnv;
export const loadModule = _mod13041.loadModule;
export const normalize = _mod12972.normalize;
export const normalizeToSize = _mod12972.normalizeToSize;
export const normalizeUrlToBase = _mod12972.normalizeUrlToBase;
export const addNonEnumerableProperty = _mod12933.addNonEnumerableProperty;
export const convertToPlainObject = _mod12933.convertToPlainObject;
export const dropUndefinedKeys = _mod12933.dropUndefinedKeys;
export const extractExceptionKeysForMessage = _mod12933.extractExceptionKeysForMessage;
export const fill = _mod12933.fill;
export const getOriginalFunction = _mod12933.getOriginalFunction;
export const markFunctionWrapped = _mod12933.markFunctionWrapped;
export const objectify = _mod12933.objectify;
export const urlEncode = _mod12933.urlEncode;
export const basename = _mod13019.basename;
export const dirname = _mod13019.dirname;
export const isAbsolute = _mod13019.isAbsolute;
export const join = _mod13019.join;
export const normalizePath = _mod13019.normalizePath;
export const relative = _mod13019.relative;
export const resolve = _mod13019.resolve;
export const makePromiseBuffer = _mod12991.makePromiseBuffer;
export const DEFAULT_USER_INCLUDES = extractRequestData.DEFAULT_USER_INCLUDES;
export const addNormalizedRequestDataToEvent = extractRequestData.addNormalizedRequestDataToEvent;
export const addRequestDataToEvent = extractRequestData.addRequestDataToEvent;
export const extractPathForTransaction = extractRequestData.extractPathForTransaction;
export const extractQueryParamsFromUrl = extractRequestData.extractQueryParamsFromUrl;
export const extractRequestData = extractRequestData.extractRequestData;
export const headersToDict = extractRequestData.headersToDict;
export const httpRequestToRequestData = extractRequestData.httpRequestToRequestData;
export const winterCGHeadersToDict = extractRequestData.winterCGHeadersToDict;
export const winterCGRequestToRequestData = extractRequestData.winterCGRequestToRequestData;
export const severityLevelFromString = _mod13014.severityLevelFromString;
export const validSeverityLevels = _mod13014.validSeverityLevels;
export const UNKNOWN_FUNCTION = stackParserFromStackParserOptions.UNKNOWN_FUNCTION;
export const createStackParser = stackParserFromStackParserOptions.createStackParser;
export const getFramesFromEvent = stackParserFromStackParserOptions.getFramesFromEvent;
export const getFunctionName = stackParserFromStackParserOptions.getFunctionName;
export const stackParserFromStackParserOptions = stackParserFromStackParserOptions.stackParserFromStackParserOptions;
export const stripSentryFramesAndReverse = stackParserFromStackParserOptions.stripSentryFramesAndReverse;
export const filenameIsInApp = _mod13043.filenameIsInApp;
export const node = _mod13043.node;
export const nodeStackLineParser = _mod13043.nodeStackLineParser;
export const isMatchingPattern = _mod12936.isMatchingPattern;
export const safeJoin = _mod12936.safeJoin;
export const snipLine = _mod12936.snipLine;
export const stringMatchesSomePattern = _mod12936.stringMatchesSomePattern;
export const truncate = _mod12936.truncate;
export const isNativeFunction = supportsFetch.isNativeFunction;
export const supportsDOMError = supportsFetch.supportsDOMError;
export const supportsDOMException = supportsFetch.supportsDOMException;
export const supportsErrorEvent = supportsFetch.supportsErrorEvent;
export const supportsFetch = supportsFetch.supportsFetch;
export const supportsNativeFetch = supportsFetch.supportsNativeFetch;
export const supportsReferrerPolicy = supportsFetch.supportsReferrerPolicy;
export const supportsReportingObserver = supportsFetch.supportsReportingObserver;
export const SyncPromise = _mod12951.SyncPromise;
export const rejectedSyncPromise = _mod12951.rejectedSyncPromise;
export const resolvedSyncPromise = _mod12951.resolvedSyncPromise;
export const _browserPerformanceTimeOriginMode = require("12941__.js")._browserPerformanceTimeOriginMode;
export const browserPerformanceTimeOrigin = require("12941__.js").browserPerformanceTimeOrigin;
export const dateTimestampInSeconds = require("12941__.js").dateTimestampInSeconds;
export const timestampInSeconds = require("12941__.js").timestampInSeconds;
export const TRACEPARENT_REGEXP = _mod12939.TRACEPARENT_REGEXP;
export const extractTraceparentData = _mod12939.extractTraceparentData;
export const generateSentryTraceHeader = _mod12939.generateSentryTraceHeader;
export const propagationContextFromHeaders = _mod12939.propagationContextFromHeaders;
export const getSDKSource = _mod13042.getSDKSource;
export const isBrowserBundle = _mod13042.isBrowserBundle;
export const addItemToEnvelope = _mod12971.addItemToEnvelope;
export const createAttachmentEnvelopeItem = _mod12971.createAttachmentEnvelopeItem;
export const createEnvelope = _mod12971.createEnvelope;
export const createEventEnvelopeHeaders = _mod12971.createEventEnvelopeHeaders;
export const createSpanEnvelopeItem = _mod12971.createSpanEnvelopeItem;
export const envelopeContainsItemType = _mod12971.envelopeContainsItemType;
export const envelopeItemTypeToDataCategory = _mod12971.envelopeItemTypeToDataCategory;
export const forEachEnvelopeItem = _mod12971.forEachEnvelopeItem;
export const getSdkMetadataForEnvelopeHeader = _mod12971.getSdkMetadataForEnvelopeHeader;
export const parseEnvelope = _mod12971.parseEnvelope;
export const serializeEnvelope = _mod12971.serializeEnvelope;
export const createClientReportEnvelope = _mod12985.createClientReportEnvelope;
export const DEFAULT_RETRY_AFTER = _mod12992.DEFAULT_RETRY_AFTER;
export const disabledUntil = _mod12992.disabledUntil;
export const isRateLimited = _mod12992.isRateLimited;
export const parseRetryAfterHeader = _mod12992.parseRetryAfterHeader;
export const updateRateLimits = _mod12992.updateRateLimits;
export const BAGGAGE_HEADER_NAME = BAGGAGE_HEADER_NAME.BAGGAGE_HEADER_NAME;
export const MAX_BAGGAGE_STRING_LENGTH = BAGGAGE_HEADER_NAME.MAX_BAGGAGE_STRING_LENGTH;
export const SENTRY_BAGGAGE_KEY_PREFIX = BAGGAGE_HEADER_NAME.SENTRY_BAGGAGE_KEY_PREFIX;
export const SENTRY_BAGGAGE_KEY_PREFIX_REGEX = BAGGAGE_HEADER_NAME.SENTRY_BAGGAGE_KEY_PREFIX_REGEX;
export const baggageHeaderToDynamicSamplingContext = BAGGAGE_HEADER_NAME.baggageHeaderToDynamicSamplingContext;
export const dynamicSamplingContextToSentryBaggageHeader =
  BAGGAGE_HEADER_NAME.dynamicSamplingContextToSentryBaggageHeader;
export const parseBaggageHeader = BAGGAGE_HEADER_NAME.parseBaggageHeader;
export const getNumberOfUrlSegments = stripUrlQueryAndFragment.getNumberOfUrlSegments;
export const getSanitizedUrlString = stripUrlQueryAndFragment.getSanitizedUrlString;
export const parseUrl = stripUrlQueryAndFragment.parseUrl;
export const stripUrlQueryAndFragment = stripUrlQueryAndFragment.stripUrlQueryAndFragment;
export const makeFifoCache = _mod13044.makeFifoCache;
export const eventFromMessage = eventFromMessage.eventFromMessage;
export const eventFromUnknownInput = eventFromMessage.eventFromUnknownInput;
export const exceptionFromError = eventFromMessage.exceptionFromError;
export const parseStackFrames = eventFromMessage.parseStackFrames;
export const callFrameToStackFrame = _mod13045.callFrameToStackFrame;
export const watchdogTimer = _mod13045.watchdogTimer;
export const LRUMap = _mod13046.LRUMap;
export const generatePropagationContext = generatePropagationContext.generatePropagationContext;
export const generateSpanId = generatePropagationContext.generateSpanId;
export const generateTraceId = generatePropagationContext.generateTraceId;
export const vercelWaitUntil = _mod13047.vercelWaitUntil;
export const SDK_VERSION = _mod12929.SDK_VERSION;
export const getDebugImagesForResources = _mod12979.getDebugImagesForResources;
export const getFilenameToDebugIdMap = _mod12979.getFilenameToDebugIdMap;
export const escapeStringForRegex = _mod13048.escapeStringForRegex;
export const supportsHistory = supportsHistory.supportsHistory;
export const _asyncNullishCoalesce = _asyncNullishCoalesce2._asyncNullishCoalesce;
export const _asyncOptionalChain = _asyncOptionalChain2._asyncOptionalChain;
export const _asyncOptionalChainDelete = _asyncOptionalChainDelete2._asyncOptionalChainDelete;
export const _nullishCoalesce = _nullishCoalesce._nullishCoalesce;
export const _optionalChain = _optionalChain._optionalChain;
export const _optionalChainDelete = _optionalChainDelete._optionalChainDelete;
