// _runtime/metro/12935__.js
import errorCallback from "../12936_errorCallback.js";
import _mod12937 from "12937__.js";
import _mod12938 from "12938__.js";
import _mod12940 from "12940__.js";
import _mod12941 from "12941__.js";
import _mod12942 from "12942__.js";
import stackParserFromStackParserOptions from "../12943_stackParserFromStackParserOptions.js";
import _mod12944 from "12944__.js";
import spanTimeInputToSeconds from "../12945_spanTimeInputToSeconds.js";
import _mod12946 from "12946__.js";
import _mod12947 from "12947__.js";
import _mod12948 from "12948__.js";
import _mod12949 from "12949__.js";
import generatePropagationContext from "../12950_generatePropagationContext.js";
import _mod12951 from "12951__.js";
import _mod12952 from "12952__.js";
import BAGGAGE_HEADER_NAME from "../12953_BAGGAGE_HEADER_NAME.js";
import _mod12955 from "12955__.js";
import _mod12956 from "12956__.js";
import _mod12957 from "12957__.js";
import _mod12958 from "12958__.js";
import _mod12959 from "12959__.js";
import ScopeClass from "../12961_ScopeClass.js";
import _mod12963 from "12963__.js";
import _mod12964 from "12964__.js";
import _mod12966 from "12966__.js";
import _mod12967 from "12967__.js";
import _mod12969 from "12969__.js";
import _mod12970 from "12970__.js";
import _mod12971 from "12971__.js";
import _mod12972 from "12972__.js";
import _mod12973 from "12973__.js";
import _mod12974 from "12974__.js";
import _mod12975 from "12975__.js";
import _mod12976 from "12976__.js";
import _mod12977 from "12977__.js";
import _mod12978 from "12978__.js";
import _mod12979 from "12979__.js";
import _mod12980 from "12980__.js";
import _mod12981 from "12981__.js";
import _mod12982 from "12982__.js";
import _mod12983 from "12983__.js";
import _mod12984 from "12984__.js";
import _mod12985 from "12985__.js";
import memoBuilder from "../12986_memoBuilder.js";
import _mod12987 from "12987__.js";
import _flush from "../12988__flush.js";
import _mod12989 from "12989__.js";
import applyScopeDataToEvent from "../12990_applyScopeDataToEvent.js";
import notifyEventProcessors from "../12991_notifyEventProcessors.js";
import _mod12992 from "12992__.js";
import SessionFlusher from "../12993_SessionFlusher.js";
import _mod12994 from "12994__.js";
import _mod12995 from "12995__.js";
import _mod12996 from "12996__.js";
import _mod12997 from "12997__.js";
import _mod12998 from "12998__.js";
import _mod12999 from "12999__.js";
import eventFromMessage from "../13000_eventFromMessage.js";
import _mod13001 from "13001__.js";
import _mod13002 from "13002__.js";
import _mod13003 from "13003__.js";
import _mod13004 from "13004__.js";
import _mod13005 from "13005__.js";
import _mod13006 from "13006__.js";
import _mod13007 from "13007__.js";
import _mod13008 from "13008__.js";
import _mod13009 from "13009__.js";
import _mod13010 from "13010__.js";
import _mod13011 from "13011__.js";
import _mod13012 from "13012__.js";
import _mod13013 from "13013__.js";
import _mod13014 from "13014__.js";
import _getEventFilterUrl from "../13015__getEventFilterUrl.js";
import _mod13016 from "13016__.js";
import _mod13017 from "13017__.js";
import _mod13018 from "13018__.js";
import _mod13020 from "13020__.js";
import extractRequestData from "../13021_extractRequestData.js";
import stripUrlQueryAndFragment from "../13022_stripUrlQueryAndFragment.js";
import _mod13025 from "13025__.js";
import _mod13026 from "13026__.js";
import _mod13027 from "13027__.js";
import debugIntegration from "../13028_debugIntegration.js";
import _mod13029 from "13029__.js";
import extraErrorDataIntegration from "../13030_extraErrorDataIntegration.js";
import _mod13031 from "13031__.js";
import _mod13032 from "13032__.js";
import sessionTimingIntegration from "../13033_sessionTimingIntegration.js";
import _mod13034 from "13034__.js";
import _mod13035 from "13035__.js";
import _mod13036 from "13036__.js";
import _mod13038 from "13038__.js";
import metricsDefault from "../13039_metricsDefault.js";
import BrowserMetricsAggregator from "../13044_BrowserMetricsAggregator.js";
import _mod13045 from "13045__.js";
import _mod13046 from "13046__.js";
import _mod13047 from "13047__.js";
import _mod13048 from "13048__.js";
import _mod13049 from "13049__.js";
import _mod13050 from "13050__.js";
import _mod13051 from "13051__.js";
import supportsFetch from "../13052_supportsFetch.js";
import _mod13053 from "13053__.js";
import _mod13054 from "13054__.js";
import _mod13055 from "13055__.js";
import _mod13056 from "13056__.js";
import _mod13057 from "13057__.js";
import _mod13058 from "13058__.js";
import _mod13059 from "13059__.js";
import _mod13060 from "13060__.js";
import _mod13061 from "13061__.js";
import supportsHistory from "../13062_supportsHistory.js";
import _asyncNullishCoalesce2 from "../13063__asyncNullishCoalesce2.js";
import _nullishCoalesce from "../13064__nullishCoalesce.js";
import _asyncOptionalChain2 from "../13065__asyncOptionalChain2.js";
import _asyncOptionalChainDelete2 from "../13066__asyncOptionalChainDelete2.js";
import _optionalChain from "../13067__optionalChain.js";
import _optionalChainDelete from "../13068__optionalChainDelete.js";

const require = globalThis.__r;

export const registerSpanErrorInstrumentation = errorCallback.registerSpanErrorInstrumentation;
export const getCapturedScopesOnSpan = _mod12969.getCapturedScopesOnSpan;
export const setCapturedScopesOnSpan = _mod12969.setCapturedScopesOnSpan;
export const addTracingExtensions = _mod12970.addTracingExtensions;
export const TRACING_DEFAULTS = _mod12971.TRACING_DEFAULTS;
export const startIdleSpan = _mod12971.startIdleSpan;
export const SentrySpan = _mod12981.SentrySpan;
export const SentryNonRecordingSpan = _mod12973.SentryNonRecordingSpan;
export const SPAN_STATUS_ERROR = _mod12957.SPAN_STATUS_ERROR;
export const SPAN_STATUS_OK = _mod12957.SPAN_STATUS_OK;
export const SPAN_STATUS_UNSET = _mod12957.SPAN_STATUS_UNSET;
export const getSpanStatusFromHttpCode = _mod12957.getSpanStatusFromHttpCode;
export const setHttpStatus = _mod12957.setHttpStatus;
export const continueTrace = _mod12974.continueTrace;
export const startInactiveSpan = _mod12974.startInactiveSpan;
export const startNewTrace = _mod12974.startNewTrace;
export const startSpan = _mod12974.startSpan;
export const startSpanManual = _mod12974.startSpanManual;
export const suppressTracing = _mod12974.suppressTracing;
export const withActiveSpan = _mod12974.withActiveSpan;
export const getDynamicSamplingContextFromClient = _mod12976.getDynamicSamplingContextFromClient;
export const getDynamicSamplingContextFromScope = _mod12976.getDynamicSamplingContextFromScope;
export const getDynamicSamplingContextFromSpan = _mod12976.getDynamicSamplingContextFromSpan;
export const spanToBaggageHeader = _mod12976.spanToBaggageHeader;
export const setMeasurement = _mod12982.setMeasurement;
export const timedEventsToMeasurements = _mod12982.timedEventsToMeasurements;
export const sampleSpan = _mod12979.sampleSpan;
export const logSpanEnd = _mod12978.logSpanEnd;
export const logSpanStart = _mod12978.logSpanStart;
export const SEMANTIC_ATTRIBUTE_CACHE_HIT = _mod12955.SEMANTIC_ATTRIBUTE_CACHE_HIT;
export const SEMANTIC_ATTRIBUTE_CACHE_ITEM_SIZE = _mod12955.SEMANTIC_ATTRIBUTE_CACHE_ITEM_SIZE;
export const SEMANTIC_ATTRIBUTE_CACHE_KEY = _mod12955.SEMANTIC_ATTRIBUTE_CACHE_KEY;
export const SEMANTIC_ATTRIBUTE_EXCLUSIVE_TIME = _mod12955.SEMANTIC_ATTRIBUTE_EXCLUSIVE_TIME;
export const SEMANTIC_ATTRIBUTE_HTTP_REQUEST_METHOD = _mod12955.SEMANTIC_ATTRIBUTE_HTTP_REQUEST_METHOD;
export const SEMANTIC_ATTRIBUTE_PROFILE_ID = _mod12955.SEMANTIC_ATTRIBUTE_PROFILE_ID;
export const SEMANTIC_ATTRIBUTE_SENTRY_CUSTOM_SPAN_NAME = _mod12955.SEMANTIC_ATTRIBUTE_SENTRY_CUSTOM_SPAN_NAME;
export const SEMANTIC_ATTRIBUTE_SENTRY_IDLE_SPAN_FINISH_REASON =
  _mod12955.SEMANTIC_ATTRIBUTE_SENTRY_IDLE_SPAN_FINISH_REASON;
export const SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_UNIT = _mod12955.SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_UNIT;
export const SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_VALUE = _mod12955.SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_VALUE;
export const SEMANTIC_ATTRIBUTE_SENTRY_OP = _mod12955.SEMANTIC_ATTRIBUTE_SENTRY_OP;
export const SEMANTIC_ATTRIBUTE_SENTRY_ORIGIN = _mod12955.SEMANTIC_ATTRIBUTE_SENTRY_ORIGIN;
export const SEMANTIC_ATTRIBUTE_SENTRY_SAMPLE_RATE = _mod12955.SEMANTIC_ATTRIBUTE_SENTRY_SAMPLE_RATE;
export const SEMANTIC_ATTRIBUTE_SENTRY_SOURCE = _mod12955.SEMANTIC_ATTRIBUTE_SENTRY_SOURCE;
export const SEMANTIC_ATTRIBUTE_URL_FULL = _mod12955.SEMANTIC_ATTRIBUTE_URL_FULL;
export const createEventEnvelope = _mod12983.createEventEnvelope;
export const createSessionEnvelope = _mod12983.createSessionEnvelope;
export const createSpanEnvelope = _mod12983.createSpanEnvelope;
export const addEventProcessor = _flush.addEventProcessor;
export const captureCheckIn = _flush.captureCheckIn;
export const captureEvent = _flush.captureEvent;
export const captureException = _flush.captureException;
export const captureMessage = _flush.captureMessage;
export const captureSession = _flush.captureSession;
export const close = _flush.close;
export const endSession = _flush.endSession;
export const flush = _flush.flush;
export const isEnabled = _flush.isEnabled;
export const isInitialized = _flush.isInitialized;
export const lastEventId = _flush.lastEventId;
export const setContext = _flush.setContext;
export const setExtra = _flush.setExtra;
export const setExtras = _flush.setExtras;
export const setTag = _flush.setTag;
export const setTags = _flush.setTags;
export const setUser = _flush.setUser;
export const startSession = _flush.startSession;
export const withMonitor = _flush.withMonitor;
export const getClient = _mod12967.getClient;
export const getCurrentScope = _mod12967.getCurrentScope;
export const getGlobalScope = _mod12967.getGlobalScope;
export const getIsolationScope = _mod12967.getIsolationScope;
export const getTraceContextFromScope = _mod12967.getTraceContextFromScope;
export const withIsolationScope = _mod12967.withIsolationScope;
export const withScope = _mod12967.withScope;
export const getDefaultCurrentScope = _mod12966.getDefaultCurrentScope;
export const getDefaultIsolationScope = _mod12966.getDefaultIsolationScope;
export const setAsyncContextStrategy = _mod12959.setAsyncContextStrategy;
export const getMainCarrier = _mod12958.getMainCarrier;
export const closeSession = _mod12963.closeSession;
export const makeSession = _mod12963.makeSession;
export const updateSession = _mod12963.updateSession;
export const SessionFlusher = SessionFlusher.SessionFlusher;
export const Scope = ScopeClass.Scope;
export const notifyEventProcessors = notifyEventProcessors.notifyEventProcessors;
export const getEnvelopeEndpointWithUrlEncodedAuth = _mod12994.getEnvelopeEndpointWithUrlEncodedAuth;
export const getReportDialogEndpoint = _mod12994.getReportDialogEndpoint;
export const BaseClient = _mod12995.BaseClient;
export const ServerRuntimeClient = _mod12999.ServerRuntimeClient;
export const initAndBind = _mod13002.initAndBind;
export const setCurrentClient = _mod13002.setCurrentClient;
export const createTransport = _mod13003.createTransport;
export const makeOfflineTransport = _mod13006.makeOfflineTransport;
export const makeMultiplexedTransport = _mod13007.makeMultiplexedTransport;
export const addIntegration = _mod12996.addIntegration;
export const defineIntegration = _mod12996.defineIntegration;
export const getIntegrationsToSetup = _mod12996.getIntegrationsToSetup;
export const applyScopeDataToEvent = applyScopeDataToEvent.applyScopeDataToEvent;
export const mergeScopeData = applyScopeDataToEvent.mergeScopeData;
export const prepareEvent = _mod12989.prepareEvent;
export const createCheckInEnvelope = _mod13001.createCheckInEnvelope;
export const hasTracingEnabled = _mod12972.hasTracingEnabled;
export const isSentryRequestUrl = _mod13008.isSentryRequestUrl;
export const handleCallbackErrors = _mod12975.handleCallbackErrors;
export const parameterize = _mod13009.parameterize;
export const addChildSpanToSpan = spanTimeInputToSeconds.addChildSpanToSpan;
export const getActiveSpan = spanTimeInputToSeconds.getActiveSpan;
export const getRootSpan = spanTimeInputToSeconds.getRootSpan;
export const getSpanDescendants = spanTimeInputToSeconds.getSpanDescendants;
export const getStatusMessage = spanTimeInputToSeconds.getStatusMessage;
export const spanIsSampled = spanTimeInputToSeconds.spanIsSampled;
export const spanTimeInputToSeconds = spanTimeInputToSeconds.spanTimeInputToSeconds;
export const spanToJSON = spanTimeInputToSeconds.spanToJSON;
export const spanToTraceContext = spanTimeInputToSeconds.spanToTraceContext;
export const spanToTraceHeader = spanTimeInputToSeconds.spanToTraceHeader;
export const updateSpanName = spanTimeInputToSeconds.updateSpanName;
export const parseSampleRate = _mod12980.parseSampleRate;
export const applySdkMetadata = _mod13010.applySdkMetadata;
export const getTraceData = _mod13011.getTraceData;
export const getTraceMetaTags = _mod13012.getTraceMetaTags;
export const DEFAULT_ENVIRONMENT = _mod12977.DEFAULT_ENVIRONMENT;
export const addBreadcrumb = _mod13013.addBreadcrumb;
export const functionToStringIntegration = _mod13014.functionToStringIntegration;
export const inboundFiltersIntegration = _getEventFilterUrl.inboundFiltersIntegration;
export const linkedErrorsIntegration = _mod13016.linkedErrorsIntegration;
export const moduleMetadataIntegration = _mod13018.moduleMetadataIntegration;
export const requestDataIntegration = _mod13020.requestDataIntegration;
export const captureConsoleIntegration = _mod13025.captureConsoleIntegration;
export const debugIntegration = debugIntegration.debugIntegration;
export const dedupeIntegration = _mod13029.dedupeIntegration;
export const extraErrorDataIntegration = extraErrorDataIntegration.extraErrorDataIntegration;
export const rewriteFramesIntegration = _mod13031.rewriteFramesIntegration;
export const sessionTimingIntegration = sessionTimingIntegration.sessionTimingIntegration;
export const zodErrorsIntegration = _mod13034.zodErrorsIntegration;
export const thirdPartyErrorFilterIntegration = _mod13035.thirdPartyErrorFilterIntegration;
export const metrics = _mod13036.metrics;
export const profiler = _mod13038.profiler;
export const metricsDefault = metricsDefault.metricsDefault;
export const BrowserMetricsAggregator = BrowserMetricsAggregator.BrowserMetricsAggregator;
export const getMetricSummaryJsonForSpan = _mod12956.getMetricSummaryJsonForSpan;
export const addTracingHeadersToFetchRequest = _mod13045.addTracingHeadersToFetchRequest;
export const instrumentFetchRequest = _mod13045.instrumentFetchRequest;
export const trpcMiddleware = _mod13046.trpcMiddleware;
export const captureFeedback = _mod13047.captureFeedback;
export const getCurrentHub = _mod13048.getCurrentHub;
export const getCurrentHubShim = _mod13048.getCurrentHubShim;
export const applyAggregateErrorsToEvent = _mod13017.applyAggregateErrorsToEvent;
export const flatten = _mod13049.flatten;
export const getBreadcrumbLogLevelFromHttpStatusCode = _mod13050.getBreadcrumbLogLevelFromHttpStatusCode;
export const getComponentName = _mod12948.getComponentName;
export const getDomElement = _mod12948.getDomElement;
export const getLocationHref = _mod12948.getLocationHref;
export const htmlTreeAsString = _mod12948.htmlTreeAsString;
export const dsnFromString = _mod12987.dsnFromString;
export const dsnToString = _mod12987.dsnToString;
export const makeDsn = _mod12987.makeDsn;
export const SentryError = _mod12997.SentryError;
export const GLOBAL_OBJ = _mod12941.GLOBAL_OBJ;
export const getGlobalSingleton = _mod12941.getGlobalSingleton;
export const addConsoleInstrumentationHandler = _mod13026.addConsoleInstrumentationHandler;
export const addFetchEndInstrumentationHandler = _mod13051.addFetchEndInstrumentationHandler;
export const addFetchInstrumentationHandler = _mod13051.addFetchInstrumentationHandler;
export const addGlobalErrorInstrumentationHandler = _mod12937.addGlobalErrorInstrumentationHandler;
export const addGlobalUnhandledRejectionInstrumentationHandler =
  _mod12944.addGlobalUnhandledRejectionInstrumentationHandler;
export const addHandler = _mod12938.addHandler;
export const maybeInstrument = _mod12938.maybeInstrument;
export const resetInstrumentationHandlers = _mod12938.resetInstrumentationHandlers;
export const triggerHandlers = _mod12938.triggerHandlers;
export const isDOMError = _mod12947.isDOMError;
export const isDOMException = _mod12947.isDOMException;
export const isElement = _mod12947.isElement;
export const isError = _mod12947.isError;
export const isErrorEvent = _mod12947.isErrorEvent;
export const isEvent = _mod12947.isEvent;
export const isInstanceOf = _mod12947.isInstanceOf;
export const isParameterizedString = _mod12947.isParameterizedString;
export const isPlainObject = _mod12947.isPlainObject;
export const isPrimitive = _mod12947.isPrimitive;
export const isRegExp = _mod12947.isRegExp;
export const isString = _mod12947.isString;
export const isSyntheticEvent = _mod12947.isSyntheticEvent;
export const isThenable = _mod12947.isThenable;
export const isVueViewModel = _mod12947.isVueViewModel;
export const isBrowser = _mod13053.isBrowser;
export const CONSOLE_LEVELS = _mod12940.CONSOLE_LEVELS;
export const consoleSandbox = _mod12940.consoleSandbox;
export const logger = _mod12940.logger;
export const originalConsoleMethods = _mod12940.originalConsoleMethods;
export const memoBuilder = memoBuilder.memoBuilder;
export const addContextToFrame = _mod12951.addContextToFrame;
export const addExceptionMechanism = _mod12951.addExceptionMechanism;
export const addExceptionTypeValue = _mod12951.addExceptionTypeValue;
export const arrayify = _mod12951.arrayify;
export const checkOrSetAlreadyCaught = _mod12951.checkOrSetAlreadyCaught;
export const getEventDescription = _mod12951.getEventDescription;
export const parseSemver = _mod12951.parseSemver;
export const uuid4 = _mod12951.uuid4;
export const dynamicRequire = _mod13054.dynamicRequire;
export const isNodeEnv = _mod13054.isNodeEnv;
export const loadModule = _mod13054.loadModule;
export const normalize = _mod12985.normalize;
export const normalizeToSize = _mod12985.normalizeToSize;
export const normalizeUrlToBase = _mod12985.normalizeUrlToBase;
export const addNonEnumerableProperty = _mod12946.addNonEnumerableProperty;
export const convertToPlainObject = _mod12946.convertToPlainObject;
export const dropUndefinedKeys = _mod12946.dropUndefinedKeys;
export const extractExceptionKeysForMessage = _mod12946.extractExceptionKeysForMessage;
export const fill = _mod12946.fill;
export const getOriginalFunction = _mod12946.getOriginalFunction;
export const markFunctionWrapped = _mod12946.markFunctionWrapped;
export const objectify = _mod12946.objectify;
export const urlEncode = _mod12946.urlEncode;
export const basename = _mod13032.basename;
export const dirname = _mod13032.dirname;
export const isAbsolute = _mod13032.isAbsolute;
export const join = _mod13032.join;
export const normalizePath = _mod13032.normalizePath;
export const relative = _mod13032.relative;
export const resolve = _mod13032.resolve;
export const makePromiseBuffer = _mod13004.makePromiseBuffer;
export const DEFAULT_USER_INCLUDES = extractRequestData.DEFAULT_USER_INCLUDES;
export const addNormalizedRequestDataToEvent = extractRequestData.addNormalizedRequestDataToEvent;
export const addRequestDataToEvent = extractRequestData.addRequestDataToEvent;
export const extractPathForTransaction = extractRequestData.extractPathForTransaction;
export const extractQueryParamsFromUrl = extractRequestData.extractQueryParamsFromUrl;
export const extractRequestData = extractRequestData.extractRequestData;
export const headersToDict = extractRequestData.headersToDict;
export const httpRequestToRequestData = extractRequestData.httpRequestToRequestData;
export const winterCGHeadersToDict = extractRequestData.winterCGHeadersToDict;
export const winterCGRequestToRequestData = extractRequestData.winterCGRequestToRequestData;
export const severityLevelFromString = _mod13027.severityLevelFromString;
export const validSeverityLevels = _mod13027.validSeverityLevels;
export const UNKNOWN_FUNCTION = stackParserFromStackParserOptions.UNKNOWN_FUNCTION;
export const createStackParser = stackParserFromStackParserOptions.createStackParser;
export const getFramesFromEvent = stackParserFromStackParserOptions.getFramesFromEvent;
export const getFunctionName = stackParserFromStackParserOptions.getFunctionName;
export const stackParserFromStackParserOptions = stackParserFromStackParserOptions.stackParserFromStackParserOptions;
export const stripSentryFramesAndReverse = stackParserFromStackParserOptions.stripSentryFramesAndReverse;
export const filenameIsInApp = _mod13056.filenameIsInApp;
export const node = _mod13056.node;
export const nodeStackLineParser = _mod13056.nodeStackLineParser;
export const isMatchingPattern = _mod12949.isMatchingPattern;
export const safeJoin = _mod12949.safeJoin;
export const snipLine = _mod12949.snipLine;
export const stringMatchesSomePattern = _mod12949.stringMatchesSomePattern;
export const truncate = _mod12949.truncate;
export const isNativeFunction = supportsFetch.isNativeFunction;
export const supportsDOMError = supportsFetch.supportsDOMError;
export const supportsDOMException = supportsFetch.supportsDOMException;
export const supportsErrorEvent = supportsFetch.supportsErrorEvent;
export const supportsFetch = supportsFetch.supportsFetch;
export const supportsNativeFetch = supportsFetch.supportsNativeFetch;
export const supportsReferrerPolicy = supportsFetch.supportsReferrerPolicy;
export const supportsReportingObserver = supportsFetch.supportsReportingObserver;
export const SyncPromise = _mod12964.SyncPromise;
export const rejectedSyncPromise = _mod12964.rejectedSyncPromise;
export const resolvedSyncPromise = _mod12964.resolvedSyncPromise;
export const _browserPerformanceTimeOriginMode = require("12954__.js")._browserPerformanceTimeOriginMode;
export const browserPerformanceTimeOrigin = require("12954__.js").browserPerformanceTimeOrigin;
export const dateTimestampInSeconds = require("12954__.js").dateTimestampInSeconds;
export const timestampInSeconds = require("12954__.js").timestampInSeconds;
export const TRACEPARENT_REGEXP = _mod12952.TRACEPARENT_REGEXP;
export const extractTraceparentData = _mod12952.extractTraceparentData;
export const generateSentryTraceHeader = _mod12952.generateSentryTraceHeader;
export const propagationContextFromHeaders = _mod12952.propagationContextFromHeaders;
export const getSDKSource = _mod13055.getSDKSource;
export const isBrowserBundle = _mod13055.isBrowserBundle;
export const addItemToEnvelope = _mod12984.addItemToEnvelope;
export const createAttachmentEnvelopeItem = _mod12984.createAttachmentEnvelopeItem;
export const createEnvelope = _mod12984.createEnvelope;
export const createEventEnvelopeHeaders = _mod12984.createEventEnvelopeHeaders;
export const createSpanEnvelopeItem = _mod12984.createSpanEnvelopeItem;
export const envelopeContainsItemType = _mod12984.envelopeContainsItemType;
export const envelopeItemTypeToDataCategory = _mod12984.envelopeItemTypeToDataCategory;
export const forEachEnvelopeItem = _mod12984.forEachEnvelopeItem;
export const getSdkMetadataForEnvelopeHeader = _mod12984.getSdkMetadataForEnvelopeHeader;
export const parseEnvelope = _mod12984.parseEnvelope;
export const serializeEnvelope = _mod12984.serializeEnvelope;
export const createClientReportEnvelope = _mod12998.createClientReportEnvelope;
export const DEFAULT_RETRY_AFTER = _mod13005.DEFAULT_RETRY_AFTER;
export const disabledUntil = _mod13005.disabledUntil;
export const isRateLimited = _mod13005.isRateLimited;
export const parseRetryAfterHeader = _mod13005.parseRetryAfterHeader;
export const updateRateLimits = _mod13005.updateRateLimits;
export const BAGGAGE_HEADER_NAME = BAGGAGE_HEADER_NAME.BAGGAGE_HEADER_NAME;
export const MAX_BAGGAGE_STRING_LENGTH = BAGGAGE_HEADER_NAME.MAX_BAGGAGE_STRING_LENGTH;
export const SENTRY_BAGGAGE_KEY_PREFIX = BAGGAGE_HEADER_NAME.SENTRY_BAGGAGE_KEY_PREFIX;
export const SENTRY_BAGGAGE_KEY_PREFIX_REGEX = BAGGAGE_HEADER_NAME.SENTRY_BAGGAGE_KEY_PREFIX_REGEX;
export const baggageHeaderToDynamicSamplingContext = BAGGAGE_HEADER_NAME.baggageHeaderToDynamicSamplingContext;
export const dynamicSamplingContextToSentryBaggageHeader =
  BAGGAGE_HEADER_NAME.dynamicSamplingContextToSentryBaggageHeader;
export const parseBaggageHeader = BAGGAGE_HEADER_NAME.parseBaggageHeader;
export const getNumberOfUrlSegments = stripUrlQueryAndFragment.getNumberOfUrlSegments;
export const getSanitizedUrlString = stripUrlQueryAndFragment.getSanitizedUrlString;
export const parseUrl = stripUrlQueryAndFragment.parseUrl;
export const stripUrlQueryAndFragment = stripUrlQueryAndFragment.stripUrlQueryAndFragment;
export const makeFifoCache = _mod13057.makeFifoCache;
export const eventFromMessage = eventFromMessage.eventFromMessage;
export const eventFromUnknownInput = eventFromMessage.eventFromUnknownInput;
export const exceptionFromError = eventFromMessage.exceptionFromError;
export const parseStackFrames = eventFromMessage.parseStackFrames;
export const callFrameToStackFrame = _mod13058.callFrameToStackFrame;
export const watchdogTimer = _mod13058.watchdogTimer;
export const LRUMap = _mod13059.LRUMap;
export const generatePropagationContext = generatePropagationContext.generatePropagationContext;
export const generateSpanId = generatePropagationContext.generateSpanId;
export const generateTraceId = generatePropagationContext.generateTraceId;
export const vercelWaitUntil = _mod13060.vercelWaitUntil;
export const SDK_VERSION = _mod12942.SDK_VERSION;
export const getDebugImagesForResources = _mod12992.getDebugImagesForResources;
export const getFilenameToDebugIdMap = _mod12992.getFilenameToDebugIdMap;
export const escapeStringForRegex = _mod13061.escapeStringForRegex;
export const supportsHistory = supportsHistory.supportsHistory;
export const _asyncNullishCoalesce = _asyncNullishCoalesce2._asyncNullishCoalesce;
export const _asyncOptionalChain = _asyncOptionalChain2._asyncOptionalChain;
export const _asyncOptionalChainDelete = _asyncOptionalChainDelete2._asyncOptionalChainDelete;
export const _nullishCoalesce = _nullishCoalesce._nullishCoalesce;
export const _optionalChain = _optionalChain._optionalChain;
export const _optionalChainDelete = _optionalChainDelete._optionalChainDelete;
