// _runtime/metro/12943__.js
import errorCallback from "../12944_errorCallback.js";
import _mod12945 from "12945__.js";
import _mod12946 from "12946__.js";
import _mod12948 from "12948__.js";
import _mod12949 from "12949__.js";
import _mod12950 from "12950__.js";
import stackParserFromStackParserOptions from "../12951_stackParserFromStackParserOptions.js";
import _mod12952 from "12952__.js";
import spanTimeInputToSeconds from "../12953_spanTimeInputToSeconds.js";
import _mod12954 from "12954__.js";
import _mod12955 from "12955__.js";
import _mod12956 from "12956__.js";
import _mod12957 from "12957__.js";
import generatePropagationContext from "../12958_generatePropagationContext.js";
import _mod12959 from "12959__.js";
import _mod12960 from "12960__.js";
import BAGGAGE_HEADER_NAME from "../12961_BAGGAGE_HEADER_NAME.js";
import _mod12963 from "12963__.js";
import _mod12964 from "12964__.js";
import _mod12965 from "12965__.js";
import _mod12966 from "12966__.js";
import _mod12967 from "12967__.js";
import ScopeClass from "../12969_ScopeClass.js";
import _mod12971 from "12971__.js";
import _mod12972 from "12972__.js";
import _mod12974 from "12974__.js";
import _mod12975 from "12975__.js";
import _mod12977 from "12977__.js";
import _mod12978 from "12978__.js";
import _mod12979 from "12979__.js";
import _mod12980 from "12980__.js";
import _mod12981 from "12981__.js";
import _mod12982 from "12982__.js";
import _mod12983 from "12983__.js";
import _mod12984 from "12984__.js";
import _mod12985 from "12985__.js";
import _mod12986 from "12986__.js";
import _mod12987 from "12987__.js";
import _mod12988 from "12988__.js";
import _mod12989 from "12989__.js";
import _mod12990 from "12990__.js";
import _mod12991 from "12991__.js";
import _mod12992 from "12992__.js";
import _mod12993 from "12993__.js";
import memoBuilder from "../12994_memoBuilder.js";
import _mod12995 from "12995__.js";
import _flush from "../12996__flush.js";
import _mod12997 from "12997__.js";
import applyScopeDataToEvent from "../12998_applyScopeDataToEvent.js";
import notifyEventProcessors from "../12999_notifyEventProcessors.js";
import _mod13000 from "13000__.js";
import SessionFlusher from "../13001_SessionFlusher.js";
import _mod13002 from "13002__.js";
import _mod13003 from "13003__.js";
import _mod13004 from "13004__.js";
import _mod13005 from "13005__.js";
import _mod13006 from "13006__.js";
import _mod13007 from "13007__.js";
import eventFromMessage from "../13008_eventFromMessage.js";
import _mod13009 from "13009__.js";
import _mod13010 from "13010__.js";
import _mod13011 from "13011__.js";
import _mod13012 from "13012__.js";
import _mod13013 from "13013__.js";
import _mod13014 from "13014__.js";
import _mod13015 from "13015__.js";
import _mod13016 from "13016__.js";
import _mod13017 from "13017__.js";
import _mod13018 from "13018__.js";
import _mod13019 from "13019__.js";
import _mod13020 from "13020__.js";
import _mod13021 from "13021__.js";
import _mod13022 from "13022__.js";
import _getEventFilterUrl from "../13023__getEventFilterUrl.js";
import _mod13024 from "13024__.js";
import _mod13025 from "13025__.js";
import _mod13026 from "13026__.js";
import _mod13028 from "13028__.js";
import extractRequestData from "../13029_extractRequestData.js";
import stripUrlQueryAndFragment from "../13030_stripUrlQueryAndFragment.js";
import _mod13033 from "13033__.js";
import _mod13034 from "13034__.js";
import _mod13035 from "13035__.js";
import debugIntegration from "../13036_debugIntegration.js";
import _mod13037 from "13037__.js";
import extraErrorDataIntegration from "../13038_extraErrorDataIntegration.js";
import _mod13039 from "13039__.js";
import _mod13040 from "13040__.js";
import sessionTimingIntegration from "../13041_sessionTimingIntegration.js";
import _mod13042 from "13042__.js";
import _mod13043 from "13043__.js";
import _mod13044 from "13044__.js";
import _mod13046 from "13046__.js";
import metricsDefault from "../13047_metricsDefault.js";
import BrowserMetricsAggregator from "../13052_BrowserMetricsAggregator.js";
import _mod13053 from "13053__.js";
import _mod13054 from "13054__.js";
import _mod13055 from "13055__.js";
import _mod13056 from "13056__.js";
import _mod13057 from "13057__.js";
import _mod13058 from "13058__.js";
import _mod13059 from "13059__.js";
import supportsFetch from "../13060_supportsFetch.js";
import _mod13061 from "13061__.js";
import _mod13062 from "13062__.js";
import _mod13063 from "13063__.js";
import _mod13064 from "13064__.js";
import _mod13065 from "13065__.js";
import _mod13066 from "13066__.js";
import _mod13067 from "13067__.js";
import _mod13068 from "13068__.js";
import _mod13069 from "13069__.js";
import supportsHistory from "../13070_supportsHistory.js";
import _asyncNullishCoalesce2 from "../13071__asyncNullishCoalesce2.js";
import _nullishCoalesce from "../13072__nullishCoalesce.js";
import _asyncOptionalChain2 from "../13073__asyncOptionalChain2.js";
import _asyncOptionalChainDelete2 from "../13074__asyncOptionalChainDelete2.js";
import _optionalChain from "../13075__optionalChain.js";
import _optionalChainDelete from "../13076__optionalChainDelete.js";

const require = globalThis.__r;

export const registerSpanErrorInstrumentation = errorCallback.registerSpanErrorInstrumentation;
export const getCapturedScopesOnSpan = _mod12977.getCapturedScopesOnSpan;
export const setCapturedScopesOnSpan = _mod12977.setCapturedScopesOnSpan;
export const addTracingExtensions = _mod12978.addTracingExtensions;
export const TRACING_DEFAULTS = _mod12979.TRACING_DEFAULTS;
export const startIdleSpan = _mod12979.startIdleSpan;
export const SentrySpan = _mod12989.SentrySpan;
export const SentryNonRecordingSpan = _mod12981.SentryNonRecordingSpan;
export const SPAN_STATUS_ERROR = _mod12965.SPAN_STATUS_ERROR;
export const SPAN_STATUS_OK = _mod12965.SPAN_STATUS_OK;
export const SPAN_STATUS_UNSET = _mod12965.SPAN_STATUS_UNSET;
export const getSpanStatusFromHttpCode = _mod12965.getSpanStatusFromHttpCode;
export const setHttpStatus = _mod12965.setHttpStatus;
export const continueTrace = _mod12982.continueTrace;
export const startInactiveSpan = _mod12982.startInactiveSpan;
export const startNewTrace = _mod12982.startNewTrace;
export const startSpan = _mod12982.startSpan;
export const startSpanManual = _mod12982.startSpanManual;
export const suppressTracing = _mod12982.suppressTracing;
export const withActiveSpan = _mod12982.withActiveSpan;
export const getDynamicSamplingContextFromClient = _mod12984.getDynamicSamplingContextFromClient;
export const getDynamicSamplingContextFromScope = _mod12984.getDynamicSamplingContextFromScope;
export const getDynamicSamplingContextFromSpan = _mod12984.getDynamicSamplingContextFromSpan;
export const spanToBaggageHeader = _mod12984.spanToBaggageHeader;
export const setMeasurement = _mod12990.setMeasurement;
export const timedEventsToMeasurements = _mod12990.timedEventsToMeasurements;
export const sampleSpan = _mod12987.sampleSpan;
export const logSpanEnd = _mod12986.logSpanEnd;
export const logSpanStart = _mod12986.logSpanStart;
export const SEMANTIC_ATTRIBUTE_CACHE_HIT = _mod12963.SEMANTIC_ATTRIBUTE_CACHE_HIT;
export const SEMANTIC_ATTRIBUTE_CACHE_ITEM_SIZE = _mod12963.SEMANTIC_ATTRIBUTE_CACHE_ITEM_SIZE;
export const SEMANTIC_ATTRIBUTE_CACHE_KEY = _mod12963.SEMANTIC_ATTRIBUTE_CACHE_KEY;
export const SEMANTIC_ATTRIBUTE_EXCLUSIVE_TIME = _mod12963.SEMANTIC_ATTRIBUTE_EXCLUSIVE_TIME;
export const SEMANTIC_ATTRIBUTE_HTTP_REQUEST_METHOD = _mod12963.SEMANTIC_ATTRIBUTE_HTTP_REQUEST_METHOD;
export const SEMANTIC_ATTRIBUTE_PROFILE_ID = _mod12963.SEMANTIC_ATTRIBUTE_PROFILE_ID;
export const SEMANTIC_ATTRIBUTE_SENTRY_CUSTOM_SPAN_NAME = _mod12963.SEMANTIC_ATTRIBUTE_SENTRY_CUSTOM_SPAN_NAME;
export const SEMANTIC_ATTRIBUTE_SENTRY_IDLE_SPAN_FINISH_REASON =
  _mod12963.SEMANTIC_ATTRIBUTE_SENTRY_IDLE_SPAN_FINISH_REASON;
export const SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_UNIT = _mod12963.SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_UNIT;
export const SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_VALUE = _mod12963.SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_VALUE;
export const SEMANTIC_ATTRIBUTE_SENTRY_OP = _mod12963.SEMANTIC_ATTRIBUTE_SENTRY_OP;
export const SEMANTIC_ATTRIBUTE_SENTRY_ORIGIN = _mod12963.SEMANTIC_ATTRIBUTE_SENTRY_ORIGIN;
export const SEMANTIC_ATTRIBUTE_SENTRY_SAMPLE_RATE = _mod12963.SEMANTIC_ATTRIBUTE_SENTRY_SAMPLE_RATE;
export const SEMANTIC_ATTRIBUTE_SENTRY_SOURCE = _mod12963.SEMANTIC_ATTRIBUTE_SENTRY_SOURCE;
export const SEMANTIC_ATTRIBUTE_URL_FULL = _mod12963.SEMANTIC_ATTRIBUTE_URL_FULL;
export const createEventEnvelope = _mod12991.createEventEnvelope;
export const createSessionEnvelope = _mod12991.createSessionEnvelope;
export const createSpanEnvelope = _mod12991.createSpanEnvelope;
export const addEventProcessor = _flush.addEventProcessor;
export const captureCheckIn = _flush.captureCheckIn;
export const captureEvent = _flush.captureEvent;
export const captureException = _flush.captureException;
export const captureMessage = _flush.captureMessage;
export const captureSession = _flush.captureSession;
export const close = _flush.close;
export const endSession = _flush.endSession;
export const flush = _flush.flush;
export const isEnabled = _flush.isEnabled;
export const isInitialized = _flush.isInitialized;
export const lastEventId = _flush.lastEventId;
export const setContext = _flush.setContext;
export const setExtra = _flush.setExtra;
export const setExtras = _flush.setExtras;
export const setTag = _flush.setTag;
export const setTags = _flush.setTags;
export const setUser = _flush.setUser;
export const startSession = _flush.startSession;
export const withMonitor = _flush.withMonitor;
export const getClient = _mod12975.getClient;
export const getCurrentScope = _mod12975.getCurrentScope;
export const getGlobalScope = _mod12975.getGlobalScope;
export const getIsolationScope = _mod12975.getIsolationScope;
export const getTraceContextFromScope = _mod12975.getTraceContextFromScope;
export const withIsolationScope = _mod12975.withIsolationScope;
export const withScope = _mod12975.withScope;
export const getDefaultCurrentScope = _mod12974.getDefaultCurrentScope;
export const getDefaultIsolationScope = _mod12974.getDefaultIsolationScope;
export const setAsyncContextStrategy = _mod12967.setAsyncContextStrategy;
export const getMainCarrier = _mod12966.getMainCarrier;
export const closeSession = _mod12971.closeSession;
export const makeSession = _mod12971.makeSession;
export const updateSession = _mod12971.updateSession;
export const SessionFlusher = SessionFlusher.SessionFlusher;
export const Scope = ScopeClass.Scope;
export const notifyEventProcessors = notifyEventProcessors.notifyEventProcessors;
export const getEnvelopeEndpointWithUrlEncodedAuth = _mod13002.getEnvelopeEndpointWithUrlEncodedAuth;
export const getReportDialogEndpoint = _mod13002.getReportDialogEndpoint;
export const BaseClient = _mod13003.BaseClient;
export const ServerRuntimeClient = _mod13007.ServerRuntimeClient;
export const initAndBind = _mod13010.initAndBind;
export const setCurrentClient = _mod13010.setCurrentClient;
export const createTransport = _mod13011.createTransport;
export const makeOfflineTransport = _mod13014.makeOfflineTransport;
export const makeMultiplexedTransport = _mod13015.makeMultiplexedTransport;
export const addIntegration = _mod13004.addIntegration;
export const defineIntegration = _mod13004.defineIntegration;
export const getIntegrationsToSetup = _mod13004.getIntegrationsToSetup;
export const applyScopeDataToEvent = applyScopeDataToEvent.applyScopeDataToEvent;
export const mergeScopeData = applyScopeDataToEvent.mergeScopeData;
export const prepareEvent = _mod12997.prepareEvent;
export const createCheckInEnvelope = _mod13009.createCheckInEnvelope;
export const hasTracingEnabled = _mod12980.hasTracingEnabled;
export const isSentryRequestUrl = _mod13016.isSentryRequestUrl;
export const handleCallbackErrors = _mod12983.handleCallbackErrors;
export const parameterize = _mod13017.parameterize;
export const addChildSpanToSpan = spanTimeInputToSeconds.addChildSpanToSpan;
export const getActiveSpan = spanTimeInputToSeconds.getActiveSpan;
export const getRootSpan = spanTimeInputToSeconds.getRootSpan;
export const getSpanDescendants = spanTimeInputToSeconds.getSpanDescendants;
export const getStatusMessage = spanTimeInputToSeconds.getStatusMessage;
export const spanIsSampled = spanTimeInputToSeconds.spanIsSampled;
export const spanTimeInputToSeconds = spanTimeInputToSeconds.spanTimeInputToSeconds;
export const spanToJSON = spanTimeInputToSeconds.spanToJSON;
export const spanToTraceContext = spanTimeInputToSeconds.spanToTraceContext;
export const spanToTraceHeader = spanTimeInputToSeconds.spanToTraceHeader;
export const updateSpanName = spanTimeInputToSeconds.updateSpanName;
export const parseSampleRate = _mod12988.parseSampleRate;
export const applySdkMetadata = _mod13018.applySdkMetadata;
export const getTraceData = _mod13019.getTraceData;
export const getTraceMetaTags = _mod13020.getTraceMetaTags;
export const DEFAULT_ENVIRONMENT = _mod12985.DEFAULT_ENVIRONMENT;
export const addBreadcrumb = _mod13021.addBreadcrumb;
export const functionToStringIntegration = _mod13022.functionToStringIntegration;
export const inboundFiltersIntegration = _getEventFilterUrl.inboundFiltersIntegration;
export const linkedErrorsIntegration = _mod13024.linkedErrorsIntegration;
export const moduleMetadataIntegration = _mod13026.moduleMetadataIntegration;
export const requestDataIntegration = _mod13028.requestDataIntegration;
export const captureConsoleIntegration = _mod13033.captureConsoleIntegration;
export const debugIntegration = debugIntegration.debugIntegration;
export const dedupeIntegration = _mod13037.dedupeIntegration;
export const extraErrorDataIntegration = extraErrorDataIntegration.extraErrorDataIntegration;
export const rewriteFramesIntegration = _mod13039.rewriteFramesIntegration;
export const sessionTimingIntegration = sessionTimingIntegration.sessionTimingIntegration;
export const zodErrorsIntegration = _mod13042.zodErrorsIntegration;
export const thirdPartyErrorFilterIntegration = _mod13043.thirdPartyErrorFilterIntegration;
export const metrics = _mod13044.metrics;
export const profiler = _mod13046.profiler;
export const metricsDefault = metricsDefault.metricsDefault;
export const BrowserMetricsAggregator = BrowserMetricsAggregator.BrowserMetricsAggregator;
export const getMetricSummaryJsonForSpan = _mod12964.getMetricSummaryJsonForSpan;
export const addTracingHeadersToFetchRequest = _mod13053.addTracingHeadersToFetchRequest;
export const instrumentFetchRequest = _mod13053.instrumentFetchRequest;
export const trpcMiddleware = _mod13054.trpcMiddleware;
export const captureFeedback = _mod13055.captureFeedback;
export const getCurrentHub = _mod13056.getCurrentHub;
export const getCurrentHubShim = _mod13056.getCurrentHubShim;
export const applyAggregateErrorsToEvent = _mod13025.applyAggregateErrorsToEvent;
export const flatten = _mod13057.flatten;
export const getBreadcrumbLogLevelFromHttpStatusCode = _mod13058.getBreadcrumbLogLevelFromHttpStatusCode;
export const getComponentName = _mod12956.getComponentName;
export const getDomElement = _mod12956.getDomElement;
export const getLocationHref = _mod12956.getLocationHref;
export const htmlTreeAsString = _mod12956.htmlTreeAsString;
export const dsnFromString = _mod12995.dsnFromString;
export const dsnToString = _mod12995.dsnToString;
export const makeDsn = _mod12995.makeDsn;
export const SentryError = _mod13005.SentryError;
export const GLOBAL_OBJ = _mod12949.GLOBAL_OBJ;
export const getGlobalSingleton = _mod12949.getGlobalSingleton;
export const addConsoleInstrumentationHandler = _mod13034.addConsoleInstrumentationHandler;
export const addFetchEndInstrumentationHandler = _mod13059.addFetchEndInstrumentationHandler;
export const addFetchInstrumentationHandler = _mod13059.addFetchInstrumentationHandler;
export const addGlobalErrorInstrumentationHandler = _mod12945.addGlobalErrorInstrumentationHandler;
export const addGlobalUnhandledRejectionInstrumentationHandler =
  _mod12952.addGlobalUnhandledRejectionInstrumentationHandler;
export const addHandler = _mod12946.addHandler;
export const maybeInstrument = _mod12946.maybeInstrument;
export const resetInstrumentationHandlers = _mod12946.resetInstrumentationHandlers;
export const triggerHandlers = _mod12946.triggerHandlers;
export const isDOMError = _mod12955.isDOMError;
export const isDOMException = _mod12955.isDOMException;
export const isElement = _mod12955.isElement;
export const isError = _mod12955.isError;
export const isErrorEvent = _mod12955.isErrorEvent;
export const isEvent = _mod12955.isEvent;
export const isInstanceOf = _mod12955.isInstanceOf;
export const isParameterizedString = _mod12955.isParameterizedString;
export const isPlainObject = _mod12955.isPlainObject;
export const isPrimitive = _mod12955.isPrimitive;
export const isRegExp = _mod12955.isRegExp;
export const isString = _mod12955.isString;
export const isSyntheticEvent = _mod12955.isSyntheticEvent;
export const isThenable = _mod12955.isThenable;
export const isVueViewModel = _mod12955.isVueViewModel;
export const isBrowser = _mod13061.isBrowser;
export const CONSOLE_LEVELS = _mod12948.CONSOLE_LEVELS;
export const consoleSandbox = _mod12948.consoleSandbox;
export const logger = _mod12948.logger;
export const originalConsoleMethods = _mod12948.originalConsoleMethods;
export const memoBuilder = memoBuilder.memoBuilder;
export const addContextToFrame = _mod12959.addContextToFrame;
export const addExceptionMechanism = _mod12959.addExceptionMechanism;
export const addExceptionTypeValue = _mod12959.addExceptionTypeValue;
export const arrayify = _mod12959.arrayify;
export const checkOrSetAlreadyCaught = _mod12959.checkOrSetAlreadyCaught;
export const getEventDescription = _mod12959.getEventDescription;
export const parseSemver = _mod12959.parseSemver;
export const uuid4 = _mod12959.uuid4;
export const dynamicRequire = _mod13062.dynamicRequire;
export const isNodeEnv = _mod13062.isNodeEnv;
export const loadModule = _mod13062.loadModule;
export const normalize = _mod12993.normalize;
export const normalizeToSize = _mod12993.normalizeToSize;
export const normalizeUrlToBase = _mod12993.normalizeUrlToBase;
export const addNonEnumerableProperty = _mod12954.addNonEnumerableProperty;
export const convertToPlainObject = _mod12954.convertToPlainObject;
export const dropUndefinedKeys = _mod12954.dropUndefinedKeys;
export const extractExceptionKeysForMessage = _mod12954.extractExceptionKeysForMessage;
export const fill = _mod12954.fill;
export const getOriginalFunction = _mod12954.getOriginalFunction;
export const markFunctionWrapped = _mod12954.markFunctionWrapped;
export const objectify = _mod12954.objectify;
export const urlEncode = _mod12954.urlEncode;
export const basename = _mod13040.basename;
export const dirname = _mod13040.dirname;
export const isAbsolute = _mod13040.isAbsolute;
export const join = _mod13040.join;
export const normalizePath = _mod13040.normalizePath;
export const relative = _mod13040.relative;
export const resolve = _mod13040.resolve;
export const makePromiseBuffer = _mod13012.makePromiseBuffer;
export const DEFAULT_USER_INCLUDES = extractRequestData.DEFAULT_USER_INCLUDES;
export const addNormalizedRequestDataToEvent = extractRequestData.addNormalizedRequestDataToEvent;
export const addRequestDataToEvent = extractRequestData.addRequestDataToEvent;
export const extractPathForTransaction = extractRequestData.extractPathForTransaction;
export const extractQueryParamsFromUrl = extractRequestData.extractQueryParamsFromUrl;
export const extractRequestData = extractRequestData.extractRequestData;
export const headersToDict = extractRequestData.headersToDict;
export const httpRequestToRequestData = extractRequestData.httpRequestToRequestData;
export const winterCGHeadersToDict = extractRequestData.winterCGHeadersToDict;
export const winterCGRequestToRequestData = extractRequestData.winterCGRequestToRequestData;
export const severityLevelFromString = _mod13035.severityLevelFromString;
export const validSeverityLevels = _mod13035.validSeverityLevels;
export const UNKNOWN_FUNCTION = stackParserFromStackParserOptions.UNKNOWN_FUNCTION;
export const createStackParser = stackParserFromStackParserOptions.createStackParser;
export const getFramesFromEvent = stackParserFromStackParserOptions.getFramesFromEvent;
export const getFunctionName = stackParserFromStackParserOptions.getFunctionName;
export const stackParserFromStackParserOptions = stackParserFromStackParserOptions.stackParserFromStackParserOptions;
export const stripSentryFramesAndReverse = stackParserFromStackParserOptions.stripSentryFramesAndReverse;
export const filenameIsInApp = _mod13064.filenameIsInApp;
export const node = _mod13064.node;
export const nodeStackLineParser = _mod13064.nodeStackLineParser;
export const isMatchingPattern = _mod12957.isMatchingPattern;
export const safeJoin = _mod12957.safeJoin;
export const snipLine = _mod12957.snipLine;
export const stringMatchesSomePattern = _mod12957.stringMatchesSomePattern;
export const truncate = _mod12957.truncate;
export const isNativeFunction = supportsFetch.isNativeFunction;
export const supportsDOMError = supportsFetch.supportsDOMError;
export const supportsDOMException = supportsFetch.supportsDOMException;
export const supportsErrorEvent = supportsFetch.supportsErrorEvent;
export const supportsFetch = supportsFetch.supportsFetch;
export const supportsNativeFetch = supportsFetch.supportsNativeFetch;
export const supportsReferrerPolicy = supportsFetch.supportsReferrerPolicy;
export const supportsReportingObserver = supportsFetch.supportsReportingObserver;
export const SyncPromise = _mod12972.SyncPromise;
export const rejectedSyncPromise = _mod12972.rejectedSyncPromise;
export const resolvedSyncPromise = _mod12972.resolvedSyncPromise;
export const _browserPerformanceTimeOriginMode = require("12962__.js")._browserPerformanceTimeOriginMode;
export const browserPerformanceTimeOrigin = require("12962__.js").browserPerformanceTimeOrigin;
export const dateTimestampInSeconds = require("12962__.js").dateTimestampInSeconds;
export const timestampInSeconds = require("12962__.js").timestampInSeconds;
export const TRACEPARENT_REGEXP = _mod12960.TRACEPARENT_REGEXP;
export const extractTraceparentData = _mod12960.extractTraceparentData;
export const generateSentryTraceHeader = _mod12960.generateSentryTraceHeader;
export const propagationContextFromHeaders = _mod12960.propagationContextFromHeaders;
export const getSDKSource = _mod13063.getSDKSource;
export const isBrowserBundle = _mod13063.isBrowserBundle;
export const addItemToEnvelope = _mod12992.addItemToEnvelope;
export const createAttachmentEnvelopeItem = _mod12992.createAttachmentEnvelopeItem;
export const createEnvelope = _mod12992.createEnvelope;
export const createEventEnvelopeHeaders = _mod12992.createEventEnvelopeHeaders;
export const createSpanEnvelopeItem = _mod12992.createSpanEnvelopeItem;
export const envelopeContainsItemType = _mod12992.envelopeContainsItemType;
export const envelopeItemTypeToDataCategory = _mod12992.envelopeItemTypeToDataCategory;
export const forEachEnvelopeItem = _mod12992.forEachEnvelopeItem;
export const getSdkMetadataForEnvelopeHeader = _mod12992.getSdkMetadataForEnvelopeHeader;
export const parseEnvelope = _mod12992.parseEnvelope;
export const serializeEnvelope = _mod12992.serializeEnvelope;
export const createClientReportEnvelope = _mod13006.createClientReportEnvelope;
export const DEFAULT_RETRY_AFTER = _mod13013.DEFAULT_RETRY_AFTER;
export const disabledUntil = _mod13013.disabledUntil;
export const isRateLimited = _mod13013.isRateLimited;
export const parseRetryAfterHeader = _mod13013.parseRetryAfterHeader;
export const updateRateLimits = _mod13013.updateRateLimits;
export const BAGGAGE_HEADER_NAME = BAGGAGE_HEADER_NAME.BAGGAGE_HEADER_NAME;
export const MAX_BAGGAGE_STRING_LENGTH = BAGGAGE_HEADER_NAME.MAX_BAGGAGE_STRING_LENGTH;
export const SENTRY_BAGGAGE_KEY_PREFIX = BAGGAGE_HEADER_NAME.SENTRY_BAGGAGE_KEY_PREFIX;
export const SENTRY_BAGGAGE_KEY_PREFIX_REGEX = BAGGAGE_HEADER_NAME.SENTRY_BAGGAGE_KEY_PREFIX_REGEX;
export const baggageHeaderToDynamicSamplingContext = BAGGAGE_HEADER_NAME.baggageHeaderToDynamicSamplingContext;
export const dynamicSamplingContextToSentryBaggageHeader =
  BAGGAGE_HEADER_NAME.dynamicSamplingContextToSentryBaggageHeader;
export const parseBaggageHeader = BAGGAGE_HEADER_NAME.parseBaggageHeader;
export const getNumberOfUrlSegments = stripUrlQueryAndFragment.getNumberOfUrlSegments;
export const getSanitizedUrlString = stripUrlQueryAndFragment.getSanitizedUrlString;
export const parseUrl = stripUrlQueryAndFragment.parseUrl;
export const stripUrlQueryAndFragment = stripUrlQueryAndFragment.stripUrlQueryAndFragment;
export const makeFifoCache = _mod13065.makeFifoCache;
export const eventFromMessage = eventFromMessage.eventFromMessage;
export const eventFromUnknownInput = eventFromMessage.eventFromUnknownInput;
export const exceptionFromError = eventFromMessage.exceptionFromError;
export const parseStackFrames = eventFromMessage.parseStackFrames;
export const callFrameToStackFrame = _mod13066.callFrameToStackFrame;
export const watchdogTimer = _mod13066.watchdogTimer;
export const LRUMap = _mod13067.LRUMap;
export const generatePropagationContext = generatePropagationContext.generatePropagationContext;
export const generateSpanId = generatePropagationContext.generateSpanId;
export const generateTraceId = generatePropagationContext.generateTraceId;
export const vercelWaitUntil = _mod13068.vercelWaitUntil;
export const SDK_VERSION = _mod12950.SDK_VERSION;
export const getDebugImagesForResources = _mod13000.getDebugImagesForResources;
export const getFilenameToDebugIdMap = _mod13000.getFilenameToDebugIdMap;
export const escapeStringForRegex = _mod13069.escapeStringForRegex;
export const supportsHistory = supportsHistory.supportsHistory;
export const _asyncNullishCoalesce = _asyncNullishCoalesce2._asyncNullishCoalesce;
export const _asyncOptionalChain = _asyncOptionalChain2._asyncOptionalChain;
export const _asyncOptionalChainDelete = _asyncOptionalChainDelete2._asyncOptionalChainDelete;
export const _nullishCoalesce = _nullishCoalesce._nullishCoalesce;
export const _optionalChain = _optionalChain._optionalChain;
export const _optionalChainDelete = _optionalChainDelete._optionalChainDelete;
