// _runtime/metro/13034__.js
import errorCallback from "../13035_errorCallback.js";
import _mod13036 from "13036__.js";
import _mod13037 from "13037__.js";
import _mod13039 from "13039__.js";
import _mod13040 from "13040__.js";
import _mod13041 from "13041__.js";
import stackParserFromStackParserOptions from "../13042_stackParserFromStackParserOptions.js";
import _mod13043 from "13043__.js";
import spanTimeInputToSeconds from "../13044_spanTimeInputToSeconds.js";
import _mod13045 from "13045__.js";
import _mod13046 from "13046__.js";
import _mod13047 from "13047__.js";
import _mod13048 from "13048__.js";
import generatePropagationContext from "../13049_generatePropagationContext.js";
import _mod13050 from "13050__.js";
import _mod13051 from "13051__.js";
import BAGGAGE_HEADER_NAME from "../13052_BAGGAGE_HEADER_NAME.js";
import _mod13054 from "13054__.js";
import _mod13055 from "13055__.js";
import _mod13056 from "13056__.js";
import _mod13057 from "13057__.js";
import _mod13058 from "13058__.js";
import ScopeClass from "../13060_ScopeClass.js";
import _mod13062 from "13062__.js";
import _mod13063 from "13063__.js";
import _mod13065 from "13065__.js";
import _mod13066 from "13066__.js";
import _mod13068 from "13068__.js";
import _mod13069 from "13069__.js";
import _mod13070 from "13070__.js";
import _mod13071 from "13071__.js";
import _mod13072 from "13072__.js";
import _mod13073 from "13073__.js";
import _mod13074 from "13074__.js";
import _mod13075 from "13075__.js";
import _mod13076 from "13076__.js";
import _mod13077 from "13077__.js";
import _mod13078 from "13078__.js";
import _mod13079 from "13079__.js";
import _mod13080 from "13080__.js";
import _mod13081 from "13081__.js";
import _mod13082 from "13082__.js";
import _mod13083 from "13083__.js";
import _mod13084 from "13084__.js";
import memoBuilder from "../13085_memoBuilder.js";
import _mod13086 from "13086__.js";
import _flush from "../13087__flush.js";
import _mod13088 from "13088__.js";
import applyScopeDataToEvent from "../13089_applyScopeDataToEvent.js";
import notifyEventProcessors from "../13090_notifyEventProcessors.js";
import _mod13091 from "13091__.js";
import SessionFlusher from "../13092_SessionFlusher.js";
import _mod13093 from "13093__.js";
import _mod13094 from "13094__.js";
import _mod13095 from "13095__.js";
import _mod13096 from "13096__.js";
import _mod13097 from "13097__.js";
import _mod13098 from "13098__.js";
import eventFromMessage from "../13099_eventFromMessage.js";
import _mod13100 from "13100__.js";
import _mod13101 from "13101__.js";
import _mod13102 from "13102__.js";
import _mod13103 from "13103__.js";
import _mod13104 from "13104__.js";
import _mod13105 from "13105__.js";
import _mod13106 from "13106__.js";
import _mod13107 from "13107__.js";
import _mod13108 from "13108__.js";
import _mod13109 from "13109__.js";
import _mod13110 from "13110__.js";
import _mod13111 from "13111__.js";
import _mod13112 from "13112__.js";
import _mod13113 from "13113__.js";
import _getEventFilterUrl from "../13114__getEventFilterUrl.js";
import _mod13115 from "13115__.js";
import _mod13116 from "13116__.js";
import _mod13117 from "13117__.js";
import _mod13119 from "13119__.js";
import extractRequestData from "../13120_extractRequestData.js";
import stripUrlQueryAndFragment from "../13121_stripUrlQueryAndFragment.js";
import _mod13124 from "13124__.js";
import _mod13125 from "13125__.js";
import _mod13126 from "13126__.js";
import debugIntegration from "../13127_debugIntegration.js";
import _mod13128 from "13128__.js";
import extraErrorDataIntegration from "../13129_extraErrorDataIntegration.js";
import _mod13130 from "13130__.js";
import _mod13131 from "13131__.js";
import sessionTimingIntegration from "../13132_sessionTimingIntegration.js";
import _mod13133 from "13133__.js";
import _mod13134 from "13134__.js";
import _mod13135 from "13135__.js";
import _mod13137 from "13137__.js";
import metricsDefault from "../13138_metricsDefault.js";
import BrowserMetricsAggregator from "../13143_BrowserMetricsAggregator.js";
import _mod13144 from "13144__.js";
import _mod13145 from "13145__.js";
import _mod13146 from "13146__.js";
import _mod13147 from "13147__.js";
import _mod13148 from "13148__.js";
import _mod13149 from "13149__.js";
import _mod13150 from "13150__.js";
import supportsFetch from "../13151_supportsFetch.js";
import _mod13152 from "13152__.js";
import _mod13153 from "13153__.js";
import _mod13154 from "13154__.js";
import _mod13155 from "13155__.js";
import _mod13156 from "13156__.js";
import _mod13157 from "13157__.js";
import _mod13158 from "13158__.js";
import _mod13159 from "13159__.js";
import _mod13160 from "13160__.js";
import supportsHistory from "../13161_supportsHistory.js";
import _asyncNullishCoalesce2 from "../13162__asyncNullishCoalesce2.js";
import _nullishCoalesce from "../13163__nullishCoalesce.js";
import _asyncOptionalChain2 from "../13164__asyncOptionalChain2.js";
import _asyncOptionalChainDelete2 from "../13165__asyncOptionalChainDelete2.js";
import _optionalChain from "../13166__optionalChain.js";
import _optionalChainDelete from "../13167__optionalChainDelete.js";

const require = globalThis.__r;

export const registerSpanErrorInstrumentation = errorCallback.registerSpanErrorInstrumentation;
export const getCapturedScopesOnSpan = _mod13068.getCapturedScopesOnSpan;
export const setCapturedScopesOnSpan = _mod13068.setCapturedScopesOnSpan;
export const addTracingExtensions = _mod13069.addTracingExtensions;
export const TRACING_DEFAULTS = _mod13070.TRACING_DEFAULTS;
export const startIdleSpan = _mod13070.startIdleSpan;
export const SentrySpan = _mod13080.SentrySpan;
export const SentryNonRecordingSpan = _mod13072.SentryNonRecordingSpan;
export const SPAN_STATUS_ERROR = _mod13056.SPAN_STATUS_ERROR;
export const SPAN_STATUS_OK = _mod13056.SPAN_STATUS_OK;
export const SPAN_STATUS_UNSET = _mod13056.SPAN_STATUS_UNSET;
export const getSpanStatusFromHttpCode = _mod13056.getSpanStatusFromHttpCode;
export const setHttpStatus = _mod13056.setHttpStatus;
export const continueTrace = _mod13073.continueTrace;
export const startInactiveSpan = _mod13073.startInactiveSpan;
export const startNewTrace = _mod13073.startNewTrace;
export const startSpan = _mod13073.startSpan;
export const startSpanManual = _mod13073.startSpanManual;
export const suppressTracing = _mod13073.suppressTracing;
export const withActiveSpan = _mod13073.withActiveSpan;
export const getDynamicSamplingContextFromClient = _mod13075.getDynamicSamplingContextFromClient;
export const getDynamicSamplingContextFromScope = _mod13075.getDynamicSamplingContextFromScope;
export const getDynamicSamplingContextFromSpan = _mod13075.getDynamicSamplingContextFromSpan;
export const spanToBaggageHeader = _mod13075.spanToBaggageHeader;
export const setMeasurement = _mod13081.setMeasurement;
export const timedEventsToMeasurements = _mod13081.timedEventsToMeasurements;
export const sampleSpan = _mod13078.sampleSpan;
export const logSpanEnd = _mod13077.logSpanEnd;
export const logSpanStart = _mod13077.logSpanStart;
export const SEMANTIC_ATTRIBUTE_CACHE_HIT = _mod13054.SEMANTIC_ATTRIBUTE_CACHE_HIT;
export const SEMANTIC_ATTRIBUTE_CACHE_ITEM_SIZE = _mod13054.SEMANTIC_ATTRIBUTE_CACHE_ITEM_SIZE;
export const SEMANTIC_ATTRIBUTE_CACHE_KEY = _mod13054.SEMANTIC_ATTRIBUTE_CACHE_KEY;
export const SEMANTIC_ATTRIBUTE_EXCLUSIVE_TIME = _mod13054.SEMANTIC_ATTRIBUTE_EXCLUSIVE_TIME;
export const SEMANTIC_ATTRIBUTE_HTTP_REQUEST_METHOD = _mod13054.SEMANTIC_ATTRIBUTE_HTTP_REQUEST_METHOD;
export const SEMANTIC_ATTRIBUTE_PROFILE_ID = _mod13054.SEMANTIC_ATTRIBUTE_PROFILE_ID;
export const SEMANTIC_ATTRIBUTE_SENTRY_CUSTOM_SPAN_NAME = _mod13054.SEMANTIC_ATTRIBUTE_SENTRY_CUSTOM_SPAN_NAME;
export const SEMANTIC_ATTRIBUTE_SENTRY_IDLE_SPAN_FINISH_REASON =
  _mod13054.SEMANTIC_ATTRIBUTE_SENTRY_IDLE_SPAN_FINISH_REASON;
export const SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_UNIT = _mod13054.SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_UNIT;
export const SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_VALUE = _mod13054.SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_VALUE;
export const SEMANTIC_ATTRIBUTE_SENTRY_OP = _mod13054.SEMANTIC_ATTRIBUTE_SENTRY_OP;
export const SEMANTIC_ATTRIBUTE_SENTRY_ORIGIN = _mod13054.SEMANTIC_ATTRIBUTE_SENTRY_ORIGIN;
export const SEMANTIC_ATTRIBUTE_SENTRY_SAMPLE_RATE = _mod13054.SEMANTIC_ATTRIBUTE_SENTRY_SAMPLE_RATE;
export const SEMANTIC_ATTRIBUTE_SENTRY_SOURCE = _mod13054.SEMANTIC_ATTRIBUTE_SENTRY_SOURCE;
export const SEMANTIC_ATTRIBUTE_URL_FULL = _mod13054.SEMANTIC_ATTRIBUTE_URL_FULL;
export const createEventEnvelope = _mod13082.createEventEnvelope;
export const createSessionEnvelope = _mod13082.createSessionEnvelope;
export const createSpanEnvelope = _mod13082.createSpanEnvelope;
export const addEventProcessor = _flush.addEventProcessor;
export const captureCheckIn = _flush.captureCheckIn;
export const captureEvent = _flush.captureEvent;
export const captureException = _flush.captureException;
export const captureMessage = _flush.captureMessage;
export const captureSession = _flush.captureSession;
export const close = _flush.close;
export const endSession = _flush.endSession;
export const flush = _flush.flush;
export const isEnabled = _flush.isEnabled;
export const isInitialized = _flush.isInitialized;
export const lastEventId = _flush.lastEventId;
export const setContext = _flush.setContext;
export const setExtra = _flush.setExtra;
export const setExtras = _flush.setExtras;
export const setTag = _flush.setTag;
export const setTags = _flush.setTags;
export const setUser = _flush.setUser;
export const startSession = _flush.startSession;
export const withMonitor = _flush.withMonitor;
export const getClient = _mod13066.getClient;
export const getCurrentScope = _mod13066.getCurrentScope;
export const getGlobalScope = _mod13066.getGlobalScope;
export const getIsolationScope = _mod13066.getIsolationScope;
export const getTraceContextFromScope = _mod13066.getTraceContextFromScope;
export const withIsolationScope = _mod13066.withIsolationScope;
export const withScope = _mod13066.withScope;
export const getDefaultCurrentScope = _mod13065.getDefaultCurrentScope;
export const getDefaultIsolationScope = _mod13065.getDefaultIsolationScope;
export const setAsyncContextStrategy = _mod13058.setAsyncContextStrategy;
export const getMainCarrier = _mod13057.getMainCarrier;
export const closeSession = _mod13062.closeSession;
export const makeSession = _mod13062.makeSession;
export const updateSession = _mod13062.updateSession;
export const SessionFlusher = SessionFlusher.SessionFlusher;
export const Scope = ScopeClass.Scope;
export const notifyEventProcessors = notifyEventProcessors.notifyEventProcessors;
export const getEnvelopeEndpointWithUrlEncodedAuth = _mod13093.getEnvelopeEndpointWithUrlEncodedAuth;
export const getReportDialogEndpoint = _mod13093.getReportDialogEndpoint;
export const BaseClient = _mod13094.BaseClient;
export const ServerRuntimeClient = _mod13098.ServerRuntimeClient;
export const initAndBind = _mod13101.initAndBind;
export const setCurrentClient = _mod13101.setCurrentClient;
export const createTransport = _mod13102.createTransport;
export const makeOfflineTransport = _mod13105.makeOfflineTransport;
export const makeMultiplexedTransport = _mod13106.makeMultiplexedTransport;
export const addIntegration = _mod13095.addIntegration;
export const defineIntegration = _mod13095.defineIntegration;
export const getIntegrationsToSetup = _mod13095.getIntegrationsToSetup;
export const applyScopeDataToEvent = applyScopeDataToEvent.applyScopeDataToEvent;
export const mergeScopeData = applyScopeDataToEvent.mergeScopeData;
export const prepareEvent = _mod13088.prepareEvent;
export const createCheckInEnvelope = _mod13100.createCheckInEnvelope;
export const hasTracingEnabled = _mod13071.hasTracingEnabled;
export const isSentryRequestUrl = _mod13107.isSentryRequestUrl;
export const handleCallbackErrors = _mod13074.handleCallbackErrors;
export const parameterize = _mod13108.parameterize;
export const addChildSpanToSpan = spanTimeInputToSeconds.addChildSpanToSpan;
export const getActiveSpan = spanTimeInputToSeconds.getActiveSpan;
export const getRootSpan = spanTimeInputToSeconds.getRootSpan;
export const getSpanDescendants = spanTimeInputToSeconds.getSpanDescendants;
export const getStatusMessage = spanTimeInputToSeconds.getStatusMessage;
export const spanIsSampled = spanTimeInputToSeconds.spanIsSampled;
export const spanTimeInputToSeconds = spanTimeInputToSeconds.spanTimeInputToSeconds;
export const spanToJSON = spanTimeInputToSeconds.spanToJSON;
export const spanToTraceContext = spanTimeInputToSeconds.spanToTraceContext;
export const spanToTraceHeader = spanTimeInputToSeconds.spanToTraceHeader;
export const updateSpanName = spanTimeInputToSeconds.updateSpanName;
export const parseSampleRate = _mod13079.parseSampleRate;
export const applySdkMetadata = _mod13109.applySdkMetadata;
export const getTraceData = _mod13110.getTraceData;
export const getTraceMetaTags = _mod13111.getTraceMetaTags;
export const DEFAULT_ENVIRONMENT = _mod13076.DEFAULT_ENVIRONMENT;
export const addBreadcrumb = _mod13112.addBreadcrumb;
export const functionToStringIntegration = _mod13113.functionToStringIntegration;
export const inboundFiltersIntegration = _getEventFilterUrl.inboundFiltersIntegration;
export const linkedErrorsIntegration = _mod13115.linkedErrorsIntegration;
export const moduleMetadataIntegration = _mod13117.moduleMetadataIntegration;
export const requestDataIntegration = _mod13119.requestDataIntegration;
export const captureConsoleIntegration = _mod13124.captureConsoleIntegration;
export const debugIntegration = debugIntegration.debugIntegration;
export const dedupeIntegration = _mod13128.dedupeIntegration;
export const extraErrorDataIntegration = extraErrorDataIntegration.extraErrorDataIntegration;
export const rewriteFramesIntegration = _mod13130.rewriteFramesIntegration;
export const sessionTimingIntegration = sessionTimingIntegration.sessionTimingIntegration;
export const zodErrorsIntegration = _mod13133.zodErrorsIntegration;
export const thirdPartyErrorFilterIntegration = _mod13134.thirdPartyErrorFilterIntegration;
export const metrics = _mod13135.metrics;
export const profiler = _mod13137.profiler;
export const metricsDefault = metricsDefault.metricsDefault;
export const BrowserMetricsAggregator = BrowserMetricsAggregator.BrowserMetricsAggregator;
export const getMetricSummaryJsonForSpan = _mod13055.getMetricSummaryJsonForSpan;
export const addTracingHeadersToFetchRequest = _mod13144.addTracingHeadersToFetchRequest;
export const instrumentFetchRequest = _mod13144.instrumentFetchRequest;
export const trpcMiddleware = _mod13145.trpcMiddleware;
export const captureFeedback = _mod13146.captureFeedback;
export const getCurrentHub = _mod13147.getCurrentHub;
export const getCurrentHubShim = _mod13147.getCurrentHubShim;
export const applyAggregateErrorsToEvent = _mod13116.applyAggregateErrorsToEvent;
export const flatten = _mod13148.flatten;
export const getBreadcrumbLogLevelFromHttpStatusCode = _mod13149.getBreadcrumbLogLevelFromHttpStatusCode;
export const getComponentName = _mod13047.getComponentName;
export const getDomElement = _mod13047.getDomElement;
export const getLocationHref = _mod13047.getLocationHref;
export const htmlTreeAsString = _mod13047.htmlTreeAsString;
export const dsnFromString = _mod13086.dsnFromString;
export const dsnToString = _mod13086.dsnToString;
export const makeDsn = _mod13086.makeDsn;
export const SentryError = _mod13096.SentryError;
export const GLOBAL_OBJ = _mod13040.GLOBAL_OBJ;
export const getGlobalSingleton = _mod13040.getGlobalSingleton;
export const addConsoleInstrumentationHandler = _mod13125.addConsoleInstrumentationHandler;
export const addFetchEndInstrumentationHandler = _mod13150.addFetchEndInstrumentationHandler;
export const addFetchInstrumentationHandler = _mod13150.addFetchInstrumentationHandler;
export const addGlobalErrorInstrumentationHandler = _mod13036.addGlobalErrorInstrumentationHandler;
export const addGlobalUnhandledRejectionInstrumentationHandler =
  _mod13043.addGlobalUnhandledRejectionInstrumentationHandler;
export const addHandler = _mod13037.addHandler;
export const maybeInstrument = _mod13037.maybeInstrument;
export const resetInstrumentationHandlers = _mod13037.resetInstrumentationHandlers;
export const triggerHandlers = _mod13037.triggerHandlers;
export const isDOMError = _mod13046.isDOMError;
export const isDOMException = _mod13046.isDOMException;
export const isElement = _mod13046.isElement;
export const isError = _mod13046.isError;
export const isErrorEvent = _mod13046.isErrorEvent;
export const isEvent = _mod13046.isEvent;
export const isInstanceOf = _mod13046.isInstanceOf;
export const isParameterizedString = _mod13046.isParameterizedString;
export const isPlainObject = _mod13046.isPlainObject;
export const isPrimitive = _mod13046.isPrimitive;
export const isRegExp = _mod13046.isRegExp;
export const isString = _mod13046.isString;
export const isSyntheticEvent = _mod13046.isSyntheticEvent;
export const isThenable = _mod13046.isThenable;
export const isVueViewModel = _mod13046.isVueViewModel;
export const isBrowser = _mod13152.isBrowser;
export const CONSOLE_LEVELS = _mod13039.CONSOLE_LEVELS;
export const consoleSandbox = _mod13039.consoleSandbox;
export const logger = _mod13039.logger;
export const originalConsoleMethods = _mod13039.originalConsoleMethods;
export const memoBuilder = memoBuilder.memoBuilder;
export const addContextToFrame = _mod13050.addContextToFrame;
export const addExceptionMechanism = _mod13050.addExceptionMechanism;
export const addExceptionTypeValue = _mod13050.addExceptionTypeValue;
export const arrayify = _mod13050.arrayify;
export const checkOrSetAlreadyCaught = _mod13050.checkOrSetAlreadyCaught;
export const getEventDescription = _mod13050.getEventDescription;
export const parseSemver = _mod13050.parseSemver;
export const uuid4 = _mod13050.uuid4;
export const dynamicRequire = _mod13153.dynamicRequire;
export const isNodeEnv = _mod13153.isNodeEnv;
export const loadModule = _mod13153.loadModule;
export const normalize = _mod13084.normalize;
export const normalizeToSize = _mod13084.normalizeToSize;
export const normalizeUrlToBase = _mod13084.normalizeUrlToBase;
export const addNonEnumerableProperty = _mod13045.addNonEnumerableProperty;
export const convertToPlainObject = _mod13045.convertToPlainObject;
export const dropUndefinedKeys = _mod13045.dropUndefinedKeys;
export const extractExceptionKeysForMessage = _mod13045.extractExceptionKeysForMessage;
export const fill = _mod13045.fill;
export const getOriginalFunction = _mod13045.getOriginalFunction;
export const markFunctionWrapped = _mod13045.markFunctionWrapped;
export const objectify = _mod13045.objectify;
export const urlEncode = _mod13045.urlEncode;
export const basename = _mod13131.basename;
export const dirname = _mod13131.dirname;
export const isAbsolute = _mod13131.isAbsolute;
export const join = _mod13131.join;
export const normalizePath = _mod13131.normalizePath;
export const relative = _mod13131.relative;
export const resolve = _mod13131.resolve;
export const makePromiseBuffer = _mod13103.makePromiseBuffer;
export const DEFAULT_USER_INCLUDES = extractRequestData.DEFAULT_USER_INCLUDES;
export const addNormalizedRequestDataToEvent = extractRequestData.addNormalizedRequestDataToEvent;
export const addRequestDataToEvent = extractRequestData.addRequestDataToEvent;
export const extractPathForTransaction = extractRequestData.extractPathForTransaction;
export const extractQueryParamsFromUrl = extractRequestData.extractQueryParamsFromUrl;
export const extractRequestData = extractRequestData.extractRequestData;
export const headersToDict = extractRequestData.headersToDict;
export const httpRequestToRequestData = extractRequestData.httpRequestToRequestData;
export const winterCGHeadersToDict = extractRequestData.winterCGHeadersToDict;
export const winterCGRequestToRequestData = extractRequestData.winterCGRequestToRequestData;
export const severityLevelFromString = _mod13126.severityLevelFromString;
export const validSeverityLevels = _mod13126.validSeverityLevels;
export const UNKNOWN_FUNCTION = stackParserFromStackParserOptions.UNKNOWN_FUNCTION;
export const createStackParser = stackParserFromStackParserOptions.createStackParser;
export const getFramesFromEvent = stackParserFromStackParserOptions.getFramesFromEvent;
export const getFunctionName = stackParserFromStackParserOptions.getFunctionName;
export const stackParserFromStackParserOptions = stackParserFromStackParserOptions.stackParserFromStackParserOptions;
export const stripSentryFramesAndReverse = stackParserFromStackParserOptions.stripSentryFramesAndReverse;
export const filenameIsInApp = _mod13155.filenameIsInApp;
export const node = _mod13155.node;
export const nodeStackLineParser = _mod13155.nodeStackLineParser;
export const isMatchingPattern = _mod13048.isMatchingPattern;
export const safeJoin = _mod13048.safeJoin;
export const snipLine = _mod13048.snipLine;
export const stringMatchesSomePattern = _mod13048.stringMatchesSomePattern;
export const truncate = _mod13048.truncate;
export const isNativeFunction = supportsFetch.isNativeFunction;
export const supportsDOMError = supportsFetch.supportsDOMError;
export const supportsDOMException = supportsFetch.supportsDOMException;
export const supportsErrorEvent = supportsFetch.supportsErrorEvent;
export const supportsFetch = supportsFetch.supportsFetch;
export const supportsNativeFetch = supportsFetch.supportsNativeFetch;
export const supportsReferrerPolicy = supportsFetch.supportsReferrerPolicy;
export const supportsReportingObserver = supportsFetch.supportsReportingObserver;
export const SyncPromise = _mod13063.SyncPromise;
export const rejectedSyncPromise = _mod13063.rejectedSyncPromise;
export const resolvedSyncPromise = _mod13063.resolvedSyncPromise;
export const _browserPerformanceTimeOriginMode = require("13053__.js")._browserPerformanceTimeOriginMode;
export const browserPerformanceTimeOrigin = require("13053__.js").browserPerformanceTimeOrigin;
export const dateTimestampInSeconds = require("13053__.js").dateTimestampInSeconds;
export const timestampInSeconds = require("13053__.js").timestampInSeconds;
export const TRACEPARENT_REGEXP = _mod13051.TRACEPARENT_REGEXP;
export const extractTraceparentData = _mod13051.extractTraceparentData;
export const generateSentryTraceHeader = _mod13051.generateSentryTraceHeader;
export const propagationContextFromHeaders = _mod13051.propagationContextFromHeaders;
export const getSDKSource = _mod13154.getSDKSource;
export const isBrowserBundle = _mod13154.isBrowserBundle;
export const addItemToEnvelope = _mod13083.addItemToEnvelope;
export const createAttachmentEnvelopeItem = _mod13083.createAttachmentEnvelopeItem;
export const createEnvelope = _mod13083.createEnvelope;
export const createEventEnvelopeHeaders = _mod13083.createEventEnvelopeHeaders;
export const createSpanEnvelopeItem = _mod13083.createSpanEnvelopeItem;
export const envelopeContainsItemType = _mod13083.envelopeContainsItemType;
export const envelopeItemTypeToDataCategory = _mod13083.envelopeItemTypeToDataCategory;
export const forEachEnvelopeItem = _mod13083.forEachEnvelopeItem;
export const getSdkMetadataForEnvelopeHeader = _mod13083.getSdkMetadataForEnvelopeHeader;
export const parseEnvelope = _mod13083.parseEnvelope;
export const serializeEnvelope = _mod13083.serializeEnvelope;
export const createClientReportEnvelope = _mod13097.createClientReportEnvelope;
export const DEFAULT_RETRY_AFTER = _mod13104.DEFAULT_RETRY_AFTER;
export const disabledUntil = _mod13104.disabledUntil;
export const isRateLimited = _mod13104.isRateLimited;
export const parseRetryAfterHeader = _mod13104.parseRetryAfterHeader;
export const updateRateLimits = _mod13104.updateRateLimits;
export const BAGGAGE_HEADER_NAME = BAGGAGE_HEADER_NAME.BAGGAGE_HEADER_NAME;
export const MAX_BAGGAGE_STRING_LENGTH = BAGGAGE_HEADER_NAME.MAX_BAGGAGE_STRING_LENGTH;
export const SENTRY_BAGGAGE_KEY_PREFIX = BAGGAGE_HEADER_NAME.SENTRY_BAGGAGE_KEY_PREFIX;
export const SENTRY_BAGGAGE_KEY_PREFIX_REGEX = BAGGAGE_HEADER_NAME.SENTRY_BAGGAGE_KEY_PREFIX_REGEX;
export const baggageHeaderToDynamicSamplingContext = BAGGAGE_HEADER_NAME.baggageHeaderToDynamicSamplingContext;
export const dynamicSamplingContextToSentryBaggageHeader =
  BAGGAGE_HEADER_NAME.dynamicSamplingContextToSentryBaggageHeader;
export const parseBaggageHeader = BAGGAGE_HEADER_NAME.parseBaggageHeader;
export const getNumberOfUrlSegments = stripUrlQueryAndFragment.getNumberOfUrlSegments;
export const getSanitizedUrlString = stripUrlQueryAndFragment.getSanitizedUrlString;
export const parseUrl = stripUrlQueryAndFragment.parseUrl;
export const stripUrlQueryAndFragment = stripUrlQueryAndFragment.stripUrlQueryAndFragment;
export const makeFifoCache = _mod13156.makeFifoCache;
export const eventFromMessage = eventFromMessage.eventFromMessage;
export const eventFromUnknownInput = eventFromMessage.eventFromUnknownInput;
export const exceptionFromError = eventFromMessage.exceptionFromError;
export const parseStackFrames = eventFromMessage.parseStackFrames;
export const callFrameToStackFrame = _mod13157.callFrameToStackFrame;
export const watchdogTimer = _mod13157.watchdogTimer;
export const LRUMap = _mod13158.LRUMap;
export const generatePropagationContext = generatePropagationContext.generatePropagationContext;
export const generateSpanId = generatePropagationContext.generateSpanId;
export const generateTraceId = generatePropagationContext.generateTraceId;
export const vercelWaitUntil = _mod13159.vercelWaitUntil;
export const SDK_VERSION = _mod13041.SDK_VERSION;
export const getDebugImagesForResources = _mod13091.getDebugImagesForResources;
export const getFilenameToDebugIdMap = _mod13091.getFilenameToDebugIdMap;
export const escapeStringForRegex = _mod13160.escapeStringForRegex;
export const supportsHistory = supportsHistory.supportsHistory;
export const _asyncNullishCoalesce = _asyncNullishCoalesce2._asyncNullishCoalesce;
export const _asyncOptionalChain = _asyncOptionalChain2._asyncOptionalChain;
export const _asyncOptionalChainDelete = _asyncOptionalChainDelete2._asyncOptionalChainDelete;
export const _nullishCoalesce = _nullishCoalesce._nullishCoalesce;
export const _optionalChain = _optionalChain._optionalChain;
export const _optionalChainDelete = _optionalChainDelete._optionalChainDelete;
