// _runtime/metro/13045__.js
import errorCallback from "../13046_errorCallback.js";
import _mod13047 from "13047__.js";
import _mod13048 from "13048__.js";
import _mod13050 from "13050__.js";
import _mod13051 from "13051__.js";
import _mod13052 from "13052__.js";
import stackParserFromStackParserOptions from "../13053_stackParserFromStackParserOptions.js";
import _mod13054 from "13054__.js";
import spanTimeInputToSeconds from "../13055_spanTimeInputToSeconds.js";
import _mod13056 from "13056__.js";
import _mod13057 from "13057__.js";
import _mod13058 from "13058__.js";
import _mod13059 from "13059__.js";
import generatePropagationContext from "../13060_generatePropagationContext.js";
import _mod13061 from "13061__.js";
import _mod13062 from "13062__.js";
import BAGGAGE_HEADER_NAME from "../13063_BAGGAGE_HEADER_NAME.js";
import _mod13065 from "13065__.js";
import _mod13066 from "13066__.js";
import _mod13067 from "13067__.js";
import _mod13068 from "13068__.js";
import _mod13069 from "13069__.js";
import ScopeClass from "../13071_ScopeClass.js";
import _mod13073 from "13073__.js";
import _mod13074 from "13074__.js";
import _mod13076 from "13076__.js";
import _mod13077 from "13077__.js";
import _mod13079 from "13079__.js";
import _mod13080 from "13080__.js";
import _mod13081 from "13081__.js";
import _mod13082 from "13082__.js";
import _mod13083 from "13083__.js";
import _mod13084 from "13084__.js";
import _mod13085 from "13085__.js";
import _mod13086 from "13086__.js";
import _mod13087 from "13087__.js";
import _mod13088 from "13088__.js";
import _mod13089 from "13089__.js";
import _mod13090 from "13090__.js";
import _mod13091 from "13091__.js";
import _mod13092 from "13092__.js";
import _mod13093 from "13093__.js";
import _mod13094 from "13094__.js";
import _mod13095 from "13095__.js";
import memoBuilder from "../13096_memoBuilder.js";
import _mod13097 from "13097__.js";
import _flush from "../13098__flush.js";
import _mod13099 from "13099__.js";
import applyScopeDataToEvent from "../13100_applyScopeDataToEvent.js";
import notifyEventProcessors from "../13101_notifyEventProcessors.js";
import _mod13102 from "13102__.js";
import SessionFlusher from "../13103_SessionFlusher.js";
import _mod13104 from "13104__.js";
import _mod13105 from "13105__.js";
import _mod13106 from "13106__.js";
import _mod13107 from "13107__.js";
import _mod13108 from "13108__.js";
import _mod13109 from "13109__.js";
import eventFromMessage from "../13110_eventFromMessage.js";
import _mod13111 from "13111__.js";
import _mod13112 from "13112__.js";
import _mod13113 from "13113__.js";
import _mod13114 from "13114__.js";
import _mod13115 from "13115__.js";
import _mod13116 from "13116__.js";
import _mod13117 from "13117__.js";
import _mod13118 from "13118__.js";
import _mod13119 from "13119__.js";
import _mod13120 from "13120__.js";
import _mod13121 from "13121__.js";
import _mod13122 from "13122__.js";
import _mod13123 from "13123__.js";
import _mod13124 from "13124__.js";
import _getEventFilterUrl from "../13125__getEventFilterUrl.js";
import _mod13126 from "13126__.js";
import _mod13127 from "13127__.js";
import _mod13128 from "13128__.js";
import _mod13130 from "13130__.js";
import extractRequestData from "../13131_extractRequestData.js";
import stripUrlQueryAndFragment from "../13132_stripUrlQueryAndFragment.js";
import _mod13135 from "13135__.js";
import _mod13136 from "13136__.js";
import _mod13137 from "13137__.js";
import debugIntegration from "../13138_debugIntegration.js";
import _mod13139 from "13139__.js";
import extraErrorDataIntegration from "../13140_extraErrorDataIntegration.js";
import _mod13141 from "13141__.js";
import _mod13142 from "13142__.js";
import sessionTimingIntegration from "../13143_sessionTimingIntegration.js";
import _mod13144 from "13144__.js";
import _mod13145 from "13145__.js";
import _mod13146 from "13146__.js";
import _mod13148 from "13148__.js";
import metricsDefault from "../13149_metricsDefault.js";
import BrowserMetricsAggregator from "../13154_BrowserMetricsAggregator.js";
import _mod13155 from "13155__.js";
import _mod13156 from "13156__.js";
import _mod13157 from "13157__.js";
import _mod13158 from "13158__.js";
import _mod13159 from "13159__.js";
import _mod13160 from "13160__.js";
import _mod13161 from "13161__.js";
import supportsFetch from "../13162_supportsFetch.js";
import _mod13163 from "13163__.js";
import _mod13164 from "13164__.js";
import _mod13165 from "13165__.js";
import _mod13166 from "13166__.js";
import _mod13167 from "13167__.js";
import _mod13168 from "13168__.js";
import _mod13169 from "13169__.js";
import _mod13170 from "13170__.js";
import _mod13171 from "13171__.js";
import supportsHistory from "../13172_supportsHistory.js";
import _asyncNullishCoalesce2 from "../13173__asyncNullishCoalesce2.js";
import _nullishCoalesce from "../13174__nullishCoalesce.js";
import _asyncOptionalChain2 from "../13175__asyncOptionalChain2.js";
import _asyncOptionalChainDelete2 from "../13176__asyncOptionalChainDelete2.js";
import _optionalChain from "../13177__optionalChain.js";
import _optionalChainDelete from "../13178__optionalChainDelete.js";

const require = globalThis.__r;

export const registerSpanErrorInstrumentation = errorCallback.registerSpanErrorInstrumentation;
export const getCapturedScopesOnSpan = _mod13079.getCapturedScopesOnSpan;
export const setCapturedScopesOnSpan = _mod13079.setCapturedScopesOnSpan;
export const addTracingExtensions = _mod13080.addTracingExtensions;
export const TRACING_DEFAULTS = _mod13081.TRACING_DEFAULTS;
export const startIdleSpan = _mod13081.startIdleSpan;
export const SentrySpan = _mod13091.SentrySpan;
export const SentryNonRecordingSpan = _mod13083.SentryNonRecordingSpan;
export const SPAN_STATUS_ERROR = _mod13067.SPAN_STATUS_ERROR;
export const SPAN_STATUS_OK = _mod13067.SPAN_STATUS_OK;
export const SPAN_STATUS_UNSET = _mod13067.SPAN_STATUS_UNSET;
export const getSpanStatusFromHttpCode = _mod13067.getSpanStatusFromHttpCode;
export const setHttpStatus = _mod13067.setHttpStatus;
export const continueTrace = _mod13084.continueTrace;
export const startInactiveSpan = _mod13084.startInactiveSpan;
export const startNewTrace = _mod13084.startNewTrace;
export const startSpan = _mod13084.startSpan;
export const startSpanManual = _mod13084.startSpanManual;
export const suppressTracing = _mod13084.suppressTracing;
export const withActiveSpan = _mod13084.withActiveSpan;
export const getDynamicSamplingContextFromClient = _mod13086.getDynamicSamplingContextFromClient;
export const getDynamicSamplingContextFromScope = _mod13086.getDynamicSamplingContextFromScope;
export const getDynamicSamplingContextFromSpan = _mod13086.getDynamicSamplingContextFromSpan;
export const spanToBaggageHeader = _mod13086.spanToBaggageHeader;
export const setMeasurement = _mod13092.setMeasurement;
export const timedEventsToMeasurements = _mod13092.timedEventsToMeasurements;
export const sampleSpan = _mod13089.sampleSpan;
export const logSpanEnd = _mod13088.logSpanEnd;
export const logSpanStart = _mod13088.logSpanStart;
export const SEMANTIC_ATTRIBUTE_CACHE_HIT = _mod13065.SEMANTIC_ATTRIBUTE_CACHE_HIT;
export const SEMANTIC_ATTRIBUTE_CACHE_ITEM_SIZE = _mod13065.SEMANTIC_ATTRIBUTE_CACHE_ITEM_SIZE;
export const SEMANTIC_ATTRIBUTE_CACHE_KEY = _mod13065.SEMANTIC_ATTRIBUTE_CACHE_KEY;
export const SEMANTIC_ATTRIBUTE_EXCLUSIVE_TIME = _mod13065.SEMANTIC_ATTRIBUTE_EXCLUSIVE_TIME;
export const SEMANTIC_ATTRIBUTE_HTTP_REQUEST_METHOD = _mod13065.SEMANTIC_ATTRIBUTE_HTTP_REQUEST_METHOD;
export const SEMANTIC_ATTRIBUTE_PROFILE_ID = _mod13065.SEMANTIC_ATTRIBUTE_PROFILE_ID;
export const SEMANTIC_ATTRIBUTE_SENTRY_CUSTOM_SPAN_NAME = _mod13065.SEMANTIC_ATTRIBUTE_SENTRY_CUSTOM_SPAN_NAME;
export const SEMANTIC_ATTRIBUTE_SENTRY_IDLE_SPAN_FINISH_REASON =
  _mod13065.SEMANTIC_ATTRIBUTE_SENTRY_IDLE_SPAN_FINISH_REASON;
export const SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_UNIT = _mod13065.SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_UNIT;
export const SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_VALUE = _mod13065.SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_VALUE;
export const SEMANTIC_ATTRIBUTE_SENTRY_OP = _mod13065.SEMANTIC_ATTRIBUTE_SENTRY_OP;
export const SEMANTIC_ATTRIBUTE_SENTRY_ORIGIN = _mod13065.SEMANTIC_ATTRIBUTE_SENTRY_ORIGIN;
export const SEMANTIC_ATTRIBUTE_SENTRY_SAMPLE_RATE = _mod13065.SEMANTIC_ATTRIBUTE_SENTRY_SAMPLE_RATE;
export const SEMANTIC_ATTRIBUTE_SENTRY_SOURCE = _mod13065.SEMANTIC_ATTRIBUTE_SENTRY_SOURCE;
export const SEMANTIC_ATTRIBUTE_URL_FULL = _mod13065.SEMANTIC_ATTRIBUTE_URL_FULL;
export const createEventEnvelope = _mod13093.createEventEnvelope;
export const createSessionEnvelope = _mod13093.createSessionEnvelope;
export const createSpanEnvelope = _mod13093.createSpanEnvelope;
export const addEventProcessor = _flush.addEventProcessor;
export const captureCheckIn = _flush.captureCheckIn;
export const captureEvent = _flush.captureEvent;
export const captureException = _flush.captureException;
export const captureMessage = _flush.captureMessage;
export const captureSession = _flush.captureSession;
export const close = _flush.close;
export const endSession = _flush.endSession;
export const flush = _flush.flush;
export const isEnabled = _flush.isEnabled;
export const isInitialized = _flush.isInitialized;
export const lastEventId = _flush.lastEventId;
export const setContext = _flush.setContext;
export const setExtra = _flush.setExtra;
export const setExtras = _flush.setExtras;
export const setTag = _flush.setTag;
export const setTags = _flush.setTags;
export const setUser = _flush.setUser;
export const startSession = _flush.startSession;
export const withMonitor = _flush.withMonitor;
export const getClient = _mod13077.getClient;
export const getCurrentScope = _mod13077.getCurrentScope;
export const getGlobalScope = _mod13077.getGlobalScope;
export const getIsolationScope = _mod13077.getIsolationScope;
export const getTraceContextFromScope = _mod13077.getTraceContextFromScope;
export const withIsolationScope = _mod13077.withIsolationScope;
export const withScope = _mod13077.withScope;
export const getDefaultCurrentScope = _mod13076.getDefaultCurrentScope;
export const getDefaultIsolationScope = _mod13076.getDefaultIsolationScope;
export const setAsyncContextStrategy = _mod13069.setAsyncContextStrategy;
export const getMainCarrier = _mod13068.getMainCarrier;
export const closeSession = _mod13073.closeSession;
export const makeSession = _mod13073.makeSession;
export const updateSession = _mod13073.updateSession;
export const SessionFlusher = SessionFlusher.SessionFlusher;
export const Scope = ScopeClass.Scope;
export const notifyEventProcessors = notifyEventProcessors.notifyEventProcessors;
export const getEnvelopeEndpointWithUrlEncodedAuth = _mod13104.getEnvelopeEndpointWithUrlEncodedAuth;
export const getReportDialogEndpoint = _mod13104.getReportDialogEndpoint;
export const BaseClient = _mod13105.BaseClient;
export const ServerRuntimeClient = _mod13109.ServerRuntimeClient;
export const initAndBind = _mod13112.initAndBind;
export const setCurrentClient = _mod13112.setCurrentClient;
export const createTransport = _mod13113.createTransport;
export const makeOfflineTransport = _mod13116.makeOfflineTransport;
export const makeMultiplexedTransport = _mod13117.makeMultiplexedTransport;
export const addIntegration = _mod13106.addIntegration;
export const defineIntegration = _mod13106.defineIntegration;
export const getIntegrationsToSetup = _mod13106.getIntegrationsToSetup;
export const applyScopeDataToEvent = applyScopeDataToEvent.applyScopeDataToEvent;
export const mergeScopeData = applyScopeDataToEvent.mergeScopeData;
export const prepareEvent = _mod13099.prepareEvent;
export const createCheckInEnvelope = _mod13111.createCheckInEnvelope;
export const hasTracingEnabled = _mod13082.hasTracingEnabled;
export const isSentryRequestUrl = _mod13118.isSentryRequestUrl;
export const handleCallbackErrors = _mod13085.handleCallbackErrors;
export const parameterize = _mod13119.parameterize;
export const addChildSpanToSpan = spanTimeInputToSeconds.addChildSpanToSpan;
export const getActiveSpan = spanTimeInputToSeconds.getActiveSpan;
export const getRootSpan = spanTimeInputToSeconds.getRootSpan;
export const getSpanDescendants = spanTimeInputToSeconds.getSpanDescendants;
export const getStatusMessage = spanTimeInputToSeconds.getStatusMessage;
export const spanIsSampled = spanTimeInputToSeconds.spanIsSampled;
export const spanTimeInputToSeconds = spanTimeInputToSeconds.spanTimeInputToSeconds;
export const spanToJSON = spanTimeInputToSeconds.spanToJSON;
export const spanToTraceContext = spanTimeInputToSeconds.spanToTraceContext;
export const spanToTraceHeader = spanTimeInputToSeconds.spanToTraceHeader;
export const updateSpanName = spanTimeInputToSeconds.updateSpanName;
export const parseSampleRate = _mod13090.parseSampleRate;
export const applySdkMetadata = _mod13120.applySdkMetadata;
export const getTraceData = _mod13121.getTraceData;
export const getTraceMetaTags = _mod13122.getTraceMetaTags;
export const DEFAULT_ENVIRONMENT = _mod13087.DEFAULT_ENVIRONMENT;
export const addBreadcrumb = _mod13123.addBreadcrumb;
export const functionToStringIntegration = _mod13124.functionToStringIntegration;
export const inboundFiltersIntegration = _getEventFilterUrl.inboundFiltersIntegration;
export const linkedErrorsIntegration = _mod13126.linkedErrorsIntegration;
export const moduleMetadataIntegration = _mod13128.moduleMetadataIntegration;
export const requestDataIntegration = _mod13130.requestDataIntegration;
export const captureConsoleIntegration = _mod13135.captureConsoleIntegration;
export const debugIntegration = debugIntegration.debugIntegration;
export const dedupeIntegration = _mod13139.dedupeIntegration;
export const extraErrorDataIntegration = extraErrorDataIntegration.extraErrorDataIntegration;
export const rewriteFramesIntegration = _mod13141.rewriteFramesIntegration;
export const sessionTimingIntegration = sessionTimingIntegration.sessionTimingIntegration;
export const zodErrorsIntegration = _mod13144.zodErrorsIntegration;
export const thirdPartyErrorFilterIntegration = _mod13145.thirdPartyErrorFilterIntegration;
export const metrics = _mod13146.metrics;
export const profiler = _mod13148.profiler;
export const metricsDefault = metricsDefault.metricsDefault;
export const BrowserMetricsAggregator = BrowserMetricsAggregator.BrowserMetricsAggregator;
export const getMetricSummaryJsonForSpan = _mod13066.getMetricSummaryJsonForSpan;
export const addTracingHeadersToFetchRequest = _mod13155.addTracingHeadersToFetchRequest;
export const instrumentFetchRequest = _mod13155.instrumentFetchRequest;
export const trpcMiddleware = _mod13156.trpcMiddleware;
export const captureFeedback = _mod13157.captureFeedback;
export const getCurrentHub = _mod13158.getCurrentHub;
export const getCurrentHubShim = _mod13158.getCurrentHubShim;
export const applyAggregateErrorsToEvent = _mod13127.applyAggregateErrorsToEvent;
export const flatten = _mod13159.flatten;
export const getBreadcrumbLogLevelFromHttpStatusCode = _mod13160.getBreadcrumbLogLevelFromHttpStatusCode;
export const getComponentName = _mod13058.getComponentName;
export const getDomElement = _mod13058.getDomElement;
export const getLocationHref = _mod13058.getLocationHref;
export const htmlTreeAsString = _mod13058.htmlTreeAsString;
export const dsnFromString = _mod13097.dsnFromString;
export const dsnToString = _mod13097.dsnToString;
export const makeDsn = _mod13097.makeDsn;
export const SentryError = _mod13107.SentryError;
export const GLOBAL_OBJ = _mod13051.GLOBAL_OBJ;
export const getGlobalSingleton = _mod13051.getGlobalSingleton;
export const addConsoleInstrumentationHandler = _mod13136.addConsoleInstrumentationHandler;
export const addFetchEndInstrumentationHandler = _mod13161.addFetchEndInstrumentationHandler;
export const addFetchInstrumentationHandler = _mod13161.addFetchInstrumentationHandler;
export const addGlobalErrorInstrumentationHandler = _mod13047.addGlobalErrorInstrumentationHandler;
export const addGlobalUnhandledRejectionInstrumentationHandler =
  _mod13054.addGlobalUnhandledRejectionInstrumentationHandler;
export const addHandler = _mod13048.addHandler;
export const maybeInstrument = _mod13048.maybeInstrument;
export const resetInstrumentationHandlers = _mod13048.resetInstrumentationHandlers;
export const triggerHandlers = _mod13048.triggerHandlers;
export const isDOMError = _mod13057.isDOMError;
export const isDOMException = _mod13057.isDOMException;
export const isElement = _mod13057.isElement;
export const isError = _mod13057.isError;
export const isErrorEvent = _mod13057.isErrorEvent;
export const isEvent = _mod13057.isEvent;
export const isInstanceOf = _mod13057.isInstanceOf;
export const isParameterizedString = _mod13057.isParameterizedString;
export const isPlainObject = _mod13057.isPlainObject;
export const isPrimitive = _mod13057.isPrimitive;
export const isRegExp = _mod13057.isRegExp;
export const isString = _mod13057.isString;
export const isSyntheticEvent = _mod13057.isSyntheticEvent;
export const isThenable = _mod13057.isThenable;
export const isVueViewModel = _mod13057.isVueViewModel;
export const isBrowser = _mod13163.isBrowser;
export const CONSOLE_LEVELS = _mod13050.CONSOLE_LEVELS;
export const consoleSandbox = _mod13050.consoleSandbox;
export const logger = _mod13050.logger;
export const originalConsoleMethods = _mod13050.originalConsoleMethods;
export const memoBuilder = memoBuilder.memoBuilder;
export const addContextToFrame = _mod13061.addContextToFrame;
export const addExceptionMechanism = _mod13061.addExceptionMechanism;
export const addExceptionTypeValue = _mod13061.addExceptionTypeValue;
export const arrayify = _mod13061.arrayify;
export const checkOrSetAlreadyCaught = _mod13061.checkOrSetAlreadyCaught;
export const getEventDescription = _mod13061.getEventDescription;
export const parseSemver = _mod13061.parseSemver;
export const uuid4 = _mod13061.uuid4;
export const dynamicRequire = _mod13164.dynamicRequire;
export const isNodeEnv = _mod13164.isNodeEnv;
export const loadModule = _mod13164.loadModule;
export const normalize = _mod13095.normalize;
export const normalizeToSize = _mod13095.normalizeToSize;
export const normalizeUrlToBase = _mod13095.normalizeUrlToBase;
export const addNonEnumerableProperty = _mod13056.addNonEnumerableProperty;
export const convertToPlainObject = _mod13056.convertToPlainObject;
export const dropUndefinedKeys = _mod13056.dropUndefinedKeys;
export const extractExceptionKeysForMessage = _mod13056.extractExceptionKeysForMessage;
export const fill = _mod13056.fill;
export const getOriginalFunction = _mod13056.getOriginalFunction;
export const markFunctionWrapped = _mod13056.markFunctionWrapped;
export const objectify = _mod13056.objectify;
export const urlEncode = _mod13056.urlEncode;
export const basename = _mod13142.basename;
export const dirname = _mod13142.dirname;
export const isAbsolute = _mod13142.isAbsolute;
export const join = _mod13142.join;
export const normalizePath = _mod13142.normalizePath;
export const relative = _mod13142.relative;
export const resolve = _mod13142.resolve;
export const makePromiseBuffer = _mod13114.makePromiseBuffer;
export const DEFAULT_USER_INCLUDES = extractRequestData.DEFAULT_USER_INCLUDES;
export const addNormalizedRequestDataToEvent = extractRequestData.addNormalizedRequestDataToEvent;
export const addRequestDataToEvent = extractRequestData.addRequestDataToEvent;
export const extractPathForTransaction = extractRequestData.extractPathForTransaction;
export const extractQueryParamsFromUrl = extractRequestData.extractQueryParamsFromUrl;
export const extractRequestData = extractRequestData.extractRequestData;
export const headersToDict = extractRequestData.headersToDict;
export const httpRequestToRequestData = extractRequestData.httpRequestToRequestData;
export const winterCGHeadersToDict = extractRequestData.winterCGHeadersToDict;
export const winterCGRequestToRequestData = extractRequestData.winterCGRequestToRequestData;
export const severityLevelFromString = _mod13137.severityLevelFromString;
export const validSeverityLevels = _mod13137.validSeverityLevels;
export const UNKNOWN_FUNCTION = stackParserFromStackParserOptions.UNKNOWN_FUNCTION;
export const createStackParser = stackParserFromStackParserOptions.createStackParser;
export const getFramesFromEvent = stackParserFromStackParserOptions.getFramesFromEvent;
export const getFunctionName = stackParserFromStackParserOptions.getFunctionName;
export const stackParserFromStackParserOptions = stackParserFromStackParserOptions.stackParserFromStackParserOptions;
export const stripSentryFramesAndReverse = stackParserFromStackParserOptions.stripSentryFramesAndReverse;
export const filenameIsInApp = _mod13166.filenameIsInApp;
export const node = _mod13166.node;
export const nodeStackLineParser = _mod13166.nodeStackLineParser;
export const isMatchingPattern = _mod13059.isMatchingPattern;
export const safeJoin = _mod13059.safeJoin;
export const snipLine = _mod13059.snipLine;
export const stringMatchesSomePattern = _mod13059.stringMatchesSomePattern;
export const truncate = _mod13059.truncate;
export const isNativeFunction = supportsFetch.isNativeFunction;
export const supportsDOMError = supportsFetch.supportsDOMError;
export const supportsDOMException = supportsFetch.supportsDOMException;
export const supportsErrorEvent = supportsFetch.supportsErrorEvent;
export const supportsFetch = supportsFetch.supportsFetch;
export const supportsNativeFetch = supportsFetch.supportsNativeFetch;
export const supportsReferrerPolicy = supportsFetch.supportsReferrerPolicy;
export const supportsReportingObserver = supportsFetch.supportsReportingObserver;
export const SyncPromise = _mod13074.SyncPromise;
export const rejectedSyncPromise = _mod13074.rejectedSyncPromise;
export const resolvedSyncPromise = _mod13074.resolvedSyncPromise;
export const _browserPerformanceTimeOriginMode = require("13064__.js")._browserPerformanceTimeOriginMode;
export const browserPerformanceTimeOrigin = require("13064__.js").browserPerformanceTimeOrigin;
export const dateTimestampInSeconds = require("13064__.js").dateTimestampInSeconds;
export const timestampInSeconds = require("13064__.js").timestampInSeconds;
export const TRACEPARENT_REGEXP = _mod13062.TRACEPARENT_REGEXP;
export const extractTraceparentData = _mod13062.extractTraceparentData;
export const generateSentryTraceHeader = _mod13062.generateSentryTraceHeader;
export const propagationContextFromHeaders = _mod13062.propagationContextFromHeaders;
export const getSDKSource = _mod13165.getSDKSource;
export const isBrowserBundle = _mod13165.isBrowserBundle;
export const addItemToEnvelope = _mod13094.addItemToEnvelope;
export const createAttachmentEnvelopeItem = _mod13094.createAttachmentEnvelopeItem;
export const createEnvelope = _mod13094.createEnvelope;
export const createEventEnvelopeHeaders = _mod13094.createEventEnvelopeHeaders;
export const createSpanEnvelopeItem = _mod13094.createSpanEnvelopeItem;
export const envelopeContainsItemType = _mod13094.envelopeContainsItemType;
export const envelopeItemTypeToDataCategory = _mod13094.envelopeItemTypeToDataCategory;
export const forEachEnvelopeItem = _mod13094.forEachEnvelopeItem;
export const getSdkMetadataForEnvelopeHeader = _mod13094.getSdkMetadataForEnvelopeHeader;
export const parseEnvelope = _mod13094.parseEnvelope;
export const serializeEnvelope = _mod13094.serializeEnvelope;
export const createClientReportEnvelope = _mod13108.createClientReportEnvelope;
export const DEFAULT_RETRY_AFTER = _mod13115.DEFAULT_RETRY_AFTER;
export const disabledUntil = _mod13115.disabledUntil;
export const isRateLimited = _mod13115.isRateLimited;
export const parseRetryAfterHeader = _mod13115.parseRetryAfterHeader;
export const updateRateLimits = _mod13115.updateRateLimits;
export const BAGGAGE_HEADER_NAME = BAGGAGE_HEADER_NAME.BAGGAGE_HEADER_NAME;
export const MAX_BAGGAGE_STRING_LENGTH = BAGGAGE_HEADER_NAME.MAX_BAGGAGE_STRING_LENGTH;
export const SENTRY_BAGGAGE_KEY_PREFIX = BAGGAGE_HEADER_NAME.SENTRY_BAGGAGE_KEY_PREFIX;
export const SENTRY_BAGGAGE_KEY_PREFIX_REGEX = BAGGAGE_HEADER_NAME.SENTRY_BAGGAGE_KEY_PREFIX_REGEX;
export const baggageHeaderToDynamicSamplingContext = BAGGAGE_HEADER_NAME.baggageHeaderToDynamicSamplingContext;
export const dynamicSamplingContextToSentryBaggageHeader =
  BAGGAGE_HEADER_NAME.dynamicSamplingContextToSentryBaggageHeader;
export const parseBaggageHeader = BAGGAGE_HEADER_NAME.parseBaggageHeader;
export const getNumberOfUrlSegments = stripUrlQueryAndFragment.getNumberOfUrlSegments;
export const getSanitizedUrlString = stripUrlQueryAndFragment.getSanitizedUrlString;
export const parseUrl = stripUrlQueryAndFragment.parseUrl;
export const stripUrlQueryAndFragment = stripUrlQueryAndFragment.stripUrlQueryAndFragment;
export const makeFifoCache = _mod13167.makeFifoCache;
export const eventFromMessage = eventFromMessage.eventFromMessage;
export const eventFromUnknownInput = eventFromMessage.eventFromUnknownInput;
export const exceptionFromError = eventFromMessage.exceptionFromError;
export const parseStackFrames = eventFromMessage.parseStackFrames;
export const callFrameToStackFrame = _mod13168.callFrameToStackFrame;
export const watchdogTimer = _mod13168.watchdogTimer;
export const LRUMap = _mod13169.LRUMap;
export const generatePropagationContext = generatePropagationContext.generatePropagationContext;
export const generateSpanId = generatePropagationContext.generateSpanId;
export const generateTraceId = generatePropagationContext.generateTraceId;
export const vercelWaitUntil = _mod13170.vercelWaitUntil;
export const SDK_VERSION = _mod13052.SDK_VERSION;
export const getDebugImagesForResources = _mod13102.getDebugImagesForResources;
export const getFilenameToDebugIdMap = _mod13102.getFilenameToDebugIdMap;
export const escapeStringForRegex = _mod13171.escapeStringForRegex;
export const supportsHistory = supportsHistory.supportsHistory;
export const _asyncNullishCoalesce = _asyncNullishCoalesce2._asyncNullishCoalesce;
export const _asyncOptionalChain = _asyncOptionalChain2._asyncOptionalChain;
export const _asyncOptionalChainDelete = _asyncOptionalChainDelete2._asyncOptionalChainDelete;
export const _nullishCoalesce = _nullishCoalesce._nullishCoalesce;
export const _optionalChain = _optionalChain._optionalChain;
export const _optionalChainDelete = _optionalChainDelete._optionalChainDelete;
