// _runtime/metro/13131__.js
import errorCallback from "../13132_errorCallback.js";
import _mod13133 from "13133__.js";
import _mod13134 from "13134__.js";
import _mod13136 from "13136__.js";
import _mod13137 from "13137__.js";
import _mod13138 from "13138__.js";
import stackParserFromStackParserOptions from "../13139_stackParserFromStackParserOptions.js";
import _mod13140 from "13140__.js";
import spanTimeInputToSeconds from "../13141_spanTimeInputToSeconds.js";
import _mod13142 from "13142__.js";
import _mod13143 from "13143__.js";
import _mod13144 from "13144__.js";
import _mod13145 from "13145__.js";
import generatePropagationContext from "../13146_generatePropagationContext.js";
import _mod13147 from "13147__.js";
import _mod13148 from "13148__.js";
import BAGGAGE_HEADER_NAME from "../13149_BAGGAGE_HEADER_NAME.js";
import _mod13151 from "13151__.js";
import _mod13152 from "13152__.js";
import _mod13153 from "13153__.js";
import _mod13154 from "13154__.js";
import _mod13155 from "13155__.js";
import ScopeClass from "../13157_ScopeClass.js";
import _mod13159 from "13159__.js";
import _mod13160 from "13160__.js";
import _mod13162 from "13162__.js";
import _mod13163 from "13163__.js";
import _mod13165 from "13165__.js";
import _mod13166 from "13166__.js";
import _mod13167 from "13167__.js";
import _mod13168 from "13168__.js";
import _mod13169 from "13169__.js";
import _mod13170 from "13170__.js";
import _mod13171 from "13171__.js";
import _mod13172 from "13172__.js";
import _mod13173 from "13173__.js";
import _mod13174 from "13174__.js";
import _mod13175 from "13175__.js";
import _mod13176 from "13176__.js";
import _mod13177 from "13177__.js";
import _mod13178 from "13178__.js";
import _mod13179 from "13179__.js";
import _mod13180 from "13180__.js";
import _mod13181 from "13181__.js";
import memoBuilder from "../13182_memoBuilder.js";
import _mod13183 from "13183__.js";
import _flush from "../13184__flush.js";
import _mod13185 from "13185__.js";
import applyScopeDataToEvent from "../13186_applyScopeDataToEvent.js";
import notifyEventProcessors from "../13187_notifyEventProcessors.js";
import _mod13188 from "13188__.js";
import SessionFlusher from "../13189_SessionFlusher.js";
import _mod13190 from "13190__.js";
import _mod13191 from "13191__.js";
import _mod13192 from "13192__.js";
import _mod13193 from "13193__.js";
import _mod13194 from "13194__.js";
import _mod13195 from "13195__.js";
import eventFromMessage from "../13196_eventFromMessage.js";
import _mod13197 from "13197__.js";
import _mod13198 from "13198__.js";
import _mod13199 from "13199__.js";
import _mod13200 from "13200__.js";
import _mod13201 from "13201__.js";
import _mod13202 from "13202__.js";
import _mod13203 from "13203__.js";
import _mod13204 from "13204__.js";
import _mod13205 from "13205__.js";
import _mod13206 from "13206__.js";
import _mod13207 from "13207__.js";
import _mod13208 from "13208__.js";
import _mod13209 from "13209__.js";
import _mod13210 from "13210__.js";
import _getEventFilterUrl from "../13211__getEventFilterUrl.js";
import _mod13212 from "13212__.js";
import _mod13213 from "13213__.js";
import _mod13214 from "13214__.js";
import _mod13216 from "13216__.js";
import extractRequestData from "../13217_extractRequestData.js";
import stripUrlQueryAndFragment from "../13218_stripUrlQueryAndFragment.js";
import _mod13221 from "13221__.js";
import _mod13222 from "13222__.js";
import _mod13223 from "13223__.js";
import debugIntegration from "../13224_debugIntegration.js";
import _mod13225 from "13225__.js";
import extraErrorDataIntegration from "../13226_extraErrorDataIntegration.js";
import _mod13227 from "13227__.js";
import _mod13228 from "13228__.js";
import sessionTimingIntegration from "../13229_sessionTimingIntegration.js";
import _mod13230 from "13230__.js";
import _mod13231 from "13231__.js";
import _mod13232 from "13232__.js";
import _mod13234 from "13234__.js";
import metricsDefault from "../13235_metricsDefault.js";
import BrowserMetricsAggregator from "../13240_BrowserMetricsAggregator.js";
import _mod13241 from "13241__.js";
import _mod13242 from "13242__.js";
import _mod13243 from "13243__.js";
import _mod13244 from "13244__.js";
import _mod13245 from "13245__.js";
import _mod13246 from "13246__.js";
import _mod13247 from "13247__.js";
import supportsFetch from "../13248_supportsFetch.js";
import _mod13249 from "13249__.js";
import _mod13250 from "13250__.js";
import _mod13251 from "13251__.js";
import _mod13252 from "13252__.js";
import _mod13253 from "13253__.js";
import _mod13254 from "13254__.js";
import _mod13255 from "13255__.js";
import _mod13256 from "13256__.js";
import _mod13257 from "13257__.js";
import supportsHistory from "../13258_supportsHistory.js";
import _asyncNullishCoalesce2 from "../13259__asyncNullishCoalesce2.js";
import _nullishCoalesce from "../13260__nullishCoalesce.js";
import _asyncOptionalChain2 from "../13261__asyncOptionalChain2.js";
import _asyncOptionalChainDelete2 from "../13262__asyncOptionalChainDelete2.js";
import _optionalChain from "../13263__optionalChain.js";
import _optionalChainDelete from "../13264__optionalChainDelete.js";

const require = globalThis.__r;

export const registerSpanErrorInstrumentation = errorCallback.registerSpanErrorInstrumentation;
export const getCapturedScopesOnSpan = _mod13165.getCapturedScopesOnSpan;
export const setCapturedScopesOnSpan = _mod13165.setCapturedScopesOnSpan;
export const addTracingExtensions = _mod13166.addTracingExtensions;
export const TRACING_DEFAULTS = _mod13167.TRACING_DEFAULTS;
export const startIdleSpan = _mod13167.startIdleSpan;
export const SentrySpan = _mod13177.SentrySpan;
export const SentryNonRecordingSpan = _mod13169.SentryNonRecordingSpan;
export const SPAN_STATUS_ERROR = _mod13153.SPAN_STATUS_ERROR;
export const SPAN_STATUS_OK = _mod13153.SPAN_STATUS_OK;
export const SPAN_STATUS_UNSET = _mod13153.SPAN_STATUS_UNSET;
export const getSpanStatusFromHttpCode = _mod13153.getSpanStatusFromHttpCode;
export const setHttpStatus = _mod13153.setHttpStatus;
export const continueTrace = _mod13170.continueTrace;
export const startInactiveSpan = _mod13170.startInactiveSpan;
export const startNewTrace = _mod13170.startNewTrace;
export const startSpan = _mod13170.startSpan;
export const startSpanManual = _mod13170.startSpanManual;
export const suppressTracing = _mod13170.suppressTracing;
export const withActiveSpan = _mod13170.withActiveSpan;
export const getDynamicSamplingContextFromClient = _mod13172.getDynamicSamplingContextFromClient;
export const getDynamicSamplingContextFromScope = _mod13172.getDynamicSamplingContextFromScope;
export const getDynamicSamplingContextFromSpan = _mod13172.getDynamicSamplingContextFromSpan;
export const spanToBaggageHeader = _mod13172.spanToBaggageHeader;
export const setMeasurement = _mod13178.setMeasurement;
export const timedEventsToMeasurements = _mod13178.timedEventsToMeasurements;
export const sampleSpan = _mod13175.sampleSpan;
export const logSpanEnd = _mod13174.logSpanEnd;
export const logSpanStart = _mod13174.logSpanStart;
export const SEMANTIC_ATTRIBUTE_CACHE_HIT = _mod13151.SEMANTIC_ATTRIBUTE_CACHE_HIT;
export const SEMANTIC_ATTRIBUTE_CACHE_ITEM_SIZE = _mod13151.SEMANTIC_ATTRIBUTE_CACHE_ITEM_SIZE;
export const SEMANTIC_ATTRIBUTE_CACHE_KEY = _mod13151.SEMANTIC_ATTRIBUTE_CACHE_KEY;
export const SEMANTIC_ATTRIBUTE_EXCLUSIVE_TIME = _mod13151.SEMANTIC_ATTRIBUTE_EXCLUSIVE_TIME;
export const SEMANTIC_ATTRIBUTE_HTTP_REQUEST_METHOD = _mod13151.SEMANTIC_ATTRIBUTE_HTTP_REQUEST_METHOD;
export const SEMANTIC_ATTRIBUTE_PROFILE_ID = _mod13151.SEMANTIC_ATTRIBUTE_PROFILE_ID;
export const SEMANTIC_ATTRIBUTE_SENTRY_CUSTOM_SPAN_NAME = _mod13151.SEMANTIC_ATTRIBUTE_SENTRY_CUSTOM_SPAN_NAME;
export const SEMANTIC_ATTRIBUTE_SENTRY_IDLE_SPAN_FINISH_REASON =
  _mod13151.SEMANTIC_ATTRIBUTE_SENTRY_IDLE_SPAN_FINISH_REASON;
export const SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_UNIT = _mod13151.SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_UNIT;
export const SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_VALUE = _mod13151.SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_VALUE;
export const SEMANTIC_ATTRIBUTE_SENTRY_OP = _mod13151.SEMANTIC_ATTRIBUTE_SENTRY_OP;
export const SEMANTIC_ATTRIBUTE_SENTRY_ORIGIN = _mod13151.SEMANTIC_ATTRIBUTE_SENTRY_ORIGIN;
export const SEMANTIC_ATTRIBUTE_SENTRY_SAMPLE_RATE = _mod13151.SEMANTIC_ATTRIBUTE_SENTRY_SAMPLE_RATE;
export const SEMANTIC_ATTRIBUTE_SENTRY_SOURCE = _mod13151.SEMANTIC_ATTRIBUTE_SENTRY_SOURCE;
export const SEMANTIC_ATTRIBUTE_URL_FULL = _mod13151.SEMANTIC_ATTRIBUTE_URL_FULL;
export const createEventEnvelope = _mod13179.createEventEnvelope;
export const createSessionEnvelope = _mod13179.createSessionEnvelope;
export const createSpanEnvelope = _mod13179.createSpanEnvelope;
export const addEventProcessor = _flush.addEventProcessor;
export const captureCheckIn = _flush.captureCheckIn;
export const captureEvent = _flush.captureEvent;
export const captureException = _flush.captureException;
export const captureMessage = _flush.captureMessage;
export const captureSession = _flush.captureSession;
export const close = _flush.close;
export const endSession = _flush.endSession;
export const flush = _flush.flush;
export const isEnabled = _flush.isEnabled;
export const isInitialized = _flush.isInitialized;
export const lastEventId = _flush.lastEventId;
export const setContext = _flush.setContext;
export const setExtra = _flush.setExtra;
export const setExtras = _flush.setExtras;
export const setTag = _flush.setTag;
export const setTags = _flush.setTags;
export const setUser = _flush.setUser;
export const startSession = _flush.startSession;
export const withMonitor = _flush.withMonitor;
export const getClient = _mod13163.getClient;
export const getCurrentScope = _mod13163.getCurrentScope;
export const getGlobalScope = _mod13163.getGlobalScope;
export const getIsolationScope = _mod13163.getIsolationScope;
export const getTraceContextFromScope = _mod13163.getTraceContextFromScope;
export const withIsolationScope = _mod13163.withIsolationScope;
export const withScope = _mod13163.withScope;
export const getDefaultCurrentScope = _mod13162.getDefaultCurrentScope;
export const getDefaultIsolationScope = _mod13162.getDefaultIsolationScope;
export const setAsyncContextStrategy = _mod13155.setAsyncContextStrategy;
export const getMainCarrier = _mod13154.getMainCarrier;
export const closeSession = _mod13159.closeSession;
export const makeSession = _mod13159.makeSession;
export const updateSession = _mod13159.updateSession;
export const SessionFlusher = SessionFlusher.SessionFlusher;
export const Scope = ScopeClass.Scope;
export const notifyEventProcessors = notifyEventProcessors.notifyEventProcessors;
export const getEnvelopeEndpointWithUrlEncodedAuth = _mod13190.getEnvelopeEndpointWithUrlEncodedAuth;
export const getReportDialogEndpoint = _mod13190.getReportDialogEndpoint;
export const BaseClient = _mod13191.BaseClient;
export const ServerRuntimeClient = _mod13195.ServerRuntimeClient;
export const initAndBind = _mod13198.initAndBind;
export const setCurrentClient = _mod13198.setCurrentClient;
export const createTransport = _mod13199.createTransport;
export const makeOfflineTransport = _mod13202.makeOfflineTransport;
export const makeMultiplexedTransport = _mod13203.makeMultiplexedTransport;
export const addIntegration = _mod13192.addIntegration;
export const defineIntegration = _mod13192.defineIntegration;
export const getIntegrationsToSetup = _mod13192.getIntegrationsToSetup;
export const applyScopeDataToEvent = applyScopeDataToEvent.applyScopeDataToEvent;
export const mergeScopeData = applyScopeDataToEvent.mergeScopeData;
export const prepareEvent = _mod13185.prepareEvent;
export const createCheckInEnvelope = _mod13197.createCheckInEnvelope;
export const hasTracingEnabled = _mod13168.hasTracingEnabled;
export const isSentryRequestUrl = _mod13204.isSentryRequestUrl;
export const handleCallbackErrors = _mod13171.handleCallbackErrors;
export const parameterize = _mod13205.parameterize;
export const addChildSpanToSpan = spanTimeInputToSeconds.addChildSpanToSpan;
export const getActiveSpan = spanTimeInputToSeconds.getActiveSpan;
export const getRootSpan = spanTimeInputToSeconds.getRootSpan;
export const getSpanDescendants = spanTimeInputToSeconds.getSpanDescendants;
export const getStatusMessage = spanTimeInputToSeconds.getStatusMessage;
export const spanIsSampled = spanTimeInputToSeconds.spanIsSampled;
export const spanTimeInputToSeconds = spanTimeInputToSeconds.spanTimeInputToSeconds;
export const spanToJSON = spanTimeInputToSeconds.spanToJSON;
export const spanToTraceContext = spanTimeInputToSeconds.spanToTraceContext;
export const spanToTraceHeader = spanTimeInputToSeconds.spanToTraceHeader;
export const updateSpanName = spanTimeInputToSeconds.updateSpanName;
export const parseSampleRate = _mod13176.parseSampleRate;
export const applySdkMetadata = _mod13206.applySdkMetadata;
export const getTraceData = _mod13207.getTraceData;
export const getTraceMetaTags = _mod13208.getTraceMetaTags;
export const DEFAULT_ENVIRONMENT = _mod13173.DEFAULT_ENVIRONMENT;
export const addBreadcrumb = _mod13209.addBreadcrumb;
export const functionToStringIntegration = _mod13210.functionToStringIntegration;
export const inboundFiltersIntegration = _getEventFilterUrl.inboundFiltersIntegration;
export const linkedErrorsIntegration = _mod13212.linkedErrorsIntegration;
export const moduleMetadataIntegration = _mod13214.moduleMetadataIntegration;
export const requestDataIntegration = _mod13216.requestDataIntegration;
export const captureConsoleIntegration = _mod13221.captureConsoleIntegration;
export const debugIntegration = debugIntegration.debugIntegration;
export const dedupeIntegration = _mod13225.dedupeIntegration;
export const extraErrorDataIntegration = extraErrorDataIntegration.extraErrorDataIntegration;
export const rewriteFramesIntegration = _mod13227.rewriteFramesIntegration;
export const sessionTimingIntegration = sessionTimingIntegration.sessionTimingIntegration;
export const zodErrorsIntegration = _mod13230.zodErrorsIntegration;
export const thirdPartyErrorFilterIntegration = _mod13231.thirdPartyErrorFilterIntegration;
export const metrics = _mod13232.metrics;
export const profiler = _mod13234.profiler;
export const metricsDefault = metricsDefault.metricsDefault;
export const BrowserMetricsAggregator = BrowserMetricsAggregator.BrowserMetricsAggregator;
export const getMetricSummaryJsonForSpan = _mod13152.getMetricSummaryJsonForSpan;
export const addTracingHeadersToFetchRequest = _mod13241.addTracingHeadersToFetchRequest;
export const instrumentFetchRequest = _mod13241.instrumentFetchRequest;
export const trpcMiddleware = _mod13242.trpcMiddleware;
export const captureFeedback = _mod13243.captureFeedback;
export const getCurrentHub = _mod13244.getCurrentHub;
export const getCurrentHubShim = _mod13244.getCurrentHubShim;
export const applyAggregateErrorsToEvent = _mod13213.applyAggregateErrorsToEvent;
export const flatten = _mod13245.flatten;
export const getBreadcrumbLogLevelFromHttpStatusCode = _mod13246.getBreadcrumbLogLevelFromHttpStatusCode;
export const getComponentName = _mod13144.getComponentName;
export const getDomElement = _mod13144.getDomElement;
export const getLocationHref = _mod13144.getLocationHref;
export const htmlTreeAsString = _mod13144.htmlTreeAsString;
export const dsnFromString = _mod13183.dsnFromString;
export const dsnToString = _mod13183.dsnToString;
export const makeDsn = _mod13183.makeDsn;
export const SentryError = _mod13193.SentryError;
export const GLOBAL_OBJ = _mod13137.GLOBAL_OBJ;
export const getGlobalSingleton = _mod13137.getGlobalSingleton;
export const addConsoleInstrumentationHandler = _mod13222.addConsoleInstrumentationHandler;
export const addFetchEndInstrumentationHandler = _mod13247.addFetchEndInstrumentationHandler;
export const addFetchInstrumentationHandler = _mod13247.addFetchInstrumentationHandler;
export const addGlobalErrorInstrumentationHandler = _mod13133.addGlobalErrorInstrumentationHandler;
export const addGlobalUnhandledRejectionInstrumentationHandler =
  _mod13140.addGlobalUnhandledRejectionInstrumentationHandler;
export const addHandler = _mod13134.addHandler;
export const maybeInstrument = _mod13134.maybeInstrument;
export const resetInstrumentationHandlers = _mod13134.resetInstrumentationHandlers;
export const triggerHandlers = _mod13134.triggerHandlers;
export const isDOMError = _mod13143.isDOMError;
export const isDOMException = _mod13143.isDOMException;
export const isElement = _mod13143.isElement;
export const isError = _mod13143.isError;
export const isErrorEvent = _mod13143.isErrorEvent;
export const isEvent = _mod13143.isEvent;
export const isInstanceOf = _mod13143.isInstanceOf;
export const isParameterizedString = _mod13143.isParameterizedString;
export const isPlainObject = _mod13143.isPlainObject;
export const isPrimitive = _mod13143.isPrimitive;
export const isRegExp = _mod13143.isRegExp;
export const isString = _mod13143.isString;
export const isSyntheticEvent = _mod13143.isSyntheticEvent;
export const isThenable = _mod13143.isThenable;
export const isVueViewModel = _mod13143.isVueViewModel;
export const isBrowser = _mod13249.isBrowser;
export const CONSOLE_LEVELS = _mod13136.CONSOLE_LEVELS;
export const consoleSandbox = _mod13136.consoleSandbox;
export const logger = _mod13136.logger;
export const originalConsoleMethods = _mod13136.originalConsoleMethods;
export const memoBuilder = memoBuilder.memoBuilder;
export const addContextToFrame = _mod13147.addContextToFrame;
export const addExceptionMechanism = _mod13147.addExceptionMechanism;
export const addExceptionTypeValue = _mod13147.addExceptionTypeValue;
export const arrayify = _mod13147.arrayify;
export const checkOrSetAlreadyCaught = _mod13147.checkOrSetAlreadyCaught;
export const getEventDescription = _mod13147.getEventDescription;
export const parseSemver = _mod13147.parseSemver;
export const uuid4 = _mod13147.uuid4;
export const dynamicRequire = _mod13250.dynamicRequire;
export const isNodeEnv = _mod13250.isNodeEnv;
export const loadModule = _mod13250.loadModule;
export const normalize = _mod13181.normalize;
export const normalizeToSize = _mod13181.normalizeToSize;
export const normalizeUrlToBase = _mod13181.normalizeUrlToBase;
export const addNonEnumerableProperty = _mod13142.addNonEnumerableProperty;
export const convertToPlainObject = _mod13142.convertToPlainObject;
export const dropUndefinedKeys = _mod13142.dropUndefinedKeys;
export const extractExceptionKeysForMessage = _mod13142.extractExceptionKeysForMessage;
export const fill = _mod13142.fill;
export const getOriginalFunction = _mod13142.getOriginalFunction;
export const markFunctionWrapped = _mod13142.markFunctionWrapped;
export const objectify = _mod13142.objectify;
export const urlEncode = _mod13142.urlEncode;
export const basename = _mod13228.basename;
export const dirname = _mod13228.dirname;
export const isAbsolute = _mod13228.isAbsolute;
export const join = _mod13228.join;
export const normalizePath = _mod13228.normalizePath;
export const relative = _mod13228.relative;
export const resolve = _mod13228.resolve;
export const makePromiseBuffer = _mod13200.makePromiseBuffer;
export const DEFAULT_USER_INCLUDES = extractRequestData.DEFAULT_USER_INCLUDES;
export const addNormalizedRequestDataToEvent = extractRequestData.addNormalizedRequestDataToEvent;
export const addRequestDataToEvent = extractRequestData.addRequestDataToEvent;
export const extractPathForTransaction = extractRequestData.extractPathForTransaction;
export const extractQueryParamsFromUrl = extractRequestData.extractQueryParamsFromUrl;
export const extractRequestData = extractRequestData.extractRequestData;
export const headersToDict = extractRequestData.headersToDict;
export const httpRequestToRequestData = extractRequestData.httpRequestToRequestData;
export const winterCGHeadersToDict = extractRequestData.winterCGHeadersToDict;
export const winterCGRequestToRequestData = extractRequestData.winterCGRequestToRequestData;
export const severityLevelFromString = _mod13223.severityLevelFromString;
export const validSeverityLevels = _mod13223.validSeverityLevels;
export const UNKNOWN_FUNCTION = stackParserFromStackParserOptions.UNKNOWN_FUNCTION;
export const createStackParser = stackParserFromStackParserOptions.createStackParser;
export const getFramesFromEvent = stackParserFromStackParserOptions.getFramesFromEvent;
export const getFunctionName = stackParserFromStackParserOptions.getFunctionName;
export const stackParserFromStackParserOptions = stackParserFromStackParserOptions.stackParserFromStackParserOptions;
export const stripSentryFramesAndReverse = stackParserFromStackParserOptions.stripSentryFramesAndReverse;
export const filenameIsInApp = _mod13252.filenameIsInApp;
export const node = _mod13252.node;
export const nodeStackLineParser = _mod13252.nodeStackLineParser;
export const isMatchingPattern = _mod13145.isMatchingPattern;
export const safeJoin = _mod13145.safeJoin;
export const snipLine = _mod13145.snipLine;
export const stringMatchesSomePattern = _mod13145.stringMatchesSomePattern;
export const truncate = _mod13145.truncate;
export const isNativeFunction = supportsFetch.isNativeFunction;
export const supportsDOMError = supportsFetch.supportsDOMError;
export const supportsDOMException = supportsFetch.supportsDOMException;
export const supportsErrorEvent = supportsFetch.supportsErrorEvent;
export const supportsFetch = supportsFetch.supportsFetch;
export const supportsNativeFetch = supportsFetch.supportsNativeFetch;
export const supportsReferrerPolicy = supportsFetch.supportsReferrerPolicy;
export const supportsReportingObserver = supportsFetch.supportsReportingObserver;
export const SyncPromise = _mod13160.SyncPromise;
export const rejectedSyncPromise = _mod13160.rejectedSyncPromise;
export const resolvedSyncPromise = _mod13160.resolvedSyncPromise;
export const _browserPerformanceTimeOriginMode = require("13150__.js")._browserPerformanceTimeOriginMode;
export const browserPerformanceTimeOrigin = require("13150__.js").browserPerformanceTimeOrigin;
export const dateTimestampInSeconds = require("13150__.js").dateTimestampInSeconds;
export const timestampInSeconds = require("13150__.js").timestampInSeconds;
export const TRACEPARENT_REGEXP = _mod13148.TRACEPARENT_REGEXP;
export const extractTraceparentData = _mod13148.extractTraceparentData;
export const generateSentryTraceHeader = _mod13148.generateSentryTraceHeader;
export const propagationContextFromHeaders = _mod13148.propagationContextFromHeaders;
export const getSDKSource = _mod13251.getSDKSource;
export const isBrowserBundle = _mod13251.isBrowserBundle;
export const addItemToEnvelope = _mod13180.addItemToEnvelope;
export const createAttachmentEnvelopeItem = _mod13180.createAttachmentEnvelopeItem;
export const createEnvelope = _mod13180.createEnvelope;
export const createEventEnvelopeHeaders = _mod13180.createEventEnvelopeHeaders;
export const createSpanEnvelopeItem = _mod13180.createSpanEnvelopeItem;
export const envelopeContainsItemType = _mod13180.envelopeContainsItemType;
export const envelopeItemTypeToDataCategory = _mod13180.envelopeItemTypeToDataCategory;
export const forEachEnvelopeItem = _mod13180.forEachEnvelopeItem;
export const getSdkMetadataForEnvelopeHeader = _mod13180.getSdkMetadataForEnvelopeHeader;
export const parseEnvelope = _mod13180.parseEnvelope;
export const serializeEnvelope = _mod13180.serializeEnvelope;
export const createClientReportEnvelope = _mod13194.createClientReportEnvelope;
export const DEFAULT_RETRY_AFTER = _mod13201.DEFAULT_RETRY_AFTER;
export const disabledUntil = _mod13201.disabledUntil;
export const isRateLimited = _mod13201.isRateLimited;
export const parseRetryAfterHeader = _mod13201.parseRetryAfterHeader;
export const updateRateLimits = _mod13201.updateRateLimits;
export const BAGGAGE_HEADER_NAME = BAGGAGE_HEADER_NAME.BAGGAGE_HEADER_NAME;
export const MAX_BAGGAGE_STRING_LENGTH = BAGGAGE_HEADER_NAME.MAX_BAGGAGE_STRING_LENGTH;
export const SENTRY_BAGGAGE_KEY_PREFIX = BAGGAGE_HEADER_NAME.SENTRY_BAGGAGE_KEY_PREFIX;
export const SENTRY_BAGGAGE_KEY_PREFIX_REGEX = BAGGAGE_HEADER_NAME.SENTRY_BAGGAGE_KEY_PREFIX_REGEX;
export const baggageHeaderToDynamicSamplingContext = BAGGAGE_HEADER_NAME.baggageHeaderToDynamicSamplingContext;
export const dynamicSamplingContextToSentryBaggageHeader =
  BAGGAGE_HEADER_NAME.dynamicSamplingContextToSentryBaggageHeader;
export const parseBaggageHeader = BAGGAGE_HEADER_NAME.parseBaggageHeader;
export const getNumberOfUrlSegments = stripUrlQueryAndFragment.getNumberOfUrlSegments;
export const getSanitizedUrlString = stripUrlQueryAndFragment.getSanitizedUrlString;
export const parseUrl = stripUrlQueryAndFragment.parseUrl;
export const stripUrlQueryAndFragment = stripUrlQueryAndFragment.stripUrlQueryAndFragment;
export const makeFifoCache = _mod13253.makeFifoCache;
export const eventFromMessage = eventFromMessage.eventFromMessage;
export const eventFromUnknownInput = eventFromMessage.eventFromUnknownInput;
export const exceptionFromError = eventFromMessage.exceptionFromError;
export const parseStackFrames = eventFromMessage.parseStackFrames;
export const callFrameToStackFrame = _mod13254.callFrameToStackFrame;
export const watchdogTimer = _mod13254.watchdogTimer;
export const LRUMap = _mod13255.LRUMap;
export const generatePropagationContext = generatePropagationContext.generatePropagationContext;
export const generateSpanId = generatePropagationContext.generateSpanId;
export const generateTraceId = generatePropagationContext.generateTraceId;
export const vercelWaitUntil = _mod13256.vercelWaitUntil;
export const SDK_VERSION = _mod13138.SDK_VERSION;
export const getDebugImagesForResources = _mod13188.getDebugImagesForResources;
export const getFilenameToDebugIdMap = _mod13188.getFilenameToDebugIdMap;
export const escapeStringForRegex = _mod13257.escapeStringForRegex;
export const supportsHistory = supportsHistory.supportsHistory;
export const _asyncNullishCoalesce = _asyncNullishCoalesce2._asyncNullishCoalesce;
export const _asyncOptionalChain = _asyncOptionalChain2._asyncOptionalChain;
export const _asyncOptionalChainDelete = _asyncOptionalChainDelete2._asyncOptionalChainDelete;
export const _nullishCoalesce = _nullishCoalesce._nullishCoalesce;
export const _optionalChain = _optionalChain._optionalChain;
export const _optionalChainDelete = _optionalChainDelete._optionalChainDelete;
