// _runtime/metro/13140__.js
import errorCallback from "../13141_errorCallback.js";
import _mod13142 from "13142__.js";
import _mod13143 from "13143__.js";
import _mod13145 from "13145__.js";
import _mod13146 from "13146__.js";
import _mod13147 from "13147__.js";
import stackParserFromStackParserOptions from "../13148_stackParserFromStackParserOptions.js";
import _mod13149 from "13149__.js";
import spanTimeInputToSeconds from "../13150_spanTimeInputToSeconds.js";
import _mod13151 from "13151__.js";
import _mod13152 from "13152__.js";
import _mod13153 from "13153__.js";
import _mod13154 from "13154__.js";
import generatePropagationContext from "../13155_generatePropagationContext.js";
import _mod13156 from "13156__.js";
import _mod13157 from "13157__.js";
import BAGGAGE_HEADER_NAME from "../13158_BAGGAGE_HEADER_NAME.js";
import _mod13160 from "13160__.js";
import _mod13161 from "13161__.js";
import _mod13162 from "13162__.js";
import _mod13163 from "13163__.js";
import _mod13164 from "13164__.js";
import ScopeClass from "../13166_ScopeClass.js";
import _mod13168 from "13168__.js";
import _mod13169 from "13169__.js";
import _mod13171 from "13171__.js";
import _mod13172 from "13172__.js";
import _mod13174 from "13174__.js";
import _mod13175 from "13175__.js";
import _mod13176 from "13176__.js";
import _mod13177 from "13177__.js";
import _mod13178 from "13178__.js";
import _mod13179 from "13179__.js";
import _mod13180 from "13180__.js";
import _mod13181 from "13181__.js";
import _mod13182 from "13182__.js";
import _mod13183 from "13183__.js";
import _mod13184 from "13184__.js";
import _mod13185 from "13185__.js";
import _mod13186 from "13186__.js";
import _mod13187 from "13187__.js";
import _mod13188 from "13188__.js";
import _mod13189 from "13189__.js";
import _mod13190 from "13190__.js";
import memoBuilder from "../13191_memoBuilder.js";
import _mod13192 from "13192__.js";
import _flush from "../13193__flush.js";
import _mod13194 from "13194__.js";
import applyScopeDataToEvent from "../13195_applyScopeDataToEvent.js";
import notifyEventProcessors from "../13196_notifyEventProcessors.js";
import _mod13197 from "13197__.js";
import SessionFlusher from "../13198_SessionFlusher.js";
import _mod13199 from "13199__.js";
import _mod13200 from "13200__.js";
import _mod13201 from "13201__.js";
import _mod13202 from "13202__.js";
import _mod13203 from "13203__.js";
import _mod13204 from "13204__.js";
import eventFromMessage from "../13205_eventFromMessage.js";
import _mod13206 from "13206__.js";
import _mod13207 from "13207__.js";
import _mod13208 from "13208__.js";
import _mod13209 from "13209__.js";
import _mod13210 from "13210__.js";
import _mod13211 from "13211__.js";
import _mod13212 from "13212__.js";
import _mod13213 from "13213__.js";
import _mod13214 from "13214__.js";
import _mod13215 from "13215__.js";
import _mod13216 from "13216__.js";
import _mod13217 from "13217__.js";
import _mod13218 from "13218__.js";
import _mod13219 from "13219__.js";
import _getEventFilterUrl from "../13220__getEventFilterUrl.js";
import _mod13221 from "13221__.js";
import _mod13222 from "13222__.js";
import _mod13223 from "13223__.js";
import _mod13225 from "13225__.js";
import extractRequestData from "../13226_extractRequestData.js";
import stripUrlQueryAndFragment from "../13227_stripUrlQueryAndFragment.js";
import _mod13230 from "13230__.js";
import _mod13231 from "13231__.js";
import _mod13232 from "13232__.js";
import debugIntegration from "../13233_debugIntegration.js";
import _mod13234 from "13234__.js";
import extraErrorDataIntegration from "../13235_extraErrorDataIntegration.js";
import _mod13236 from "13236__.js";
import _mod13237 from "13237__.js";
import sessionTimingIntegration from "../13238_sessionTimingIntegration.js";
import _mod13239 from "13239__.js";
import _mod13240 from "13240__.js";
import _mod13241 from "13241__.js";
import _mod13243 from "13243__.js";
import metricsDefault from "../13244_metricsDefault.js";
import BrowserMetricsAggregator from "../13249_BrowserMetricsAggregator.js";
import _mod13250 from "13250__.js";
import _mod13251 from "13251__.js";
import _mod13252 from "13252__.js";
import _mod13253 from "13253__.js";
import _mod13254 from "13254__.js";
import _mod13255 from "13255__.js";
import _mod13256 from "13256__.js";
import supportsFetch from "../13257_supportsFetch.js";
import _mod13258 from "13258__.js";
import _mod13259 from "13259__.js";
import _mod13260 from "13260__.js";
import _mod13261 from "13261__.js";
import _mod13262 from "13262__.js";
import _mod13263 from "13263__.js";
import _mod13264 from "13264__.js";
import _mod13265 from "13265__.js";
import _mod13266 from "13266__.js";
import supportsHistory from "../13267_supportsHistory.js";
import _asyncNullishCoalesce2 from "../13268__asyncNullishCoalesce2.js";
import _nullishCoalesce from "../13269__nullishCoalesce.js";
import _asyncOptionalChain2 from "../13270__asyncOptionalChain2.js";
import _asyncOptionalChainDelete2 from "../13271__asyncOptionalChainDelete2.js";
import _optionalChain from "../13272__optionalChain.js";
import _optionalChainDelete from "../13273__optionalChainDelete.js";

const require = globalThis.__r;

export const registerSpanErrorInstrumentation = errorCallback.registerSpanErrorInstrumentation;
export const getCapturedScopesOnSpan = _mod13174.getCapturedScopesOnSpan;
export const setCapturedScopesOnSpan = _mod13174.setCapturedScopesOnSpan;
export const addTracingExtensions = _mod13175.addTracingExtensions;
export const TRACING_DEFAULTS = _mod13176.TRACING_DEFAULTS;
export const startIdleSpan = _mod13176.startIdleSpan;
export const SentrySpan = _mod13186.SentrySpan;
export const SentryNonRecordingSpan = _mod13178.SentryNonRecordingSpan;
export const SPAN_STATUS_ERROR = _mod13162.SPAN_STATUS_ERROR;
export const SPAN_STATUS_OK = _mod13162.SPAN_STATUS_OK;
export const SPAN_STATUS_UNSET = _mod13162.SPAN_STATUS_UNSET;
export const getSpanStatusFromHttpCode = _mod13162.getSpanStatusFromHttpCode;
export const setHttpStatus = _mod13162.setHttpStatus;
export const continueTrace = _mod13179.continueTrace;
export const startInactiveSpan = _mod13179.startInactiveSpan;
export const startNewTrace = _mod13179.startNewTrace;
export const startSpan = _mod13179.startSpan;
export const startSpanManual = _mod13179.startSpanManual;
export const suppressTracing = _mod13179.suppressTracing;
export const withActiveSpan = _mod13179.withActiveSpan;
export const getDynamicSamplingContextFromClient = _mod13181.getDynamicSamplingContextFromClient;
export const getDynamicSamplingContextFromScope = _mod13181.getDynamicSamplingContextFromScope;
export const getDynamicSamplingContextFromSpan = _mod13181.getDynamicSamplingContextFromSpan;
export const spanToBaggageHeader = _mod13181.spanToBaggageHeader;
export const setMeasurement = _mod13187.setMeasurement;
export const timedEventsToMeasurements = _mod13187.timedEventsToMeasurements;
export const sampleSpan = _mod13184.sampleSpan;
export const logSpanEnd = _mod13183.logSpanEnd;
export const logSpanStart = _mod13183.logSpanStart;
export const SEMANTIC_ATTRIBUTE_CACHE_HIT = _mod13160.SEMANTIC_ATTRIBUTE_CACHE_HIT;
export const SEMANTIC_ATTRIBUTE_CACHE_ITEM_SIZE = _mod13160.SEMANTIC_ATTRIBUTE_CACHE_ITEM_SIZE;
export const SEMANTIC_ATTRIBUTE_CACHE_KEY = _mod13160.SEMANTIC_ATTRIBUTE_CACHE_KEY;
export const SEMANTIC_ATTRIBUTE_EXCLUSIVE_TIME = _mod13160.SEMANTIC_ATTRIBUTE_EXCLUSIVE_TIME;
export const SEMANTIC_ATTRIBUTE_HTTP_REQUEST_METHOD = _mod13160.SEMANTIC_ATTRIBUTE_HTTP_REQUEST_METHOD;
export const SEMANTIC_ATTRIBUTE_PROFILE_ID = _mod13160.SEMANTIC_ATTRIBUTE_PROFILE_ID;
export const SEMANTIC_ATTRIBUTE_SENTRY_CUSTOM_SPAN_NAME = _mod13160.SEMANTIC_ATTRIBUTE_SENTRY_CUSTOM_SPAN_NAME;
export const SEMANTIC_ATTRIBUTE_SENTRY_IDLE_SPAN_FINISH_REASON =
  _mod13160.SEMANTIC_ATTRIBUTE_SENTRY_IDLE_SPAN_FINISH_REASON;
export const SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_UNIT = _mod13160.SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_UNIT;
export const SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_VALUE = _mod13160.SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_VALUE;
export const SEMANTIC_ATTRIBUTE_SENTRY_OP = _mod13160.SEMANTIC_ATTRIBUTE_SENTRY_OP;
export const SEMANTIC_ATTRIBUTE_SENTRY_ORIGIN = _mod13160.SEMANTIC_ATTRIBUTE_SENTRY_ORIGIN;
export const SEMANTIC_ATTRIBUTE_SENTRY_SAMPLE_RATE = _mod13160.SEMANTIC_ATTRIBUTE_SENTRY_SAMPLE_RATE;
export const SEMANTIC_ATTRIBUTE_SENTRY_SOURCE = _mod13160.SEMANTIC_ATTRIBUTE_SENTRY_SOURCE;
export const SEMANTIC_ATTRIBUTE_URL_FULL = _mod13160.SEMANTIC_ATTRIBUTE_URL_FULL;
export const createEventEnvelope = _mod13188.createEventEnvelope;
export const createSessionEnvelope = _mod13188.createSessionEnvelope;
export const createSpanEnvelope = _mod13188.createSpanEnvelope;
export const addEventProcessor = _flush.addEventProcessor;
export const captureCheckIn = _flush.captureCheckIn;
export const captureEvent = _flush.captureEvent;
export const captureException = _flush.captureException;
export const captureMessage = _flush.captureMessage;
export const captureSession = _flush.captureSession;
export const close = _flush.close;
export const endSession = _flush.endSession;
export const flush = _flush.flush;
export const isEnabled = _flush.isEnabled;
export const isInitialized = _flush.isInitialized;
export const lastEventId = _flush.lastEventId;
export const setContext = _flush.setContext;
export const setExtra = _flush.setExtra;
export const setExtras = _flush.setExtras;
export const setTag = _flush.setTag;
export const setTags = _flush.setTags;
export const setUser = _flush.setUser;
export const startSession = _flush.startSession;
export const withMonitor = _flush.withMonitor;
export const getClient = _mod13172.getClient;
export const getCurrentScope = _mod13172.getCurrentScope;
export const getGlobalScope = _mod13172.getGlobalScope;
export const getIsolationScope = _mod13172.getIsolationScope;
export const getTraceContextFromScope = _mod13172.getTraceContextFromScope;
export const withIsolationScope = _mod13172.withIsolationScope;
export const withScope = _mod13172.withScope;
export const getDefaultCurrentScope = _mod13171.getDefaultCurrentScope;
export const getDefaultIsolationScope = _mod13171.getDefaultIsolationScope;
export const setAsyncContextStrategy = _mod13164.setAsyncContextStrategy;
export const getMainCarrier = _mod13163.getMainCarrier;
export const closeSession = _mod13168.closeSession;
export const makeSession = _mod13168.makeSession;
export const updateSession = _mod13168.updateSession;
export const SessionFlusher = SessionFlusher.SessionFlusher;
export const Scope = ScopeClass.Scope;
export const notifyEventProcessors = notifyEventProcessors.notifyEventProcessors;
export const getEnvelopeEndpointWithUrlEncodedAuth = _mod13199.getEnvelopeEndpointWithUrlEncodedAuth;
export const getReportDialogEndpoint = _mod13199.getReportDialogEndpoint;
export const BaseClient = _mod13200.BaseClient;
export const ServerRuntimeClient = _mod13204.ServerRuntimeClient;
export const initAndBind = _mod13207.initAndBind;
export const setCurrentClient = _mod13207.setCurrentClient;
export const createTransport = _mod13208.createTransport;
export const makeOfflineTransport = _mod13211.makeOfflineTransport;
export const makeMultiplexedTransport = _mod13212.makeMultiplexedTransport;
export const addIntegration = _mod13201.addIntegration;
export const defineIntegration = _mod13201.defineIntegration;
export const getIntegrationsToSetup = _mod13201.getIntegrationsToSetup;
export const applyScopeDataToEvent = applyScopeDataToEvent.applyScopeDataToEvent;
export const mergeScopeData = applyScopeDataToEvent.mergeScopeData;
export const prepareEvent = _mod13194.prepareEvent;
export const createCheckInEnvelope = _mod13206.createCheckInEnvelope;
export const hasTracingEnabled = _mod13177.hasTracingEnabled;
export const isSentryRequestUrl = _mod13213.isSentryRequestUrl;
export const handleCallbackErrors = _mod13180.handleCallbackErrors;
export const parameterize = _mod13214.parameterize;
export const addChildSpanToSpan = spanTimeInputToSeconds.addChildSpanToSpan;
export const getActiveSpan = spanTimeInputToSeconds.getActiveSpan;
export const getRootSpan = spanTimeInputToSeconds.getRootSpan;
export const getSpanDescendants = spanTimeInputToSeconds.getSpanDescendants;
export const getStatusMessage = spanTimeInputToSeconds.getStatusMessage;
export const spanIsSampled = spanTimeInputToSeconds.spanIsSampled;
export const spanTimeInputToSeconds = spanTimeInputToSeconds.spanTimeInputToSeconds;
export const spanToJSON = spanTimeInputToSeconds.spanToJSON;
export const spanToTraceContext = spanTimeInputToSeconds.spanToTraceContext;
export const spanToTraceHeader = spanTimeInputToSeconds.spanToTraceHeader;
export const updateSpanName = spanTimeInputToSeconds.updateSpanName;
export const parseSampleRate = _mod13185.parseSampleRate;
export const applySdkMetadata = _mod13215.applySdkMetadata;
export const getTraceData = _mod13216.getTraceData;
export const getTraceMetaTags = _mod13217.getTraceMetaTags;
export const DEFAULT_ENVIRONMENT = _mod13182.DEFAULT_ENVIRONMENT;
export const addBreadcrumb = _mod13218.addBreadcrumb;
export const functionToStringIntegration = _mod13219.functionToStringIntegration;
export const inboundFiltersIntegration = _getEventFilterUrl.inboundFiltersIntegration;
export const linkedErrorsIntegration = _mod13221.linkedErrorsIntegration;
export const moduleMetadataIntegration = _mod13223.moduleMetadataIntegration;
export const requestDataIntegration = _mod13225.requestDataIntegration;
export const captureConsoleIntegration = _mod13230.captureConsoleIntegration;
export const debugIntegration = debugIntegration.debugIntegration;
export const dedupeIntegration = _mod13234.dedupeIntegration;
export const extraErrorDataIntegration = extraErrorDataIntegration.extraErrorDataIntegration;
export const rewriteFramesIntegration = _mod13236.rewriteFramesIntegration;
export const sessionTimingIntegration = sessionTimingIntegration.sessionTimingIntegration;
export const zodErrorsIntegration = _mod13239.zodErrorsIntegration;
export const thirdPartyErrorFilterIntegration = _mod13240.thirdPartyErrorFilterIntegration;
export const metrics = _mod13241.metrics;
export const profiler = _mod13243.profiler;
export const metricsDefault = metricsDefault.metricsDefault;
export const BrowserMetricsAggregator = BrowserMetricsAggregator.BrowserMetricsAggregator;
export const getMetricSummaryJsonForSpan = _mod13161.getMetricSummaryJsonForSpan;
export const addTracingHeadersToFetchRequest = _mod13250.addTracingHeadersToFetchRequest;
export const instrumentFetchRequest = _mod13250.instrumentFetchRequest;
export const trpcMiddleware = _mod13251.trpcMiddleware;
export const captureFeedback = _mod13252.captureFeedback;
export const getCurrentHub = _mod13253.getCurrentHub;
export const getCurrentHubShim = _mod13253.getCurrentHubShim;
export const applyAggregateErrorsToEvent = _mod13222.applyAggregateErrorsToEvent;
export const flatten = _mod13254.flatten;
export const getBreadcrumbLogLevelFromHttpStatusCode = _mod13255.getBreadcrumbLogLevelFromHttpStatusCode;
export const getComponentName = _mod13153.getComponentName;
export const getDomElement = _mod13153.getDomElement;
export const getLocationHref = _mod13153.getLocationHref;
export const htmlTreeAsString = _mod13153.htmlTreeAsString;
export const dsnFromString = _mod13192.dsnFromString;
export const dsnToString = _mod13192.dsnToString;
export const makeDsn = _mod13192.makeDsn;
export const SentryError = _mod13202.SentryError;
export const GLOBAL_OBJ = _mod13146.GLOBAL_OBJ;
export const getGlobalSingleton = _mod13146.getGlobalSingleton;
export const addConsoleInstrumentationHandler = _mod13231.addConsoleInstrumentationHandler;
export const addFetchEndInstrumentationHandler = _mod13256.addFetchEndInstrumentationHandler;
export const addFetchInstrumentationHandler = _mod13256.addFetchInstrumentationHandler;
export const addGlobalErrorInstrumentationHandler = _mod13142.addGlobalErrorInstrumentationHandler;
export const addGlobalUnhandledRejectionInstrumentationHandler =
  _mod13149.addGlobalUnhandledRejectionInstrumentationHandler;
export const addHandler = _mod13143.addHandler;
export const maybeInstrument = _mod13143.maybeInstrument;
export const resetInstrumentationHandlers = _mod13143.resetInstrumentationHandlers;
export const triggerHandlers = _mod13143.triggerHandlers;
export const isDOMError = _mod13152.isDOMError;
export const isDOMException = _mod13152.isDOMException;
export const isElement = _mod13152.isElement;
export const isError = _mod13152.isError;
export const isErrorEvent = _mod13152.isErrorEvent;
export const isEvent = _mod13152.isEvent;
export const isInstanceOf = _mod13152.isInstanceOf;
export const isParameterizedString = _mod13152.isParameterizedString;
export const isPlainObject = _mod13152.isPlainObject;
export const isPrimitive = _mod13152.isPrimitive;
export const isRegExp = _mod13152.isRegExp;
export const isString = _mod13152.isString;
export const isSyntheticEvent = _mod13152.isSyntheticEvent;
export const isThenable = _mod13152.isThenable;
export const isVueViewModel = _mod13152.isVueViewModel;
export const isBrowser = _mod13258.isBrowser;
export const CONSOLE_LEVELS = _mod13145.CONSOLE_LEVELS;
export const consoleSandbox = _mod13145.consoleSandbox;
export const logger = _mod13145.logger;
export const originalConsoleMethods = _mod13145.originalConsoleMethods;
export const memoBuilder = memoBuilder.memoBuilder;
export const addContextToFrame = _mod13156.addContextToFrame;
export const addExceptionMechanism = _mod13156.addExceptionMechanism;
export const addExceptionTypeValue = _mod13156.addExceptionTypeValue;
export const arrayify = _mod13156.arrayify;
export const checkOrSetAlreadyCaught = _mod13156.checkOrSetAlreadyCaught;
export const getEventDescription = _mod13156.getEventDescription;
export const parseSemver = _mod13156.parseSemver;
export const uuid4 = _mod13156.uuid4;
export const dynamicRequire = _mod13259.dynamicRequire;
export const isNodeEnv = _mod13259.isNodeEnv;
export const loadModule = _mod13259.loadModule;
export const normalize = _mod13190.normalize;
export const normalizeToSize = _mod13190.normalizeToSize;
export const normalizeUrlToBase = _mod13190.normalizeUrlToBase;
export const addNonEnumerableProperty = _mod13151.addNonEnumerableProperty;
export const convertToPlainObject = _mod13151.convertToPlainObject;
export const dropUndefinedKeys = _mod13151.dropUndefinedKeys;
export const extractExceptionKeysForMessage = _mod13151.extractExceptionKeysForMessage;
export const fill = _mod13151.fill;
export const getOriginalFunction = _mod13151.getOriginalFunction;
export const markFunctionWrapped = _mod13151.markFunctionWrapped;
export const objectify = _mod13151.objectify;
export const urlEncode = _mod13151.urlEncode;
export const basename = _mod13237.basename;
export const dirname = _mod13237.dirname;
export const isAbsolute = _mod13237.isAbsolute;
export const join = _mod13237.join;
export const normalizePath = _mod13237.normalizePath;
export const relative = _mod13237.relative;
export const resolve = _mod13237.resolve;
export const makePromiseBuffer = _mod13209.makePromiseBuffer;
export const DEFAULT_USER_INCLUDES = extractRequestData.DEFAULT_USER_INCLUDES;
export const addNormalizedRequestDataToEvent = extractRequestData.addNormalizedRequestDataToEvent;
export const addRequestDataToEvent = extractRequestData.addRequestDataToEvent;
export const extractPathForTransaction = extractRequestData.extractPathForTransaction;
export const extractQueryParamsFromUrl = extractRequestData.extractQueryParamsFromUrl;
export const extractRequestData = extractRequestData.extractRequestData;
export const headersToDict = extractRequestData.headersToDict;
export const httpRequestToRequestData = extractRequestData.httpRequestToRequestData;
export const winterCGHeadersToDict = extractRequestData.winterCGHeadersToDict;
export const winterCGRequestToRequestData = extractRequestData.winterCGRequestToRequestData;
export const severityLevelFromString = _mod13232.severityLevelFromString;
export const validSeverityLevels = _mod13232.validSeverityLevels;
export const UNKNOWN_FUNCTION = stackParserFromStackParserOptions.UNKNOWN_FUNCTION;
export const createStackParser = stackParserFromStackParserOptions.createStackParser;
export const getFramesFromEvent = stackParserFromStackParserOptions.getFramesFromEvent;
export const getFunctionName = stackParserFromStackParserOptions.getFunctionName;
export const stackParserFromStackParserOptions = stackParserFromStackParserOptions.stackParserFromStackParserOptions;
export const stripSentryFramesAndReverse = stackParserFromStackParserOptions.stripSentryFramesAndReverse;
export const filenameIsInApp = _mod13261.filenameIsInApp;
export const node = _mod13261.node;
export const nodeStackLineParser = _mod13261.nodeStackLineParser;
export const isMatchingPattern = _mod13154.isMatchingPattern;
export const safeJoin = _mod13154.safeJoin;
export const snipLine = _mod13154.snipLine;
export const stringMatchesSomePattern = _mod13154.stringMatchesSomePattern;
export const truncate = _mod13154.truncate;
export const isNativeFunction = supportsFetch.isNativeFunction;
export const supportsDOMError = supportsFetch.supportsDOMError;
export const supportsDOMException = supportsFetch.supportsDOMException;
export const supportsErrorEvent = supportsFetch.supportsErrorEvent;
export const supportsFetch = supportsFetch.supportsFetch;
export const supportsNativeFetch = supportsFetch.supportsNativeFetch;
export const supportsReferrerPolicy = supportsFetch.supportsReferrerPolicy;
export const supportsReportingObserver = supportsFetch.supportsReportingObserver;
export const SyncPromise = _mod13169.SyncPromise;
export const rejectedSyncPromise = _mod13169.rejectedSyncPromise;
export const resolvedSyncPromise = _mod13169.resolvedSyncPromise;
export const _browserPerformanceTimeOriginMode = require("13159__.js")._browserPerformanceTimeOriginMode;
export const browserPerformanceTimeOrigin = require("13159__.js").browserPerformanceTimeOrigin;
export const dateTimestampInSeconds = require("13159__.js").dateTimestampInSeconds;
export const timestampInSeconds = require("13159__.js").timestampInSeconds;
export const TRACEPARENT_REGEXP = _mod13157.TRACEPARENT_REGEXP;
export const extractTraceparentData = _mod13157.extractTraceparentData;
export const generateSentryTraceHeader = _mod13157.generateSentryTraceHeader;
export const propagationContextFromHeaders = _mod13157.propagationContextFromHeaders;
export const getSDKSource = _mod13260.getSDKSource;
export const isBrowserBundle = _mod13260.isBrowserBundle;
export const addItemToEnvelope = _mod13189.addItemToEnvelope;
export const createAttachmentEnvelopeItem = _mod13189.createAttachmentEnvelopeItem;
export const createEnvelope = _mod13189.createEnvelope;
export const createEventEnvelopeHeaders = _mod13189.createEventEnvelopeHeaders;
export const createSpanEnvelopeItem = _mod13189.createSpanEnvelopeItem;
export const envelopeContainsItemType = _mod13189.envelopeContainsItemType;
export const envelopeItemTypeToDataCategory = _mod13189.envelopeItemTypeToDataCategory;
export const forEachEnvelopeItem = _mod13189.forEachEnvelopeItem;
export const getSdkMetadataForEnvelopeHeader = _mod13189.getSdkMetadataForEnvelopeHeader;
export const parseEnvelope = _mod13189.parseEnvelope;
export const serializeEnvelope = _mod13189.serializeEnvelope;
export const createClientReportEnvelope = _mod13203.createClientReportEnvelope;
export const DEFAULT_RETRY_AFTER = _mod13210.DEFAULT_RETRY_AFTER;
export const disabledUntil = _mod13210.disabledUntil;
export const isRateLimited = _mod13210.isRateLimited;
export const parseRetryAfterHeader = _mod13210.parseRetryAfterHeader;
export const updateRateLimits = _mod13210.updateRateLimits;
export const BAGGAGE_HEADER_NAME = BAGGAGE_HEADER_NAME.BAGGAGE_HEADER_NAME;
export const MAX_BAGGAGE_STRING_LENGTH = BAGGAGE_HEADER_NAME.MAX_BAGGAGE_STRING_LENGTH;
export const SENTRY_BAGGAGE_KEY_PREFIX = BAGGAGE_HEADER_NAME.SENTRY_BAGGAGE_KEY_PREFIX;
export const SENTRY_BAGGAGE_KEY_PREFIX_REGEX = BAGGAGE_HEADER_NAME.SENTRY_BAGGAGE_KEY_PREFIX_REGEX;
export const baggageHeaderToDynamicSamplingContext = BAGGAGE_HEADER_NAME.baggageHeaderToDynamicSamplingContext;
export const dynamicSamplingContextToSentryBaggageHeader =
  BAGGAGE_HEADER_NAME.dynamicSamplingContextToSentryBaggageHeader;
export const parseBaggageHeader = BAGGAGE_HEADER_NAME.parseBaggageHeader;
export const getNumberOfUrlSegments = stripUrlQueryAndFragment.getNumberOfUrlSegments;
export const getSanitizedUrlString = stripUrlQueryAndFragment.getSanitizedUrlString;
export const parseUrl = stripUrlQueryAndFragment.parseUrl;
export const stripUrlQueryAndFragment = stripUrlQueryAndFragment.stripUrlQueryAndFragment;
export const makeFifoCache = _mod13262.makeFifoCache;
export const eventFromMessage = eventFromMessage.eventFromMessage;
export const eventFromUnknownInput = eventFromMessage.eventFromUnknownInput;
export const exceptionFromError = eventFromMessage.exceptionFromError;
export const parseStackFrames = eventFromMessage.parseStackFrames;
export const callFrameToStackFrame = _mod13263.callFrameToStackFrame;
export const watchdogTimer = _mod13263.watchdogTimer;
export const LRUMap = _mod13264.LRUMap;
export const generatePropagationContext = generatePropagationContext.generatePropagationContext;
export const generateSpanId = generatePropagationContext.generateSpanId;
export const generateTraceId = generatePropagationContext.generateTraceId;
export const vercelWaitUntil = _mod13265.vercelWaitUntil;
export const SDK_VERSION = _mod13147.SDK_VERSION;
export const getDebugImagesForResources = _mod13197.getDebugImagesForResources;
export const getFilenameToDebugIdMap = _mod13197.getFilenameToDebugIdMap;
export const escapeStringForRegex = _mod13266.escapeStringForRegex;
export const supportsHistory = supportsHistory.supportsHistory;
export const _asyncNullishCoalesce = _asyncNullishCoalesce2._asyncNullishCoalesce;
export const _asyncOptionalChain = _asyncOptionalChain2._asyncOptionalChain;
export const _asyncOptionalChainDelete = _asyncOptionalChainDelete2._asyncOptionalChainDelete;
export const _nullishCoalesce = _nullishCoalesce._nullishCoalesce;
export const _optionalChain = _optionalChain._optionalChain;
export const _optionalChainDelete = _optionalChainDelete._optionalChainDelete;
