// discord_app/modules/app_startup/AllGatewayConnectionStores.native.tsx
import obj132 from "../../../_runtime/00002_obj132.js";
import processCallbacks from "../gateway/PostConnectionCallbackStore.tsx";
import set from "../../stores/ConnectedAccountsStore.tsx";
import set2 from "../guild_mod_dash_member_safety/BulkBanStore.tsx";
import map from "../../stores/InstantInviteStore.tsx";
import set3 from "../media_channel/MediaPostSharePromptStore.tsx";
import set4 from "../forums/ForumPostUnreadCountStore.tsx";
import map2 from "../content_inventory/ContentInventoryStore.tsx";
import map3 from "../content_inventory/ContentInventoryOutboxStore.tsx";
import map4 from "../rtc/TransientKeyStore.tsx";
import map5 from "../creator_monetization/CreatorMonetizationStore.tsx";
import map6 from "../global_discovery_servers/GlobalDiscoveryServersSearchCountsStore.tsx";
import map7 from "../global_discovery_servers/GlobalDiscoveryServersSearchResultsStore.tsx";
import set5 from "../local_push_notification/native/LocalPushNotificationStore.tsx";
import participantFromServer from "../activities/EmbeddedActivitiesStore.tsx";
import "reset";
import adUser from "../ads/native/AdUserStore.tsx";
import "initialize";
import handleSelectedChannelStoreChanged from "../app_database/modules/messages/SaveableChannelsStore.tsx";
import hasChannel from "../app_database/stores/BasicChannelCacheStore.tsx";
import "result";
import handleDismissWithDismissed from "../app_launcher/AppLauncherStore.tsx";
import "handleInit";
import getIndexKey from "../application_commands/ApplicationCommandIndexStore.tsx";
import handleInit from "../application_commands/ApplicationCommandStore.tsx";
import addApplication from "../applications/ApplicationStore.tsx";
import handleUpdateUser from "../auth/LoginRequiredActionStore.tsx";
import handleClearCaches from "../cache/CacheStore.tsx";
import getParticipants from "../calls/ChannelRTCStore.tsx";
import "handleConnectionReset";
import isSubscriptionGated from "../channel/GatedChannelStore.tsx";
import resetAllState from "../channel/VoiceChannelAnimationStateStore.tsx";
import _toTimestampMs from "../channel/VoiceChannelStartTimeStore.tsx";
import isSyncedModeThemesEnabled from "../client_themes/ClientThemesBackgroundStore.tsx";
import "updateState";
import entryToKey from "../content_inventory/ContentInventoryActivityStore.tsx";
import withContent from "../dismissible_content/DismissibleContentShownStateStore.tsx";
import getEmojiToGroupId from "../emojis/EmojiStore.tsx";
import fromServer from "../emojis/RawGuildEmojiStore.tsx";
import getHash from "../experiments/ExperimentStore.tsx";
import "handleConnectionOpen";
import handleSearchMessagesSuccess from "../explicit_media_redaction/ExplicitMediaSearchStore.tsx";
import getFpMessageInfo from "../explicit_media_redaction/ExplicitMediaStore.tsx";
import showReviewRequestModal from "../feedback/native/RequestReviewStore.tsx";
import maybeRebuildState from "../forums/ForumActivePostStore.tsx";
import "handleLoadThreadsSuccess";
import handleLoadThreadsSuccess from "../forums/ForumPostRecentMessageStore.tsx";
import recountRelationshipTypes from "../game_relationships/GameRelationshipStore.tsx";
import computeAlertSettings from "../guild_antiraid/GuildIncidentsStore.tsx";
import handleMessageSendFailedAutomod from "../guild_automod/GuildAutomodMessageStore.tsx";
import truncateOldMessageData from "../guild_home/ActiveChannelsStore.tsx";
import handleGatewayJoinRequestUpdate from "../guild_member_verification/UserGuildJoinRequestStore.tsx";
import getMemberSafetyPageStore from "../guild_mod_dash_member_safety/MemberSafetyStore.tsx";
import "handleUpdate";
import shouldShowOnboarding from "../guild_onboarding/GuildOnboardingStore.tsx";
import secondaryIndexMap from "../guild_products/GuildProductsStore.tsx";
import completeStep from "../guild_progress/GuildProgressStore.tsx";
import makeGroupListingIndexSubscriptionListingTag from "../guild_role_subscriptions/GuildRoleSubscriptionsStore.tsx";
import computeRolesForGuild from "../guild_role_subscriptions/SubscriptionRoleStore.tsx";
import scheduledEventSort from "../guild_scheduled_events/GuildScheduledEventStore.tsx";
import "handleReset";
import snapshotSelectedGuildId from "../guild_themes/GuildThemeRuntimeStore.tsx";
import harvestType from "../harvester/DataHarvestStore.tsx";
import findOrCreateMessageRecord from "../inbox/RecentMentionsStore.tsx";
import "handleSetLocationMetadata";
import getMediaPostEmbed from "../media_channel/MediaPostEmbedStore.tsx";
import isMessagePreviewEnabledForChannel from "../message_request/MessageRequestPreviewStore.tsx";
import "processChannel";
import processChannel from "../message_request/SpamMessageRequestStore.tsx";
import dropChannelIfEmpty from "../messages/EphemeralMessageStore.tsx";
import updateGuildState from "../messages/GuildOfficialMessagesStore.tsx";
import _validate from "../notification_center/NotificationCenterItemsStore.tsx";
import startInterval from "../notifications/settings_unread_notice/UnreadSettingNoticeStore2.tsx";
import freshTeenActivityWithMap from "../parent_tools/FamilyCenterStore.tsx";
import handleSetLocationMetadata from "../phone/PhoneStore.tsx";
import setPremiumTypeActual from "../premium/OverridePremiumTypeStore.tsx";
import getCurrentTime from "../premium/gifting/PremiumGiftingIntentStore.tsx";
import clearDismissUntil from "../premium/native/NoticeStore.tsx";
import "handleConnectionOpenOrResumed";
import guildHasCommunity from "../recent_channels/NewChannelsStore.tsx";
import getRegionalFeatureConfig from "../regional_feature_config/RegionalFeatureConfigStore.tsx";
import resetStates from "../relationships/GuildFriendshipStore.tsx";
import getState from "../replies/PendingReplyStore.tsx";
import processMessage from "../replies/ReferencedMessageStore.tsx";
import updateTtl from "../rewards/ProgramRewardsStore.tsx";
import computeCallVerification from "../rtc/SecureFramesVerifiedStore.tsx";
import getTimeSafe from "../saved_messages/SavedMessagesStore.tsx";
import handleReaction from "../search/SearchMessageStore.tsx";
import handleReset from "../search/SearchRecentMessageStore.tsx";
import "init";
import onPostConnectionOpen from "../slayer_storefront/SocialLayerStorefrontConfigManager.tsx";
import handleUserSettingsStoreUpdate from "../slayer_storefront/SocialLayerStorefrontStore.tsx";
import upsertAccount from "../spotify/SpotifyStore.tsx";
import getActiveStageChannelIds from "../stage_channels/StageChannelParticipantStore.tsx";
import buildStageChannelUserRoles from "../stage_channels/StageChannelRoleStore.tsx";
import handleUpdateActivity from "../stage_channels/StageChannelSelfRichPresenceStore.tsx";
import handleStageInstanceCreateOrUpdate from "../stage_channels/StageInstanceStore.tsx";
import parseServerGuildSticker from "../stickers/GuildStickersStore.tsx";
import loadSavedGuildStickers from "../stickers/StickersStore.tsx";
import handleQuickSwitcherUpdate from "../summaries/SummaryStore.tsx";
import rebuild from "../threads/ActiveJoinedThreadsStore.tsx";
import handleThreadCreateOrUpdate from "../threads/ActiveThreadsStore.tsx";
import listKey from "../threads/ArchivedThreadsStore.tsx";
import storeThread from "../threads/JoinedThreadsStore.tsx";
import handleUserUpdate from "../threads/ThreadMemberListStore.tsx";
import updateFromGuild from "../threads/ThreadMembersStore.tsx";
import updateState from "../threads/ThreadMessageStore.tsx";
import getNote from "../user_profile/notes/NoteStore.tsx";
import _getSystemLocale from "../user_settings/LocaleStore.tsx";
import handleThemeChange from "../user_settings/ThemeStore.tsx";
import handleConnectionClosedOrResumed from "../user_settings/UserSettingsProtoStore.tsx";
import stopActivity from "../../stores/ActivityTrackingStore.tsx";
import reset from "../../stores/ApplicationStreamingStore.tsx";
import fetchFingerprint from "../../stores/AuthenticationStore.tsx";
import callConnect from "../../stores/CallStore.tsx";
import incrementVersion from "../../stores/CategoryCollapseStore.tsx";
import getFollowerStatsForChannel from "../../stores/ChannelFollowerStatsStore.tsx";
import getMemberListId from "../../stores/ChannelMemberStore.tsx";
import handleChannelDelete from "../../stores/ChannelPinsStore.tsx";
import getSkuIdForChannel from "../../stores/ChannelSKUStore.tsx";
import ensureGuildLoaded from "../../stores/ChannelStore.tsx";
import hasConsented from "../../stores/ConsentStore.tsx";
import init from "../../stores/DeveloperExperimentStore.tsx";
import refreshSourceMapCookie from "../../stores/DeveloperOptionsStore.tsx";
import handleChanged from "../../stores/DraftStore.tsx";
import updateParty from "../../stores/GamePartyStore.tsx";
import getGeoRestrictedGuilds from "../../stores/GeoRestrictedGuildStore.tsx";
import updateGiftCode from "../../stores/GiftCodeStore.tsx";
import setIndex from "../../stores/GuildCategoryStore.tsx";
import comparator from "../../stores/GuildChannelStore.tsx";
import handleInviteData from "../../stores/GuildMemberCountStore.tsx";
import handleConnectionReset from "../../stores/GuildMemberRequesterStore.tsx";
import trackCommunicationDisabled from "../../stores/GuildMemberStore.tsx";
import allGuildIds from "../../stores/GuildMembershipStore.tsx";
import updateGuildUnreadSentinel from "../../stores/GuildReadStateStore.tsx";
import createGuildRoleRecordFromRust from "../../stores/GuildRoleStore.tsx";
import createGuildRecordFromRust from "../../stores/GuildStore.tsx";
import handleConnectionOpenOrResumed from "../../stores/GuildSubscriptionsStore.tsx";
import recomputeGuild from "../../stores/GuildVerificationStore.tsx";
import getVerificationKey from "../../stores/MFAStore.tsx";
import _detectH265HardwareDecode from "../../stores/MediaEngineStore.tsx";
import reactionKey from "../../stores/MessageReactionsStore.tsx";
import reinjectEphemerals from "../../stores/MessageStore.tsx";
import _handlePresenceUpdate from "../../stores/NowPlayingStore.tsx";
import getUncachedChannelPermissions from "../../stores/PermissionStore.tsx";
import sortActivity from "../../stores/PresenceStore.tsx";
import rebuildUnreads from "../../stores/PrivateChannelReadStateStore.tsx";
import performQuery from "../../stores/PrivateChannelRecipientsInviteStore.tsx";
import retryFailedUsers from "../../stores/RTCConnectionDesyncStore.tsx";
import createRTCConnection from "../../stores/RTCConnectionStore.tsx";
import generateOldThreadCutoff from "../../stores/ReadStateStore.tsx";
import markAllUserIdListsStale from "../../stores/RelationshipStore.tsx";
import handleConnectionOpen from "../../stores/SelectedGuildStore.tsx";
import filterPlayingActivities from "../../stores/SelfPresenceStore.tsx";
import handleUpdate from "../../stores/SessionsStore.tsx";
import insertUnsortedGuilds from "../../stores/SortedGuildStore.tsx";
import anyoneHasFlagInContext from "../../stores/SpeakingStore.tsx";
import fetchSurveyIfNeeded from "../../stores/SurveyStore.tsx";
import handleTypingStart from "../../stores/TypingStore.tsx";
import initialize from "../../stores/UploadStore.tsx";
import updateUserGuildSettingsInternal from "../../stores/UserGuildSettingsStore.tsx";
import handleRequiredAction from "../../stores/UserRequiredActionStore.tsx";
import mergeGuildAvatar from "../../stores/UserStore.tsx";
import makeTimeoutKey from "../../stores/VideoStreamStore.tsx";
import updateVoiceState from "../../stores/VoiceStateStore.tsx";
import handlePaymentSourceCreateEnd from "../../stores/billing/BillingInfoStore.tsx";
import handleUserStoreUpdates from "../../stores/channel_notices/GuildMFAWarningStore.tsx";
import checkGuildIsHub from "../../stores/channel_notices/HubLinkNoticeStore.tsx";
import handleAlertMessage from "../../stores/native/InAppNotificationStore.tsx";
import handleCacheOrSocketLoaded from "../../stores/native/NUFStore.tsx";
import makeSortedChannel from "../../stores/views/PrivateChannelSortStore.tsx";
import getVoiceStatesForGuild from "../../stores/views/SortedVoiceStateStore.tsx";

map3;
map2;
map5;
set4;
processCallbacks;
map6;
map7;
set2;
set5;
set3;
map4;
set;
map;
const result = obj132.fileFinishedImporting("modules/app_startup/AllGatewayConnectionStores.native.tsx");

export default function noop() {

};