// === Module 15767: UserSettingsDesignSystemTableRow ===

// Module 15767 (UserSettingsDesignSystemTableRow)
import initialize from "initialize" /* 504 */;
import native from "native" /* 1178 */;
import AvatarUtilsDefault from "AvatarUtils" /* 1396 */;
import useSafeAreaInsetsDefault from "useSafeAreaInsets" /* 1611 */;
import Text_Text from "Text/Text" /* 4556 */;
import Stack_Stack from "Stack/Stack" /* 4973 */;
import LinearGradientDefault from "LinearGradient" /* 4987 */;
import TableCheckboxRow from "TableCheckboxRow" /* 5604 */;
import TableRow from "TableRow" /* 5605 */;
import TableRowIcon from "TableRowIcon" /* 5611 */;
import TableRadioGroup from "TableRadioGroup" /* 5685 */;
import TableRowGroup from "TableRowGroup" /* 5687 */;
import TableRadioRow from "TableRadioRow" /* 5688 */;
import TableSwitchRow from "TableSwitchRow" /* 7201 */;
import SettingsIcon from "SettingsIcon" /* 7380 */;
import RowButton from "RowButton" /* 8595 */;
import _modDef14109 from "module_14109" /* 14109 */;
import _modDef14110 from "module_14110" /* 14110 */;
import _modDef14111 from "module_14111" /* 14111 */;
import _modDef14112 from "module_14112" /* 14112 */;
import _slicedToArray from "module_32" /* 32 */;
import noop from "module_19" /* 19 */;
import SelectedGuildStore from "SelectedGuildStore" /* 4381 */;
import UserStore from "UserStore" /* 1371 */;

require = fn;
function MyTableRow() {
  let obj = { label: "Notifications", onPress, icon: null };
  obj = { IconComponent: SettingsIcon.SettingsIcon };
  obj.icon = closure_1_12(TableRow.TableRow.Icon, obj);
  return closure_1_12(TableRow.TableRow, obj);
}
get_ActivityIndicator = fn(17);
({ View: hasOwnProperty, Image: metroRequire, ScrollView: closure_7 } = get_ActivityIndicator);
const Constants = fn(1074);
({ NOOP: c10, StatusTypes: closure_11 } = Constants);
const jsxProd = fn(21);
({ jsx: closure_12, jsxs: map1 } = jsxProd);
const size = fn(2);
const result = size.fileFinishedImporting("modules/user_settings/design_system/native/UserSettingsDesignSystemTableRow.tsx");

export default function UserSettingsDesignSystemTableRow() {
  let obj = initialize;
  const items = [UserStore];
  const stateFromStores = obj.useStateFromStores(items, () => currentUser.getCurrentUser());
  const guildId = SelectedGuildStore.getGuildId();
  const rect = useSafeAreaInsetsDefault();
  [tmp4, require] = _slicedToArray(noop.useState(false), 2);
  const tmp3 = _slicedToArray(noop.useState(false), 2);
  [tmp6, importDefault] = _slicedToArray(noop.useState(false), 2);
  const callback = noop.useCallback((arg0) => {
    require(arg0);
  }, []);
  obj = { children: null };
  const callback1 = noop.useCallback((arg0) => {
    importDefault(arg0);
  }, []);
  obj = { spacing: 24, style: { paddingTop: rect.top, paddingBottom: rect.bottom, paddingHorizontal: 12 }, children: null };
  const obj1 = { hasIcons: true, children: null };
  const obj2 = { onPress, icon: null, label: "Boost your Server", subLabel: "Unlock perks for the entire community", trailing: null };
  const tmp5 = _slicedToArray(noop.useState(false), 2);
  obj2.icon = closure_12(TableRow.TableRow.Icon, { IconComponent: SettingsIcon.SettingsIcon });
  obj2.trailing = closure_12(TableRow.TableRow.Arrow, {});
  const items1 = [closure_12(TableRow.TableRow, obj2), closure_12(MyTableRow, {}), , , , , ];
  const obj4 = { icon: null, label: "Add a Friend" };
  const obj3 = { IconComponent: SettingsIcon.SettingsIcon };
  obj4.icon = closure_12(TableRow.TableRow.Icon, { IconComponent: SettingsIcon.SettingsIcon });
  items1[2] = closure_12(TableRow.TableRow, obj4);
  const obj6 = { icon: null, label: "A really long label that takes up all of the space and then some", subLabel: "A really long sublabel that takes up all of the space and then some" };
  const obj5 = { IconComponent: SettingsIcon.SettingsIcon };
  obj6.icon = closure_12(TableRow.TableRow.Icon, { IconComponent: SettingsIcon.SettingsIcon });
  items1[3] = closure_12(TableRow.TableRow, obj6);
  const obj8 = { icon: null, label: "A really long label, but next to an arrow, that takes up all of the space and then some", subLabel: "A really long sublabel, but next to an arrow, that takes up all of the space and then some", trailing: null };
  const obj7 = { IconComponent: SettingsIcon.SettingsIcon };
  obj8.icon = closure_12(TableRow.TableRow.Icon, { IconComponent: SettingsIcon.SettingsIcon });
  obj8.trailing = closure_12(TableRow.TableRow.Arrow, {});
  items1[4] = closure_12(TableRow.TableRow, obj8);
  const obj10 = { icon: null, label: null, subLabel: null };
  const obj9 = { IconComponent: SettingsIcon.SettingsIcon };
  obj10.icon = closure_12(TableRow.TableRow.Icon, { IconComponent: SettingsIcon.SettingsIcon });
  obj10.label = closure_12(Text_Text.Text, { variant: "text-md/medium", lineClamp: 1, children: "Custom node for label - A really long label that takes up all of the space and then some" });
  const obj12 = { style: { flexDirection: "row", alignItems: "center" }, children: null };
  const obj13 = { style: { flexShrink: 0, height: 24, width: 24, marginEnd: 8 }, source: null, resizeMode: "contain" };
  const obj14 = { uri: null };
  let obj17 = AvatarUtilsDefault;
  obj14.uri = obj17.getEmojiURL({ id: "801497159479722084", animated: false, size: 24 });
  obj13.source = obj14;
  const items2 = [closure_12(closure_6, obj13), closure_12(Text_Text.Text, { variant: "text-md/medium", lineClamp: 1, color: "text-muted", style: { flexShrink: 1 }, children: "Custom node for subLabel - A really long sublabel that takes up all of the space and then some" })];
  obj12.children = items2;
  obj10.subLabel = closure_13(closure_5, obj12);
  items1[5] = closure_12(TableRow.TableRow, obj10);
  const obj15 = { icon: null, label: "A disabled row", subLabel: "you cant do anything with this", disabled: true };
  const obj11 = { IconComponent: SettingsIcon.SettingsIcon };
  obj15.icon = closure_12(TableRow.TableRow.Icon, { IconComponent: SettingsIcon.SettingsIcon });
  items1[6] = closure_12(TableRow.TableRow, obj15);
  obj1.children = items1;
  const items3 = [closure_13(TableRowGroup.TableRowGroup, obj1), , , , , , ];
  obj17 = { title: "Table Row Section", hasIcons: true, children: null };
  const obj18 = { label: stateFromStores.globalName, subLabel: stateFromStores.username, icon: null };
  const obj16 = { IconComponent: SettingsIcon.SettingsIcon };
  obj18.icon = closure_12(native.Avatar, { user: stateFromStores, guildId, status: constants.ONLINE, size: native.AvatarSizes.REFRESH_MEDIUM_32 });
  const items4 = [closure_12(TableRow.TableRow, obj18), , , , , , , , , , ];
  const obj20 = { icon: null, label: "Language", trailing: null };
  const obj19 = { user: stateFromStores, guildId, status: constants.ONLINE, size: native.AvatarSizes.REFRESH_MEDIUM_32 };
  obj20.icon = closure_12(TableRow.TableRow.Icon, { IconComponent: SettingsIcon.SettingsIcon });
  obj20.trailing = closure_12(TableRow.TableRow.TrailingText, { text: "English (US)" });
  items4[1] = closure_12(TableRow.TableRow, obj20);
  const obj22 = { icon: null, label: "Display Name", trailing: null };
  const obj21 = { IconComponent: SettingsIcon.SettingsIcon };
  obj22.icon = closure_12(TableRow.TableRow.Icon, { IconComponent: SettingsIcon.SettingsIcon });
  obj22.trailing = closure_12(TableRow.TableRow.TrailingText, { text: "thisisareallylongusernamewhichshouldtruncate" });
  items4[2] = closure_12(TableRow.TableRow, obj22);
  const obj24 = { icon: null, label: "Display Name", trailing: null, arrow: true };
  const obj23 = { IconComponent: SettingsIcon.SettingsIcon };
  obj24.icon = closure_12(TableRow.TableRow.Icon, { IconComponent: SettingsIcon.SettingsIcon });
  obj24.trailing = closure_12(TableRow.TableRow.TrailingText, { text: "thisisareallylongusernamewhichshouldtruncate" });
  items4[3] = closure_12(TableRow.TableRow, obj24);
  const obj26 = { icon: null, label: "Display Name That Is Very Long And Maybe Wrap", trailing: null };
  const obj25 = { IconComponent: SettingsIcon.SettingsIcon };
  obj26.icon = closure_12(TableRow.TableRow.Icon, { IconComponent: SettingsIcon.SettingsIcon });
  obj26.trailing = closure_12(TableRow.TableRow.TrailingText, { text: "thisisareallylongusernamewhichshouldtruncate" });
  items4[4] = closure_12(TableRow.TableRow, obj26);
  const obj28 = { icon: null, label: "Display Name That Is Very Long And Maybe Wrap", trailing: null };
  const obj27 = { IconComponent: SettingsIcon.SettingsIcon };
  obj28.icon = closure_12(TableRow.TableRow.Icon, { IconComponent: SettingsIcon.SettingsIcon });
  obj28.trailing = closure_12(TableRow.TableRow.TrailingText, { text: "100" });
  items4[5] = closure_12(TableRow.TableRow, obj28);
  const obj30 = { icon: null, label: "Language", subLabel: "English (US)" };
  const obj29 = { IconComponent: SettingsIcon.SettingsIcon };
  obj30.icon = closure_12(TableRow.TableRow.Icon, { IconComponent: SettingsIcon.SettingsIcon });
  items4[6] = closure_12(TableRow.TableRow, obj30);
  const obj32 = { icon: null, label: "A really long label that has a switch next to it", subLabel: "Show more information in less space", value: null, onValueChange: null };
  const obj31 = { IconComponent: SettingsIcon.SettingsIcon };
  obj32.icon = closure_12(TableRow.TableRow.Icon, { IconComponent: SettingsIcon.SettingsIcon });
  obj32.value = tmp4;
  obj32.onValueChange = callback;
  items4[7] = closure_12(TableSwitchRow.TableSwitchRow, obj32);
  const obj34 = { icon: null, label: "Text & Images", subLabel: "Automatically play GIFs when possible", value: true, onValueChange: null, disabled: true };
  const obj33 = { IconComponent: SettingsIcon.SettingsIcon };
  obj34.icon = closure_12(TableRow.TableRow.Icon, { IconComponent: SettingsIcon.SettingsIcon });
  obj34.onValueChange = onPress;
  items4[8] = closure_12(TableSwitchRow.TableSwitchRow, obj34);
  const obj36 = { icon: null, label: "A checkbox row", subLabel: "This can be checked or unchecked", checked: null, onPress: null };
  const obj35 = { IconComponent: SettingsIcon.SettingsIcon };
  obj36.icon = closure_12(TableRow.TableRow.Icon, { IconComponent: SettingsIcon.SettingsIcon });
  obj36.checked = tmp6;
  obj36.onPress = callback1;
  items4[9] = closure_12(TableCheckboxRow.TableCheckboxRow, obj36);
  const obj38 = { icon: null, label: "A really long label that has a checkbox next to it", subLabel: "Show more information in less space", checked: true, disabled: true, onPress: null };
  const obj37 = { IconComponent: SettingsIcon.SettingsIcon };
  obj38.icon = closure_12(TableRow.TableRow.Icon, { IconComponent: SettingsIcon.SettingsIcon });
  obj38.onPress = onPress;
  items4[10] = closure_12(TableCheckboxRow.TableCheckboxRow, obj38);
  obj17.children = items4;
  items3[1] = closure_13(TableRowGroup.TableRowGroup, obj17);
  const obj40 = { title: "Draggable Table Rows", description: "Table rows can optionally show a drag handle. Note that this does not actually make them draggable, you need to implement that yourself.", hasIcons: true, children: null };
  const obj41 = { draggable: true, onPress, icon: null, label: "Boost your Server", subLabel: "Unlock perks for the entire community", trailing: null };
  const obj39 = { IconComponent: SettingsIcon.SettingsIcon };
  obj41.icon = closure_12(TableRow.TableRow.Icon, { IconComponent: SettingsIcon.SettingsIcon });
  obj41.trailing = closure_12(TableRow.TableRow.Arrow, {});
  const items5 = [closure_12(TableRow.TableRow, obj41), ];
  const obj43 = { draggable: true, onPress, icon: null, label: "Boost your Server", subLabel: "Unlock perks for the entire community", trailing: null };
  const obj42 = { IconComponent: SettingsIcon.SettingsIcon };
  obj43.icon = closure_12(TableRow.TableRow.Icon, { IconComponent: SettingsIcon.SettingsIcon });
  obj43.trailing = closure_12(TableRow.TableRow.Arrow, {});
  items5[1] = closure_12(TableRow.TableRow, obj43);
  obj40.children = items5;
  items3[2] = closure_13(TableRowGroup.TableRowGroup, obj40);
  const obj45 = { title: "No Icons", hasIcons: false, children: null };
  const items6 = [closure_12(TableRow.TableRow, { label: "First Item", subLabel: "Here is an item", onPress }), closure_12(TableRow.TableRow, { label: "Second Item", subLabel: "Here is another item", onPress }), closure_12(TableRow.TableRow, { label: "Third Item", subLabel: "Here is yet another item", onPress })];
  obj45.children = items6;
  items3[3] = closure_13(TableRowGroup.TableRowGroup, obj45);
  const obj49 = { title: "Radio Group", hasIcons: false, defaultValue: "option1", onChange: onPress, children: null };
  const items7 = [closure_12(TableRadioRow.TableRadioRow, { label: "First Item", subLabel: "Here is an item", value: "option1" }), closure_12(TableRadioRow.TableRadioRow, { label: "Second Item", subLabel: "Here is another item", value: "option2" }), closure_12(TableRadioRow.TableRadioRow, { label: "Third Item", subLabel: "Here is yet another item", value: "option3" }), closure_12(TableRadioRow.TableRadioRow, { label: "Disabled Item", subLabel: "This should not be selectable", value: "option4", disabled: true })];
  obj49.children = items7;
  items3[4] = closure_13(TableRadioGroup.TableRadioGroup, obj49);
  const obj50 = { title: "Online Status", hasIcons: true, defaultValue: "option1", onChange: onPress, children: null };
  const obj51 = { icon: null, label: "Online", value: "option1" };
  const obj44 = { IconComponent: SettingsIcon.SettingsIcon };
  const obj46 = { label: "First Item", subLabel: "Here is an item", onPress };
  const obj47 = { label: "Second Item", subLabel: "Here is another item", onPress };
  const obj48 = { label: "Third Item", subLabel: "Here is yet another item", onPress };
  obj51.icon = closure_12(TableRowIcon.TableRowIcon, { variant: "text-status-online", source: _modDef14112 });
  const items8 = [closure_12(TableRadioRow.TableRadioRow, obj51), , , ];
  const obj53 = { icon: null, label: "Idle", value: "option2" };
  const obj52 = { variant: "text-status-online", source: _modDef14112 };
  obj53.icon = closure_12(TableRowIcon.TableRowIcon, { variant: "text-status-idle", source: _modDef14109 });
  items8[1] = closure_12(TableRadioRow.TableRadioRow, obj53);
  const obj55 = { icon: null, label: "Do Not Disturb", value: "option3" };
  const obj54 = { variant: "text-status-idle", source: _modDef14109 };
  obj55.icon = closure_12(TableRowIcon.TableRowIcon, { variant: "text-status-dnd", source: _modDef14110 });
  items8[2] = closure_12(TableRadioRow.TableRadioRow, obj55);
  const obj57 = { icon: null, label: "Invisible", value: "option4" };
  const obj56 = { variant: "text-status-dnd", source: _modDef14110 };
  obj57.icon = closure_12(TableRowIcon.TableRowIcon, { variant: "text-status-offline", source: _modDef14111 });
  items8[3] = closure_12(TableRadioRow.TableRadioRow, obj57);
  obj50.children = items8;
  items3[5] = closure_13(TableRadioGroup.TableRadioGroup, obj50);
  const obj59 = { spacing: 12, children: null };
  const items9 = [closure_12(Text_Text.Text, { variant: "heading-sm/semibold", children: "Row buttons" }), , , ];
  const obj60 = { icon: null, label: "Boost your server", onPress: null };
  const obj58 = { variant: "text-status-offline", source: _modDef14111 };
  obj60.icon = closure_12(TableRow.TableRow.Icon, { IconComponent: SettingsIcon.SettingsIcon });
  obj60.onPress = onPress;
  items9[1] = closure_12(RowButton.RowButton, obj60);
  items9[2] = closure_12(RowButton.RowButton, { label: "Disabled row button", onPress, disabled: true, arrow: false });
  const obj63 = { style: { padding: 8 }, start: { x: 0, y: 0 }, end: { x: 1, y: 0 }, colors: ["red", "orange", "yellow", "green", "teal", "blue", "purple"], children: null };
  const obj61 = { IconComponent: SettingsIcon.SettingsIcon };
  const obj62 = { label: "Disabled row button", onPress, disabled: true, arrow: false };
  const obj64 = { icon: null, experimental_withBlurBackground: true, label: "Row Button", onPress: null };
  const tmp9 = LinearGradientDefault;
  obj64.icon = closure_12(TableRow.TableRow.Icon, { IconComponent: SettingsIcon.SettingsIcon, variant: "translucent" });
  obj64.onPress = onPress;
  obj63.children = closure_12(RowButton.RowButton, obj64);
  items9[3] = closure_12(tmp9, obj63);
  obj59.children = items9;
  items3[6] = closure_13(Stack_Stack.Stack, obj59);
  obj.children = items3;
  obj.children = closure_13(Stack_Stack.Stack, obj);
  return closure_12(closure_7, obj);
};