import { registerAsset } from "../../../../../_runtime/09751_registerAsset.js";
import { registerAsset } from "../../../../../_runtime/13213_registerAsset.js";
import { registerAsset } from "../../../../../_runtime/14414_registerAsset.js";
import { registerAsset } from "../../../../../_runtime/14415_registerAsset.js";
import { registerAsset } from "../../../../../_runtime/14416_registerAsset.js";
import { registerAsset } from "../../../../../_runtime/14417_registerAsset.js";
import { registerAsset } from "../../../../../_runtime/14418_registerAsset.js";
import { registerAsset } from "../../../../../_runtime/14419_registerAsset.js";
import { registerAsset } from "../../../../../_runtime/14420_registerAsset.js";
import { registerAsset } from "../../../../../_runtime/14421_registerAsset.js";
import { registerAsset } from "../../../../../_runtime/14422_registerAsset.js";
import { registerAsset } from "../../../../../_runtime/14423_registerAsset.js";
import { registerAsset } from "../../../../../_runtime/14424_registerAsset.js";
import { getSystemLocale } from "../../../../intl/index.native.tsx";
// discord_app/modules/user_settings/appearance/native/SettingsAppearanceDummyData.tsx
import { StatusTypes } from "ME";

const result = require("registerAsset").fileFinishedImporting("modules/user_settings/appearance/native/SettingsAppearanceDummyData.tsx");

export default function _default() {
  const items = [{ id: "1", kind: "messages-header" }, , , , , , , , , , ];
  let obj = { id: "2", kind: "activity-cards", cards: null };
  obj = { title: null, subtitle: null, kind: "activity", image: null, avatars: null };
  const intl = getSystemLocale /* getSystemLocale */.intl;
  obj[0] = intl.string(getSystemLocale /* getSystemLocale */.t.B6GPzA);
  const intl2 = getSystemLocale /* getSystemLocale */.intl;
  obj[1] = intl2.string(getSystemLocale /* getSystemLocale */.t["Tnrh/k"]);
  obj[3] = registerAsset;
  const items1 = [registerAsset, registerAsset, registerAsset, registerAsset, registerAsset];
  obj[4] = items1;
  const items2 = [obj, ];
  obj = { title: null, subtitle: null, kind: "voice-chat", image: null };
  const intl3 = getSystemLocale /* getSystemLocale */.intl;
  obj[0] = intl3.string(getSystemLocale /* getSystemLocale */.t.YAgqmE);
  const intl4 = getSystemLocale /* getSystemLocale */.intl;
  obj[1] = intl4.string(getSystemLocale /* getSystemLocale */.t["9YJgal"]);
  obj[3] = registerAsset;
  items2[1] = obj;
  obj[2] = items2;
  items[1] = obj;
  const obj1 = { id: "3", kind: "channel-row", timestamp: null, title: null, preview: null, isUnread: true, avatar1: null };
  const intl5 = getSystemLocale /* getSystemLocale */.intl;
  obj1[2] = intl5.formatToPlainString(getSystemLocale /* getSystemLocale */.t["XIGt+W"], { minutes: 24 });
  const intl6 = getSystemLocale /* getSystemLocale */.intl;
  obj1[3] = intl6.string(getSystemLocale /* getSystemLocale */.t["mK5Zd+"]);
  const intl7 = getSystemLocale /* getSystemLocale */.intl;
  obj1[4] = intl7.string(getSystemLocale /* getSystemLocale */.t.cvvVUV);
  obj1[6] = registerAsset;
  items[2] = obj1;
  const obj2 = { id: "4", kind: "channel-row", timestamp: null, title: null, preview: null, isUnread: true, avatar1: null, avatar2: null };
  const intl8 = getSystemLocale /* getSystemLocale */.intl;
  obj2[2] = intl8.formatToPlainString(getSystemLocale /* getSystemLocale */.t["XIGt+W"], { minutes: 32 });
  const intl9 = getSystemLocale /* getSystemLocale */.intl;
  obj2[3] = intl9.string(getSystemLocale /* getSystemLocale */.t.FpJH9k);
  const intl10 = getSystemLocale /* getSystemLocale */.intl;
  obj2[4] = intl10.string(getSystemLocale /* getSystemLocale */.t.F1WIrQ);
  obj2[6] = registerAsset;
  obj2[7] = registerAsset;
  items[3] = obj2;
  const obj3 = { id: "5", kind: "channel-row", timestamp: null, title: null, preview: null, avatar1: null, status: null };
  const intl11 = getSystemLocale /* getSystemLocale */.intl;
  obj3[2] = intl11.formatToPlainString(getSystemLocale /* getSystemLocale */.t.rhY1Rs, { hours: 1 });
  const intl12 = getSystemLocale /* getSystemLocale */.intl;
  obj3[3] = intl12.string(getSystemLocale /* getSystemLocale */.t.PHbyD7);
  const intl13 = getSystemLocale /* getSystemLocale */.intl;
  obj3[4] = intl13.string(getSystemLocale /* getSystemLocale */.t.GSuP1s);
  obj3[5] = registerAsset;
  obj3[6] = StatusTypes.IDLE;
  items[4] = obj3;
  const obj4 = { id: "7", kind: "channel-row", timestamp: null, title: null, preview: null, avatar1: null, avatar2: null };
  const intl14 = getSystemLocale /* getSystemLocale */.intl;
  obj4[2] = intl14.formatToPlainString(getSystemLocale /* getSystemLocale */.t.rhY1Rs, { hours: 2 });
  const intl15 = getSystemLocale /* getSystemLocale */.intl;
  obj4[3] = intl15.string(getSystemLocale /* getSystemLocale */.t["0HGnUV"]);
  const intl16 = getSystemLocale /* getSystemLocale */.intl;
  obj4[4] = intl16.string(getSystemLocale /* getSystemLocale */.t["VYL+vm"]);
  obj4[5] = registerAsset;
  obj4[6] = registerAsset;
  items[5] = obj4;
  const obj5 = { id: "10", kind: "channel-row", timestamp: null, title: null, preview: null, avatar1: null };
  const intl17 = getSystemLocale /* getSystemLocale */.intl;
  obj5[2] = intl17.formatToPlainString(getSystemLocale /* getSystemLocale */.t.rhY1Rs, { hours: 2 });
  const intl18 = getSystemLocale /* getSystemLocale */.intl;
  obj5[3] = intl18.string(getSystemLocale /* getSystemLocale */.t["z+f+zN"]);
  const intl19 = getSystemLocale /* getSystemLocale */.intl;
  obj5[4] = intl19.string(getSystemLocale /* getSystemLocale */.t.Wy2xnv);
  obj5[5] = registerAsset;
  items[6] = obj5;
  const obj6 = { id: "11", kind: "channel-row", timestamp: null, title: null, preview: null, avatar1: null, avatar2: null };
  const intl20 = getSystemLocale /* getSystemLocale */.intl;
  obj6[2] = intl20.formatToPlainString(getSystemLocale /* getSystemLocale */.t.rhY1Rs, { hours: 4 });
  const intl21 = getSystemLocale /* getSystemLocale */.intl;
  obj6[3] = intl21.string(getSystemLocale /* getSystemLocale */.t["AYOqO/"]);
  const intl22 = getSystemLocale /* getSystemLocale */.intl;
  obj6[4] = intl22.string(getSystemLocale /* getSystemLocale */.t.OrbvPP);
  obj6[5] = registerAsset;
  obj6[6] = registerAsset;
  items[7] = obj6;
  const obj7 = { id: "12", kind: "channel-row", timestamp: null, title: null, preview: null, avatar1: null, status: null };
  const intl23 = getSystemLocale /* getSystemLocale */.intl;
  obj7[2] = intl23.formatToPlainString(getSystemLocale /* getSystemLocale */.t.rhY1Rs, { hours: 6 });
  const intl24 = getSystemLocale /* getSystemLocale */.intl;
  obj7[3] = intl24.string(getSystemLocale /* getSystemLocale */.t["86rWJp"]);
  const intl25 = getSystemLocale /* getSystemLocale */.intl;
  obj7[4] = intl25.string(getSystemLocale /* getSystemLocale */.t.dFT4dX);
  obj7[5] = registerAsset;
  obj7[6] = StatusTypes.DND;
  items[8] = obj7;
  const obj8 = { id: "13", kind: "channel-row", timestamp: null, title: null, preview: null, avatar1: null };
  const intl26 = getSystemLocale /* getSystemLocale */.intl;
  obj8[2] = intl26.formatToPlainString(getSystemLocale /* getSystemLocale */.t.rhY1Rs, { hours: 18 });
  const intl27 = getSystemLocale /* getSystemLocale */.intl;
  obj8[3] = intl27.string(getSystemLocale /* getSystemLocale */.t["z3+vGV"]);
  const intl28 = getSystemLocale /* getSystemLocale */.intl;
  obj8[4] = intl28.string(getSystemLocale /* getSystemLocale */.t.Zj8Sl1);
  obj8[5] = registerAsset;
  items[9] = obj8;
  const obj9 = { id: "15", kind: "channel-row", timestamp: null, title: null, preview: null, avatar1: null, status: null };
  const intl29 = getSystemLocale /* getSystemLocale */.intl;
  obj9[2] = intl29.formatToPlainString(getSystemLocale /* getSystemLocale */.t.rhY1Rs, { hours: 21 });
  const intl30 = getSystemLocale /* getSystemLocale */.intl;
  obj9[3] = intl30.string(getSystemLocale /* getSystemLocale */.t["8SENG2"]);
  const intl31 = getSystemLocale /* getSystemLocale */.intl;
  obj9[4] = intl31.string(getSystemLocale /* getSystemLocale */.t["2ziAWp"]);
  obj9[5] = registerAsset;
  obj9[6] = StatusTypes.DND;
  items[10] = obj9;
  return items;
};