// discord_app/design/void/Form/native/index.tsx
import set from "../../../../../_runtime/00002_set.js";
import FormCheckboxRowDefault from "FormCheckboxRow.tsx";
import _modDef7137 from "FormRow.tsx";
import contextDefault from "Form.tsx";
import FormLabelDefault from "FormLabel.tsx";
import FormSubLabelDefault from "FormSubLabel.tsx";
import FormArrowDefault from "FormArrow.tsx";
import FormRadioDefault from "FormRadio.tsx";
import FormCheckboxDefault from "FormCheckbox.tsx";
import RowCheckmarkDefault from "FormCheckmark.tsx";
import FormIconDefault from "FormIcon.tsx";
import FormCTADefault from "FormCTA.tsx";
import FormCTAButtonDefault from "FormCTAButton.tsx";
import DividerDefault from "FormDivider.tsx";
import FormHintDefault from "FormHint.tsx";
import _modDef8601 from "FormInput.tsx";
import FormSectionDefault from "FormSection.tsx";
import FormTitleDefault from "FormTitle.tsx";
import OptionButtonDefault from "FormSelect.tsx";
import FormSwitchDefault from "FormSwitch.tsx";
import FormTextColors from "FormText.tsx";
import FormTextColorsDefault from "FormText.tsx";
import FormSwitchRowDefault from "FormSwitchRow.tsx";
import FormRadioRowDefault from "FormRadioRow.tsx";
import FormRadioGroupDefault from "FormRadioGroup.tsx";
import FormSliderRowDefault from "FormSliderRow.tsx";
import CardSectionDefault from "../../CardSection/native/CardSection.tsx";

const result = set.fileFinishedImporting("design/void/Form/native/index.tsx");

export const Form = contextDefault;
export const FormArrow = FormArrowDefault;
export const FormCheckbox = FormCheckboxDefault;
export const FormCheckmark = RowCheckmarkDefault;
export const FormCTA = FormCTADefault;
export const FormCTAButton = FormCTAButtonDefault;
export const FormDivider = DividerDefault;
export const FormHint = FormHintDefault;
export const FormIcon = FormIconDefault;
export const FormInput = _modDef8601;
export const FormLabel = FormLabelDefault;
export const FormRadio = FormRadioDefault;
export const FormRow = _modDef7137;
export const FormSection = FormSectionDefault;
export const FormSelect = OptionButtonDefault;
export const FormSubLabel = FormSubLabelDefault;
export const FormSwitch = FormSwitchDefault;
export const FormText = FormTextColorsDefault;
export const FormTextColors = FormTextColors.FormTextColors;
export const FormTitle = FormTitleDefault;
export const FormSwitchRow = FormSwitchRowDefault;
export const FormRadioRow = FormRadioRowDefault;
export const FormCheckboxRow = FormCheckboxRowDefault;
export const FormRadioGroup = FormRadioGroupDefault;
export const FormSliderRow = FormSliderRowDefault;
export const FormCardSection = CardSectionDefault;
