// === Module 14647: crossPlatformRPCCommands ===

// Module 14647 (crossPlatformRPCCommands)
import applicationDefault from "application" /* 14648 */;
import certifiedDevicesDefault from "certifiedDevices" /* 14652 */;
import channelsDefault from "channels" /* 14654 */;
import commands_configDefault from "commands/config" /* 14657 */;
import contextDefault from "context" /* 14658 */;
import guildsDefault from "guilds" /* 14663 */;
import imagesDefault from "images" /* 14664 */;
import invitesDefault from "invites" /* 14665 */;
import linksDefault from "links" /* 14667 */;
import logsDefault from "logs" /* 14674 */;
import networkingDefault from "networking" /* 14675 */;
import providersDefault from "providers" /* 14676 */;
import relationshipsDefault from "relationships" /* 14677 */;
import setActivityDefault from "setActivity" /* 14678 */;
import setOrientationLockStateDefault from "setOrientationLockState" /* 14679 */;
import merged15Default from "merged15" /* 14680 */;
import subscriptionsDefault from "subscriptions" /* 14687 */;
import usersDefault from "users" /* 14689 */;
import userSettingsDefault from "userSettings" /* 14690 */;
import platformBehaviorsDefault from "platformBehaviors" /* 14691 */;
import soundboardDefault from "soundboard" /* 14692 */;
import conjureLivePreviewDefault from "conjureLivePreview" /* 14693 */;
import conjureVoiceDefault from "conjureVoice" /* 14694 */;
import activitiesDefault from "activities" /* 14695 */;
import questsDefault from "quests" /* 14696 */;
import voiceChannelChatDefault from "voiceChannelChat" /* 14697 */;

const application = Object.assign(applicationDefault);
const certifiedDevices = Object.assign(certifiedDevicesDefault);
const channels = Object.assign(channelsDefault);
const config = Object.assign(commands_configDefault);
const context = Object.assign(contextDefault);
const guilds = Object.assign(guildsDefault);
const images = Object.assign(imagesDefault);
const invites = Object.assign(invitesDefault);
const links = Object.assign(linksDefault);
const logs = Object.assign(logsDefault);
const networking = Object.assign(networkingDefault);
const providers = Object.assign(providersDefault);
const relationships = Object.assign(relationshipsDefault);
const setActivity = Object.assign(setActivityDefault);
const setOrientationLockState = Object.assign(setOrientationLockStateDefault);
const merged15 = Object.assign(merged15Default);
const subscriptions = Object.assign(subscriptionsDefault);
const users = Object.assign(usersDefault);
const userSettings = Object.assign(userSettingsDefault);
const platformBehaviors = Object.assign(platformBehaviorsDefault);
const soundboard = Object.assign(soundboardDefault);
const conjureLivePreview = Object.assign(conjureLivePreviewDefault);
const conjureVoice = Object.assign(conjureVoiceDefault);
const activities = Object.assign(activitiesDefault);
const quests = Object.assign(questsDefault);
const voiceChannelChat = Object.assign(voiceChannelChatDefault);
const size = fn(2);
const result = size.fileFinishedImporting("modules/rpc/server/commands/crossPlatformRPCCommands.tsx");

export const crossPlatformCommands = {};