// === Module 17032: PremiumDiscountOfferActionSheetContent ===

// Module 17032 (PremiumDiscountOfferActionSheetContent)
import nativeDefault from "native" /* 576 */;
import util from "util" /* 1114 */;
import PremiumUtils from "PremiumUtils" /* 4262 */;
import Text_Text from "Text/Text" /* 4601 */;
import components_Button_Button from "components/Button/Button" /* 5025 */;
import FolderIcon from "FolderIcon" /* 5124 */;
import NitroFileUploadExperiments from "NitroFileUploadExperiments" /* 5180 */;
import native from "native" /* 5742 */;
import NitroWheelIcon from "NitroWheelIcon" /* 8732 */;
import ChatSmileIcon from "ChatSmileIcon" /* 9491 */;
import UserIcon from "UserIcon" /* 11896 */;
import PremiumPerksListDefault from "PremiumPerksList" /* 15771 */;
import noop from "module_19" /* 19 */;

require = fn;
const View = fn(17).View;
const PremiumTypes = fn(1373).PremiumTypes;
const jsxProd = fn(21);
({ jsx: hasOwnProperty, jsxs: metroRequire } = jsxProd);
const createStyles = fn(4605);
let obj = { contentContainer: null, buttonContainer: null, title: null, heroIllustrationContainer: null };
obj = { paddingHorizontal: 36, paddingTop: 18, paddingBottom: 36, width: "100%", backgroundColor: nativeDefault.colors.BACKGROUND_BASE_LOW, alignItems: "flex-start", display: "flex", flexDirection: "column", gap: 0 };
obj.contentContainer = obj;
obj.buttonContainer = { marginVertical: 6, width: "100%", height: 48 };
obj.title = { width: "100%", textAlign: "center" };
obj.heroIllustrationContainer = { alignItems: "center", justifyContent: "center", height: 188, width: "100%" };
let closure_7 = createStyles.createStyles(obj);
const size = fn(2);
const result = size.fileFinishedImporting("modules/premium/native/discounts/PremiumDiscountOfferActionSheetContent.tsx");

export default noop.memo(function PremiumDiscountOfferActionSheetContent(arg0) {
  ({ discountOffer, onConfirm } = arg0);
  const tmp = closure_7();
  let obj = { IconComponent: UserIcon.UserIcon, label: null, description: null };
  const intl = util.intl;
  obj.label = intl.string(util.t.kpMomJ);
  const intl2 = util.intl;
  obj.description = intl2.string(util.t.uVUtPw);
  const items = [obj, , ];
  obj = { IconComponent: ChatSmileIcon.ChatSmileIcon, label: null, description: null };
  const intl3 = util.intl;
  obj.label = intl3.string(util.t["R2IV/Q"]);
  const intl4 = util.intl;
  obj.description = intl4.string(util.t["3SUJLd"]);
  items[1] = obj;
  obj = { IconComponent: FolderIcon.FolderIcon, label: null, description: null };
  const intl5 = util.intl;
  obj.label = intl5.string(util.t["u/NJKc"]);
  let obj3 = NitroFileUploadExperiments;
  const obj1 = { legacyCopy: null, rolloutCopy: null };
  const intl6 = util.intl;
  obj1.legacyCopy = intl6.string(util.t.i1UuMk);
  const intl7 = util.intl;
  const obj2 = { maxFileSize: null };
  let obj6 = PremiumUtils;
  obj2.maxFileSize = obj6.getMaxFileSizeForPremiumType(PremiumTypes.TIER_2, { useSpace: false });
  obj1.rolloutCopy = intl7.formatToPlainString(util.t.PvqncD, obj2);
  obj.description = obj3.getNitroFileUploadRolloutCopy(obj1);
  items[2] = obj;
  const amount = discountOffer.discount.amount;
  obj3 = { style: tmp.contentContainer, children: null };
  const items1 = [hasOwnProperty(View, { style: tmp.heroIllustrationContainer, children: hasOwnProperty(native.NitroWumpusFlightRight3dIllustration, { width: 180, height: 180 }) }), , , ];
  const obj5 = { variant: "heading-xl/bold", color: "mobile-text-heading-primary", style: tmp.title, children: null };
  const intl8 = util.intl;
  obj5.children = intl8.formatToPlainString(util.t.qowbUk, { percent: amount });
  items1[1] = hasOwnProperty(Text_Text.Text, obj5);
  items1[2] = hasOwnProperty(PremiumPerksListDefault, { perks: items });
  obj6 = { style: tmp.buttonContainer, children: null };
  const obj7 = { size: "lg", text: null, onPress: null, grow: true, icon: null };
  const intl9 = util.intl;
  obj7.text = intl9.formatToPlainString(util.t.bkQ4bH, { percent: amount });
  obj7.onPress = onConfirm;
  const obj4 = { style: tmp.heroIllustrationContainer, children: hasOwnProperty(native.NitroWumpusFlightRight3dIllustration, { width: 180, height: 180 }) };
  obj7.icon = hasOwnProperty(NitroWheelIcon.NitroWheelIcon, { size: "md", color: nativeDefault.unsafe_rawColors.WHITE });
  obj6.children = hasOwnProperty(components_Button_Button.Button, obj7);
  items1[3] = hasOwnProperty(View, obj6);
  obj3.children = items1;
  return timestampProducer(View, obj3);
});