// _runtime/00119_setUpDefaltReactNativeEnvironment.js
import setUpDefaltReactNativeEnvironment from "setUpDefaltReactNativeEnvironment";

setUpDefaltReactNativeEnvironment = setUpDefaltReactNativeEnvironment.default();