// _runtime/00272_get_BatchedBridge.js
import { MessageQueue } from "00039_MessageQueue.js";
import { map } from "00066_map.js";
import { measure } from "00068_measure.js";
import { set } from "00144_set.js";
import { restoreDeletedValuesInNestedArray } from "00146_restoreDeletedValuesInNestedArray.js";
import { deepDiffer } from "00147_deepDiffer.js";
import { flattenStyle } from "00148_flattenStyle.js";
import { _isNativeReflectConstruct } from "00152__isNativeReflectConstruct.js";
import { _isNativeReflectConstruct } from "00189__isNativeReflectConstruct.js";
import { MessageQueue } from "00276_MessageQueue.js";
import { deepFreezeAndThrowOnMutationInDev } from "00277_deepFreezeAndThrowOnMutationInDev.js";
import { _isNativeReflectConstruct } from "00278__isNativeReflectConstruct.js";
import { legacySendAccessibilityEvent } from "00279_legacySendAccessibilityEvent.js";
import { EventEmitter } from "00280_EventEmitter.js";
import { createPublicRootInstance } from "00281_createPublicRootInstance.js";
import { dispatchNativeEvent } from "00282_dispatchNativeEvent.js";
const obj = {};
Object.defineProperty(obj, "BatchedBridge", { get: () => MessageQueue.default, set: undefined });
Object.defineProperty(obj, "ExceptionsManager", { get: () => _isNativeReflectConstruct.default, set: undefined });
Object.defineProperty(obj, "Platform", { get: () => require("00273_get_Version.js") /* get Version */ /* get Version */.default, set: undefined });
Object.defineProperty(obj, "RCTEventEmitter", { get: () => MessageQueue.default, set: undefined });
Object.defineProperty(obj, "ReactNativeViewConfigRegistry", { get: () => map, set: undefined });
Object.defineProperty(obj, "TextInputState", { get: () => set.default, set: undefined });
Object.defineProperty(obj, "UIManager", { get: () => measure.default, set: undefined });
Object.defineProperty(obj, "deepDiffer", { get: () => deepDiffer.default, set: undefined });
Object.defineProperty(obj, "deepFreezeAndThrowOnMutationInDev", { get: () => deepFreezeAndThrowOnMutationInDev.default, set: undefined });
Object.defineProperty(obj, "flattenStyle", { get: () => flattenStyle.default, set: undefined });
Object.defineProperty(obj, "ReactFiberErrorDialog", { get: () => _isNativeReflectConstruct.default, set: undefined });
Object.defineProperty(obj, "legacySendAccessibilityEvent", { get: () => legacySendAccessibilityEvent.default, set: undefined });
Object.defineProperty(obj, "RawEventEmitter", { get: () => EventEmitter.default, set: undefined });
Object.defineProperty(obj, "CustomEvent", { get: () => _isNativeReflectConstruct.default, set: undefined });
Object.defineProperty(obj, "createAttributePayload", { get: () => restoreDeletedValuesInNestedArray.create, set: undefined });
Object.defineProperty(obj, "diffAttributePayloads", { get: () => restoreDeletedValuesInNestedArray.diff, set: undefined });
Object.defineProperty(obj, "createPublicRootInstance", { get: () => createPublicRootInstance.createPublicRootInstance, set: undefined });
Object.defineProperty(obj, "createPublicInstance", { get: () => createPublicRootInstance.createPublicInstance, set: undefined });
Object.defineProperty(obj, "createPublicTextInstance", { get: () => createPublicRootInstance.createPublicTextInstance, set: undefined });
Object.defineProperty(obj, "getNativeTagFromPublicInstance", { get: () => createPublicRootInstance.getNativeTagFromPublicInstance, set: undefined });
Object.defineProperty(obj, "getNodeFromPublicInstance", { get: () => createPublicRootInstance.getNodeFromPublicInstance, set: undefined });
Object.defineProperty(obj, "getInternalInstanceHandleFromPublicInstance", { get: () => createPublicRootInstance.getInternalInstanceHandleFromPublicInstance, set: undefined });
Object.defineProperty(obj, "dispatchNativeEvent", { get: () => dispatchNativeEvent.default, set: undefined });

export default obj;