// _runtime/00676_debugSymbolicatorIntegration.js
import _mod677 from "metro/00677__.js";
import _mod865 from "metro/00865__.js";
import reactNativeErrorHandlersIntegration from "00881_reactNativeErrorHandlersIntegration.js";
import walkErrorTree from "00888_walkErrorTree.js";
import _mod975 from "metro/00975__.js";
import eventOriginIntegration from "00976_eventOriginIntegration.js";
import defaultSdkInfo from "00977_defaultSdkInfo.js";
import _mod979 from "metro/00979__.js";
import modulesLoaderIntegration from "00980_modulesLoaderIntegration.js";
import stopProfiling from "00981_stopProfiling.js";
import ANDROID_DEFAULT_BUNDLE_NAME from "00986_ANDROID_DEFAULT_BUNDLE_NAME.js";
import _mod990 from "metro/00990__.js";
import _mod991 from "metro/00991__.js";
import expoContextIntegration from "00992_expoContextIntegration.js";
import spotlightIntegration from "00993_spotlightIntegration.js";
import mobileReplayIntegrationNoop from "00994_mobileReplayIntegrationNoop.js";
import _getClientIntegration from "00998__getClientIntegration.js";
import browserReplayIntegrationNoop from "00999_browserReplayIntegrationNoop.js";
import init from "01000_init.js";
import _mod1017 from "metro/01017__.js";
import patchAppRegistryRunApplication from "01018_patchAppRegistryRunApplication.js";
import _mod1027 from "metro/01027__.js";
import stallTrackingIntegration from "01029_stallTrackingIntegration.js";
import userInteractionIntegration from "01030_userInteractionIntegration.js";
import timeToDisplayIntegration from "01032_timeToDisplayIntegration.js";
import _mod1035 from "metro/01035__.js";
import _mod1036 from "metro/01036__.js";
import logEnricherIntegration from "01038_logEnricherIntegration.js";
import graphqlIntegration from "01039_graphqlIntegration.js";
import supabaseIntegration from "01040_supabaseIntegration.js";

export const debugSymbolicatorIntegration = _mod677.debugSymbolicatorIntegration;
export const deviceContextIntegration = _mod865.deviceContextIntegration;
export const reactNativeErrorHandlersIntegration =
  reactNativeErrorHandlersIntegration.reactNativeErrorHandlersIntegration;
export const nativeLinkedErrorsIntegration = walkErrorTree.nativeLinkedErrorsIntegration;
export const nativeReleaseIntegration = _mod975.nativeReleaseIntegration;
export const eventOriginIntegration = eventOriginIntegration.eventOriginIntegration;
export const sdkInfoIntegration = defaultSdkInfo.sdkInfoIntegration;
export const reactNativeInfoIntegration = _mod979.reactNativeInfoIntegration;
export const modulesLoaderIntegration = modulesLoaderIntegration.modulesLoaderIntegration;
export const hermesProfilingIntegration = stopProfiling.hermesProfilingIntegration;
export const screenshotIntegration = _mod990.screenshotIntegration;
export const viewHierarchyIntegration = _mod991.viewHierarchyIntegration;
export const expoContextIntegration = expoContextIntegration.expoContextIntegration;
export const spotlightIntegration = spotlightIntegration.spotlightIntegration;
export const mobileReplayIntegration = mobileReplayIntegrationNoop.mobileReplayIntegration;
export const feedbackIntegration = _getClientIntegration.feedbackIntegration;
export const browserReplayIntegration = browserReplayIntegrationNoop.browserReplayIntegration;
export const appStartIntegration = _mod1017.appStartIntegration;
export const nativeFramesIntegration = _mod1027.nativeFramesIntegration;
export const createNativeFramesIntegrations = _mod1027.createNativeFramesIntegrations;
export const stallTrackingIntegration = stallTrackingIntegration.stallTrackingIntegration;
export const userInteractionIntegration = userInteractionIntegration.userInteractionIntegration;
export const createReactNativeRewriteFrames = ANDROID_DEFAULT_BUNDLE_NAME.createReactNativeRewriteFrames;
export const appRegistryIntegration = patchAppRegistryRunApplication.appRegistryIntegration;
export const timeToDisplayIntegration = timeToDisplayIntegration.timeToDisplayIntegration;
export const breadcrumbsIntegration = _mod1035.breadcrumbsIntegration;
export const primitiveTagIntegration = _mod1036.primitiveTagIntegration;
export const logEnricherIntegration = logEnricherIntegration.logEnricherIntegration;
export const graphqlIntegration = graphqlIntegration.graphqlIntegration;
export const supabaseIntegration = supabaseIntegration.supabaseIntegration;
export const browserApiErrorsIntegration = init.browserApiErrorsIntegration;
export const dedupeIntegration = init.dedupeIntegration;
export const functionToStringIntegration = init.functionToStringIntegration;
export const browserGlobalHandlersIntegration = init.globalHandlersIntegration;
export const httpClientIntegration = init.httpClientIntegration;
export const httpContextIntegration = init.httpContextIntegration;
export const inboundFiltersIntegration = init.inboundFiltersIntegration;
export const browserLinkedErrorsIntegration = init.linkedErrorsIntegration;
export const rewriteFramesIntegration = init.rewriteFramesIntegration;
export const extraErrorDataIntegration = init.extraErrorDataIntegration;
