// _runtime/00687_debugSymbolicatorIntegration.js
import _mod688 from "metro/00688__.js";
import deviceContextIntegration from "00876_deviceContextIntegration.js";
import reactNativeErrorHandlersIntegration from "00892_reactNativeErrorHandlersIntegration.js";
import nativeLinkedErrorsIntegration from "00899_nativeLinkedErrorsIntegration.js";
import nativeReleaseIntegration from "00986_nativeReleaseIntegration.js";
import eventOriginIntegration from "00987_eventOriginIntegration.js";
import defaultSdkInfo from "00988_defaultSdkInfo.js";
import reactNativeInfoIntegration from "00990_reactNativeInfoIntegration.js";
import modulesLoaderIntegration from "00991_modulesLoaderIntegration.js";
import hermesProfilingIntegration from "00992_hermesProfilingIntegration.js";
import ANDROID_DEFAULT_BUNDLE_NAME from "00997_ANDROID_DEFAULT_BUNDLE_NAME.js";
import screenshotIntegration from "01001_screenshotIntegration.js";
import viewHierarchyIntegration from "01002_viewHierarchyIntegration.js";
import OTA_UPDATES_CONTEXT_KEY from "01003_OTA_UPDATES_CONTEXT_KEY.js";
import spotlightIntegration from "01004_spotlightIntegration.js";
import MOBILE_REPLAY_INTEGRATION_NAME from "01005_MOBILE_REPLAY_INTEGRATION_NAME.js";
import MOBILE_FEEDBACK_INTEGRATION_NAME from "01009_MOBILE_FEEDBACK_INTEGRATION_NAME.js";
import browserReplayIntegration from "01010_browserReplayIntegration.js";
import init from "01011_init.js";
import captureAppStart from "01028_captureAppStart.js";
import _mod1029 from "metro/01029__.js";
import _mod1038 from "metro/01038__.js";
import stallTrackingIntegration from "01040_stallTrackingIntegration.js";
import userInteractionIntegration from "01041_userInteractionIntegration.js";
import _mod1043 from "metro/01043__.js";
import _mod1046 from "metro/01046__.js";
import _mod1047 from "metro/01047__.js";
import logEnricherIntegration from "01049_logEnricherIntegration.js";
import graphqlIntegration from "01050_graphqlIntegration.js";
import supabaseIntegration from "01051_supabaseIntegration.js";

const deviceContextIntegration_export = deviceContextIntegration.deviceContextIntegration;
const reactNativeErrorHandlersIntegration_export =
  reactNativeErrorHandlersIntegration.reactNativeErrorHandlersIntegration;
const nativeLinkedErrorsIntegration_export = nativeLinkedErrorsIntegration.nativeLinkedErrorsIntegration;
const nativeReleaseIntegration_export = nativeReleaseIntegration.nativeReleaseIntegration;
const eventOriginIntegration_export = eventOriginIntegration.eventOriginIntegration;
const reactNativeInfoIntegration_export = reactNativeInfoIntegration.reactNativeInfoIntegration;
const modulesLoaderIntegration_export = modulesLoaderIntegration.modulesLoaderIntegration;
const hermesProfilingIntegration_export = hermesProfilingIntegration.hermesProfilingIntegration;
const screenshotIntegration_export = screenshotIntegration.screenshotIntegration;
const viewHierarchyIntegration_export = viewHierarchyIntegration.viewHierarchyIntegration;
const spotlightIntegration_export = spotlightIntegration.spotlightIntegration;
const browserReplayIntegration_export = browserReplayIntegration.browserReplayIntegration;
const stallTrackingIntegration_export = stallTrackingIntegration.stallTrackingIntegration;
const userInteractionIntegration_export = userInteractionIntegration.userInteractionIntegration;
const logEnricherIntegration_export = logEnricherIntegration.logEnricherIntegration;
const graphqlIntegration_export = graphqlIntegration.graphqlIntegration;
const supabaseIntegration_export = supabaseIntegration.supabaseIntegration;

export const debugSymbolicatorIntegration = _mod688.debugSymbolicatorIntegration;
export { deviceContextIntegration_export as deviceContextIntegration };
export { reactNativeErrorHandlersIntegration_export as reactNativeErrorHandlersIntegration };
export { nativeLinkedErrorsIntegration_export as nativeLinkedErrorsIntegration };
export { nativeReleaseIntegration_export as nativeReleaseIntegration };
export { eventOriginIntegration_export as eventOriginIntegration };
export const sdkInfoIntegration = defaultSdkInfo.sdkInfoIntegration;
export { reactNativeInfoIntegration_export as reactNativeInfoIntegration };
export { modulesLoaderIntegration_export as modulesLoaderIntegration };
export { hermesProfilingIntegration_export as hermesProfilingIntegration };
export { screenshotIntegration_export as screenshotIntegration };
export { viewHierarchyIntegration_export as viewHierarchyIntegration };
export const expoContextIntegration = OTA_UPDATES_CONTEXT_KEY.expoContextIntegration;
export { spotlightIntegration_export as spotlightIntegration };
export const mobileReplayIntegration = MOBILE_REPLAY_INTEGRATION_NAME.mobileReplayIntegration;
export const feedbackIntegration = MOBILE_FEEDBACK_INTEGRATION_NAME.feedbackIntegration;
export { browserReplayIntegration_export as browserReplayIntegration };
export const appStartIntegration = captureAppStart.appStartIntegration;
export const nativeFramesIntegration = _mod1038.nativeFramesIntegration;
export const createNativeFramesIntegrations = _mod1038.createNativeFramesIntegrations;
export { stallTrackingIntegration_export as stallTrackingIntegration };
export { userInteractionIntegration_export as userInteractionIntegration };
export const createReactNativeRewriteFrames = ANDROID_DEFAULT_BUNDLE_NAME.createReactNativeRewriteFrames;
export const appRegistryIntegration = _mod1029.appRegistryIntegration;
export const timeToDisplayIntegration = _mod1043.timeToDisplayIntegration;
export const breadcrumbsIntegration = _mod1046.breadcrumbsIntegration;
export const primitiveTagIntegration = _mod1047.primitiveTagIntegration;
export { logEnricherIntegration_export as logEnricherIntegration };
export { graphqlIntegration_export as graphqlIntegration };
export { supabaseIntegration_export as supabaseIntegration };
export const browserApiErrorsIntegration = init.browserApiErrorsIntegration;
export const dedupeIntegration = init.dedupeIntegration;
export const functionToStringIntegration = init.functionToStringIntegration;
export const browserGlobalHandlersIntegration = init.globalHandlersIntegration;
export const httpClientIntegration = init.httpClientIntegration;
export const httpContextIntegration = init.httpContextIntegration;
export const inboundFiltersIntegration = init.inboundFiltersIntegration;
export const browserLinkedErrorsIntegration = init.linkedErrorsIntegration;
export const rewriteFramesIntegration = init.rewriteFramesIntegration;
export const extraErrorDataIntegration = init.extraErrorDataIntegration;
