// _runtime/00808_debugSymbolicatorIntegration.js
import processEvent from "00809_processEvent.js";
import processEvent2 from "00997_processEvent.js";
import reactNativeErrorHandlersIntegration from "01013_reactNativeErrorHandlersIntegration.js";
import walkErrorTree from "01020_walkErrorTree.js";
import processEvent3 from "01107_processEvent.js";
import eventOriginIntegration from "01108_eventOriginIntegration.js";
import items from "01109_items.js";
import processEvent4 from "01111_processEvent.js";
import modulesLoaderIntegration from "01112_modulesLoaderIntegration.js";
import stopProfiling from "01113_stopProfiling.js";
import ANDROID_DEFAULT_BUNDLE_NAME from "01118_ANDROID_DEFAULT_BUNDLE_NAME.js";
import processEvent5 from "01122_processEvent.js";
import processEvent6 from "01123_processEvent.js";
import getExpoUpdatesContext from "01124_getExpoUpdatesContext.js";
import getDefaultSidecarUrl from "01125_getDefaultSidecarUrl.js";
import mobileReplayIntegrationNoop from "01126_mobileReplayIntegrationNoop.js";
import _getClientIntegration from "01130__getClientIntegration.js";
import browserReplayIntegrationNoop from "01131_browserReplayIntegrationNoop.js";
import init from "01132_init.js";
import setSpanDurationAsMeasurementOnTransactionEvent from "01149_setSpanDurationAsMeasurementOnTransactionEvent.js";
import patchAppRegistryRunApplication from "01150_patchAppRegistryRunApplication.js";
import fetchNativeFrames from "01159_fetchNativeFrames.js";
import stallTrackingIntegration from "01161_stallTrackingIntegration.js";
import userInteractionIntegration from "01162_userInteractionIntegration.js";
import isDeadlineExceeded from "01164_isDeadlineExceeded.js";
import breadcrumbsIntegration from "01167_breadcrumbsIntegration.js";
import primitiveTagIntegration from "01168_primitiveTagIntegration.js";
import logEnricherIntegration from "01170_logEnricherIntegration.js";
import graphqlIntegration from "01171_graphqlIntegration.js";
import supabaseIntegration from "01172_supabaseIntegration.js";

export const debugSymbolicatorIntegration = processEvent.debugSymbolicatorIntegration;
export const deviceContextIntegration = processEvent2.deviceContextIntegration;
export const reactNativeErrorHandlersIntegration =
  reactNativeErrorHandlersIntegration.reactNativeErrorHandlersIntegration;
export const nativeLinkedErrorsIntegration = walkErrorTree.nativeLinkedErrorsIntegration;
export const nativeReleaseIntegration = processEvent3.nativeReleaseIntegration;
export const eventOriginIntegration = eventOriginIntegration.eventOriginIntegration;
export const sdkInfoIntegration = items.sdkInfoIntegration;
export const reactNativeInfoIntegration = processEvent4.reactNativeInfoIntegration;
export const modulesLoaderIntegration = modulesLoaderIntegration.modulesLoaderIntegration;
export const hermesProfilingIntegration = stopProfiling.hermesProfilingIntegration;
export const screenshotIntegration = processEvent5.screenshotIntegration;
export const viewHierarchyIntegration = processEvent6.viewHierarchyIntegration;
export const expoContextIntegration = getExpoUpdatesContext.expoContextIntegration;
export const spotlightIntegration = getDefaultSidecarUrl.spotlightIntegration;
export const mobileReplayIntegration = mobileReplayIntegrationNoop.mobileReplayIntegration;
export const feedbackIntegration = _getClientIntegration.feedbackIntegration;
export const browserReplayIntegration = browserReplayIntegrationNoop.browserReplayIntegration;
export const appStartIntegration = setSpanDurationAsMeasurementOnTransactionEvent.appStartIntegration;
export const nativeFramesIntegration = fetchNativeFrames.nativeFramesIntegration;
export const createNativeFramesIntegrations = fetchNativeFrames.createNativeFramesIntegrations;
export const stallTrackingIntegration = stallTrackingIntegration.stallTrackingIntegration;
export const userInteractionIntegration = userInteractionIntegration.userInteractionIntegration;
export const createReactNativeRewriteFrames = ANDROID_DEFAULT_BUNDLE_NAME.createReactNativeRewriteFrames;
export const appRegistryIntegration = patchAppRegistryRunApplication.appRegistryIntegration;
export const timeToDisplayIntegration = isDeadlineExceeded.timeToDisplayIntegration;
export const breadcrumbsIntegration = breadcrumbsIntegration.breadcrumbsIntegration;
export const primitiveTagIntegration = primitiveTagIntegration.primitiveTagIntegration;
export const logEnricherIntegration = logEnricherIntegration.logEnricherIntegration;
export const graphqlIntegration = graphqlIntegration.graphqlIntegration;
export const supabaseIntegration = supabaseIntegration.supabaseIntegration;
export const browserApiErrorsIntegration = init.browserApiErrorsIntegration;
export const dedupeIntegration = init.dedupeIntegration;
export const functionToStringIntegration = init.functionToStringIntegration;
export const browserGlobalHandlersIntegration = init.globalHandlersIntegration;
export const httpClientIntegration = init.httpClientIntegration;
export const httpContextIntegration = init.httpContextIntegration;
export const inboundFiltersIntegration = init.inboundFiltersIntegration;
export const browserLinkedErrorsIntegration = init.linkedErrorsIntegration;
export const rewriteFramesIntegration = init.rewriteFramesIntegration;
export const extraErrorDataIntegration = init.extraErrorDataIntegration;
