// _runtime/00817_registerSpanErrorInstrumentation.js
import registerSpanErrorInstrumentation from "00818_registerSpanErrorInstrumentation.js";
import spanToJSON from "00819_spanToJSON.js";
import unwrapScopeFromWeakRef from "00820_unwrapScopeFromWeakRef.js";
import _mod821 from "metro/00821__.js";
import addNonEnumerableProperty from "00822_addNonEnumerableProperty.js";
import consoleSandbox from "00824_consoleSandbox.js";
import getGlobalSingleton from "00825_getGlobalSingleton.js";
import _mod826 from "metro/00826__.js";
import isInstanceOf from "00827_isInstanceOf.js";
import _htmlElementAsString from "00828__htmlElementAsString.js";
import generateSpanId from "00829_generateSpanId.js";
import addContextToFrame from "00830_addContextToFrame.js";
import safeDateNow from "00831_safeDateNow.js";
import isMatchingPattern from "00832_isMatchingPattern.js";
import createStackParser from "00833_createStackParser.js";
import regExp from "00834_regExp.js";
import baggageHeaderToDynamicSamplingContext from "00835_baggageHeaderToDynamicSamplingContext.js";
import parseSampleRate from "00836_parseSampleRate.js";
import dsnFromString from "00837_dsnFromString.js";
import dateTimestampInSeconds from "00838_dateTimestampInSeconds.js";
import _mod839 from "metro/00839__.js";
import getSpanStatusFromHttpCode from "00840_getSpanStatusFromHttpCode.js";
import getAsyncContextStrategy from "00841_getAsyncContextStrategy.js";
import Scope from "00843_Scope.js";
import _getSpanForScope from "00844__getSpanForScope.js";
import updateSession from "00845_updateSession.js";
import getDefaultCurrentScope from "00847_getDefaultCurrentScope.js";
import getClient from "00848_getClient.js";
import instrumentError from "00849_instrumentError.js";
import addHandler from "00850_addHandler.js";
import instrumentUnhandledRejection from "00851_instrumentUnhandledRejection.js";
import TRACING_DEFAULTS from "00852_TRACING_DEFAULTS.js";
import hasSpansEnabled from "00855_hasSpansEnabled.js";
import SentryNonRecordingSpan from "00856_SentryNonRecordingSpan.js";
import getDynamicSamplingContextFromSpan from "00857_getDynamicSamplingContextFromSpan.js";
import _mod858 from "metro/00858__.js";
import isFullFinishedSpan from "00860_isFullFinishedSpan.js";
import logSpanEnd from "00861_logSpanEnd.js";
import setMeasurement from "00862_setMeasurement.js";
import _enhanceEventWithSdkInfo from "00863__enhanceEventWithSdkInfo.js";
import forEachEnvelopeItem from "00864_forEachEnvelopeItem.js";
import normalize from "00865_normalize.js";
import createChildOrRootSpan from "00866_createChildOrRootSpan.js";
import handleCallbackErrors from "00867_handleCallbackErrors.js";
import sampleSpan from "00868_sampleSpan.js";
import captureCheckIn from "00869_captureCheckIn.js";
import applyClientOptions from "00870_applyClientOptions.js";
import mergeScopeData from "00871_mergeScopeData.js";
import _notifyEventProcessors from "00872__notifyEventProcessors.js";
import SyncPromise from "00873_SyncPromise.js";
import getFilenameToDebugIdMap from "00874_getFilenameToDebugIdMap.js";
import getEnvelopeEndpointWithUrlEncodedAuth from "00875_getEnvelopeEndpointWithUrlEncodedAuth.js";
import isErrorEvent from "00876_isErrorEvent.js";
import makePromiseBuffer from "00877_makePromiseBuffer.js";
import createTransport from "00878_createTransport.js";
import parseRetryAfterHeader from "00879_parseRetryAfterHeader.js";
import _INTERNAL_captureSerializedLog from "00880__INTERNAL_captureSerializedLog.js";
import _INTERNAL_captureSerializedMetric from "00885__INTERNAL_captureSerializedMetric.js";
import setupIntegration from "00887_setupIntegration.js";
import createClientReportEnvelope from "00889_createClientReportEnvelope.js";
import _isNativeReflectConstruct from "00891__isNativeReflectConstruct.js";
import exceptionFromError from "00893_exceptionFromError.js";
import createCheckInEnvelope from "00894_createCheckInEnvelope.js";
import initAndBind from "00895_initAndBind.js";
import MIN_DELAY from "00896_MIN_DELAY.js";
import eventFromEnvelope from "00897_eventFromEnvelope.js";
import set from "00898_set.js";
import isSentryRequestUrl from "00899_isSentryRequestUrl.js";
import getHttpSpanDetailsFromUrlObject from "00900_getHttpSpanDetailsFromUrlObject.js";
import parameterize from "00901_parameterize.js";
import addAutoIpAddressToSession from "00902_addAutoIpAddressToSession.js";
import applySdkMetadata from "00903_applySdkMetadata.js";
import getTraceData from "00904_getTraceData.js";
import getTraceMetaTags from "00905_getTraceMetaTags.js";
import debounce from "00906_debounce.js";
import winterCGHeadersToDict from "00907_winterCGHeadersToDict.js";
import addBreadcrumb from "00908_addBreadcrumb.js";
import weakMap from "00909_weakMap.js";
import _mergeOptions from "00910__mergeOptions.js";
import linkedErrorsIntegration from "00911_linkedErrorsIntegration.js";
import aggregateExceptionsFromError from "00912_aggregateExceptionsFromError.js";
import moduleMetadataIntegration from "00913_moduleMetadataIntegration.js";
import map from "00914_map.js";
import requestDataIntegration from "00915_requestDataIntegration.js";
import captureConsoleIntegration from "00918_captureConsoleIntegration.js";
import instrumentConsole from "00919_instrumentConsole.js";
import severityLevelFromString from "00920_severityLevelFromString.js";
import _shouldDropEvent from "00921__shouldDropEvent.js";
import _extractErrorData from "00922__extractErrorData.js";
import generateIteratee from "00923_generateIteratee.js";
import resolve from "00924_resolve.js";
import markAsInstrumented from "00925_markAsInstrumented.js";
import flattenIssue from "00926_flattenIssue.js";
import thirdPartyErrorFilterIntegration from "00927_thirdPartyErrorFilterIntegration.js";
import addConsoleBreadcrumb from "00928_addConsoleBreadcrumb.js";
import featureFlagsIntegration from "00929_featureFlagsIntegration.js";
import _INTERNAL_addFeatureFlagToActiveSpan from "00930__INTERNAL_addFeatureFlagToActiveSpan.js";
import growthbookIntegration from "00931_growthbookIntegration.js";
import _mod932 from "metro/00932__.js";
import _addTracingHeadersToFetchRequest from "metro/00933__addTracingHeadersToFetchRequest.js";
import trpcMiddleware from "00934_trpcMiddleware.js";
import weakSet from "00935_weakSet.js";
import captureFeedback from "00949_captureFeedback.js";
import fmt from "00950_fmt.js";
import consoleLoggingIntegration from "00951_consoleLoggingIntegration.js";
import count from "00953_count.js";
import createConsolaReporter from "00954_createConsolaReporter.js";
import onVercelAiSpanStart from "00955_onVercelAiSpanStart.js";
import convertPromptToMessages from "00957_convertPromptToMessages.js";
import extractRequestAttributes from "00962_extractRequestAttributes.js";
import items from "00964_items.js";
import addPrivateRequestAttributes from "00969_addPrivateRequestAttributes.js";
import _mod971 from "metro/00971__.js";
import addPrivateRequestAttributes2 from "00973_addPrivateRequestAttributes.js";
import _mod974 from "metro/00974__.js";
import createLangChainCallbackHandler from "00977_createLangChainCallbackHandler.js";
import _mod979 from "metro/00979__.js";
import instrumentLangGraph from "00980_instrumentLangGraph.js";
import _mod981 from "metro/00981__.js";
import getBreadcrumbLogLevelFromHttpStatusCode from "00983_getBreadcrumbLogLevelFromHttpStatusCode.js";
import _isNativeReflectConstruct2 from "00984__isNativeReflectConstruct.js";
import _resolveResponse from "00985__resolveResponse.js";
import _isFetchSupported from "00986__isFetchSupported.js";
import isBrowser from "00987_isBrowser.js";
import dynamicRequire from "00988_dynamicRequire.js";
import getSDKSource from "00989_getSDKSource.js";
import replaceExports from "00990_replaceExports.js";
import filenameIsInApp from "00991_filenameIsInApp.js";
import callFrameToStackFrame from "00992_callFrameToStackFrame.js";
import LRUMap from "00993_LRUMap.js";
import vercelWaitUntil from "00994_vercelWaitUntil.js";
import flushWithTimeout from "00995_flushWithTimeout.js";
import escapeStringForRegex from "00996_escapeStringForRegex.js";

Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });

export const registerSpanErrorInstrumentation = registerSpanErrorInstrumentation.registerSpanErrorInstrumentation;
export const getCapturedScopesOnSpan = unwrapScopeFromWeakRef.getCapturedScopesOnSpan;
export const setCapturedScopesOnSpan = unwrapScopeFromWeakRef.setCapturedScopesOnSpan;
export const TRACING_DEFAULTS = TRACING_DEFAULTS.TRACING_DEFAULTS;
export const startIdleSpan = TRACING_DEFAULTS.startIdleSpan;
export const SentrySpan = isFullFinishedSpan.SentrySpan;
export const SentryNonRecordingSpan = SentryNonRecordingSpan.SentryNonRecordingSpan;
export const SPAN_STATUS_ERROR = getSpanStatusFromHttpCode.SPAN_STATUS_ERROR;
export const SPAN_STATUS_OK = getSpanStatusFromHttpCode.SPAN_STATUS_OK;
export const SPAN_STATUS_UNSET = getSpanStatusFromHttpCode.SPAN_STATUS_UNSET;
export const getSpanStatusFromHttpCode = getSpanStatusFromHttpCode.getSpanStatusFromHttpCode;
export const setHttpStatus = getSpanStatusFromHttpCode.setHttpStatus;
export const continueTrace = createChildOrRootSpan.continueTrace;
export const startInactiveSpan = createChildOrRootSpan.startInactiveSpan;
export const startNewTrace = createChildOrRootSpan.startNewTrace;
export const startSpan = createChildOrRootSpan.startSpan;
export const startSpanManual = createChildOrRootSpan.startSpanManual;
export const suppressTracing = createChildOrRootSpan.suppressTracing;
export const withActiveSpan = createChildOrRootSpan.withActiveSpan;
export const getDynamicSamplingContextFromClient = getDynamicSamplingContextFromSpan.getDynamicSamplingContextFromClient;
export const getDynamicSamplingContextFromScope = getDynamicSamplingContextFromSpan.getDynamicSamplingContextFromScope;
export const getDynamicSamplingContextFromSpan = getDynamicSamplingContextFromSpan.getDynamicSamplingContextFromSpan;
export const spanToBaggageHeader = getDynamicSamplingContextFromSpan.spanToBaggageHeader;
export const setMeasurement = setMeasurement.setMeasurement;
export const timedEventsToMeasurements = setMeasurement.timedEventsToMeasurements;
export const sampleSpan = sampleSpan.sampleSpan;
export const logSpanEnd = logSpanEnd.logSpanEnd;
export const logSpanStart = logSpanEnd.logSpanStart;
export const SEMANTIC_ATTRIBUTE_CACHE_HIT = _mod839.SEMANTIC_ATTRIBUTE_CACHE_HIT;
export const SEMANTIC_ATTRIBUTE_CACHE_ITEM_SIZE = _mod839.SEMANTIC_ATTRIBUTE_CACHE_ITEM_SIZE;
export const SEMANTIC_ATTRIBUTE_CACHE_KEY = _mod839.SEMANTIC_ATTRIBUTE_CACHE_KEY;
export const SEMANTIC_ATTRIBUTE_EXCLUSIVE_TIME = _mod839.SEMANTIC_ATTRIBUTE_EXCLUSIVE_TIME;
export const SEMANTIC_ATTRIBUTE_HTTP_REQUEST_METHOD = _mod839.SEMANTIC_ATTRIBUTE_HTTP_REQUEST_METHOD;
export const SEMANTIC_ATTRIBUTE_PROFILE_ID = _mod839.SEMANTIC_ATTRIBUTE_PROFILE_ID;
export const SEMANTIC_ATTRIBUTE_SENTRY_CUSTOM_SPAN_NAME = _mod839.SEMANTIC_ATTRIBUTE_SENTRY_CUSTOM_SPAN_NAME;
export const SEMANTIC_ATTRIBUTE_SENTRY_IDLE_SPAN_FINISH_REASON = _mod839.SEMANTIC_ATTRIBUTE_SENTRY_IDLE_SPAN_FINISH_REASON;
export const SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_UNIT = _mod839.SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_UNIT;
export const SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_VALUE = _mod839.SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_VALUE;
export const SEMANTIC_ATTRIBUTE_SENTRY_OP = _mod839.SEMANTIC_ATTRIBUTE_SENTRY_OP;
export const SEMANTIC_ATTRIBUTE_SENTRY_ORIGIN = _mod839.SEMANTIC_ATTRIBUTE_SENTRY_ORIGIN;
export const SEMANTIC_ATTRIBUTE_SENTRY_PREVIOUS_TRACE_SAMPLE_RATE = _mod839.SEMANTIC_ATTRIBUTE_SENTRY_PREVIOUS_TRACE_SAMPLE_RATE;
export const SEMANTIC_ATTRIBUTE_SENTRY_SAMPLE_RATE = _mod839.SEMANTIC_ATTRIBUTE_SENTRY_SAMPLE_RATE;
export const SEMANTIC_ATTRIBUTE_SENTRY_SOURCE = _mod839.SEMANTIC_ATTRIBUTE_SENTRY_SOURCE;
export const SEMANTIC_ATTRIBUTE_URL_FULL = _mod839.SEMANTIC_ATTRIBUTE_URL_FULL;
export const SEMANTIC_LINK_ATTRIBUTE_LINK_TYPE = _mod839.SEMANTIC_LINK_ATTRIBUTE_LINK_TYPE;
export const createEventEnvelope = _enhanceEventWithSdkInfo.createEventEnvelope;
export const createSessionEnvelope = _enhanceEventWithSdkInfo.createSessionEnvelope;
export const createSpanEnvelope = _enhanceEventWithSdkInfo.createSpanEnvelope;
export const addEventProcessor = captureCheckIn.addEventProcessor;
export const captureCheckIn = captureCheckIn.captureCheckIn;
export const captureEvent = captureCheckIn.captureEvent;
export const captureException = captureCheckIn.captureException;
export const captureMessage = captureCheckIn.captureMessage;
export const captureSession = captureCheckIn.captureSession;
export const close = captureCheckIn.close;
export const endSession = captureCheckIn.endSession;
export const flush = captureCheckIn.flush;
export const isEnabled = captureCheckIn.isEnabled;
export const isInitialized = captureCheckIn.isInitialized;
export const lastEventId = captureCheckIn.lastEventId;
export const setContext = captureCheckIn.setContext;
export const setExtra = captureCheckIn.setExtra;
export const setExtras = captureCheckIn.setExtras;
export const setTag = captureCheckIn.setTag;
export const setTags = captureCheckIn.setTags;
export const setUser = captureCheckIn.setUser;
export const startSession = captureCheckIn.startSession;
export const withMonitor = captureCheckIn.withMonitor;
export const getClient = getClient.getClient;
export const getCurrentScope = getClient.getCurrentScope;
export const getGlobalScope = getClient.getGlobalScope;
export const getIsolationScope = getClient.getIsolationScope;
export const getTraceContextFromScope = getClient.getTraceContextFromScope;
export const withIsolationScope = getClient.withIsolationScope;
export const withScope = getClient.withScope;
export const getDefaultCurrentScope = getDefaultCurrentScope.getDefaultCurrentScope;
export const getDefaultIsolationScope = getDefaultCurrentScope.getDefaultIsolationScope;
export const setAsyncContextStrategy = getAsyncContextStrategy.setAsyncContextStrategy;
export const getGlobalSingleton = getGlobalSingleton.getGlobalSingleton;
export const getMainCarrier = getGlobalSingleton.getMainCarrier;
export const closeSession = updateSession.closeSession;
export const makeSession = updateSession.makeSession;
export const updateSession = updateSession.updateSession;
export const Scope = Scope.Scope;
export const notifyEventProcessors = _notifyEventProcessors.notifyEventProcessors;
export const getEnvelopeEndpointWithUrlEncodedAuth = getEnvelopeEndpointWithUrlEncodedAuth.getEnvelopeEndpointWithUrlEncodedAuth;
export const getReportDialogEndpoint = getEnvelopeEndpointWithUrlEncodedAuth.getReportDialogEndpoint;
export const Client = isErrorEvent.Client;
export const ServerRuntimeClient = _isNativeReflectConstruct.ServerRuntimeClient;
export const initAndBind = initAndBind.initAndBind;
export const setCurrentClient = initAndBind.setCurrentClient;
export const createTransport = createTransport.createTransport;
export const makeOfflineTransport = MIN_DELAY.makeOfflineTransport;
export const MULTIPLEXED_TRANSPORT_EXTRA_KEY = eventFromEnvelope.MULTIPLEXED_TRANSPORT_EXTRA_KEY;
export const makeMultiplexedTransport = eventFromEnvelope.makeMultiplexedTransport;
export const addIntegration = setupIntegration.addIntegration;
export const defineIntegration = setupIntegration.defineIntegration;
export const getIntegrationsToSetup = setupIntegration.getIntegrationsToSetup;
export const installedIntegrations = setupIntegration.installedIntegrations;
export const _INTERNAL_clearAiProviderSkips = set._INTERNAL_clearAiProviderSkips;
export const _INTERNAL_shouldSkipAiProviderWrapping = set._INTERNAL_shouldSkipAiProviderWrapping;
export const _INTERNAL_skipAiProviderWrapping = set._INTERNAL_skipAiProviderWrapping;
export const applyScopeDataToEvent = mergeScopeData.applyScopeDataToEvent;
export const getCombinedScopeData = mergeScopeData.getCombinedScopeData;
export const mergeScopeData = mergeScopeData.mergeScopeData;
export const prepareEvent = applyClientOptions.prepareEvent;
export const createCheckInEnvelope = createCheckInEnvelope.createCheckInEnvelope;
export const hasSpansEnabled = hasSpansEnabled.hasSpansEnabled;
export const isSentryRequestUrl = isSentryRequestUrl.isSentryRequestUrl;
export const handleCallbackErrors = handleCallbackErrors.handleCallbackErrors;
export const fmt = parameterize.fmt;
export const parameterize = parameterize.parameterize;
export const addAutoIpAddressToSession = addAutoIpAddressToSession.addAutoIpAddressToSession;
export const addAutoIpAddressToUser = addAutoIpAddressToSession.addAutoIpAddressToUser;
export const addChildSpanToSpan = spanToJSON.addChildSpanToSpan;
export const convertSpanLinksForEnvelope = spanToJSON.convertSpanLinksForEnvelope;
export const getActiveSpan = spanToJSON.getActiveSpan;
export const getRootSpan = spanToJSON.getRootSpan;
export const getSpanDescendants = spanToJSON.getSpanDescendants;
export const getStatusMessage = spanToJSON.getStatusMessage;
export const spanIsSampled = spanToJSON.spanIsSampled;
export const spanTimeInputToSeconds = spanToJSON.spanTimeInputToSeconds;
export const spanToJSON = spanToJSON.spanToJSON;
export const spanToTraceContext = spanToJSON.spanToTraceContext;
export const spanToTraceHeader = spanToJSON.spanToTraceHeader;
export const updateSpanName = spanToJSON.updateSpanName;
export const _INTERNAL_setSpanForScope = _getSpanForScope._setSpanForScope;
export const parseSampleRate = parseSampleRate.parseSampleRate;
export const applySdkMetadata = applySdkMetadata.applySdkMetadata;
export const getTraceData = getTraceData.getTraceData;
export const getTraceMetaTags = getTraceMetaTags.getTraceMetaTags;
export const debounce = debounce.debounce;
export const extractQueryParamsFromUrl = winterCGHeadersToDict.extractQueryParamsFromUrl;
export const headersToDict = winterCGHeadersToDict.headersToDict;
export const httpHeadersToSpanAttributes = winterCGHeadersToDict.httpHeadersToSpanAttributes;
export const httpRequestToRequestData = winterCGHeadersToDict.httpRequestToRequestData;
export const winterCGHeadersToDict = winterCGHeadersToDict.winterCGHeadersToDict;
export const winterCGRequestToRequestData = winterCGHeadersToDict.winterCGRequestToRequestData;
export const DEFAULT_ENVIRONMENT = _mod858.DEFAULT_ENVIRONMENT;
export const DEV_ENVIRONMENT = _mod858.DEV_ENVIRONMENT;
export const addBreadcrumb = addBreadcrumb.addBreadcrumb;
export const functionToStringIntegration = weakMap.functionToStringIntegration;
export const eventFiltersIntegration = _mergeOptions.eventFiltersIntegration;
export const inboundFiltersIntegration = _mergeOptions.inboundFiltersIntegration;
export const linkedErrorsIntegration = linkedErrorsIntegration.linkedErrorsIntegration;
export const moduleMetadataIntegration = moduleMetadataIntegration.moduleMetadataIntegration;
export const requestDataIntegration = requestDataIntegration.requestDataIntegration;
export const captureConsoleIntegration = captureConsoleIntegration.captureConsoleIntegration;
export const dedupeIntegration = _shouldDropEvent.dedupeIntegration;
export const extraErrorDataIntegration = _extractErrorData.extraErrorDataIntegration;
export const rewriteFramesIntegration = generateIteratee.rewriteFramesIntegration;
export const instrumentSupabaseClient = markAsInstrumented.instrumentSupabaseClient;
export const supabaseIntegration = markAsInstrumented.supabaseIntegration;
export const zodErrorsIntegration = flattenIssue.zodErrorsIntegration;
export const thirdPartyErrorFilterIntegration = thirdPartyErrorFilterIntegration.thirdPartyErrorFilterIntegration;
export const consoleIntegration = addConsoleBreadcrumb.consoleIntegration;
export const featureFlagsIntegration = featureFlagsIntegration.featureFlagsIntegration;
export const growthbookIntegration = growthbookIntegration.growthbookIntegration;
export const profiler = _mod932.profiler;
export const instrumentFetchRequest = _addTracingHeadersToFetchRequest.instrumentFetchRequest;
export const trpcMiddleware = trpcMiddleware.trpcMiddleware;
export const wrapMcpServerWithSentry = weakSet.wrapMcpServerWithSentry;
export const captureFeedback = captureFeedback.captureFeedback;
export const _INTERNAL_captureLog = _INTERNAL_captureSerializedLog._INTERNAL_captureLog;
export const _INTERNAL_captureSerializedLog = _INTERNAL_captureSerializedLog._INTERNAL_captureSerializedLog;
export const _INTERNAL_flushLogsBuffer = _INTERNAL_captureSerializedLog._INTERNAL_flushLogsBuffer;
export const logger = fmt;
export const consoleLoggingIntegration = consoleLoggingIntegration.consoleLoggingIntegration;
export const _INTERNAL_captureMetric = _INTERNAL_captureSerializedMetric._INTERNAL_captureMetric;
export const _INTERNAL_captureSerializedMetric = _INTERNAL_captureSerializedMetric._INTERNAL_captureSerializedMetric;
export const _INTERNAL_flushMetricsBuffer = _INTERNAL_captureSerializedMetric._INTERNAL_flushMetricsBuffer;
export const metrics = count;
export const createConsolaReporter = createConsolaReporter.createConsolaReporter;
export const addVercelAiProcessors = onVercelAiSpanStart.addVercelAiProcessors;
export const _INTERNAL_cleanupToolCallSpan = convertPromptToMessages._INTERNAL_cleanupToolCallSpan;
export const _INTERNAL_getSpanForToolCallId = convertPromptToMessages._INTERNAL_getSpanForToolCallId;
export const instrumentOpenAiClient = extractRequestAttributes.instrumentOpenAiClient;
export const OPENAI_INTEGRATION_NAME = items.OPENAI_INTEGRATION_NAME;
export const instrumentAnthropicAiClient = addPrivateRequestAttributes.instrumentAnthropicAiClient;
export const ANTHROPIC_AI_INTEGRATION_NAME = _mod971.ANTHROPIC_AI_INTEGRATION_NAME;
export const instrumentGoogleGenAIClient = addPrivateRequestAttributes2.instrumentGoogleGenAIClient;
export const GOOGLE_GENAI_INTEGRATION_NAME = _mod974.GOOGLE_GENAI_INTEGRATION_NAME;
export const createLangChainCallbackHandler = createLangChainCallbackHandler.createLangChainCallbackHandler;
export const LANGCHAIN_INTEGRATION_NAME = _mod979.LANGCHAIN_INTEGRATION_NAME;
export const instrumentLangGraph = instrumentLangGraph.instrumentLangGraph;
export const instrumentStateGraphCompile = instrumentLangGraph.instrumentStateGraphCompile;
export const LANGGRAPH_INTEGRATION_NAME = _mod981.LANGGRAPH_INTEGRATION_NAME;
export const _INTERNAL_FLAG_BUFFER_SIZE = _INTERNAL_addFeatureFlagToActiveSpan._INTERNAL_FLAG_BUFFER_SIZE;
export const _INTERNAL_MAX_FLAGS_PER_SPAN = _INTERNAL_addFeatureFlagToActiveSpan._INTERNAL_MAX_FLAGS_PER_SPAN;
export const _INTERNAL_addFeatureFlagToActiveSpan = _INTERNAL_addFeatureFlagToActiveSpan._INTERNAL_addFeatureFlagToActiveSpan;
export const _INTERNAL_copyFlagsFromScopeToEvent = _INTERNAL_addFeatureFlagToActiveSpan._INTERNAL_copyFlagsFromScopeToEvent;
export const _INTERNAL_insertFlagToScope = _INTERNAL_addFeatureFlagToActiveSpan._INTERNAL_insertFlagToScope;
export const applyAggregateErrorsToEvent = aggregateExceptionsFromError.applyAggregateErrorsToEvent;
export const getBreadcrumbLogLevelFromHttpStatusCode = getBreadcrumbLogLevelFromHttpStatusCode.getBreadcrumbLogLevelFromHttpStatusCode;
export const getComponentName = _htmlElementAsString.getComponentName;
export const getLocationHref = _htmlElementAsString.getLocationHref;
export const htmlTreeAsString = _htmlElementAsString.htmlTreeAsString;
export const dsnFromString = dsnFromString.dsnFromString;
export const dsnToString = dsnFromString.dsnToString;
export const makeDsn = dsnFromString.makeDsn;
export const SentryError = _isNativeReflectConstruct2.SentryError;
export const GLOBAL_OBJ = _mod821.GLOBAL_OBJ;
export const addConsoleInstrumentationHandler = instrumentConsole.addConsoleInstrumentationHandler;
export const addFetchEndInstrumentationHandler = _resolveResponse.addFetchEndInstrumentationHandler;
export const addFetchInstrumentationHandler = _resolveResponse.addFetchInstrumentationHandler;
export const addGlobalErrorInstrumentationHandler = instrumentError.addGlobalErrorInstrumentationHandler;
export const addGlobalUnhandledRejectionInstrumentationHandler = instrumentUnhandledRejection.addGlobalUnhandledRejectionInstrumentationHandler;
export const addHandler = addHandler.addHandler;
export const maybeInstrument = addHandler.maybeInstrument;
export const resetInstrumentationHandlers = addHandler.resetInstrumentationHandlers;
export const triggerHandlers = addHandler.triggerHandlers;
export const isDOMError = isInstanceOf.isDOMError;
export const isDOMException = isInstanceOf.isDOMException;
export const isElement = isInstanceOf.isElement;
export const isError = isInstanceOf.isError;
export const isErrorEvent = isInstanceOf.isErrorEvent;
export const isEvent = isInstanceOf.isEvent;
export const isInstanceOf = isInstanceOf.isInstanceOf;
export const isParameterizedString = isInstanceOf.isParameterizedString;
export const isPlainObject = isInstanceOf.isPlainObject;
export const isPrimitive = isInstanceOf.isPrimitive;
export const isRegExp = isInstanceOf.isRegExp;
export const isString = isInstanceOf.isString;
export const isSyntheticEvent = isInstanceOf.isSyntheticEvent;
export const isThenable = isInstanceOf.isThenable;
export const isVueViewModel = isInstanceOf.isVueViewModel;
export const isBrowser = isBrowser.isBrowser;
export const CONSOLE_LEVELS = consoleSandbox.CONSOLE_LEVELS;
export const consoleSandbox = consoleSandbox.consoleSandbox;
export const debug = consoleSandbox.debug;
export const originalConsoleMethods = consoleSandbox.originalConsoleMethods;
export const addContextToFrame = addContextToFrame.addContextToFrame;
export const addExceptionMechanism = addContextToFrame.addExceptionMechanism;
export const addExceptionTypeValue = addContextToFrame.addExceptionTypeValue;
export const checkOrSetAlreadyCaught = addContextToFrame.checkOrSetAlreadyCaught;
export const getEventDescription = addContextToFrame.getEventDescription;
export const parseSemver = addContextToFrame.parseSemver;
export const uuid4 = addContextToFrame.uuid4;
export const isNodeEnv = dynamicRequire.isNodeEnv;
export const loadModule = dynamicRequire.loadModule;
export const normalize = normalize.normalize;
export const normalizeToSize = normalize.normalizeToSize;
export const normalizeUrlToBase = normalize.normalizeUrlToBase;
export const addNonEnumerableProperty = addNonEnumerableProperty.addNonEnumerableProperty;
export const convertToPlainObject = addNonEnumerableProperty.convertToPlainObject;
export const dropUndefinedKeys = addNonEnumerableProperty.dropUndefinedKeys;
export const extractExceptionKeysForMessage = addNonEnumerableProperty.extractExceptionKeysForMessage;
export const fill = addNonEnumerableProperty.fill;
export const getOriginalFunction = addNonEnumerableProperty.getOriginalFunction;
export const markFunctionWrapped = addNonEnumerableProperty.markFunctionWrapped;
export const objectify = addNonEnumerableProperty.objectify;
export const basename = resolve.basename;
export const dirname = resolve.dirname;
export const isAbsolute = resolve.isAbsolute;
export const join = resolve.join;
export const normalizePath = resolve.normalizePath;
export const relative = resolve.relative;
export const resolve = resolve.resolve;
export const SENTRY_BUFFER_FULL_ERROR = makePromiseBuffer.SENTRY_BUFFER_FULL_ERROR;
export const makePromiseBuffer = makePromiseBuffer.makePromiseBuffer;
export const severityLevelFromString = severityLevelFromString.severityLevelFromString;
export const replaceExports = replaceExports.replaceExports;
export const UNKNOWN_FUNCTION = createStackParser.UNKNOWN_FUNCTION;
export const createStackParser = createStackParser.createStackParser;
export const getFramesFromEvent = createStackParser.getFramesFromEvent;
export const getFunctionName = createStackParser.getFunctionName;
export const stackParserFromStackParserOptions = createStackParser.stackParserFromStackParserOptions;
export const stripSentryFramesAndReverse = createStackParser.stripSentryFramesAndReverse;
export const filenameIsInApp = filenameIsInApp.filenameIsInApp;
export const node = filenameIsInApp.node;
export const nodeStackLineParser = filenameIsInApp.nodeStackLineParser;
export const isMatchingPattern = isMatchingPattern.isMatchingPattern;
export const safeJoin = isMatchingPattern.safeJoin;
export const snipLine = isMatchingPattern.snipLine;
export const stringMatchesSomePattern = isMatchingPattern.stringMatchesSomePattern;
export const truncate = isMatchingPattern.truncate;
export const isNativeFunction = _isFetchSupported.isNativeFunction;
export const supportsDOMError = _isFetchSupported.supportsDOMError;
export const supportsDOMException = _isFetchSupported.supportsDOMException;
export const supportsErrorEvent = _isFetchSupported.supportsErrorEvent;
export const supportsFetch = _isFetchSupported.supportsFetch;
export const supportsHistory = _isFetchSupported.supportsHistory;
export const supportsNativeFetch = _isFetchSupported.supportsNativeFetch;
export const supportsReferrerPolicy = _isFetchSupported.supportsReferrerPolicy;
export const supportsReportingObserver = _isFetchSupported.supportsReportingObserver;
export const SyncPromise = SyncPromise.SyncPromise;
export const rejectedSyncPromise = SyncPromise.rejectedSyncPromise;
export const resolvedSyncPromise = SyncPromise.resolvedSyncPromise;
export const browserPerformanceTimeOrigin = dateTimestampInSeconds.browserPerformanceTimeOrigin;
export const dateTimestampInSeconds = dateTimestampInSeconds.dateTimestampInSeconds;
export const timestampInSeconds = dateTimestampInSeconds.timestampInSeconds;
export const TRACEPARENT_REGEXP = regExp.TRACEPARENT_REGEXP;
export const extractTraceparentData = regExp.extractTraceparentData;
export const generateSentryTraceHeader = regExp.generateSentryTraceHeader;
export const generateTraceparentHeader = regExp.generateTraceparentHeader;
export const propagationContextFromHeaders = regExp.propagationContextFromHeaders;
export const shouldContinueTrace = regExp.shouldContinueTrace;
export const getSDKSource = getSDKSource.getSDKSource;
export const isBrowserBundle = getSDKSource.isBrowserBundle;
export const addItemToEnvelope = forEachEnvelopeItem.addItemToEnvelope;
export const createAttachmentEnvelopeItem = forEachEnvelopeItem.createAttachmentEnvelopeItem;
export const createEnvelope = forEachEnvelopeItem.createEnvelope;
export const createEventEnvelopeHeaders = forEachEnvelopeItem.createEventEnvelopeHeaders;
export const createSpanEnvelopeItem = forEachEnvelopeItem.createSpanEnvelopeItem;
export const envelopeContainsItemType = forEachEnvelopeItem.envelopeContainsItemType;
export const envelopeItemTypeToDataCategory = forEachEnvelopeItem.envelopeItemTypeToDataCategory;
export const forEachEnvelopeItem = forEachEnvelopeItem.forEachEnvelopeItem;
export const getSdkMetadataForEnvelopeHeader = forEachEnvelopeItem.getSdkMetadataForEnvelopeHeader;
export const parseEnvelope = forEachEnvelopeItem.parseEnvelope;
export const serializeEnvelope = forEachEnvelopeItem.serializeEnvelope;
export const createClientReportEnvelope = createClientReportEnvelope.createClientReportEnvelope;
export const DEFAULT_RETRY_AFTER = parseRetryAfterHeader.DEFAULT_RETRY_AFTER;
export const disabledUntil = parseRetryAfterHeader.disabledUntil;
export const isRateLimited = parseRetryAfterHeader.isRateLimited;
export const parseRetryAfterHeader = parseRetryAfterHeader.parseRetryAfterHeader;
export const updateRateLimits = parseRetryAfterHeader.updateRateLimits;
export const MAX_BAGGAGE_STRING_LENGTH = baggageHeaderToDynamicSamplingContext.MAX_BAGGAGE_STRING_LENGTH;
export const SENTRY_BAGGAGE_KEY_PREFIX = baggageHeaderToDynamicSamplingContext.SENTRY_BAGGAGE_KEY_PREFIX;
export const SENTRY_BAGGAGE_KEY_PREFIX_REGEX = baggageHeaderToDynamicSamplingContext.SENTRY_BAGGAGE_KEY_PREFIX_REGEX;
export const baggageHeaderToDynamicSamplingContext = baggageHeaderToDynamicSamplingContext.baggageHeaderToDynamicSamplingContext;
export const dynamicSamplingContextToSentryBaggageHeader = baggageHeaderToDynamicSamplingContext.dynamicSamplingContextToSentryBaggageHeader;
export const objectToBaggageHeader = baggageHeaderToDynamicSamplingContext.objectToBaggageHeader;
export const parseBaggageHeader = baggageHeaderToDynamicSamplingContext.parseBaggageHeader;
export const getHttpSpanDetailsFromUrlObject = getHttpSpanDetailsFromUrlObject.getHttpSpanDetailsFromUrlObject;
export const getSanitizedUrlString = getHttpSpanDetailsFromUrlObject.getSanitizedUrlString;
export const getSanitizedUrlStringFromUrlObject = getHttpSpanDetailsFromUrlObject.getSanitizedUrlStringFromUrlObject;
export const isURLObjectRelative = getHttpSpanDetailsFromUrlObject.isURLObjectRelative;
export const parseStringToURLObject = getHttpSpanDetailsFromUrlObject.parseStringToURLObject;
export const parseUrl = getHttpSpanDetailsFromUrlObject.parseUrl;
export const stripDataUrlContent = getHttpSpanDetailsFromUrlObject.stripDataUrlContent;
export const stripUrlQueryAndFragment = getHttpSpanDetailsFromUrlObject.stripUrlQueryAndFragment;
export const _INTERNAL_enhanceErrorWithSentryInfo = exceptionFromError._enhanceErrorWithSentryInfo;
export const eventFromMessage = exceptionFromError.eventFromMessage;
export const eventFromUnknownInput = exceptionFromError.eventFromUnknownInput;
export const exceptionFromError = exceptionFromError.exceptionFromError;
export const parseStackFrames = exceptionFromError.parseStackFrames;
export const callFrameToStackFrame = callFrameToStackFrame.callFrameToStackFrame;
export const watchdogTimer = callFrameToStackFrame.watchdogTimer;
export const LRUMap = LRUMap.LRUMap;
export const generateSpanId = generateSpanId.generateSpanId;
export const generateTraceId = generateSpanId.generateTraceId;
export const vercelWaitUntil = vercelWaitUntil.vercelWaitUntil;
export const flushIfServerless = flushWithTimeout.flushIfServerless;
export const SDK_VERSION = _mod826.SDK_VERSION;
export const getDebugImagesForResources = getFilenameToDebugIdMap.getDebugImagesForResources;
export const getFilenameToDebugIdMap = getFilenameToDebugIdMap.getFilenameToDebugIdMap;
export const getFilenameToMetadataMap = map.getFilenameToMetadataMap;
export const escapeStringForRegex = escapeStringForRegex.escapeStringForRegex;
export const _INTERNAL_safeDateNow = safeDateNow.safeDateNow;
export const _INTERNAL_safeMathRandom = safeDateNow.safeMathRandom;
export const _INTERNAL_withRandomSafeContext = safeDateNow.withRandomSafeContext;