// _runtime/00898_addClsInstrumentationHandler.js
import triggerHandlers from "00899_triggerHandlers.js";
import _addMeasureSpans from "00923__addMeasureSpans.js";
import extractNetworkProtocol from "00924_extractNetworkProtocol.js";
import resourceTimingToSpanAttributes from "00928_resourceTimingToSpanAttributes.js";
import _onElementTiming from "00929__onElementTiming.js";
import instrumentDOM from "00930_instrumentDOM.js";
import instrumentHistory from "00931_instrumentHistory.js";
import getNativeImplementation from "00932_getNativeImplementation.js";
import instrumentXHR from "00933_instrumentXHR.js";
import serializeFormData from "00934_serializeFormData.js";
import map from "00935_map.js";

Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });

export const addClsInstrumentationHandler = triggerHandlers.addClsInstrumentationHandler;
export const addInpInstrumentationHandler = triggerHandlers.addInpInstrumentationHandler;
export const addLcpInstrumentationHandler = triggerHandlers.addLcpInstrumentationHandler;
export const addPerformanceInstrumentationHandler = triggerHandlers.addPerformanceInstrumentationHandler;
export const addTtfbInstrumentationHandler = triggerHandlers.addTtfbInstrumentationHandler;
export const addPerformanceEntries = _addMeasureSpans.addPerformanceEntries;
export const startTrackingInteractions = _addMeasureSpans.startTrackingInteractions;
export const startTrackingLongAnimationFrames = _addMeasureSpans.startTrackingLongAnimationFrames;
export const startTrackingLongTasks = _addMeasureSpans.startTrackingLongTasks;
export const startTrackingWebVitals = _addMeasureSpans.startTrackingWebVitals;
export const startTrackingElementTiming = _onElementTiming.startTrackingElementTiming;
export const extractNetworkProtocol = extractNetworkProtocol.extractNetworkProtocol;
export const addClickKeypressInstrumentationHandler = instrumentDOM.addClickKeypressInstrumentationHandler;
export const addHistoryInstrumentationHandler = instrumentHistory.addHistoryInstrumentationHandler;
export const clearCachedImplementation = getNativeImplementation.clearCachedImplementation;
export const fetch = getNativeImplementation.fetch;
export const getNativeImplementation = getNativeImplementation.getNativeImplementation;
export const setTimeout = getNativeImplementation.setTimeout;
export const SENTRY_XHR_DATA_KEY = instrumentXHR.SENTRY_XHR_DATA_KEY;
export const addXhrInstrumentationHandler = instrumentXHR.addXhrInstrumentationHandler;
export const getBodyString = serializeFormData.getBodyString;
export const getFetchRequestArgBody = serializeFormData.getFetchRequestArgBody;
export const parseXhrResponseHeaders = serializeFormData.parseXhrResponseHeaders;
export const serializeFormData = serializeFormData.serializeFormData;
export const resourceTimingToSpanAttributes = resourceTimingToSpanAttributes.resourceTimingToSpanAttributes;
export const registerInpInteractionListener = map.registerInpInteractionListener;
export const startTrackingINP = map.startTrackingINP;
