// _runtime/00900_feedbackAsyncIntegration.js
import _mod693 from "metro/00693__.js";
import _mod901 from "metro/00901__.js";
import _mod902 from "metro/00902__.js";
import lazyLoadIntegration from "00903_lazyLoadIntegration.js";
import _mod904 from "metro/00904__.js";
import feedbackSyncIntegration from "00905_feedbackSyncIntegration.js";
import BrowserClient from "00906_BrowserClient.js";
import eventFromException from "00907_eventFromException.js";
import _mod908 from "metro/00908__.js";
import uiProfiler from "00947_uiProfiler.js";
import chromeStackLineParser from "00949_chromeStackLineParser.js";
import _mod950 from "metro/00950__.js";
import forceLoad from "00951_forceLoad.js";
import browserApiErrorsIntegration from "00952_browserApiErrorsIntegration.js";
import breadcrumbsIntegration from "00953_breadcrumbsIntegration.js";
import _eventFromRejectionWithPrimitive from "00954__eventFromRejectionWithPrimitive.js";
import _mod955 from "metro/00955__.js";
import httpContextIntegration from "00956_httpContextIntegration.js";
import browserSessionIntegration from "00957_browserSessionIntegration.js";
import showReportDialog from "00959_showReportDialog.js";
import reportingObserverIntegration from "00960_reportingObserverIntegration.js";
import httpClientIntegration from "00961_httpClientIntegration.js";
import applySourceContextToFrame from "00962_applySourceContextToFrame.js";
import _getGraphQLOperation from "00963__getGraphQLOperation.js";
import _mod964 from "metro/00964__.js";
import _mod965 from "metro/00965__.js";
import defaultRequestInstrumentationOptions from "00966_defaultRequestInstrumentationOptions.js";
import BROWSER_TRACING_INTEGRATION_ID from "00968_BROWSER_TRACING_INTEGRATION_ID.js";
import _mod970 from "metro/00970__.js";
import reportPageLoaded from "00972_reportPageLoaded.js";
import _mod973 from "metro/00973__.js";
import _mod974 from "metro/00974__.js";
import browserProfilingIntegration from "00975_browserProfilingIntegration.js";
import _mod979 from "metro/00979__.js";
import OpenFeatureIntegrationHook from "00980_OpenFeatureIntegrationHook.js";
import unleashIntegration from "00981_unleashIntegration.js";
import _mod982 from "metro/00982__.js";
import statsigIntegration from "00983_statsigIntegration.js";
import _asyncToGenerator from "metro/00984__asyncToGenerator.js";
import _mod985 from "metro/00985__.js";

Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
const feedbackSyncIntegration_export = feedbackSyncIntegration.feedbackSyncIntegration;
const BrowserClient_export = BrowserClient.BrowserClient;
const uiProfiler_export = uiProfiler.uiProfiler;
const chromeStackLineParser_export = chromeStackLineParser.chromeStackLineParser;
const eventFromException_export = eventFromException.eventFromException;
const forceLoad_export = forceLoad.forceLoad;
const showReportDialog_export = showReportDialog.showReportDialog;
const breadcrumbsIntegration_export = breadcrumbsIntegration.breadcrumbsIntegration;
const httpContextIntegration_export = httpContextIntegration.httpContextIntegration;
const browserApiErrorsIntegration_export = browserApiErrorsIntegration.browserApiErrorsIntegration;
const lazyLoadIntegration_export = lazyLoadIntegration.lazyLoadIntegration;
const reportingObserverIntegration_export = reportingObserverIntegration.reportingObserverIntegration;
const httpClientIntegration_export = httpClientIntegration.httpClientIntegration;
const defaultRequestInstrumentationOptions_export =
  defaultRequestInstrumentationOptions.defaultRequestInstrumentationOptions;
const reportPageLoaded_export = reportPageLoaded.reportPageLoaded;
const browserProfilingIntegration_export = browserProfilingIntegration.browserProfilingIntegration;
const browserSessionIntegration_export = browserSessionIntegration.browserSessionIntegration;
const OpenFeatureIntegrationHook_export = OpenFeatureIntegrationHook.OpenFeatureIntegrationHook;
const unleashIntegration_export = unleashIntegration.unleashIntegration;
const statsigIntegration_export = statsigIntegration.statsigIntegration;

export const feedbackAsyncIntegration = _mod901.feedbackAsyncIntegration;
export const feedbackIntegration = feedbackSyncIntegration.feedbackSyncIntegration;
export { feedbackSyncIntegration_export as feedbackSyncIntegration };
export const MULTIPLEXED_TRANSPORT_EXTRA_KEY = _mod693.MULTIPLEXED_TRANSPORT_EXTRA_KEY;
export const SDK_VERSION = _mod693.SDK_VERSION;
export const SEMANTIC_ATTRIBUTE_SENTRY_OP = _mod693.SEMANTIC_ATTRIBUTE_SENTRY_OP;
export const SEMANTIC_ATTRIBUTE_SENTRY_ORIGIN = _mod693.SEMANTIC_ATTRIBUTE_SENTRY_ORIGIN;
export const SEMANTIC_ATTRIBUTE_SENTRY_SAMPLE_RATE = _mod693.SEMANTIC_ATTRIBUTE_SENTRY_SAMPLE_RATE;
export const SEMANTIC_ATTRIBUTE_SENTRY_SOURCE = _mod693.SEMANTIC_ATTRIBUTE_SENTRY_SOURCE;
export const Scope = _mod693.Scope;
export const addBreadcrumb = _mod693.addBreadcrumb;
export const addEventProcessor = _mod693.addEventProcessor;
export const addIntegration = _mod693.addIntegration;
export const captureConsoleIntegration = _mod693.captureConsoleIntegration;
export const captureEvent = _mod693.captureEvent;
export const captureException = _mod693.captureException;
export const captureFeedback = _mod693.captureFeedback;
export const captureMessage = _mod693.captureMessage;
export const captureSession = _mod693.captureSession;
export const close = _mod693.close;
export const consoleLoggingIntegration = _mod693.consoleLoggingIntegration;
export const continueTrace = _mod693.continueTrace;
export const createConsolaReporter = _mod693.createConsolaReporter;
export const createLangChainCallbackHandler = _mod693.createLangChainCallbackHandler;
export const createTransport = _mod693.createTransport;
export const dedupeIntegration = _mod693.dedupeIntegration;
export const endSession = _mod693.endSession;
export const eventFiltersIntegration = _mod693.eventFiltersIntegration;
export const extraErrorDataIntegration = _mod693.extraErrorDataIntegration;
export const featureFlagsIntegration = _mod693.featureFlagsIntegration;
export const flush = _mod693.flush;
export const functionToStringIntegration = _mod693.functionToStringIntegration;
export const getActiveSpan = _mod693.getActiveSpan;
export const getClient = _mod693.getClient;
export const getCurrentScope = _mod693.getCurrentScope;
export const getGlobalScope = _mod693.getGlobalScope;
export const getIsolationScope = _mod693.getIsolationScope;
export const getRootSpan = _mod693.getRootSpan;
export const getSpanDescendants = _mod693.getSpanDescendants;
export const getSpanStatusFromHttpCode = _mod693.getSpanStatusFromHttpCode;
export const getTraceData = _mod693.getTraceData;
export const inboundFiltersIntegration = _mod693.inboundFiltersIntegration;
export const instrumentAnthropicAiClient = _mod693.instrumentAnthropicAiClient;
export const instrumentGoogleGenAIClient = _mod693.instrumentGoogleGenAIClient;
export const instrumentLangGraph = _mod693.instrumentLangGraph;
export const instrumentOpenAiClient = _mod693.instrumentOpenAiClient;
export const instrumentSupabaseClient = _mod693.instrumentSupabaseClient;
export const isEnabled = _mod693.isEnabled;
export const isInitialized = _mod693.isInitialized;
export const lastEventId = _mod693.lastEventId;
export const logger = _mod693.logger;
export const makeMultiplexedTransport = _mod693.makeMultiplexedTransport;
export const metrics = _mod693.metrics;
export const moduleMetadataIntegration = _mod693.moduleMetadataIntegration;
export const parameterize = _mod693.parameterize;
export const registerSpanErrorInstrumentation = _mod693.registerSpanErrorInstrumentation;
export const rewriteFramesIntegration = _mod693.rewriteFramesIntegration;
export const setContext = _mod693.setContext;
export const setCurrentClient = _mod693.setCurrentClient;
export const setExtra = _mod693.setExtra;
export const setExtras = _mod693.setExtras;
export const setHttpStatus = _mod693.setHttpStatus;
export const setMeasurement = _mod693.setMeasurement;
export const setTag = _mod693.setTag;
export const setTags = _mod693.setTags;
export const setUser = _mod693.setUser;
export const spanToBaggageHeader = _mod693.spanToBaggageHeader;
export const spanToJSON = _mod693.spanToJSON;
export const spanToTraceHeader = _mod693.spanToTraceHeader;
export const startInactiveSpan = _mod693.startInactiveSpan;
export const startNewTrace = _mod693.startNewTrace;
export const startSession = _mod693.startSession;
export const startSpan = _mod693.startSpan;
export const startSpanManual = _mod693.startSpanManual;
export const supabaseIntegration = _mod693.supabaseIntegration;
export const suppressTracing = _mod693.suppressTracing;
export const thirdPartyErrorFilterIntegration = _mod693.thirdPartyErrorFilterIntegration;
export const updateSpanName = _mod693.updateSpanName;
export const withActiveSpan = _mod693.withActiveSpan;
export const withIsolationScope = _mod693.withIsolationScope;
export const withScope = _mod693.withScope;
export const zodErrorsIntegration = _mod693.zodErrorsIntegration;
export const WINDOW = _mod904.WINDOW;
export { BrowserClient_export as BrowserClient };
export const makeFetchTransport = _mod908.makeFetchTransport;
export { uiProfiler_export as uiProfiler };
export { chromeStackLineParser_export as chromeStackLineParser };
export const defaultStackLineParsers = chromeStackLineParser.defaultStackLineParsers;
export const defaultStackParser = chromeStackLineParser.defaultStackParser;
export const geckoStackLineParser = chromeStackLineParser.geckoStackLineParser;
export const opera10StackLineParser = chromeStackLineParser.opera10StackLineParser;
export const opera11StackLineParser = chromeStackLineParser.opera11StackLineParser;
export const winjsStackLineParser = chromeStackLineParser.winjsStackLineParser;
export { eventFromException_export as eventFromException };
export const eventFromMessage = eventFromException.eventFromMessage;
export const exceptionFromError = eventFromException.exceptionFromError;
export const createUserFeedbackEnvelope = _mod950.createUserFeedbackEnvelope;
export { forceLoad_export as forceLoad };
export const getDefaultIntegrations = forceLoad.getDefaultIntegrations;
export const init = forceLoad.init;
export const onLoad = forceLoad.onLoad;
export { showReportDialog_export as showReportDialog };
export { breadcrumbsIntegration_export as breadcrumbsIntegration };
export const globalHandlersIntegration = _eventFromRejectionWithPrimitive.globalHandlersIntegration;
export { httpContextIntegration_export as httpContextIntegration };
export const linkedErrorsIntegration = _mod955.linkedErrorsIntegration;
export { browserApiErrorsIntegration_export as browserApiErrorsIntegration };
export { lazyLoadIntegration_export as lazyLoadIntegration };
export { reportingObserverIntegration_export as reportingObserverIntegration };
export { httpClientIntegration_export as httpClientIntegration };
export const contextLinesIntegration = applySourceContextToFrame.contextLinesIntegration;
export const graphqlClientIntegration = _getGraphQLOperation.graphqlClientIntegration;
export const getReplay = _mod964.getReplay;
export const replayIntegration = _mod964.replayIntegration;
export const replayCanvasIntegration = _mod965.replayCanvasIntegration;
export const getFeedback = _mod902.getFeedback;
export const sendFeedback = _mod902.sendFeedback;
export { defaultRequestInstrumentationOptions_export as defaultRequestInstrumentationOptions };
export const instrumentOutgoingRequests = defaultRequestInstrumentationOptions.instrumentOutgoingRequests;
export const browserTracingIntegration = BROWSER_TRACING_INTEGRATION_ID.browserTracingIntegration;
export const startBrowserTracingNavigationSpan = BROWSER_TRACING_INTEGRATION_ID.startBrowserTracingNavigationSpan;
export const startBrowserTracingPageLoadSpan = BROWSER_TRACING_INTEGRATION_ID.startBrowserTracingPageLoadSpan;
export { reportPageLoaded_export as reportPageLoaded };
export const setActiveSpanInBrowser = _mod973.setActiveSpanInBrowser;
export const makeBrowserOfflineTransport = _mod974.makeBrowserOfflineTransport;
export { browserProfilingIntegration_export as browserProfilingIntegration };
export const spotlightBrowserIntegration = _mod970.spotlightBrowserIntegration;
export { browserSessionIntegration_export as browserSessionIntegration };
export const buildLaunchDarklyFlagUsedHandler = _mod979.buildLaunchDarklyFlagUsedHandler;
export const launchDarklyIntegration = _mod979.launchDarklyIntegration;
export { OpenFeatureIntegrationHook_export as OpenFeatureIntegrationHook };
export const openFeatureIntegration = OpenFeatureIntegrationHook.openFeatureIntegration;
export { unleashIntegration_export as unleashIntegration };
export const growthbookIntegration = _mod982.growthbookIntegration;
export { statsigIntegration_export as statsigIntegration };
export const diagnoseSdkConnectivity = _asyncToGenerator.diagnoseSdkConnectivity;
export const registerWebWorker = _mod985.registerWebWorker;
export const webWorkerIntegration = _mod985.webWorkerIntegration;
