// _runtime/01030_addClsInstrumentationHandler.js
import triggerHandlers from "01031_triggerHandlers.js";
import _addMeasureSpans from "01055__addMeasureSpans.js";
import extractNetworkProtocol from "01056_extractNetworkProtocol.js";
import resourceTimingToSpanAttributes from "01060_resourceTimingToSpanAttributes.js";
import _onElementTiming from "01061__onElementTiming.js";
import instrumentDOM from "01062_instrumentDOM.js";
import instrumentHistory from "01063_instrumentHistory.js";
import getNativeImplementation from "01064_getNativeImplementation.js";
import instrumentXHR from "01065_instrumentXHR.js";
import serializeFormData from "01066_serializeFormData.js";
import map from "01067_map.js";

Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });

export const addClsInstrumentationHandler = triggerHandlers.addClsInstrumentationHandler;
export const addInpInstrumentationHandler = triggerHandlers.addInpInstrumentationHandler;
export const addLcpInstrumentationHandler = triggerHandlers.addLcpInstrumentationHandler;
export const addPerformanceInstrumentationHandler = triggerHandlers.addPerformanceInstrumentationHandler;
export const addTtfbInstrumentationHandler = triggerHandlers.addTtfbInstrumentationHandler;
export const addPerformanceEntries = _addMeasureSpans.addPerformanceEntries;
export const startTrackingInteractions = _addMeasureSpans.startTrackingInteractions;
export const startTrackingLongAnimationFrames = _addMeasureSpans.startTrackingLongAnimationFrames;
export const startTrackingLongTasks = _addMeasureSpans.startTrackingLongTasks;
export const startTrackingWebVitals = _addMeasureSpans.startTrackingWebVitals;
export const startTrackingElementTiming = _onElementTiming.startTrackingElementTiming;
export const extractNetworkProtocol = extractNetworkProtocol.extractNetworkProtocol;
export const addClickKeypressInstrumentationHandler = instrumentDOM.addClickKeypressInstrumentationHandler;
export const addHistoryInstrumentationHandler = instrumentHistory.addHistoryInstrumentationHandler;
export const clearCachedImplementation = getNativeImplementation.clearCachedImplementation;
export const fetch = getNativeImplementation.fetch;
export const getNativeImplementation = getNativeImplementation.getNativeImplementation;
export const setTimeout = getNativeImplementation.setTimeout;
export const SENTRY_XHR_DATA_KEY = instrumentXHR.SENTRY_XHR_DATA_KEY;
export const addXhrInstrumentationHandler = instrumentXHR.addXhrInstrumentationHandler;
export const getBodyString = serializeFormData.getBodyString;
export const getFetchRequestArgBody = serializeFormData.getFetchRequestArgBody;
export const parseXhrResponseHeaders = serializeFormData.parseXhrResponseHeaders;
export const serializeFormData = serializeFormData.serializeFormData;
export const resourceTimingToSpanAttributes = resourceTimingToSpanAttributes.resourceTimingToSpanAttributes;
export const registerInpInteractionListener = map.registerInpInteractionListener;
export const startTrackingINP = map.startTrackingINP;
