// _runtime/01486_BaseNavigationContainer.js
import _mod1499 from "metro/01499__.js";
import _mod1501 from "metro/01501__.js";
import NOT_INITIALIZED_ERROR from "01509_NOT_INITIALIZED_ERROR.js";
import findFocusedRoute from "01510_findFocusedRoute.js";
import NavigationContainerRefContext from "01514_NavigationContainerRefContext.js";
import ThemeProvider from "01519_ThemeProvider.js";
import _mod1520 from "metro/01520__.js";
import _mod1521 from "metro/01521__.js";
import _mod1522 from "metro/01522__.js";
import _mod1523 from "metro/01523__.js";
import _mod1524 from "metro/01524__.js";
import context1 from "01525_context1.js";
import _mod1526 from "metro/01526__.js";
import NavigationContext from "01527_NavigationContext.js";
import CurrentRenderContext from "01532_CurrentRenderContext.js";
import _mod1533 from "metro/01533__.js";
import CHILD_STATE from "01534_CHILD_STATE.js";
import serializeParamValue from "01537_serializeParamValue.js";
import prepareConfigResources from "01545_prepareConfigResources.js";
import NavigationHelpersContext from "01549_NavigationHelpersContext.js";
import NavigationIndependentTree from "01550_NavigationIndependentTree.js";
import NavigationMetaContext from "01552_NavigationMetaContext.js";
import PreventRemoveContext from "01553_PreventRemoveContext.js";
import transformPreventedRoutes from "01554_transformPreventedRoutes.js";
import _mod1555 from "metro/01555__.js";
import _mod1556 from "metro/01556__.js";
import _mod1557 from "metro/01557__.js";
import NavigationStateListenerProvider from "01575_NavigationStateListenerProvider.js";
import _mod1576 from "metro/01576__.js";
import _mod1577 from "metro/01577__.js";
import _mod1578 from "metro/01578__.js";
import _mod1579 from "metro/01579__.js";
import _mod1580 from "metro/01580__.js";

for (const key10013 in require("PrivateValueStore")) {
  arg5[key10013] = require("PrivateValueStore")[key10013];
  continue;
}
for (const key10017 in require("CommonActions")) {
  arg5[key10017] = require("CommonActions")[key10017];
  continue;
}

export const BaseNavigationContainer = _mod1499.BaseNavigationContainer;
export const createNavigationContainerRef = NOT_INITIALIZED_ERROR.createNavigationContainerRef;
export const createNavigatorFactory = _mod1521.createNavigatorFactory;
export const CurrentRenderContext = CurrentRenderContext.CurrentRenderContext;
export const findFocusedRoute = findFocusedRoute.findFocusedRoute;
export const getActionFromState = _mod1533.getActionFromState;
export const getFocusedRouteNameFromRoute = CHILD_STATE.getFocusedRouteNameFromRoute;
export const getPathFromState = serializeParamValue.getPathFromState;
export const getStateFromPath = prepareConfigResources.getStateFromPath;
export const NavigationContainerRefContext = NavigationContainerRefContext.NavigationContainerRefContext;
export const NavigationContext = NavigationContext.NavigationContext;
export const NavigationHelpersContext = NavigationHelpersContext.NavigationHelpersContext;
export const NavigationIndependentTree = NavigationIndependentTree.NavigationIndependentTree;
export const NavigationMetaContext = NavigationMetaContext.NavigationMetaContext;
export const NavigationProvider = _mod1524.NavigationProvider;
export const NavigationRouteContext = _mod1524.NavigationRouteContext;
export const PreventRemoveContext = PreventRemoveContext.PreventRemoveContext;
export const PreventRemoveProvider = transformPreventedRoutes.PreventRemoveProvider;
export const createComponentForStaticNavigation = _mod1522.createComponentForStaticNavigationDeprecated;
export const createPathConfigForStaticNavigation = _mod1522.createPathConfigForStaticNavigation;
export const createScreenFactory = _mod1522.createScreenFactory;
export const ThemeContext = _mod1520.ThemeContext;
export const ThemeProvider = ThemeProvider.ThemeProvider;
export const useTheme = _mod1555.useTheme;
export const useFocusEffect = _mod1556.useFocusEffect;
export const useIsFocused = context1.useIsFocused;
export const useNavigation = _mod1526.useNavigation;
export const useNavigationBuilder = _mod1557.useNavigationBuilder;
export const useNavigationContainerRef = _mod1576.useNavigationContainerRef;
export const useNavigationIndependentTree = _mod1501.useNavigationIndependentTree;
export const useNavigationState = NavigationStateListenerProvider.useNavigationState;
export const usePreventRemove = _mod1577.usePreventRemove;
export const usePreventRemoveContext = _mod1578.usePreventRemoveContext;
export const useRoute = _mod1523.useRoute;
export const useStateForPath = _mod1579.useStateForPath;
export const validatePathConfig = _mod1580.validatePathConfig;
