// _runtime/01493_BaseNavigationContainer.js
import _createClass from "metro/01494__createClass.js";
import CommonActions from "01495_CommonActions.js";
import _mod1506 from "metro/01506__.js";
import react from "01508_react.js";
import NOT_INITIALIZED_ERROR from "01516_NOT_INITIALIZED_ERROR.js";
import findFocusedRoute from "01517_findFocusedRoute.js";
import react2 from "01521_react.js";
import ThemeProvider from "01526_ThemeProvider.js";
import react3 from "01527_react.js";
import _mod1528 from "metro/01528__.js";
import _mod1529 from "metro/01529__.js";
import react4 from "01530_react.js";
import _mod1531 from "metro/01531__.js";
import _mod1532 from "metro/01532__.js";
import _mod1533 from "metro/01533__.js";
import react5 from "01534_react.js";
import react6 from "01539_react.js";
import _mod1540 from "metro/01540__.js";
import CHILD_STATE from "01541_CHILD_STATE.js";
import _mod1544 from "metro/01544__.js";
import _mod1552 from "metro/01552__.js";
import react7 from "01556_react.js";
import NavigationIndependentTree from "01557_NavigationIndependentTree.js";
import react8 from "01559_react.js";
import react9 from "01560_react.js";
import PreventRemoveProvider from "01561_PreventRemoveProvider.js";
import react10 from "01562_react.js";
import react11 from "01563_react.js";
import _mod1564 from "metro/01564__.js";
import NavigationStateListenerProvider from "01582_NavigationStateListenerProvider.js";
import react12 from "01583_react.js";
import _mod1584 from "metro/01584__.js";
import react13 from "01585_react.js";
import react14 from "01586_react.js";
import validatePathConfig from "01587_validatePathConfig.js";

for (const key10013 in _createClass) {
  exports[key10013] = _createClass[key10013];
  continue;
}
for (const key10017 in CommonActions) {
  exports[key10017] = CommonActions[key10017];
  continue;
}
const findFocusedRoute_export = findFocusedRoute.findFocusedRoute;
const NavigationIndependentTree_export = NavigationIndependentTree.NavigationIndependentTree;
const PreventRemoveProvider_export = PreventRemoveProvider.PreventRemoveProvider;
const ThemeProvider_export = ThemeProvider.ThemeProvider;
const validatePathConfig_export = validatePathConfig.validatePathConfig;

export const BaseNavigationContainer = _mod1506.BaseNavigationContainer;
export const createNavigationContainerRef = NOT_INITIALIZED_ERROR.createNavigationContainerRef;
export const createNavigatorFactory = _mod1528.createNavigatorFactory;
export const CurrentRenderContext = react6.CurrentRenderContext;
export { findFocusedRoute_export as findFocusedRoute };
export const getActionFromState = _mod1540.getActionFromState;
export const getFocusedRouteNameFromRoute = CHILD_STATE.getFocusedRouteNameFromRoute;
export const getPathFromState = _mod1544.getPathFromState;
export const getStateFromPath = _mod1552.getStateFromPath;
export const NavigationContainerRefContext = react2.NavigationContainerRefContext;
export const NavigationContext = react5.NavigationContext;
export const NavigationHelpersContext = react7.NavigationHelpersContext;
export { NavigationIndependentTree_export as NavigationIndependentTree };
export const NavigationMetaContext = react8.NavigationMetaContext;
export const NavigationProvider = _mod1531.NavigationProvider;
export const NavigationRouteContext = _mod1531.NavigationRouteContext;
export const PreventRemoveContext = react9.PreventRemoveContext;
export { PreventRemoveProvider_export as PreventRemoveProvider };
export const createComponentForStaticNavigation = _mod1529.createComponentForStaticNavigationDeprecated;
export const createPathConfigForStaticNavigation = _mod1529.createPathConfigForStaticNavigation;
export const createScreenFactory = _mod1529.createScreenFactory;
export const ThemeContext = react3.ThemeContext;
export { ThemeProvider_export as ThemeProvider };
export const useTheme = react10.useTheme;
export const useFocusEffect = react11.useFocusEffect;
export const useIsFocused = _mod1532.useIsFocused;
export const useNavigation = _mod1533.useNavigation;
export const useNavigationBuilder = _mod1564.useNavigationBuilder;
export const useNavigationContainerRef = react12.useNavigationContainerRef;
export const useNavigationIndependentTree = react.useNavigationIndependentTree;
export const useNavigationState = NavigationStateListenerProvider.useNavigationState;
export const usePreventRemove = _mod1584.usePreventRemove;
export const usePreventRemoveContext = react13.usePreventRemoveContext;
export const useRoute = react4.useRoute;
export const useStateForPath = react14.useStateForPath;
export { validatePathConfig_export as validatePathConfig };
