// _runtime/01502_BaseNavigationContainer.js
import getPartialState from "01515_getPartialState.js";
import useNavigationIndependentTree from "01517_useNavigationIndependentTree.js";
import createNavigationContainerRef from "01525_createNavigationContainerRef.js";
import findFocusedRoute from "01526_findFocusedRoute.js";
import NavigationContainerRefContext from "01530_NavigationContainerRefContext.js";
import ThemeProvider from "01535_ThemeProvider.js";
import context from "01536_context.js";
import createNavigatorFactory from "01537_createNavigatorFactory.js";
import getItemsFromScreens from "01538_getItemsFromScreens.js";
import useRoute from "01539_useRoute.js";
import context2 from "01540_context.js";
import context1 from "01541_context1.js";
import useNavigation from "01542_useNavigation.js";
import NavigationContext from "01543_NavigationContext.js";
import CurrentRenderContext from "01548_CurrentRenderContext.js";
import weakMap from "01549_weakMap.js";
import getFocusedRouteNameFromRoute from "01550_getFocusedRouteNameFromRoute.js";
import serializeParamValue from "01553_serializeParamValue.js";
import prepareConfigResources from "01561_prepareConfigResources.js";
import NavigationHelpersContext from "01565_NavigationHelpersContext.js";
import NavigationIndependentTree from "01566_NavigationIndependentTree.js";
import NavigationMetaContext from "01568_NavigationMetaContext.js";
import PreventRemoveContext from "01569_PreventRemoveContext.js";
import transformPreventedRoutes from "01570_transformPreventedRoutes.js";
import useTheme from "01571_useTheme.js";
import useFocusEffect from "01572_useFocusEffect.js";
import isNavigationState from "01573_isNavigationState.js";
import useNavigationState from "01591_useNavigationState.js";
import useNavigationContainerRef from "01592_useNavigationContainerRef.js";
import usePreventRemove from "01593_usePreventRemove.js";
import usePreventRemoveContext from "01594_usePreventRemoveContext.js";
import useStateForPath from "01595_useStateForPath.js";
import formatToList from "01596_formatToList.js";

for (const key10013 in require("PrivateValueStore")) {
  let tmp2 = key10013;
  arg5[key10013] = require("PrivateValueStore")[key10013];
  continue;
}
for (const key10017 in require("CommonActions")) {
  let tmp3 = key10017;
  arg5[key10017] = require("CommonActions")[key10017];
  continue;
}

export const BaseNavigationContainer = getPartialState.BaseNavigationContainer;
export const createNavigationContainerRef = createNavigationContainerRef.createNavigationContainerRef;
export const createNavigatorFactory = createNavigatorFactory.createNavigatorFactory;
export const CurrentRenderContext = CurrentRenderContext.CurrentRenderContext;
export const findFocusedRoute = findFocusedRoute.findFocusedRoute;
export const getActionFromState = weakMap.getActionFromState;
export const getFocusedRouteNameFromRoute = getFocusedRouteNameFromRoute.getFocusedRouteNameFromRoute;
export const getPathFromState = serializeParamValue.getPathFromState;
export const getStateFromPath = prepareConfigResources.getStateFromPath;
export const NavigationContainerRefContext = NavigationContainerRefContext.NavigationContainerRefContext;
export const NavigationContext = NavigationContext.NavigationContext;
export const NavigationHelpersContext = NavigationHelpersContext.NavigationHelpersContext;
export const NavigationIndependentTree = NavigationIndependentTree.NavigationIndependentTree;
export const NavigationMetaContext = NavigationMetaContext.NavigationMetaContext;
export const NavigationProvider = context2.NavigationProvider;
export const NavigationRouteContext = context2.NavigationRouteContext;
export const PreventRemoveContext = PreventRemoveContext.PreventRemoveContext;
export const PreventRemoveProvider = transformPreventedRoutes.PreventRemoveProvider;
export const createComponentForStaticNavigation = getItemsFromScreens.createComponentForStaticNavigationDeprecated;
export const createPathConfigForStaticNavigation = getItemsFromScreens.createPathConfigForStaticNavigation;
export const createScreenFactory = getItemsFromScreens.createScreenFactory;
export const ThemeContext = context.ThemeContext;
export const ThemeProvider = ThemeProvider.ThemeProvider;
export const useTheme = useTheme.useTheme;
export const useFocusEffect = useFocusEffect.useFocusEffect;
export const useIsFocused = context1.useIsFocused;
export const useNavigation = useNavigation.useNavigation;
export const useNavigationBuilder = isNavigationState.useNavigationBuilder;
export const useNavigationContainerRef = useNavigationContainerRef.useNavigationContainerRef;
export const useNavigationIndependentTree = useNavigationIndependentTree.useNavigationIndependentTree;
export const useNavigationState = useNavigationState.useNavigationState;
export const usePreventRemove = usePreventRemove.usePreventRemove;
export const usePreventRemoveContext = usePreventRemoveContext.usePreventRemoveContext;
export const useRoute = useRoute.useRoute;
export const useStateForPath = useStateForPath.useStateForPath;
export const validatePathConfig = formatToList.validatePathConfig;