// _runtime/01706_startWebLayoutAnimation.js
import startWebLayoutAnimation from "01707_startWebLayoutAnimation.js";
import setElementAnimation from "01721_setElementAnimation.js";
import findDescendantWithExitingAnimation from "01739_findDescendantWithExitingAnimation.js";

export const startWebLayoutAnimation = startWebLayoutAnimation.startWebLayoutAnimation;
export const tryActivateLayoutTransition = startWebLayoutAnimation.tryActivateLayoutTransition;
export const getReducedMotionFromConfig = setElementAnimation.getReducedMotionFromConfig;
export const saveSnapshot = setElementAnimation.saveSnapshot;
export const configureWebLayoutAnimations = findDescendantWithExitingAnimation.configureWebLayoutAnimations;
