// _runtime/03776_parsers.js
import _typeof from "metro/03777__typeof.js";
import _typeof2 from "metro/03779__typeof.js";
import _typeof3 from "metro/03782__typeof.js";
import _typeof4 from "metro/03783__typeof.js";
import _typeof5 from "metro/03784__typeof.js";
import _typeof6 from "metro/03785__typeof.js";
import _typeof7 from "metro/03786__typeof.js";
import _typeof8 from "metro/03787__typeof.js";
import _typeof9 from "metro/03788__typeof.js";
import _typeof10 from "metro/03789__typeof.js";
import _typeof11 from "metro/03791__typeof.js";
import _typeof12 from "metro/03793__typeof.js";
import _typeof13 from "metro/03794__typeof.js";
import _typeof14 from "metro/03795__typeof.js";
import _typeof15 from "metro/03797__typeof.js";
import _typeof16 from "metro/03798__typeof.js";
import _typeof17 from "metro/03799__typeof.js";
import _typeof18 from "metro/03801__typeof.js";
import _typeof19 from "metro/03802__typeof.js";
import _typeof20 from "metro/03803__typeof.js";
import _typeof21 from "metro/03804__typeof.js";
import _typeof22 from "metro/03805__typeof.js";
import _typeof23 from "metro/03806__typeof.js";
import _typeof24 from "metro/03807__typeof.js";
import _typeof25 from "metro/03808__typeof.js";
import _typeof26 from "metro/03809__typeof.js";
import _typeof27 from "metro/03810__typeof.js";
import _typeof28 from "metro/03811__typeof.js";
import _typeof29 from "metro/03812__typeof.js";
import _typeof30 from "metro/03813__typeof.js";
import _typeof31 from "metro/03814__typeof.js";

const obj = { G: null, y: null, Y: null, R: null, u: null, Q: null, q: null, M: null, L: null, w: null, I: null, d: null, D: null, E: null, e: null, c: null, i: null, a: null, b: null, B: null, h: null, H: null, K: null, k: null, m: null, s: null, S: null, X: null, x: null, t: null, T: null };
const eraParser = new _typeof.EraParser();
obj[0] = eraParser;
const yearParser = new _typeof2.YearParser();
obj[1] = yearParser;
const localWeekYearParser = new _typeof3.LocalWeekYearParser();
obj[2] = localWeekYearParser;
const iSOWeekYearParser = new _typeof4.ISOWeekYearParser();
obj[3] = iSOWeekYearParser;
const extendedYearParser = new _typeof5.ExtendedYearParser();
obj[4] = extendedYearParser;
const quarterParser = new _typeof6.QuarterParser();
obj[5] = quarterParser;
const standAloneQuarterParser = new _typeof7.StandAloneQuarterParser();
obj[6] = standAloneQuarterParser;
const monthParser = new _typeof8.MonthParser();
obj[7] = monthParser;
const standAloneMonthParser = new _typeof9.StandAloneMonthParser();
obj[8] = standAloneMonthParser;
const localWeekParser = new _typeof10.LocalWeekParser();
obj[9] = localWeekParser;
const iSOWeekParser = new _typeof11.ISOWeekParser();
obj[10] = iSOWeekParser;
const dateParser = new _typeof12.DateParser();
obj[11] = dateParser;
const dayOfYearParser = new _typeof13.DayOfYearParser();
obj[12] = dayOfYearParser;
const dayParser = new _typeof14.DayParser();
obj[13] = dayParser;
const localDayParser = new _typeof15.LocalDayParser();
obj[14] = localDayParser;
const standAloneLocalDayParser = new _typeof16.StandAloneLocalDayParser();
obj[15] = standAloneLocalDayParser;
const iSODayParser = new _typeof17.ISODayParser();
obj[16] = iSODayParser;
const aMPMParser = new _typeof18.AMPMParser();
obj[17] = aMPMParser;
const aMPMMidnightParser = new _typeof19.AMPMMidnightParser();
obj[18] = aMPMMidnightParser;
const dayPeriodParser = new _typeof20.DayPeriodParser();
obj[19] = dayPeriodParser;
const hour1to12Parser = new _typeof21.Hour1to12Parser();
obj[20] = hour1to12Parser;
const hour0to23Parser = new _typeof22.Hour0to23Parser();
obj[21] = hour0to23Parser;
const hour0To11Parser = new _typeof23.Hour0To11Parser();
obj[22] = hour0To11Parser;
const hour1To24Parser = new _typeof24.Hour1To24Parser();
obj[23] = hour1To24Parser;
const minuteParser = new _typeof25.MinuteParser();
obj[24] = minuteParser;
const secondParser = new _typeof26.SecondParser();
obj[25] = secondParser;
const fractionOfSecondParser = new _typeof27.FractionOfSecondParser();
obj[26] = fractionOfSecondParser;
const iSOTimezoneWithZParser = new _typeof28.ISOTimezoneWithZParser();
obj[27] = iSOTimezoneWithZParser;
const iSOTimezoneParser = new _typeof29.ISOTimezoneParser();
obj[28] = iSOTimezoneParser;
const timestampSecondsParser = new _typeof30.TimestampSecondsParser();
obj[29] = timestampSecondsParser;
const timestampMillisecondsParser = new _typeof31.TimestampMillisecondsParser();
obj[30] = timestampMillisecondsParser;

export const parsers = obj;