// _runtime/05249___react_navigation__elements_contexts.js
import __react_navigation__elements_contexts from "__react_navigation__elements_contexts";


export default __react_navigation__elements_contexts("HeaderHeightContext", undefined);