// _runtime/05533_LegacyBaseButton.js
import _mod5539 from "metro/05539__.js";
import items1 from "05558_items1.js";
import items12 from "05559_items1.js";
import managePanProps from "05569_managePanProps.js";
import items13 from "05570_items1.js";
import _isNativeReflectConstruct from "05571__isNativeReflectConstruct.js";
import items14 from "05573_items1.js";
import _isNativeReflectConstruct2 from "05574__isNativeReflectConstruct.js";
import items from "05575_items.js";
import _isNativeReflectConstruct3 from "05646__isNativeReflectConstruct.js";
import itemsDefault from "05647_items.js";
import LegacyScrollView from "05648_LegacyScrollView.js";
import GestureHandlerRootViewDefault from "05649_GestureHandlerRootView.js";
import hitSlopDefault from "05651_hitSlop.js";
import _mod5653 from "metro/05653__.js";
import LegacyText from "05663_LegacyText.js";
import TouchableHighlight from "05664_TouchableHighlight.js";
import _mod5670 from "metro/05670__.js";
import pinchHandlerName from "05671_pinchHandlerName.js";
import rotationHandlerName from "05672_rotationHandlerName.js";
import _mod5673 from "metro/05673__.js";
import 05534__ from "metro/05534__.js";
import initialize from "05535_initialize.js";

initialize = initialize.initialize();
for (const key10019 in require("BaseButton")) {
  let tmp4 = key10019;
  arg5[key10019] = require("BaseButton")[key10019];
  continue;
}

export const LegacyBaseButton = _isNativeReflectConstruct3.LegacyBaseButton;
export const LegacyBorderlessButton = _isNativeReflectConstruct3.LegacyBorderlessButton;
export const LegacyRawButton = _isNativeReflectConstruct3.LegacyRawButton;
export const LegacyRectButton = _isNativeReflectConstruct3.LegacyRectButton;
export const LegacyDrawerLayoutAndroid = LegacyScrollView.LegacyDrawerLayoutAndroid;
export const LegacyFlatList = LegacyScrollView.LegacyFlatList;
export const LegacyRefreshControl = LegacyScrollView.LegacyRefreshControl;
export const LegacyScrollView = LegacyScrollView.LegacyScrollView;
export const LegacySwitch = LegacyScrollView.LegacySwitch;
export const LegacyTextInput = LegacyScrollView.LegacyTextInput;
export const GestureHandlerRootView = GestureHandlerRootViewDefault;
export const LegacyPressable = hitSlopDefault;
export const LegacyText = LegacyText.LegacyText;
export const TouchableHighlight = TouchableHighlight.TouchableHighlight;
export const TouchableNativeFeedback = TouchableHighlight.TouchableNativeFeedback;
export const TouchableOpacity = TouchableHighlight.TouchableOpacity;
export const TouchableWithoutFeedback = TouchableHighlight.TouchableWithoutFeedback;
export const Directions = _mod5670.Directions;
export const legacy_createNativeWrapper = itemsDefault;
export const FlingGestureHandler = items14.FlingGestureHandler;
export const ForceTouchGestureHandler = _isNativeReflectConstruct.ForceTouchGestureHandler;
export const MouseButton = items1.MouseButton;
export const Gesture = _mod5653.GestureObjects;
export const HoverEffect = _isNativeReflectConstruct2.HoverEffect;
export const LongPressGestureHandler = items13.LongPressGestureHandler;
export const NativeViewGestureHandler = items.NativeViewGestureHandler;
export const PanGestureHandler = managePanProps.PanGestureHandler;
export const PinchGestureHandler = pinchHandlerName.PinchGestureHandler;
export const RotationGestureHandler = rotationHandlerName.RotationGestureHandler;
export const TapGestureHandler = items12.TapGestureHandler;
export const PointerType = _mod5673.PointerType;
export const State = _mod5539.State;