// _runtime/05604_LegacyBaseButton.js
import _mod5610 from "metro/05610__.js";
import items1 from "05629_items1.js";
import items12 from "05630_items1.js";
import managePanProps from "05640_managePanProps.js";
import items13 from "05641_items1.js";
import _isNativeReflectConstruct from "05642__isNativeReflectConstruct.js";
import items14 from "05644_items1.js";
import _isNativeReflectConstruct2 from "05645__isNativeReflectConstruct.js";
import items from "05646_items.js";
import _isNativeReflectConstruct3 from "05717__isNativeReflectConstruct.js";
import itemsDefault from "05718_items.js";
import LegacyScrollView from "05719_LegacyScrollView.js";
import GestureHandlerRootViewDefault from "05720_GestureHandlerRootView.js";
import hitSlopDefault from "05722_hitSlop.js";
import _mod5724 from "metro/05724__.js";
import LegacyText from "05734_LegacyText.js";
import TouchableHighlight from "05735_TouchableHighlight.js";
import _mod5741 from "metro/05741__.js";
import pinchHandlerName from "05742_pinchHandlerName.js";
import rotationHandlerName from "05743_rotationHandlerName.js";
import _mod5744 from "metro/05744__.js";
import 05605__ from "metro/05605__.js";
import initialize from "05606_initialize.js";

initialize = initialize.initialize();
for (const key10019 in require("BaseButton")) {
  let tmp4 = key10019;
  arg5[key10019] = require("BaseButton")[key10019];
  continue;
}

export const LegacyBaseButton = _isNativeReflectConstruct3.LegacyBaseButton;
export const LegacyBorderlessButton = _isNativeReflectConstruct3.LegacyBorderlessButton;
export const LegacyRawButton = _isNativeReflectConstruct3.LegacyRawButton;
export const LegacyRectButton = _isNativeReflectConstruct3.LegacyRectButton;
export const LegacyDrawerLayoutAndroid = LegacyScrollView.LegacyDrawerLayoutAndroid;
export const LegacyFlatList = LegacyScrollView.LegacyFlatList;
export const LegacyRefreshControl = LegacyScrollView.LegacyRefreshControl;
export const LegacyScrollView = LegacyScrollView.LegacyScrollView;
export const LegacySwitch = LegacyScrollView.LegacySwitch;
export const LegacyTextInput = LegacyScrollView.LegacyTextInput;
export const GestureHandlerRootView = GestureHandlerRootViewDefault;
export const LegacyPressable = hitSlopDefault;
export const LegacyText = LegacyText.LegacyText;
export const TouchableHighlight = TouchableHighlight.TouchableHighlight;
export const TouchableNativeFeedback = TouchableHighlight.TouchableNativeFeedback;
export const TouchableOpacity = TouchableHighlight.TouchableOpacity;
export const TouchableWithoutFeedback = TouchableHighlight.TouchableWithoutFeedback;
export const Directions = _mod5741.Directions;
export const legacy_createNativeWrapper = itemsDefault;
export const FlingGestureHandler = items14.FlingGestureHandler;
export const ForceTouchGestureHandler = _isNativeReflectConstruct.ForceTouchGestureHandler;
export const MouseButton = items1.MouseButton;
export const Gesture = _mod5724.GestureObjects;
export const HoverEffect = _isNativeReflectConstruct2.HoverEffect;
export const LongPressGestureHandler = items13.LongPressGestureHandler;
export const NativeViewGestureHandler = items.NativeViewGestureHandler;
export const PanGestureHandler = managePanProps.PanGestureHandler;
export const PinchGestureHandler = pinchHandlerName.PinchGestureHandler;
export const RotationGestureHandler = rotationHandlerName.RotationGestureHandler;
export const TapGestureHandler = items12.TapGestureHandler;
export const PointerType = _mod5744.PointerType;
export const State = _mod5610.State;