// _runtime/05620_LegacyBaseButton.js
import _mod5626 from "metro/05626__.js";
import items1 from "05645_items1.js";
import items12 from "05646_items1.js";
import managePanProps from "05656_managePanProps.js";
import items13 from "05657_items1.js";
import _isNativeReflectConstruct from "05658__isNativeReflectConstruct.js";
import items14 from "05660_items1.js";
import _isNativeReflectConstruct2 from "05661__isNativeReflectConstruct.js";
import items from "05662_items.js";
import _isNativeReflectConstruct3 from "05733__isNativeReflectConstruct.js";
import itemsDefault from "05734_items.js";
import LegacyScrollView from "05735_LegacyScrollView.js";
import GestureHandlerRootViewDefault from "05736_GestureHandlerRootView.js";
import hitSlopDefault from "05738_hitSlop.js";
import _mod5740 from "metro/05740__.js";
import LegacyText from "05750_LegacyText.js";
import TouchableHighlight from "05751_TouchableHighlight.js";
import _mod5757 from "metro/05757__.js";
import pinchHandlerName from "05758_pinchHandlerName.js";
import rotationHandlerName from "05759_rotationHandlerName.js";
import _mod5760 from "metro/05760__.js";
import 05621__ from "metro/05621__.js";
import initialize from "05622_initialize.js";

initialize = initialize.initialize();
for (const key10019 in require("BaseButton")) {
  let tmp4 = key10019;
  arg5[key10019] = require("BaseButton")[key10019];
  continue;
}

export const LegacyBaseButton = _isNativeReflectConstruct3.LegacyBaseButton;
export const LegacyBorderlessButton = _isNativeReflectConstruct3.LegacyBorderlessButton;
export const LegacyRawButton = _isNativeReflectConstruct3.LegacyRawButton;
export const LegacyRectButton = _isNativeReflectConstruct3.LegacyRectButton;
export const LegacyDrawerLayoutAndroid = LegacyScrollView.LegacyDrawerLayoutAndroid;
export const LegacyFlatList = LegacyScrollView.LegacyFlatList;
export const LegacyRefreshControl = LegacyScrollView.LegacyRefreshControl;
export const LegacyScrollView = LegacyScrollView.LegacyScrollView;
export const LegacySwitch = LegacyScrollView.LegacySwitch;
export const LegacyTextInput = LegacyScrollView.LegacyTextInput;
export const GestureHandlerRootView = GestureHandlerRootViewDefault;
export const LegacyPressable = hitSlopDefault;
export const LegacyText = LegacyText.LegacyText;
export const TouchableHighlight = TouchableHighlight.TouchableHighlight;
export const TouchableNativeFeedback = TouchableHighlight.TouchableNativeFeedback;
export const TouchableOpacity = TouchableHighlight.TouchableOpacity;
export const TouchableWithoutFeedback = TouchableHighlight.TouchableWithoutFeedback;
export const Directions = _mod5757.Directions;
export const legacy_createNativeWrapper = itemsDefault;
export const FlingGestureHandler = items14.FlingGestureHandler;
export const ForceTouchGestureHandler = _isNativeReflectConstruct.ForceTouchGestureHandler;
export const MouseButton = items1.MouseButton;
export const Gesture = _mod5740.GestureObjects;
export const HoverEffect = _isNativeReflectConstruct2.HoverEffect;
export const LongPressGestureHandler = items13.LongPressGestureHandler;
export const NativeViewGestureHandler = items.NativeViewGestureHandler;
export const PanGestureHandler = managePanProps.PanGestureHandler;
export const PinchGestureHandler = pinchHandlerName.PinchGestureHandler;
export const RotationGestureHandler = rotationHandlerName.RotationGestureHandler;
export const TapGestureHandler = items12.TapGestureHandler;
export const PointerType = _mod5760.PointerType;
export const State = _mod5626.State;