// _runtime/05652_LegacyBaseButton.js
import _mod5658 from "metro/05658__.js";
import items1 from "05677_items1.js";
import items12 from "05678_items1.js";
import managePanProps from "05688_managePanProps.js";
import items13 from "05689_items1.js";
import _isNativeReflectConstruct from "05690__isNativeReflectConstruct.js";
import items14 from "05692_items1.js";
import _isNativeReflectConstruct2 from "05693__isNativeReflectConstruct.js";
import items from "05694_items.js";
import _isNativeReflectConstruct3 from "05765__isNativeReflectConstruct.js";
import itemsDefault from "05766_items.js";
import LegacyScrollView from "05767_LegacyScrollView.js";
import GestureHandlerRootViewDefault from "05768_GestureHandlerRootView.js";
import hitSlopDefault from "05770_hitSlop.js";
import _mod5772 from "metro/05772__.js";
import LegacyText from "05782_LegacyText.js";
import TouchableHighlight from "05783_TouchableHighlight.js";
import _mod5789 from "metro/05789__.js";
import pinchHandlerName from "05790_pinchHandlerName.js";
import rotationHandlerName from "05791_rotationHandlerName.js";
import _mod5792 from "metro/05792__.js";
import 05653__ from "metro/05653__.js";
import initialize from "05654_initialize.js";

initialize = initialize.initialize();
for (const key10019 in require("BaseButton")) {
  let tmp4 = key10019;
  arg5[key10019] = require("BaseButton")[key10019];
  continue;
}

export const LegacyBaseButton = _isNativeReflectConstruct3.LegacyBaseButton;
export const LegacyBorderlessButton = _isNativeReflectConstruct3.LegacyBorderlessButton;
export const LegacyRawButton = _isNativeReflectConstruct3.LegacyRawButton;
export const LegacyRectButton = _isNativeReflectConstruct3.LegacyRectButton;
export const LegacyDrawerLayoutAndroid = LegacyScrollView.LegacyDrawerLayoutAndroid;
export const LegacyFlatList = LegacyScrollView.LegacyFlatList;
export const LegacyRefreshControl = LegacyScrollView.LegacyRefreshControl;
export const LegacyScrollView = LegacyScrollView.LegacyScrollView;
export const LegacySwitch = LegacyScrollView.LegacySwitch;
export const LegacyTextInput = LegacyScrollView.LegacyTextInput;
export const GestureHandlerRootView = GestureHandlerRootViewDefault;
export const LegacyPressable = hitSlopDefault;
export const LegacyText = LegacyText.LegacyText;
export const TouchableHighlight = TouchableHighlight.TouchableHighlight;
export const TouchableNativeFeedback = TouchableHighlight.TouchableNativeFeedback;
export const TouchableOpacity = TouchableHighlight.TouchableOpacity;
export const TouchableWithoutFeedback = TouchableHighlight.TouchableWithoutFeedback;
export const Directions = _mod5789.Directions;
export const legacy_createNativeWrapper = itemsDefault;
export const FlingGestureHandler = items14.FlingGestureHandler;
export const ForceTouchGestureHandler = _isNativeReflectConstruct.ForceTouchGestureHandler;
export const MouseButton = items1.MouseButton;
export const Gesture = _mod5772.GestureObjects;
export const HoverEffect = _isNativeReflectConstruct2.HoverEffect;
export const LongPressGestureHandler = items13.LongPressGestureHandler;
export const NativeViewGestureHandler = items.NativeViewGestureHandler;
export const PanGestureHandler = managePanProps.PanGestureHandler;
export const PinchGestureHandler = pinchHandlerName.PinchGestureHandler;
export const RotationGestureHandler = rotationHandlerName.RotationGestureHandler;
export const TapGestureHandler = items12.TapGestureHandler;
export const PointerType = _mod5792.PointerType;
export const State = _mod5658.State;