// _runtime/05661_LegacyBaseButton.js
import _mod5667 from "metro/05667__.js";
import items1 from "05686_items1.js";
import items12 from "05687_items1.js";
import managePanProps from "05697_managePanProps.js";
import items13 from "05698_items1.js";
import _isNativeReflectConstruct from "05699__isNativeReflectConstruct.js";
import items14 from "05701_items1.js";
import _isNativeReflectConstruct2 from "05702__isNativeReflectConstruct.js";
import items from "05703_items.js";
import _isNativeReflectConstruct3 from "05774__isNativeReflectConstruct.js";
import itemsDefault from "05775_items.js";
import LegacyScrollView from "05776_LegacyScrollView.js";
import GestureHandlerRootViewDefault from "05777_GestureHandlerRootView.js";
import hitSlopDefault from "05779_hitSlop.js";
import _mod5781 from "metro/05781__.js";
import LegacyText from "05791_LegacyText.js";
import TouchableHighlight from "05792_TouchableHighlight.js";
import _mod5798 from "metro/05798__.js";
import pinchHandlerName from "05799_pinchHandlerName.js";
import rotationHandlerName from "05800_rotationHandlerName.js";
import _mod5801 from "metro/05801__.js";
import 05662__ from "metro/05662__.js";
import initialize from "05663_initialize.js";

initialize = initialize.initialize();
for (const key10019 in require("BaseButton")) {
  let tmp4 = key10019;
  arg5[key10019] = require("BaseButton")[key10019];
  continue;
}

export const LegacyBaseButton = _isNativeReflectConstruct3.LegacyBaseButton;
export const LegacyBorderlessButton = _isNativeReflectConstruct3.LegacyBorderlessButton;
export const LegacyRawButton = _isNativeReflectConstruct3.LegacyRawButton;
export const LegacyRectButton = _isNativeReflectConstruct3.LegacyRectButton;
export const LegacyDrawerLayoutAndroid = LegacyScrollView.LegacyDrawerLayoutAndroid;
export const LegacyFlatList = LegacyScrollView.LegacyFlatList;
export const LegacyRefreshControl = LegacyScrollView.LegacyRefreshControl;
export const LegacyScrollView = LegacyScrollView.LegacyScrollView;
export const LegacySwitch = LegacyScrollView.LegacySwitch;
export const LegacyTextInput = LegacyScrollView.LegacyTextInput;
export const GestureHandlerRootView = GestureHandlerRootViewDefault;
export const LegacyPressable = hitSlopDefault;
export const LegacyText = LegacyText.LegacyText;
export const TouchableHighlight = TouchableHighlight.TouchableHighlight;
export const TouchableNativeFeedback = TouchableHighlight.TouchableNativeFeedback;
export const TouchableOpacity = TouchableHighlight.TouchableOpacity;
export const TouchableWithoutFeedback = TouchableHighlight.TouchableWithoutFeedback;
export const Directions = _mod5798.Directions;
export const legacy_createNativeWrapper = itemsDefault;
export const FlingGestureHandler = items14.FlingGestureHandler;
export const ForceTouchGestureHandler = _isNativeReflectConstruct.ForceTouchGestureHandler;
export const MouseButton = items1.MouseButton;
export const Gesture = _mod5781.GestureObjects;
export const HoverEffect = _isNativeReflectConstruct2.HoverEffect;
export const LongPressGestureHandler = items13.LongPressGestureHandler;
export const NativeViewGestureHandler = items.NativeViewGestureHandler;
export const PanGestureHandler = managePanProps.PanGestureHandler;
export const PinchGestureHandler = pinchHandlerName.PinchGestureHandler;
export const RotationGestureHandler = rotationHandlerName.RotationGestureHandler;
export const TapGestureHandler = items12.TapGestureHandler;
export const PointerType = _mod5801.PointerType;
export const State = _mod5667.State;