// _runtime/05721_set.js
arg5.PanNativeProperties = new Set([
  "minDist",
  "avgTouches",
  "enableTrackpadTwoFingerGesture",
  "minPointers",
  "maxPointers",
  "minVelocity",
  "minVelocityX",
  "minVelocityY",
  "activateAfterLongPress",
  "activeOffsetYStart",
  "activeOffsetYEnd",
  "activeOffsetXStart",
  "activeOffsetXEnd",
  "failOffsetYStart",
  "failOffsetYEnd",
  "failOffsetXStart",
  "failOffsetXEnd",
]);
