// _runtime/05772_BottomSheetHostingContainer.js
import BottomSheetHostingContainer from "05773_BottomSheetHostingContainer.js";


export const BottomSheetHostingContainer = BottomSheetHostingContainer.BottomSheetHostingContainer;