// _runtime/06377_LegacyBaseButton.js
import _mod6383 from "metro/06383__.js";
import items1 from "06402_items1.js";
import items12 from "06403_items1.js";
import managePanProps from "06413_managePanProps.js";
import items13 from "06414_items1.js";
import _isNativeReflectConstruct from "06415__isNativeReflectConstruct.js";
import items14 from "06417_items1.js";
import _isNativeReflectConstruct2 from "06418__isNativeReflectConstruct.js";
import items from "06419_items.js";
import _isNativeReflectConstruct3 from "06490__isNativeReflectConstruct.js";
import itemsDefault from "06491_items.js";
import LegacyScrollView from "06492_LegacyScrollView.js";
import GestureHandlerRootViewDefault from "06493_GestureHandlerRootView.js";
import hitSlopDefault from "06495_hitSlop.js";
import _mod6497 from "metro/06497__.js";
import LegacyText from "06507_LegacyText.js";
import TouchableHighlight from "06508_TouchableHighlight.js";
import _mod6514 from "metro/06514__.js";
import pinchHandlerName from "06515_pinchHandlerName.js";
import rotationHandlerName from "06516_rotationHandlerName.js";
import _mod6517 from "metro/06517__.js";
import 06378__ from "metro/06378__.js";
import initialize from "06379_initialize.js";

initialize = initialize.initialize();
for (const key10019 in require("BaseButton")) {
  arg5[key10019] = require("BaseButton")[key10019];
  continue;
}

export const LegacyBaseButton = _isNativeReflectConstruct3.LegacyBaseButton;
export const LegacyBorderlessButton = _isNativeReflectConstruct3.LegacyBorderlessButton;
export const LegacyRawButton = _isNativeReflectConstruct3.LegacyRawButton;
export const LegacyRectButton = _isNativeReflectConstruct3.LegacyRectButton;
export const LegacyDrawerLayoutAndroid = LegacyScrollView.LegacyDrawerLayoutAndroid;
export const LegacyFlatList = LegacyScrollView.LegacyFlatList;
export const LegacyRefreshControl = LegacyScrollView.LegacyRefreshControl;
export const LegacyScrollView = LegacyScrollView.LegacyScrollView;
export const LegacySwitch = LegacyScrollView.LegacySwitch;
export const LegacyTextInput = LegacyScrollView.LegacyTextInput;
export const GestureHandlerRootView = GestureHandlerRootViewDefault;
export const LegacyPressable = hitSlopDefault;
export const LegacyText = LegacyText.LegacyText;
export const TouchableHighlight = TouchableHighlight.TouchableHighlight;
export const TouchableNativeFeedback = TouchableHighlight.TouchableNativeFeedback;
export const TouchableOpacity = TouchableHighlight.TouchableOpacity;
export const TouchableWithoutFeedback = TouchableHighlight.TouchableWithoutFeedback;
export const Directions = _mod6514.Directions;
export const legacy_createNativeWrapper = itemsDefault;
export const FlingGestureHandler = items14.FlingGestureHandler;
export const ForceTouchGestureHandler = _isNativeReflectConstruct.ForceTouchGestureHandler;
export const MouseButton = items1.MouseButton;
export const Gesture = _mod6497.GestureObjects;
export const HoverEffect = _isNativeReflectConstruct2.HoverEffect;
export const LongPressGestureHandler = items13.LongPressGestureHandler;
export const NativeViewGestureHandler = items.NativeViewGestureHandler;
export const PanGestureHandler = managePanProps.PanGestureHandler;
export const PinchGestureHandler = pinchHandlerName.PinchGestureHandler;
export const RotationGestureHandler = rotationHandlerName.RotationGestureHandler;
export const TapGestureHandler = items12.TapGestureHandler;
export const PointerType = _mod6517.PointerType;
export const State = _mod6383.State;