// _runtime/06574_Circle.js
import _isNativeReflectConstructDefault from "06575__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault2 from "06585__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault3 from "06599__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault4 from "06601__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault5 from "06603__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault6 from "06605__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault7 from "06607__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault8 from "06611__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault9 from "06613__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault10 from "06614__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault11 from "06616__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault12 from "06617__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault13 from "06618__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault14 from "06619__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault15 from "06620__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault16 from "06621__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault17 from "06623__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault18 from "06625__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault19 from "06627__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault20 from "06629__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault21 from "06631__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault22 from "06632__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault23 from "06633__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault24 from "06634__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault25 from "06635__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault26 from "06636__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault27 from "06637__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault28 from "06638__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault29 from "06640__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault30 from "06642__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault31 from "06644__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault32 from "06646__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault33 from "06650__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault34 from "06652__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault35 from "06655__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault36 from "06657__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault37 from "06659__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault38 from "06661__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault39 from "06662__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault40 from "06664__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault41 from "06666__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault42 from "06667__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault43 from "06669__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault44 from "06670__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault45 from "06673__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault46 from "06675__isNativeReflectConstruct.js";


export default _isNativeReflectConstructDefault;
export const Circle = _isNativeReflectConstructDefault3;
export const ClipPath = _isNativeReflectConstructDefault4;
export const Defs = _isNativeReflectConstructDefault5;
export const Ellipse = _isNativeReflectConstructDefault6;
export const FeBlend = _isNativeReflectConstructDefault7;
export const FeColorMatrix = _isNativeReflectConstructDefault8;
export const FeComponentTransfer = _isNativeReflectConstructDefault9;
export const FeComposite = _isNativeReflectConstructDefault10;
export const FeConvolveMatrix = _isNativeReflectConstructDefault11;
export const FeDiffuseLighting = _isNativeReflectConstructDefault12;
export const FeDisplacementMap = _isNativeReflectConstructDefault13;
export const FeDistantLight = _isNativeReflectConstructDefault14;
export const FeDropShadow = _isNativeReflectConstructDefault15;
export const FeFlood = _isNativeReflectConstructDefault18;
export const FeFuncA = require("_isNativeReflectConstruct").FeFuncA;
export const FeFuncB = require("_isNativeReflectConstruct").FeFuncB;
export const FeFuncG = require("_isNativeReflectConstruct").FeFuncG;
export const FeFuncR = require("_isNativeReflectConstruct").FeFuncR;
export const FeGaussianBlur = _isNativeReflectConstructDefault16;
export const FeImage = _isNativeReflectConstructDefault21;
export const FeMerge = _isNativeReflectConstructDefault19;
export const FeMergeNode = _isNativeReflectConstructDefault20;
export const FeMorphology = _isNativeReflectConstructDefault22;
export const FeOffset = _isNativeReflectConstructDefault17;
export const FePointLight = _isNativeReflectConstructDefault23;
export const FeSpecularLighting = _isNativeReflectConstructDefault24;
export const FeSpotLight = _isNativeReflectConstructDefault25;
export const FeTile = _isNativeReflectConstructDefault26;
export const FeTurbulence = _isNativeReflectConstructDefault27;
export const Filter = _isNativeReflectConstructDefault28;
export const ForeignObject = _isNativeReflectConstructDefault29;
export const G = _isNativeReflectConstructDefault2;
export const Image = _isNativeReflectConstructDefault30;
export const Line = _isNativeReflectConstructDefault31;
export const LinearGradient = _isNativeReflectConstructDefault32;
export const Marker = _isNativeReflectConstructDefault33;
export const Mask = _isNativeReflectConstructDefault34;
export const Path = _isNativeReflectConstructDefault35;
export const Pattern = _isNativeReflectConstructDefault36;
export const Polygon = _isNativeReflectConstructDefault37;
export const Polyline = _isNativeReflectConstructDefault38;
export const RadialGradient = _isNativeReflectConstructDefault39;
export const Rect = _isNativeReflectConstructDefault40;
export const Stop = _isNativeReflectConstructDefault41;
export const Svg = _isNativeReflectConstructDefault;
export const Symbol = _isNativeReflectConstructDefault42;
export const Text = _isNativeReflectConstructDefault43;
export const TextPath = _isNativeReflectConstructDefault45;
export const TSpan = _isNativeReflectConstructDefault44;
export const Use = _isNativeReflectConstructDefault46;