// _runtime/06994_BottomSheetHostingContainer.js
import BottomSheetHostingContainer from "06995_BottomSheetHostingContainer.js";


export const BottomSheetHostingContainer = BottomSheetHostingContainer.BottomSheetHostingContainer;