// _runtime/07988_Circle.js
import _isNativeReflectConstructDefault from "07989__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault2 from "07999__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault3 from "08013__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault4 from "08015__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault5 from "08017__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault6 from "08019__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault7 from "08021__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault8 from "08025__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault9 from "08027__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault10 from "08028__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault11 from "08030__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault12 from "08031__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault13 from "08032__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault14 from "08033__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault15 from "08034__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault16 from "08035__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault17 from "08037__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault18 from "08039__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault19 from "08041__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault20 from "08043__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault21 from "08045__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault22 from "08046__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault23 from "08047__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault24 from "08048__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault25 from "08049__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault26 from "08050__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault27 from "08051__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault28 from "08052__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault29 from "08054__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault30 from "08056__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault31 from "08058__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault32 from "08060__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault33 from "08064__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault34 from "08066__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault35 from "08069__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault36 from "08071__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault37 from "08073__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault38 from "08075__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault39 from "08076__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault40 from "08078__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault41 from "08080__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault42 from "08081__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault43 from "08083__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault44 from "08084__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault45 from "08087__isNativeReflectConstruct.js";
import _isNativeReflectConstructDefault46 from "08089__isNativeReflectConstruct.js";


export default _isNativeReflectConstructDefault;
export const Circle = _isNativeReflectConstructDefault3;
export const ClipPath = _isNativeReflectConstructDefault4;
export const Defs = _isNativeReflectConstructDefault5;
export const Ellipse = _isNativeReflectConstructDefault6;
export const FeBlend = _isNativeReflectConstructDefault7;
export const FeColorMatrix = _isNativeReflectConstructDefault8;
export const FeComponentTransfer = _isNativeReflectConstructDefault9;
export const FeComposite = _isNativeReflectConstructDefault10;
export const FeConvolveMatrix = _isNativeReflectConstructDefault11;
export const FeDiffuseLighting = _isNativeReflectConstructDefault12;
export const FeDisplacementMap = _isNativeReflectConstructDefault13;
export const FeDistantLight = _isNativeReflectConstructDefault14;
export const FeDropShadow = _isNativeReflectConstructDefault15;
export const FeFlood = _isNativeReflectConstructDefault18;
export const FeFuncA = require("_isNativeReflectConstruct").FeFuncA;
export const FeFuncB = require("_isNativeReflectConstruct").FeFuncB;
export const FeFuncG = require("_isNativeReflectConstruct").FeFuncG;
export const FeFuncR = require("_isNativeReflectConstruct").FeFuncR;
export const FeGaussianBlur = _isNativeReflectConstructDefault16;
export const FeImage = _isNativeReflectConstructDefault21;
export const FeMerge = _isNativeReflectConstructDefault19;
export const FeMergeNode = _isNativeReflectConstructDefault20;
export const FeMorphology = _isNativeReflectConstructDefault22;
export const FeOffset = _isNativeReflectConstructDefault17;
export const FePointLight = _isNativeReflectConstructDefault23;
export const FeSpecularLighting = _isNativeReflectConstructDefault24;
export const FeSpotLight = _isNativeReflectConstructDefault25;
export const FeTile = _isNativeReflectConstructDefault26;
export const FeTurbulence = _isNativeReflectConstructDefault27;
export const Filter = _isNativeReflectConstructDefault28;
export const ForeignObject = _isNativeReflectConstructDefault29;
export const G = _isNativeReflectConstructDefault2;
export const Image = _isNativeReflectConstructDefault30;
export const Line = _isNativeReflectConstructDefault31;
export const LinearGradient = _isNativeReflectConstructDefault32;
export const Marker = _isNativeReflectConstructDefault33;
export const Mask = _isNativeReflectConstructDefault34;
export const Path = _isNativeReflectConstructDefault35;
export const Pattern = _isNativeReflectConstructDefault36;
export const Polygon = _isNativeReflectConstructDefault37;
export const Polyline = _isNativeReflectConstructDefault38;
export const RadialGradient = _isNativeReflectConstructDefault39;
export const Rect = _isNativeReflectConstructDefault40;
export const Stop = _isNativeReflectConstructDefault41;
export const Svg = _isNativeReflectConstructDefault;
export const Symbol = _isNativeReflectConstructDefault42;
export const Text = _isNativeReflectConstructDefault43;
export const TextPath = _isNativeReflectConstructDefault45;
export const TSpan = _isNativeReflectConstructDefault44;
export const Use = _isNativeReflectConstructDefault46;