// _runtime/12297_registerSpanErrorInstrumentation.js
import errorCallback from "12298_errorCallback.js";
import instrumentError from "12299_instrumentError.js";
import addHandler from "12300_addHandler.js";
import consoleSandbox from "12302_consoleSandbox.js";
import getGlobalSingleton from "12303_getGlobalSingleton.js";
import _mod12304 from "metro/12304__.js";
import createStackParser from "12305_createStackParser.js";
import instrumentUnhandledRejection from "12306_instrumentUnhandledRejection.js";
import spanTimeInputToSeconds from "12307_spanTimeInputToSeconds.js";
import addNonEnumerableProperty from "12308_addNonEnumerableProperty.js";
import isInstanceOf from "12309_isInstanceOf.js";
import _htmlElementAsString from "12310__htmlElementAsString.js";
import isMatchingPattern from "12311_isMatchingPattern.js";
import generatePropagationContext from "12312_generatePropagationContext.js";
import addContextToFrame from "12313_addContextToFrame.js";
import regExp from "12314_regExp.js";
import baggageHeaderToDynamicSamplingContext from "12315_baggageHeaderToDynamicSamplingContext.js";
import _mod12317 from "metro/12317__.js";
import getMetricSummaryJsonForSpan from "12318_getMetricSummaryJsonForSpan.js";
import getSpanStatusFromHttpCode from "12319_getSpanStatusFromHttpCode.js";
import getMainCarrier from "12320_getMainCarrier.js";
import getAsyncContextStrategy from "12321_getAsyncContextStrategy.js";
import ScopeClass from "12323_ScopeClass.js";
import updateSession from "12325_updateSession.js";
import SyncPromise from "12326_SyncPromise.js";
import getDefaultCurrentScope from "12328_getDefaultCurrentScope.js";
import getClient from "12329_getClient.js";
import getCapturedScopesOnSpan from "12331_getCapturedScopesOnSpan.js";
import addTracingExtensions from "12332_addTracingExtensions.js";
import TRACING_DEFAULTS from "12333_TRACING_DEFAULTS.js";
import hasTracingEnabled from "12334_hasTracingEnabled.js";
import SentryNonRecordingSpan from "12335_SentryNonRecordingSpan.js";
import createChildOrRootSpan from "12336_createChildOrRootSpan.js";
import handleCallbackErrors from "12337_handleCallbackErrors.js";
import getDynamicSamplingContextFromSpan from "12338_getDynamicSamplingContextFromSpan.js";
import _mod12339 from "metro/12339__.js";
import logSpanEnd from "12340_logSpanEnd.js";
import sampleSpan from "12341_sampleSpan.js";
import parseSampleRate from "12342_parseSampleRate.js";
import isFullFinishedSpan from "12343_isFullFinishedSpan.js";
import setMeasurement from "12344_setMeasurement.js";
import createEventEnvelope from "12345_createEventEnvelope.js";
import forEachEnvelopeItem from "12346_forEachEnvelopeItem.js";
import normalize from "12347_normalize.js";
import memoBuilder from "12348_memoBuilder.js";
import dsnFromString from "12349_dsnFromString.js";
import _flush from "12350__flush.js";
import applyClientOptions from "12351_applyClientOptions.js";
import applyScopeDataToEvent from "12352_applyScopeDataToEvent.js";
import notifyEventProcessors from "12353_notifyEventProcessors.js";
import getFilenameToDebugIdMap from "12354_getFilenameToDebugIdMap.js";
import SessionFlusher from "12355_SessionFlusher.js";
import getEnvelopeEndpointWithUrlEncodedAuth from "12356_getEnvelopeEndpointWithUrlEncodedAuth.js";
import isErrorEvent from "12357_isErrorEvent.js";
import setupIntegration from "12358_setupIntegration.js";
import _isNativeReflectConstruct from "12359__isNativeReflectConstruct.js";
import createClientReportEnvelope from "12360_createClientReportEnvelope.js";
import _isNativeReflectConstruct2 from "12361__isNativeReflectConstruct.js";
import eventFromMessage from "12362_eventFromMessage.js";
import createCheckInEnvelope from "12363_createCheckInEnvelope.js";
import initAndBind from "12364_initAndBind.js";
import createTransport from "12365_createTransport.js";
import makePromiseBuffer from "12366_makePromiseBuffer.js";
import parseRetryAfterHeader from "12367_parseRetryAfterHeader.js";
import MIN_DELAY from "12368_MIN_DELAY.js";
import eventFromEnvelope from "12369_eventFromEnvelope.js";
import isSentryRequestUrl from "12370_isSentryRequestUrl.js";
import parameterize from "12371_parameterize.js";
import applySdkMetadata from "12372_applySdkMetadata.js";
import getTraceData from "12373_getTraceData.js";
import getTraceMetaTags from "12374_getTraceMetaTags.js";
import addBreadcrumb from "12375_addBreadcrumb.js";
import weakMap from "12376_weakMap.js";
import _getEventFilterUrl from "12377__getEventFilterUrl.js";
import linkedErrorsIntegration from "12378_linkedErrorsIntegration.js";
import aggregateExceptionsFromError from "12379_aggregateExceptionsFromError.js";
import moduleMetadataIntegration from "12380_moduleMetadataIntegration.js";
import requestDataIntegration from "12382_requestDataIntegration.js";
import extractRequestData from "12383_extractRequestData.js";
import getNumberOfUrlSegments from "12384_getNumberOfUrlSegments.js";
import captureConsoleIntegration from "12387_captureConsoleIntegration.js";
import instrumentConsole from "12388_instrumentConsole.js";
import severityLevelFromString from "12389_severityLevelFromString.js";
import debugIntegration from "12390_debugIntegration.js";
import _shouldDropEvent from "12391__shouldDropEvent.js";
import extraErrorDataIntegration from "12392_extraErrorDataIntegration.js";
import generateIteratee from "12393_generateIteratee.js";
import resolve from "12394_resolve.js";
import sessionTimingIntegration from "12395_sessionTimingIntegration.js";
import flattenIssue from "12396_flattenIssue.js";
import thirdPartyErrorFilterIntegration from "12397_thirdPartyErrorFilterIntegration.js";
import addToMetricsAggregator from "12398_addToMetricsAggregator.js";
import _mod12400 from "metro/12400__.js";
import addToMetricsAggregator2 from "12401_addToMetricsAggregator.js";
import BrowserMetricsAggregator from "12406_BrowserMetricsAggregator.js";
import _addTracingHeadersToFetchRequest from "metro/12407__addTracingHeadersToFetchRequest.js";
import trpcMiddleware from "12408_trpcMiddleware.js";
import captureFeedback from "12409_captureFeedback.js";
import getCurrentHubShim from "12410_getCurrentHubShim.js";
import flatten from "12411_flatten.js";
import getBreadcrumbLogLevelFromHttpStatusCode from "12412_getBreadcrumbLogLevelFromHttpStatusCode.js";
import _resolveResponse from "12413__resolveResponse.js";
import supportsFetch from "12414_supportsFetch.js";
import isBrowser from "12415_isBrowser.js";
import dynamicRequire from "12416_dynamicRequire.js";
import getSDKSource from "12417_getSDKSource.js";
import filenameIsInApp from "12418_filenameIsInApp.js";
import makeFifoCache from "12419_makeFifoCache.js";
import callFrameToStackFrame from "12420_callFrameToStackFrame.js";
import LRUMap from "12421_LRUMap.js";
import vercelWaitUntil from "12422_vercelWaitUntil.js";
import escapeStringForRegex from "12423_escapeStringForRegex.js";
import supportsHistory from "12424_supportsHistory.js";
import _asyncNullishCoalesce2 from "12425__asyncNullishCoalesce2.js";
import _nullishCoalesce from "12426__nullishCoalesce.js";
import _asyncOptionalChain2 from "12427__asyncOptionalChain2.js";
import _asyncOptionalChainDelete2 from "12428__asyncOptionalChainDelete2.js";
import _optionalChain from "12429__optionalChain.js";
import _optionalChainDelete from "12430__optionalChainDelete.js";
import { dateTimestampInSeconds } from "12316_dateTimestampInSeconds.js";


export const registerSpanErrorInstrumentation = errorCallback.registerSpanErrorInstrumentation;
export const getCapturedScopesOnSpan = getCapturedScopesOnSpan.getCapturedScopesOnSpan;
export const setCapturedScopesOnSpan = getCapturedScopesOnSpan.setCapturedScopesOnSpan;
export const addTracingExtensions = addTracingExtensions.addTracingExtensions;
export const TRACING_DEFAULTS = TRACING_DEFAULTS.TRACING_DEFAULTS;
export const startIdleSpan = TRACING_DEFAULTS.startIdleSpan;
export const SentrySpan = isFullFinishedSpan.SentrySpan;
export const SentryNonRecordingSpan = SentryNonRecordingSpan.SentryNonRecordingSpan;
export const SPAN_STATUS_ERROR = getSpanStatusFromHttpCode.SPAN_STATUS_ERROR;
export const SPAN_STATUS_OK = getSpanStatusFromHttpCode.SPAN_STATUS_OK;
export const SPAN_STATUS_UNSET = getSpanStatusFromHttpCode.SPAN_STATUS_UNSET;
export const getSpanStatusFromHttpCode = getSpanStatusFromHttpCode.getSpanStatusFromHttpCode;
export const setHttpStatus = getSpanStatusFromHttpCode.setHttpStatus;
export const continueTrace = createChildOrRootSpan.continueTrace;
export const startInactiveSpan = createChildOrRootSpan.startInactiveSpan;
export const startNewTrace = createChildOrRootSpan.startNewTrace;
export const startSpan = createChildOrRootSpan.startSpan;
export const startSpanManual = createChildOrRootSpan.startSpanManual;
export const suppressTracing = createChildOrRootSpan.suppressTracing;
export const withActiveSpan = createChildOrRootSpan.withActiveSpan;
export const getDynamicSamplingContextFromClient = getDynamicSamplingContextFromSpan.getDynamicSamplingContextFromClient;
export const getDynamicSamplingContextFromScope = getDynamicSamplingContextFromSpan.getDynamicSamplingContextFromScope;
export const getDynamicSamplingContextFromSpan = getDynamicSamplingContextFromSpan.getDynamicSamplingContextFromSpan;
export const spanToBaggageHeader = getDynamicSamplingContextFromSpan.spanToBaggageHeader;
export const setMeasurement = setMeasurement.setMeasurement;
export const timedEventsToMeasurements = setMeasurement.timedEventsToMeasurements;
export const sampleSpan = sampleSpan.sampleSpan;
export const logSpanEnd = logSpanEnd.logSpanEnd;
export const logSpanStart = logSpanEnd.logSpanStart;
export const SEMANTIC_ATTRIBUTE_CACHE_HIT = _mod12317.SEMANTIC_ATTRIBUTE_CACHE_HIT;
export const SEMANTIC_ATTRIBUTE_CACHE_ITEM_SIZE = _mod12317.SEMANTIC_ATTRIBUTE_CACHE_ITEM_SIZE;
export const SEMANTIC_ATTRIBUTE_CACHE_KEY = _mod12317.SEMANTIC_ATTRIBUTE_CACHE_KEY;
export const SEMANTIC_ATTRIBUTE_EXCLUSIVE_TIME = _mod12317.SEMANTIC_ATTRIBUTE_EXCLUSIVE_TIME;
export const SEMANTIC_ATTRIBUTE_HTTP_REQUEST_METHOD = _mod12317.SEMANTIC_ATTRIBUTE_HTTP_REQUEST_METHOD;
export const SEMANTIC_ATTRIBUTE_PROFILE_ID = _mod12317.SEMANTIC_ATTRIBUTE_PROFILE_ID;
export const SEMANTIC_ATTRIBUTE_SENTRY_CUSTOM_SPAN_NAME = _mod12317.SEMANTIC_ATTRIBUTE_SENTRY_CUSTOM_SPAN_NAME;
export const SEMANTIC_ATTRIBUTE_SENTRY_IDLE_SPAN_FINISH_REASON = _mod12317.SEMANTIC_ATTRIBUTE_SENTRY_IDLE_SPAN_FINISH_REASON;
export const SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_UNIT = _mod12317.SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_UNIT;
export const SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_VALUE = _mod12317.SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_VALUE;
export const SEMANTIC_ATTRIBUTE_SENTRY_OP = _mod12317.SEMANTIC_ATTRIBUTE_SENTRY_OP;
export const SEMANTIC_ATTRIBUTE_SENTRY_ORIGIN = _mod12317.SEMANTIC_ATTRIBUTE_SENTRY_ORIGIN;
export const SEMANTIC_ATTRIBUTE_SENTRY_SAMPLE_RATE = _mod12317.SEMANTIC_ATTRIBUTE_SENTRY_SAMPLE_RATE;
export const SEMANTIC_ATTRIBUTE_SENTRY_SOURCE = _mod12317.SEMANTIC_ATTRIBUTE_SENTRY_SOURCE;
export const SEMANTIC_ATTRIBUTE_URL_FULL = _mod12317.SEMANTIC_ATTRIBUTE_URL_FULL;
export const createEventEnvelope = createEventEnvelope.createEventEnvelope;
export const createSessionEnvelope = createEventEnvelope.createSessionEnvelope;
export const createSpanEnvelope = createEventEnvelope.createSpanEnvelope;
export const addEventProcessor = _flush.addEventProcessor;
export const captureCheckIn = _flush.captureCheckIn;
export const captureEvent = _flush.captureEvent;
export const captureException = _flush.captureException;
export const captureMessage = _flush.captureMessage;
export const captureSession = _flush.captureSession;
export const close = _flush.close;
export const endSession = _flush.endSession;
export const flush = _flush.flush;
export const isEnabled = _flush.isEnabled;
export const isInitialized = _flush.isInitialized;
export const lastEventId = _flush.lastEventId;
export const setContext = _flush.setContext;
export const setExtra = _flush.setExtra;
export const setExtras = _flush.setExtras;
export const setTag = _flush.setTag;
export const setTags = _flush.setTags;
export const setUser = _flush.setUser;
export const startSession = _flush.startSession;
export const withMonitor = _flush.withMonitor;
export const getClient = getClient.getClient;
export const getCurrentScope = getClient.getCurrentScope;
export const getGlobalScope = getClient.getGlobalScope;
export const getIsolationScope = getClient.getIsolationScope;
export const getTraceContextFromScope = getClient.getTraceContextFromScope;
export const withIsolationScope = getClient.withIsolationScope;
export const withScope = getClient.withScope;
export const getDefaultCurrentScope = getDefaultCurrentScope.getDefaultCurrentScope;
export const getDefaultIsolationScope = getDefaultCurrentScope.getDefaultIsolationScope;
export const setAsyncContextStrategy = getAsyncContextStrategy.setAsyncContextStrategy;
export const getMainCarrier = getMainCarrier.getMainCarrier;
export const closeSession = updateSession.closeSession;
export const makeSession = updateSession.makeSession;
export const updateSession = updateSession.updateSession;
export const SessionFlusher = SessionFlusher.SessionFlusher;
export const Scope = ScopeClass.Scope;
export const notifyEventProcessors = notifyEventProcessors.notifyEventProcessors;
export const getEnvelopeEndpointWithUrlEncodedAuth = getEnvelopeEndpointWithUrlEncodedAuth.getEnvelopeEndpointWithUrlEncodedAuth;
export const getReportDialogEndpoint = getEnvelopeEndpointWithUrlEncodedAuth.getReportDialogEndpoint;
export const BaseClient = isErrorEvent.BaseClient;
export const ServerRuntimeClient = _isNativeReflectConstruct2.ServerRuntimeClient;
export const initAndBind = initAndBind.initAndBind;
export const setCurrentClient = initAndBind.setCurrentClient;
export const createTransport = createTransport.createTransport;
export const makeOfflineTransport = MIN_DELAY.makeOfflineTransport;
export const makeMultiplexedTransport = eventFromEnvelope.makeMultiplexedTransport;
export const addIntegration = setupIntegration.addIntegration;
export const defineIntegration = setupIntegration.defineIntegration;
export const getIntegrationsToSetup = setupIntegration.getIntegrationsToSetup;
export const applyScopeDataToEvent = applyScopeDataToEvent.applyScopeDataToEvent;
export const mergeScopeData = applyScopeDataToEvent.mergeScopeData;
export const prepareEvent = applyClientOptions.prepareEvent;
export const createCheckInEnvelope = createCheckInEnvelope.createCheckInEnvelope;
export const hasTracingEnabled = hasTracingEnabled.hasTracingEnabled;
export const isSentryRequestUrl = isSentryRequestUrl.isSentryRequestUrl;
export const handleCallbackErrors = handleCallbackErrors.handleCallbackErrors;
export const parameterize = parameterize.parameterize;
export const addChildSpanToSpan = spanTimeInputToSeconds.addChildSpanToSpan;
export const getActiveSpan = spanTimeInputToSeconds.getActiveSpan;
export const getRootSpan = spanTimeInputToSeconds.getRootSpan;
export const getSpanDescendants = spanTimeInputToSeconds.getSpanDescendants;
export const getStatusMessage = spanTimeInputToSeconds.getStatusMessage;
export const spanIsSampled = spanTimeInputToSeconds.spanIsSampled;
export const spanTimeInputToSeconds = spanTimeInputToSeconds.spanTimeInputToSeconds;
export const spanToJSON = spanTimeInputToSeconds.spanToJSON;
export const spanToTraceContext = spanTimeInputToSeconds.spanToTraceContext;
export const spanToTraceHeader = spanTimeInputToSeconds.spanToTraceHeader;
export const updateSpanName = spanTimeInputToSeconds.updateSpanName;
export const parseSampleRate = parseSampleRate.parseSampleRate;
export const applySdkMetadata = applySdkMetadata.applySdkMetadata;
export const getTraceData = getTraceData.getTraceData;
export const getTraceMetaTags = getTraceMetaTags.getTraceMetaTags;
export const DEFAULT_ENVIRONMENT = _mod12339.DEFAULT_ENVIRONMENT;
export const addBreadcrumb = addBreadcrumb.addBreadcrumb;
export const functionToStringIntegration = weakMap.functionToStringIntegration;
export const inboundFiltersIntegration = _getEventFilterUrl.inboundFiltersIntegration;
export const linkedErrorsIntegration = linkedErrorsIntegration.linkedErrorsIntegration;
export const moduleMetadataIntegration = moduleMetadataIntegration.moduleMetadataIntegration;
export const requestDataIntegration = requestDataIntegration.requestDataIntegration;
export const captureConsoleIntegration = captureConsoleIntegration.captureConsoleIntegration;
export const debugIntegration = debugIntegration.debugIntegration;
export const dedupeIntegration = _shouldDropEvent.dedupeIntegration;
export const extraErrorDataIntegration = extraErrorDataIntegration.extraErrorDataIntegration;
export const rewriteFramesIntegration = generateIteratee.rewriteFramesIntegration;
export const sessionTimingIntegration = sessionTimingIntegration.sessionTimingIntegration;
export const zodErrorsIntegration = flattenIssue.zodErrorsIntegration;
export const thirdPartyErrorFilterIntegration = thirdPartyErrorFilterIntegration.thirdPartyErrorFilterIntegration;
export const metrics = addToMetricsAggregator.metrics;
export const profiler = _mod12400.profiler;
export const metricsDefault = addToMetricsAggregator2.metricsDefault;
export const BrowserMetricsAggregator = BrowserMetricsAggregator.BrowserMetricsAggregator;
export const getMetricSummaryJsonForSpan = getMetricSummaryJsonForSpan.getMetricSummaryJsonForSpan;
export const addTracingHeadersToFetchRequest = _addTracingHeadersToFetchRequest.addTracingHeadersToFetchRequest;
export const instrumentFetchRequest = _addTracingHeadersToFetchRequest.instrumentFetchRequest;
export const trpcMiddleware = trpcMiddleware.trpcMiddleware;
export const captureFeedback = captureFeedback.captureFeedback;
export const getCurrentHub = getCurrentHubShim.getCurrentHub;
export const getCurrentHubShim = getCurrentHubShim.getCurrentHubShim;
export const applyAggregateErrorsToEvent = aggregateExceptionsFromError.applyAggregateErrorsToEvent;
export const flatten = flatten.flatten;
export const getBreadcrumbLogLevelFromHttpStatusCode = getBreadcrumbLogLevelFromHttpStatusCode.getBreadcrumbLogLevelFromHttpStatusCode;
export const getComponentName = _htmlElementAsString.getComponentName;
export const getDomElement = _htmlElementAsString.getDomElement;
export const getLocationHref = _htmlElementAsString.getLocationHref;
export const htmlTreeAsString = _htmlElementAsString.htmlTreeAsString;
export const dsnFromString = dsnFromString.dsnFromString;
export const dsnToString = dsnFromString.dsnToString;
export const makeDsn = dsnFromString.makeDsn;
export const SentryError = _isNativeReflectConstruct.SentryError;
export const GLOBAL_OBJ = getGlobalSingleton.GLOBAL_OBJ;
export const getGlobalSingleton = getGlobalSingleton.getGlobalSingleton;
export const addConsoleInstrumentationHandler = instrumentConsole.addConsoleInstrumentationHandler;
export const addFetchEndInstrumentationHandler = _resolveResponse.addFetchEndInstrumentationHandler;
export const addFetchInstrumentationHandler = _resolveResponse.addFetchInstrumentationHandler;
export const addGlobalErrorInstrumentationHandler = instrumentError.addGlobalErrorInstrumentationHandler;
export const addGlobalUnhandledRejectionInstrumentationHandler = instrumentUnhandledRejection.addGlobalUnhandledRejectionInstrumentationHandler;
export const addHandler = addHandler.addHandler;
export const maybeInstrument = addHandler.maybeInstrument;
export const resetInstrumentationHandlers = addHandler.resetInstrumentationHandlers;
export const triggerHandlers = addHandler.triggerHandlers;
export const isDOMError = isInstanceOf.isDOMError;
export const isDOMException = isInstanceOf.isDOMException;
export const isElement = isInstanceOf.isElement;
export const isError = isInstanceOf.isError;
export const isErrorEvent = isInstanceOf.isErrorEvent;
export const isEvent = isInstanceOf.isEvent;
export const isInstanceOf = isInstanceOf.isInstanceOf;
export const isParameterizedString = isInstanceOf.isParameterizedString;
export const isPlainObject = isInstanceOf.isPlainObject;
export const isPrimitive = isInstanceOf.isPrimitive;
export const isRegExp = isInstanceOf.isRegExp;
export const isString = isInstanceOf.isString;
export const isSyntheticEvent = isInstanceOf.isSyntheticEvent;
export const isThenable = isInstanceOf.isThenable;
export const isVueViewModel = isInstanceOf.isVueViewModel;
export const isBrowser = isBrowser.isBrowser;
export const CONSOLE_LEVELS = consoleSandbox.CONSOLE_LEVELS;
export const consoleSandbox = consoleSandbox.consoleSandbox;
export const logger = consoleSandbox.logger;
export const originalConsoleMethods = consoleSandbox.originalConsoleMethods;
export const memoBuilder = memoBuilder.memoBuilder;
export const addContextToFrame = addContextToFrame.addContextToFrame;
export const addExceptionMechanism = addContextToFrame.addExceptionMechanism;
export const addExceptionTypeValue = addContextToFrame.addExceptionTypeValue;
export const arrayify = addContextToFrame.arrayify;
export const checkOrSetAlreadyCaught = addContextToFrame.checkOrSetAlreadyCaught;
export const getEventDescription = addContextToFrame.getEventDescription;
export const parseSemver = addContextToFrame.parseSemver;
export const uuid4 = addContextToFrame.uuid4;
export const dynamicRequire = dynamicRequire.dynamicRequire;
export const isNodeEnv = dynamicRequire.isNodeEnv;
export const loadModule = dynamicRequire.loadModule;
export const normalize = normalize.normalize;
export const normalizeToSize = normalize.normalizeToSize;
export const normalizeUrlToBase = normalize.normalizeUrlToBase;
export const addNonEnumerableProperty = addNonEnumerableProperty.addNonEnumerableProperty;
export const convertToPlainObject = addNonEnumerableProperty.convertToPlainObject;
export const dropUndefinedKeys = addNonEnumerableProperty.dropUndefinedKeys;
export const extractExceptionKeysForMessage = addNonEnumerableProperty.extractExceptionKeysForMessage;
export const fill = addNonEnumerableProperty.fill;
export const getOriginalFunction = addNonEnumerableProperty.getOriginalFunction;
export const markFunctionWrapped = addNonEnumerableProperty.markFunctionWrapped;
export const objectify = addNonEnumerableProperty.objectify;
export const urlEncode = addNonEnumerableProperty.urlEncode;
export const basename = resolve.basename;
export const dirname = resolve.dirname;
export const isAbsolute = resolve.isAbsolute;
export const join = resolve.join;
export const normalizePath = resolve.normalizePath;
export const relative = resolve.relative;
export const resolve = resolve.resolve;
export const makePromiseBuffer = makePromiseBuffer.makePromiseBuffer;
export const DEFAULT_USER_INCLUDES = extractRequestData.DEFAULT_USER_INCLUDES;
export const addNormalizedRequestDataToEvent = extractRequestData.addNormalizedRequestDataToEvent;
export const addRequestDataToEvent = extractRequestData.addRequestDataToEvent;
export const extractPathForTransaction = extractRequestData.extractPathForTransaction;
export const extractQueryParamsFromUrl = extractRequestData.extractQueryParamsFromUrl;
export const extractRequestData = extractRequestData.extractRequestData;
export const headersToDict = extractRequestData.headersToDict;
export const httpRequestToRequestData = extractRequestData.httpRequestToRequestData;
export const winterCGHeadersToDict = extractRequestData.winterCGHeadersToDict;
export const winterCGRequestToRequestData = extractRequestData.winterCGRequestToRequestData;
export const severityLevelFromString = severityLevelFromString.severityLevelFromString;
export const validSeverityLevels = severityLevelFromString.validSeverityLevels;
export const UNKNOWN_FUNCTION = createStackParser.UNKNOWN_FUNCTION;
export const createStackParser = createStackParser.createStackParser;
export const getFramesFromEvent = createStackParser.getFramesFromEvent;
export const getFunctionName = createStackParser.getFunctionName;
export const stackParserFromStackParserOptions = createStackParser.stackParserFromStackParserOptions;
export const stripSentryFramesAndReverse = createStackParser.stripSentryFramesAndReverse;
export const filenameIsInApp = filenameIsInApp.filenameIsInApp;
export const node = filenameIsInApp.node;
export const nodeStackLineParser = filenameIsInApp.nodeStackLineParser;
export const isMatchingPattern = isMatchingPattern.isMatchingPattern;
export const safeJoin = isMatchingPattern.safeJoin;
export const snipLine = isMatchingPattern.snipLine;
export const stringMatchesSomePattern = isMatchingPattern.stringMatchesSomePattern;
export const truncate = isMatchingPattern.truncate;
export const isNativeFunction = supportsFetch.isNativeFunction;
export const supportsDOMError = supportsFetch.supportsDOMError;
export const supportsDOMException = supportsFetch.supportsDOMException;
export const supportsErrorEvent = supportsFetch.supportsErrorEvent;
export const supportsFetch = supportsFetch.supportsFetch;
export const supportsNativeFetch = supportsFetch.supportsNativeFetch;
export const supportsReferrerPolicy = supportsFetch.supportsReferrerPolicy;
export const supportsReportingObserver = supportsFetch.supportsReportingObserver;
export const SyncPromise = SyncPromise.SyncPromise;
export const rejectedSyncPromise = SyncPromise.rejectedSyncPromise;
export const resolvedSyncPromise = SyncPromise.resolvedSyncPromise;
export const _browserPerformanceTimeOriginMode = dateTimestampInSeconds /* dateTimestampInSeconds */._browserPerformanceTimeOriginMode;
export const browserPerformanceTimeOrigin = require("dateTimestampInSeconds").browserPerformanceTimeOrigin;
export const dateTimestampInSeconds = require("dateTimestampInSeconds").dateTimestampInSeconds;
export const timestampInSeconds = require("dateTimestampInSeconds").timestampInSeconds;
export const TRACEPARENT_REGEXP = regExp.TRACEPARENT_REGEXP;
export const extractTraceparentData = regExp.extractTraceparentData;
export const generateSentryTraceHeader = regExp.generateSentryTraceHeader;
export const propagationContextFromHeaders = regExp.propagationContextFromHeaders;
export const getSDKSource = getSDKSource.getSDKSource;
export const isBrowserBundle = getSDKSource.isBrowserBundle;
export const addItemToEnvelope = forEachEnvelopeItem.addItemToEnvelope;
export const createAttachmentEnvelopeItem = forEachEnvelopeItem.createAttachmentEnvelopeItem;
export const createEnvelope = forEachEnvelopeItem.createEnvelope;
export const createEventEnvelopeHeaders = forEachEnvelopeItem.createEventEnvelopeHeaders;
export const createSpanEnvelopeItem = forEachEnvelopeItem.createSpanEnvelopeItem;
export const envelopeContainsItemType = forEachEnvelopeItem.envelopeContainsItemType;
export const envelopeItemTypeToDataCategory = forEachEnvelopeItem.envelopeItemTypeToDataCategory;
export const forEachEnvelopeItem = forEachEnvelopeItem.forEachEnvelopeItem;
export const getSdkMetadataForEnvelopeHeader = forEachEnvelopeItem.getSdkMetadataForEnvelopeHeader;
export const parseEnvelope = forEachEnvelopeItem.parseEnvelope;
export const serializeEnvelope = forEachEnvelopeItem.serializeEnvelope;
export const createClientReportEnvelope = createClientReportEnvelope.createClientReportEnvelope;
export const DEFAULT_RETRY_AFTER = parseRetryAfterHeader.DEFAULT_RETRY_AFTER;
export const disabledUntil = parseRetryAfterHeader.disabledUntil;
export const isRateLimited = parseRetryAfterHeader.isRateLimited;
export const parseRetryAfterHeader = parseRetryAfterHeader.parseRetryAfterHeader;
export const updateRateLimits = parseRetryAfterHeader.updateRateLimits;
export const BAGGAGE_HEADER_NAME = baggageHeaderToDynamicSamplingContext.BAGGAGE_HEADER_NAME;
export const MAX_BAGGAGE_STRING_LENGTH = baggageHeaderToDynamicSamplingContext.MAX_BAGGAGE_STRING_LENGTH;
export const SENTRY_BAGGAGE_KEY_PREFIX = baggageHeaderToDynamicSamplingContext.SENTRY_BAGGAGE_KEY_PREFIX;
export const SENTRY_BAGGAGE_KEY_PREFIX_REGEX = baggageHeaderToDynamicSamplingContext.SENTRY_BAGGAGE_KEY_PREFIX_REGEX;
export const baggageHeaderToDynamicSamplingContext = baggageHeaderToDynamicSamplingContext.baggageHeaderToDynamicSamplingContext;
export const dynamicSamplingContextToSentryBaggageHeader = baggageHeaderToDynamicSamplingContext.dynamicSamplingContextToSentryBaggageHeader;
export const parseBaggageHeader = baggageHeaderToDynamicSamplingContext.parseBaggageHeader;
export const getNumberOfUrlSegments = getNumberOfUrlSegments.getNumberOfUrlSegments;
export const getSanitizedUrlString = getNumberOfUrlSegments.getSanitizedUrlString;
export const parseUrl = getNumberOfUrlSegments.parseUrl;
export const stripUrlQueryAndFragment = getNumberOfUrlSegments.stripUrlQueryAndFragment;
export const makeFifoCache = makeFifoCache.makeFifoCache;
export const eventFromMessage = eventFromMessage.eventFromMessage;
export const eventFromUnknownInput = eventFromMessage.eventFromUnknownInput;
export const exceptionFromError = eventFromMessage.exceptionFromError;
export const parseStackFrames = eventFromMessage.parseStackFrames;
export const callFrameToStackFrame = callFrameToStackFrame.callFrameToStackFrame;
export const watchdogTimer = callFrameToStackFrame.watchdogTimer;
export const LRUMap = LRUMap.LRUMap;
export const generatePropagationContext = generatePropagationContext.generatePropagationContext;
export const generateSpanId = generatePropagationContext.generateSpanId;
export const generateTraceId = generatePropagationContext.generateTraceId;
export const vercelWaitUntil = vercelWaitUntil.vercelWaitUntil;
export const SDK_VERSION = _mod12304.SDK_VERSION;
export const getDebugImagesForResources = getFilenameToDebugIdMap.getDebugImagesForResources;
export const getFilenameToDebugIdMap = getFilenameToDebugIdMap.getFilenameToDebugIdMap;
export const escapeStringForRegex = escapeStringForRegex.escapeStringForRegex;
export const supportsHistory = supportsHistory.supportsHistory;
export const _asyncNullishCoalesce = _asyncNullishCoalesce2._asyncNullishCoalesce;
export const _asyncOptionalChain = _asyncOptionalChain2._asyncOptionalChain;
export const _asyncOptionalChainDelete = _asyncOptionalChainDelete2._asyncOptionalChainDelete;
export const _nullishCoalesce = _nullishCoalesce._nullishCoalesce;
export const _optionalChain = _optionalChain._optionalChain;
export const _optionalChainDelete = _optionalChainDelete._optionalChainDelete;