// discord_app/modules/feedback/FeedbackUtils.tsx
import FeedbackRating from "FeedbackRating";
import { AnalyticEvents } from "ME";

let c10;
let c3;
let c4;
let c5;
let c9;
let closure_6;
let error;
let metroImportAll;
let unpackModuleId;
({ ConnectionFeedbackOption: c3, AudioFeedbackOption: c4, VideoFeedbackOption: c5, VideoBackgroundFeedbackOption: closure_6, StreamFeedbackOption: error, FeedbackOptionVariant: metroImportAll, FeedbackType: c9, MAX_REPRESENTABLE_DATE: c10, PeopleFeedbackOption: unpackModuleId } = FeedbackRating);
const result = require("apply").fileFinishedImporting("modules/feedback/FeedbackUtils.tsx");

export const shuffleProblems = function shuffleProblems(outer1_7, otherKey) {
  let closure_0 = otherKey;
  const shuffleResult = require("../../../_runtime/00012_apply.js").shuffle(outer1_7);
  const findIndexResult = shuffleResult.findIndex((value) => value.value === closure_0);
  if (findIndexResult > -1) {
    shuffleResult.splice(findIndexResult, 1);
    shuffleResult.push(shuffleResult[findIndexResult]);
  }
  return shuffleResult;
};
export const processOptOut = function processOptOut(feedbackType) {
  feedbackType = feedbackType.feedbackType;
  let obj = require("../../utils/AnalyticsUtils.tsx");
  obj = { feedback_type: table[feedbackType], opted_out_until: closure_10 };
  obj.track(AnalyticEvents.USER_SETTINGS_IN_APP_FEEDBACK_OPTED_OUT, obj);
  const InAppFeedbackStates = feedbackType(3958).InAppFeedbackStates;
  InAppFeedbackStates.updateSetting((arg0) => {
    let obj = {};
    const merged = Object.assign(arg0);
    obj = {};
    const merged1 = Object.assign(arg0[feedbackType]);
    obj.optOutExpiryTime = outer1_10;
    obj[feedbackType] = obj;
    return obj;
  });
};
export const getConnectionFeedbackOptions = function getConnectionFeedbackOptions() {
  let obj = { variant: constants6.SELF, value: constants.COULD_NOT_CONNECT, label: null };
  const intl = require("../../intl/index.native.tsx") /* getSystemLocale */.intl;
  obj[2] = intl.string(require("intl/Feedback.messages.js").gMHKDJ);
  const items = [obj, , , , , ];
  obj = { value: constants.HIGH_TTC, variant: constants6.SELF, label: null };
  const intl2 = require("../../intl/index.native.tsx") /* getSystemLocale */.intl;
  obj[2] = intl2.string(require("intl/Feedback.messages.js").y06Ayn);
  items[1] = obj;
  obj = { value: constants.HIGH_LATENCY, variant: constants6.SELF, label: null };
  const intl3 = require("../../intl/index.native.tsx") /* getSystemLocale */.intl;
  obj[2] = intl3.string(require("intl/Feedback.messages.js").y5k8Jq);
  items[2] = obj;
  const obj1 = { value: constants.ROBOT_VOICE, variant: constants6.SOMEONE, label: null };
  const intl4 = require("../../intl/index.native.tsx") /* getSystemLocale */.intl;
  obj1[2] = intl4.string(require("intl/Feedback.messages.js").f2914v);
  items[3] = obj1;
  const obj2 = { value: constants.DESYNC, variant: constants6.UNSPECIFIED, label: null };
  const intl5 = require("../../intl/index.native.tsx") /* getSystemLocale */.intl;
  obj2[2] = intl5.string(require("intl/Feedback.messages.js")["zk+QL1"]);
  items[4] = obj2;
  const obj3 = { value: constants.CUTTING, variant: constants6.SOMEONE, label: null };
  const intl6 = require("../../intl/index.native.tsx") /* getSystemLocale */.intl;
  obj3[2] = intl6.string(require("intl/Feedback.messages.js").K5vYQA);
  items[5] = obj3;
  const found = items.filter((disabled) => !disabled.disabled);
  return found.map((arg0) => Object.assign(arg0, Object.create(null)));
};
export const getAudioFeedbackOptions = function getAudioFeedbackOptions(isMobile) {
  let obj = { value: constants2.NO_AUDIO, variant: constants6.SELF, label: null };
  const intl = require("../../intl/index.native.tsx") /* getSystemLocale */.intl;
  obj[2] = intl.string(require("intl/Feedback.messages.js")["GWypH+"]);
  const items = [obj, , , , , , , , , , , , ];
  obj = { value: constants2.NO_AUDIO, variant: constants6.OTHERS, label: null };
  const intl2 = require("../../intl/index.native.tsx") /* getSystemLocale */.intl;
  obj[2] = intl2.string(require("intl/Feedback.messages.js").ftSvQ0);
  items[1] = obj;
  obj = { value: constants2.LOW_QUALITY_AUDIO, variant: constants6.OTHERS, label: null };
  const intl3 = require("../../intl/index.native.tsx") /* getSystemLocale */.intl;
  obj[2] = intl3.string(require("intl/Feedback.messages.js")["1DnNRO"]);
  items[2] = obj;
  const obj1 = { value: constants2.ROBOT_VOICE, variant: constants6.SOMEONE, label: null };
  const intl4 = require("../../intl/index.native.tsx") /* getSystemLocale */.intl;
  obj1[2] = intl4.string(require("intl/Feedback.messages.js").yGe0BL);
  items[3] = obj1;
  const obj2 = { value: constants2.ECHO, variant: constants6.OTHERS, label: null };
  const intl5 = require("../../intl/index.native.tsx") /* getSystemLocale */.intl;
  obj2[2] = intl5.string(require("intl/Feedback.messages.js").Q5Dsaz);
  items[4] = obj2;
  const obj3 = { value: constants2.TOO_QUIET_OR_LOUD, variant: constants6.SOMEONE, label: null };
  const intl6 = require("../../intl/index.native.tsx") /* getSystemLocale */.intl;
  obj3[2] = intl6.string(require("intl/Feedback.messages.js")["1o77I3"]);
  items[5] = obj3;
  const obj4 = { value: constants2.CUTTING, variant: constants6.SOMEONE, label: null };
  const intl7 = require("../../intl/index.native.tsx") /* getSystemLocale */.intl;
  obj4[2] = intl7.string(require("intl/Feedback.messages.js").RK9DUi);
  items[6] = obj4;
  const obj5 = { value: constants2.DELAYED, variant: constants6.UNSPECIFIED, label: null };
  const intl8 = require("../../intl/index.native.tsx") /* getSystemLocale */.intl;
  obj5[2] = intl8.string(require("intl/Feedback.messages.js").RGRgmM);
  items[7] = obj5;
  const obj6 = { value: constants2.BACKGROUND_NOISE, variant: constants6.SOMEONE, label: null };
  const intl9 = require("../../intl/index.native.tsx") /* getSystemLocale */.intl;
  obj6[2] = intl9.string(require("intl/Feedback.messages.js")["anHk1/"]);
  items[8] = obj6;
  const obj7 = { value: constants2.UNABLE_TO_FIND_DEVICE, variant: constants6.SELF, label: null };
  const intl10 = require("../../intl/index.native.tsx") /* getSystemLocale */.intl;
  obj7[2] = intl10.string(require("intl/Feedback.messages.js")["05VSjm"]);
  items[9] = obj7;
  const obj8 = { value: constants2.COMPLAINTS, variant: constants6.OTHERS, label: null };
  const intl11 = require("../../intl/index.native.tsx") /* getSystemLocale */.intl;
  obj8[2] = intl11.string(require("intl/Feedback.messages.js").kbbtwi);
  items[10] = obj8;
  const obj9 = { value: constants2.TROUBLE_WITH_SPEAKERPHONE, variant: constants6.SELF, label: null, disabled: null };
  const intl12 = require("../../intl/index.native.tsx") /* getSystemLocale */.intl;
  obj9[2] = intl12.string(require("intl/Feedback.messages.js")["4qlGrO"]);
  obj9[3] = !isMobile.isMobile;
  items[11] = obj9;
  const obj10 = { value: constants2.NO_GAME_AUDIO, variant: constants6.SELF, label: null };
  const intl13 = require("../../intl/index.native.tsx") /* getSystemLocale */.intl;
  obj10[2] = intl13.string(require("intl/Feedback.messages.js")["2IG95D"]);
  items[12] = obj10;
  const found = items.filter((disabled) => !disabled.disabled);
  return found.map((arg0) => Object.assign(arg0, Object.create(null)));
};
export const getVideoFeedbackOptions = function getVideoFeedbackOptions() {
  let obj = { value: constants3.NO_VIDEO, variant: constants6.SELF, label: null };
  const intl = require("../../intl/index.native.tsx") /* getSystemLocale */.intl;
  obj[2] = intl.string(require("intl/Feedback.messages.js")["Bh+02d"]);
  const items = [obj, , , , , ];
  obj = { value: constants3.NO_VIDEO, variant: constants6.SOMEONE, label: null };
  const intl2 = require("../../intl/index.native.tsx") /* getSystemLocale */.intl;
  obj[2] = intl2.string(require("intl/Feedback.messages.js")["R+wqwU"]);
  items[1] = obj;
  obj = { value: constants3.FREEZING_OR_HITCHING, variant: constants6.SOMEONE, label: null };
  const intl3 = require("../../intl/index.native.tsx") /* getSystemLocale */.intl;
  obj[2] = intl3.string(require("intl/Feedback.messages.js")["8I/GUL"]);
  items[2] = obj;
  const obj1 = { value: constants3.BLURRY_OR_PIXELATED, variant: constants6.SOMEONE, label: null };
  const intl4 = require("../../intl/index.native.tsx") /* getSystemLocale */.intl;
  obj1[2] = intl4.string(require("intl/Feedback.messages.js").k7Idoz);
  items[3] = obj1;
  const obj2 = { value: constants3.UNABLE_TO_ENABLE_DEVICE, variant: constants6.SELF, label: null };
  const intl5 = require("../../intl/index.native.tsx") /* getSystemLocale */.intl;
  obj2[2] = intl5.string(require("intl/Feedback.messages.js").QbC6La);
  items[4] = obj2;
  const obj3 = { value: constants3.DESYNC, variant: constants6.UNSPECIFIED, label: null };
  const intl6 = require("../../intl/index.native.tsx") /* getSystemLocale */.intl;
  obj3[2] = intl6.string(require("intl/Feedback.messages.js").vRDE5O);
  items[5] = obj3;
  const found = items.filter((disabled) => !disabled.disabled);
  return found.map((arg0) => Object.assign(arg0, Object.create(null)));
};
export const getVideoBackgroundFeedbackOptions = function getVideoBackgroundFeedbackOptions() {
  let obj = { value: constants4.OUTLINE_FUZZY_OR_HALO, variant: constants6.SELF, label: null };
  const intl = require("../../intl/index.native.tsx") /* getSystemLocale */.intl;
  obj[2] = intl.string(require("intl/Feedback.messages.js").calUNv);
  const items = [obj, , , ];
  obj = { value: constants4.INACCURATE_BACKGROUND_DETECTION, variant: constants6.SELF, label: null };
  const intl2 = require("../../intl/index.native.tsx") /* getSystemLocale */.intl;
  obj[2] = intl2.string(require("intl/Feedback.messages.js").zYumoj);
  items[1] = obj;
  obj = { value: constants4.FLICKERING_ARTIFACTS, variant: constants6.SELF, label: null };
  const intl3 = require("../../intl/index.native.tsx") /* getSystemLocale */.intl;
  obj[2] = intl3.string(require("intl/Feedback.messages.js").ie5nCG);
  items[2] = obj;
  const obj1 = { value: constants4.LAG_ON_MOVEMENT, variant: constants6.SELF, label: null };
  const intl4 = require("../../intl/index.native.tsx") /* getSystemLocale */.intl;
  obj1[2] = intl4.string(require("intl/Feedback.messages.js")["Gg/Y1X"]);
  items[3] = obj1;
  const found = items.filter((disabled) => !disabled.disabled);
  return found.map((arg0) => Object.assign(arg0, Object.create(null)));
};
export const getStreamFeedbackOptions = function getStreamFeedbackOptions(isStreamer) {
  isStreamer = isStreamer.isStreamer;
  let obj = { value: constants5.COULD_NOT_LOAD, variant: constants6.SELF, label: null, disabled: null };
  const intl = require("../../intl/index.native.tsx") /* getSystemLocale */.intl;
  obj[2] = intl.string(require("intl/Feedback.messages.js")["w+kiDF"]);
  obj[3] = !isStreamer;
  const items = [obj, , , , , , , , , , , , , , , , , , ];
  obj = { value: constants5.BLACK_SCREEN, variant: constants6.SELF, label: null, disabled: null };
  const intl2 = require("../../intl/index.native.tsx") /* getSystemLocale */.intl;
  obj[2] = intl2.string(require("intl/Feedback.messages.js").RRZZZb);
  obj[3] = !isStreamer;
  items[1] = obj;
  obj = { value: constants5.FREEZING_OR_HITCHING, variant: constants6.SELF, label: null, disabled: null };
  const intl3 = require("../../intl/index.native.tsx") /* getSystemLocale */.intl;
  obj[2] = intl3.string(require("intl/Feedback.messages.js")["3PKSkd"]);
  obj[3] = !isStreamer;
  items[2] = obj;
  const obj1 = { value: constants5.LAG, variant: constants6.SELF, label: null, disabled: null };
  const intl4 = require("../../intl/index.native.tsx") /* getSystemLocale */.intl;
  obj1[2] = intl4.string(require("intl/Feedback.messages.js").iMxexK);
  obj1[3] = !isStreamer;
  items[3] = obj1;
  const obj2 = { value: constants5.BLURRY_OR_PIXELATED, variant: constants6.SELF, label: null, disabled: null };
  const intl5 = require("../../intl/index.native.tsx") /* getSystemLocale */.intl;
  obj2[2] = intl5.string(require("intl/Feedback.messages.js")["8ceyQy"]);
  obj2[3] = !isStreamer;
  items[4] = obj2;
  const obj3 = { value: constants5.NO_AUDIO, variant: constants6.SELF, label: null, disabled: null };
  const intl6 = require("../../intl/index.native.tsx") /* getSystemLocale */.intl;
  obj3[2] = intl6.string(require("intl/Feedback.messages.js").HaZSC3);
  obj3[3] = !isStreamer;
  items[5] = obj3;
  const obj4 = { value: constants5.BAD_AUDIO, variant: constants6.SELF, label: null, disabled: null };
  const intl7 = require("../../intl/index.native.tsx") /* getSystemLocale */.intl;
  obj4[2] = intl7.string(require("intl/Feedback.messages.js")["zIC+8Y"]);
  obj4[3] = !isStreamer;
  items[6] = obj4;
  const obj5 = { value: constants5.STOPPED_UNEXPECTEDLY, variant: constants6.SELF, label: null, disabled: null };
  const intl8 = require("../../intl/index.native.tsx") /* getSystemLocale */.intl;
  obj5[2] = intl8.string(require("intl/Feedback.messages.js")["/nlKuG"]);
  obj5[3] = !isStreamer;
  items[7] = obj5;
  const obj6 = { value: constants5.DESYNC, variant: constants6.SELF, label: null, disabled: null };
  const intl9 = require("../../intl/index.native.tsx") /* getSystemLocale */.intl;
  obj6[2] = intl9.string(require("intl/Feedback.messages.js").JS6akP);
  obj6[3] = !isStreamer;
  items[8] = obj6;
  const obj7 = { value: constants5.NO_GAME_AUDIO, variant: constants6.SELF, label: null, disabled: null };
  const intl10 = require("../../intl/index.native.tsx") /* getSystemLocale */.intl;
  obj7[2] = intl10.string(require("intl/Feedback.messages.js").TaIrh5);
  obj7[3] = !isStreamer;
  items[9] = obj7;
  const obj8 = { value: constants5.COULD_NOT_LOAD, variant: constants6.SOMEONE, label: null, disabled: null };
  const intl11 = require("../../intl/index.native.tsx") /* getSystemLocale */.intl;
  obj8[2] = intl11.string(require("intl/Feedback.messages.js").jU9Zs8);
  obj8[3] = isStreamer;
  items[10] = obj8;
  const obj9 = { value: constants5.BLACK_SCREEN, variant: constants6.SOMEONE, label: null, disabled: null };
  const intl12 = require("../../intl/index.native.tsx") /* getSystemLocale */.intl;
  obj9[2] = intl12.string(require("intl/Feedback.messages.js").aml28x);
  obj9[3] = isStreamer;
  items[11] = obj9;
  const obj10 = { value: constants5.FREEZING_OR_HITCHING, variant: constants6.SOMEONE, label: null, disabled: null };
  const intl13 = require("../../intl/index.native.tsx") /* getSystemLocale */.intl;
  obj10[2] = intl13.string(require("intl/Feedback.messages.js").V3EeCH);
  obj10[3] = isStreamer;
  items[12] = obj10;
  const obj11 = { value: constants5.LAG, variant: constants6.SOMEONE, label: null, disabled: null };
  const intl14 = require("../../intl/index.native.tsx") /* getSystemLocale */.intl;
  obj11[2] = intl14.string(require("intl/Feedback.messages.js").hi1Y39);
  obj11[3] = isStreamer;
  items[13] = obj11;
  const obj12 = { value: constants5.BLURRY_OR_PIXELATED, variant: constants6.SOMEONE, label: null, disabled: null };
  const intl15 = require("../../intl/index.native.tsx") /* getSystemLocale */.intl;
  obj12[2] = intl15.string(require("intl/Feedback.messages.js").qdBn3L);
  obj12[3] = isStreamer;
  items[14] = obj12;
  const obj13 = { value: constants5.NO_AUDIO, variant: constants6.SOMEONE, label: null, disabled: null };
  const intl16 = require("../../intl/index.native.tsx") /* getSystemLocale */.intl;
  obj13[2] = intl16.string(require("intl/Feedback.messages.js").DOOlop);
  obj13[3] = isStreamer;
  items[15] = obj13;
  const obj14 = { value: constants5.BAD_AUDIO, variant: constants6.SOMEONE, label: null, disabled: null };
  const intl17 = require("../../intl/index.native.tsx") /* getSystemLocale */.intl;
  obj14[2] = intl17.string(require("intl/Feedback.messages.js").k7bdGE);
  obj14[3] = isStreamer;
  items[16] = obj14;
  const obj15 = { value: constants5.STOPPED_UNEXPECTEDLY, variant: constants6.SOMEONE, label: null, disabled: null };
  const intl18 = require("../../intl/index.native.tsx") /* getSystemLocale */.intl;
  obj15[2] = intl18.string(require("intl/Feedback.messages.js").jPD998);
  obj15[3] = isStreamer;
  items[17] = obj15;
  const obj16 = { value: constants5.DESYNC, variant: constants6.SOMEONE, label: null, disabled: null };
  const intl19 = require("../../intl/index.native.tsx") /* getSystemLocale */.intl;
  obj16[2] = intl19.string(require("intl/Feedback.messages.js").JfAvQp);
  obj16[3] = isStreamer;
  items[18] = obj16;
  const found = items.filter((disabled) => !disabled.disabled);
  return found.map((arg0) => Object.assign(arg0, Object.create(null)));
};
export const getPeopleFeedbackOptions = function getPeopleFeedbackOptions() {
  const obj = { value: constants7.TOXIC_OR_INAPPROPRIATE, variant: constants6.OTHERS, label: null };
  const intl = require("../../intl/index.native.tsx") /* getSystemLocale */.intl;
  obj[2] = intl.string(require("intl/Feedback.messages.js").PLBRzF);
  const items = [obj];
  const found = items.filter((disabled) => !disabled.disabled);
  return found.map((arg0) => Object.assign(arg0, Object.create(null)));
};