// discord_app/modules/feedback/FeedbackUtils.tsx
import _modDef12 from "../../../_runtime/metro/00012__.js";
import Constants2 from "../../Constants.tsx";
import util from "../../intl/index.native.tsx";
import AnalyticsUtilsDefault from "../../utils/AnalyticsUtils.tsx";
import _modDef2658 from "intl/Feedback.messages.js";
import Constants from "Constants.tsx";
import size from "../../../_runtime/metro/00002__.js";

({
  ConnectionFeedbackOption: c3,
  AudioFeedbackOption: closure_4,
  VideoFeedbackOption: hasOwnProperty,
  VideoBackgroundFeedbackOption: metroRequire,
  StreamFeedbackOption: closure_7,
  FeedbackOptionVariant: closure_8,
  FeedbackType: closure_9,
  MAX_REPRESENTABLE_DATE: c10,
  PeopleFeedbackOption: closure_11,
} = Constants);
const AnalyticEvents = Constants2.AnalyticEvents;
const result = size.fileFinishedImporting("modules/feedback/FeedbackUtils.tsx");

export const shuffleProblems = function shuffleProblems(reasons, otherKey) {
  closure_0 = otherKey;
  const shuffleResult = _modDef12.shuffle(reasons);
  const findIndexResult = shuffleResult.findIndex((value) => value.value === closure_0);
  if (findIndexResult > -1) {
    shuffleResult.splice(findIndexResult, 1);
    shuffleResult.push(shuffleResult[findIndexResult]);
  }
  return shuffleResult;
};
export const processOptOut = function processOptOut(feedbackType) {
  feedbackType = feedbackType.feedbackType;
  let obj = { feedback_type: closure_9[feedbackType], opted_out_until };
  obj.track(AnalyticEvents.USER_SETTINGS_IN_APP_FEEDBACK_OPTED_OUT, obj);
  const InAppFeedbackStates = feedbackType(1935).InAppFeedbackStates;
  InAppFeedbackStates.updateSetting((arg0) => {
    let obj = {};
    const merged = Object.assign(arg0);
    obj = {};
    const merged1 = Object.assign(arg0[feedbackType]);
    obj.optOutExpiryTime = optOutExpiryTime;
    obj[feedbackType] = obj;
    return obj;
  });
};
export const getConnectionFeedbackOptions = function getConnectionFeedbackOptions() {
  let obj = { variant: constants6.SELF, value: constants.COULD_NOT_CONNECT, label: null };
  const intl = util.intl;
  obj.label = intl.string(_modDef2658.gMHKDJ);
  const items = [obj, , , , ,];
  obj = { value: constants.HIGH_TTC, variant: constants6.SELF, label: null };
  const intl2 = util.intl;
  obj.label = intl2.string(_modDef2658.y06Ayn);
  items[1] = obj;
  obj = { value: constants.HIGH_LATENCY, variant: constants6.SELF, label: null };
  const intl3 = util.intl;
  obj.label = intl3.string(_modDef2658.y5k8Jq);
  items[2] = obj;
  const obj1 = { value: constants.ROBOT_VOICE, variant: constants6.SOMEONE, label: null };
  const intl4 = util.intl;
  obj1.label = intl4.string(_modDef2658.f2914v);
  items[3] = obj1;
  const obj2 = { value: constants.DESYNC, variant: constants6.UNSPECIFIED, label: null };
  const intl5 = util.intl;
  obj2.label = intl5.string(_modDef2658["zk+QL1"]);
  items[4] = obj2;
  const obj3 = { value: constants.CUTTING, variant: constants6.SOMEONE, label: null };
  const intl6 = util.intl;
  obj3.label = intl6.string(_modDef2658.K5vYQA);
  items[5] = obj3;
  const found = items.filter((disabled) => !disabled.disabled);
  return found.map((item) => Object.assign(item, Object.assign({ disabled: 0 })));
};
export const getAudioFeedbackOptions = function getAudioFeedbackOptions(isMobile) {
  let obj = { value: constants2.NO_AUDIO, variant: constants6.SELF, label: null };
  const intl = util.intl;
  obj.label = intl.string(_modDef2658["GWypH+"]);
  const items = [obj, , , , , , , , , , , ,];
  obj = { value: constants2.NO_AUDIO, variant: constants6.OTHERS, label: null };
  const intl2 = util.intl;
  obj.label = intl2.string(_modDef2658.ftSvQ0);
  items[1] = obj;
  obj = { value: constants2.LOW_QUALITY_AUDIO, variant: constants6.OTHERS, label: null };
  const intl3 = util.intl;
  obj.label = intl3.string(_modDef2658["1DnNRO"]);
  items[2] = obj;
  const obj1 = { value: constants2.ROBOT_VOICE, variant: constants6.SOMEONE, label: null };
  const intl4 = util.intl;
  obj1.label = intl4.string(_modDef2658.yGe0BL);
  items[3] = obj1;
  const obj2 = { value: constants2.ECHO, variant: constants6.OTHERS, label: null };
  const intl5 = util.intl;
  obj2.label = intl5.string(_modDef2658.Q5Dsaz);
  items[4] = obj2;
  const obj3 = { value: constants2.TOO_QUIET_OR_LOUD, variant: constants6.SOMEONE, label: null };
  const intl6 = util.intl;
  obj3.label = intl6.string(_modDef2658["1o77I3"]);
  items[5] = obj3;
  const obj4 = { value: constants2.CUTTING, variant: constants6.SOMEONE, label: null };
  const intl7 = util.intl;
  obj4.label = intl7.string(_modDef2658.RK9DUi);
  items[6] = obj4;
  const obj5 = { value: constants2.DELAYED, variant: constants6.UNSPECIFIED, label: null };
  const intl8 = util.intl;
  obj5.label = intl8.string(_modDef2658.RGRgmM);
  items[7] = obj5;
  const obj6 = { value: constants2.BACKGROUND_NOISE, variant: constants6.SOMEONE, label: null };
  const intl9 = util.intl;
  obj6.label = intl9.string(_modDef2658["anHk1/"]);
  items[8] = obj6;
  const obj7 = { value: constants2.UNABLE_TO_FIND_DEVICE, variant: constants6.SELF, label: null };
  const intl10 = util.intl;
  obj7.label = intl10.string(_modDef2658["05VSjm"]);
  items[9] = obj7;
  const obj8 = { value: constants2.COMPLAINTS, variant: constants6.OTHERS, label: null };
  const intl11 = util.intl;
  obj8.label = intl11.string(_modDef2658.kbbtwi);
  items[10] = obj8;
  const obj9 = { value: constants2.TROUBLE_WITH_SPEAKERPHONE, variant: constants6.SELF, label: null, disabled: null };
  const intl12 = util.intl;
  obj9.label = intl12.string(_modDef2658["4qlGrO"]);
  obj9.disabled = !isMobile.isMobile;
  items[11] = obj9;
  const obj10 = { value: constants2.NO_GAME_AUDIO, variant: constants6.SELF, label: null };
  const intl13 = util.intl;
  obj10.label = intl13.string(_modDef2658["2IG95D"]);
  items[12] = obj10;
  const found = items.filter((disabled) => !disabled.disabled);
  return found.map((item) => Object.assign(item, Object.assign({ disabled: 0 })));
};
export const getVideoFeedbackOptions = function getVideoFeedbackOptions() {
  let obj = { value: constants3.NO_VIDEO, variant: constants6.SELF, label: null };
  const intl = util.intl;
  obj.label = intl.string(_modDef2658["Bh+02d"]);
  const items = [obj, , , , ,];
  obj = { value: constants3.NO_VIDEO, variant: constants6.SOMEONE, label: null };
  const intl2 = util.intl;
  obj.label = intl2.string(_modDef2658["R+wqwU"]);
  items[1] = obj;
  obj = { value: constants3.FREEZING_OR_HITCHING, variant: constants6.SOMEONE, label: null };
  const intl3 = util.intl;
  obj.label = intl3.string(_modDef2658["8I/GUL"]);
  items[2] = obj;
  const obj1 = { value: constants3.BLURRY_OR_PIXELATED, variant: constants6.SOMEONE, label: null };
  const intl4 = util.intl;
  obj1.label = intl4.string(_modDef2658.k7Idoz);
  items[3] = obj1;
  const obj2 = { value: constants3.UNABLE_TO_ENABLE_DEVICE, variant: constants6.SELF, label: null };
  const intl5 = util.intl;
  obj2.label = intl5.string(_modDef2658.QbC6La);
  items[4] = obj2;
  const obj3 = { value: constants3.DESYNC, variant: constants6.UNSPECIFIED, label: null };
  const intl6 = util.intl;
  obj3.label = intl6.string(_modDef2658.vRDE5O);
  items[5] = obj3;
  const found = items.filter((disabled) => !disabled.disabled);
  return found.map((item) => Object.assign(item, Object.assign({ disabled: 0 })));
};
export const getVideoBackgroundFeedbackOptions = function getVideoBackgroundFeedbackOptions() {
  let obj = { value: constants4.OUTLINE_FUZZY_OR_HALO, variant: constants6.SELF, label: null };
  const intl = util.intl;
  obj.label = intl.string(_modDef2658.calUNv);
  const items = [obj, , ,];
  obj = { value: constants4.INACCURATE_BACKGROUND_DETECTION, variant: constants6.SELF, label: null };
  const intl2 = util.intl;
  obj.label = intl2.string(_modDef2658.zYumoj);
  items[1] = obj;
  obj = { value: constants4.FLICKERING_ARTIFACTS, variant: constants6.SELF, label: null };
  const intl3 = util.intl;
  obj.label = intl3.string(_modDef2658.ie5nCG);
  items[2] = obj;
  const obj1 = { value: constants4.LAG_ON_MOVEMENT, variant: constants6.SELF, label: null };
  const intl4 = util.intl;
  obj1.label = intl4.string(_modDef2658["Gg/Y1X"]);
  items[3] = obj1;
  const found = items.filter((disabled) => !disabled.disabled);
  return found.map((item) => Object.assign(item, Object.assign({ disabled: 0 })));
};
export const getStreamFeedbackOptions = function getStreamFeedbackOptions(isStreamer) {
  isStreamer = isStreamer.isStreamer;
  let obj = { value: constants5.COULD_NOT_LOAD, variant: constants6.SELF, label: null, disabled: null };
  const intl = util.intl;
  obj.label = intl.string(_modDef2658["w+kiDF"]);
  obj.disabled = !isStreamer;
  const items = [obj, , , , , , , , , , , , , , , , , ,];
  obj = { value: constants5.BLACK_SCREEN, variant: constants6.SELF, label: null, disabled: null };
  const intl2 = util.intl;
  obj.label = intl2.string(_modDef2658.RRZZZb);
  obj.disabled = !isStreamer;
  items[1] = obj;
  obj = { value: constants5.FREEZING_OR_HITCHING, variant: constants6.SELF, label: null, disabled: null };
  const intl3 = util.intl;
  obj.label = intl3.string(_modDef2658["3PKSkd"]);
  obj.disabled = !isStreamer;
  items[2] = obj;
  const obj1 = { value: constants5.LAG, variant: constants6.SELF, label: null, disabled: null };
  const intl4 = util.intl;
  obj1.label = intl4.string(_modDef2658.iMxexK);
  obj1.disabled = !isStreamer;
  items[3] = obj1;
  const obj2 = { value: constants5.BLURRY_OR_PIXELATED, variant: constants6.SELF, label: null, disabled: null };
  const intl5 = util.intl;
  obj2.label = intl5.string(_modDef2658["8ceyQy"]);
  obj2.disabled = !isStreamer;
  items[4] = obj2;
  const obj3 = { value: constants5.NO_AUDIO, variant: constants6.SELF, label: null, disabled: null };
  const intl6 = util.intl;
  obj3.label = intl6.string(_modDef2658.HaZSC3);
  obj3.disabled = !isStreamer;
  items[5] = obj3;
  const obj4 = { value: constants5.BAD_AUDIO, variant: constants6.SELF, label: null, disabled: null };
  const intl7 = util.intl;
  obj4.label = intl7.string(_modDef2658["zIC+8Y"]);
  obj4.disabled = !isStreamer;
  items[6] = obj4;
  const obj5 = { value: constants5.STOPPED_UNEXPECTEDLY, variant: constants6.SELF, label: null, disabled: null };
  const intl8 = util.intl;
  obj5.label = intl8.string(_modDef2658["/nlKuG"]);
  obj5.disabled = !isStreamer;
  items[7] = obj5;
  const obj6 = { value: constants5.DESYNC, variant: constants6.SELF, label: null, disabled: null };
  const intl9 = util.intl;
  obj6.label = intl9.string(_modDef2658.JS6akP);
  obj6.disabled = !isStreamer;
  items[8] = obj6;
  const obj7 = { value: constants5.NO_GAME_AUDIO, variant: constants6.SELF, label: null, disabled: null };
  const intl10 = util.intl;
  obj7.label = intl10.string(_modDef2658.TaIrh5);
  obj7.disabled = !isStreamer;
  items[9] = obj7;
  const obj8 = { value: constants5.COULD_NOT_LOAD, variant: constants6.SOMEONE, label: null, disabled: null };
  const intl11 = util.intl;
  obj8.label = intl11.string(_modDef2658.jU9Zs8);
  obj8.disabled = isStreamer;
  items[10] = obj8;
  const obj9 = { value: constants5.BLACK_SCREEN, variant: constants6.SOMEONE, label: null, disabled: null };
  const intl12 = util.intl;
  obj9.label = intl12.string(_modDef2658.aml28x);
  obj9.disabled = isStreamer;
  items[11] = obj9;
  const obj10 = { value: constants5.FREEZING_OR_HITCHING, variant: constants6.SOMEONE, label: null, disabled: null };
  const intl13 = util.intl;
  obj10.label = intl13.string(_modDef2658.V3EeCH);
  obj10.disabled = isStreamer;
  items[12] = obj10;
  const obj11 = { value: constants5.LAG, variant: constants6.SOMEONE, label: null, disabled: null };
  const intl14 = util.intl;
  obj11.label = intl14.string(_modDef2658.hi1Y39);
  obj11.disabled = isStreamer;
  items[13] = obj11;
  const obj12 = { value: constants5.BLURRY_OR_PIXELATED, variant: constants6.SOMEONE, label: null, disabled: null };
  const intl15 = util.intl;
  obj12.label = intl15.string(_modDef2658.qdBn3L);
  obj12.disabled = isStreamer;
  items[14] = obj12;
  const obj13 = { value: constants5.NO_AUDIO, variant: constants6.SOMEONE, label: null, disabled: null };
  const intl16 = util.intl;
  obj13.label = intl16.string(_modDef2658.DOOlop);
  obj13.disabled = isStreamer;
  items[15] = obj13;
  const obj14 = { value: constants5.BAD_AUDIO, variant: constants6.SOMEONE, label: null, disabled: null };
  const intl17 = util.intl;
  obj14.label = intl17.string(_modDef2658.k7bdGE);
  obj14.disabled = isStreamer;
  items[16] = obj14;
  const obj15 = { value: constants5.STOPPED_UNEXPECTEDLY, variant: constants6.SOMEONE, label: null, disabled: null };
  const intl18 = util.intl;
  obj15.label = intl18.string(_modDef2658.jPD998);
  obj15.disabled = isStreamer;
  items[17] = obj15;
  const obj16 = { value: constants5.DESYNC, variant: constants6.SOMEONE, label: null, disabled: null };
  const intl19 = util.intl;
  obj16.label = intl19.string(_modDef2658.JfAvQp);
  obj16.disabled = isStreamer;
  items[18] = obj16;
  const found = items.filter((disabled) => !disabled.disabled);
  return found.map((item) => Object.assign(item, Object.assign({ disabled: 0 })));
};
export const getPeopleFeedbackOptions = function getPeopleFeedbackOptions() {
  const obj = { value: constants7.TOXIC_OR_INAPPROPRIATE, variant: constants6.OTHERS, label: null };
  const intl = util.intl;
  obj.label = intl.string(_modDef2658.PLBRzF);
  const items = [obj];
  const found = items.filter((disabled) => !disabled.disabled);
  return found.map((item) => Object.assign(item, Object.assign({ disabled: 0 })));
};
