// discord_app/modules/collectibles/native/ProductDetailsActionSheetSkeleton.tsx
import ThemesDefault from "../../../../discord_common/js/packages/tokens/native.tsx";
import _modDef4115 from "../../reanimated/ReanimatedRexport.tsx";
import noop from "../../../../_runtime/00019_noop.js";
import { View } from "../../../../_runtime/00017_get_ActivityIndicator.js";
import jsxProd from "../../../../_runtime/react/00021_jsxProd.js";
import "createCacheKey";

const require = fn;
({ jsx: c5, jsxs: closure_6 } = jsxProd);
const createCacheKey = { backgroundColor: ThemesDefault.colors.BORDER_SUBTLE };
createCacheKey[2] = createCacheKey;
createCacheKey[3] = { marginTop: ThemesDefault.space.PX_12, marginHorizontal: ThemesDefault.space.PX_16, height: 280, borderRadius: ThemesDefault.radii.md };
createCacheKey[4] = { marginTop: ThemesDefault.space.PX_24, marginHorizontal: ThemesDefault.space.PX_16, gap: ThemesDefault.space.PX_8 };
createCacheKey[5] = { height: 24, width: "60%", borderRadius: ThemesDefault.radii.xs };
createCacheKey[6] = { height: 16, width: "90%", borderRadius: ThemesDefault.radii.xs };
createCacheKey[7] = { marginTop: ThemesDefault.space.PX_12, height: 20, width: "30%", borderRadius: ThemesDefault.radii.xs };
createCacheKey[8] = { paddingHorizontal: ThemesDefault.space.PX_16, paddingTop: ThemesDefault.space.PX_8, paddingBottom: ThemesDefault.space.PX_16 };
createCacheKey[9] = { height: require("MINIMUM_HIT_AREA").LARGE_BUTTON_HEIGHT, borderRadius: ThemesDefault.radii.round };
let closure_7 = createCacheKey.createStyles(createCacheKey);
let closure_8 = { code: "function ProductDetailsActionSheetSkeletonTsx1(){const{opacity}=this.__closure;return{opacity:opacity.get()};}" };
const obj7 = { height: require("MINIMUM_HIT_AREA").LARGE_BUTTON_HEIGHT, borderRadius: ThemesDefault.radii.round };
let result = require("obj132").fileFinishedImporting("modules/collectibles/native/ProductDetailsActionSheetSkeleton.tsx");

export default function ProductDetailsActionSheetSkeleton() {
  const tmp = callback3();
  let sharedValue;
  let obj = sharedValue(4115);
  sharedValue = obj.useSharedValue(0.3);
  const items = [sharedValue];
  const effect = React.useEffect(() => {
    const obj = sharedValue(dependencyMap[6]);
    const result = sharedValue.set(obj.withRepeat(sharedValue(dependencyMap[7]).withTiming(1, { duration: 650 }), -1, true));
  }, items);
  obj1 = sharedValue(4115);
  const fn = function o() {
    return { opacity: sharedValue.get() };
  };
  fn.__closure = { opacity: sharedValue };
  fn.__workletHash = 4141895524740;
  fn.__initData = closure_8;
  const animatedStyle = obj1.useAnimatedStyle(fn);
  obj = { style: tmp.scrollArea, children: null };
  const items1 = [, , ];
  ({ block: arr2[0], preview: arr2[1] } = tmp);
  items1[2] = animatedStyle;
  const items2 = [callback(_modDef4115.View, { style: items1 }), ];
  obj1 = { style: tmp.info, children: null };
  const items3 = [, , ];
  ({ block: arr4[0], title: arr4[1] } = tmp);
  items3[2] = animatedStyle;
  const items4 = [callback(_modDef4115.View, { style: items3 }), , ];
  const items5 = [, , ];
  ({ block: arr6[0], description: arr6[1] } = tmp);
  items5[2] = animatedStyle;
  items4[1] = callback(_modDef4115.View, { style: items5 });
  const items6 = [, , ];
  ({ block: arr7[0], price: arr7[1] } = tmp);
  items6[2] = animatedStyle;
  items4[2] = callback(_modDef4115.View, { style: items6 });
  obj1[1] = items4;
  items2[1] = callback2(View, obj1);
  obj[1] = items2;
  const items7 = [callback2(View, obj), ];
  const items8 = [, , ];
  ({ block: arr9[0], purchaseButton: arr9[1] } = tmp);
  items8[2] = animatedStyle;
  items7[1] = callback(View, { style: tmp.purchaseSection, children: callback(_modDef4115.View, { style: items8 }) });
  obj[1] = items7;
  return callback2(View, obj);
};