// discord_app/design/void/native.tsx
import set from "../../../_runtime/00002_set.js";
import STATUS_PADDING from "Status/native/StatusConstants.tsx";
import PX_16 from "BadgeConstants/native/BadgeConstants.tsx";
import getTextStyles from "Button/native/Button.tsx";
import getTextStylesDefault from "Button/native/Button.tsx";
import View from "OverlayView/native/OverlayView.tsx";
import ViewDefault from "OverlayView/native/OverlayView.tsx";
import IconSizes from "Icon/native/Icon.tsx";
import IconSizesDefault from "Icon/native/Icon.tsx";
import PressableBase from "Pressables/native/Pressables.tsx";
import Form from "Form/native/index.tsx";
import CardSectionDefault from "CardSection/native/CardSection.tsx";
import _modDef8323 from "LegacyText/native/LegacyText.tsx";
import renderDefault from "TouchableHitBox/native/TouchableHitBox.tsx";
import StaticNativeCutoutAvatarImage from "CutoutableAvatarImage/native/CutoutableAvatarImage.tsx";
import StaticNativeCutoutAvatarImageDefault from "CutoutableAvatarImage/native/CutoutableAvatarImage.tsx";
import VoidTextInputDefault from "TextInput/native/TextInput.tsx";
import RoleLabel from "RoleLabel/native/RoleLabel.tsx";
import BetaTag from "BetaTag/native/BetaTag.tsx";
import BetaTagDefault from "BetaTag/native/BetaTag.tsx";
import SquareIconButton from "IconButton/native/IconButton.tsx";
import ShinyButtonDefault from "ShinyButton/native/ShinyButton.tsx";
import CheckboxDefault from "Checkbox/native/Checkbox.tsx";
import CloseDefault from "CloseIcon/native/CloseIcon.tsx";
import AnimatedEllipsisDotDefault from "Ellipsis/native/Ellipsis.tsx";
import GradientBorderDefault from "GradientBorder/native/GradientBorder.tsx";
import HelpMessage from "HelpMessage/native/HelpMessage.tsx";
import HelpMessageDefault from "HelpMessage/native/HelpMessage.tsx";
import IconPillDefault from "IconPill/native/IconPill.tsx";
import NewTagDefault from "NewTag/native/NewTag.tsx";
import RadioEmpty from "RadioGroup/native/RadioGroup.tsx";
import RadioEmptyDefault from "RadioGroup/native/RadioGroup.tsx";
import CollapsibleDefault from "Collapsible/native/Collapsible.tsx";
import OverflowSquircle from "SummarizedIconRow/native/SummarizedIconRow.tsx";
import OverflowSquircleDefault from "SummarizedIconRow/native/SummarizedIconRow.tsx";
import ThemedIconDefault from "ThemedIcon/native/ThemedIcon.tsx";
import LocalImageThumbnailDefault from "ThumbnailImage/native/ThumbnailImage.tsx";
import Tooltip from "Tooltip/native/Tooltip.tsx";
import TooltipDefault from "Tooltip/native/Tooltip.tsx";
import WarningCircleDefault from "WarningCircle/native/WarningCircle.tsx";
import getAnimatedTypingTranslateX from "Status/native/StatusUtils.tsx";
import STATUS_PADDINGDefault from "Status/native/getStatusContainerStyle.tsx";
import Status from "Status/native/Status.tsx";
import StatusDefault from "Status/native/Status.tsx";
import getStatusSize from "Avatar/native/Avatar.tsx";
import getStatusSizeDefault from "Avatar/native/Avatar.tsx";
import AccessibilityFocusViewDefault from "AccessibilityFocusView/native/AccessibilityFocusView.tsx";
import PassthroughTouchViewDefault from "PassthroughTouchView/native/PassthroughTouchView.tsx";
import STANDARD_EASING from "Easing/native/Easing.tsx";
import SpacerDefault from "Spacer/native/Spacer.tsx";
import LiveTagDefault from "LiveTag/native/LiveTag.tsx";
import RoleDot from "RoleDot/native/RoleDot.tsx";
import generateBoxShadowStyle from "Shadows/native/Shadows.tsx";
import NitroWheelDefault from "NitroWheel/native/NitroWheel.tsx";
import EmptyStateDefault from "EmptyState/native/EmptyState.tsx";
import RNTextInput from "Atoms/native/Atoms.tsx";
import Badge from "Badge/native/Badge.tsx";
import BadgeDefault from "Badge/native/Badge.tsx";
import CarouselPaginationDefault from "CarouselPagination/native/CarouselPagination.tsx";
import Fonts from "InputView/native/InputView.tsx";
import FontsDefault from "InputView/native/InputView.tsx";
import BadgeColors from "Badges/native/Badges.tsx";
import EmptyState from "RefreshEmptyState/native/RefreshEmptyState.tsx";
import EmptyStateDefault2 from "RefreshEmptyState/native/RefreshEmptyState.tsx";

const result = set.fileFinishedImporting("design/void/native.tsx");

export const Button = getTextStylesDefault;
export const BUTTON_CORNER_RADIUS = getTextStyles.BUTTON_CORNER_RADIUS;
export const useButtonStyles = getTextStyles.useButtonStyles;
export const ButtonLooks = getTextStyles.ButtonLooks;
export const ButtonColors = getTextStyles.ButtonColors;
export const ButtonSizes = getTextStyles.ButtonSizes;
export const getButtonStyles = getTextStyles.getButtonStyles;
export const ButtonText = getTextStyles.ButtonText;
export const getRedesignVariant = getTextStyles.getRedesignVariant;
export const getRedesignSize = getTextStyles.getRedesignSize;
export const ShinyButton = ShinyButtonDefault;
export const BetaTag = BetaTagDefault;
export const BetaSizes = BetaTag.BetaSizes;
export const Checkbox = CheckboxDefault;
export const CloseIcon = CloseDefault;
export const Ellipsis = AnimatedEllipsisDotDefault;
export const GradientBorder = GradientBorderDefault;
export const HelpMessage = HelpMessageDefault;
export const HelpMessageTypes = HelpMessage.HelpMessageTypes;
export const IconPill = IconPillDefault;
export const NewTag = NewTagDefault;
export const OverlayView = ViewDefault;
export const TransitionGroupOverlayView = View.TransitionGroupOverlayView;
export const NonExpandingOverlayView = View.NonExpandingOverlayView;
export const RadioGroup = RadioEmptyDefault;
export const RadioIndicator = RadioEmpty.RadioIndicator;
export const RadioItem = RadioEmpty.RadioItem;
export const SummarizedIconRow = OverflowSquircleDefault;
export const OverflowText = OverflowSquircle.OverflowText;
export const OverflowTextSmall = OverflowSquircle.OverflowTextSmall;
export const OverflowCircle = OverflowSquircle.OverflowCircle;
export const TextInput = VoidTextInputDefault;
export const ThemedIcon = ThemedIconDefault;
export const ThumbnailImage = LocalImageThumbnailDefault;
export const Tooltip = TooltipDefault;
export const TooltipArrowDirections = Tooltip.TooltipArrowDirections;
export const TooltipArrowPositions = Tooltip.TooltipArrowPositions;
export const WarningCircle = WarningCircleDefault;
export const STATUS_PADDING = STATUS_PADDING.STATUS_PADDING;
export const StatusSizes = STATUS_PADDING.StatusSizes;
export const getAnimatedTypingTranslateX = getAnimatedTypingTranslateX.getAnimatedTypingTranslateX;
export const getMobileStatusContainerRect = getAnimatedTypingTranslateX.getMobileStatusContainerRect;
export const getStatusTypingDimensions = getAnimatedTypingTranslateX.getStatusTypingDimensions;
export const getStatusContainerStyle = STATUS_PADDINGDefault;
export const Status = StatusDefault;
export const StatusWithTyping = Status.StatusWithTyping;
export const Icon = IconSizesDefault;
export const IconSizes = IconSizes.IconSizes;
export const getIconSize = IconSizes.getIconSize;
export const getIconStyle = IconSizes.getIconStyle;
export const CutoutableAvatarImage = StaticNativeCutoutAvatarImageDefault;
export const AvatarSizes = StaticNativeCutoutAvatarImage.AvatarSizes;
export const AVATAR_SIZE_MAP = StaticNativeCutoutAvatarImage.AVATAR_SIZE_MAP;
export const avatarStyles = StaticNativeCutoutAvatarImage.styles;
export const CutoutDirection = StaticNativeCutoutAvatarImage.CutoutDirection;
export const CutoutType = StaticNativeCutoutAvatarImage.CutoutType;
export const Avatar = getStatusSizeDefault;
export const getStatusSize = getStatusSize.getStatusSize;
export const AccessibilityFocusView = AccessibilityFocusViewDefault;
export const Collapsible = CollapsibleDefault;
export const PassthroughTouchView = PassthroughTouchViewDefault;
export const BADGE_SIZE = PX_16.BADGE_SIZE;
export const BADGE_SIZE_UNREAD = PX_16.BADGE_SIZE_UNREAD;
export const BADGE_PADDING = PX_16.BADGE_PADDING;
export const BADGE_MASK_SIZE = PX_16.BADGE_MASK_SIZE;
export const BADGE_MASK_UNREAD_SIZE = PX_16.BADGE_MASK_UNREAD_SIZE;
export const STANDARD_EASING = STANDARD_EASING.STANDARD_EASING;
export const DECELERATED_EASING = STANDARD_EASING.DECELERATED_EASING;
export const Spacer = SpacerDefault;
export const LiveTag = LiveTagDefault;
export const RoleDot = RoleDot.RoleDot;
export const generateBoxShadowStyle = generateBoxShadowStyle.generateBoxShadowStyle;
export const EIGHT_DP_ELEVATION_SHADOW_PARAMS = generateBoxShadowStyle.EIGHT_DP_ELEVATION_SHADOW_PARAMS;
export const FOUR_DP_ELEVATION_SHADOW_PARAMS = generateBoxShadowStyle.FOUR_DP_ELEVATION_SHADOW_PARAMS;
export const EXPERIMENTAL_HIGH_ELEVATION_SHADOW_PARAMS = generateBoxShadowStyle.EXPERIMENTAL_HIGH_ELEVATION_SHADOW_PARAMS;
export const NO_ELEVATION_SHADOW_PARAMS = generateBoxShadowStyle.NO_ELEVATION_SHADOW_PARAMS;
export const NitroWheel = NitroWheelDefault;
export const EmptyState = EmptyStateDefault;
export const LegacyText = _modDef8323;
export const RNTextInput = RNTextInput.RNTextInput;
export const Badge = BadgeDefault;
export const MaskedBadge = Badge.MaskedBadge;
export const CarouselPagination = CarouselPaginationDefault;
export const InputView = FontsDefault;
export const ClearButtonVisibility = Fonts.ClearButtonVisibility;
export const BadgeColors = BadgeColors.BadgeColors;
export const TextBadge = BadgeColors.TextBadge;
export const RefreshEmptyState = EmptyStateDefault2;
export const ThemedEmptyState = EmptyState.ThemedEmptyState;
export const CardSection = CardSectionDefault;
export const Form = Form.Form;
export const FormArrow = Form.FormArrow;
export const FormCheckbox = Form.FormCheckbox;
export const FormCheckmark = Form.FormCheckmark;
export const FormCTA = Form.FormCTA;
export const FormCTAButton = Form.FormCTAButton;
export const FormDivider = Form.FormDivider;
export const FormHint = Form.FormHint;
export const FormIcon = Form.FormIcon;
export const FormInput = Form.FormInput;
export const FormLabel = Form.FormLabel;
export const FormRadio = Form.FormRadio;
export const FormRow = Form.FormRow;
export const FormSection = Form.FormSection;
export const FormSelect = Form.FormSelect;
export const FormSubLabel = Form.FormSubLabel;
export const FormSwitch = Form.FormSwitch;
export const FormText = Form.FormText;
export const FormTextColors = Form.FormTextColors;
export const FormTitle = Form.FormTitle;
export const FormSwitchRow = Form.FormSwitchRow;
export const FormRadioRow = Form.FormRadioRow;
export const FormCheckboxRow = Form.FormCheckboxRow;
export const FormRadioGroup = Form.FormRadioGroup;
export const FormSliderRow = Form.FormSliderRow;
export const FormCardSection = Form.FormCardSection;
export const PressableOpacity = PressableBase.PressableOpacity;
export const PressableHighlight = PressableBase.PressableHighlight;
export const SquareIconButton = SquareIconButton.SquareIconButton;
export const CircularIconButton = SquareIconButton.CircularIconButton;
export const TouchableHitBox = renderDefault;
export const RoleLabel = RoleLabel.RoleLabel;