// discord_app/design/void/native.tsx
import StatusConstants from "Status/native/StatusConstants.tsx";
import BadgeConstants from "BadgeConstants/native/BadgeConstants.tsx";
import Button_Button from "Button/native/Button.tsx";
import OverlayView from "OverlayView/native/OverlayView.tsx";
import Icon from "Icon/native/Icon.tsx";
import Pressables from "Pressables/native/Pressables.tsx";
import Form from "Form/native/index.tsx";
import CardSectionDefault from "CardSection/native/CardSection.tsx";
import LegacyText_LegacyTextDefault from "LegacyText/native/LegacyText.tsx";
import TouchableHitBoxDefault from "TouchableHitBox/native/TouchableHitBox.tsx";
import TextInput_TextInputDefault from "TextInput/native/TextInput.tsx";
import RoleLabel from "RoleLabel/native/RoleLabel.tsx";
import CutoutableAvatarImage from "CutoutableAvatarImage/native/CutoutableAvatarImage.tsx";
import BetaTag from "BetaTag/native/BetaTag.tsx";
import IconButton_IconButton from "IconButton/native/IconButton.tsx";
import ShinyButton_ShinyButtonDefault from "ShinyButton/native/ShinyButton.tsx";
import Checkbox_CheckboxDefault from "Checkbox/native/Checkbox.tsx";
import CloseIconDefault from "CloseIcon/native/CloseIcon.tsx";
import EllipsisDefault from "Ellipsis/native/Ellipsis.tsx";
import GradientBorderDefault from "GradientBorder/native/GradientBorder.tsx";
import HelpMessage from "HelpMessage/native/HelpMessage.tsx";
import IconPillDefault from "IconPill/native/IconPill.tsx";
import NewTagDefault from "NewTag/native/NewTag.tsx";
import RadioGroup from "RadioGroup/native/RadioGroup.tsx";
import CollapsibleDefault from "Collapsible/native/Collapsible.tsx";
import SummarizedIconRow from "SummarizedIconRow/native/SummarizedIconRow.tsx";
import ThemedIconDefault from "ThemedIcon/native/ThemedIcon.tsx";
import ThumbnailImageDefault from "ThumbnailImage/native/ThumbnailImage.tsx";
import Tooltip_Tooltip from "Tooltip/native/Tooltip.tsx";
import WarningCircleDefault from "WarningCircle/native/WarningCircle.tsx";
import Status_StatusUtils from "Status/native/StatusUtils.tsx";
import getStatusContainerStyleDefault from "Status/native/getStatusContainerStyle.tsx";
import Status from "Status/native/Status.tsx";
import Avatar from "Avatar/native/Avatar.tsx";
import AccessibilityFocusViewDefault from "AccessibilityFocusView/native/AccessibilityFocusView.tsx";
import PassthroughTouchViewDefault from "PassthroughTouchView/native/PassthroughTouchView.tsx";
import Easing from "Easing/native/Easing.tsx";
import SpacerDefault from "Spacer/native/Spacer.tsx";
import LiveTagDefault from "LiveTag/native/LiveTag.tsx";
import RoleDot from "RoleDot/native/RoleDot.tsx";
import Shadows from "Shadows/native/Shadows.tsx";
import NitroWheelDefault from "NitroWheel/native/NitroWheel.tsx";
import EmptyStateDefault from "EmptyState/native/EmptyState.tsx";
import Atoms from "Atoms/native/Atoms.tsx";
import Badge_Badge from "Badge/native/Badge.tsx";
import CarouselPaginationDefault from "CarouselPagination/native/CarouselPagination.tsx";
import InputView from "InputView/native/InputView.tsx";
import Badges_Badges from "Badges/native/Badges.tsx";
import RefreshEmptyState from "RefreshEmptyState/native/RefreshEmptyState.tsx";
import size from "../../../_runtime/metro/00002__.js";

const Button_ButtonDefault = Button_Button;
const OverlayViewDefault = OverlayView;
const IconDefault = Icon;
const CutoutableAvatarImageDefault = CutoutableAvatarImage;
const BetaTagDefault = BetaTag;
const HelpMessageDefault = HelpMessage;
const RadioGroupDefault = RadioGroup;
const SummarizedIconRowDefault = SummarizedIconRow;
const Tooltip_TooltipDefault = Tooltip_Tooltip;
const StatusDefault = Status;
const AvatarDefault = Avatar;
const Badge_BadgeDefault = Badge_Badge;
const InputViewDefault = InputView;
const RefreshEmptyStateDefault = RefreshEmptyState;

const result = size.fileFinishedImporting("design/void/native.tsx");

export const Button = Button_ButtonDefault;
export const BUTTON_CORNER_RADIUS = Button_Button.BUTTON_CORNER_RADIUS;
export const useButtonStyles = Button_Button.useButtonStyles;
export const ButtonLooks = Button_Button.ButtonLooks;
export const ButtonColors = Button_Button.ButtonColors;
export const ButtonSizes = Button_Button.ButtonSizes;
export const getButtonStyles = Button_Button.getButtonStyles;
export const ButtonText = Button_Button.ButtonText;
export const getRedesignVariant = Button_Button.getRedesignVariant;
export const getRedesignSize = Button_Button.getRedesignSize;
export const ShinyButton = ShinyButton_ShinyButtonDefault;
export const BetaTag = BetaTagDefault;
export const BetaSizes = BetaTag.BetaSizes;
export const Checkbox = Checkbox_CheckboxDefault;
export const CloseIcon = CloseIconDefault;
export const Ellipsis = EllipsisDefault;
export const GradientBorder = GradientBorderDefault;
export const HelpMessage = HelpMessageDefault;
export const HelpMessageTypes = HelpMessage.HelpMessageTypes;
export const IconPill = IconPillDefault;
export const NewTag = NewTagDefault;
export const OverlayView = OverlayViewDefault;
export const TransitionGroupOverlayView = OverlayView.TransitionGroupOverlayView;
export const NonExpandingOverlayView = OverlayView.NonExpandingOverlayView;
export const RadioGroup = RadioGroupDefault;
export const RadioIndicator = RadioGroup.RadioIndicator;
export const RadioItem = RadioGroup.RadioItem;
export const SummarizedIconRow = SummarizedIconRowDefault;
export const OverflowText = SummarizedIconRow.OverflowText;
export const OverflowTextSmall = SummarizedIconRow.OverflowTextSmall;
export const OverflowCircle = SummarizedIconRow.OverflowCircle;
export const TextInput = TextInput_TextInputDefault;
export const ThemedIcon = ThemedIconDefault;
export const ThumbnailImage = ThumbnailImageDefault;
export const Tooltip = Tooltip_TooltipDefault;
export const TooltipArrowDirections = Tooltip_Tooltip.TooltipArrowDirections;
export const TooltipArrowPositions = Tooltip_Tooltip.TooltipArrowPositions;
export const WarningCircle = WarningCircleDefault;
export const STATUS_PADDING = StatusConstants.STATUS_PADDING;
export const StatusSizes = StatusConstants.StatusSizes;
export const getAnimatedTypingTranslateX = Status_StatusUtils.getAnimatedTypingTranslateX;
export const getMobileStatusContainerRect = Status_StatusUtils.getMobileStatusContainerRect;
export const getStatusTypingDimensions = Status_StatusUtils.getStatusTypingDimensions;
export const getStatusContainerStyle = getStatusContainerStyleDefault;
export const Status = StatusDefault;
export const StatusWithTyping = Status.StatusWithTyping;
export const Icon = IconDefault;
export const IconSizes = Icon.IconSizes;
export const getIconSize = Icon.getIconSize;
export const getIconStyle = Icon.getIconStyle;
export const CutoutableAvatarImage = CutoutableAvatarImageDefault;
export const AvatarSizes = CutoutableAvatarImage.AvatarSizes;
export const AVATAR_SIZE_MAP = CutoutableAvatarImage.AVATAR_SIZE_MAP;
export const avatarStyles = CutoutableAvatarImage.styles;
export const CutoutDirection = CutoutableAvatarImage.CutoutDirection;
export const CutoutType = CutoutableAvatarImage.CutoutType;
export const Avatar = AvatarDefault;
export const getStatusSize = Avatar.getStatusSize;
export const AccessibilityFocusView = AccessibilityFocusViewDefault;
export const Collapsible = CollapsibleDefault;
export const PassthroughTouchView = PassthroughTouchViewDefault;
export const BADGE_SIZE = BadgeConstants.BADGE_SIZE;
export const BADGE_SIZE_UNREAD = BadgeConstants.BADGE_SIZE_UNREAD;
export const BADGE_PADDING = BadgeConstants.BADGE_PADDING;
export const BADGE_MASK_SIZE = BadgeConstants.BADGE_MASK_SIZE;
export const BADGE_MASK_UNREAD_SIZE = BadgeConstants.BADGE_MASK_UNREAD_SIZE;
export const STANDARD_EASING = Easing.STANDARD_EASING;
export const DECELERATED_EASING = Easing.DECELERATED_EASING;
export const Spacer = SpacerDefault;
export const LiveTag = LiveTagDefault;
export const RoleDot = RoleDot.RoleDot;
export const generateBoxShadowStyle = Shadows.generateBoxShadowStyle;
export const EIGHT_DP_ELEVATION_SHADOW_PARAMS = Shadows.EIGHT_DP_ELEVATION_SHADOW_PARAMS;
export const FOUR_DP_ELEVATION_SHADOW_PARAMS = Shadows.FOUR_DP_ELEVATION_SHADOW_PARAMS;
export const EXPERIMENTAL_HIGH_ELEVATION_SHADOW_PARAMS = Shadows.EXPERIMENTAL_HIGH_ELEVATION_SHADOW_PARAMS;
export const NO_ELEVATION_SHADOW_PARAMS = Shadows.NO_ELEVATION_SHADOW_PARAMS;
export const NitroWheel = NitroWheelDefault;
export const EmptyState = EmptyStateDefault;
export const LegacyText = LegacyText_LegacyTextDefault;
export const RNTextInput = Atoms.RNTextInput;
export const Badge = Badge_BadgeDefault;
export const MaskedBadge = Badge_Badge.MaskedBadge;
export const CarouselPagination = CarouselPaginationDefault;
export const InputView = InputViewDefault;
export const ClearButtonVisibility = InputView.ClearButtonVisibility;
export const BadgeColors = Badges_Badges.BadgeColors;
export const TextBadge = Badges_Badges.TextBadge;
export const RefreshEmptyState = RefreshEmptyStateDefault;
export const ThemedEmptyState = RefreshEmptyState.ThemedEmptyState;
export const CardSection = CardSectionDefault;
export const Form = Form.Form;
export const FormArrow = Form.FormArrow;
export const FormCheckbox = Form.FormCheckbox;
export const FormCheckmark = Form.FormCheckmark;
export const FormCTA = Form.FormCTA;
export const FormCTAButton = Form.FormCTAButton;
export const FormDivider = Form.FormDivider;
export const FormHint = Form.FormHint;
export const FormIcon = Form.FormIcon;
export const FormInput = Form.FormInput;
export const FormLabel = Form.FormLabel;
export const FormRadio = Form.FormRadio;
export const FormRow = Form.FormRow;
export const FormSection = Form.FormSection;
export const FormSelect = Form.FormSelect;
export const FormSubLabel = Form.FormSubLabel;
export const FormSwitch = Form.FormSwitch;
export const FormText = Form.FormText;
export const FormTextColors = Form.FormTextColors;
export const FormTitle = Form.FormTitle;
export const FormSwitchRow = Form.FormSwitchRow;
export const FormRadioRow = Form.FormRadioRow;
export const FormCheckboxRow = Form.FormCheckboxRow;
export const FormRadioGroup = Form.FormRadioGroup;
export const FormSliderRow = Form.FormSliderRow;
export const FormCardSection = Form.FormCardSection;
export const PressableOpacity = Pressables.PressableOpacity;
export const PressableHighlight = Pressables.PressableHighlight;
export const SquareIconButton = IconButton_IconButton.SquareIconButton;
export const CircularIconButton = IconButton_IconButton.CircularIconButton;
export const TouchableHitBox = TouchableHitBoxDefault;
export const RoleLabel = RoleLabel.RoleLabel;
