// discord_app/modules/checkpoint/CheckpointCharacterAssets.tsx
import CheckpointCharacterBase from "../../../discord_common/js/shared/shared-constants/CheckpointCharacterBase.tsx";
import _modDef5148 from "../../../discord_assets/assets/checkpoint/2026/character/layer/base/icy.png.js";
import _modDef5149 from "../../../discord_assets/assets/checkpoint/2026/character/layer/base/crimson.png.js";
import _modDef5150 from "../../../discord_assets/assets/checkpoint/2026/character/layer/base/chrome.png.js";
import _modDef5151 from "../../../discord_assets/assets/checkpoint/2026/character/layer/base/galactic.png.js";
import _modDef5152 from "../../../discord_assets/assets/checkpoint/2026/character/layer/base/forest.png.js";
import _modDef5153 from "../../../discord_assets/assets/checkpoint/2026/character/layer/base/midnight.png.js";
import _modDef5154 from "../../../discord_assets/assets/checkpoint/2026/character/layer/base/cream.png.js";
import _modDef5155 from "../../../discord_assets/assets/checkpoint/2026/character/layer/base/orange.png.js";
import _modDef5156 from "../../../discord_assets/assets/checkpoint/2026/character/layer/base/purple.png.js";
import _modDef5157 from "../../../discord_assets/assets/checkpoint/2026/character/layer/base/red.png.js";
import _modDef5158 from "../../../discord_assets/assets/checkpoint/2026/character/layer/base/cobalt.png.js";
import _modDef5159 from "../../../discord_assets/assets/checkpoint/2026/character/layer/base/x_ray.png.js";
import _modDef5160 from "../../../discord_assets/assets/checkpoint/2026/character/layer/base/liquid.png.js";
import _modDef5161 from "../../../discord_assets/assets/checkpoint/2026/character/layer/base/butter.png.js";
import _modDef5162 from "../../../discord_assets/assets/checkpoint/2026/character/layer/base/iridescent.png.js";
import CheckpointCharacterShoes from "../../../discord_common/js/shared/shared-constants/CheckpointCharacterShoes.tsx";
import _modDef5164 from "../../../discord_assets/assets/checkpoint/2026/character/layer/shoes/fancy_heels.png.js";
import _modDef5165 from "../../../discord_assets/assets/checkpoint/2026/character/layer/shoes/sneakers.png.js";
import _modDef5166 from "../../../discord_assets/assets/checkpoint/2026/character/layer/shoes/socks.png.js";
import _modDef5167 from "../../../discord_assets/assets/checkpoint/2026/character/layer/shoes/wumpus_slippers.png.js";
import _modDef5168 from "../../../discord_assets/assets/checkpoint/2026/character/layer/shoes/bionic.png.js";
import _modDef5169 from "../../../discord_assets/assets/checkpoint/2026/character/layer/shoes/platforms.png.js";
import _modDef5170 from "../../../discord_assets/assets/checkpoint/2026/character/layer/shoes/western_boots.png.js";
import _modDef5171 from "../../../discord_assets/assets/checkpoint/2026/character/layer/shoes/kitty_paws.png.js";
import _modDef5172 from "../../../discord_assets/assets/checkpoint/2026/character/layer/shoes/roller_skates.png.js";
import _modDef5173 from "../../../discord_assets/assets/checkpoint/2026/character/layer/shoes/snow_shoes.png.js";
import _modDef5174 from "../../../discord_assets/assets/checkpoint/2026/character/layer/shoes/icarus_sandals.png.js";
import _modDef5175 from "../../../discord_assets/assets/checkpoint/2026/character/layer/shoes/clown.png.js";
import _modDef5176 from "../../../discord_assets/assets/checkpoint/2026/character/layer/shoes/ballet.png.js";
import _modDef5177 from "../../../discord_assets/assets/checkpoint/2026/character/layer/shoes/cyber_stompers.png.js";
import CheckpointCharacterOutfit from "../../../discord_common/js/shared/shared-constants/CheckpointCharacterOutfit.tsx";
import _modDef5179 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/baddie.png.js";
import _modDef5180 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/traveler.png.js";
import _modDef5181 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/streamer.png.js";
import _modDef5182 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/camper.png.js";
import _modDef5183 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/athlete.png.js";
import _modDef5184 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/cowpoke.png.js";
import _modDef5185 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/goth.png.js";
import _modDef5186 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/astronaut.png.js";
import _modDef5187 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/jester.png.js";
import _modDef5188 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/trash_can.png.js";
import _modDef5189 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/mage.png.js";
import _modDef5190 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/mech.png.js";
import _modDef5191 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/knight.png.js";
import _modDef5192 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/magical.png.js";
import _modDef5193 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/baddie_monochrome.png.js";
import _modDef5194 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/baddie_violet.png.js";
import _modDef5195 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/baddie_pastel.png.js";
import _modDef5196 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/baddie_sunset.png.js";
import _modDef5197 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/traveler_haze.png.js";
import _modDef5198 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/traveler_moss.png.js";
import _modDef5199 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/traveler_chrono.png.js";
import _modDef5200 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/traveler_umber.png.js";
import _modDef5201 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/streamer_flames.png.js";
import _modDef5202 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/streamer_stripes.png.js";
import _modDef5203 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/streamer_smiley.png.js";
import _modDef5204 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/streamer_vintage.png.js";
import _modDef5205 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/camper_plaid.png.js";
import _modDef5206 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/camper_swamp.png.js";
import _modDef5207 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/camper_glamp.png.js";
import _modDef5208 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/camper_amber.png.js";
import _modDef5209 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/athlete_blocked.png.js";
import _modDef5210 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/athlete_faded.png.js";
import _modDef5211 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/athlete_checkered.png.js";
import _modDef5212 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/athlete_lined.png.js";
import _modDef5213 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/cowpoke_onyx.png.js";
import _modDef5214 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/cowpoke_steel.png.js";
import _modDef5215 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/cowpoke_denim.png.js";
import _modDef5216 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/cowpoke_blush.png.js";
import _modDef5217 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/goth_siren.png.js";
import _modDef5218 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/goth_serpent.png.js";
import _modDef5219 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/goth_raven.png.js";
import _modDef5220 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/goth_vamp.png.js";
import _modDef5221 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/astronaut_stardust.png.js";
import _modDef5222 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/astronaut_martian.png.js";
import _modDef5223 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/astronaut_solar.png.js";
import _modDef5224 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/astronaut_cosmic.png.js";
import _modDef5225 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/jester_confetti.png.js";
import _modDef5226 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/jester_carnival.png.js";
import _modDef5227 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/jester_sunrise.png.js";
import _modDef5228 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/jester_nightfall.png.js";
import _modDef5229 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/trash_can_blackout.png.js";
import _modDef5230 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/trash_can_caution.png.js";
import _modDef5231 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/trash_can_bubblegum.png.js";
import _modDef5232 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/trash_can_toxic.png.js";
import _modDef5233 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/mage_shadow.png.js";
import _modDef5234 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/mage_dusk.png.js";
import _modDef5235 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/mage_wildwood.png.js";
import _modDef5236 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/mage_winter.png.js";
import _modDef5237 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/mech_aero.png.js";
import _modDef5238 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/mech_viper.png.js";
import _modDef5239 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/mech_ultraviolet.png.js";
import _modDef5240 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/mech_sandstorm.png.js";
import _modDef5241 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/knight_iron.png.js";
import _modDef5242 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/knight_rust.png.js";
import _modDef5243 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/knight_petal.png.js";
import _modDef5244 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/knight_glacier.png.js";
import _modDef5245 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/magical_sapphire.png.js";
import _modDef5246 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/magical_amethyst.png.js";
import _modDef5247 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/magical_frost.png.js";
import _modDef5248 from "../../../discord_assets/assets/checkpoint/2026/character/layer/outfit/magical_citrine.png.js";
import CheckpointCharacterFace from "../../../discord_common/js/shared/shared-constants/CheckpointCharacterFace.tsx";
import _modDef5250 from "../../../discord_assets/assets/checkpoint/2026/character/layer/face/chill.png.js";
import _modDef5251 from "../../../discord_assets/assets/checkpoint/2026/character/layer/face/cry_baby.png.js";
import _modDef5252 from "../../../discord_assets/assets/checkpoint/2026/character/layer/face/bored.png.js";
import _modDef5253 from "../../../discord_assets/assets/checkpoint/2026/character/layer/face/locked_in.png.js";
import _modDef5254 from "../../../discord_assets/assets/checkpoint/2026/character/layer/face/smitten.png.js";
import _modDef5255 from "../../../discord_assets/assets/checkpoint/2026/character/layer/face/confused.png.js";
import _modDef5256 from "../../../discord_assets/assets/checkpoint/2026/character/layer/face/anxious.png.js";
import _modDef5257 from "../../../discord_assets/assets/checkpoint/2026/character/layer/face/sparkly.png.js";
import _modDef5258 from "../../../discord_assets/assets/checkpoint/2026/character/layer/face/rage.png.js";
import _modDef5259 from "../../../discord_assets/assets/checkpoint/2026/character/layer/face/sus.png.js";
import _modDef5260 from "../../../discord_assets/assets/checkpoint/2026/character/layer/face/spellbound.png.js";
import _modDef5261 from "../../../discord_assets/assets/checkpoint/2026/character/layer/face/cursed.png.js";
import _modDef5262 from "../../../discord_assets/assets/checkpoint/2026/character/layer/face/free_fall.png.js";
import _modDef5263 from "../../../discord_assets/assets/checkpoint/2026/character/layer/face/possessed.png.js";
import _modDef5264 from "../../../discord_assets/assets/checkpoint/2026/character/layer/face/awkward.png.js";
import CheckpointCharacterHat from "../../../discord_common/js/shared/shared-constants/CheckpointCharacterHat.tsx";
import _modDef5266 from "../../../discord_assets/assets/checkpoint/2026/character/layer/hat/cap.png.js";
import _modDef5267 from "../../../discord_assets/assets/checkpoint/2026/character/layer/hat/elven_headpiece.png.js";
import _modDef5268 from "../../../discord_assets/assets/checkpoint/2026/character/layer/hat/headphones.png.js";
import _modDef5269 from "../../../discord_assets/assets/checkpoint/2026/character/layer/hat/teddy_beanie.png.js";
import _modDef5270 from "../../../discord_assets/assets/checkpoint/2026/character/layer/hat/piercings.png.js";
import _modDef5271 from "../../../discord_assets/assets/checkpoint/2026/character/layer/hat/headband.png.js";
import _modDef5272 from "../../../discord_assets/assets/checkpoint/2026/character/layer/hat/sunglasses.png.js";
import _modDef5273 from "../../../discord_assets/assets/checkpoint/2026/character/layer/hat/banana_peel.png.js";
import _modDef5274 from "../../../discord_assets/assets/checkpoint/2026/character/layer/hat/leaf.png.js";
import _modDef5275 from "../../../discord_assets/assets/checkpoint/2026/character/layer/hat/fire.png.js";
import _modDef5276 from "../../../discord_assets/assets/checkpoint/2026/character/layer/hat/halo.png.js";
import _modDef5277 from "../../../discord_assets/assets/checkpoint/2026/character/layer/hat/brain.png.js";
import _modDef5278 from "../../../discord_assets/assets/checkpoint/2026/character/layer/hat/traffic_cone.png.js";
import _modDef5279 from "../../../discord_assets/assets/checkpoint/2026/character/layer/hat/crown.png.js";
import CheckpointCharacterWearable from "../../../discord_common/js/shared/shared-constants/CheckpointCharacterWearable.tsx";
import _modDef5281 from "../../../discord_assets/assets/checkpoint/2026/character/layer/wearable/angel_wings.png.js";
import _modDef5282 from "../../../discord_assets/assets/checkpoint/2026/character/layer/wearable/stickers.png.js";
import _modDef5283 from "../../../discord_assets/assets/checkpoint/2026/character/layer/wearable/tote.png.js";
import _modDef5284 from "../../../discord_assets/assets/checkpoint/2026/character/layer/wearable/wizard_staff.png.js";
import _modDef5285 from "../../../discord_assets/assets/checkpoint/2026/character/layer/wearable/skateboard.png.js";
import _modDef5286 from "../../../discord_assets/assets/checkpoint/2026/character/layer/wearable/take_out_bag.png.js";
import _modDef5287 from "../../../discord_assets/assets/checkpoint/2026/character/layer/wearable/pixel_wrench.png.js";
import _modDef5288 from "../../../discord_assets/assets/checkpoint/2026/character/layer/wearable/mech_wings.png.js";
import _modDef5289 from "../../../discord_assets/assets/checkpoint/2026/character/layer/wearable/sword.png.js";
import _modDef5290 from "../../../discord_assets/assets/checkpoint/2026/character/layer/wearable/deviant_tail.png.js";
import _modDef5291 from "../../../discord_assets/assets/checkpoint/2026/character/layer/wearable/magical_staff.png.js";
import _modDef5292 from "../../../discord_assets/assets/checkpoint/2026/character/layer/wearable/butterfly_wings.png.js";
import _modDef5293 from "../../../discord_assets/assets/checkpoint/2026/character/layer/wearable/cat_backpack.png.js";
import _modDef5294 from "../../../discord_assets/assets/checkpoint/2026/character/layer/wearable/dragon_wings.png.js";
import CheckpointCharacterAura from "../../../discord_common/js/shared/shared-constants/CheckpointCharacterAura.tsx";
import _modDef5296 from "../../../discord_assets/assets/checkpoint/2026/character/layer/aura/blaze.png.js";
import _modDef5297 from "../../../discord_assets/assets/checkpoint/2026/character/layer/aura/blossom.png.js";
import _modDef5298 from "../../../discord_assets/assets/checkpoint/2026/character/layer/aura/prism.png.js";
import _modDef5299 from "../../../discord_assets/assets/checkpoint/2026/character/layer/aura/shock.png.js";
import _modDef5300 from "../../../discord_assets/assets/checkpoint/2026/character/layer/aura/fated.png.js";
import _modDef5301 from "../../../discord_assets/assets/checkpoint/2026/character/layer/aura/luster.png.js";
import _modDef5302 from "../../../discord_assets/assets/checkpoint/2026/character/layer/aura/bubbles.png.js";
import _modDef5303 from "../../../discord_assets/assets/checkpoint/2026/character/layer/aura/spooky.png.js";
import _modDef5304 from "../../../discord_assets/assets/checkpoint/2026/character/layer/aura/cursed.png.js";
import _modDef5305 from "../../../discord_assets/assets/checkpoint/2026/character/layer/aura/magnetic.png.js";
import _modDef5306 from "../../../discord_assets/assets/checkpoint/2026/character/layer/aura/radioactive.png.js";
import _modDef5307 from "../../../discord_assets/assets/checkpoint/2026/character/layer/aura/elemental.png.js";
import _modDef5308 from "../../../discord_assets/assets/checkpoint/2026/character/layer/aura/shimmer.png.js";
import _modDef5309 from "../../../discord_assets/assets/checkpoint/2026/character/layer/aura/witchy.png.js";
import size from "../../../_runtime/metro/00002__.js";

const obj = {};
const obj2 = { layer: _modDef5148 };
const ICY = CheckpointCharacterBase.CheckpointCharacterBase.ICY;
obj[ICY] = obj2;
const obj3 = { layer: _modDef5149 };
const CRIMSON = CheckpointCharacterBase.CheckpointCharacterBase.CRIMSON;
obj[CRIMSON] = obj3;
const obj4 = { layer: _modDef5150 };
const CHROME = CheckpointCharacterBase.CheckpointCharacterBase.CHROME;
obj[CHROME] = obj4;
const obj5 = { layer: _modDef5151 };
const GALACTIC = CheckpointCharacterBase.CheckpointCharacterBase.GALACTIC;
obj[GALACTIC] = obj5;
const obj6 = { layer: _modDef5152 };
const FOREST = CheckpointCharacterBase.CheckpointCharacterBase.FOREST;
obj[FOREST] = obj6;
const obj7 = { layer: _modDef5153 };
const MIDNIGHT = CheckpointCharacterBase.CheckpointCharacterBase.MIDNIGHT;
obj[MIDNIGHT] = obj7;
const obj8 = { layer: _modDef5154 };
const CREAM = CheckpointCharacterBase.CheckpointCharacterBase.CREAM;
obj[CREAM] = obj8;
const obj9 = { layer: _modDef5155 };
const ORANGE = CheckpointCharacterBase.CheckpointCharacterBase.ORANGE;
obj[ORANGE] = obj9;
const obj10 = { layer: _modDef5156 };
const PURPLE = CheckpointCharacterBase.CheckpointCharacterBase.PURPLE;
obj[PURPLE] = obj10;
const obj11 = { layer: _modDef5157 };
const RED = CheckpointCharacterBase.CheckpointCharacterBase.RED;
obj[RED] = obj11;
const obj12 = { layer: _modDef5158 };
const COBALT = CheckpointCharacterBase.CheckpointCharacterBase.COBALT;
obj[COBALT] = obj12;
const obj13 = { layer: _modDef5159 };
const X_RAY = CheckpointCharacterBase.CheckpointCharacterBase.X_RAY;
obj[X_RAY] = obj13;
const obj14 = { layer: _modDef5160 };
const LIQUID = CheckpointCharacterBase.CheckpointCharacterBase.LIQUID;
obj[LIQUID] = obj14;
const obj15 = { layer: _modDef5161 };
const BUTTER = CheckpointCharacterBase.CheckpointCharacterBase.BUTTER;
obj[BUTTER] = obj15;
const obj16 = { layer: _modDef5162 };
const IRIDESCENT = CheckpointCharacterBase.CheckpointCharacterBase.IRIDESCENT;
obj[IRIDESCENT] = obj16;
const obj17 = {};
const obj18 = { layer: _modDef5164 };
const FANCY_HEELS = CheckpointCharacterShoes.CheckpointCharacterShoes.FANCY_HEELS;
obj17[FANCY_HEELS] = obj18;
const obj19 = { layer: _modDef5165 };
const SNEAKERS = CheckpointCharacterShoes.CheckpointCharacterShoes.SNEAKERS;
obj17[SNEAKERS] = obj19;
const obj20 = { layer: _modDef5166 };
const SOCKS = CheckpointCharacterShoes.CheckpointCharacterShoes.SOCKS;
obj17[SOCKS] = obj20;
const obj21 = { layer: _modDef5167 };
const WUMPUS_SLIPPERS = CheckpointCharacterShoes.CheckpointCharacterShoes.WUMPUS_SLIPPERS;
obj17[WUMPUS_SLIPPERS] = obj21;
const obj22 = { layer: _modDef5168 };
const BIONIC = CheckpointCharacterShoes.CheckpointCharacterShoes.BIONIC;
obj17[BIONIC] = obj22;
const obj23 = { layer: _modDef5169 };
const PLATFORMS = CheckpointCharacterShoes.CheckpointCharacterShoes.PLATFORMS;
obj17[PLATFORMS] = obj23;
const obj24 = { layer: _modDef5170 };
const WESTERN_BOOTS = CheckpointCharacterShoes.CheckpointCharacterShoes.WESTERN_BOOTS;
obj17[WESTERN_BOOTS] = obj24;
const obj25 = { layer: _modDef5171 };
const KITTY_PAWS = CheckpointCharacterShoes.CheckpointCharacterShoes.KITTY_PAWS;
obj17[KITTY_PAWS] = obj25;
const obj26 = { layer: _modDef5172 };
const ROLLER_SKATES = CheckpointCharacterShoes.CheckpointCharacterShoes.ROLLER_SKATES;
obj17[ROLLER_SKATES] = obj26;
const obj27 = { layer: _modDef5173 };
const SNOW_SHOES = CheckpointCharacterShoes.CheckpointCharacterShoes.SNOW_SHOES;
obj17[SNOW_SHOES] = obj27;
const obj28 = { layer: _modDef5174 };
const ICARUS_SANDALS = CheckpointCharacterShoes.CheckpointCharacterShoes.ICARUS_SANDALS;
obj17[ICARUS_SANDALS] = obj28;
const obj29 = { layer: _modDef5175 };
const CLOWN = CheckpointCharacterShoes.CheckpointCharacterShoes.CLOWN;
obj17[CLOWN] = obj29;
const obj30 = { layer: _modDef5176 };
const BALLET = CheckpointCharacterShoes.CheckpointCharacterShoes.BALLET;
obj17[BALLET] = obj30;
const obj31 = { layer: _modDef5177 };
const CYBER_STOMPERS = CheckpointCharacterShoes.CheckpointCharacterShoes.CYBER_STOMPERS;
obj17[CYBER_STOMPERS] = obj31;
const obj32 = {};
const obj33 = { layer: _modDef5179 };
const BADDIE_DEFAULT = CheckpointCharacterOutfit.CheckpointCharacterOutfit.BADDIE_DEFAULT;
obj32[BADDIE_DEFAULT] = obj33;
const obj34 = { layer: _modDef5180 };
const TRAVELER_DEFAULT = CheckpointCharacterOutfit.CheckpointCharacterOutfit.TRAVELER_DEFAULT;
obj32[TRAVELER_DEFAULT] = obj34;
const obj35 = { layer: _modDef5181 };
const STREAMER_DEFAULT = CheckpointCharacterOutfit.CheckpointCharacterOutfit.STREAMER_DEFAULT;
obj32[STREAMER_DEFAULT] = obj35;
const obj36 = { layer: _modDef5182 };
const CAMPER_DEFAULT = CheckpointCharacterOutfit.CheckpointCharacterOutfit.CAMPER_DEFAULT;
obj32[CAMPER_DEFAULT] = obj36;
const obj37 = { layer: _modDef5183 };
const ATHLETE_DEFAULT = CheckpointCharacterOutfit.CheckpointCharacterOutfit.ATHLETE_DEFAULT;
obj32[ATHLETE_DEFAULT] = obj37;
const obj38 = { layer: _modDef5184 };
const COWPOKE_DEFAULT = CheckpointCharacterOutfit.CheckpointCharacterOutfit.COWPOKE_DEFAULT;
obj32[COWPOKE_DEFAULT] = obj38;
const obj39 = { layer: _modDef5185 };
const GOTH_DEFAULT = CheckpointCharacterOutfit.CheckpointCharacterOutfit.GOTH_DEFAULT;
obj32[GOTH_DEFAULT] = obj39;
const obj40 = { layer: _modDef5186 };
const ASTRONAUT_DEFAULT = CheckpointCharacterOutfit.CheckpointCharacterOutfit.ASTRONAUT_DEFAULT;
obj32[ASTRONAUT_DEFAULT] = obj40;
const obj41 = { layer: _modDef5187 };
const JESTER_DEFAULT = CheckpointCharacterOutfit.CheckpointCharacterOutfit.JESTER_DEFAULT;
obj32[JESTER_DEFAULT] = obj41;
const obj42 = { layer: _modDef5188 };
const TRASH_CAN_DEFAULT = CheckpointCharacterOutfit.CheckpointCharacterOutfit.TRASH_CAN_DEFAULT;
obj32[TRASH_CAN_DEFAULT] = obj42;
const obj43 = { layer: _modDef5189 };
const MAGE_DEFAULT = CheckpointCharacterOutfit.CheckpointCharacterOutfit.MAGE_DEFAULT;
obj32[MAGE_DEFAULT] = obj43;
const obj44 = { layer: _modDef5190 };
const MECH_DEFAULT = CheckpointCharacterOutfit.CheckpointCharacterOutfit.MECH_DEFAULT;
obj32[MECH_DEFAULT] = obj44;
const obj45 = { layer: _modDef5191 };
const KNIGHT_DEFAULT = CheckpointCharacterOutfit.CheckpointCharacterOutfit.KNIGHT_DEFAULT;
obj32[KNIGHT_DEFAULT] = obj45;
const obj46 = { layer: _modDef5192 };
const MAGICAL_DEFAULT = CheckpointCharacterOutfit.CheckpointCharacterOutfit.MAGICAL_DEFAULT;
obj32[MAGICAL_DEFAULT] = obj46;
const obj47 = { layer: _modDef5193 };
const BADDIE_MONOCHROME = CheckpointCharacterOutfit.CheckpointCharacterOutfit.BADDIE_MONOCHROME;
obj32[BADDIE_MONOCHROME] = obj47;
const obj48 = { layer: _modDef5194 };
const BADDIE_VIOLET = CheckpointCharacterOutfit.CheckpointCharacterOutfit.BADDIE_VIOLET;
obj32[BADDIE_VIOLET] = obj48;
const obj49 = { layer: _modDef5195 };
const BADDIE_PASTEL = CheckpointCharacterOutfit.CheckpointCharacterOutfit.BADDIE_PASTEL;
obj32[BADDIE_PASTEL] = obj49;
const obj50 = { layer: _modDef5196 };
const BADDIE_SUNSET = CheckpointCharacterOutfit.CheckpointCharacterOutfit.BADDIE_SUNSET;
obj32[BADDIE_SUNSET] = obj50;
const obj51 = { layer: _modDef5197 };
const TRAVELER_HAZE = CheckpointCharacterOutfit.CheckpointCharacterOutfit.TRAVELER_HAZE;
obj32[TRAVELER_HAZE] = obj51;
const obj52 = { layer: _modDef5198 };
const TRAVELER_MOSS = CheckpointCharacterOutfit.CheckpointCharacterOutfit.TRAVELER_MOSS;
obj32[TRAVELER_MOSS] = obj52;
const obj53 = { layer: _modDef5199 };
const TRAVELER_CHRONO = CheckpointCharacterOutfit.CheckpointCharacterOutfit.TRAVELER_CHRONO;
obj32[TRAVELER_CHRONO] = obj53;
const obj54 = { layer: _modDef5200 };
const TRAVELER_UMBER = CheckpointCharacterOutfit.CheckpointCharacterOutfit.TRAVELER_UMBER;
obj32[TRAVELER_UMBER] = obj54;
const obj55 = { layer: _modDef5201 };
const STREAMER_FLAMES = CheckpointCharacterOutfit.CheckpointCharacterOutfit.STREAMER_FLAMES;
obj32[STREAMER_FLAMES] = obj55;
const obj56 = { layer: _modDef5202 };
const STREAMER_STRIPES = CheckpointCharacterOutfit.CheckpointCharacterOutfit.STREAMER_STRIPES;
obj32[STREAMER_STRIPES] = obj56;
const obj57 = { layer: _modDef5203 };
const STREAMER_SMILEY = CheckpointCharacterOutfit.CheckpointCharacterOutfit.STREAMER_SMILEY;
obj32[STREAMER_SMILEY] = obj57;
const obj58 = { layer: _modDef5204 };
const STREAMER_VINTAGE = CheckpointCharacterOutfit.CheckpointCharacterOutfit.STREAMER_VINTAGE;
obj32[STREAMER_VINTAGE] = obj58;
const obj59 = { layer: _modDef5205 };
const CAMPER_PLAID = CheckpointCharacterOutfit.CheckpointCharacterOutfit.CAMPER_PLAID;
obj32[CAMPER_PLAID] = obj59;
const obj60 = { layer: _modDef5206 };
const CAMPER_SWAMP = CheckpointCharacterOutfit.CheckpointCharacterOutfit.CAMPER_SWAMP;
obj32[CAMPER_SWAMP] = obj60;
const obj61 = { layer: _modDef5207 };
const CAMPER_GLAMP = CheckpointCharacterOutfit.CheckpointCharacterOutfit.CAMPER_GLAMP;
obj32[CAMPER_GLAMP] = obj61;
const obj62 = { layer: _modDef5208 };
const CAMPER_AMBER = CheckpointCharacterOutfit.CheckpointCharacterOutfit.CAMPER_AMBER;
obj32[CAMPER_AMBER] = obj62;
const obj63 = { layer: _modDef5209 };
const ATHLETE_BLOCKED = CheckpointCharacterOutfit.CheckpointCharacterOutfit.ATHLETE_BLOCKED;
obj32[ATHLETE_BLOCKED] = obj63;
const obj64 = { layer: _modDef5210 };
const ATHLETE_FADED = CheckpointCharacterOutfit.CheckpointCharacterOutfit.ATHLETE_FADED;
obj32[ATHLETE_FADED] = obj64;
const obj65 = { layer: _modDef5211 };
const ATHLETE_CHECKERED = CheckpointCharacterOutfit.CheckpointCharacterOutfit.ATHLETE_CHECKERED;
obj32[ATHLETE_CHECKERED] = obj65;
const obj66 = { layer: _modDef5212 };
const ATHLETE_LINED = CheckpointCharacterOutfit.CheckpointCharacterOutfit.ATHLETE_LINED;
obj32[ATHLETE_LINED] = obj66;
const obj67 = { layer: _modDef5213 };
const COWPOKE_ONYX = CheckpointCharacterOutfit.CheckpointCharacterOutfit.COWPOKE_ONYX;
obj32[COWPOKE_ONYX] = obj67;
const obj68 = { layer: _modDef5214 };
const COWPOKE_STEEL = CheckpointCharacterOutfit.CheckpointCharacterOutfit.COWPOKE_STEEL;
obj32[COWPOKE_STEEL] = obj68;
const obj69 = { layer: _modDef5215 };
const COWPOKE_DENIM = CheckpointCharacterOutfit.CheckpointCharacterOutfit.COWPOKE_DENIM;
obj32[COWPOKE_DENIM] = obj69;
const obj70 = { layer: _modDef5216 };
const COWPOKE_BLUSH = CheckpointCharacterOutfit.CheckpointCharacterOutfit.COWPOKE_BLUSH;
obj32[COWPOKE_BLUSH] = obj70;
const obj71 = { layer: _modDef5217 };
const GOTH_SIREN = CheckpointCharacterOutfit.CheckpointCharacterOutfit.GOTH_SIREN;
obj32[GOTH_SIREN] = obj71;
const obj72 = { layer: _modDef5218 };
const GOTH_SERPENT = CheckpointCharacterOutfit.CheckpointCharacterOutfit.GOTH_SERPENT;
obj32[GOTH_SERPENT] = obj72;
const obj73 = { layer: _modDef5219 };
const GOTH_RAVEN = CheckpointCharacterOutfit.CheckpointCharacterOutfit.GOTH_RAVEN;
obj32[GOTH_RAVEN] = obj73;
const obj74 = { layer: _modDef5220 };
const GOTH_VAMP = CheckpointCharacterOutfit.CheckpointCharacterOutfit.GOTH_VAMP;
obj32[GOTH_VAMP] = obj74;
const obj75 = { layer: _modDef5221 };
const ASTRONAUT_STARDUST = CheckpointCharacterOutfit.CheckpointCharacterOutfit.ASTRONAUT_STARDUST;
obj32[ASTRONAUT_STARDUST] = obj75;
const obj76 = { layer: _modDef5222 };
const ASTRONAUT_MARTIAN = CheckpointCharacterOutfit.CheckpointCharacterOutfit.ASTRONAUT_MARTIAN;
obj32[ASTRONAUT_MARTIAN] = obj76;
const obj77 = { layer: _modDef5223 };
const ASTRONAUT_SOLAR = CheckpointCharacterOutfit.CheckpointCharacterOutfit.ASTRONAUT_SOLAR;
obj32[ASTRONAUT_SOLAR] = obj77;
const obj78 = { layer: _modDef5224 };
const ASTRONAUT_COSMIC = CheckpointCharacterOutfit.CheckpointCharacterOutfit.ASTRONAUT_COSMIC;
obj32[ASTRONAUT_COSMIC] = obj78;
const obj79 = { layer: _modDef5225 };
const JESTER_CONFETTI = CheckpointCharacterOutfit.CheckpointCharacterOutfit.JESTER_CONFETTI;
obj32[JESTER_CONFETTI] = obj79;
const obj80 = { layer: _modDef5226 };
const JESTER_CARNIVAL = CheckpointCharacterOutfit.CheckpointCharacterOutfit.JESTER_CARNIVAL;
obj32[JESTER_CARNIVAL] = obj80;
const obj81 = { layer: _modDef5227 };
const JESTER_SUNRISE = CheckpointCharacterOutfit.CheckpointCharacterOutfit.JESTER_SUNRISE;
obj32[JESTER_SUNRISE] = obj81;
const obj82 = { layer: _modDef5228 };
const JESTER_NIGHTFALL = CheckpointCharacterOutfit.CheckpointCharacterOutfit.JESTER_NIGHTFALL;
obj32[JESTER_NIGHTFALL] = obj82;
const obj83 = { layer: _modDef5229 };
const TRASH_CAN_BLACKOUT = CheckpointCharacterOutfit.CheckpointCharacterOutfit.TRASH_CAN_BLACKOUT;
obj32[TRASH_CAN_BLACKOUT] = obj83;
const obj84 = { layer: _modDef5230 };
const TRASH_CAN_CAUTION = CheckpointCharacterOutfit.CheckpointCharacterOutfit.TRASH_CAN_CAUTION;
obj32[TRASH_CAN_CAUTION] = obj84;
const obj85 = { layer: _modDef5231 };
const TRASH_CAN_BUBBLEGUM = CheckpointCharacterOutfit.CheckpointCharacterOutfit.TRASH_CAN_BUBBLEGUM;
obj32[TRASH_CAN_BUBBLEGUM] = obj85;
const obj86 = { layer: _modDef5232 };
const TRASH_CAN_TOXIC = CheckpointCharacterOutfit.CheckpointCharacterOutfit.TRASH_CAN_TOXIC;
obj32[TRASH_CAN_TOXIC] = obj86;
const obj87 = { layer: _modDef5233 };
const MAGE_SHADOW = CheckpointCharacterOutfit.CheckpointCharacterOutfit.MAGE_SHADOW;
obj32[MAGE_SHADOW] = obj87;
const obj88 = { layer: _modDef5234 };
const MAGE_DUSK = CheckpointCharacterOutfit.CheckpointCharacterOutfit.MAGE_DUSK;
obj32[MAGE_DUSK] = obj88;
const obj89 = { layer: _modDef5235 };
const MAGE_WILDWOOD = CheckpointCharacterOutfit.CheckpointCharacterOutfit.MAGE_WILDWOOD;
obj32[MAGE_WILDWOOD] = obj89;
const obj90 = { layer: _modDef5236 };
const MAGE_WINTER = CheckpointCharacterOutfit.CheckpointCharacterOutfit.MAGE_WINTER;
obj32[MAGE_WINTER] = obj90;
const obj91 = { layer: _modDef5237 };
const MECH_AERO = CheckpointCharacterOutfit.CheckpointCharacterOutfit.MECH_AERO;
obj32[MECH_AERO] = obj91;
const obj92 = { layer: _modDef5238 };
const MECH_VIPER = CheckpointCharacterOutfit.CheckpointCharacterOutfit.MECH_VIPER;
obj32[MECH_VIPER] = obj92;
const obj93 = { layer: _modDef5239 };
const MECH_ULTRAVIOLET = CheckpointCharacterOutfit.CheckpointCharacterOutfit.MECH_ULTRAVIOLET;
obj32[MECH_ULTRAVIOLET] = obj93;
const obj94 = { layer: _modDef5240 };
const MECH_SANDSTORM = CheckpointCharacterOutfit.CheckpointCharacterOutfit.MECH_SANDSTORM;
obj32[MECH_SANDSTORM] = obj94;
const obj95 = { layer: _modDef5241 };
const KNIGHT_IRON = CheckpointCharacterOutfit.CheckpointCharacterOutfit.KNIGHT_IRON;
obj32[KNIGHT_IRON] = obj95;
const obj96 = { layer: _modDef5242 };
const KNIGHT_RUST = CheckpointCharacterOutfit.CheckpointCharacterOutfit.KNIGHT_RUST;
obj32[KNIGHT_RUST] = obj96;
const obj97 = { layer: _modDef5243 };
const KNIGHT_PETAL = CheckpointCharacterOutfit.CheckpointCharacterOutfit.KNIGHT_PETAL;
obj32[KNIGHT_PETAL] = obj97;
const obj98 = { layer: _modDef5244 };
const KNIGHT_GLACIER = CheckpointCharacterOutfit.CheckpointCharacterOutfit.KNIGHT_GLACIER;
obj32[KNIGHT_GLACIER] = obj98;
const obj99 = { layer: _modDef5245 };
const MAGICAL_SAPPHIRE = CheckpointCharacterOutfit.CheckpointCharacterOutfit.MAGICAL_SAPPHIRE;
obj32[MAGICAL_SAPPHIRE] = obj99;
const obj100 = { layer: _modDef5246 };
const MAGICAL_AMETHYST = CheckpointCharacterOutfit.CheckpointCharacterOutfit.MAGICAL_AMETHYST;
obj32[MAGICAL_AMETHYST] = obj100;
const obj101 = { layer: _modDef5247 };
const MAGICAL_FROST = CheckpointCharacterOutfit.CheckpointCharacterOutfit.MAGICAL_FROST;
obj32[MAGICAL_FROST] = obj101;
const obj102 = { layer: _modDef5248 };
const MAGICAL_CITRINE = CheckpointCharacterOutfit.CheckpointCharacterOutfit.MAGICAL_CITRINE;
obj32[MAGICAL_CITRINE] = obj102;
const obj103 = {};
const obj104 = { layer: _modDef5250 };
const CHILL = CheckpointCharacterFace.CheckpointCharacterFace.CHILL;
obj103[CHILL] = obj104;
const obj105 = { layer: _modDef5251 };
const CRY_BABY = CheckpointCharacterFace.CheckpointCharacterFace.CRY_BABY;
obj103[CRY_BABY] = obj105;
const obj106 = { layer: _modDef5252 };
const BORED = CheckpointCharacterFace.CheckpointCharacterFace.BORED;
obj103[BORED] = obj106;
const obj107 = { layer: _modDef5253 };
const LOCKED_IN = CheckpointCharacterFace.CheckpointCharacterFace.LOCKED_IN;
obj103[LOCKED_IN] = obj107;
const obj108 = { layer: _modDef5254 };
const SMITTEN = CheckpointCharacterFace.CheckpointCharacterFace.SMITTEN;
obj103[SMITTEN] = obj108;
const obj109 = { layer: _modDef5255 };
const CONFUSED = CheckpointCharacterFace.CheckpointCharacterFace.CONFUSED;
obj103[CONFUSED] = obj109;
const obj110 = { layer: _modDef5256 };
const ANXIOUS = CheckpointCharacterFace.CheckpointCharacterFace.ANXIOUS;
obj103[ANXIOUS] = obj110;
const obj111 = { layer: _modDef5257 };
const SPARKLY = CheckpointCharacterFace.CheckpointCharacterFace.SPARKLY;
obj103[SPARKLY] = obj111;
const obj112 = { layer: _modDef5258 };
const RAGE = CheckpointCharacterFace.CheckpointCharacterFace.RAGE;
obj103[RAGE] = obj112;
const obj113 = { layer: _modDef5259 };
const SUS = CheckpointCharacterFace.CheckpointCharacterFace.SUS;
obj103[SUS] = obj113;
const obj114 = { layer: _modDef5260 };
const SPELLBOUND = CheckpointCharacterFace.CheckpointCharacterFace.SPELLBOUND;
obj103[SPELLBOUND] = obj114;
const obj115 = { layer: _modDef5261 };
const CURSED = CheckpointCharacterFace.CheckpointCharacterFace.CURSED;
obj103[CURSED] = obj115;
const obj116 = { layer: _modDef5262 };
const FREE_FALL = CheckpointCharacterFace.CheckpointCharacterFace.FREE_FALL;
obj103[FREE_FALL] = obj116;
const obj117 = { layer: _modDef5263 };
const POSSESSED = CheckpointCharacterFace.CheckpointCharacterFace.POSSESSED;
obj103[POSSESSED] = obj117;
const obj118 = { layer: _modDef5264 };
const AWKWARD = CheckpointCharacterFace.CheckpointCharacterFace.AWKWARD;
obj103[AWKWARD] = obj118;
const obj119 = {};
const obj120 = { layer: _modDef5266 };
const CAP = CheckpointCharacterHat.CheckpointCharacterHat.CAP;
obj119[CAP] = obj120;
const obj121 = { layer: _modDef5267 };
const ELVEN_HEADPIECE = CheckpointCharacterHat.CheckpointCharacterHat.ELVEN_HEADPIECE;
obj119[ELVEN_HEADPIECE] = obj121;
const obj122 = { layer: _modDef5268 };
const HEADPHONES = CheckpointCharacterHat.CheckpointCharacterHat.HEADPHONES;
obj119[HEADPHONES] = obj122;
const obj123 = { layer: _modDef5269 };
const TEDDY_BEANIE = CheckpointCharacterHat.CheckpointCharacterHat.TEDDY_BEANIE;
obj119[TEDDY_BEANIE] = obj123;
const obj124 = { layer: _modDef5270 };
const PIERCINGS = CheckpointCharacterHat.CheckpointCharacterHat.PIERCINGS;
obj119[PIERCINGS] = obj124;
const obj125 = { layer: _modDef5271 };
const HEADBAND = CheckpointCharacterHat.CheckpointCharacterHat.HEADBAND;
obj119[HEADBAND] = obj125;
const obj126 = { layer: _modDef5272 };
const SUNGLASSES = CheckpointCharacterHat.CheckpointCharacterHat.SUNGLASSES;
obj119[SUNGLASSES] = obj126;
const obj127 = { layer: _modDef5273 };
const BANANA_PEEL = CheckpointCharacterHat.CheckpointCharacterHat.BANANA_PEEL;
obj119[BANANA_PEEL] = obj127;
const obj128 = { layer: _modDef5274 };
const LEAF = CheckpointCharacterHat.CheckpointCharacterHat.LEAF;
obj119[LEAF] = obj128;
const obj129 = { layer: _modDef5275 };
const FIRE = CheckpointCharacterHat.CheckpointCharacterHat.FIRE;
obj119[FIRE] = obj129;
const obj130 = { layer: _modDef5276 };
const HALO = CheckpointCharacterHat.CheckpointCharacterHat.HALO;
obj119[HALO] = obj130;
const obj131 = { layer: _modDef5277 };
const BRAIN = CheckpointCharacterHat.CheckpointCharacterHat.BRAIN;
obj119[BRAIN] = obj131;
const obj132 = { layer: _modDef5278 };
const TRAFFIC_CONE = CheckpointCharacterHat.CheckpointCharacterHat.TRAFFIC_CONE;
obj119[TRAFFIC_CONE] = obj132;
const obj133 = { layer: _modDef5279 };
const CROWN = CheckpointCharacterHat.CheckpointCharacterHat.CROWN;
obj119[CROWN] = obj133;
const obj134 = {};
const obj135 = { layer: _modDef5281 };
const ANGEL_WINGS = CheckpointCharacterWearable.CheckpointCharacterWearable.ANGEL_WINGS;
obj134[ANGEL_WINGS] = obj135;
const obj136 = { layer: _modDef5282 };
const STICKERS = CheckpointCharacterWearable.CheckpointCharacterWearable.STICKERS;
obj134[STICKERS] = obj136;
const obj137 = { layer: _modDef5283 };
const TOTE = CheckpointCharacterWearable.CheckpointCharacterWearable.TOTE;
obj134[TOTE] = obj137;
const obj138 = { layer: _modDef5284 };
const WIZARD_STAFF = CheckpointCharacterWearable.CheckpointCharacterWearable.WIZARD_STAFF;
obj134[WIZARD_STAFF] = obj138;
const obj139 = { layer: _modDef5285 };
const SKATEBOARD = CheckpointCharacterWearable.CheckpointCharacterWearable.SKATEBOARD;
obj134[SKATEBOARD] = obj139;
const obj140 = { layer: _modDef5286 };
const TAKE_OUT_BAG = CheckpointCharacterWearable.CheckpointCharacterWearable.TAKE_OUT_BAG;
obj134[TAKE_OUT_BAG] = obj140;
const obj141 = { layer: _modDef5287 };
const PIXEL_WRENCH = CheckpointCharacterWearable.CheckpointCharacterWearable.PIXEL_WRENCH;
obj134[PIXEL_WRENCH] = obj141;
const obj142 = { layer: _modDef5288 };
const MECH_WINGS = CheckpointCharacterWearable.CheckpointCharacterWearable.MECH_WINGS;
obj134[MECH_WINGS] = obj142;
const obj143 = { layer: _modDef5289 };
const SWORD = CheckpointCharacterWearable.CheckpointCharacterWearable.SWORD;
obj134[SWORD] = obj143;
const obj144 = { layer: _modDef5290 };
const DEVIANT_TAIL = CheckpointCharacterWearable.CheckpointCharacterWearable.DEVIANT_TAIL;
obj134[DEVIANT_TAIL] = obj144;
const obj145 = { layer: _modDef5291 };
const MAGICAL_STAFF = CheckpointCharacterWearable.CheckpointCharacterWearable.MAGICAL_STAFF;
obj134[MAGICAL_STAFF] = obj145;
const obj146 = { layer: _modDef5292 };
const BUTTERFLY_WINGS = CheckpointCharacterWearable.CheckpointCharacterWearable.BUTTERFLY_WINGS;
obj134[BUTTERFLY_WINGS] = obj146;
const obj147 = { layer: _modDef5293 };
const CAT_BACKPACK = CheckpointCharacterWearable.CheckpointCharacterWearable.CAT_BACKPACK;
obj134[CAT_BACKPACK] = obj147;
const obj148 = { layer: _modDef5294 };
const DRAGON_WINGS = CheckpointCharacterWearable.CheckpointCharacterWearable.DRAGON_WINGS;
obj134[DRAGON_WINGS] = obj148;
const obj149 = {};
const obj150 = { layer: _modDef5296 };
const BLAZE = CheckpointCharacterAura.CheckpointCharacterAura.BLAZE;
obj149[BLAZE] = obj150;
const obj151 = { layer: _modDef5297 };
const BLOSSOM = CheckpointCharacterAura.CheckpointCharacterAura.BLOSSOM;
obj149[BLOSSOM] = obj151;
const obj152 = { layer: _modDef5298 };
const PRISM = CheckpointCharacterAura.CheckpointCharacterAura.PRISM;
obj149[PRISM] = obj152;
const obj153 = { layer: _modDef5299 };
const SHOCK = CheckpointCharacterAura.CheckpointCharacterAura.SHOCK;
obj149[SHOCK] = obj153;
const obj154 = { layer: _modDef5300 };
const FATED = CheckpointCharacterAura.CheckpointCharacterAura.FATED;
obj149[FATED] = obj154;
const obj155 = { layer: _modDef5301 };
const LUSTER = CheckpointCharacterAura.CheckpointCharacterAura.LUSTER;
obj149[LUSTER] = obj155;
const obj156 = { layer: _modDef5302 };
const BUBBLES = CheckpointCharacterAura.CheckpointCharacterAura.BUBBLES;
obj149[BUBBLES] = obj156;
const obj157 = { layer: _modDef5303 };
const SPOOKY = CheckpointCharacterAura.CheckpointCharacterAura.SPOOKY;
obj149[SPOOKY] = obj157;
const obj158 = { layer: _modDef5304 };
const CURSED2 = CheckpointCharacterAura.CheckpointCharacterAura.CURSED;
obj149[CURSED2] = obj158;
const obj159 = { layer: _modDef5305 };
const MAGNETIC = CheckpointCharacterAura.CheckpointCharacterAura.MAGNETIC;
obj149[MAGNETIC] = obj159;
const obj160 = { layer: _modDef5306 };
const RADIOACTIVE = CheckpointCharacterAura.CheckpointCharacterAura.RADIOACTIVE;
obj149[RADIOACTIVE] = obj160;
const obj161 = { layer: _modDef5307 };
const ELEMENTAL = CheckpointCharacterAura.CheckpointCharacterAura.ELEMENTAL;
obj149[ELEMENTAL] = obj161;
const obj162 = { layer: _modDef5308 };
const SHIMMER = CheckpointCharacterAura.CheckpointCharacterAura.SHIMMER;
obj149[SHIMMER] = obj162;
const obj163 = { layer: _modDef5309 };
const WITCHY = CheckpointCharacterAura.CheckpointCharacterAura.WITCHY;
obj149[WITCHY] = obj163;
const result = size.fileFinishedImporting("modules/checkpoint/CheckpointCharacterAssets.tsx");

export const CHARACTER_BASE_TRAIT_ASSETS = obj;
export const CHARACTER_SHOES_TRAIT_ASSETS = obj17;
export const CHARACTER_OUTFIT_TRAIT_ASSETS = obj32;
export const CHARACTER_FACE_TRAIT_ASSETS = obj103;
export const CHARACTER_HAT_TRAIT_ASSETS = obj119;
export const CHARACTER_WEARABLE_TRAIT_ASSETS = obj134;
export const CHARACTER_AURA_TRAIT_ASSETS = obj149;
