// discord_app/modules/guild_role_subscriptions/native/manage_subscriptions/ResubscribedAlert.tsx
import "noop";
import get_ActivityIndicator from "get ActivityIndicator";
import jsxProd from "jsxProd";
import createCacheKey from "createCacheKey";
import { registerAsset } from "../../../../../_runtime/14520_registerAsset.js";
import { componentDidMount } from "../../../../components_native/common/Alert.tsx";
import { Text } from "../../../../design/components/Text/native/Text.tsx";
import { Button } from "../../../../design/void/native.tsx";
import { getSystemLocale } from "../../../../intl/index.native.tsx";

let c3;
let c4;
let c5;
let closure_6;
const require = arg1;
({ View: c3, Image: c4 } = get_ActivityIndicator);
({ jsx: c5, jsxs: closure_6 } = jsxProd);
createCacheKey = { container: null, body: null, centerText: null, headerImage: null };
createCacheKey = { backgroundColor: require("Themes").colors.BACKGROUND_MOD_NORMAL };
createCacheKey[0] = createCacheKey;
createCacheKey[1] = { alignItems: "center", textAlign: "center" };
createCacheKey[2] = { textAlign: "center" };
createCacheKey[3] = { width: 87, height: 87 };
createCacheKey = createCacheKey.createStyles(createCacheKey);
const result = require("jsxProd").fileFinishedImporting("modules/guild_role_subscriptions/native/manage_subscriptions/ResubscribedAlert.tsx");

export default function ResubscribedAlert(onClose) {
  const tmp = createCacheKey();
  let obj = { confirmText: null, onConfirm: null, style: null, children: null };
  const intl = getSystemLocale.intl;
  obj[0] = intl.string(getSystemLocale.t["NX+WJN"]);
  obj[1] = onClose.onClose;
  obj[2] = tmp.container;
  obj = { style: tmp.body, children: null };
  obj = { source: registerAsset, style: tmp.headerImage };
  const items = [callback(closure_4, obj), callback(Button.Spacer, { size: 27 }), , , ];
  const obj1 = { variant: "text-lg/semibold", color: "mobile-text-heading-primary", style: tmp.centerText, children: null };
  const intl2 = getSystemLocale.intl;
  obj1[3] = intl2.string(getSystemLocale.t.oPV2cy);
  items[2] = callback(Text.Text, obj1);
  items[3] = callback(Button.Spacer, { size: 12 });
  const obj2 = { variant: "text-md/normal", color: "mobile-text-heading-primary", style: tmp.centerText, children: null };
  const intl3 = getSystemLocale.intl;
  obj2[3] = intl3.string(getSystemLocale.t.DdRizV);
  items[4] = callback(Text.Text, obj2);
  obj[1] = items;
  obj[3] = callback2(closure_3, obj);
  return callback(componentDidMount, obj);
};