// discord_app/modules/guild_profile/native/components/GuildProfileLoadingError.tsx
import noopAll from "../../../../../_runtime/00019_noop.js";
import ThemesDefault from "../../../../../discord_common/js/packages/tokens/native.tsx";
import getSystemLocale from "../../../../intl/index.native.tsx";
import map from "../../../../design/tokens/native/useToken.tsx";
import useThemeDefault from "../../../../hooks/useTheme.tsx";
import Text from "../../../../design/components/Text/native/Text.tsx";
import LinearGradientDefault from "../../../../../_runtime/04940_LinearGradient.js";
import PressableBase from "../../../../design/void/Pressables/native/Pressables.tsx";
import WarningIcon from "../../../../design/components/Icon/native/redesign/generated/WarningIcon.tsx";
import GuildProfileBackground from "GuildProfileView.tsx";
import { View } from "../../../../../_runtime/00017_get_ActivityIndicator.js";
import jsxProd from "../../../../../_runtime/react/00021_jsxProd.js";

require = arg1;
noopAll;
({ jsx: c4, jsxs: c5 } = jsxProd);
const result = require("set").fileFinishedImporting("modules/guild_profile/native/components/GuildProfileLoadingError.tsx");

export default function GuildProfileLoadingError(onPress) {
  let obj = GuildProfileBackground;
  const styles = obj.useStyles();
  obj1 = map;
  obj = { style: styles.container, children: null };
  const token = obj1.useToken(ThemesDefault.colors.BACKGROUND_BASE_LOWEST);
  obj = { style: styles.colorBanner, start: null, end: null, colors: null };
  const tmp2 = useThemeDefault();
  obj[1] = GuildProfileBackground.DiagonalGradient.START;
  obj[2] = GuildProfileBackground.DiagonalGradient.END;
  let obj4 = GuildProfileBackground;
  obj[3] = obj4.getBackgroundForProfile(tmp2, token);
  const items = [callback(LinearGradientDefault, obj), , ];
  obj1 = { style: styles.header, children: null };
  const obj2 = { style: styles.avatarBackground, children: null };
  const obj3 = { style: styles.avatarBackground, children: null };
  obj4 = { size: "lg", color: ThemesDefault.colors.TEXT_FEEDBACK_WARNING };
  obj3[1] = callback(WarningIcon.WarningIcon, obj4);
  obj2[1] = callback(View, obj3);
  obj1[1] = callback(View, obj2);
  items[1] = callback(View, obj1);
  const obj5 = { style: styles.body, children: null };
  const obj6 = { variant: "heading-lg/semibold", color: "mobile-text-heading-primary", children: null };
  const intl = getSystemLocale.intl;
  obj6[2] = intl.string(getSystemLocale.t.DmIUGK);
  const items1 = [callback(Text.Text, obj6), ];
  const obj7 = { style: styles.error, onPress: onPress.onRetry, accessibilityRole: "button", accessibilityLabel: null, children: null };
  const intl2 = getSystemLocale.intl;
  obj7[3] = intl2.string(getSystemLocale.t.s1fAEw);
  const tmp4 = LinearGradientDefault;
  const items2 = [callback(WarningIcon.WarningIcon, { size: "sm", color: ThemesDefault.colors.TEXT_FEEDBACK_WARNING }), ];
  const obj9 = { variant: "text-sm/normal", color: "text-feedback-warning", children: null };
  const intl3 = getSystemLocale.intl;
  obj9[2] = intl3.string(getSystemLocale.t.tmGHjc);
  items2[1] = callback(Text.Text, obj9);
  obj7[4] = items2;
  items1[1] = callback2(PressableBase.PressableOpacity, obj7);
  obj5[1] = items1;
  items[2] = callback2(View, obj5);
  obj[1] = items;
  return callback2(View, obj);
};