import { SafeAreaPaddingView } from "../../../../../../components_native/common/SafeAreaView.tsx";
import { Button } from "../../../../../../design/components/Button/native/Button.native.tsx";
import { Text } from "../../../../../../design/components/Text/native/Text.tsx";
import { getSystemLocale } from "../../../../../../intl/index.native.tsx";
import { styles } from "../TwoWayLinkStyles.tsx";
// discord_app/modules/user_settings/connections/native/two_way_link/playstation/PlayStationLinkSuccess.tsx
import noop from "noop";
import get_ActivityIndicator from "get ActivityIndicator";
import jsxProd from "jsxProd";
import createCacheKey from "createCacheKey";

let c4;
let c5;
let closure_6;
let error;
const require = arg1;
({ Image: c4, View: c5 } = get_ActivityIndicator);
({ jsx: closure_6, jsxs: error } = jsxProd);
let closure_8 = createCacheKey.createStyles({ image: { width: 124, height: 160, marginBottom: 24 } });
const result = require("jsxProd").fileFinishedImporting("modules/user_settings/connections/native/two_way_link/playstation/PlayStationLinkSuccess.tsx");

export const PlayStationLinkSuccess = function PlayStationLinkSuccess(onClose) {
  let obj = styles /* styles */;
  const twoWayLinkStyles = obj.useTwoWayLinkStyles();
  obj = { style: twoWayLinkStyles.container, children: null };
  obj = { style: twoWayLinkStyles.content, children: null };
  const tmp = callback3();
  const items = [callback(closure_4, { source: React.useMemo(() => ({ uri: callback(table[5]) }), []), style: callback3().image }), , ];
  const obj2 = { variant: "heading-xl/extrabold", color: "mobile-text-heading-primary", style: twoWayLinkStyles.title, children: null };
  const intl = getSystemLocale /* getSystemLocale */.intl;
  obj2[3] = intl.string(getSystemLocale /* getSystemLocale */.t.e6SOl0);
  items[1] = callback(Text /* Text */.Text, obj2);
  const obj3 = { variant: "text-md/normal", color: "text-default", style: twoWayLinkStyles.body, children: null };
  const intl2 = getSystemLocale /* getSystemLocale */.intl;
  obj3[3] = intl2.string(getSystemLocale /* getSystemLocale */.t.QjAZAQ);
  items[2] = callback(Text /* Text */.Text, obj3);
  obj[1] = items;
  const items1 = [callback2(closure_5, obj), ];
  const obj4 = { bottom: true, style: twoWayLinkStyles.footerContainer, children: null };
  const obj5 = { style: twoWayLinkStyles.footerButton, children: null };
  const obj6 = { size: "md", text: null, onPress: null };
  const intl3 = getSystemLocale /* getSystemLocale */.intl;
  obj6[1] = intl3.string(getSystemLocale /* getSystemLocale */.t.i4jeWR);
  obj6[2] = onClose.onClose;
  obj5[1] = callback(Button /* Button */.Button, obj6);
  obj4[2] = callback(closure_5, obj5);
  items1[1] = callback(SafeAreaPaddingView /* SafeAreaPaddingView */.SafeAreaPaddingView, obj4);
  obj[1] = items1;
  return callback2(closure_5, obj);
};