// === Module 9049: ClearAllIncomingRequestsConfirmation ===

// Module 9049 (ClearAllIncomingRequestsConfirmation)
import nativeDefault from "native" /* 576 */;
import util from "util" /* 1114 */;
import ToastUtils from "ToastUtils" /* 4258 */;
import ModalActionCreatorsDefault from "ModalActionCreators" /* 4763 */;
import RelationshipActionCreatorsDefault from "RelationshipActionCreators" /* 9042 */;
import _slicedToArray from "module_32" /* 32 */;
import noop from "module_19" /* 19 */;

require = fn;
get_ActivityIndicator = fn(17);
({ View: hasOwnProperty, ScrollView: metroRequire } = get_ActivityIndicator);
const jsxProd = fn(21);
({ jsx: closure_7, Fragment: closure_8, jsxs: closure_9 } = jsxProd);
fn(4560);
let createStyles = { root: null, closeButton: null, content: null, container: null, footer: null, header: null, headerText: null, body: null, noticeHeader: null, buttonWrapper: null };
createStyles = { display: "flex", flexDirection: "column", backgroundColor: nativeDefault.colors.BACKGROUND_BASE_LOW, height: "100%", paddingTop: nativeDefault.space.PX_24 };
createStyles.root = createStyles;
createStyles.closeButton = { marginRight: 8, alignSelf: "flex-end" };
createStyles.content = { flexGrow: 1, padding: nativeDefault.space.PX_16 };
let obj1 = { flexGrow: 1, padding: nativeDefault.space.PX_16 };
createStyles.container = { display: "flex", flexDirection: "column", height: "100%", marginTop: nativeDefault.space.PX_24 };
let obj2 = { display: "flex", flexDirection: "column", height: "100%", marginTop: nativeDefault.space.PX_24 };
createStyles.footer = { flexGrow: 0, flexShrink: 1, backgroundColor: nativeDefault.colors.BORDER_SUBTLE, paddingVertical: nativeDefault.space.PX_24, paddingHorizontal: nativeDefault.space.PX_16 };
let obj3 = { flexGrow: 0, flexShrink: 1, backgroundColor: nativeDefault.colors.BORDER_SUBTLE, paddingVertical: nativeDefault.space.PX_24, paddingHorizontal: nativeDefault.space.PX_16 };
createStyles.header = { display: "flex", alignItems: "center", justifyContent: "center", marginBottom: nativeDefault.space.PX_16 };
let obj4 = { display: "flex", alignItems: "center", justifyContent: "center", marginBottom: nativeDefault.space.PX_16 };
createStyles.headerText = { marginTop: nativeDefault.space.PX_16, marginBottom: nativeDefault.space.PX_4 };
let obj5 = { marginTop: nativeDefault.space.PX_16, marginBottom: nativeDefault.space.PX_4 };
createStyles.body = { padding: nativeDefault.space.PX_24, borderRadius: nativeDefault.radii.md, backgroundColor: nativeDefault.colors.BACKGROUND_SURFACE_HIGH };
let obj6 = { padding: nativeDefault.space.PX_24, borderRadius: nativeDefault.radii.md, backgroundColor: nativeDefault.colors.BACKGROUND_SURFACE_HIGH };
createStyles.noticeHeader = { marginBottom: nativeDefault.space.PX_4 };
let obj7 = { marginBottom: nativeDefault.space.PX_4 };
createStyles.buttonWrapper = { marginBottom: nativeDefault.space.PX_4 };
let closure_10 = createStyles.createStyles(createStyles);
const size = fn(2);
let result = size.fileFinishedImporting("modules/people/native/ClearAllIncomingRequestsConfirmation.tsx");

export default function ClearAllIncomingRequestsConfirmationModal(incomingRequestCount) {
  _require = undefined;
  const tmp = closure_10();
  [tmp3, c0] = _slicedToArray(noop.useState(false), 2);
  const callback = noop.useCallback(() => {
    _undefined(false);
    let arr = ModalActionCreatorsDefault;
    arr = arr.pop();
  }, []);
  const callback1 = noop.useCallback(() => {
    _undefined(false);
    const intl = util.intl;
    ToastUtils.presentFailedToast(intl.string(util.t.R0RpRX));
  }, []);
  const items = [callback, callback1];
  const callback2 = noop.useCallback(() => {
    _undefined(true);
    const result = RelationshipActionCreatorsDefault.clearPendingRelationships();
    result.then(callback).catch(callback1);
  }, items);
  let obj = { top: true, children: null };
  obj = { style: tmp.root, children: null };
  obj = { accessibilityRole: "button", accessibilityLabel: null, source: null, style: null, onPress: null };
  const tmp2 = _slicedToArray(noop.useState(false), 2);
  let intl = require("util").intl;
  obj.accessibilityLabel = intl.string(require("util").t.cpT0Cq);
  obj.source = callback(callback1[12]);
  const items1 = [tmp.closeButton];
  obj.style = items1;
  obj.onPress = function onPress() {
    return callback(callback1[6]).pop();
  };
  const items2 = [closure_7(callback(callback1[11]), obj), ];
  const obj1 = { style: tmp.container, children: null };
  const obj2 = { style: tmp.content, children: null };
  const obj3 = { children: null };
  const obj4 = { style: tmp.header, children: null };
  const obj5 = { style: tmp.headerText, variant: "text-lg/bold", children: null };
  const intl2 = require("util").intl;
  obj5.children = intl2.string(require("util").t.eVjfAu);
  obj4.children = closure_7(require("Text/Text").Text, obj5);
  const items3 = [closure_7(closure_5, obj4), ];
  const obj6 = { style: tmp.body, children: null };
  const obj7 = { style: tmp.noticeHeader, variant: "text-xs/normal", color: "mobile-text-heading-primary", children: null };
  const intl3 = require("util").intl;
  obj7.children = intl3.format(require("util").t.jaXsA3, { incomingRequestCount: incomingRequestCount.incomingPendingRequestCount });
  obj6.children = closure_7(require("Text/Text").Text, obj7);
  items3[1] = closure_7(closure_5, obj6);
  obj3.children = items3;
  obj2.children = closure_9(closure_8, obj3);
  const items4 = [closure_7(closure_6, obj2), ];
  const obj8 = { style: tmp.footer, children: null };
  const obj9 = { bottom: true, children: null };
  const obj10 = { children: null };
  const obj11 = { style: tmp.buttonWrapper, children: null };
  const obj12 = { disabled: tmp3, loading: tmp3, variant: "destructive", size: "md", text: null, onPress: null, grow: true };
  const intl4 = require("util").intl;
  obj12.text = intl4.string(require("util").t.Eq9seb);
  obj12.onPress = callback2;
  obj11.children = closure_7(require("components/Button/Button").Button, obj12);
  const items5 = [closure_7(closure_5, obj11), ];
  const obj13 = { style: tmp.buttonWrapper, children: null };
  const obj14 = { variant: "secondary", size: "md", text: null, onPress: null, grow: true };
  const intl5 = require("util").intl;
  obj14.text = intl5.string(require("util").t["ETE/oC"]);
  obj14.onPress = callback(callback1[6]).pop;
  obj13.children = closure_7(require("components/Button/Button").Button, obj14);
  items5[1] = closure_7(closure_5, obj13);
  obj10.children = items5;
  obj9.children = closure_9(closure_8, obj10);
  obj8.children = closure_7(require("common/SafeAreaView").SafeAreaPaddingView, obj9);
  items4[1] = closure_7(closure_5, obj8);
  obj1.children = items4;
  items2[1] = closure_9(closure_5, obj1);
  obj.children = items2;
  obj.children = closure_9(closure_5, obj);
  return closure_7(require("common/SafeAreaView").SafeAreaPaddingView, obj);
};